### PR TITLE
Add "no-ticks" and vertical "no-ticks" appearances for RangeWidget

### PR DESCRIPTION
**Pull request by grzesiek2010**

### CODE REVIEW

**Comment by mmarciniak90** [comment]
Tested with success on Android: 4.1, 4.2, 4.4, 5.1, 6.0
Verified : 
* vertical no-ticks decimal
* vertical no-ticks integer
* horizontal no-ticks decimal
* horizontal no-ticks integer
screenshot_2017-07-03-12-57-54
screenshot_2017-07-03-13-01-33

**Comment by lognaturel** [comment]
Over on the spec side of things, we had discussed using pseudocode such as [this](https://github.com/opendatakit/xforms-spec/issues/111#issuecomment-299275326) to represent appearances. The current approach in the code is stricter and means that `no-ticks vertical` (as opposed to `vertical no-ticks`) would end up showing a horizontal range with ticks. @grzesiek2010 what do you think of that pseudocode? Is there another way we can give users a bit more flexibility?

**Comment by grzesiek2010** [comment]
@lognaturel I impreved it and now it's more flexible as you wanted.
You can test this form: 
[range .txt](https://github.com/opendatakit/collect/files/1127308/range.txt)

**Comment by lognaturel** [comment]
One high-level thing. It now occurs to me that it would be good to support `null` values for this widget if possible. The documentation could highly encourage form designers to set a default value so they're explicitly deciding where the slider handle starts rather than it always starting in the middle. Can you please see about supporting `null`?

I'm happy with how the horizontal slider is looking and working with and without ticks. The vertical slider has a few issues:

- Height: I know vertical elements are always much harder to size! Is there some kind of constraint or dynamically resizing container you can use to take up the whole available vertical space? I think it's too short right now to be very useful.

- It's not clear which numbers are bounds and which is the value being chosen. What about putting the bounds to the right of the slider and the selected value to the left? That would be exactly what you have for the horizontal slider but flipped vertically. 😊

And an implementation question. To get ticks vs no ticks, the layouts have two `SeekBar`s that are shown or hidden depending on whether or not there should be ticks. Did you consider any other alternatives? It would be good to get a description of how you decided it's the best approach.

**Comment by grzesiek2010** [comment]
@lognaturel 

> Height: I know vertical elements are always much harder to size! Is there some kind of constraint or dynamically resizing container you can use to take up the whole available vertical space? I think it's too short right now to be very useful.

I just increased the height value so now the seekBar is longer.

> It's not clear which numbers are bounds and which is the value being chosen. What about putting the bounds to the right of the slider and the selected value to the left? That would be exactly what you have for the horizontal slider but flipped vertically

Done.

> And an implementation question. To get ticks vs no ticks, the layouts have two SeekBars that are shown or hidden depending on whether or not there should be ticks. Did you consider any other alternatives? It would be good to get a description of how you decided it's the best approach.

Yes I was trying to create the seekBar programmatically using an appropriate style
`new SeekBar(this, null, R.style.Widget_AppCompat_SeekBar_Discrete)` if needed and `new SeekBar(this)` otherwise and then inflate it but I wasn't able to get one with ticks (it doesn't work). So I decided to do that in that way.  

> One high-level thing. It now occurs to me that it would be good to support null values for this widget if possible. The documentation could highly encourage form designers to set a default value so they're explicitly deciding where the slider handle starts rather than it always starting in the middle. Can you please see about supporting null?

I'm not sure about it, even if we want to implement that we should do that in a separate pull request as it's related to entire widget not only to `no-ticks` appearance. I'll create a separate issue for that.

**Comment by lognaturel** [comment]
Let's start with the fixed height it is now and solicit some feedback on how people use it. We may find it could be styled and scaled differently to better match how it's used.

I see a couple of issues which I will file separately.

**Pull request merged**
