### PR TITLE
Pull out cardinal direction strings so they can be translated

### LINKED ISSUE #329: Pull out cardinal direction strings so they can be translated
#### Software and hardware versions 
Collect v1.4.12

#### Problem description
`GeoPointWidget`'s `formatGps` method hardcodes "W", "E", "S", "N" as identifiers of the cardinal directions. They should be translatable.

### PR DESCRIPTION
**Pull request by grzesiek2010**
This PR is in reference to resolve #329

### CODE REVIEW

**Comment by lognaturel** [comment]
This assumes an order that may not be correct for all languages, especially right-to-left languages. The pulled out string should take positional arguments for degrees, min, seconds.

**Comment by grzesiek2010** [comment]
Fixed.

**Review by lognaturel — CHANGES_REQUESTED** [review]
I just thought of one more thing! This is going to be a very confusing one for translators to know what to do with. It would help them to put a comment above EACH of the strings with something like 
`<!-- %1$s represents degrees, %2$s represents minutes and %3$s represents seconds as in W 18°48'8" -->`
It needs to be above each separate string because they will show up separately in the translation interface.

**Comment by grzesiek2010** [comment]
Done.

**Pull request merged**
