### PR TITLE
Removes useless parenthesis

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Minor refactoring. Adds a rule to prevent addition of unnecessary parathesis in code

#### What has been done to verify that this works as intended?
This does not modify the behaviour of the app as it is just a minor code refactor

#### Why is this the best possible solution? Were any other approaches considered?
Removed useless parathesis and verified that it does not introduce any unsuspected changes

#### Are there any risks to merging this code? If so, what are they?
I don't think there are  risks to merging this but more reviews are always better. Also, it would be great to discuss if this will really be positive change and will not cause any problems in code readability

#### Do we need any specific form for testing your changes? If so, please attach one.

### CODE REVIEW

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
I was sitting on this one because I thought it might cause some merge conflicts but actually I think it's ok.

I like the change, I think extra parens make things harder to read!

**Comment by lognaturel** [comment]
I apologize, I was wrong about the low impact of this one. It turns out it conflicted with #1544 and because that one moved code with IDE support it was really hard to untangle. @dcbriccetti and I decided to revert this one to make that merge safer.

@dcbriccetti also mentioned that he finds some redundant parentheses useful. I don't feel strongly one way or the other but we should probably discuss before you issue a new PR, @shobhitagarwal1612.

**Comment by shobhitagarwal1612** [comment]
I did write the code readability point in the risks to merging this PR. Looks like it got buried in the paragraph. :smile:

**Comment by lognaturel** [comment]
No no, I saw it. I just figured that if no one had commented there were no objections which is probably not a good assumption to make.

**Comment by dcbriccetti** [comment]
I’ll try to check in more often so I can weigh in in a timely manner.

**Comment by shobhitagarwal1612** [comment]
:+1:

**Comment by lognaturel** [comment]
Sooooo... sounds like we leave things the way they are?

**Comment by dcbriccetti** [comment]
Can we change only the cases that are especially dumb, like `return (a + b)`?

**Comment by heyjamesknight** [comment]
I agree with @dcbriccetti, sometimes the extra parens are there to improve readability.

**Pull request merged**
