### PR TITLE
Add bikram sambat (Nepali) date widget

### PR DESCRIPTION
**Pull request by alxndrsn**
Use `appearance="bikram-sambat"` on `date` inputs to make them display using the Nepali calendar.

### CODE REVIEW

**Comment by mmarciniak90** [comment]
@opendatakit-bot label "needs testing"

**Comment by lognaturel** [comment]
Cool! The big question for me is whether this would be immediately useful to your team @alxndrsn. If so, I think we could make the surface changes to make it not overlap with the question title and see if we can merge close to as-is.

However, I suspect that you're on an old Collect fork and won't need this in core immediately. If that's the case, I'd rather we take the time to match the look and feel of other calendars and the code structure of other specialized calendars, especially in light of the work going on in #1505.

**Comment by mmarciniak90** [comment]
* Nepali date overlaps a question title
screenshot_20171016-163554
* Fix works only for date question. It should work for :
   * Full date
   * Month and year
   * Date and time

**Comment by mmarciniak90** [comment]
@opendatakit-bot unlabel "needs testing"

**Comment by lognaturel** [comment]
@alxndrsn I notice the library is unlicensed so unfortunately that means we can't use it! I'm going to close this for now and we can keep track of the feature in #1538. If the lib gets a compatible license we could consider it. Since you already have alxndrsn/bikram-sambat.js#5 filed, maybe we could work on that jointly and get it submitted to Joda.

**Comment by alxndrsn** [comment]
> If the lib gets a compatible license we could consider it.

I've added a licence to the java libs.

**Comment by alxndrsn** [comment]
@mmarciniak90 thanks for the feedback!  I'll take a look at the overlapping labels.

**Pull request closed without merging**
