### PR TITLE
Use MultiClickSafeButton in ProjectSettingsDialog for all the buttons

### LINKED ISSUE #4811: Multiple clicks on Add Project/About open up view from Main menu
#### Software and hardware versions 
Collect v2021.2.4

#### Problem description
Multiple clicks on Add Project open up view from Main menu

#### Steps to reproduce the problem
1. User opens a dialog with a list of added projects
2. User clicks multiple times on `Add Project` or `About`
3. User is able to open view from the Main menu

#### Expected behavior
User is not able to click multiple times on `Add Project` and `About`

#### Other information 
Similar to #4798

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #4811 

#### What has been done to verify that this works as intended?
I tested the fix and confirmed that everything works fine.

#### Why is this the best possible solution? Were any other approaches considered?
It's the same solution we use across the app. I don't know if it was possible to reproduce the same issue clicking on `Add project` button but just in case I handled this button as well.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It's a safe fix so we just need to confirm that the issue no longer exist.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by seadowg — APPROVED** [review]

**Comment by mmarciniak90** [comment]
@grzesiek2010, I'm still able to open e.g. Get Blank Form or Delete Saved Form page when I click a lot of times on Add Project or About.
ezgif com-video-to-gif

**Comment by grzesiek2010** [comment]
> I'm still able to open e.g. Get Blank Form or Delete Saved Form page when I click a lot of times on Add Project or About.

ahh it was a tricky case. Ok now everything should be fine.

**Comment by mmarciniak90** [comment]
**Tested with success**

Verified on Android 8.1, 9.0, 10.0

Verified cases:
- multi-click on `Add project`
- multi-click on `About`
- vertical device orientation
- horizontal device orientation
- RTL language

**Comment by kkrawczyk123** [comment]
Tested with success also on Androids 5.1 and 11.

**Pull request merged**
