### PR TITLE
Issue 311: Separate form preloaded values for username, email from server settings

### PR DESCRIPTION
**Pull request by dcbriccetti**
This implements ln’s proposal (https://github.com/opendatakit/collect/issues/311). I have saved a form containing all six pre-filled values, and they are correct. It may be time for an ODK expert to try this out.

### CODE REVIEW

**Comment by dcbriccetti** [comment]
I merged in recent master changes to this branch, so this might be a good time to process this pull request.

**Comment by lognaturel** [comment]
👍 Let me see if I can better express what I was trying to get at in the issue regarding a migration of sorts. I'm concerned that some people have forms out in the field that expect username and/or email address to be set. With this change, those values will be cleared. I think it would be worth doing some kind of "migration" that makes it so that the first time the app is launched after the change, the Aggregate username is copied to the username metadata field and the Google account is copied to the email metadata field. What do you think @dcbriccetti @yanokwa @nribeka 

Now that I see the description text as a summary for the "Form metadata" setting ("These values will be..."), it seems kind of long. Any alternate ideas? We can also leave it for now and review it as part of the broader redesign.

**Comment by dcbriccetti** [comment]
Thanks for the reminder that this remains to be done. If I don’t see objections from @yanokwa or @nribeka I’ll go ahead with your plan.

**Comment by yanokwa** [comment]
No objections from me, @dcbriccetti. It's important that it only runs on first install.

**Comment by dcbriccetti** [comment]
What’s a good approach, a shared preferences flag, formMetadataConverted?

**Comment by lognaturel** [comment]
@dcbriccetti That's the best I can come up with...

**Comment by dcbriccetti** [comment]
This is ready for review. Test results:

```
Before calling migrateOnce
metadata_migrated         false
selected_google_account   a Google email address
username                  a user

After calling migrateOnce
metadata_email            a Google email address
metadata_migrated         true
metadata_username         a user
selected_google_account   a Google email address
username                  a user

After changing metadata
metadata_email            an email--changed
metadata_migrated         true
metadata_phonenumber      a phone number--changed
metadata_username         a user--changed
selected_google_account   a Google email address
username                  a user

After calling migrateOnce again
metadata_email            an email--changed
metadata_migrated         true
metadata_phonenumber      a phone number--changed
metadata_username         a user--changed
selected_google_account   a Google email address
username                  a user
```

**Comment by lognaturel** [comment]
Nice. This is so much better than the confusing double username/email.

A couple of questions related to the functionality
- The "migration" is currently triggered by the user going to the metadata preferences screen, right? That means that users can't just keep using the app as they normally would and expect preloads to be populated correctly. I think the migration should actually happen on app launch.

- Leaving a phone number blank means it implicitly gets replaced by the phone's number, right? If there is a phone number set by the phone, that means it's impossible to represent a blank number? That feels a bit surprising to me. I liked @hooverlunch's suggestion of preloading the number if available during the migration and then letting it be editable.

- I have no recollection of how bulk configuration works but @hooverlunch mentioned it in the issue and it'd be nice to know that these values are saved along with other preferences when a user goes to admin settings > action bar > save settings to disk. Could you please take a quick look @dcbriccetti?

**Comment by smoyte** [comment]
Re bulk configuration: it's via Java object serialization. If these things are stored in the pref object or whatever it is, they should get serialized. Should be easily coverable with an integration or unit test.

**Comment by dcbriccetti** [comment]
Hi @lognaturel. Items 1 and 3 are addressed. As for 2, you’re right, I didn’t override a TelephonyManager-provided phone number with a zero-length metadata value. That’s easy to change. But, should we actually store a PropertyManager property with a zero length string, or should we remove the property entirely? I lean towards doing the latter. @yanokwa might have an opinion.

**Comment by dcbriccetti** [comment]
Regarding the question above, I went with empty strings, as that made the code simpler, and produced correct results on the saved forms.

Something else: I added logging for the migration:
```
.../org.odk.collect.android I/FormMetadataMigrator: migrate called, will migrate
.../org.odk.collect.android I/FormMetadataMigrator: Copying Dave from username to metadata_username
.../org.odk.collect.android I/FormMetadataMigrator: Copying dcbriccetti@gmail.com from selected_google_account to metadata_email
```

This enhancement is ready for further review.

**Comment by lognaturel** [comment]
Yay for logging, that's very helpful. Everything looks great!

One last thing I hadn't noticed before. I think "Google account" needs to be removed from the Admin Setting and "Form metadata" should now show up after "Platform settings" so that admins can block access to it.

**Comment by lognaturel** [comment]
Yes, that's a desired side-effect. 😊 Ready for final review, then, I think?

**Comment by dcbriccetti** [comment]
Ah, good. I have one more small change coming. I had to change AdminPreferencesActivityTest, because it is fragile. I’m spending 20 minutes to make it no longer fragile.

**Comment by dcbriccetti** [comment]
Ready now.

**Comment by lognaturel** [comment]
🎉

**Pull request merged**
