### PR TITLE
Upgrade OKHttp3 to allow unicode in headers

### LINKED ISSUE #3281: OkHttp failure when submission filename contains unicode
#### Software and hardware versions 
Collect v1.23.0

#### Problem description
Submission filenames are based on the form name which can contain unicode. Trying to send a submission with such a form name causes a crash.

See reproduction steps and full error message at https://forum.opendatakit.org/t/unable-to-upload-odk-record-to-server/21230

### PR DESCRIPTION
**Pull request by lognaturel**
Closes #3281 

#### What has been done to verify that this works as intended?
Successfully submitted an instance from the form definition in the issue.

#### Why is this the best possible solution? Were any other approaches considered?
I was going to add a test for this but since it turns out to be an OKHttp3 bug (https://github.com/square/okhttp/issues/4564) and [a test was introduced for the fix](https://github.com/square/okhttp/pull/4618/files#diff-c0fbf53145399b63adc71321a0d0b864R275), I don't think we need to add one at this level.

Since the OKHttp fix was backported to OKHttp3 (which we need to use because we support API levels lower than 21), this is the simplest possible fix.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
The goal of this PR is to allow users to send submissions with filenames that contain unicode. Since the fix involves an update to the HTTP library, there could be side effects in anything that involves data transfers. I've reviewed [the changelog](https://github.com/square/okhttp/compare/okhttp_3.12.x) and everything looks safe, well-tested, and like it will provide user benefit.

#### Do we need any specific form for testing your changes? If so, please attach one.
See issue.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by lognaturel** [comment]
I don't think there's much meaningful review or QA to do here since it's a dependency bug. I propose we release this as soon as possible since users are likely to run into it and then QA can evaluate and decide whether it makes sense to do a quick regression check.

**Comment by yanokwa** [comment]
Ordinarily, I'd want to hold a hot fix a few days after a release, but this affects submissions and there are a likely a number of submissions with Unicode.

**Review by yanokwa — APPROVED** [review]

**Comment by seadowg** [comment]
For the moment I agree it's an OkHttp responsibility but it might still be nice long term to add something to the`OpenRosaXRequestTest` classes as they are technically independent of the underlying HTTP client. This would give us protection if we move to another HTTP client in the (hopefully far future). What do you think? Happy to take that on or write an issue up (could be a "good first issue").

**Comment by lognaturel** [comment]
@seadowg I'm not convinced that we need to have an HTTP-specific test but sleeping on this has led me to think we should have a form with a unicode name involved in some end-to-end regression test (which would include submission). I think it's the kind of thing that is likely to bite us in some other unexpected way. I had actually completely forgotten that the form name as opposed to form_id was used to create the submission filename. That means we have paths that have unicode in them and I can imagine all kinds of odd things happening if we, for example, make changes to the storage layer. Will be interested to hear QA's thoughts on where that best fits in.

**Comment by mmarciniak90** [comment]
**Tested with success on v1.23.1 from Play Store**

Verified form: [ReunionRecuperacion.xml.txt](https://github.com/opendatakit/collect/files/3466337/ReunionRecuperacion.xml.txt)

Verified on Android: 9.0, 8.1, 7.0, 6.0, 5.1, 4.4, 4.2

Verified cases:
- send with success the form to Aggregate
- send with success the form to Google Sheet

@opendatakit-bot unlabel "needs testing" 
@opendatakit-bot label "behavior verified"

**Comment by seadowg** [comment]
@lognaturel yeah that makes sense. There are a lot of places for something like that to go wrong.

**Pull request merged**
