### PR TITLE
Fixes Calendar number readability on Android 4.1.2 (Fixes #489)

### LINKED ISSUE #489: Calendar numbers are unreadable on Android 4.1.2
#### Software and hardware versions 
Collect v1.4.16-18-gd398fc05, Android 4.1.2 Nexus 5 emulator

#### Problem description
screen shot 2017-03-01 at 12 48 59 pm

#### Steps to reproduce the problem
1. Download a form with a calendar question such as New Widgets from the default test server
1. Go to the question with the calendar widget

#### Expected behavior
From API 22 emulator:
screen shot 2017-03-01 at 12 52 07 pm

#### Other information 
The calendar scrolling is also not optimal but that should be addressed as a separate issue.

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**

### CODE REVIEW

**Comment by grzesiek2010** [comment]
[DateWidget](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/widgets/DateWidget.java) also uses calendar so this problem might occur there too but your fix is only for [DateTimeWidget](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/widgets/DateTimeWidget.java). Did you investigate DateWidget?

**Comment by grzesiek2010** [comment]
The second thing - you should add a link http://stackoverflow.com/a/36321828/5479029 as it's not your solution.

**Comment by shobhitagarwal1612** [comment]
@grzesiek2010 Thanks for the help. I have added the check for both DateWidget and DateTimeWidget classes. Also added the link of the solution url to the new DateWidgetUtils class

**Comment by grzesiek2010** [comment]
@shobhitagarwal1612 ok looks better but I'm not sure if creating new class is a good idea. Personally I would prefer adding this code to [QuestionWidget](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java) as there is only one method and both widgets extends QuestionWidget.
@lognaturel what do you think?

Or maybe we could even refactor these widgets... I think DateTimeWidget could extend DateWidget then it should look better.

**Comment by lognaturel** [comment]
@shobhitagarwal1612 @grzesiek2010 I'm happy with the structure for now and it can always be revisited as needed. 

I don't think `QuestionWidget` is the right place for that code because it only applies to a couple of widget types. In the longer term, I think there probably should be a layer added to the inheritance hierarchy to enable more code sharing and cleaner abstractions. That would either be by adding an abstract superclass that both extend or by making `DateTimeWidget` a subclass of `DateWidget`. I haven't looked carefully enough at what code is and isn't shared to say which is most appropriate.

**Comment by lognaturel** [comment]
And again, thanks for the good teamwork! 😊

**Pull request merged**
