### PR TITLE
fixes #1723 Restricted number of opened date dialog's to one

### LINKED ISSUE #1723: More than one date dialog is opened when user quickly clicks the button several times
#### Software and hardware versions 
Collect v1.12.0

#### Problem description
More than one date dialog is opened when user quickly clicks the button several times

#### Steps to reproduce the problem
1. User quickly clicks the 'Select date' button several times
2. Dialog appears
3. User selects date and clicks OK
4. User sees that additional dialog is visible with default date

#### Expected behavior
User is not able to open two dialogs

#### Other information 
Problem related to https://github.com/opendatakit/collect/issues/1624. 
Noticed during release testing

### PR DESCRIPTION
**Pull request by dr0pdb**
Closes #1723 

#### What has been done to verify that this works as intended?

Checked on Android 5.1.1 using the all widgets form.

#### Why is this the best possible solution? Were any other approaches considered?

Hiding any previously shown dialog was the best possible and feasible solution in my view.

#### Are there any risks to merging this code? If so, what are they?

NA

#### Do we need any specific form for testing your changes? If so, please attach one.
No, just the all widgets form will do.

### CODE REVIEW

**Comment by grzesiek2010** [comment]
@srv-twry 

I believe it works well but it's not a right solution in this case. Please investigate https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java#L402 and 
https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/widgets/QuestionWidget.java#L420

and how other widgets are protected from multi-touching.

**Comment by grzesiek2010** [comment]
@opendatakit-bot label "changes requested"
@opendatakit-bot unlabel "needs review"

**Comment by srv-twry** [comment]
@grzesiek2010 Please review.

**Comment by dr0pdb** [comment]
@grzesiek2010 Please review

**Comment by grzesiek2010** [comment]
Yes, this is it tanks.

@opendatakit-bot "needs testing"

**Comment by grzesiek2010** [comment]
@opendatakit-bot unlabel "changes requested"
@opendatakit-bot label "needs testing"

**Comment by mmarciniak90** [comment]
**Tested with success!**
Verified on Android: 4.1, 4.2, 4.4, 5.1, 6.0, 7.0, 8.0
I did not notice regression on other widgets.

@opendatakit-bot unlabel "needs testing"

**Review by lognaturel — APPROVED** [review]

**Pull request merged**
