### PR TITLE
Fixed draw_layout

### LINKED ISSUE #914: Buttons in DrawWidget don't look good
#### Software and hardware versions 
Collect v1.5.1

#### Steps to reproduce the problem
Use this form: 
[draw.txt](https://github.com/opendatakit/collect/files/929900/draw.txt)

#### Other information 
screenshot_2017-04-18-15-17-10

### PR DESCRIPTION
**Pull request by grzesiek2010**
This PR is in reference to resolve #914 
My proposal is to add new layout for landscape view:
landscape
portrait

### CODE REVIEW

**Comment by lognaturel** [comment]
That is much better, thanks. The reset button isn't working for me. I think it would be nice to also scale the image to fill the entirety of the screen in portrait. Right now it's scaling down like it would for landscape mode when you open a drawing that was just created:
screen shot 2017-04-20 at 2 58 48 pm

Basically, I think that if it starts out in portrait mode, it should be shown at full scale in portrait and scaled down in landscape. Ideally, when it starts in landscape mode, I think it should be shown at full scale in landscape and scaled down in portrait (to fill the full width). It would be interesting to see how other mobile drawing apps deal with rotation. Do they do what I'm describing or do they use something like a square canvas that fits one edge but needs to be scrolled for the other?

**Comment by grzesiek2010** [comment]
@lognaturel nice sketch :+1: 
Could you add more info about your device? because:
1. Reset button works well on my device
2. As you can see above it's shown at full scale on my device in portrait mode
and I'm not sure if I should work on point 2 as there is a separate issue https://github.com/opendatakit/collect/issues/794

**Comment by lognaturel** [comment]
Nexus 6, Android 6.0.1. Does the sketch open at full scale on your device if you save it and then open it again?

Yes, you can focus on portrait for this one.

**Comment by nribeka** [comment]
Should we put each of the button on each corner? I think a lot of camera apps do this approach where they have some set of buttons at the top of the screen and some other set of buttons at the bottom.

I think having two rows of button on the same place could create accidental pressing of other button (a.k.a. fat fingering buttons). Even though the reset and cancel are in the same row in this layout, so if they ever fat finger it, it would be resetting it or cancelling it.

**Comment by grzesiek2010** [comment]
Generally it would be great to add menu like that:
screenshot_2017-04-21-21-55-33

**Comment by lognaturel** [comment]
I totally agree there's a lot that could be done to improve the draw widget! I think the stacked buttons are a fine place to start -- it's a clear improvement and doesn't require too much effort.

Then I think we should capture the redundancy between `AnnotateWidget`, `DrawWidget`, `SignatureWidget` and decide on a coherent user experience for the base class to have. I really like the menu you're proposing, @grzesiek2010. I've filed #943 for the refactoring part.

Let's keep this PR focused on the minor button improvement in portrait and then spend some time designing a better drawing experience.

**Pull request closed without merging**
