### PR TITLE
View sent form

### PR DESCRIPTION
**Pull request by grzesiek2010**
This PR is in reference to resolve #251

@lognaturel 
It's ready for review let me now if I missed something. 
I have only one question. When we reset app state and check "Saved forms" option we clear database to and information about sent forms. I'm not sure it's good. Should we change this? Maybe we should add separate option for reset database?

### CODE REVIEW

**Comment by lognaturel** [comment]
I think the behavior of reset app state is still good. If someone just wants to delete forms, they can delete them from the delete menu and then they'll still show up as sent and deleted. Reset should really only be for when the phone is in a weird state and someone wants to start from a clean slate. Good thing to think about, though. @yanokwa what do you think?

When I try to run this, I'm getting "Can't upgrade read-only database" for instances.db. This is after I did an app reset so it could be related. I did a data reset from Applications > ODK Collect as well and that didn't help. Neither does deleting the app and installing it again.

**Comment by lognaturel** [comment]
Sigh, I'm sorry. It's because I had already added the column previously and didn't realize that because the dbs are on the SD card they don't get deleted on data or app deletion.

**Comment by grzesiek2010** [comment]
Yes I tested upgrade scenario so it should work or I am bad tester :)

**Comment by lognaturel** [comment]
This is looking really good. Because it ends up touching a lot, I want to make sure we've systematically thought about all the cases to verify even in the absence of automated testing.

Scenarios verified:
1. fill out form, save and finalize it. It should show up only in "Edit Saved Form" and "Send Finalized Form"
1. fill out form, save and finalize it, send it. It should show up only in "View Sent Form". The number next to "View Sent Form" should be incremented by 1.
1. fill out form, save and finalize it, send it then delete it. It should show up only in "View Sent Form". The number next to "View Sent Form" should be incremented by 1. The form should be listed as deleted and have a non-visible icon next to it.
1. fill out encrypted form, save it. It should show up only in "Edit Saved Form". It should be editable.
1. fill out encrypted form, save and finalize it. It should show up only in "Edit Saved Form" and "Send Finalized Form". It should NOT be editable (forms are encrypted when finalized).
1. fill out encrypted form, save and finalize it, send it. It should show up only in "View Sent Form". It should be identified as encrypted and have a non-visible icon next to it. The number next to "View Sent Form" should be incremented by 1.
1. uncheck "View Sent Form" from the admin settings and it should disappear from the main menu.

I also tried it with Google Forms since we seem to be really good at breaking that. 😁

@grzesiek2010 does that cover everything you can think of?

**Comment by grzesiek2010** [comment]
@lognaturel 
It looks ok to me. I've tested all listed cases and I can confirm it works.

**Comment by lognaturel** [comment]
Here's one thing -- the `dateDeleted` column should really be a date rather than a string. I know `displaySubtext` does a text thing but it's not a great practice. It means we can't sort by that deleted date and that that subtext can't be localized. For example, I switch between English and French and now half of my form subtext is in one language and half in the other! 

I'm also still wondering about whether introducing the new `STATUS_SUBMITTED_AND_DELETED` status is necessary. Those same forms can be identified as `STATUS_SUBMITTED` with a `dateDeleted` that's not null. Does adding the new status simplify the code significantly?

**Comment by grzesiek2010** [comment]
@lognaturel 
I fixed both bugs from your las comment. You are right STATUS_SUBMITTED was not necessary.

**Comment by yanokwa** [comment]
I've reviewed it and it looks good to me. There are some minor issues that I'll file separate issues for.

**Pull request merged**
