### PR TITLE
Closes #4798

### LINKED ISSUE #4798: Multiple clicks on Settings open up unexpected views
#### Software and hardware versions 
Collect v2021.2.x
Android 5.1, 8.1, 9.0, 10.0

#### Problem description
Multiple clicks on `Settings` open up unexpected views

#### Steps to reproduce the problem
1. User opens a dialog with a list of added projects
2. User clicks multiple times on `Settings`
3. User is able to open view from the Main menu and goes to some view in settings

#### Expected behavior
User is not able to click multiple times on `Settings`

#### Other information 
ezgif com-video-to-gif

### PR DESCRIPTION
**Pull request by Unreal-Dreams**
Closes #

#### What has been done to verify that this works as intended?
Testing on given hardware versions as raised in issue #4798 was performed.
#### Why is this the best possible solution? Were any other approaches considered?
Class Multiguard is already included in the codebase which provides the best possible solution. I also considered the approach where we can disable the button with setEnabled(false) until it is safe for the user to click it again.
#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Users will not be able to click on the settings button multiple times which will prevent the opening of unexpected views. There are no accidental behavioral changes.
#### Do we need any specific form for testing your changes? If so, please attach one.
No
#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by Unreal-Dreams** [comment]
Hey, @grzesiek2010  can you please review my PR

**Review by grzesiek2010 — APPROVED** [review]

**Comment by grzesiek2010** [comment]
It looks good, thanks!

**Comment by Unreal-Dreams** [comment]
@grzesiek2010  I have tested the changes on the android versions mentioned in the issue i.e Android 5.1, 8.1, 9.0, 10.0, and everything works fine. No unexpected behavior is present in the settings button. If there are any more steps in testing please let me know. Thank You!

**Comment by grzesiek2010** [comment]
That's great you tested your changes but we have a QA team responsible for verifying every single fix/new feature so that label was added to let them know they that they can check it.

**Comment by Unreal-Dreams** [comment]
@grzesiek2010 Ok thanks for sharing the process.

**Comment by mmarciniak90** [comment]
**Tested with success**

Verified on Android 8.1, 9.0, 10.0

Verified cases:
- multi-click on `Settings`
- vertical device orientation
- horizontal device orientation
- RTL language

Noticed a similar issue during testing #4811

**Comment by kkrawczyk123** [comment]
Tested with success also on Androids 5.1 and 11.

**Pull request merged**
