### PR TITLE
Catch Mapbox error on 64bit devices

### LINKED ISSUE #3144: Collect crashes when user selects Mapbox Maps SDK on ARM64 device
#### Software and hardware versions 
Collect v1.22.2
Android v8.1

#### Problem description
Collect crashes when user selects Mapbox Maps SDK 

#### Steps to reproduce the problem
1. The user goes to `General Settings` > `User interface`
2. The user opens the `Mapping SDK` dialog
3. The user selects `Mapbox Maps SDK`
 
#### Expected behavior
Collect does not crash

#### Crash
`2019-06-11 10:43:59.696 25431-25431/org.odk.collect.android E/Mbgl-LibraryLoader: Failed to load native shared library.
    java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/org.odk.collect.android/app_lib/libmapbox-gl.so" is 32-bit instead of 64-bit
        at java.lang.Runtime.load0(Runtime.java:928)
        at java.lang.System.load(System.java:1621)
        at com.getkeepsafe.relinker.SystemLibraryLoader.loadPath(SystemLibraryLoader.java:29)
        at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:204)
        at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
        at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:92)
        at com.mapbox.mapboxsdk.module.loader.LibraryLoaderProviderImpl$ReLinkerLibraryLoader.load(LibraryLoaderProviderImpl.java:38)
        at com.mapbox.mapboxsdk.LibraryLoader.load(LibraryLoader.java:43)
        at com.mapbox.mapboxsdk.net.NativeConnectivityListener.<clinit>(NativeConnectivityListener.java:13)
        at com.mapbox.mapboxsdk.net.ConnectivityReceiver.instance(ConnectivityReceiver.java:43)
        at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:60)
        at org.odk.collect.android.map.MapboxUtils.initMapbox(MapboxUtils.java:30)
        at org.odk.collect.android.preferences.UserInterfacePreferences.lambda$initMapPrefs$4$UserInterfacePreferences(UserInterfacePreferences.java:228)
        at org.odk.collect.android.preferences.-$$Lambda$UserInterfacePreferences$7x5hXs_yrA1xCufJDOUBgbAG8Nk.onPreferenceChange(Unknown Source:6)
        at android.preference.Preference.callChangeListener(Preference.java:1080)
        at android.preference.ListPreference.onDialogClosed(ListPreference.java:282)
        at android.preference.DialogPreference.onDismiss(DialogPreference.java:395)
        at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1361)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
2019-06-11 10:43:59.697 25431-25431/org.odk.collect.android E/zygote64: No implementation found for void com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize() (tried Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize and Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize__)
2019-06-11 10:43:59.699 25431-25431/org.odk.collect.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.odk.collect.android, PID: 25431
    java.lang.UnsatisfiedLinkError: No implementation found for void com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize() (tried Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize and Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize__)
        at com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize(Native Method)
        at com.mapbox.mapboxsdk.net.NativeConnectivityListener.<init>(NativeConnectivityListener.java:27)
        at com.mapbox.mapboxsdk.net.ConnectivityReceiver.instance(ConnectivityReceiver.java:43)
        at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:60)
        at org.odk.collect.android.map.MapboxUtils.initMapbox(MapboxUtils.java:30)
        at org.odk.collect.android.preferences.UserInterfacePreferences.lambda$initMapPrefs$4$UserInterfacePreferences(UserInterfacePreferences.java:228)
        at org.odk.collect.android.preferences.-$$Lambda$UserInterfacePreferences$7x5hXs_yrA1xCufJDOUBgbAG8Nk.onPreferenceChange(Unknown Source:6)
        at android.preference.Preference.callChangeListener(Preference.java:1080)
        at android.preference.ListPreference.onDialogClosed(ListPreference.java:282)
        at android.preference.DialogPreference.onDismiss(DialogPreference.java:395)
        at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1361)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)`

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #3144 

#### What has been done to verify that this works as intended?
I tested the case described in the issue and confirmed that the app is no longer crashing.

#### Why is this the best possible solution? Were any other approaches considered?
I've just realized that my solution in https://github.com/opendatakit/collect/pull/3146/commits has been changed and now it catches exceptions but both `ExceptionInInitializerError` and `UnsatisfiedLinkError` used before extend `Error`, not `Exception` so it won't be caught.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It's safe and can't affect anything apart from fixing the issue.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
Thank you, @grzesiek2010. I apologize for missing that in review. @yanokwa, this means the latest point release actually had no effect, unfortunately.

**Comment by lognaturel** [comment]
The design choice of `Exception` vs. `Error` is an interesting one. It suggests that Mapbox functionality is always considered central to an app's function (inaccurate in our case). And the name `ExceptionInInitializerError` is a strange one because it's an "exception error"... 🤷🏻‍♀️

**Comment by grzesiek2010** [comment]
> I apologize for missing that in review

It happens but again it shows that even such small prs should be tested (especially if we can reproduce the issue)

**Comment by lognaturel** [comment]
> even such small prs should be tested (especially if we can reproduce the issue)

I go back and forth on that. When there's availability to do a safe point release, it feels ok to do quickly and verify later. It has avoided user pain in the past and even in this case it's not a very big setback. But you're certainly right in principle.

**Comment by zestyping** [comment]
I'm so sorry, this was my mistake in suggesting `Exception`!  I forgot that `Error` is a separate hierarchy.

**Comment by lognaturel** [comment]
@grzesiek2010 I think I may have come across as dismissive of your concerns and suggestions and I certainly didn't mean that. Thanks for pushing back -- that's what makes the project better.

I let this work through my brain as I was doing other things and have a few thoughts:
- We should not rush to do point releases when the issue is with new behavior. That is, with #3133, people with existing forms weren't able to do their work so that was definitely a priority. With this, new behavior wasn't available which is much less of a big deal. I think @yanokwa and I were fresh off 1.22.1 which went well and 1.22.2 which didn't have any meaningful QA to do and thought "let's do the same thing again" even though it's a different situation.

- When we do merge something without QA that, like @grzesiek2010 said, is easily verifiable, we should always mark as `needs testing` and `high priority` and bring @mmarciniak90 in so that she can do a quick sanity check. That was just my mistake -- I couldn't imagine any way that it wouldn't satisfy the requirement but I guess I'm just not that creative!

No worries at all, @zestyping.

So @mmarciniak90, please sanity check. 😊🙏

**Comment by mmarciniak90** [comment]
**Tested with success**

Verified on the 64bit device with Android 8.1 - Nexus 5X.
Verified also on other devices to check regression (Android 4.2, 4.4, 5.1, 6.0, 7.0)

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Pull request merged**
