### PR TITLE
Lighten the color of popup dialog of Spinner widget for dark theme

### LINKED ISSUE #2213: Lighten select_one popups
#### Software and hardware versions 
Collect v1.15 beta 0

#### Problem description
According to https://forum.opendatakit.org/t/odk-collect-v1-15-beta/13086/9, the select one with minimal appearance is a little too dark.

I agree that select_one it could be a little lighter. It's currently #303030 and it could probably be #3f3f3f to match other pop up dialogs (it's kind of a pop up).

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Closes #2213 

#### What has been done to verify that this works as intended?
Verified manually with both the themes

#### Why is this the best possible solution? Were any other approaches considered?
This is the most appropriate solution which is in line with the already implemented approach

#### Are there any risks to merging this code? If so, what are they?
No

#### Do we need any specific form for testing your changes? If so, please attach one.
Any form with spinner widget

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew pmd checkstyle lint findbugs` and confirmed all checks still pass.
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

issue-2213

### CODE REVIEW

**Comment by mmarciniak90** [comment]
@shobhitagarwal1612 Honestly, I do not see a difference in pop up. 
In #2213 suggested is to use #3f3f3f color like in other pop up dialogs.

||3f3f3f|

| before fix | fix| other dialog|
|---|---|---|
|screenshot_2018-05-21-13-45-36|screenshot_2018-05-21-13-43-37|screenshot_2018-05-21-13-44-00|

**Comment by mmarciniak90** [comment]
@opendatakit-bot unlabel "needs testing"

**Comment by shobhitagarwal1612** [comment]
@mmarciniak90 Fixed

**Comment by mmarciniak90** [comment]
@shobhitagarwal1612 thank you for so quick fix! Spinner looks great now! :+1: 

**Tested with success**

Verified on Android: 4.1, 4.2, 4.4, 5.1, 6.0, 7.0, 8.1

|screenshot_20180523-110209|screenshot_20180523-110821|
|---|---|

@opendatakit-bot label "behavior verified"
@opendatakit-bot unlabel "needs testing"

**Review by lognaturel — APPROVED** [review]

**Pull request merged**
