### PR TITLE
Improvements to the typography used in the form

### LINKED ISSUE #5953: Bringing the bold font back to the hierarchy view
### **Changes for this release**

In considering this upcoming release, we want to bring the bold font back (both in the hierarchy view and inline), but keep the following styling changes:
- Unifying margins in the hierarchy view and form entry
- Spacing (which we will tighten up as part of [this work](https://github.com/getodk/collect/issues/5932#issuecomment-1908949154))
- Adding folder icon 
- Indenting 

We are doing this because we are worried about a few things:
- Inconsistency with web forms
- The finalization changes have been disruptive for some folks and this might create more pushback 
- Might take away from other styling updates we are introducing in this release 

---

**Future considerations** 

- Our [original goal](https://github.com/getodk/collect/issues/5837) was to create more consistency between the hierarchy view and form entry experience
- We also wanted to remove the bold font because long bold sentences are hard to read and not always accessible. Bold fonts work well for short sentences, but how people design their forms is out of our control. Ideally, we want to use bold sparingly because overuse will make it difficult for users to know which parts of the content they need to pay the most attention to. 
- By removing the bold font form designers can introduce font styling where they see fit, like bolding certain words to emphasize certain things. 
- One idea is to remove the bold font & bundle it with other related changes, such as displaying media to the summary view (rather than the raw output), so it's more user-friendly and informative. 
- We also hope to create a [guide for designing user-friendly forms](https://docs.google.com/document/d/1SD8hwX9LBJXAQddFtpC1xeczAjrqRaWVq3t3xRe87gM/edit) mostly about content design tips 

Add these notes here so we have something to reference – mostly so I don't forget. Feel free to edit if I missed anything.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5953 

#### Why is this the best possible solution? Were any other approaches considered?
We have discussed on slack that the space between the lines in question labels is too big now. I've investigated it and it turns out it's 28sp and in v2023.3.1 it was 24sp for the labels displayed in a form and 26sp for labels displayed in the hierarchy view. I think 24sp looks ok so that's the value I applied for both views.

When it comes to the fontWeight @lognaturel and @alyblenkin wanted to see if something bolder (like it was before in the case of the form view) would look better so please take a look and let me know what you like more:

| Before (master) | After |
| ------------- | ------------- |
| Screenshot_1707738882 | Screenshot_1707738550|
| Screenshot_1707738880 | Screenshot_1707738547 |

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Just make sure that question labels in the form view and the hierarchy view are bold. Typography in other parts of the app should not change. The only exception is the app bar where the text will be bold too.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by alyblenkin** [comment]
Thanks so much for investigating @grzesiek2010. The spacing feels better! It's a minor tweak, but it helps visually group the questions better. 

My pre-caffeine thoughts on the bold:
- The bold works great for short sentences but is challenging to read when the text spans more than two lines. 
- The summary page feels heavy but connected to the form-filling experience because it's consistent with the font weight, making it easier for users to orient themselves in the flow.
- We could ship it with these new changes and then come back to remove the bold and make other changes related to this flow, such as displaying media (images, audio, video, etc.). That would also allow us to communicate with users and identify any risks in being different from Enketo.

Curious to know what you think @lognaturel!

**Comment by lognaturel** [comment]
>  @lognaturel and @alyblenkin wanted to see if something bolder (like it was before in the case of the form view) would look better

It's not so much about which looks better, it's about minimizing risk of disruption so we don't get derailed again by a bunch of user pushback!

> We could ship it with these new changes and then come back to remove the bold and make other changes related to this flow, such as displaying media (images, audio, video, etc.). That would also allow us to communicate with users and identify any risks in being different from Enketo.

I'm in favor of this. Keeping the bold in this release and applying it consistently across the form entry and summary screens buys us time to better understand how meaningful/important the bold is today and prepare users for a change. It also lets us consider other changes we might want to make to separate questions more within a field list.

**Comment by alyblenkin** [comment]
> I'm in favor of this. Keeping the bold in this release and applying it consistently across the form entry and summary screens buys us time to better understand how meaningful/important the bold is today and prepare users for a change. It also lets us consider other changes we might want to make to separate questions more within a field list.

Sounds like a plan to me! I'll approve the change

**Review by alyblenkin — APPROVED** [review]

**Comment by grzesiek2010** [comment]
Is it ok that the title in the app bar will be bold too? It was bold in v2023.3.1 as well because the same text appearance is used there.

**Comment by seadowg** [comment]
> Is it ok that the title in the app bar will be bold too? It was bold in v2023.3.1 as well because the same text appearance is used there.

It makes sense to keep that consistent to me. @alyblenkin?

**Review by seadowg — APPROVED** [review]

**Comment by srujner** [comment]
**Tested with Success!**

Verified on device with **Android 13**

Verified cases:
- Works toward issue #5953;
- Question labels in the form view and the hierarchy view are bold;
- Quick check through some forms; 
- Light and Dark mode;
- Rotate the screen and minimize the app.

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on device with Android 10

**Pull request merged**
