### PR TITLE
Improves UI of search view

### LINKED ISSUE #1287: Improve the UI of search bar
Currently, the search bar appears below the app bar. This causes the entire list to move up/down when this box appears. 
I propose that the search view should be in the app bar itself

screenshot_1501311113

PR submitted [here](https://github.com/opendatakit/collect/pull/1286)

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
In reference to resolve #1287

### CODE REVIEW

**Comment by lognaturel** [comment]
This is definitely more in line with with modern Android apps and looks very nice. I think it makes sense to roll out in the August release along with the sort menu refresh. How does that sound @shobhitagarwal1612 @yanokwa @grzesiek2010 and anyone else who wants to weigh in?

I noticed a couple of inconsistencies. When I rotate the screen into landscape, the Collect clipboard icon in the upper left now turns into a hamburger menu. In Delete Saved Forms, when empty, the field says "Search..." and has no underline. In the other screens, the field has a magnifying glass icon inside and the text has an underline. The Google apps I looked at have the text "Search" rather than a magnifying glass so I'd tend to go with that consistently across the board.

**Comment by grzesiek2010** [comment]
https://github.com/opendatakit/collect/pull/1286/files#diff-a551fa7ec8c877869892148c037d0a7aR141
and
https://github.com/opendatakit/collect/pull/1286/files#diff-a551fa7ec8c877869892148c037d0a7aR168

I'm always really concerned about it.... maybe you don't remember but we were talking about it some time ago. A I know its a bad practice.

Now I realized there are some other activities with this... maybe it was considered.
Every time you use it you should be able to explain why, so:

Could you explain why do you use it? Why can't you use onSaveInstanceState method? What do you try to achieve? 
Don't know if you understand it but it helps you only with orientation changes but configuration changes can occur for a number of reasons - not just screen orientation changes and then a problem you try to solve (whatever it is) might occur.

Please read more about it:
https://stackoverflow.com/a/5336057/5479029
http://www.androiddesignpatterns.com/2013/04/retaining-objects-across-config-changes.html
https://stackoverflow.com/a/7990543/5479029

**Comment by lognaturel** [comment]
That's a good point, @grzesiek2010, thanks for mentioning it.

**Comment by shobhitagarwal1612** [comment]
> In Delete Saved Forms, when empty, the field says "Search..." and has no underline. In the other screens, the field has a magnifying glass icon inside and the text has an underline. The Google apps I looked at have the text "Search" rather than a magnifying glass so I'd tend to go with that consistently across the board.

Looking into this. Point to note is that both are implemented the same way and are the inflated using the same `list_menu.xml`. The only difference is that the DeleteSavedForm is a fragment while the other screens are an activity. 


> Could you explain why do you use it? Why can't you use onSaveInstanceState method? What do you try to achieve?

@grzesiek2010 Thanks for reminding me that. I was having some trouble while trying to retain the state of search view on orientation changes but I don't clearly remember what that was. So I will remove the `configChanges` again to get the exact reason for using this workaround instead of `onSaveInstanceState`

**Comment by shobhitagarwal1612** [comment]
So what I did was save the `state` and `search text` in `onSaveInstanceState` and added a check to the `onCreateOptionsMenu` to reopen the search view if it was opened previously. But the method `onCreateOptionsMenu` is called only when the activity is recreated. So when the activity is just paused and resumed then this trick fails to reopen the searchView

**Comment by grzesiek2010** [comment]
Currently I'm off and I'm back on 16.08 but could you provide precise steps to reproduce your problem? Then I will able to understand it faster.

**Comment by grzesiek2010** [comment]
I'm back. What about those steps?

**Comment by shobhitagarwal1612** [comment]
1. Save the search view state `visible/hidden` and search text in `onSaveInstanceState`
2. Restore the value in `onRestoreInstanceState`
3. Add a check in `onCreateOptionsMenu` to open the search view with the search text if the restored state is visible.

**Comment by grzesiek2010** [comment]
ok good to know too but at first I would like to know steps like for users. I mean eg. 
open search box then enter any text then rotate your device and you should see that text.

**Comment by grzesiek2010** [comment]
@shobhitagarwal1612 it's possible to save everything using only onSaveInstanceState https://github.com/opendatakit/collect/pull/1347

**Comment by shobhitagarwal1612** [comment]
Thanks @grzesiek2010 !

**Comment by shobhitagarwal1612** [comment]
@lognaturel Please review

**Comment by grzesiek2010** [comment]
One another thing from me: Why doesn't the searchbox take all available space in landscape mode? Could we fix that? It would look better.

screenshot_2017-08-17-08-52-36

**Comment by mmarciniak90** [comment]
I described two cases to pay attention to them. 

Sort icon appears in one case.
1. User opens 'Delete Saved Form' view 
2. User clicks on search icon
3. User clicks on device back button to close keyboard
4. **Sort icon appears**

screenshot_20170817-141902

Menu icon is visible next to search bar on views:
* Send Finalized Form
* Get Blank Form

screenshot_20170817-143404
screenshot_20170817-143407
screenshot_20170817-143704

**Comment by shobhitagarwal1612** [comment]
@lognaturel Ready to be reviewed

**Comment by lognaturel** [comment]
👍 Looks great on Samsung Galaxy Tab - Android 5.1.1 and Motorola G4 - Android 7.0. I see [here](https://stackoverflow.com/a/34050959/137744) that there may be some variation between Android versions for the width fix. @grzesiek2010 could you please do a quick sanity check on an Android 4.x device? Or @shobhitagarwal1612 if you still have one, let me know if you've tried it.

**Review by lognaturel — APPROVED** [review]

**Comment by shobhitagarwal1612** [comment]
@lognaturel I also tested it on Android 7. My device with Android 4.4 is broken, so I wasn't able to test on that.

**Comment by grzesiek2010** [comment]
@lognaturel It looks ok on Samsung GT-S7582 Android 4.2.2.

**Pull request merged**
