### PR TITLE
Ignore lint error for Slovene [Fix master branch]

### PR DESCRIPTION
**Pull request by grzesiek2010**
#### Why is this the best possible solution? Were any other approaches considered?
We can ignore this warning like we do for Ukrainian also.

#### Are there any risks to merging this code? If so, what are they?
No.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew pmd checkstyle lintDebug spotbugsDebug` and confirmed all checks still pass.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by shobhitagarwal1612 — APPROVED** [review]
Looks great!

**Comment by lognaturel** [comment]
🙏 Seems this is a property of slavic languages. Is Polish like this, @grzesiek2010? It seems perhaps the translations should account for the property but I don’t really understand what it means.

**Comment by grzesiek2010** [comment]
> Seems this is a property of slavic languages. Is Polish like this

yes, but in our case, Now I'm wondering if we need more than `one` and `few` options. In Polish it would be enough. I noticed that someone has added `many` and `other` just for `uk` an `sl` but in fact, exactly the same strings are used for them like for `few`.

**Comment by grzesiek2010** [comment]
> Seems this is a property of slavic languages. Is Polish like this

yes it is but in this case (this message) we don't need to provide more options I guess it's ok.

**Pull request merged**
