### PR TITLE
Issue #943 widget redundancy

### LINKED ISSUE #943: Capture redundancy between DrawWidget, AnnotateWidget and SignatureWidget
`DrawWidget`, `AnnotateWidget` and `SignatureWidget` have a lot in common but that similarity is not reflected in the code. Capturing that similarity will make it possible to make interface improvements to all three at the same time.

### PR DESCRIPTION
**Pull request by xsteelej**
Closes #943 

#### What has been done to verify that this works as intended?

A combination of tests have been performed:
1) Unit tests already exist, they still pass
2) androidTest (Espresso) tests already exist for the components, they still pass
3) Used the "All Widgets" form to manually check that the Image widgets still behave as expected. I first tested them on a _master_ version of Collect before testing my branch.

#### Why is this the best possible solution? Were any other approaches considered?

The original ask was to remove redundancy in just three Widgets: DrawWidget, SignatureWidget, AnnotateWidget. Upon analysis, it became apparent that AnnotateWidget also had duplicate code that was also present in ImageWidget and AlignedImageWidget. It made sense to also remove redundancy in all widgets that inherited from BaseImageWidget (5 In Total; DrawWidget, SignatureWidget, ImageWidget, AnnotateWidget, AlignedImageWidget).

I considered three approaches, choosing option 3 below:

1) Move all duplicate code up into BaseImageWidget and define abstract methods to enforce subclasses to implement class specific functionality. Discounted this design, although it was fairly neat the impact on the existing structure seemed a little too large.

2) Wrap all the Widgets in decorator classes - Discounted as this seemed like a massive overkill.

3) Create inner _handler_ classes for launching the edit, view, capture image activities inside BaseImageWidget. The widgets then use the most appropriate handler concrete class to fulfil their needs.

Option 3 was chosen because it had less impact on the current structure, whilst removing most of the duplicated code.

#### Are there any risks to merging this code? If so, what are they?

There is a risk that a regression bug could have been introduced into the ImageWidget suite of classes. Every effort has been made to ensure that they work as they currently do, but another thorough test will be needed.

#### Do we need any specific form for testing your changes? If so, please attach one.

The default "All widgets" form can be used

#### Does this change require updates to documentation? If so, please file an issue at https://github.com/opendatakit/docs/issues/new and include the link below.

N/A

### CODE REVIEW

**Comment by lognaturel** [comment]
Looks good to me! Thanks, @xsteelej!

**Comment by mmarciniak90** [comment]
Tested with success!

Verified on Android: 4.1, 4.2, 4.4, 5.1, 6.0, 8.1
I did not notice regression.

Verified:
* ImageWidget, DrawWidget, AnnotateWidget, SignatureWidget, AlignedImageWidget
* horizontal and portrait device orientation
* taking picture and adding from storage
* new and saved form

@opendatakit-bot label "behavior verified"

**Comment by mmarciniak90** [comment]
@opendatakit-bot unlabel "needs testing"

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
Hurray, now that pesky bot will finally leave us alone! ;)

**Pull request merged**
