### PR TITLE
Fix Magenta theme issues

### LINKED ISSUE #3849: Fix visual issues in Magenta theme
The new "experimental" Magenta theme has some visual issues that will need to be fixed before it's ready for primetime:

- [x] Some dialogs in the app use the wrong button styles:

- [x] Search bar has extra 🔍 icon in "Delete saved form" search

- [x] Search view text colors are wrong (see screenshot above)

- [x] On magenta view scroll is not visible until you actually start to scroll what differentiates it from the other modes

It's totally fine if picking this up to just solve one of the issues!

### PR DESCRIPTION
**Pull request by seadowg**
Closes #3849

This gets Magenta to a pretty good place I think. We need to discuss what the next steps will be for Magenta. I'm not sure actually releasing it outside of beta makes sense, but we should now be able to reimplement our Light and Dark themes using the structure we have in place for Magenta. It could be that the Magenta color palette (or something less dramatic) then replaces the Light colors. Potentially moving to a `DayNight` theme would be a good goal for the next release.

#### What has been done to verify that this works as intended?

Played around with the app to check everything looks ok.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Shouldn't have any other effect other than making Magenta less glitchy! Good to check as much of the app as possible.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by lognaturel — CHANGES_REQUESTED** [review]
I propose we merge as-is and ask @getodk/testers to pay attention to the few things that changed in all themes during their v1.28 regression pass. I see preference dialogs and item dividers in form listings. Anything else?

**Review by lognaturel — APPROVED** [review]

**Comment by seadowg** [comment]
I would say the areas to keep an eye on are:

* dialog buttons (they should be "text" buttons)
* dividers in lists
* icon colors

**Comment by lognaturel** [comment]
@getodk/testers I've left the `needs testing` label so you see this but please take it off if it doesn't match your workflow for things that will just be verified in your regression pass!

**Comment by mmarciniak90** [comment]
I spent a while to verify this PR on the master branch.

Verified on Android version: 7.0, 8.1, 10.0

Verified cases:
- Connecting to Server dialog and Cancel buttons - Aggregate, Google Drive
- Search bar
- Search view text colors
- scroll
- `turn on flashlight` button on Gonfigyre via QR code - pink
- `turn on flashlight` button on Barcode widget - pink
- "text" buttons on General Settings and Admin Settings
- buttons and dialogs on MapActivity 
- buttons on GeoWidgets - reported a new issue #4160 
- Liker widget - reported a new issue #4165
- dividers in lists: select one, select multi, views under main menu buttons, hierarchy

@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"

**Pull request merged**
