### PR TITLE
WIP: Enable Fused Location for GeoPoint

### LINKED ISSUE #2717: Switch all location capture to FusedLocationProvider
- [x] Implement changes
- [ ] Explore and document how users can force GPS-only results
- [ ] Understand and document implications for external high-precision GPS sensors
- [ ] Document implications for accuracy and location data availability for user-facing docs

`FusedLocationProvider` is the location provider recommended by Google. It's supposed to balance accuracy, resource usage, etc.

Collect used to use it but in Feb 2018, it started capping accuracy at 10m (https://github.com/opendatakit/collect/issues/2008). This turned out to be [an Android bug](https://issuetracker.google.com/u/0/issues/79189573#comment20) which is now fixed. However, accuracy **[is still capped at 3m](https://issuetracker.google.com/issues/118789585)**.

It would probably make sense for the 3m issue to be addressed before switching back to using it.

Regardless, there are some higher-level questions about whether it's the right way to go. It's supposed to provide better battery management but that's only if less accuracy is acceptable. It may make sense to continue only using the GPS since accuracy is almost always important. That said, there are certain environments (urban) where other location sources may be more accurate. Users could force using the GPS by turning other providers off at the Android level, I think, but that may be harder to use.

This may be a conversation more appropriate for the forum. I wanted to at least file the issue so the content and history is not forgotten but feel free to close and start a thread elsewhere or comment here.

### PR DESCRIPTION
**Pull request by boscacci**
Closes #2717

#### What has been done to verify that this works as intended?

Tested on my Pixel 2XL; now I can take GeoPoints in my local urban canyons. I'd be curious to see how location accuracy performs out in the open though.

#### Why is this the best possible solution? Were any other approaches considered?

Honestly, I just wanted this capability back for myself. Curious to hear from the community whether or not it's a good idea to put it into production, but here's the switch flipped anyhow

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.

There are a few lines of old comments in the code that might be irrelevant now

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

I'm not sure how to do these things. I apologize

### CODE REVIEW

**Comment by yanokwa** [comment]
I'm going to mark this as a WIP because it'll need extensive testing before this ships and I don't want to merge it accidentally.

@mmarciniak90 @kkrawczyk123 Please look at this after we ship the Collect release. I want to make sure we don't change accuracy.

**Review by seadowg — CHANGES_REQUESTED** [review]
@boscacci would you be able to rebase this against master to resolve conflicts?

**Comment by lognaturel** [comment]
Thanks for your patience through the long silence on this, @boscacci. Fundamentally, I don't understand the tradeoffs well enough to make a decision on whether this is beneficial for the majority of users. I do think things are currently in a really confusing state, though (https://github.com/opendatakit/collect/issues/2997), and that we should try to make a thoughtful decision on how Collect accesses location consistently across location question types and basemap options.

Some things I think we should have an understanding of before flipping the switch:
- what happens in environments where only GPS is available (no wifi or cell)? Is only GPS used? Is the same accuracy reported as if the GPS provider were used directly? I don't think this is actually documented and the Fused provider is a total black box so this might require experimentation. I think an exercise such as https://forum.opendatakit.org/t/why-can-t-i-get-as-accurate-gps-position-with-odk-collect-as-i-can-get-with-other-apps/21741 might be helpful.
- how Android settings affect the Fused provider. Specifically, is it actually possible to configure GPS-only behavior if desired and how can we best document this for users.

**Comment by lognaturel** [comment]
Replaced by #3440, slated for completion and release in v1.26.

**Pull request closed without merging**
