### PR TITLE
New color picker

### LINKED ISSUE #1907: Small color picker
#### Software and hardware versions 
Collect v 1.12.2
Android 7.0
Samsung Galaxy S6 edge

#### Problem description

The color picker is very small on the screen and almost impossible to choose the color you want

#### Steps to reproduce the problem

1) Open an image type with draw appearance 
2) Click on plus FAB
3) Click on "Set color"
#### Expected behavior

The color picker should be bigger

#### Screenshots 
28460360_1548389028608050_1981746943_o
28343307_1548387458608207_659312532_o

#### Other information 

I would like to work on it. Also can you provide the right size for it?

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #1907 

#### What has been done to verify that this works as intended?
I've tested the new dialog using `DrawWidget` and `SignatureWidget`.

#### Why is this the best possible solution? Were any other approaches considered?
I used https://github.com/martin-stone/hsv-alpha-color-picker-android

This one looks much better in landscape mode so it's the best option for us.
screenshot_2018-04-24-23-20-13

#### Are there any risks to merging this code? If so, what are they?
Using external dependencies might be always risky. I check output .apk file size and it's the same but we should test that new dialog on various devices to be sure everything is ok.

#### Do we need any specific form for testing your changes? If so, please attach one.
`AllWidgets` form contains needed widgets.

#### Does this change require updates to documentation? If so, please file an issue at https://github.com/opendatakit/docs/issues/new and include the link below.

I'm not sure... maybe we should just update screenshoot. Should I file an issue n such a acase?

### CODE REVIEW

**Review by dcbriccetti — APPROVED** [review]
All the drawing widgets I found in the All Widgets form force the device into landscape, so I wasn’t able to observe this color picker in portrait mode. Was anyone?

**Comment by grzesiek2010** [comment]
> All the drawing widgets I found in the All Widgets form force the device into landscape, so I wasn’t able to observe this color picker in portrait mode. Was anyone?

not in Collect since we use it only in those two places. I think we are not going to enable portrait mode there because as I remember it would require working on some related issues and generally it's not worth it I think.

**Comment by dcbriccetti** [comment]
OK, as long as we’ve tested it in the one possible orientation. Thanks for finishing this task. It’s good to be deleting that custom implementation. We probably should update the documentation if there’s a screen shot of the old, tiny picker. 

@lognaturel, do you want a look at this PR, or shall I go ahead and merge?

**Comment by grzesiek2010** [comment]
> or shall I go ahead and merge

testing should take place before. I know it's a small change but our QAs test each pr :wink:

**Comment by lognaturel** [comment]
I believe the annotate widget will show in portrait when you take a portrait photo. 

@dcbriccetti you can merge once it passes QA, I'm happy with this!

**Comment by mmarciniak90** [comment]
**Tested with success!**

Verified on Android: 4.1, 4.2, 4.4, 5.1, 6.0, 7.0, 8.0.
New color picker looks great on all devices :smile:, also on 3.0 inches screen.

Verified cases:

| text type |  result|
|---|---|
| signature widget | screenshot_20180426-150741|
| annotate widget - horizontal | screenshot_20180426-150536|
| annotate widget - vertical |screenshot_20180426-145926|
| draw widget| screenshot_20180426-145857|

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label  "behavior verified"

**Comment by adammichaelwood** [comment]
For reference:

This change does not require a change in the documentation.

https://docs.opendatakit.org/form-question-types/#image-widget-with-annotation
https://docs.opendatakit.org/form-question-types/#draw-widget

These show the options menu that includes the `Set Color` option,
but they do not show the color picker.

**Pull request merged**
