### PR TITLE
Improves spinner widget

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**

### CODE REVIEW

**Comment by lognaturel** [comment]
It looks like this may have been started from the wrong branch? I think it should be off master and merged into master. 

It's looking better with standard colors! I was looking to see whether there were any material design guidelines for that kind of control and it looks like [this](https://material.io/guidelines/components/buttons.html#buttons-dropdown-buttons) is it. I like that it uses the accent color to show what is selected and that the currently selected value in a normal (non-bold) font. It also looks a little bit more cohesive both because of the thin line at the bottom and because the little arrow is closer to the text choices. What do you think about adding one or both of those?

**Comment by shobhitagarwal1612** [comment]
I will surely take a look at it soon

**Comment by lognaturel** [comment]
Accent color looks fantastic!

I think the reason that "Select One Answer" originally had that unusual color is to make it stand out and suggest that it is tappable. I think that now that it's black it looks very nice but it's not as obviously an object to be interacted with. The example from that material design doc I linked from above is:
screen shot 2017-06-16 at 12 54 07 pm
I think both the thin line below the widget and the fact that the down arrow is closer to the end of the selected answer makes it look more like something that should be tapped. What about just trying the thin line for now? Or do you think there's a` reason it's not appropriate in this context?

**Comment by shobhitagarwal1612** [comment]
Thanks for the suggestions @lognaturel. They are really helpful. It looks much better now. 
I have done the changes, please review

**Comment by lognaturel** [comment]
Fantastic, that looks really nice!!

**Pull request merged**
