### PR TITLE
Fixed handling repeatable groups wrapped with regular ones

### LINKED ISSUE #6015: Crash in the Nested repeats for audit form while removing an empty inner repeat
#### ODK Collect version
2023.3.1. the store version 2024.1.2, the master version 6c6c19d8f1e9b4b89f1d10a31fe698e67e864dd7
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
There is a crash in the 3231 Nested repeats for audit form while removing an empty inner repeat.
 [https://console.firebase.google.com/u/1/project/api-project-322300403941/crashlytics/app/a[…]ey=65DB5F0903B2000171A29DE4E04C99F0_1918010274617643865](https://console.firebase.google.com/u/1/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/ea07d0f482dae5c1119a950eb82e2b0d?time=last-seven-days&types=crash&versions=2024.1.1%20(4793)&sessionEventKey=65DB5F0903B2000171A29DE4E04C99F0_1918010274617643865)
#### Steps to reproduce the problem
1. Open to 3231 Nested repeats for audit form.
[3231nested-repeats-for-audit.xml.txt](https://github.com/getodk/collect/files/14602643/3231nested-repeats-for-audit.xml.txt)

2. Go to the hierarchy view.
3. Tap the arrow 4 times so that you can see outer repeat1, outer group 1, outer repeat 2.
4. Tap Outer group 1.
5. Tap the bin to remove the group (inner repeat 2).
6. In the dialog (Remove group "null” and all of its sub-groups?) tap "Remove group”.
#### Expected behavior
The app shouldn’t crash

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #6015 

#### Why is this the best possible solution? Were any other approaches considered?
We had at least two issues with this case when a repeatable group was wrapped with a regular one:
1. The fact that the regular group in the hierarchy was visible as a removable one. I've described it in https://github.com/getodk/collect/issues/6015#issuecomment-2068924271
2. A wrong path was displayed in the hierarchy when navigating up.

I think I've fixed both issues using the appropriate form index.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
The pr is not big but I find it risky. We need to test the hierarchy view with nested groups (repeatable and regular ones) to make sure they are displayed in the correct way. @dbemke @srujner @WKobus please be creative and create your own forms ideally with multiple levels of nested groups.

#### Do we need any specific form for testing your changes? If so, please attach one.
The form I've attached in this comment: https://github.com/getodk/collect/issues/6015#issuecomment-2068924271

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by seadowg — APPROVED** [review]

**Comment by seadowg** [comment]
Given that @grzesiek2010 has flagged this as risky, I'll wait to merge until after testing.

**Comment by dbemke** [comment]
I tried removing groups in the form 
[groups_crash(1).xlsx.txt](https://github.com/getodk/collect/files/15319441/groups_crash.1.xlsx.txt)
and there is a crash. I removed a group from the place shown in the screenshot - is it the same case or different as in the issue?
casrhRepeat

**Comment by dbemke** [comment]
There is a difference between the way group/ repeats are shown in 
[3231nested-repeats-for-audit.xml.txt](https://github.com/getodk/collect/files/15330943/3231nested-repeats-for-audit.xml.txt). 
Which one is the expected one?
The light mode is the PR version, the dark mode is the master version.
A different icon:
iconsRepeats

Difference in the way outer > inner is shown:
2023vrPR

**Comment by grzesiek2010** [comment]
To me the PR version works correctly and what you see on the master branch and older versions was wrong, for example the duplicate section `Inner repeat 2` in the path (the second example) or the `Inner repeat 2 > 1` displayed where you are on the outer (regular group) level (the first example).

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on a device with Android 10

**Verified Cases:**
- issue #6015 doesn’t occur
- repeat groups in regular groups (with and without a question in it)
- nested repeats
- removing group in the hierarchy view
- how repeats are shown (paths, icons) in the hierarchy view
- repeat group containing a field-list
- regression checks in repeat forms (forms with indexed repeat, repeat_count, nested repeats)

**Comment by WKobus** [comment]
**Tested with Success!**

Verified on a device with Android 14

**Pull request merged**
