### PR TITLE
Fixes crash on device rotation in Server Preferences

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**

### CODE REVIEW

**Comment by shobhitagarwal1612** [comment]
Fixes #1191

**Review by lognaturel — APPROVED** [review]
@mmarciniak90 will give a final validation!

**Comment by mmarciniak90** [comment]
Crash does not occur but I noticed other unexpected behavior.
**Use case:**
1. User goes to General Settings
2. User goes to Server
3. User changes device orientation
4. User is moved to General Settings (bug: #1184)
5. User changes device orientation again
6. User clicks device back button
7. Header line gets thicker  :heavy_exclamation_mark: To leave setting user need to click again on device back button
8. User clicks on server
9. User sees unexpected combination of two views
screenshot_20170622-204454
screenshot_20170622-204457
screenshot_20170622-204500

**Comment by lognaturel** [comment]
@mmarciniak90 Thank you! I think this is related to #1184. @shobhitagarwal1612 has come across a similar situation before with the stacked windows.

How about we merging this and filing a separate issue or adding it to #1184?

**Comment by shobhitagarwal1612** [comment]
@mmarciniak90 Thanks for reporting it!
@lognaturel I agree with you. We should use this fix to prevent the crash. I'll fix this along with #1184. Thoughts?

**Comment by lognaturel** [comment]
That sounds great, @shobhitagarwal1612. I'll add it as a comment to #1184. Thanks, @mmarciniak90!

**Comment by mmarciniak90** [comment]
@opendatakit-bot unlabel "needs testing"

**Pull request merged**
