### PR TITLE
Use Expandable Notification for Match Exactly errors

### LINKED ISSUE #4018: User is not able to read the whole error message when `Exactly match server` is set
#### Software and hardware versions 
Collect master with #3986 

#### Problem description
User is not able to read the whole error message when `Exactly match server` is set

#### Steps to reproduce the problem
Use case 1:
1. `Exactly match server` is set
2. User adds not existing aggregate URL 
3. User sees notification with message but there is no option to read the whole message
4. If user clicks on it, user is moved to `Fill Blank Form` list and the refresh icon is red.

Screenshot_20200810-103540

Use case 2:
1. `Exactly match server` is set and there is no internet connection
2. User sees notification with message but there is no option to read the whole message

Screenshot_20200810-101735

#### Expected behavior
Dialog with the whole message is visible when user clicks on notification with error
OR if we don't want to show dialog
Whole message is visible in the notification

### PR DESCRIPTION
**Pull request by seadowg**
Closes #4018.

Longer error messages will now display in an expandable/collapsible notification rather than being cut off.

#### What has been done to verify that this works as intended?

Verified manually.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Good to just check notifications for Match Exactly all make sense.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
The behavior varies by Android version and probably by form factor (e.g. on Galaxy Tab A I only see the title and need to drag down on the notification to see any details) but I imagine this is probably as good as it gets.

**Comment by mmarciniak90** [comment]
I worked on testing this issue on Android versions: 7.0, 8.1, 9.0
Only on Android 7.0, the full notification message is hidden. There is an arrow expanding the message so, it's not a big deal but I wanted to point it out. @kkrawczyk123 can you look at this also on other Android versions?


Verified cases:

|Aggregate| |
|---|---|
|no internet connection / aeroplane mode | Aggregate does not exist / incorrect username or password|
|Screenshot_20200901-164839|Screenshot_20200901-165007|

|Central| |
|---|---|
|no internet connection / aeroplane mode | Central's project does not exist|
|Screenshot_20200901-171540|Screenshot_20200901-171618|

* User is able to collapse and expand message

**Comment by kkrawczyk123** [comment]
I can't see any issues on my Androids 5.1, 7.1 and 10 as well but I do not understand why the recently added "No network available" toast for offline cases in #4020 has been changed in that PR and actually makes things more complicated. 

@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"

**Comment by seadowg** [comment]
> I do not understand why the recently added "No network available" toast for offline cases in #4020 has been changed

@kkrawczyk123 ah that just seems that way because this PR branches off some earlier commits than master. When this merges that behaviour will still be there (hopefully)!

**Pull request merged**
