### PR TITLE
Fixed the ActivityNotFoundException in GoogleAccountsManager class

### LINKED ISSUE #2434: No Activity found to handle Intent { act=com.google.android.gms.common.account.CHOOSE_ACCOUNT pkg=com.google.android.gms (has extras) }
[From Crashlytics](https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/5b3379b66007d59fcdf8b27f?time=last-seven-days&sessionId=5B5D61DF012D00010035C2A293D82638_DNE_0_v2) (requires auth):

```
android.app.Instrumentation.checkStartActivityResult (Instrumentation.java:1657)
arrow_drop_down
android.app.Fragment.startActivityForResult (Fragment.java:1058)
arrow_right
org.odk.collect.android.utilities.gdrive.GoogleAccountsManager.showAccountPickerDialog (GoogleAccountsManager.java:184)
org.odk.collect.android.utilities.gdrive.GoogleAccountsManager.chooseAccount (GoogleAccountsManager.java:152)
org.odk.collect.android.preferences.ServerPreferencesFragment$2.onPreferenceClick (ServerPreferencesFragment.java:224)
android.preference.Preference.performClick (Preference.java:952)
arrow_drop_down
dalvik.system.NativeStart.main (NativeStart.java)
```

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #2434 

The issue occurs only in `Server Settings` while trying to select an account, in all other places we handle the mentioned exception.

#### What has been done to verify that this works as intended?
I was able to reproduce the issue on one of our devices so I confirmed that it doesn't crash anymore and an appropriate message is displayed.

#### Why is this the best possible solution? Were any other approaches considered?
The only thing we can do here checking if an activity we want to start is available, if not we should display an appropriate message.

#### Are there any risks to merging this code? If so, what are they?
No.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew pmd checkstyle lintDebug spotbugsDebug` and confirmed all checks still pass.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by jd-alexander — APPROVED** [review]
Looks good!

**Comment by shobhitagarwal1612** [comment]
In my opinion, we should not handle the case when activity is not available in this class. Instead, there should be another method added to `GoogleAccountSelectionListener` like `onError()` which should be called. Then the implementing activity should handle the case accordingly.

For eg. In `GoogleDriveActivity`, it would be much user-friendly if a dialog appears with an appropriate message and dismissing it finishes the activity as well. 

@grzesiek2010 What do you think?

**Comment by grzesiek2010** [comment]
@shobhitagarwal1612 

thanks, your question/proposal reminded me that we already have a util class to check Google Play Services and that should be used.
If there is something wrong a dialog is displayed:
screenshot_2018-08-02-00-46-00

maybe the message is not perfect but that's what we use in other classes too.

please take a look again.

**Comment by shobhitagarwal1612** [comment]
:+1: Maybe `Google Play Services Missing!` would be more accurate but this approach does seem better

**Comment by grzesiek2010** [comment]
> Maybe Google Play Services Missing! would be more accurate but this approach does seem better

but we don't define that message it comes from https://developers.google.com/android/reference/com/google/android/gms/common/GoogleApiAvailability.html#getErrorDialog(android.app.Activity, int, int)

**Comment by grzesiek2010** [comment]
@shobhitagarwal1612 you have given thumbs up but you haven't accepted changes? Is there anything wrong here?

**Comment by shobhitagarwal1612** [comment]
@grzesiek2010 The latest changes you pushed only fixed the issue for the preferences screen and not everywhere else. So I thought that this PR is still WIP

**Comment by grzesiek2010** [comment]
> The latest changes you pushed only fixed the issue for the preferences screen and not everywhere else. So I thought that this PR is still WIP

The issue occurs only there. In all other cases that dialog is displayed and it's already handled.
I've just updated the description.

**Review by shobhitagarwal1612 — APPROVED** [review]
@opendatakit-bot label "needs testing"

**Comment by mmarciniak90** [comment]
**Tested with success!**

Verified on Android 4,1, 4.2 (Infinix), 4.2.2 (Samsung Duos GT-S7582)
I disabled Google Play Services. I was not able to do this on the other Android versions.
Compared with v1.16.2 where the crash occurred on Server settings view.
I did not notice the impact on other Android versions.

Verified cases:
* General Settings -> Server
* Get Blank Form
* Send Finalized Form

|before fix|after fix|
|---|---|
|screenshot_2018-08-10-11-23-30|screenshot_2018-08-10-11-51-07|

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Pull request merged**
