### PR TITLE
Remove null pointer exception bug on getVersionedAppName() method

### PR DESCRIPTION
**Pull request by thegenuinegourav**
Updated gradle file to target 25 SDK instead of 22 Plus Solved the App crash Bug on getVersionedAppName() method due to null pointer exception

### CODE REVIEW

**Comment by lognaturel** [comment]
@thegenuinegourav We've actually deliberately chosen to target SDK 22 because there are UI implications to changing it. Updating it could be something that is done as part of the UI refresh.

Can you please try to trace why `versionName` is null? Is it possible that it's because you don't have the git command line application installed? I'll make sure to add that to the getting started guide!

**Comment by thegenuinegourav** [comment]
No it has nothing to do with git command line application install provided my system have this properly installed! Still debugging whats wrong with versionName part.

**Comment by lognaturel** [comment]
@thegenuinegourav Interesting! Do keep us posted on what you find out. It would be nice to get this fixed at the root since there should always be a version name displayed.

**Comment by thegenuinegourav** [comment]
Hope this helps https://github.com/opendatakit/collect/pull/473

**Pull request closed without merging**
