### PR TITLE
Changing device orientation affects the appearance in RTL languages on Android 8.1

### LINKED ISSUE #2265: Changing device orientation affects the appearance in RTL languages on Android 8.1
#### Software and hardware versions 
Collect v1.15.0
Android 8.1
RTL language
'Do not keep activities' turned OFF

#### Problem description
A part of views are returned to LTR appearance after change device orientation

#### Steps to reproduce the problem
1. The user uses RTL language

|screenshot_20180605-161231|screenshot_20180605-161221|screenshot_20180605-161217|screenshot_20180605-161336|
|---|---|---|---|

2. The user changes device orientation
3. Views are moved to LTR appearance

|screenshot_20180605-161239|screenshot_20180605-161342|screenshot_20180605-161317|screenshot_20180605-161244|
|---|---|---|---|

#### Expected behavior
Changing device orientation does not affect the appearance in RTL languages

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #2265

#### What has been done to verify that this works as intended?
Tested on Android 8.1 and Android 5.1.1

#### Why is this the best possible solution? Were any other approaches considered?
It's a solution recommended on many sites eg. https://gunhansancar.com/change-language-programmatically-in-android/ and it's the only one.

#### Are there any risks to merging this code? If so, what are they?
Yes, I changed updating languages so it' should be tested. I mean switching between different languages.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew pmd checkstyle lint findbugs` and confirmed all checks still pass.
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by mmarciniak90** [comment]
@grzesiek2010 I usualy use RTL laguage visible on screen

Almost all texts were translated, which you can see on screen:

After these changes I do not see translated texts

Translations are applied when I select language located above.

**Comment by mmarciniak90** [comment]
@opendatakit-bot unlabel "needs testing"

**Comment by grzesiek2010** [comment]
Ok, I fixed the problem you can continue testing @mmarciniak90 
@opendatakit-bot label "needs testing"

**Comment by mmarciniak90** [comment]
**Tested with success!**

Verified on Android 8.1. I did not notice regression on Android 5.1, 6.0.
Verified cases:
* 3 RTL languages
* light and dark theme
* changing device orientation

@opendatakit-bot label "behavior verified"
@opendatakit-bot unlabel "needs testing"

**Review by lognaturel — APPROVED** [review]

**Pull request merged**
