### PR TITLE
Adaptation problem in RTL languages, Fix issue#1981

### LINKED ISSUE #1981: RTL writing system is not visible on all views
#### Software and hardware versions 
Collect v1.13.2
Devices with Android: 4.1, 4.2, 4.4, 6.0, 7.0, 8.0.

#### Problem description
RTL writing system is not visible on all views 

#### Steps to reproduce the problem
1. User uses Collect on RTL language
2. User opens Fill Blank Form / Get Blank Form / Delete Saved Form or starts filling some form
3. User sees that text is not start from the right of the page and continues to the left.

#### Expected behavior
* User sees text which starts from the right of the page and continues to the left on all views
* On one of my devices to tests - Huawei Y5 with Android 5.1 - RTL languages works as expected on most of all views.

#### Examples

| View | Android 6.0 - Moto G4 | Android 5.1 - Huawei Y5 | 
| ---- | ---- | ---- |
| Get Blank Form | screenshot_20180307-164007 | screenshot_2018-03-07-14-40-09 | 
| Fill Blank Form | screenshot_20180307-163619 | screenshot_2018-03-07-14-37-37 | 
| Simple widget | screenshot_20180307-163716 | screenshot_2018-03-07-14-37-30 | 
| Select one quick appearance | screenshot_20180307-164733 | screenshot_2018-03-07-14-46-32|

### PR DESCRIPTION
**Pull request by huangyz0918**
Closes #1981 

#### What has been done to verify that this works as intended?
I modified the `style.xml / theme.xml` files in Project, Fix the TextView and EditText adaptation problem with RTL language, and test these changes with several devices, they all worked well.

Here are some test records:

__Form and Form list:__

|   Samsung Galaxy S8 (Android 7.0)           |  Samsung Galaxy S4 (Android 4.2)      |
| ---- | :----: |
|||
|||
|||
|||

__About items:__

|   Before          |  After      |
| ---- | :----: |
|||
|||

#### Why is this the best possible solution? Were any other approaches considered?
To modify the `style.xml` file is the best solution with code changes. We can consider many ways to address RTL problems, such as: 

- Detect language in Java code and force views to reverse under RTL language environment
- Change layout value in xml files, add some RTL-support parameters.
- Modify `style.xml` or `theme.xml`.
- Use Android Studio to create new layout files to adapt devices under API 17.
- Use some third-part library (such as :[gradle-android-rtl](https://github.com/znyang/gradle-android-rtl) and [rtl-viewpager](https://github.com/duolingo/rtl-viewpager)) to support RTL adaptions.

We can use them in combination and finally solve these problems. I will continue improving RTL adaption in our project and make more tests.

#### Are there any risks to merging this code? If so, what are they?
Na
#### Do we need any specific form for testing your changes? If so, please attach one.
My changes based on API level >= 17, for API level 16, I have tested one before, it worked ok.
So we don't need a further testing I think, at least we have improved devices with higher API than 16.

### CODE REVIEW

**Comment by lognaturel** [comment]
This is looking really good, @huangyz0918! 👏 

It looks like the second commit created a bad diff by making old changes to files look new. I'm not exactly sure how to fix it but the first thing I would try is `git fetch upstream` followed by `git rebase upstream/master`. You will then have to do a `push --force`.

**Comment by huangyz0918** [comment]
Thanks! 
I found when I update my repo, I committed some unrelated changes :(
So I close this PR and back to checking my code make sure they are clean.
After that I will open a new PR with clean code and additional function change.

**Comment by lognaturel** [comment]
Ok! You can also use this as an opportunity to learn about more advanced git functionality -- https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History. It should absolutely be possible to recover with the same branch and pull request. Did you try my suggestion to start with?

**Comment by huangyz0918** [comment]
@lognaturel Thank you for your suggestion~
I have fixed some problems with my local repo.Besides, I created a new remote named `upstream` in my local repo, I can use it to update my fork repo with ODK Collect !
I opened a new PR, and I think it may look better :>

**Pull request closed without merging**
