### PR TITLE
Remove check for Aggregate 0.9 legacy servers when adding media attachments

### LINKED ISSUE #3037: Only jpg attachments are sent to servers that don't provide a Location header in response to the HEAD request
#### Software and hardware versions 
Collect v1.21.1

#### Problem description
Servers that don't provide a `Location` header in response to the `HEAD` request don't receive file attachments other than jpg.

See https://github.com/opendatakit/aggregate/issues/455 and https://github.com/opendatakit/central/issues/47

#### Steps to reproduce the problem
Try to send an attachment other than a jpg to Central.

#### Expected behavior
Files of any type should be sent to any server regardless of the `HEAD` request response.

#### Other information 
We will call this "a warning against spaghetti code."

### PR DESCRIPTION
**Pull request by lognaturel**
Closes #3037

#### What has been done to verify that this works as intended?
Used the All Widgets form with Central. Attached a jpg image and a wav sound file. Confirmed that only the jpg is sent from `master`. Tried it again with this change and confirmed that the jpg and wav are both sent.

#### Why is this the best possible solution? Were any other approaches considered?
I considered checking the `X-OpenRosa-Version` header instead but really, there's no reason to support Aggregate 0.9 anymore. It's 8 years old and was only in production for a short time.

I aspired to write a test for this and spent some time thinking about how I could decouple things to make it testable but I decided that makes the change riskier than it needs to be for now.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Users will be able to send arbitrary attachments to servers that don't send the `Location` header in response to the `HEAD` request.

#### Do we need any specific form for testing your changes? If so, please attach one.
Any form with non-jpg attachments. All Widgets works well.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by ggalmazor** [comment]
I've found this block in `InstanceServerUploader#119`: 
```java
} else if (headResult.getStatusCode() == HttpsURLConnection.HTTP_NO_CONTENT) {
    // Redirect header received
    if (responseHeaders.containsKey("Location")) {
        try {
            Uri newURI = Uri.parse(URLDecoder.decode(responseHeaders.get("Location"), "utf-8"));
            // Allow redirects within same host. This could be redirecting to HTTPS.
            if (submissionUri.getHost().equalsIgnoreCase(newURI.getHost())) {
                // Re-add params if server didn't respond with params
                if (newURI.getQuery() == null) {
                    newURI = newURI.buildUpon()
                            .encodedQuery(submissionUri.getEncodedQuery())
                            .build();
                }
                uriRemap.put(submissionUri, newURI);
                submissionUri = newURI;
            } else {
                // Don't follow a redirection attempt to a different host.
                // We can't tell if this is a spoof or not.
                saveFailedStatusToDatabase(instance);
                throw new UploadException(FAIL
                        + "Unexpected redirection attempt to a different host: "
                        + newURI.toString());
            }
        } catch (Exception e) {
            saveFailedStatusToDatabase(instance);
            throw new UploadException(FAIL + urlString + " " + e.toString());
        }
    }
}
```

Do you think we still need it? If not, I think we should remove it as well. By removing that block, the `uriRemap` member can be removed as well because it's not updated anywhere (always an empty map).

**Comment by ggalmazor** [comment]
I've gone ahead and tried to work out how to safely remove the block: https://github.com/ggalmazor/collect/commit/86237ae547fb77bac30185d0fb04428c2df47ef2

I think we should take the chance to do it to completely remove any trace of Collect processing the `Location` header at all, but I might be unaware of other risks of doing so.

I've checked that no other place looks for that header, and that there's no other use for the `uriRemap` map other than changing the submission url to whatever comes in the header's value (which, by the way, could be unsafe to do in some Aggregate deployment configurations).

I've verified the change by running an emulated Collect against a local Aggregate server and sending a form with a WAV and a JPG files, and then checking in Aggregate that both attachments got to the server.

**Review by ggalmazor — APPROVED** [review]
Looking good to me! Approving.

I've made a couple of comments with some extra changes we could add to this PR for your consideration.

**Comment by lognaturel** [comment]
@ggalmazor For this issue, I see the problem as the `Location` header being used to filter out what binary types are sent. Which is kind of terrifying behavior anyway -- there was no user feedback on that filtering, files were just silently omitted.

I don't feel confident that taking out the whole redirect infrastructure won't affect users of other servers. I know redirects are supposed to be done with a 3xx status code but https://docs.opendatakit.org/openrosa-form-submission/#extended-transmission-considerations implies redirect and 204 are expected together.

That said, it sure would be great to remove that code. If we Just Do It, that means that on Collect upgrade, some users may no longer be able to submit. They wouldn't lose any data, though, just time. @yanokwa, perhaps you want to weigh in on that?

Edit: this was added in the very first implementation at https://github.com/opendatakit/collect/commit/520d3c57f8420a2541b1cb943930a15defc07fca

Edit: another bad case would be if a server can accept submissions at /formUpload but redirects under certain conditions. Then data would go to the wrong place.

**Comment by lognaturel** [comment]
Oh, and there is also https://github.com/opendatakit/collect/issues/1577 which suggests more broadly accepting redirects.

**Review by grzesiek2010 — APPROVED** [review]

**Comment by yanokwa** [comment]
I've discussed this with @lognaturel and I agree with her narrow approach. I think it's very unlikely that someone has .9 server in production and so that's very low risk and fixes the more urgent issue.

@ggalmazor's suggestion of the broader change is a good one, but we should discuss it at https://github.com/opendatakit/collect/issues/1577 and try to get a good plan in place.

**Review by huangyz0918 — APPROVED** [review]

**Comment by mmarciniak90** [comment]
@lognaturel I noticed that Collect crashes when I swipe to `Selfie widget` or `Selfie video widget`. 

This crash is visible on Android 4.2. 
In this case, I check this behavior for Android 4.1 and the crash is also visible.

Here is a log with the crash
[crash.txt](https://github.com/opendatakit/collect/files/3130902/crash.txt)

**Comment by mmarciniak90** [comment]
@lognaturel, master branch also crashes.

**Comment by lognaturel** [comment]
Thanks, everyone!

@mmarciniak90, would be good to get a ticket for the crash since it's a regression (generally supporting Android 4.x should be pretty low priority). Is it possible there was another stacktrace, though? That one doesn't look like it would impact users.

**Comment by mmarciniak90** [comment]
@lognaturel I created a separate issue for the crash. I added attachments with full logs.

**Comment by mmarciniak90** [comment]
**Tested with success.**

Verified on Android: 4.4, 5.1, 6.0, 7.0, 8.1

Verified form [media.xml.txt](https://github.com/opendatakit/collect/files/3153010/media.xml.txt).

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Pull request merged**
