### PR TITLE
Exception java.lang.RuntimeException: An error occurred while executing doInBackground()

### LINKED ISSUE #1208: Exception java.lang.RuntimeException: An error occurred while executing doInBackground()
#### Software and hardware versions 
Collect v1.8.0

Logs from firebase:

`Caused by java.lang.NullPointerException: Attempt to invoke direct method 'java.io.File org.odk.collect.android.tasks.DownloadFormsTask$FileResult.getFile()' on a null object reference
org.odk.collect.android.tasks.DownloadFormsTask$FileResult.access$000 (DownloadFormsTask.java:540)
org.odk.collect.android.tasks.DownloadFormsTask.checkForBadSubmissionUrl (DownloadFormsTask.java:201)
org.odk.collect.android.tasks.DownloadFormsTask.doInBackground (DownloadFormsTask.java:154)
org.odk.collect.android.tasks.DownloadFormsTask.doInBackground (DownloadFormsTask.java:67)
android.os.AsyncTask$2.call (AsyncTask.java:295)
java.util.concurrent.FutureTask.run (FutureTask.java:237)
android.os.AsyncTask$SerialExecutor$1.run (AsyncTask.java:234)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1113)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:588)
java.lang.Thread.run (Thread.java:818)`

### PR DESCRIPTION
**Pull request by grzesiek2010**
This PR is in reference to resolve #1208

### CODE REVIEW

**Comment by lognaturel** [comment]
Thank you, @grzesiek2010! @mmarciniak90 this is something we will release as a patch so would be good to prioritize.

**Comment by lognaturel** [comment]
Now that I think about it, I think this would be ok for a reviewer to merge without an extra testing pass since it's pretty clear what the problem was and that the fix addresses it. 

I'll still give @mmarciniak90 some time to look at it if you want since it will be at least another day before we get the patch release done.

**Review by lognaturel — APPROVED** [review]

**Comment by grzesiek2010** [comment]
@lognaturel I agree it's not very important to test it by @mmarciniak90

**Comment by mmarciniak90** [comment]
@opendatakit-bot unlabel "needs testing"

**Pull request merged**
