### PR TITLE
Buildtools Upgrade

### LINKED ISSUE #243: Upgrade buildtools
Our build tools are on an old version. Upgrade the gradle file to support the latest version and confirm the app builds and works.

### PR DESCRIPTION
**Pull request by avin-sharma**
Fixes #243 
Upgraded buildtools to the current latest (25.0.0)

### CODE REVIEW

**Comment by yanokwa** [comment]
Hi @avin-sharma! Thanks for the PR. I think the tests are failing because you did not also edit the circle.yml file to include build-tools-25.0.0. Could you add that to the PR?

@lognaturel Are all the build-tools-X and android-X are needed?

**Comment by avin-sharma** [comment]
Hi @yanokwa ! Edited the circle.yml file to include build-tools-25.0.0 and the tests were successful. 
Also accidentally closed the PR sorry about that.

**Comment by lognaturel** [comment]
@yanokwa No, we don't need more than one version. @avin-sharma, can you please make one more edit to circle.yml to only include build-tools-25.0.0 (that is, remove 22.0.0) and only include android-22 and then we can merge? Thanks! 😊

**Comment by lognaturel** [comment]
🎉 Thanks, @avin-sharma! If you're looking at other issues and ever have any questions or thoughts on how they should be approached, don't hesitate to comment.

**Comment by avin-sharma** [comment]
@yanokwa @lognaturel Thankyou.
This was my first ever contribution to open source, the experience was positive and welcoming.
Hope i can add more value as i learn more.

**Pull request merged**
