### PR TITLE
Fixes back button when navigating "My Drive" goes all the way back to root

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Addresses #741

### CODE REVIEW

**Comment by lognaturel** [comment]
Nice, the back button behavior is 👌👌. It looks like search no longer works, though!

**Comment by shobhitagarwal1612** [comment]
@lognaturel Fixed

**Comment by lognaturel** [comment]
@shobhitagarwal1612 if you were curious why the corresponding issue wasn't closed automatically, it's because GitHub doesn't consider "addresses" a keyword for closing issues! See [here](https://help.github.com/articles/closing-issues-via-commit-messages/) for the ones that work.

I tend to forget to go back to make sure issues were closed automatically so thanks for helping us clean up. 😄

**Comment by shobhitagarwal1612** [comment]
Thanks for the reminder

**Pull request merged**
