### PR TITLE
Delete after send option doesn't work

### LINKED ISSUE #1129: Delete after send option doesn't work
#### Software and hardware versions 
Collect v1.7.1

#### Steps to reproduce the problem
1. Check "Delete after send" option in "General Settings"
2. Complete any form
2. Go to "Send Finalized Form" and send that form

#### Expected behavior
That instance should be deleted automatically.

#### Other information 
It's caused by https://github.com/opendatakit/collect/pull/574/files#diff-b569288bc988dd4905e004c69dbba56dL660

@lakshyagupta21 could you explain why you changed `STATUS_SUBMITTED` to `STATUS_COMPLETE` because I don't understand why we need that.

### PR DESCRIPTION
**Pull request by grzesiek2010**
This PR is in reference to resolve #1129

### CODE REVIEW

**Comment by nribeka** [comment]
@grzesiek2010 this PR makes me wondering with the approach that we took around your changes inside the onPostExecute method.

The onPostExecute:
* received all ids that was submitted inside the Outcome object
* we then iterate the Outcome's keys to get the InstanceColumns._ID values
* we then query the instance table to get the ids that we will pass to DeleteInstancesTask

Shouldn't we just pass the keys from the outcome object to the DeleteInstanceTask since they're the same id in the first place? Or am I missing anything here?

**Comment by grzesiek2010** [comment]
@nribeka 
We can't to that for example one of those ids in the key set might have SUBMISSION_FAILED status so we need to read from database and check the status.

**Comment by nribeka** [comment]
@grzesiek2010 
the outcome object use the failure status and store it as a string only. I thought it would store the status as a flag to mark whether it was submitted successfully or not. This would avoid the need to do extra query (potentially with slicing) and extra iteration to just get the same exact id from the db.

**Comment by grzesiek2010** [comment]
@nribeka 
As I noticed the outcome object might contain for example:

> full submission upload was successful!

or 

> Error: Bad Request (400) at https://opendatakit.appspot.com/submission?deviceID=imei%3A356002063918359

and it's a message from the server so I'm not sure if it's not dangerous to check that string because someone might change the default successful string from `full submission upload was successful!` to something else.

and even if you are right I'm not in favour of doing that refactoring as a part of this pr. If you have an idea you can add your pr or file an issue the I can take it if you are busy.

**Comment by lognaturel** [comment]
@nribeka Thanks for your comments, I do agree there could be some refactoring done around this code! Isn't it the case that the delete after send preference could be checked before building the query?

While @grzesiek2010 is correct that checking against the success string is a really bad idea, how about checking if the outcome `.startsWith(InstanceUploaderTask.fail` (which should really be `FAIL` or `ERROR_STRING` or something)?

I agree that these are separate from the issue this solves. I'll merge this and then please do submit some refactoring!

**Pull request merged**
