### PR TITLE
Make sure soft-deleted form can be re-downloaded

### LINKED ISSUE #4026: Deleting blank forms after sending submission is broken and makes forms unseable
#### Software and hardware versions 
Collect v1.28.x, Android v all, device used...

#### Problem description
When I was testing Central and switching between projects I have noticed Collect issue that after sending submission and deleting form using Collect Delete blank form - form is not really deleted. It is still visible in form folder but it is not visible on Collects UI. On Get Blank form in Collect checkbox is not selected by default but form is not visible on fill blank form and even after downloading form once again it is still not visible in fill blank form.

#### Steps to reproduce the problem
1. Download any form from any server (I was able to reproduce for Aggregate and Central)
2. Fill submission
3. Send submission 
4. Delete saved form and blank form 
5. See that form is still visible in form folder even if it has been deleted
6. Go back to Collect and see that fill blank form list is empty
7. Go to Get Blank form - checkbox next to form is not even selected
8. Download the same form once again 
9. Open Fill Blank Form list is still empty 

gif of reproduction steps:
deleteform

#### Expected behavior
- Form should be deleted after using Delete Saved Form in Collect and not visible in form folder and via Collects ui
- After deleting form it should be selected by default to download on get blank form list
- After downloading form once again it should be visible on fill blank form list and be useable by user

#### Other information 
- I was not able to reproduce this issue on 1.27.3 so it is regression connected to soft delete
- I was not able to reproduce that issue for blank form only
- I was not able to reproduce that issue for blank form and saved/filled submission - sending submission step is pivotal

@getodk-bot label "regression"

### PR DESCRIPTION
**Pull request by seadowg**
Closes #4026

#### What has been done to verify that this works as intended?

Manually verified and wrote new test.

#### Why is this the best possible solution? Were any other approaches considered?

I'm not a fan of testing this at an Espresso level. I started at writing tests at a lower level but it would mean a bit of a complicated dance around the `MultiFormDownloader` and `ServerFormDownloader`. I think this would get everything to a better place and potentially mean killing the `MultiFormDownloader` which would be nice. I'm going to continue that work immediately but didn't want to hold the regression fix up or add more risk to it.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Good to just check the issue is fixed and that form download still seems to be working!

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by lognaturel — APPROVED** [review]

**Comment by mmarciniak90** [comment]
@seadowg I follow repro steps from #4026 
I can confirm that I'm able to download a form and it's visible on the `Fill Blank Form` view. 
But I also noticed one unexpected thing. 
When I download a form for a second time, the time visible on `Fill Blank Form` list shows the time of the first download -> that's mean the form has not been removed. I'm worried that forms for which user sent submission are never removed from device.

**Comment by seadowg** [comment]
@mmarciniak90 ah I think there might be a problem where submitted/sent filled forms are never deleted from the database (but their files are) so when we work out whether to do a soft delete or a full delete of the actual form we think there is still an "instance" (filled form). Could you try deleting forms with and without filled forms and with and without those filled forms being sent? I'll investigate this in the code as well.

**Comment by seadowg** [comment]
@mmarciniak90 just to clarify I mean filled forms that are submitted **and then** deleted. We definitely want to soft delete forms that have submitted instances that **are not** deleted as they would still be viewable in the app.

**Comment by seadowg** [comment]
@mmarciniak90 ok blank forms should now be deleted as expected when it and its submitted instances are filled forms are deleted

**Comment by mmarciniak90** [comment]
**Tested with success**

Verified on Android versions: 7.0, 8.1, 9.0

Verified cases:
* steps from the issue ->  I'm able to download a form and it's visible on the Fill Blank Form view (also after the latest changes)
* if the sent submission is removed and form is removed -> form is totally removed from device, form is not available in form directory
* if the (sent) submission is NOT removed but form is removed -> form is still available in form directory but it's not visible on `Fill Blank Form` list. When user downloads it again, form appears on list and the time of the first download is visible under form name
* reset removes all files
* Match exactly is set ->  the (sent) submission is NOT removed -> Aggregate server is changed to another Aggregate server -> refresh button is clicked -> form list is reloaded, forms from the second server appear, form from the first server is still available in form directory but it's not visible on `Fill Blank Form` list. When submission is removed -> form is also removed from directory

In my opinion, this PR is worth double checking, @kkrawczyk123

**Comment by kkrawczyk123** [comment]
Verified with success on Androids 5.1, 7.1 and 10. 

@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"

**Pull request merged**
