### PR TITLE
Collect does not resize large annotated images. #121

### PR DESCRIPTION
**Pull request by max2me**
This is for #121 issue.

In general it seems like there are 2 nuances that led to that behavior:
* Even though draw activity requests landscape orientation, calculations could be done while it's still in portrait mode (which affects screen width & height).
* FileUtils.getBitmapScaledToDisplay() uses sampling for loading images which means exact size of loaded image can be impresize.

Tested changes on the phone in portrait & landscape:
* Taking a landscape picture, then sketching
* Taking a portrait picture, then sketching
* Choosing a landscape picture, then sketching
* Choosing a portrait picture, then sketching

### CODE REVIEW

**Comment by max2me** [comment]
@lognaturel It would be great if you could test it on tablet, I dont have one and emulator on my machine aint working (takes forever to start and then it's super slow). I might have to look into upgrading PC as its CPU is rather old.

**Comment by lognaturel** [comment]
I unfortunately don't have a hardware tablet either. I tried it on an emulated Nexus 10, though, and it looks good!

The only issue I'm seeing is that when the image doesn't fill the screen's width when it's scaled to fill the height, there is a gray bar added to the right:
- choose image with a width smaller than the screen
- tap markup, it gets displayed with some gray to the right
- tap save and close, the gray is still there
I verified it's part of the image saved to the sdcard, too.

Ideally the image would be centered horizontally in that case and the buffer pixels would not be added to the image.

**Comment by max2me** [comment]
@lognaturel This should be addressed now. Initially pursued direction of simply adjusting size of the view to the size of bitmap but that proved to be a dead end because of the hack to account for landscape orientation. So I ended up simply shifting position of the bitmap in order to center it (as well as maintaining) a copy of the path with adjusted coordinates.

Tested on both landscape and portrait images. Please take a look.

**Comment by lognaturel** [comment]
@yanokwa I think we should merge this. It does save/send a scaled version of the original image which is too bad but at least it's now usable (it was previously scaling and cropping images and adding a gray filler bar so this is a very clear improvement). Ideally it would be possible to zoom and have a more image editor experience in the widget but that's a different thing. I have filed #286 on rethinking this widget's overall behavior.

**Pull request merged**
