### PR TITLE
Background color change can be removed. Fix #1975

### LINKED ISSUE #1975: The background of question text is still highlighted after listening to audio
#### Software and hardware versions 
Collect v1.13.2 and older versions

#### Problem description
The background of question text is still highlighted after listening to audio.

#### Steps to reproduce the problem
1. Download `Birds` form from the demo server.
ezgif com-video-to-gif 2

#### Expected behavior
I think we can get rid of that white background (It doesn't look good). Highlighting the text is enough.
@lognaturel do you agree.

### PR DESCRIPTION
**Pull request by hossamnasser938**
Closes #1975 

#### What has been done to verify that this works as intended?
Tested on physical device (Samsung galaxy J5) and some emulators.

#### Why is this the best possible solution? Were any other approaches considered?
@lognaturel  said "Yes, I agree that highlighting the text is a sufficient indicator that audio is playing and that the background color change can be removed. " so I simply removed the code that changes the color of the background.

#### Are there any risks to merging this code? If so, what are they?
No risks at all.

#### Do we need any specific form for testing your changes? If so, please attach one.
'Birds' form can be tested.

### CODE REVIEW

**Comment by grzesiek2010** [comment]
@hossamnasser938 

Your changes look good to me. Could you just implement one additional change? I would change that blue color we use to highlight question text and use our [tintColor](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/res/values/colors.xml#L19) it's also blue but it's the same blue we use in other views. It's just for consistency.

You can do that in a separate commit.

**Comment by hossamnasser938** [comment]
Awesome @grzesiek2010  It's a very simple task. I'll do it now.

**Comment by grzesiek2010** [comment]
@hossamnasser938 

please fix your build and it's ready for testing.

**Comment by hossamnasser938** [comment]
How can I do that @grzesiek2010 . When I run gradle lint, I get this error "Do not use windows line endings"

**Comment by grzesiek2010** [comment]
I think that error occurs only on your side. Look at your output file https://1768-40213809-gh.circle-artifacts.com/0/reports/lint/lint-result.xml I can see there only one error `id="ResourceAsColor"`

**Comment by hossamnasser938** [comment]
@grzesiek2010 Can I make the constant DEFAULT_PLAY_COLOR instant instead of static to be able to call getContext() method 
`-    private static final int DEFAULT_PLAY_COLOR = R.color.tintColor;
+    private final int DEFAULT_PLAY_COLOR = ContextCompat.getColor(getContext() , R.color.tintColor);`

Would it affect anything like memory as it will be declared for every instance of the class or it's not a significant change?

**Comment by grzesiek2010** [comment]
Generally `DEFAULT_PLAY_COLOR` is used only to initialize `playColor` field so I think you can remove `DEFAULT_PLAY_COLOR` at all and use only something like:
`private int playColor = ContextCompat.getColor(getContext() , R.color.tintColor);
`

**Comment by hossamnasser938** [comment]
@grzesiek2010 You are right that will not affect anything now but I 'm afraid that may break the default style of programming which have bad effects on future maintenance.

**Comment by hossamnasser938** [comment]
@grzesiek2010 How can I get this [page](https://1768-40213809-gh.circle-artifacts.com/0/reports/lint/lint-result.xml) you provided me before?

**Comment by grzesiek2010** [comment]
Your build -> Artifacts -> lint

**Comment by hossamnasser938** [comment]
@grzesiek2010 No errors. Why it doen not build?
https://1770-40213809-gh.circle-artifacts.com/0/reports/lint/lint-result.xml

**Comment by grzesiek2010** [comment]
I don't know just try to run the build again maybe it's a random problem sometimes it happens.

**Comment by hossamnasser938** [comment]
@grzesiek2010 How to run build again?

**Comment by grzesiek2010** [comment]
There is a button on CircleCI. Click on `details` and it should be there.

**Pull request closed without merging**
