### PR TITLE
Update JavaRosa to get secondary instance performance improvements

### LINKED ISSUE #4363: When going to a screen with a dynamic choice list, the choice list is computed twice
#### Software and hardware versions 
Collect v1.29; introduced when we added value changes to audit log

#### Problem description
Computing a dynamic choice list is an expensive operation because it involves evaluating an XPath expression over and over again as part of a linear search through all possible choices. Currently the list is computed twice when a screen flip occurs: once as part of building a select widget and another as part of logging an analytics event for that screen (even if values are not saved in the log!):
Screen Shot 2021-01-27 at 11 04 19 AM

#### Steps to reproduce the problem
Fill any form with a select with a choice filter (e.g. [cascade.xml.zip](https://github.com/getodk/collect/files/5883216/cascade.xml.zip)). Put a breakpoint at `FormDef.populateDynamicChoices` and see that it gets called twice when going to a question with a choice filter.

#### Expected behavior
The choice list should only be computed once.

### PR DESCRIPTION
**Pull request by lognaturel**
Closes #4363

This should halve the time it takes to generate and display a filtered choice list. It should also make navigation to questions with choice lists instant if the values involved in the filter expressions haven't changed. For example, in a form with a district question and then a settlement question filtered based on district, if the district doesn't change, it should be instant to go to the settlement question, to view the settlement question in the hierarchy view, etc. Note that when loading a saved form, all of the choice lists will need to be filtered so displaying that initial hierarchy screen will take time.

#### What has been done to verify that this works as intended?
- JavaRosa tests added and reviewed by @dcbriccetti.
- Verified [external 52k split form](https://drive.google.com/drive/u/0/folders/1QwX7E-u19jzXvzwkOpj2Y4X-xb9ihd1f) with Samsung Galaxy Tab A. Prior to PR navigating to Settlement question after changing District question took ~11s. Now it takes ~5s.
- Verified that navigation is instant when filter values don't change.
- Verified that saving a form with large secondary instances is instant
- Verified that a form instance with large secondary instances can be opened for editing

#### Why is this the best possible solution? Were any other approaches considered?
See https://github.com/getodk/javarosa/pull/626 and https://github.com/getodk/javarosa/pull/619.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
There's risk around anything having to do with selects with choice filters. In particular, there's risk around the filtering happening correctly and updating when needed and there's risk around translated choices.

#### Do we need any specific form for testing your changes? If so, please attach one.
This is a tricky one to verify because the main risk is around different kinds of form definitions. I've checked:
- [external 52k split](https://drive.google.com/drive/u/0/folders/1QwX7E-u19jzXvzwkOpj2Y4X-xb9ihd1f) (external selects, 52k choices, no translations)
- [Nigeria wards internal](https://docs.google.com/spreadsheets/d/1B9vUMXvXNoLoV3SWEBTxxyhyJ-vxLbZ6EI2hbpl4nYw/edit#gid=0) (internal selects, 12k choices, no translations)

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by mmarciniak90** [comment]
Form: `External 52 k split`

Andorid 7 | 1.30.1 | PR
|---|---|---|
1st load |4s | 4s
2nd load | 1.3s | 1.3s
load from cache|3.3s | 4.2
going from district to settlement|4s | 3s
finalizing|2.4s | 1.2s

Andorid 6 | 1.30.1 | PR
|---|---|---|
1st load |13s | 13s
2nd load | 4s | 3.5s
load from cache|11s | 13s
going from district to settlement|**12s** | **6.9s**
finalizing|**9s** |**1.5s**

Form: `Nigeria Wards Internal`

Andorid 7 | 1.30.1 | PR
|---|---|---|
1st load |2.9s | 3.5s
2nd load | 2s | 2s
load from cache|2.1s| 2.1s|
finalizing|2s | 1.3s

Andorid 6 | 1.30.1 | PR
|---|---|---|
1st load |9.2s| 9s
2nd load | 5s | 5s
load from cache| 6.5s |7s
finalizing|**4.6s** | **1s**

**Comment by kkrawczyk123** [comment]
My results of performance testing from devices: Motorola Moto G Play Android 7.1 and Huawei Y560-L01 Android 5.1:

Form: `External 52 k split`

| Android 5.1 | 1.30 | PR |
| ---- | ---- | ---- |
| 1st load | 16s | 16s |
| 2nd load | 4s | 4s |
| going from district to settlement | **19s** | **12s** | 
| finalizing | **9s** | **1s** |

| Android 7.1 | 1.30 | PR |
| ---- | ---- | ---- |
| 1st load | 15s | 15s |
| 2nd load | 4s | 3s |
| going from district to settlement | **10s** | **7s** | 
| finalizing | **5s** | **1s** |


Form: `Nigeria Wards Internal`

| Android 5.1 | 1.30 | PR |
| ---- | ---- | ---- |
| 1st load | 25s | 23s |
| 2nd load | 7s | 7s |
| finalizing | **5s** | **1s** |

| Android 7.1 | 1.30 | PR |
| ---- | ---- | ---- |
| 1st load | 7s | 7s |
| 2nd load | 5s | 3s |
| finalizing | **4s** | **2s** |

Regression checks on:
- form with field-list
- select one and multi with minimal appearance
- selects with a quick appearance
- selects with autocomplete appearance 
- selects with column pack appearance
- selects with search 
- form with external itemsets
- form with external secondary instances

**Comment by mmarciniak90** [comment]
@lognaturel what do you think about results?

Regression cases have also been verified on Androids 7.0, 8.1, 10.0

**Comment by lognaturel** [comment]
Thanks! The results look as expected. Did you also verify that once prior filtering questions are set (eg district in the 52k form and population search string for Nigeria wards last question) showing the filtered question (eg settlement or ward with the target population) is always instant within the same form filling session? That’s in the hierarchy, swiping back and forth to the question, and possibly some other cases I’ve missed. 

The other big area of risk is translations. Do some of the forms you verified have multiple languages?

**Comment by mmarciniak90** [comment]
@lognaturel, during today's tests, I discovered one broken behavior.
I changed the answer in the first select and jumped to the end -> I was able to finalize without validation.

ezgif com-video-to-gif

@getodk-bot unlabel "needs testing"

**Comment by kkrawczyk123** [comment]
Additional performance checks on the worst device that I have Android 5.1:
- go back from settlement to district: less than 1s - I am not that fast to stop the timer 
- jump to hierarchy: 1s
- jump to each question: little delay with loading each question, less than 1s visible 
- use go to start/ go the end button: less than 1s 
- save not finalize from save and exit view: 1s
- screen rotate when all lists of answers displayed: 4s (probably connected to the device)
- go to general settings and go back to form: less than 1s

**Comment by lognaturel** [comment]
@mmarciniak90, really good catch. I cleared out answers no longer in choices by setting them to an empty string but I should have been setting them to null. Fix and new test at https://github.com/getodk/javarosa/pull/626/commits/27fd4ead84e0c21a18b2adde903c216cccc64c9e. Please verify.

Thanks, @kkrawczyk123, that looks as I would expect and I'm glad to see you didn't identify any other remaining slow operations.

**Comment by lognaturel** [comment]
Keeping this a draft until we have a JR release since we don't want to merge the jar here.

**Comment by kkrawczyk123** [comment]
**Tested with success!**
Verified on Androids: 5.1, 7.1 and 9.0

Tested cases:
- jump to the hierarchy
- go to start/go to the end
- go backward/forward
- add/edit answers
- remove response
- screen rotation
- edit answers and validate upon swipe/validate upon finalize
- save/finalize forms
- used filter in Nigeria form
- regression checks from the comment above
- edit finalized form
- change language
- RTL language
- go to General Settings and change settings in the middle of filling a form 
- issue has been fixed

**Comment by mmarciniak90** [comment]
Also successfully tested on Android 7.0, 8.1, 10.0

@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"

**Comment by lognaturel** [comment]
Thanks, @mmarciniak90, @kkrawczyk123!

Merging now so this can start being exercised in every day use.

**Pull request merged**
