### PR TITLE
Use material bottom navigation in FormDownloadList

### PR DESCRIPTION
**Pull request by grzesiek2010**
#### What has been done to verify that this works as intended?
I tested manually the activity.

#### Why is this the best possible solution? Were any other approaches considered?
I followed https://material.io/design/components/bottom-navigation.html

| Master  | This branch | This branch |
| ------------- | ------------- | ------------- |
| screenshot_2019-03-08-00-56-17 | screenshot_2019-03-08-00-50-10  | screenshot_2019-03-08-00-49-44  |

it's just a first step beacuse we can use such a bottom navigation in other places as well.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It implements changes in `FormDownloadList` so the functionality should be tested.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by grzesiek2010** [comment]
@yanokwa @cooperka what do you think?

**Comment by shobhitagarwal1612** [comment]
The guideline says that it should be used to get to a new destination rather than performing single tasks. Couple of ideas after seeing the above screenshots:
 - removing the bottom buttons or nav bar
 - add refresh button to appbar or swipe to refresh
 - single tap to download single item
 - long tap to select multiple items and download using floating download button

**Comment by grzesiek2010** [comment]
That's right but taking into account that many of our users are not really used to new technologies so every big change in UI is a problem for them I wanted to keep those options there (like before).

**Comment by grzesiek2010** [comment]
Let's keep this pr for further discussion.

**Comment by cooperka** [comment]
The "go up" button recently moved from the bottom into the options menu (top buttons), and I think it would be acceptable for these buttons to go up there as well. If we're going to change this screen I'd rather change it in a more standard direction.

I agree we should be cautious with big changes, but ultimately this screen is meant for performing one specific action ("download new forms") and users must know that action is possible because that's why they came to this screen. If we move the button, they will find it, and if the UI follows normal conventions then they will remember where it is in the future.

Proposal:
- Make "download" a [floating action button](https://material.io/design/components/buttons-floating-action-button.html#behavior)
- Keep "sort" and "search" as option menu items, showAsAction **always**
- Make "select all" an option menu item, showAsAction **ifRoom**
- Make "refresh" an option menu item, showAsAction **ifRoom**
- Also add "pull to refresh" behavior

**Comment by grzesiek2010** [comment]
You forgot about the search button. Search and sort buttons are always visible on other lists so it would be strange to make them visible `ifRoom` here. I'm not sure if keeping so many options in the toolbar is a good idea.

**Comment by cooperka** [comment]
Good point, I agree -- edited

**Comment by shobhitagarwal1612** [comment]
@cooperka What is your opinion on the visibility of the floating "download" button? IMO, it should be hidden when nothing is selected and pop up from button as soon as items are selected

**Comment by cooperka** [comment]
I think that's a great idea (or start disabled and become enabled). Any idea if one or the other is standard?

**Comment by shobhitagarwal1612** [comment]
From what I have noticed in the trending applications, floating buttons are never disabled. There are either visible or gone. Also, they are aware of the scrolling background

**Comment by grzesiek2010** [comment]
I said that big changes in UI might be difficult for some users but I like the idea with selecting forms by long press. That's how Gmail app works for example. There is a nice app [MaterialX](https://play.google.com/store/apps/details?id=com.material.components) which presents some good patterns and there is also a section that shows select multiple lists and it works in the same way.
ezgif com-video-to-gif

**Comment by cooperka** [comment]
That MaterialX app is fantastic, thanks for the link.

Long press is nice when selection is not the primary action, but in this case I think checkboxes make sense because there's nothing else to do on the page other than select forms. Long press requires slightly more effort and is slightly less intuitive, and I don't see a strong benefit to changing.

@grzesiek2010 it sounds like you're not in favor of moving "select all" and "refresh" into the options menu, is that still the case? Can you explain your reasoning more deeply? That still seems like the simplest and most effective change to be made here that conforms to Material conventions.

**Comment by grzesiek2010** [comment]
I'm closing it for now.

**Pull request closed without merging**
