### PR TITLE
Replace png icons with vectors

### PR DESCRIPTION
**Pull request by Shreya001**
Closes #1885 

#### What has been done to verify that this works as intended? I have deleted the png icons and added vector files instead with same name. These vector files were mainly taken from google material icons and rest were traced by me.

### CODE REVIEW

**Comment by lognaturel** [comment]
Thank you @Shreya001! Please edit the PR description to answer the questions in the prompts and specify which issue should be closed. You should include information like where the vector files come from.

The build is failing because of lint checks. You can see the report locally by running `./gradlew lint` or by clicking on Details next to "Your tests failed on CircleCI" above and then looking at Artifacts. There is also a warning for "Long vector paths" that would be good for you to address.

**Comment by Shreya001** [comment]
@lognaturel can you please help I am unable to find Why  the checks failed

**Comment by grzesiek2010** [comment]
@Shreya001 it failed because of lints. You can run `./gradlew lint` command and check what's going on. Reports are generated in `collect_app->build->reports` dir. There you can find all with `severity="error"` and fix them.

**Comment by shobhitagarwal1612** [comment]
@Shreya001 Have a look at the report generated.
It says, " When using VectorDrawableCompat, you need to use app:srcCompat."

 https://1493-40213809-gh.circle-artifacts.com/0/reports/lint/lint-result.html#VectorDrawableCompat

**Comment by Shreya001** [comment]
@grzesiek2010  can you please review it and let me know so that I can work on other issues as well.

**Comment by shobhitagarwal1612** [comment]
image
 The logo icon is changed.

**Comment by shobhitagarwal1612** [comment]
image

Icons are missing on this screen.

**Comment by shobhitagarwal1612** [comment]
image
These should be a bit bigger and aligned vertically

**Comment by shobhitagarwal1612** [comment]
image

Icons missing (Please ignore the unloaded map.It's because I'm not using my API key for debug builds)

**Comment by grzesiek2010** [comment]
@lognaturel I think it would be better to divide it into a few small prs for each activity/fragment etc. It would be much easier to review and test everything. What do you think?

**Comment by lognaturel** [comment]
I do agree, @grzesiek2010. @Shreya001, let's close this for now since there are a number of problems with it and you can open PRs for different areas of the code one by one (about activity, map questions, form entry activity, etc). That way once one set is verified, it can be merged right away.

The clipboard logo is probably best to keep as a png.

**Comment by Shreya001** [comment]
@grzesiek2010 is the issue closed or I can still work on same or should I work on something else?

**Comment by grzesiek2010** [comment]
@Shreya001 
It's closed. We still want to do that but in a few separate pull requests for each view/activity/fragment. You can review all existed pngs and file an issue for a particular view you want to fix. Here is a good example https://github.com/opendatakit/collect/issues/1858

**Comment by Shreya001** [comment]
Thanks @grzesiek2010

**Pull request closed without merging**
