### PR TITLE
Fix issue with extras being ignored

### PR DESCRIPTION
**Pull request by lognaturel**
The extra value needs to be parsed, not the extra name. This is bad because it means no extras have been passed on to external apps.

#### What has been done to verify that this works as intended?
Tried it with [send-sms-or-email-in-form.xml.txt](https://github.com/opendatakit/collect/files/2291955/send-sms-or-email-in-form.xml.txt) and  [dial-number.xml.txt](https://github.com/opendatakit/collect/files/2291961/dial-number.xml.txt). Also debugged to see that the intent values were properly passed on.

#### Why is this the best possible solution? Were any other approaches considered?
It looks like in #2386 I inverted keys and values. This rectifies the problem. I'm not really sure why this wasn't caught by the test case launching the counter app because it seems like it wouldn't have launched with the intended values.

#### Are there any risks to merging this code? If so, what are they?
This change targets extras passed to external apps and that's all it touches. That functionality doesn't work at all right now so I don't think there are any risks other than not actually addressing the issue.

#### Do we need any specific form for testing your changes? If so, please attach one.
[send-sms-or-email-in-form.xml.txt](https://github.com/opendatakit/collect/files/2291955/send-sms-or-email-in-form.xml.txt) and 
[dial-number.xml.txt](https://github.com/opendatakit/collect/files/2291961/dial-number.xml.txt) Just to be extra sure, it might be worth modifying the values passed into the counter app and checking that those properly get sent on.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No, it's a bug fix.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew pmd checkstyle lintDebug spotbugsDebug` and confirmed all checks still pass.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by kkrawczyk123** [comment]
**Tested with success!**
Verified on Androids 6.0 and 5.1.

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Comment by yanokwa** [comment]
@kkrawczyk123 Do you have an idea why this bug wasn't caught by the test case of launching the counter app?

**Review by yanokwa — APPROVED** [review]

**Comment by lognaturel** [comment]
> Do you have an idea why this bug wasn't caught by the test case of launching the counter app?

My guess is that the test case involves launching the counter app and incrementing its value but not verifying that the value for that question is "remembered" the next time it's launched. @mmarciniak90 or @kkrawczyk123 Could you please make sure that the Counter test case requires launching the counter app a couple of times and verifying that the counter value increments between launches? That way it would more easily catch regressions like these. Sorry for introducing it in the first place!!

**Comment by kkrawczyk123** [comment]
Sure @lognaturel, we will!

**Pull request merged**
