### PR TITLE
External audio widget

### LINKED ISSUE #4214: Add support for external binary question types
https://github.com/getodk/collect/pull/4188 added support for binary files to be returned by external apps to intent field lists. This issue is to allow single-question media questions to call out to external applications. 

[Current documentation](https://docs.getodk.org/launch-apps-from-collect/#designing-an-external-app-to-return-a-single-value-to-collect) for external questions.

From [the specification document](https://docs.google.com/document/d/1JbKiwgBCuI2t3Cd8n5OnyrNce3woq20ncZbN3oGcPhU/edit):
If the field has a binary type, Collect will use the ClipData contents. If there’s more than one item in the ClipData, Collect will fail silently and clear the field.

Implementation notes:
* Currently each question type has its own widget class. Is it better to continue this pattern or could we pull everything to do with external applications out of the widget layer?
* Important to manage redundancy with the field-list implementation
* https://github.com/getodk/collect/pull/4208#issuecomment-724199226 has some cases to test

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #4214

#### What has been done to verify that this works as intended?
I tested the new widget manually and added automated tests.

#### Why is this the best possible solution? Were any other approaches considered?
It's a continuation of: https://github.com/getodk/collect/issues/4214

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Here I implemented a completly new ExAudioWidget. I didn't touch other widgets so we can focus on the new one and that would be enough.

#### Do we need any specific form for testing your changes? If so, please attach one.
[exTestForm.xlsx](https://github.com/getodk/collect/files/5951659/exTestForm.xlsx)

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
Yes https://github.com/getodk/docs/issues/1318

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by lognaturel — APPROVED** [review]
It feels to me like there's some audio playback code that could be pulled out and shared but I don't think it's a big deal. Nice to see some tests for parsing the intent strings.

**Comment by grzesiek2010** [comment]
> It feels to me like there's some audio playback code that could be pulled out and shared but I don't think it's a big deal.

yeah I wanted to create a custom view for the entire player and pull out the duplicated code there but at the same time I didn't want to make conflicts with what Callum is working on

**Comment by mmarciniak90** [comment]
**Tested with success**

Verified on Android 7.0, 8.1, 10.0

**Verified cases:**
- generated answer
- RTL language
- used forward/backward navigation buttons
- remove response
- save/finalize form
- toast is visible when external app is not available
- launch counter app
- light/dark mode
- edit form
- don't keep activities
- rotation
- minimize
- send submission to Central and Aggregate
- different font sizes
- regression check on ex string and numerical widgets

**Comment by kkrawczyk123** [comment]
Verified also on Androids: 5.1, 7.1 and 9.0

@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"

**Pull request merged**
