### PR TITLE
Load system locale at startup if supported. Fixes #890

### LINKED ISSUE #890: App language should default to phone language
#### Software and hardware versions 
Collect v1.5.1-65-g068e4ade

#### Problem description
The app language defaults to English on the first launch after #817 was introduced. It should default to the phone language.

#### Steps to reproduce the problem
1. Uninstall Collect or run a version prior to the inclusion of #817 
1. Change the phone language to a language other than English that is supported by Collect
1. Install and launch Collect

The app language will default to English.

#### Expected behavior
The app language should default to the phone language if it is supported by Collect.

#### Other information 
I believe all that needs to change is the default [here](https://github.com/abdulwd/collect/blob/deeb3da2a8a9d1cc3614c8f9f349caac4b500c82/collect_app/src/main/java/org/odk/collect/android/utilities/LocaleHelper.java#L23) so that it is based on the phone's locale rather than hardcoded to English. Additionally, there will first have to be a check to make sure that the phone language is supported by Collect. If not, English is probably the right default.

### PR DESCRIPTION
**Pull request by icemc**
@lognaturel @yanokwa could you please review this little fix I made

### CODE REVIEW

**Comment by icemc** [comment]
This PR addresses issue #890

**Comment by lognaturel** [comment]
Thank you @icemc! The case that I described in the issue works well. However, I'm seeing a couple of problems. When the language from the phone locale is used, the summary text in the settings still shows "English". Either "Use phone locale" could be an option or the language of the phone locale could be saved as the preference so it can be displayed as the summary text. This may depend somewhat on how we decide to handle the next problem.

Changing the phone locale always overrides the app setting until the app is closed and restarted. To verify this:
1. Open Collect, set the language to language1 in the settings
1. Change the phone language to language2
1. Open Collect again, notice that the app is in language2
1. Go to settings and see that the summary still shows language1
1. Kill Collect
1. Restart Collect and notice that the app is in language1

This is pretty confusing behavior. I think either "Use phone locale" should be an explicit option or once the language is set by Collect, it should not be changed by the OS. 

This leads me to see that we're kind of fighting the operating system here. @icemc @abdulwd @yanokwa @nribeka Any thoughts on what the best behavior would be here?

**Comment by yanokwa** [comment]
I'm OK fighting the OS if we are solving a real problem! We've already decided at https://github.com/opendatakit/collect/issues/890 that this is a real problem, so we should solve it as cleanly as we can.

I think `Use phone locale` should be the default option at the top of the list. Then once that is changed, Collect should persist it. 

One caveat here is that there might be random bugs we run into (e.g., http://stackoverflow.com/a/9535374)

**Comment by icemc** [comment]
@yanokwa  please need to be clarified about what you said in the previous comment. Are you saying that if during App launch the phone locale is set to say Language1 and the user goes to the phones settings and and changes the language to language2 on returning to collect the display language should still be language1?

**Comment by lognaturel** [comment]
I believe what @yanokwa prefers is to introduce a "Use phone locale" option for the language setting which would preserve the previous versions' behavior -- the language would just be set by the phone. Then, if the user instead picks a specific language in the app, the app should be in that language until the user changes it again from the app, regardless of whether the system language is changed. The user should also be able to go back to "Use phone locale" ([this](http://stackoverflow.com/a/23556454/137744) gives an idea how).

Did I get that right @yanokwa?

**Comment by yanokwa** [comment]
Yup, you got it right!

**Comment by icemc** [comment]
@lognaturel and @yanokwa got it. Working on it.

**Comment by abdulwd** [comment]
Busy with exams. I will look into the issue tomorrow. :)

**Comment by icemc** [comment]
@lognaturel  and @yanokwa  Im done with the fix. Tested and it worked as required. Sorry for the dirty commit history will submit a new PR with fewer commits if requested. Waiting to hear from you. Cheers

**Pull request closed without merging**
