### PR TITLE
Use ellipsis character

### LINKED ISSUE #747: In strings, ellipsis string can be replaced with ellipsis character
When you run `./gradle lint`, a report is generated at `collect_app/build/reports/lint-results.html` with potential problems with Collect. Find the `Ellipsis string can be replaced with ellipsis character` section and fix those.

### PR DESCRIPTION
**Pull request by championoverthinker**

### CODE REVIEW

**Comment by grzesiek2010** [comment]
@sjain281297 Thanks for such a quick solution it works well but i prefer other way - look here is an example: https://github.com/grzesiek2010/collect/commit/bcf1a27cd407c5a66611e956151f1788e02fa37d

You can do that just using Android Studio:




It looks better I think.

I think we should add every resoveld lint type (in this case TypographyEllipsis) to https://github.com/opendatakit/collect/blob/master/collect_app/lint.xml in order to avoid the same in the future.

**Comment by championoverthinker** [comment]
@grzesiek2010 thanks for the info I will keep it in mind in the future :smile:

**Comment by grzesiek2010** [comment]
@sjain281297 are you going to fix that now in the second way? It would be great. Because I'm not sure what you mean by "in the future".

**Comment by championoverthinker** [comment]
@grzesiek2010 ofcourse I am going to fix it.Sorry for the misunderstanding.

**Comment by grzesiek2010** [comment]
@sjain281297 Great! thanks.

**Comment by championoverthinker** [comment]
@grzesiek2010 please review

**Comment by grzesiek2010** [comment]
@sjain281297 there is something wrong with your branch looks like you need to rebase against current master branch.

**Comment by sjain281297** [comment]
I ll just check

**Comment by championoverthinker** [comment]
@grzesiek2010 I have fixed it please check now

**Comment by grzesiek2010** [comment]
@sjain281297 it's the same look https://github.com/opendatakit/collect/pull/750/files

**Comment by sjain281297** [comment]
I think I should close this pull request and submit another pr with new branch.Is that ok?

**Comment by grzesiek2010** [comment]
You don't need to close this pr.
If you don't know how to resolve this problem and you want to start with new branch you can do that.

for example:
this branch is named "editbranch". 
So you can go to master:

> git checkout master

remove your old branch:

> git branch -D editbranch

then update your master branch. 

after that you can create a branch with the same name "editbranch":

> git checkout editbranch

and:
*create all required changes
*push your changes using:

> git push origin editbranch --force

and everything should be ok.

**Comment by championoverthinker** [comment]
@grzesiek2010 thanks a lot for your help and cooperating with me.I have finally fixed the issue.

**Comment by grzesiek2010** [comment]
@sjain281297 Now it's ok :) Please add this small change I mentioned above:

> I think we should add every resoveld lint type (in this case TypographyEllipsis) to https://github.com/opendatakit/collect/blob/master/collect_app/lint.xml in order to avoid the same in the future.

I'm not sure what @lognaturel and @yanokwa think but even if they don't like my proposal you can reamove that easily. i think we need that.

Please do that in a separate commit so then you can remove that easily if needed.

**Comment by championoverthinker** [comment]
@grzesiek2010 I am a bit inexperienced with lint.Can you just guide me a bit on how to do it.If that's ok with you.

**Comment by grzesiek2010** [comment]
@sjain281297 You just need to add new line in this file https://github.com/opendatakit/collect/blob/master/collect_app/lint.xml

it should look like the others but with TypographyEllipsis id of course.

**Comment by sjain281297** [comment]
Ohh thanks.I ll add it.

**Comment by grzesiek2010** [comment]
It looks ok to me. Thanks @sjain281297

**Comment by yanokwa** [comment]
Thanks for your contribution @sjain281297 🙏🏿

**Pull request merged**
