### PR TITLE
Fixes Issue#2158: Collect crashes when user changes device orientation during loading image to any of Image Widget

### LINKED ISSUE #2158: Collect crashes when user changes device orientation during loading image to any of Image Widget
#### Software and hardware versions 
Collect master

#### Problem description
App crashes when the user changes device orientation during loading image

#### Steps to reproduce the problem
1. The user starts a form with images
2. The user chooses some image
3. The user sees dialog `please wait a few moments.`
screenshot_20180427-095359
4. User changes device orientation
5. App crashes

#### Expected behavior
* ODK Collect does not crash
* Image is loaded

### PR DESCRIPTION
**Pull request by SaumiaSinghal**
Closes #2158 

#### What has been done to verify that this works as intended?
I tested it on Android 4.1, 5.1 and 8.1.

#### Why is this the best possible solution? Were any other approaches considered?
It fixes the orientation until the loading of Image to any of Image widget is complete.

#### Are there any risks to merging this code? If so, what are they?
No

#### Do we need any specific form for testing your changes? If so, please attach one.
Forms having Image widget.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew pmd checkstyle lint findbugs` and confirmed all checks still pass.
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by grzesiek2010** [comment]
@SaumiaSinghal 

I know the issue is just about orientation changes but I bet it may also occur if you close an app using device button, or if you just turn off and on the screen etc. Were you able to reproduce the issue?

**Comment by SaumiaSinghal** [comment]
Yes @grzesiek2010, I was able to reproduce this issue, I tried the other three cases, you mentioned as well, and it's working on my phone running Android 5.1.

**Comment by SaumiaSinghal** [comment]
But what i found wrong while working on this issue is that `scaleDownImageIfNeeded()` is never actually scaling down large sized images. I found that on changing device orientation while uploading large images, it actually calls `onDestroy()` and restarts the app and so our image, however, there in directory, is not shown on screen.

**Comment by grzesiek2010** [comment]
Sorry for the delay.

Ok, it might be difficult to reproduce the issue in the way I mentioned (other than changing device orientation) but it's possible. Your solution just blocks changing device orientation what is not a real cause. The real cause is that we try to dismiss a dialog we didn't show again after recreating the activity and such a recreation might be triggered not only by changing device orientation. So we can't accept this fix.

**Comment by grzesiek2010** [comment]
Probably we should display that dialog again after recreating the activity or maybe we can use [DialogFragment](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/fragments/dialogs/SimpleDialog.java) like [SImpleDialog](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/fragments/dialogs/SimpleDialog.java) which is displayed automatically.

**Comment by SaumiaSinghal** [comment]
Thanks for reviewing @grzesiek2010, yes, you are right, while working on it, I did observe some strange behaviour when i was using progress dialog and when not.

**Comment by SaumiaSinghal** [comment]
Also, progress dialog is deprecated so, maybe, I should go with DialogFragment..

**Comment by SaumiaSinghal** [comment]
Hie @grzesiek2010, I removed the progress Dialog and any other Dialog fragment and found it was still not working fine but then i found that there is something wrong with `rotateImageIfNeeded` as without it, it's working fine..

**Comment by grzesiek2010** [comment]
> found that there is something wrong with rotateImageIfNeeded as without it, it's working fine.

I don't really understand what is wrong but if you noticed anything you can file a separate issue. Here we just want to fix the crash.

**Comment by SaumiaSinghal** [comment]
Hie @grzesiek2010, Since this was not the correct way of fixing this issue, I've opened a new PR for the same. Please review. I am closing this for now.

**Pull request closed without merging**
