### PR TITLE
Fixed margin margin between group name and list

### LINKED ISSUE #5933: Increase margin between group name and list
We need to increase the [margin](https://github.com/getodk/collect/pull/5885#issuecomment-1900484062) between group name and list, as it's overlapping and is difficult to read when there is a long list of questions. 

Image

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5933 

#### Why is this the best possible solution? Were any other approaches considered?
It's rather a small tweak but it makes the gap between the group name and the question label bigger so @alyblenkin please take a look and let me know it this is ok:

| Before  | Now |
| ------------- | ------------- |
| Screenshot_1709751585  | Screenshot_1709751085 |
| Screenshot_1709751588 | Screenshot_1709751103 |

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It should be a safe change so please just briefly verify that spacings are consistent between the form view and the hierarchy view.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by alyblenkin — APPROVED** [review]
Small tweak but it's much better.

**Comment by dbemke** [comment]
**Tested with success!**

Verified on devices with Android: 8.1, 10

**Comment by WKobus** [comment]
**Tested with success!**

Verified on devices with Android: 11

**Comment by srujner** [comment]
**Tested with success!**

Verified on devices with Android: 13

**Pull request merged**
