### PR TITLE
Fix bug in RelativeLayout with empty content under RTL language, fix #1914.

### LINKED ISSUE #1914: Blank hierarchy/jump view for RTL language
#### Software and hardware versions 
Collect v1.12.1, Android v7.1.0, device used Moto g4+

#### Problem description
The 'All Widgets Page' that shows all the widgets in the form, is blank when a RTL language is selected.

#### Steps to reproduce the problem
1. Select a Right to Left language.
2. Get 'All Widgets' form from the 'Get Blank Form' Option and then open the form.
3. Click on Overview button in the top-bar (icon that looks like a diagonal arrow pointing a dot).

#### Expected behavior
The page should show a list of all the widgets in the form.

**Screenshot**
assdsasa
screenshot_20180217-020613

### PR DESCRIPTION
**Pull request by huangyz0918**
Closes #1914 
links to PR #2080

### CODE REVIEW

**Comment by grzesiek2010** [comment]
@huangyz0918 

can't we move some code from this class to xml file to avoid all those `if else statements`?

**Comment by huangyz0918** [comment]
@grzesiek2010 

These views are injected with **Java code**, so there are no layout files to modify. A good suggestions is to build a static method to detect RTL layout and handle them all.

**Comment by grzesiek2010** [comment]
We should follow the same approach we use in other lists. An adapter -> each row use an xml file and we can specify all those things in that file we don't need any additional class and multiple if else statements.

**Comment by grzesiek2010** [comment]
@opendatakit-bot unlabel "needs testing"

**Comment by grzesiek2010** [comment]
@lognaturel I removed `needs testing` label because I think we can do that in a better way but if you, for example, want to fix that quickly an release a new version it's ok and we can improve the behavior later.

**Comment by huangyz0918** [comment]
Similar with my new PR #2123 (I hate so many `if-else` statements), so I agree with you @grzesiek2010 . It's really good !

But as for this list (jump/hierarchy), it contains some groups like `observation` so it seems not so easy to build an adapter and the adapter can also be complex, these `if-else` is unavoidable since they are use for API-detecting, you need to add them in adapter or build extra res folders either. But for #2123 , I strongly recommend to build an adapter for `media layout` because it's too hard to read the code.

What do you think about that? @grzesiek2010 @lognaturel

**Comment by grzesiek2010** [comment]
Let me take a deeper look at this issue to check whether its possible or not.

**Comment by grzesiek2010** [comment]
@huangyz0918 this is my proposal https://github.com/opendatakit/collect/pull/2128
please review if you are free. Lots of code refactoring there but the first commit is most crucial when it comes to the approach.

We don't need if statements for rtl or different builds everything is in xml files.

If you agree with my solution please close this one.

**Comment by huangyz0918** [comment]
In favor of #2128 and #2098

**Pull request closed without merging**
