### PR TITLE
QuestionWidget fix

### PR DESCRIPTION
**Pull request by jkpr**
The previous commit placed code to initialize object member `MediaLayout
mediaLayout` in method `addQuestionText`. This method, however is
overridden in various widgets, including `LabelWidget`.

Thus later code in the constructor could try to call a method on `null`.

### CODE REVIEW

**Comment by mitchellsundt** [comment]
Can I have some context on this please? 

What do all of these commits add?

**Comment by jkpr** [comment]
Hmm... I'm a newbie at this git game, so I'm not certain the best way to do things. I have my own development going on, and I keep a master branch tracking with opendatakit's master branch. All I am submitting to change is a few lines in QuestionWidget.java. I think the only difference (I click on "Files changed" above) is in that file.

**Comment by jkpr** [comment]
I'm going to close this until I figure out how to submit just one commit.

**Comment by jbeorse** [comment]
You might look into the squash option for merging and rebasing.

**Pull request closed without merging**
