### PR TITLE
Fixed bugs in Admin Settings -> User Settings

### LINKED ISSUE #2966: Add possibility to hide `Show guidance for questions` option only
#### Software and hardware versions 
Collect v1.18.0 (older versions were not verified)

#### Problem description
There is no possibility to hide `Show guidance for questions` option because this one is not listed in `Admin Settings`  -> `User Settings`

#### Steps to reproduce the problem
1. User goes to `Admin Settings`  -> `User Settings`
2. User unselect almost all options, besides one from `Form management` part, e.g. `Auto send`
3. User leaves Admin settings and opens `General Settings`
4. User sees `Show guidance for questions`

Screenshot_20190326-104925

#### Expected behavior
* `Show guidance for questions` should be listed in `Admin Settings`  -> `User Settings`. 
* Admin is able to hide `Show guidance for questions` option

#### Notes
Discovered during testing #2960

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #2966 

#### What has been done to verify that this works as intended?
I tested Admin and General Settings - showing/hiding settings, 
confirmed that guidance hint` option is now available and works as expected, 
confirmed that the order of settings matches the order form General Settings..

#### Why is this the best possible solution? Were any other approaches considered?
Testing #2960 I noticed some problems in `Admin Settings -> User Settings`:
1. Missing `guidance hint` option #2966 
2. Visible `change submission transport` option which should be hidden since we disabled the SMS feature.
3. Mixed options - I reorderd them to match the order form General Settings.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This pr requires confirming that the option I mentioned above (`guidance hint`) is no longer available.
`change submission transport` option is now available in `Admin Settings -> User Settings`.
Settings are reordered properly.
Apart from that, it's not risky.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
I'm not sure what happens in Transifex when a string is commented out but I don't think it's a big deal either way. Otherwise, looks great and would be good to have in 1.21.

**Comment by mmarciniak90** [comment]
@grzesiek2010 Could you update your branch and add changes from #2960?

**Comment by grzesiek2010** [comment]
> Could you update your branch and add changes from #2960?

Done.

**Comment by mmarciniak90** [comment]
**Tested with success**

Verified on Android: 4.2, 4.4, 5.1, 6.0, 7.0, 8.1

Tested cases:
- hide only `Show guidance for questions` option
- hide all options (General Settings list is empty but Admin Settings -> General Settings contains all options)
- hide all options except `Show guidance for questions` option
- scan the QR code when all options are hidden
- `Submission transport` option is not listed
- options order 

| apk with fix| v1.20|
|---|---|
|Screenshot_20190327-103810|Screenshot_20190327-103902|
|Screenshot_20190327-103816|Screenshot_20190327-103906|


@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Pull request merged**
