### PR TITLE
Add tests for FormDownloadViewModel

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
#### What has been done to verify that this works as intended?
Tested on Redmi Note 4 and no crashes observed

#### Why is this the best possible solution? Were any other approaches considered?
Some refactoring had to be done in order to ensure that the behavior which is to be tested is only controlled by the view model and not from the view too.

1. View now subscribes to Observables using ViewModel instead of querying directly.
2. Removed other calls to the method being made from the view
3. Add unit tests to validate the behavior of the code changed

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Possible risks include a change in the behavior of alert/progress dialogs when checking/downloading the blank forms

#### Do we need any specific form for testing your changes? If so, please attach one.
Not needed

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No 

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by seadowg** [comment]
Hey @shobhitagarwal1612! I'll try and get a chance for a proper look through of this in the next few days.

On an initial skim I did have a question: did you look at using [LiveData](https://developer.android.com/topic/libraries/architecture/livedata) instead of Rx here for view model values here? It would prevent us from having to take care of unbinding (as LiveData works with the Activity lifecycle). If we really feel like we want to be playing with Rx objects it (supposedly) [easy to convert to them](https://developer.android.com/topic/libraries/architecture/livedata) from LiveData values.

**Comment by shobhitagarwal1612** [comment]
I thought so too but that was causing too many changes and I was looking for a progressive approach towards adding the tests. That's why I wanted you to have a look at it and suggest your ideas since you have a ton of experience in this.

**Comment by shobhitagarwal1612** [comment]
I have added tests for the following actions:
 - download complete/error/cancel form list
 - download complete/cancel forms
 - alert dialog creation/dismiss/restore
 - progress dialog creation/dismiss/restore
 - progress dialog message updation
 - cancel dialog creation/dismiss
 - downloadOnlyMode

**Comment by seadowg** [comment]
> I thought so too but that was causing too many changes and I was looking for a progressive approach towards adding the tests. That's why I wanted you to have a look at it and suggest your ideas since you have a ton of experience in this.

That does make sense. I think that because we're introducing tests to the `FormDownloadViewModel` we're at a good point to make the decision about what its interface should look like. While I can see the merits of Rx for network requests my guess would be that we'd benefit from simpler code within our Activity here by using `LiveData`. How do you feel about experimenting with having the `FormDownloadViewModel` return `LiveData` objects rather than `Observable` ones? We could still use Rx internally (within the ViewModel and Repository etc) and then convert to `LiveData` for the values we expose.

**Review by seadowg — CHANGES_REQUESTED** [review]
> I thought so too but that was causing too many changes and I was looking for a progressive approach towards adding the tests. That's why I wanted you to have a look at it and suggest your ideas since you have a ton of experience in this.

That does make sense. I think that because we're introducing tests to the `FormDownloadViewModel` we're at a good point to make the decision about what its interface should look like. While I can see the merits of Rx for network requests my guess would be that we'd benefit from simpler code within our Activity here by using `LiveData`. How do you feel about experimenting with having the `FormDownloadViewModel` return `LiveData` objects rather than `Observable` ones? We could still use Rx internally (within the ViewModel and Repository etc) and then convert to `LiveData` for the values we expose.

(Totally happy to discuss this just thought we might be in a good place to have a go at introducing some newer Android patterns)

**Comment by shobhitagarwal1612** [comment]
I'm all in about experimenting with `LiveData`. So if I am understanding correctly, what you're suggesting would be to bind the XML layout with `FormDownloadViewModel` directly, right?

**Comment by shobhitagarwal1612** [comment]
The reason I used `BehaviorSubject` was to re-emit the last emitted event on it's subscription (for restoring UI on view recreation)

**Comment by seadowg** [comment]
> I'm all in about experimenting with `LiveData`. So if I am understanding correctly, what you're suggesting would be to bind the XML layout with `FormDownloadViewModel` directly, right?

No not that far yet (although that would be cool). I just mean using the [LiveData](https://developer.android.com/topic/libraries/architecture/livedata) objects in place of Rx's `Observable` in the Activity. 

For instance we'd have `getProgressDialog()` in the `FormDownloadViewModel` return a `LiveData<Boolean>` rather than an `Observable<Boolean>`. That would mean in the activity instead of:

```java
compositeDisposable.add(viewModel.getProgressDialog()
                .subscribeOn(schedulerProvider.io())
                .observeOn(schedulerProvider.ui())
                .subscribe(shouldDisplay -> {
                    if (shouldDisplay && (progressDialog == null || !progressDialog.isShowing())) {
                        createProgressDialog();
                    } else if (!shouldDisplay && progressDialog != null && progressDialog.isShowing()) {
                        progressDialog.dismiss();
                    }
                }, Timber::e));
```

We'd have something a little more like this:

```java
viewModel.getProgressDialog().bind(this, new Observer<Boolean>() {
    @Override
     public void onChanged(Boolean shouldDisplay) {
         if (shouldDisplay && (progressDialog == null || !progressDialog.isShowing())) {
              createProgressDialog();
          } else if (!shouldDisplay && progressDialog != null && progressDialog.isShowing()) {
              progressDialog.dismiss();
     }
});
```

This binding will automatically be "unbound"/"rebound" on pause/resume cycles in the Activity (Android is doing that for us which is why we pass `this` to `bind`) and like with the `BehaviourSubject` when the "rebind" happens during an `onResume` our `onChanged` will be called.

**Comment by shobhitagarwal1612** [comment]
So this must be done only once, i.e. in `onCreate()` method?

**Comment by seadowg** [comment]
> So this must be done only once, i.e. in `onCreate()` method?

Yeah exactly!

**Comment by shobhitagarwal1612** [comment]
Thanks for the suggestion!

**Comment by shobhitagarwal1612** [comment]
@seadowg I have replaced `Observable` with `LiveData` and it all looks much better than before. Although, I have kept the RxJava Observables to bind `DataModel` with `ViewModel` as it provides more flexibility and complete control. Please have a look at it again.

**Comment by shobhitagarwal1612** [comment]
@lognaturel @grzesiek2010 Please give feedback regarding the approach and usefulness of the added tests. I want to add more tests but the diff is getting larger and larger. So, I would like to get feedback on this much work that I have done before proceeding any further. If yes then we can merge this to get the architecture and the basic tests in. And in later PRs, I can add remaining tests which will be based around removing the one-to-one mapping between View and ViewModel and covering the entire activity with tests

**Comment by lognaturel** [comment]
There's a lot of good stuff here but as you note, @shobhitagarwal1612, the PR has gotten quite large and has deviated from the original goal of adding tests. Since the refactors are not supported by tests and are quite extensive, I don't think it's reasonable to review this PR as-is.

It looks like the focus of the PR has become proposing a structure and process for pulling state out of activities into `ViewModel`s and for rearranging packages. Some ideas of places to start:
- set up black box tests of the form download list happy path to support refactors (coordinating with @mmarciniak90 who will likely be introducing some Appium tests)
- isolate some related pieces of state to make observable rather than directly accessed by the activity and discuss the structure (agreed using `LiveData` would be more advantageous). The proposal should include a description of what decisions you've made @shobhitagarwal1612 and why.
- focus on user benefit and make sure there is an issue filed to support the proposed changes

**Comment by shobhitagarwal1612** [comment]
Sure @lognaturel. I agree with your comments. Will start working on the plan soon

**Comment by lognaturel** [comment]
Closing for now due to inactivity but looking forward to more in this direction!

**Pull request closed without merging**
