### PR TITLE
Downgraded androidx.lifecycle:lifecycle-extensions

### LINKED ISSUE #3418: Fill Blank Form page is always empty in Android 10
This was reported on the forum: https://forum.opendatakit.org/t/nothing-available-to-display-on-fill-blank-form-page/22974/2.

#### Software and hardware versions 
Collect v1.24, Android v10, Installed from Play Store (doesn't appear in debug builds)

#### Problem description

Downloaded forms are not displayed in "Fill Blank Form" page on Android 10.l

#### Steps to reproduce the problem

On an Android 10 device with Collect installed from the Play Store:
1. Download a form
2. Open "Fill Blank Form"

Form is not shown.

#### Expected behavior

Downloaded forms should be shown.

### Other information

After digging in a little the problem appears to have appeared in https://github.com/opendatakit/collect/commit/237121bf0c5938a65f3d7f04f7285e65ba3c8218. It's only reproducible on builds using ProGuard (`minifyEnabled(true)` in `build.gradle`).

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #3418 

#### What has been done to verify that this works as intended?
I tested the fix using `odkCollectRelease` build.

#### Why is this the best possible solution? Were any other approaches considered?
Seems like a bug in `androidx.lifecycle:lifecycle-extensions:2.2.0-beta01+`. The problem is that [onLoadFinished()](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/activities/FormChooserListActivity.java#L227) is not called, what interesting it works well in another place FileManagerFragment, the only difference is that there it's used in a Fragment and here it's used in an Activity, so it might be a bug related to activities).

When it comes to loaders they have been deprecated so I filled an issue to replace them https://github.com/opendatakit/collect/issues/3419 I can't be sure but I believe it will allow us to upgrade `androidx.lifecycle:lifecycle-extensions`

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
To test the issue we need a device with Android 10.
Then we need to update [debug build](https://github.com/opendatakit/collect/blob/master/collect_app/build.gradle#L118):
adding:
```
minifyEnabled(true)
proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
```

Please also confirm that problems with `ClassCastExceptions` are not visible again: https://github.com/opendatakit/collect/pull/3395

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
@grzesiek2010 Can you remind me why we even tried to use alpha and beta releases? I thought we had agreed to only use them when no full release was compatible with everything else. In this case, if `2.1.0` was compatible, we should not have been using pre-release versions.

**Comment by grzesiek2010** [comment]
> I thought we had agreed to only use them when no full release was compatible with everything else

That's true but I think we agreed on it after we upgraded the lib to `2.2.0-alpha04` which was buggy and I bumped it to `2.2.0-beta01` which turned out to be buggy as well. Of course, we could have downgraded it after discovering those bugs with `ClassCastException` but we didn't.

**Comment by seadowg** [comment]
Just marking this as `high priority` on the assumption we want to get it out as a hotfix for 1.24.

**Comment by mmarciniak90** [comment]
**Tested with success**

Tested on **emulator** with Android 10
Verified also on Androids: 9.0, 8.1, 7.0, 6.0, 5.1, 4.4

Verified cases:
* availability the form which was download from Aggregate on `Fill Blank Form` view
* availability the form which was download from Google Drive on `Fill Blank Form` view
* filled `all-widgets-fieldlist-noosm.xml` form  - #3388
* filled `TestRatingWidget.xml` form - #3384

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Pull request merged**
