### PR TITLE
Audio widget

### LINKED ISSUE #1120: Improving the audio widget
This is the proposed wireframe for the new UI
audio widget

When no audio file is selected, then the bottom layout with play buttons and seekbar will remain hidden

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Resolves #1120 

device-2017-06-12-133526

Please merge #1128 to update the `ui-refresh` branch

### CODE REVIEW

**Comment by lognaturel** [comment]
Nice! I presume this will continue evolving as you decide on app-wide defaults for spacing, colors and things like that so I won't comment too much on the visual aspect. Here are a few comments and questions about the functionality:
- it took me a while to understand that the seek forward and back buttons only work when the audio is playing. First question is are they necessary? The scrub bar works pretty well and is intuitive. It might be easier not to have skip buttons. If they are there, it would be helpful for them to work when the audio is not playing.

- when scrubbing, it's very easy to accidentally swipe out of the question. @grzesiek2010 just checked in some code to `FormEntryActivity` that should be helpful for that since he had the same problem with the range widget.

- when scrubbing, it would be great to update the time elapsed and time remaining.

- would be great not to pause playback when changing orientation.

**Comment by grzesiek2010** [comment]
@shobhitagarwal1612 
Isn't this icon https://material.io/icons/#ic_attach_file or this one https://material.io/icons/#ic_file_upload better the second button?

**Comment by lognaturel** [comment]
@grzesiek2010 I do like the paperclip and it's what you had in your mockups, @shobhitagarwal1612!

**Comment by shobhitagarwal1612** [comment]
@lognaturel @grzesiek2010 

> when scrubbing, it's very easy to accidentally swipe out of the question. @grzesiek2010 just checked in some code to FormEntryActivity that should be helpful for that since he had the same problem with the range widget.

Done


> Isn't this icon https://material.io/icons/#ic_attach_file or this one https://material.io/icons/#ic_file_upload better the second button?

Added the paper clip icon


> when scrubbing, it would be great to update the time elapsed and time remaining.

Done


> it took me a while to understand that the seek forward and back buttons only work when the audio is playing. If they are there, it would be helpful for them to work when the audio is not playing.

Actually, the buttons are working in pause state too. The seekbar and the timer weren't updating, so that was a bug. Fixed that too.


> The first question is are they necessary? The scrub bar works pretty well and is intuitive. It might be easier not to have skip buttons. 

It felt like an incomplete audio player to me. If you think that it's not necessary then I don't have any problem in removing them.

> would be great not to pause playback when changing orientation.

I used the same `MediaPlayer` object which is used for playing audio in `QuestionWidget` so that it automatically follows the default behaviour.

**Pull request closed without merging**
