### PR TITLE
Ensure all download errors result in a dialog

### LINKED ISSUE #4224: Security errors when getting blank form are ignored and result in empty form list
#### Software and hardware versions 
Collect v1.28

#### Problem description
If there's a security error when attempting to fetch a form list, the error is swallowed and an empty list is shown.

#### Steps to reproduce the problem
Connect to a server that results in a security error. Check out https://github.com/lognaturel/collect/tree/trust-isrgrootx1, comment out `.addPlatformTrustedCertificates()` to only use the Let's Encrypt root, try to fetch the form list from the default Aggregate server.

#### Expected behavior
An error should be shown about Collect not being able to securely connect.

### PR DESCRIPTION
**Pull request by lognaturel**
Closes #4224

#### What has been done to verify that this works as intended?
I checked out https://github.com/lognaturel/collect/tree/trust-isrgrootx1, commented out `.addPlatformTrustedCertificates()`, did `git cherry-pick ff62422` to get just the commit from this PR, tried to get blank forms from the default Aggregate server on Android <= 6.0, verified I get a dialog about not being able to securely connect.

#### Why is this the best possible solution? Were any other approaches considered?
I think this captures the semantics -- the special case is when auth is required. In all other cases, a dialog with the appropriate error message should be displayed. Having that second case addressed by an `else` rather than enumerating cases means we don't risk more bugs of this kind as we add types of errors that we provide messages for.

I considered testing options. Maybe we should test all the known error types in `FormDownloadListActivityTest`? CC @seadowg. I hesitate because adding a new type is where issues are likely to come up and adding tests for the existing error types won't help with that. 

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This affects how all non-success cases are handled when getting blank forms so there are regression risks around servers requiring auth and servers with other types of failures.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by seadowg — APPROVED** [review]
This looks right to me. The code you have there is really what should have been there if we'd driven it out initially with the tests in `GetBlankFormTest`. I think I'd like to avoid trying to add more tests for `FormDownloadListActivity` at the moment as it's a bit of a monster.

**Comment by lognaturel** [comment]
> if we'd driven it out initially with the tests in GetBlankFormTest

Sounds right. Annoyingly, I looked for that test class but couldn't find it, maybe because I forgot to look for a connected test. It can be a little hard to know where some of these feature tests live.

**Comment by kkrawczyk123** [comment]
@lognaturel so far we did a regression check mostly on cases:
- Get blank form from Aggregate
- error message when set https://valid-isrgrootx1.letsencrypt.org. as server
- Get blank form from local Aggregate
- Get blank form from Central
- Get blank form from Google Drive
- Get blank form from Ona
- Get blank form from Kobo
- error messages on invalid URLs like: typo, http/https, invalid port, invalid credentials, require credentials
- Download form from the server specified in CollectTester
- submit instance using CollectTester

We are not sure if our testing is sufficient - is there anything more on your mind that we can check?

**Comment by lognaturel** [comment]
All this looks good to me and I can't think of any other cases. This does move around some code that is for handling external apps launching Collect with server credentials but I don't think there's any risk there. You have this in your regression checklist, right? I think CollectTester might exercise that.

**Comment by mmarciniak90** [comment]
**Tested with success**

Verified on Android versions: 5.1, 7.0, 7.1, 8.1, 9.0, 10.0

Verified also all regression tests related to CollectTester.

@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"

**Pull request merged**
