### PR TITLE
change goto icon from png to vector(1858)

### LINKED ISSUE #1858: Replace png icons from FormEntryActivity with vectors
#### Software and hardware versions 
Collect v1.12.2 and older versions

#### Problem description
Replace png icons from FormEntryActivity with vectors

#### Steps to reproduce the problem
Just open any form.

screenshot_2018-02-13-13-38-05

#### Expected behavior
We should use vectors instead of pngs, and both icons should be black like here for example: 
screenshot_2018-02-13-13-38-01

it looks better.

@opendatakit-bot label "quick win"

### PR DESCRIPTION
**Pull request by lumarega**
Closes #1858

#### What has been done to verify that this works as intended?
tested locally to verify that icons were changed

#### Are there any risks to merging this code? If so, what are they?
No

#### Do we need any specific form for testing your changes? If so, please attach one.
No

### CODE REVIEW

**Comment by grzesiek2010** [comment]
@lumarega 
The shape itself looks ok but the icon is visibly smaller than other icons eg. the save one (especially when it comes to height):
icons

and why the file is so complex? So many paths.

**Comment by lumarega** [comment]
@grzesiek2010 I´ll try to make it bigger, to match the other icons.

> and why the file is so complex? So many paths.

I did it using Android studio vector creator (File->new->vector asset. Then choose an SVG file) since it was an automated process I´m not sure why it created so many paths. I´m going to check that out.

**Comment by lumarega** [comment]
For what I understood, please correct me if I´m wrong, the vector paths are created based on the SVG image. So if the SVG icon has some complexity the paths to create its vector will also do so. When I built it using inkscape I used the 'trace bitmap' feature and it didn´t look really good since the original image had shadows and i believe it messed up its shape. So after that  there were a lot of corrections to make. Perhaps that´s why it became so complex. 

@grzesiek2010 I understand that this is not good for performance. Would you like better to make a simpler SVG icon and send it to me so I can make a new vector?

**Comment by grzesiek2010** [comment]
I don't think it's really important I just asked, if you are able to fix the size please do it if not let me know.

**Comment by lumarega** [comment]
I resized it and it does look better bigger. what do you think?

image

Should I close this PR and send a new one?

**Comment by lognaturel** [comment]
I agree, @lumarega! But it looks a bit distorted. Is it stretched evenly horizontally and vertically?

No need to send in a new PR. You can add another commit to the branch and push it and the PR will be updated. Basically a pull request tracks a specific branch.

**Comment by lumarega** [comment]
yeah I was looking to it now and it kind of does look distorded. I had to resize it and maybe I didn´t do it evenly. Gonna fix it. 

> No need to send in a new PR. You can add another commit to the branch and push it and the PR will be updated. Basically a pull request tracks a specific branch.

Thanks for clarifying this it's my first(s) PR so I wasn´t really sure how it works!

**Comment by lumarega** [comment]
This is what the icon looks like after evenly resizing it.

image

**Comment by grzesiek2010** [comment]
It's the same as before - the icon is visibly smaller.

**Comment by grzesiek2010** [comment]
@lumarega 
Thanks for your work. I created that icon https://github.com/opendatakit/collect/pull/2044 because I want to prevent you from struggling with graphics - you probably want to work on typical Android issues.

**Comment by lognaturel** [comment]
I'm going to close this one @lumarega so @grzesiek2010 can keep working with the simplified graphic in #2044. If you have any questions about producing vector graphics, he's a great person to find in Slack and ask, he knows a lot!

**Pull request closed without merging**
