### PR TITLE
Fixed more multiclick issues

### LINKED ISSUE #4133: Ability to multi-click in MapActivity area
#### Software and hardware versions 
Collect v1.27.3 (older versions were not verified)
Android 8.1, 9.0

#### Problem description
Ability to multi-click in MapActivity area 

#### Steps to reproduce the problem
Use case 1:
1. User multi-clicks on **map icon** next to form name on `Fill Blank Form` view
2. Map view is opened 2 times

Use case 2:
1. User clicks on map icon next to form name on `Fill Blank Form` view
2. User multi-clicks on **new instance** button on the map which launches the FormEntryActivity
3. Form is opened two times

#### Expected behavior
Multi-click should not be allowed

#### Other information 
Issues noticed while testing #4120 

@getodk-bot label "Specific to Android version"

### LINKED ISSUE #4135: Ability to multi-click on 'Go To Start' button
#### Software and hardware versions 
Collect v1.27.3 (older versions were not verified)
Android 8.1, 9.0

#### Problem description
Ability to multi-click on 'Go To Start' button

#### Steps to reproduce the problem
1. User opens form
2. User opens hierarchy view
3. User multi-clicks on `Go To Start` button
4. User is moved to first question
5. User swipes to next question but it looks like user swipes to the same question

ezgif com-video-to-gif

#### Expected behavior
Multi-click should not be allowed

#### Other information 
Issues noticed while testing #4120

@getodk-bot label "Specific to Android version"

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #4133
Closes #4135

#### What has been done to verify that this works as intended?
I tested implemented fixes manually.

#### Why is this the best possible solution? Were any other approaches considered?
Android doesn't do the job for us so we need to handle multiclick issues on our own. It's the same solution using MultiClickGuard class like we already use.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It's a safe fix so we just need to confirm that the described issues are fixed.

#### Do we need any specific form for testing your changes? If so, please attach one.
The All widgets form would be enough.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by seadowg — APPROVED** [review]

**Comment by kkrawczyk123** [comment]
@grzesiek2010 both issues have been fixed but small regression has been introduced. It is allowed to multiclick on offline layer button on map view. Issue does not occur on master, geowidgets and map settings. I am also able to reproduce it on all Android versionsns. Could you please take a look?
ezgif com-video-to-gif (38)

@getodk-bot unlabel "needs testing"

**Comment by grzesiek2010** [comment]
@kkrawczyk123 Are you sure this is regression? Could you try other devices?
That button hadn't been protected before I implemented my changes, now it is so it's strange that you claim that before everything was fine and now it doesn't work as expected. It's quite opposite.

**Comment by kkrawczyk123** [comment]
@grzesiek2010 I don't even have more devices to try on as I have already tried on all of them.

**Comment by grzesiek2010** [comment]
@kkrawczyk123 ok the issue should be fixed.

**Comment by mmarciniak90** [comment]
**Tested with success**

Verified on Android versions: 5.1, 7.0, 7.1, 8.1, 9.0, 10.0

Verified cases:
* multi-click on map icon next to form name on Fill Blank Form view
* multi-click on new instance button on the MapActivity which launches the FormEntryActivity
* multi-click on offline layer icon on the MapActivity
* multi-click on offline layer icon on Geo widget
* multi-click on offline layer icon in settings
* multi-click on 'Go To Start' button
* multi-click on 'Go To End' button

@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"

**Pull request merged**
