### PR TITLE
Check for READ_PHONE_STATE permission (API 23+)

### PR DESCRIPTION
**Pull request by grzesiek2010**
In this pull request, I handled three last permissions (**GET_ACCOUNTS**, **SEND_SMS**, **READ_PHONE_STATE**).

[GET_ACCOUNTS](https://developer.android.com/reference/android/Manifest.permission.html#GET_ACCOUNTS)
It's a permission we should request if we want to access google accounts:
-if we click on Google account option in Server Settings
-if we try to get forms from Google Drive
-if we try to send a finalized form to Google Sheet

The last case may be triggered manually (then a request should appear) and automattically (auto send option) and then we shouldn't ask users for permission since it takes oplace in the background, we should just display a notification that auto send failed because of permission (what i did).

[SEND_SMS](https://developer.android.com/reference/android/Manifest.permission.html#SEND_SMS)
It's a permission we should request if we want to a finalized form via SMS.
If we add an auto send option for SMS we should handle sucha a cese in the same way like above (a notification).

[READ_PHONE_STATE](https://developer.android.com/reference/android/Manifest.permission.html#READ_PHONE_STATE)
It's a permission we need to ask for if we want to have an acces for: Device ID, Subscriber ID, SIM serial number.
We use this values in forms here is a sample form: 
[preloads.xml.txt](https://github.com/opendatakit/collect/files/2209348/preloads.xml.txt)

and additionali Device ID is added to request while sending forms (atatched to a request).

None of those values is required we can still use ODK Collect without this permission but but then mentioned values are empty.
I decided to ask for this permission while the app is started for the first time. Then if needed when we open Form Metadata settings, and then if needed while sending form to the aggregate (not required but if user denies the Device ID added to a request that I mentioned would be empty)

#### What has been done to verify that this works as intended?
I tested all three permissions (cases I described above). 

#### Why is this the best possible solution? Were any other approaches considered?
It's a continuation of the approach we agreed #2119

#### Are there any risks to merging this code? If so, what are they?
No, it should be safe.

#### Do we need any specific form for testing your changes? If so, please attach one.
GET_ACCOUNTS - no form needed
SEND_SMS - a sample form available on the demo server
READ_PHONE_STATE - form attached above

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew pmd checkstyle lintDebug spotbugsDebug` and confirmed all checks still pass.
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by lognaturel** [comment]
Thanks so much for the thoughtful decisions you made around when to ask for permissions and for the great description, @grzesiek2010! And thanks for replacing `easypermissions`, I was just going to file an issue for that. 👍 

I agree with what you've done for GET_ACCOUNTS and SEND_SMS. READ_PHONE_STATE is even trickier.

> ask for this permission while the app is started for the first time

I don't think we should do this. For most enumerators, this will never be relevant because they'll never get a form that requires any of that metadata. It's already a difficult permission to explain and even harder to explain if it's not something their organization uses.

> open Form Metadata settings

Definitely.

> sending form to the aggregate (not required but if user denies the Device ID added to a request that I mentioned would be empty)

Is that too late? In other words, if the user grants the permission then, does the value actually get written? It feels like it should be either on form launch or on form save or perhaps both. I also wonder if it should be blocking -- we don't even allow a user to open or save a form if they don't grant the permission. If an organization wants to track which device made a submission, I think it's really important those values are populated.

**Comment by grzesiek2010** [comment]
> Is that too late? In other words, if the user grants the permission then, does the value actually get written?

it's just for deviceid we attach to a request it's not about metadata so it's ok.

>I also wonder if it should be blocking -- we don't even allow a user to open or save a form if they don't grant the permission.

I don't think it's a good idea, as you noticed most of forms don't contain any of that metadata. Maybe we can just ask for that permission on a form launch only if that form contains dangerous metadata (deviceId, phonenumber, simserial or subscriberid)?

**Comment by jd-alexander** [comment]
> If we add an auto send option for SMS we should handle such a a case in the same way like above (a notification).

Good idea! @grzesiek2010  Autosend ideation #2370  and a first attempt #2378 has already begun so I could implement a permission check within `SmsService` that ties into the existing notification infrastructure once we finalize its implementation.

Just thought of something else, just noting here so I can remember. If the permission to send SMS is granted and then revoked during a submission then I need to ensure that the path to the actual SMS sending is guarded by such a check so that a crash doesn't occur.

**Comment by jd-alexander** [comment]
> I don't think it's a good idea, as you noticed most of forms don't contain any of that metadata. Maybe we can just ask for that permission on a form launch only if that form contains dangerous metadata (deviceId, phonenumber, simserial or subscriberid)?

Making permission prompts contextual is always a good idea because the less of them we can have the better so I would do this.

**Comment by lognaturel** [comment]
To be explicit, @grzesiek2010 reminded me that there are 2 different uses of `deviceid` -- one is to attach to every single request and the other is what I was thinking of, when it is used in a form.

For the `deviceid` attached to each request, I think what this PR does is good. That is:

> sending form to the aggregate (not required but if user denies the Device ID added to a request that I mentioned would be empty)

So the case we still need to finalize a strategy for is when device info is explicitly used in a form definition. In that case, I think we should require the permission and either not let the user open the form or not let the user save an instance. Either is fine by me. When these "preloads" are included in the form, it means it's information the survey developer wants and it should be treated as a required field. The challenge is that these fields are populated at the JR level. I haven't yet had a chance to look at how we can identify a form that contains such a "preload". The goal would be to do exactly this:

> Maybe we can just ask for that permission on a form launch only if that form contains dangerous metadata (deviceId, phonenumber, simserial or subscriberid)?

**Comment by grzesiek2010** [comment]
@lognaturel 
The pr is updated!

We agreed that we should request the permission before starting a form if needed (if a form contains dangerous preload params). I implemented required changes to do that. In order to check which form contains mentioned dangerous preload params, I decided to add a new column to the database and check for those params only during downloading forms or scanning new forms. I think it's better than checking that each time we open a form what would require more time during loading. If a user denies a form is not started as you expected.

I didn't implement requesting the permission before saving a form because I think it doesn't really make sense. I made a quick investigation and if a form is started you can revoke permissions and still everything is ok because those dangerous params are already added. Even if there is something dangerous in this case I think it's super rare and there is no need to care about it.

Of course, adding a new column required upgrading database version so I tested this case and everything looks ok.

There is only one problem - lack of backward compatibility... I mean if you already have forms we don't scan them again to update the new column I added. We could fix this problem, for example, recreating the forms.db after upgrading to version 7 and the just scanning forms again (it's triggered if you open a form list) but I'm not sure if we need that.

What do you think?

**Comment by yanokwa** [comment]
I don't know if I love adding new columns to the DB, but I'll leave that to @lognaturel to decide. 

I think backward compatibility is important because it feels to me like a data loss issue! The scenario I'm thinking of is this.
1. Collect is updated to this new version.
1. Enumerators don't approve the permission for some reason (likely because they are confused)
1. All my submissions now don't have important metadata like device ID.
1. Downstream processing tools that depend on metadata break.

Recreating the forms.db feels fragile and dangerous to me. I'd rather that we check the DB to see if that preloads column has a value. If we don't we add the value. If we do, we leave it alone.

**Comment by grzesiek2010** [comment]
I'm not sure if checking whether `containsDangerousPreloadParams` is empty before opening a form is a good idea. It's just for backward compatibility and is needed probably just for 1.17.0 or maybe 1.18.0 and after a few months, probably the code would be not needed. I would vote for scanning forms and updating if needed during database upgrade or maybe in DiskSyncTask but I prefer the first option.

**Comment by lognaturel** [comment]
> I didn't implement requesting the permission before saving a form because I think it doesn't really make sense.

Agreed, I initially thought preloads were like other calculations that happen again on save but it looks like they're only processed once on load. (Note: this is kind of a weird quirk and should probably be documented explicitly somewhere if it isn't already)

I think it would be really ideal for the permissions check to be triggered as-needed without needing to store something in the DB from an initial parse. Either way, it would make sense to introduce something like `PropertyManager.requiresPermissions(propertyName)` that checks if a particular property requires permissions.

It would be great if `PropertyManager.getSingularProperty` could do the check but I can't really come up with a way to do that since it doesn't know about any activity to attach any UI to, right? That would truly catch all cases where the properties were accessed. The current implementation only accounts for bind preloads but it's also possible to use the `property` "Xpath function" (see `XPathFuncExpr`). It's unlikely to be very common but is possible. Also, preloads can be evaluated as new repeats are created.

**Comment by grzesiek2010** [comment]
> I think it would be really ideal for the permissions check to be triggered as-needed without needing to store something in the DB from an initial parse.

Generally, I agree but `as-needed` in our case means request permissions if not granted before opening a form. If we check that after opening a form and then grant permissions we would need to load the form again (to inject proper values to javarosa) or do something like that somehow. So doing that before opening a form is the best solution I think you agree.

So how can we determine whether a form needs this permission or not? We would need to parse such a form and it would be heavy to do that each time we try to open any form. That's why I implemented a solution using a database and just using parsing forms which take place while downloading/scanning.

> The current implementation only accounts for bind preloads but it's also possible to use the property "Xpath function" (see XPathFuncExpr). It's unlikely to be very common but is possible. Also, preloads can be evaluated as new repeats are created.

I don't really understand this part. Could you explain or attach any sample form? Does that mean my solution doesn't work for all cases?

**Comment by yanokwa** [comment]
@lognaturel Believes that it's possible to do this check without storing it in a DB (e.g., maybe it's stored somewhere in the FormDef). I'm not so sure. We'll give it a week for us to think about our options then proceed based on what we learn.

**Comment by lognaturel** [comment]
Well, let me be specific. I'm not yet convinced that it's not possible to do reasonably without adding a db column. 

> If we check that after opening a form

The ideal would be to do it as part of loading the form, for example, in `PropertyManager.getSingularProperty`. The question is how to propagate a failure there to the UI. And I understand that `getSingularProperty` doesn't actually read the property value from the device, that's done by the `PropertyManager` constructor. This means that if the permissions check failed but then permissions were granted by the user, the code from the constructor would need to be run again before the get call on the `properties` map.

Since the dangerous calls are in the `PropertyManager` constructor which is called by `Collect.initProperties()` and that method is called at various times including settings changes and app launch, that means Collect will repeatedly try to read those values, fail and then log a `SecurityException`. This doesn't seem like a very elegant approach and in fact it seems there should be a permissions check wrapping that code instead of a try/catch. That is, if permissions are granted, read the values and if not, do nothing. That check should only wrap the actual dangerous calls. Currently, the try/catch is too aggressive, I think -- the user-defined properties should be outside of it.

See https://github.com/opendatakit/javarosa/blob/master/src/org/javarosa/xpath/expr/XPathFuncExpr.java#L404 for the `property` function. For example, you can use something like `property("phonenumber")` in a calculate. It's not terribly useful as far as I can tell since you could just use the `jr:preload` syntax for it but it does exist.

**Comment by lognaturel** [comment]
@grzesiek2010 What do you think of cherry-picking the last commit onto a new branch and continuing the work there? That way the accounts and SMS permissions can be merged and hopefully stop accumulating merge conflicts!

**Comment by grzesiek2010** [comment]
> What do you think of cherry-picking the last commit onto a new branch and continuing the work there? That way the accounts and SMS permissions can be merged and hopefully stop accumulating merge conflicts!

I created a separate pr for GET_ACCOUNTS and SEND_SMS and I'll fix this one.

**Comment by lognaturel** [comment]
Thanks, @grzesiek2010, those were easy to merge!

Backing up a few steps, you initially asked for the permission on app launch because that's when the `PropertyManager` constructor reads the values from the device, right?

Would be good to explore if/how you can propagate a permissions message from `PropertyManager.getSingularProperty` without needing to rework the whole structure. This could be a use for `RxEventBus`. 

Here are the cases I can think of:
- `getSingularProperty` is called and Collect has permissions. This is actually not all that straightforward because it's possible that Collect didn't have permissions when the constructor was called. I'm not entirely sure what the right behavior is. Maybe check to see if the property is `null` and if so read it from the device again?
- `getSingularProperty` is called, Collect doesn't have permissions and user gives permissions. In this case, we're pretty sure we need to read the property from the device again and in fact we probably need to read all properties again so calling the `PropertyManager` constructor seems like the right action (that code would probably need to move to a private method because we don't want to create a new one, just reload the values).
- `getSingularProperty` is called, user doesn't have permissions and user doesn't give permissions when prompted. The form shouldn't finish loading.

All this makes me wonder a couple of things:
- if we do the check for permissions when getting the property and then possibly have to read it from the device again, is storing all the properties in the `properties` map really all that useful or should the getter just read from the device? What are the benefits to calling building the `properties` map on app launch? Performance?
- what should happen if `initProperties` has been run and then the user revokes the permission? Seems extremely unlikely to happen but really the properties should probably be cleared? Again, this might indicate that `getSingularProperty` should be responsible for getting the property value from the device.

**Comment by grzesiek2010** [comment]
@lognaturel 
I took another look at this issue after my break and I think a better solution would be to implement a small change in the javarosa repo https://github.com/opendatakit/javarosa/commit/048d4e0c6870a7bca9116c3436b0b6e19b421825

and then I would be able to check easily if a for contains dangerous preloadParams or not. What do you think? I know it would require a new javarosa release but in my opinion, it's simpler and clearer than checking params in `getSingularProperty` which may be called in many different situations/cases.

**Comment by grzesiek2010** [comment]
or maybe just collect preloadParams in the same class and then check them on the Collect's side because none of them are dangerous for javarosa so maybe it's not a good naming.

**Comment by grzesiek2010** [comment]
anyway, I think it's a better way to implement changes on in javarosa.

**Comment by lognaturel** [comment]
While I do like that better than the DB option, it still doesn't result in checking the permission on use. That is, someone could load a form, revoke the permissions and then be in an odd state. Again, not super likely but checking for permissions preemptively is against the spirit of the permission checks. They're supposed to be invoked when a resource is accessed. 

Additionally, it's really odd for JavaRosa to save state about a specific set of preload names. First of all, it currently has no knowledge of any particular preloads since that's all done by concrete `PropertyManager` implementations in the clients. Then, these specific preloads are entirely Android-specific but JavaRosa is not. And of course, this still wouldn't address use of the `property` function.

> `getSingularProperty` which may be called in many different situations/cases.

Yes, exactly. If `getSingularProperty` did the dangerous call and checked for the permission, that would catch 100% of cases. It sounds like you think there are cases where the permission check wouldn't be needed. When would that be?

Did you look into the `getSingularProperty` possibility at all? What were your findings?

**Comment by grzesiek2010** [comment]
Ok now I see I'm not able to convince you :smile: 

> Did you look into the getSingularProperty possibility at all? What were your findings?

yes, I'm on it and it's almost ready. I'll create a pr ASAP.

**Comment by lognaturel** [comment]
Replaced by #2506 

Thanks, @grzesiek2010! Hopefully the reasoning makes sense. I'm trying not to be overly picky here but I do think we should aim to get these permission checks as close to "right" as we know how.

**Pull request closed without merging**
