### PR TITLE
Make constants in AdminKeys final (as in PreferenceKeys)

### PR DESCRIPTION
**Pull request by royrivnam**
#549  @lognaturel is this what is asked for in the issue of making AdminKeys as true constants.

### CODE REVIEW

**Comment by yadav-rahul** [comment]
@royrivnam Can you resolve merge conflicts?

**Comment by royrivnam** [comment]
@yadav-rahul i am trying..i even changed the branch to local branch from master and did it all over again and created a new pull request but it isnt working can you please give a lead on how to solve this problem

**Comment by royrivnam** [comment]
@yadav-rahul done...merge conflicts resolved

**Comment by shobhitagarwal1612** [comment]
@royrivnam Please provide more meaningful headings for the pull requests. Also close the PR #566 and refer #549 in this PR instead of #566. Thank you :smile:

**Comment by royrivnam** [comment]
@shobhitagarwal1612 done and thanks for that

**Comment by lognaturel** [comment]
Thanks everyone! @royrivnam this isn't quite right. You should be working with `AdminKeys`, not with `AdminPreferencesActivity`. Your change should not change the order of the keys or their values. You should only add `final` after the access modifier (or at the beginning of the line for package-private values).

**Pull request closed without merging**
