### PR TITLE
Explicitly address repeat in field-list case

### LINKED ISSUE #4145: RuntimeException in FormController.java:922
#### Problem description
https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/960eea5fd9eed2e302699052950fdaee?time=last-seven-days&versions=v1.28.1%20(3923)&sessionEventKey=5F7B186800E50001483327869100C764_1458566851285633918

```
Fatal Exception: java.lang.RuntimeException: Only questions and regular groups are allowed in 'field-list'.  Bad node is: /aGgNSwSLxKcrJWY8NtVfjt/Section_B/B_chitralada/asset
       at org.odk.collect.android.javarosawrapper.FormController.getQuestionPrompts(FormController.java:922)
       at org.odk.collect.android.activities.FormEntryActivity.updateFieldListQuestions(FormEntryActivity.java:2708)
       at org.odk.collect.android.activities.FormEntryActivity.access$1900(FormEntryActivity.java:200)
       at org.odk.collect.android.activities.FormEntryActivity$10.run(FormEntryActivity.java:2681)
       at android.app.Activity.runOnUiThread(Activity.java:5289)
       at org.odk.collect.android.activities.FormEntryActivity.widgetValueChanged(FormEntryActivity.java:2678)
       at org.odk.collect.android.formentry.ODKView.widgetValueChanged(ODKView.java:621)
       at org.odk.collect.android.widgets.QuestionWidget.widgetValueChanged(QuestionWidget.java:499)
       at org.odk.collect.android.widgets.items.SelectMultiWidget.onItemClicked(SelectMultiWidget.java:85)
       at org.odk.collect.android.adapters.SelectMultipleListAdapter.lambda$createButton$0(SelectMultipleListAdapter.java:106)
       at org.odk.collect.android.adapters.-$$Lambda$SelectMultipleListAdapter$apSaKhIavlUfvDCnua9cTtxGgo4.onCheckedChanged(-.java)
```

### PR DESCRIPTION
**Pull request by lognaturel**
Closes #4145

This updates the message shown in case of a repeat in a field-list and makes sure the error is caught everywhere it may occur.

#### What has been done to verify that this works as intended?
Tried it with https://docs.google.com/spreadsheets/d/159jGIYoZ5-f1JQTAWyfUFqk9-3k4mmbaM14KgbKbCbA/edit#gid=0, verified the new message is shown. This form does not result in the stack trace from the issue but it's similar.

#### Why is this the best possible solution? Were any other approaches considered?
@grzesiek2010 and I discussed several other options. He proposed using a snackbar generated in `FormController.getQuestionPrompts`. I don't love that this means having display code in a controller. His other idea was to replace the misplaced repeat by an inline message. I like this but it's a whole new concept. My thinking is that we'd like to support repeats in field lists at some point so we just need a temporary way to keep alerting users that it's not currently supported. Making the dialog message more helpful and making sure it always shows up seems like a good way to do this.

I introduced `FormDesignException` because this feels like a very particular kind of issue. Using a `RuntimeException` led us to the crash from the initial issue because calling sites didn't require that the exception be handled.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This should only provide more helpful messaging in the case of a repeat in a field-list. Regression risk should be low and all related to exceptions during form filling.

#### Do we need any specific form for testing your changes? If so, please attach one.
https://docs.google.com/spreadsheets/d/159jGIYoZ5-f1JQTAWyfUFqk9-3k4mmbaM14KgbKbCbA/edit#gid=0 is one.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by grzesiek2010 — APPROVED** [review]

**Comment by mmarciniak90** [comment]
@lognaturel, I see a double space in error message: `not  supported` 

Verified on Android versions: 7.0, 8.1, 10.0 

Verified cases:
- `field-list-repeat` form -> **user friendly error message is visible**

|PR|v1.27|
|---|---|
|Screenshot_20201126-174844|Screenshot_20201126-174648|

- `repeat_group_form` form
- `bad-instance-name` form
- rotation on error -> Form in background disappears. If error is closed, user is moved to main screen. The same behavior as before.
- adding groups
- edit submission
- jump from hierarchy view
- minimization
- light/dark mode
- RTL language

**Comment by kkrawczyk123** [comment]
@lognaturel I have noticed a small issue: When close opened dialog and swipe back it is displayed again (what is fine as it works in the same way on 1.27 and master) but when I swipe twice fast the content of the error is doubled (this is not visible on 1.27 and master), see the gif:
ezgif com-video-to-gif (43)

@getodk-bot unlabel "needs testing"

**Comment by lognaturel** [comment]
> I see a double space in error message: not supported

Ah, thanks. I went back and forth on putting "currently" in there and looks like I didn't clean up very well! Fixed.

> the content of the error is doubled 

I'm inclined to let this one go. I think what's going on is that the error is being generated from two different places. Do you think it's a big issue or might be hiding something more serious?

**Comment by mmarciniak90** [comment]
> Do you think it's a big issue or might be hiding something more serious?

We see no danger for serious consequences here.

@getodk-bot label "behavior verified"

**Pull request merged**
