### PR TITLE
Replaces nested preference screens with preference headers

### LINKED ISSUE #1184: User is moved to General Setting from Server Settings, User interface, Form manager, User and device identity when user changes device orientation
#### Software and hardware versions 
Collect current master, v1.8.0 beta-9
Android v4.1, v4.4, v5.1, v6.0, 
Device used: 
- Samsung Galaxy Young GT-S6310, 
- Samsung Galaxy J1 SM-J100H, 
- Huawei Y560-L01, 
- Sony Xperia Z3 D6603

#### Problem description
User is moved to General Setting from Server Settings, User interface, Form manager, User and device identity when user changes device orientation

#### Steps to reproduce the problem
1. User is on one of view:  Server Settings, User interface, Form manager, User and device identity
2. User changes device orientation
3. User is moved to General settings

#### Expected behavior
User is still on the same view in other orientation.

#### Other information 
Problem discovered during testing [Settings redesign #1101](https://github.com/opendatakit/collect/pull/1101)

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Fixes #1184

### CODE REVIEW

**Comment by lognaturel** [comment]
This is great, especially with a tablet form factor! I think the WIP tag has to do with the admin preferences show/hide not working, is that right? Is there anything else? @shobhitagarwal1612 do you have a strategy for addressing the show/hide?

I think it's really important to address #1184 before doing a release. At the same time, this is a pretty significant set of changes that needs to be verified before merging.

**Comment by shobhitagarwal1612** [comment]
The only bug that is left to address is to remove the extra view that is being displayed in pre nougat devices below the toolbar. Rest of the work is done

**Comment by lognaturel** [comment]
@shobhitagarwal1612 Ok, that's great! 

I see that you updated the `DisabledPreferencesRemover` but it's not working for me on a Nexus 10, API 25 emulator. Is it for you?

**Comment by shobhitagarwal1612** [comment]
I used API 25 and it was working for me. I'll check it once again

**Comment by shobhitagarwal1612** [comment]
Yes, you were right. There was a bug

**Comment by lognaturel** [comment]
Fantastic, it's working beautifully on Nexus 10, API 25 emulator. 🎉

**Comment by shobhitagarwal1612** [comment]
There are still some bugs left for API 19. Working on that

**Comment by mmarciniak90** [comment]
I noticed issues in the appearance.
- There are no lines which separate settings options on Android 6.0 and Android 5.1.
android6 0

- Extra line is visible between General Settings header and Server option on Android 4.4, 4.2, 4.1
android4 4

**Comment by shobhitagarwal1612** [comment]
> There are no lines which separate settings options on Android 6.0 and Android 5.1.

@mmarciniak90 This is the default appearance for settings in devices with Lollipop and above. Do we need to change that too?

> Extra line is visible between General Settings header and Server option on Android 4.4, 4.2, 4.1

fixed!

**Comment by grzesiek2010** [comment]
@shobhitagarwal1612 

> This is the default appearance for settings in devices with Lollipop and above. Do we need to change that too?

Why do you think it's a default appearance? I can see lines if I use master branch and those lines are not visible when I switch to your branch.

**Comment by shobhitagarwal1612** [comment]
Earlier we were not using preference headers. So it was being inflated as a normal list, hence lines between the items. 

This screenshot is of the settings screen in API 25 emulator
screenshot_1498472933

**Comment by mmarciniak90** [comment]
I checked Android settings on Android 6.0 real device - Sony Z3 and I see a lines. 
screenshot_20170626-123808
Maybe I'm wrong but I it could depend on screen overlay eg. in Samsung/Sony devices.
Additionally, all views should be consistent. When user opens sub-menu in General Settings, lines are visible. 
screenshot_20170626-123944

**Comment by shobhitagarwal1612** [comment]
@mmarciniak90 I agree that the views should look consistent. Is it ok if I remove the divider lines from all of the settings i.e. `About Settings`, `Admin Settings` & `General Settings` ?

screenshot_1498474865

screenshot_1498474859

**Comment by grzesiek2010** [comment]
@shobhitagarwal1612 

>  Is it ok if I remove the divider lines from all of the settings i.e. About Settings, Admin Settings & General Settings ?

I think it's ok. What do you think @lognaturel

**Comment by shobhitagarwal1612** [comment]
@grzesiek2010 @mmarciniak90 Done

**Comment by lognaturel** [comment]
@grzesiek2010 @mmarciniak90 I will give you a couple of hours in case you want to come back and review once again.

I've looked at it with a Nexus 5, API 22. It looks nice and consistent to me without the separator lines. I can confirm that #1184 is fixed and that show/hide with admin settings works well.

**Comment by grzesiek2010** [comment]
@lognaturel It looks ok to me.

**Comment by mmarciniak90** [comment]
Tested with success. Changing device orientation does not move the user to other view. 
Tested on Android 4.1, 4.2, 4.4, 5.1, 6.0.
Additionally, views are consistent.
Views on Android 5.1, 6.0:
screenshot_20170626-205227
screenshot_20170626-205235

Views on Android 4.1, 4.2, 4.4:
screenshot_2017-06-26-20-52-48
screenshot_2017-06-26-20-52-51

**Comment by lognaturel** [comment]
Thank you so much, @shobhitagarwal1612, @mmarciniak90 and @grzesiek2010!

**Comment by lognaturel** [comment]
@shobhitagarwal1612 Could you please resolve this conflict that came from merging in the timing feature? Thanks!

**Comment by shobhitagarwal1612** [comment]
already onto it

**Comment by lognaturel** [comment]
How are you so fast?!?

**Pull request merged**
