### PR TITLE
Reworked the banner in Ready to send screen using card view

### LINKED ISSUE #6347: Remove grey background on "Ready to send" screen
As part of [#6320](https://github.com/getodk/collect/pull/6320#issuecomment-2289205679), we want remove the grey banner for "Form last sent" to be consistent with the new styling. Without the app bar elevation / shadow it looks disconnected.  

Screenshot 2024-08-19 at 4 31 25 PM

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #6347

#### Why is this the best possible solution? Were any other approaches considered?
I tried making the custom `ReadyToSendBanner` view extend `MaterialCardView`, but it displayed gray background corners that I couldn't remove (this might be an Android bug). The solution was to wrap it in an additional `FrameLayout`, which may seem redundant at first glance.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
The only change is the visual representation of the banner in `Ready to send`. Its functionality remains the same.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by alyblenkin** [comment]
Could we left align all the text? Now that I'm seeing it, we have space to bring the icon and text closer together in the card. Otherwise, I think this looks really good and it anchors the page well.

**Comment by grzesiek2010** [comment]
> Could we left align all the text? Now that I'm seeing it, we have space to bring the icon and text closer together in the card.

Just text or the icon too? If we align both it will be like this:
Screenshot_1727424085

**Comment by alyblenkin** [comment]
Aligning the text was the only issue. I thought the icon looked fine before because the gap with the text looks too big.

**Comment by grzesiek2010** [comment]
@alyblenkin If only the text is aligned it will be like this, do you think it's better?
Screenshot_1727713717

**Comment by alyblenkin** [comment]
The white space around the card makes it difficult to get the spacing right, but I don't want to spend too much more time on it because it's already looking good with the new card and app bar changes. 

I think we keep the text aligned but add a bit more space between the icon and text (it almost gives the illusion that the icons are aligned).

Screenshot 2024-09-30 at 11 57 44 AM

**Comment by grzesiek2010** [comment]
@alyblenkin it's ready.

**Review by alyblenkin — APPROVED** [review]

**Comment by srujner** [comment]
**Tested with Success!**

Verified on device with Android 10 and 13

Verified cases:

- Light and dark theme;
- Rotate the screen, minimize the app;
- Work towards #6347

**Comment by WKobus** [comment]
**Tested with Success**

Verified on device with Android 14

**Pull request merged**
