### PR TITLE
View sent form module initial commit

### PR DESCRIPTION
**Pull request by ratikanta131**
This is for the issue #235 

It is the initial commit of view sent form module. The purpose of this is to view the forms which are already sent to server.

There will be a button in Main Menu screen named "View Sent Form", by tapping on which the user can see the sent forms.

### CODE REVIEW

**Comment by lognaturel** [comment]
Thanks so much for doing this, @ratikanta-sdrc! It's in general looking great. Could you please remove the code you commented out? Version tracking keeps a great record of how things used to be so we can easily go back to earlier versions if needed. In general, you can feel free to remove code that's no longer needed or that needs to move.

I think that just like with "Edit Saved Form" and "Send Finalized Form", the "View Sent Form" button should show in parentheses how many forms are available for viewing. Similarly, there should be an option in the admin settings to hide the button "View Sent Form" button just like for the other main menu buttons.

For pictures, the filename is shown. I think it would be more useful if the picture itself could be displayed. There may be other widgets that could benefit from being displayed differently.

Now for a bigger functionality question. This currently only displays forms that were sent and are still on the phone. That means that someone who has the "delete after send" option checked or deletes a form will not see all the forms they have sent. One of the reasons people want this feature is to be able to confirm that submissions were actually sent so I think it's important that there's a record of all forms sent. 

One way to go about this would be to change the behavior of instance deletion so that it does not remove the DB record but instead changes the status to "deleted" with a deletion timestamp. That way, deleted instances could still show up in "View Sent Form" with sent time and deletion time. The user wouldn't be able to see the values but would at least know that it was sent. What do you think? It would be good to get some other opinions on this, too -- @batkinson @yanokwa @nribeka

**Comment by chrislrobert** [comment]
It's a bit unclear to me how much the goal is to just list forms with meta-data vs. show actual form data, but please just keep in mind that many projects use encrypted forms (appropriately so!). For those, only meta-data will be available. So hopefully the feature will still be implemented so as to be at least minimally useful for encrypted cases as well.

**Comment by lognaturel** [comment]
@chrislrobert That's a great point. My understanding is that the biggest reason this is asked for is for data review. But an important secondary goal is for enumerators to be able to confirm that the data they collected was sent. I think you're right that for encrypted forms, metadata should be shown even if the full form can't be reviewed. The UI will need to indicate to the user which forms can and can't be viewed and why. There could be something like an icon that shows the status (trashcan/lock) and/or graying out of instances that can't be viewed.

**Comment by ratikanta131** [comment]
Okay. So we are going to make the changes and update this PR. @lognaturel Please confirm.

**Comment by chrislrobert** [comment]
Great, thanks! FWIW, when people review things they almost always want to change them. So teams that want to do in-field review generally follow the save -> review -> finalize -> send workflow. If you review post-finalization, you can do that with unencrypted forms -- but if you edit and make changes then the UUID gets changed (appropriately enough) and then you end up with what people consider to be duplicate submissions (also appropriately enough) in the data stream. With a bunch of investigation, they find that the re-edited submission looks like a 100% duplicate but it's maybe only a 99% duplicate because some small change was made to some field somewhere. I agree that confirming what submissions/data was sent is a solid use case, but I'd just be prepared for everybody to next demand the ability to edit... in which case, really, they just should have followed the save -> review -> finalize -> send workflow instead of the save+finalize -> send -> review workflow. I think that you'll want to keep pushing people into the former workflow (where they can make changes without creating duplicates) rather than the latter.

**Comment by lognaturel** [comment]
@chrislrobert It does seem likely people will be asking for edit and I agree with your suggestion to recommend they save -> review -> finalize -> send. Thanks for the heads up!

@ratikanta-sdrc That sounds fantastic. To summarize, I think these are the changes and additions to make:
1. Remove commented out code
1. Add number of sent forms in parentheses after 'View Sent Form' button name
1. Move 'View Sent Form' button to below 'Send Finalized Form' (we didn't talk about this but I think it makes more sense with the workflow)
1. Add option in admin settings to hide 'View Sent Form' button
1. Change the behavior of instance deletion so the metadata in the database isn't deleted but rather the status is changed. Make sure deleted forms only show up in 'View Sent Form' (not in 'Edit Saved Form', etc)
1. Indicate which forms can't be viewed with a lock for encrypted forms and a trashcan for deleted ones (you can take icons from [https://material.io/icons/](https://material.io/icons/))

Don't hesitate to discuss any of this here and we can work on it together!

**Comment by ratikanta131** [comment]
Thanks for the summary @lognaturel . After conformation from @yanokwa we will start implementing it.

**Comment by yanokwa** [comment]
@ratikanta-sdrc I agree with @lognaturel's summary. Please start and update the issue if you run into any problems!

**Comment by ratikanta131** [comment]
Thank you @yanokwa, we will work on the code and update this PR.

**Comment by lognaturel** [comment]
@ratikanta-sdrc There have been some new requests for this feature and it should be a priority. Unless you plan on working on it in the next few days, let's have someone else take a look at it. Thanks!

**Comment by ratikanta131** [comment]
@lognaturel  Sorry for being off the radar since last few weeks. We were busy with some project deliverable and still are. We need around two weeks time to complete the above changes. If this time line is fine then we will move on with the development otherwise we will also be happy if someone is doing it. We can help in the code that we have already done.

**Comment by lognaturel** [comment]
That's perfect, @ratikanta-sdrc! Let us know how we can all help. I know it's a very busy time of year and I hope you and your team have had a great start to 2017.

**Comment by ratikanta131** [comment]
Yes @lognaturel , So will we move on with the development?

**Comment by lognaturel** [comment]
Yes, please! We appreciate anything you can contribute. If it's looking like 2 weeks isn't going to work out, let us know and we can see about someone else finishing it.

**Comment by ratikanta131** [comment]
Thank you @lognaturel, for now we are not clear about the encrypted form thing. How will we know the sent form is encrypted or not (from the database)?

**Comment by lognaturel** [comment]
You're right, there isn't that information in the DB. So maybe what's better is to have something that identifies an instance as non-editable when the canEditWhenComplete property for that instance is set to false. If the user taps on that instance, a popup with the cannot_edit_completed_form string can be shown ("This form cannot be edited once it has been marked as complete. It may be encrypted."). How does that sound?

**Comment by ratikanta131** [comment]
Our condition was if the instance is encrypted then we won't allow users to view it in "View Sent Form". We are not letting the user to edit it anyways because it's SENT form. So if we can put something like isEncrypted (true/false), we will get the solution. If the isEncrypted value is true then we will show the lock icon, if false we will allow user to view it.
OR
We can keep two more status SENT_ENCRYPTED and SENT_DELETED. SENT_ENCRYPTED will show the lock icon in the list and SENT_DELETED will show the delete icon in the list. If the status is simply SENT, the user will able to view the form.

**Comment by lognaturel** [comment]
<strike>I don't see much of a benefit to making a difference between forms that can't be edited and forms that are encrypted! If you add `isEncrypted` to the DB, you'll still need to deal with the case of `canEditWhenComplete` and `isEncrypted` BOTH being false. To me, showing that the form can't be edited and giving the user a hint that it may be encrypted is good enough. But I may be missing something. @yanokwa or @chrislrobert?</strike> see next comment.

What you say about `sentDeleted` makes me realize that I wasn't thinking quite right about number 5 in the [steps list](https://github.com/opendatakit/collect/pull/251#issuecomment-261877240). I wrote that the instance deletion behavior should be changed but it should really say that instance deletion _for sent forms_ should be changed to leave the metadata record. In other words, deletion should stay the same EXCEPT for forms that have already been sent. In that case and only in that case, the metadata record should stay. To figure out that it's deleted, you can either use the fact that there's no corresponding XML instance or add a boolean or timestamp record in the database. I tend to like `deletedOn` as a timestamp but I don't feel strongly about that.

**Comment by lognaturel** [comment]
Arg, I apologize. The fact that `canEditWhenComplete` is set to `false` doesn't necessarily mean it can't be **viewed** and we're only going to be viewing forms in this case. So perhaps that's not the field to use. I don't know if it's possible to view a form that's not encrypted and for which `canEditWhenComplete` is set to false, though.

**Comment by lognaturel** [comment]
Ok, I'm coming back at this with a clearer head so will hopefully have better ideas. Thank you for asking great questions and making sure that we get this right.

I think that in the list view, the user just needs to know whether or not a form is viewable. Let's start by just showing [the visibility off incon](https://material.io/icons/#ic_visibility_off) in all cases that the form can't be viewed. I believe there are three reasons that forms would not be viewable:
- the instance has been deleted
- the blank form has been deleted
- the instance is encrypted

When building the list, I think you can do the following checks:
- check to see if the instance has been deleted, if it has, show that the form is not viewable
- look up the `jrFormID` in the forms database to see if the blank form is on the device, if it's not, show that the form is not viewable
- if the blank form is on the device, see if it has a value set for the `base64RsaPublicKey` field, if it does, show that the form is not viewable (because it is encrypted)

So now there's the question of how to keep track of forms that have been sent then deleted. I think the way most aligned with what has been done so far would be to add a `sentAndDeleted` option to the `status` column. It would be nice to also show to the user the date of deletion *in addition to* the date of submission. Perhaps that information can simply added as a second line in `displaySubtext`? I don't know whether you can have linebreaks there but I imagine so.

Quick mockup of what I'm proposing:
screen shot 2017-01-19 at 9 28 06 pm

For now, I think it's fine to simply make the rows that can't be viewed non-clickable.

How does that sound?

**Comment by ratikanta131** [comment]
Thank you @lognaturel for the clarity. This sounds good to us and this much information will be enough to move on for now. We have completed the development part of 1, 2, 3 and 4 small points out of 6 [steps](https://github.com/opendatakit/collect/pull/251#issuecomment-261877240). Now we will do the left two steps.

**Comment by ratikanta131** [comment]
@lognaturel We have completed the [steps](https://github.com/opendatakit/collect/pull/251#issuecomment-261877240).

**Comment by lognaturel** [comment]
Thank you! 🎉 It's looking really nice!

I haven't had a chance to look at the code deeply yet but I do see that it will need a database migration to be runnable. Could you please add the new DB column in `onUpgrade` in `InstanceProvider.java` for the new DB version 4?

I also see that while the new column is currently named `deletedDate`, it actually represents a generated subtext string analogous to `displaySubtext`. It would be better to store and use the date itself so that the string displayed to the user can be properly localized (eventually we'll probably want to change `displaySubtext` as well). The constant currently called `DELETED_SUBTEXT` should then also be renamed to `DELETED_DATE`.

In terms of behavior, I see the following:
- This PR also changes the behavior of "Edit Saved Form" so that finalized forms are not editable. I believe that they should be editable. @yanokwa?
- Relatedly, encrypted forms are encrypted on finalization so they should be editable until finalized.
- I sometimes see the "not visible" icon appear next to forms that are visible as I scroll. I wonder if it's some kind of cell reuse issue?
- When I view a sent form that starts with a repeat (e.g. Biggest of N Set from the test server), it shows me the first group rather than showing me the top level that I see when I edit the same saved form.

**Comment by yanokwa** [comment]
Agreed that non-encrypted finalized forms should be editable. As long as a form hasn't been sent and is editable, why restrict the user from editing it?

**Comment by ratikanta131** [comment]
Okay @lognaturel  we will look into it and will try to do the changes.

**Comment by lognaturel** [comment]
@ratikanta-sdrc We would like to have this included in the Feb 20th release. Let me know if you can get it done by Feb 15. If not, someone else can do it. Thanks!

**Comment by ratikanta131** [comment]
@lognaturel Sorry for the delay, I know these are small changes but we really busy with some serious deliverable. We will be happy if somebody will do this and if this feature is getting included in Feb 20th release.

**Comment by lognaturel** [comment]
Thanks for getting it most of the way there, @ratikanta-sdrc and good luck with your project!

**Comment by ratikanta131** [comment]
You are welcome @lognaturel . Thank you for the opportunity.

**Pull request closed without merging**
