### PR TITLE
CODE_REFACTORING: Added one general method to create buttons for widgets

### PR DESCRIPTION
**Pull request by grzesiek2010**
This pr contains code refactoring. I've implemented one general approach to build buttons for the widgets.

#### What has been done to verify that this works as intended?
I've used AllWidgets form to review all widgets and confirm it looks like before. I've used also forms froms https://github.com/opendatakit/collect/pull/1274 to test range widgets.

#### Why is this the best possible solution? Were any other approaches considered?
Now we have one general method to build buttons for our widgets so we can be sure everything is consistent and looks the same.

#### Are there any risks to merging this code? If so, what are they?
I can't see any risk.

### CODE REVIEW

**Comment by grzesiek2010** [comment]
@lognaturel it's a pretty small but really needed improvement which makes our code a little clearer. Please take a look.

**Comment by lognaturel** [comment]
Seems like a good change to me. I noticed that there was some inconsistency between button sizes on tablets so capturing this redundancy seems great. One that's missing is the UrlWidget because it currently uses an XML layout. Would be good to give that one the same treatment.

**Comment by grzesiek2010** [comment]
@lognaturel it's ready

**Comment by shobhitagarwal1612** [comment]
Looks fantastic!

**Review by lognaturel — APPROVED** [review]

**Pull request merged**
