### PR TITLE
Collect #535: Editing a form instance from an external app shows blank layout

### PR DESCRIPTION
**Pull request by batkinson**

### CODE REVIEW

**Comment by lognaturel** [comment]
Thanks, @batkinson, this seems like a reasonable first step. I'll review in more depth soon.

To be clear, we do want to remove all need for extras and those constants before the next release. I think that if anyone has tried to use the intent and noticed that the extras were needed, they would have told us that it made no sense, not gone ahead and used it. So we can start with something like this but we should do a deeper refactor as soon as possible.

**Comment by batkinson** [comment]
> they would have told us that it made no sense, not gone ahead and used it. 

You mean besides me? I *had* to do it, because the functionality broke. Removing them (depending on how they are removed) may break all apps until the integrating application is *also* updated to remove the extras that were required by the change. To really clean this up, it may requiring breaking people *twice*.

**Comment by lognaturel** [comment]
@yanokwa What do you think. Do we keep a bad API change that was made by mistake in the off chance that someone may have adapted to it? I think breaking integrations twice is worth it to fix our mistake.

**Comment by batkinson** [comment]
@lognaturel I am definitely not advocating for keeping "a bad API change". I *am* advocating that this isn't how you want to handle things if integrations are of more interest than forks. During active development, following the breakage is slightly annoying, but manageable. However, for deployed solutions if API stability isn't likely, there's no alternative but to fork. I just want to call attention to what you're doing in case the integrator's perspective is not apparent.

**Comment by lognaturel** [comment]
Yes, I completely understand. The higher-level mistake was that we (I) forgot about integrations / thought they weren't actually happening. That was very unfortunate and I think we're now equipped to make sure it doesn't happen again.

I agree we need to commit to provide API stability. We also need to document integration points, test them, and get a good sense of how people actually use them. I would rather be upfront about the mistake introduced in the API and subsequently removed, document it in the release notes and deliberately act on the commitment to a stable API moving forward rather than leaving bad code in to support a bad API that we inadvertently introduced!

**Pull request closed without merging**
