### PR TITLE
SurveyCTO contribution: Fixed application crash when loading offline map tiles.

### PR DESCRIPTION
**Pull request by meletis**
@lognaturel reported a crash in #1045. We have fixed it on our branch and we should share that fix here.

### CODE REVIEW

**Comment by grzesiek2010** [comment]
@meletis 
I don't understand why we need this change because if I download and example file from http://geoodk.com/mbtiles_howto.html everything works well without this change as well. 

The stacktraces attached in #1045 are not related to this fix. Please try an example file from https://www.mapbox.com/help/define-mbtiles/
I believe there is just something wrong with that second file.

@lognaturel @meletis What do you think as I said everything is ok if I use the first file.

**Comment by meletis** [comment]
It IS related but only for some .mbtiles files and some devices. You see, we verified that there are some devices (Android API versions actually) that using the wrong table name ("images" instead of "tiles") doesn't raise any exception. The code continues, the InputStream is null which gives a zero for the Bitmap height, THEN the app crashes. But in some devices, the Cursor throws an SQL exception because the table name is bad, so the error stack trace is different in those cases.

If you want to verify my fix you can try with this file (before merging the fix of course):

https://github.com/klokantech/vector-tiles-sample/releases/download/v1.0/countries-raster.mbtiles

If you open this file with an SQLite browser, you will see that there is no "images" table in that, but there is a "tiles" table. The .mbtiles file that you used contains both the "images" and the "tiles" tables so that's why it can never fail even without the fix.

According to the [specs](https://github.com/mapbox/mbtiles-spec/blob/master/1.2/spec.md), the "images" table is not something that we can rely on, since it is not even documented.

**Comment by grzesiek2010** [comment]
@meletis 
You are right we need this fix.
Using your file I can reproduce the issue and I can see:

> android.database.sqlite.SQLiteException: no such table: images (code 1): , while compiling: SELECT tile_data FROM images LIMIT 0,1
                                                                             at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                             at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1093)
                                                                             at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:670)
                                                                             at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                                             at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:59)
                                                                             at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
                                                                             at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
                                                                             at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1440)
                                                                             at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1379)
                                                                             at org.odk.collect.android.spatial.OsmMBTileSource.createFromFile(OsmMBTileSource.java:85)
                                                                             at org.odk.collect.android.spatial.OsmMBTileProvider.<init>(OsmMBTileProvider.java:0)
                                                                             at org.odk.collect.android.spatial.MapHelper$1.onClick(MapHelper.java:230)

but @lognaturel attached 

> java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getHeight()' on a null object reference
	at org.odk.collect.android.spatial.OsmMBTileSource.createFromFile(OsmMBTileSource.java:93)
	at org.odk.collect.android.spatial.OsmMBTileProvider.<init>(OsmMBTileProvider.java:0)
	at org.odk.collect.android.spatial.MapHelper$1.onClick(MapHelper.java:230)
	at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1119)
	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1155)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3152)
	at android.widget.AbsListView$3.run(AbsListView.java:4067)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

that's why I said it's not related. The file she used still doesn't work (even with your fix). But now I agree with you we need that. Thanks for the explanation!

**Comment by meletis** [comment]
Hmm, you are right. I think I have overlooked the stack trace. You are right, there are two bugs here and we only fixed one. But at least we can keep this one. 

Thanks!

**Comment by lognaturel** [comment]
Thank you @meletis!

Closes #1092.

**Pull request merged**
