### PR TITLE
Add quick attribute support for cascading selects

### LINKED ISSUE #240: Add quick attribute support for for cascading selects
The folks at https://github.com/medic/medic-collect have noticed that `appearance="quick"` was not working for cascading selects. They have added a new widget to be able to handle this field type and it'd be good to include it in Collect. 

The relevant bits of code are at https://github.com/medic/medic-collect/blob/master/src/org/odk/collect/android/widgets/WidgetFactory.java#L85

### PR DESCRIPTION
**Pull request by grzesiek2010**
This PR is in reference to resolve #240

### CODE REVIEW

**Comment by lognaturel** [comment]
Looks good. Can you please attach the form that you used for verification? That would be a good thing to do in general. You can change the extension to .txt and just drag it into a comment.

**Comment by grzesiek2010** [comment]
Here you go
[COLLECT-240.zip](https://github.com/opendatakit/collect/files/738379/COLLECT-240.zip)

**Comment by lognaturel** [comment]
Do you have any sense of what that `derived` constructor parameter was supposed to be for? I noticed the `StringWidget` also has it, also unused for some reason.

**Comment by grzesiek2010** [comment]
I have no idea. I've been working with ODK it was always unused as i remember.

**Comment by lognaturel** [comment]
Good to see it gone, then!

**Pull request merged**
