### PR TITLE
Fixed broken audit file when there is a new form with different audit options

### LINKED ISSUE #3100: Values in audit file are mixed after updating form and changing audit options
#### Software and hardware versions 
Current master branch

#### Problem description
The problem exists only if we upgrade a form disabling one of the options and we edit a saved form so it's rather a very rare case.

#### Steps to reproduce the problem

1. Create a form with tracking locations and changes in audit file.
2. Fill a form.
3. Upgrade the form disabling one option.
4. Edit the saved form.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #3100 

The case described there, is very rare. My proposed solution is to add one empty line in audit file and a new header below when we edit a form with existed audit file which was created using different options (more or fewer columns). The result would be like:

image

The other possible solution would be to keep the same header with columns we don't need anymore but then adding values in appropriate places would be difficult and the code would be more complex. It could also indicate that there was something wrong for example we would keep location columns but all values would be empty, then someone who reviews such a  file would be confused.

@lognaturel If you accept my solution I'll add some automated tests.

### CODE REVIEW

**Comment by lognaturel** [comment]
It should always be possible to machine-interpret audit files just by reading a single header. This solution is easy enough for a human to deal with but breaks any downstream tools that need to parse these files.

Is this case possible when a form definition is updated from a server or can it only happen when pushing forms manually from `adb`? I thought that instances remained associated with the form definition with a matching `form_id`/`version` combination and so that (provided a server doesn't allow a different form def that reuses a `form_id`/`version` tuple), this kind of change wouldn't affect an existing instance.

If it's only possible with manual push, I think we could consider simply documenting the limitation. If we do want to fix it, I think the right thing to do is if an audit file exists (the filename in the instance should be used to determine this, not hardcoded `audit.csv`), read the header from that file and
- if it matches the audit settings from the form def, do nothing
- if it doesn't match the audit settings from the form def, parse the whole file and rewrite it with the correct columns

This should definitely be done with an existing, tested CSV library that takes care of the parsing, probably http://commons.apache.org/proper/commons-csv/.

**Comment by grzesiek2010** [comment]
> Is this case possible when a form definition is updated from a server or can it only happen when pushing forms manually from adb? I thought that instances remained associated with the form definition with a matching form_id/version combination and so that (provided a server doesn't allow a different form def that reuses a form_id/version tuple), this kind of change wouldn't affect an existing instance.

you are partially right, but we can't be sure that users set form versions maybe some of them just remove the original form and upload a newer version but with the same version number.

> if it doesn't match the audit settings from the form def, parse the whole file and rewrite it with the correct columns

so in the case described above, you would remove `latitude, longitude, accuracy` columns and get rid of all collected coordinates?

**Comment by lognaturel** [comment]
> we can't be sure that users set form versions maybe some of them just remove the original form and upload a newer version but with the same version number.

That's right, Aggregate does let users do that (not e.g. Central). It still doesn't feel very likely that this would happen in the middle of filling out an instance. And even if it does, that seems like it would be a scenario that happens during development of a new form, not during a data collection campaign.

Given all that, I think I'm more inclined to do nothing and document the limitation. What do you think?

> so in the case described above, you would remove latitude, longitude, accuracy columns and get rid of all collected coordinates?

Yes, I think that would be simpler than keeping a superset. It will be a challenge for downstream tools either way.

**Comment by grzesiek2010** [comment]
> Given all that, I think I'm more inclined to do nothing and document the limitation. What do you think?

It doesn't cause any crash, just values are in wrong columns but still, it's readable for humans so I agree.

**Pull request closed without merging**
