### PR TITLE
Re-introduce app bar elevation

### LINKED ISSUE #5750: Re-introduce app bar elevation
**Problem**
The app bar is flat now that we introduce M3. 

**Solution**
We want to bring back the old elevation to help create a better distinction between the app bar and the form.

Screenshot 2023-09-22 at 11 35 46 AM

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5750 

#### What has been done to verify that this works as intended?
I've tested the changes manually.

#### Why is this the best possible solution? Were any other approaches considered?
It looks like there is no easy way to enable elevation in material 3 because it has been removed. There is also a bug that makes using gradients impossible (see: https://github.com/getodk/collect/pull/5761/files#diff-7d12231ce75168eb1a5759984db076573126bdb318d87c98dcb4059be8ba2c87R3) so I had to build my own gradient/shadow.

It would be like:

| Light mode | Dark mode |
| ------------- | ------------- |
| Screenshot_1699453557| Screenshot_1699453579 |

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Just review different screens in the app to make sure there is a shadow below the app bar. It's of course important to check both themes (light/dark).

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by alyblenkin** [comment]
@grzesiek2010 - I'm not really seeing the difference. The contrast is easier to spot in the dark theme, but they could all be darker.

**Comment by grzesiek2010** [comment]
> I'm not really seeing the difference. The contrast is easier to spot in the dark theme, but they could all be darker.

Do you mean it's not visible enough so you don't see the difference between no elevation and this pr or no difference between what we had before moving to material 3 and this pr?

**Comment by alyblenkin** [comment]
> Do you mean it's not visible enough so you don't see the difference between no elevation and this pr or no difference between what we had before moving to material 3 and this pr?

Yes, I don't think it's visible enough.

**Comment by alyblenkin** [comment]
@grzesiek2010 - the changes look great in light and dark mode! Let me know if you want me to approve this or if you're waiting for someone else to check over anything.

**Comment by grzesiek2010** [comment]
@alyblenkin if it looks ok for you please approve this pr and we can start testing.

**Review by alyblenkin — APPROVED** [review]

**Review by seadowg — APPROVED** [review]

**Comment by dbemke** [comment]
I'm not sure if the bar under Saved form and Blank forms in Delete form is expected? A screenshot of the old vs new
oldVsnew

**Comment by dbemke** [comment]
In RTL language the bar separating forms on a list (e.g. in Start new form, Drafts) is shorter on the left. The issue doesn't occur on the master version.
RTLformss
What is the expected (after all changes) in LTR languages, the line under a form should take the whole space (from the left to the right)?

**Comment by grzesiek2010** [comment]
> In RTL language the bar separating forms on a list (e.g. in Start new form, Drafts) is shorter on the left. The issue doesn't occur on the master version.

I think it doesn't have anything to do with the language direction. It has been fixed on master so I've rebased and now it should be ok.

> I'm not sure if the bar under Saved form and Blank forms in Delete form is expected? A screenshot of the old vs new

What does the old mean? It was already like that on master so I guess that line was introduced after migrating to material 3. After rebasing onto master it looks a little bit better so I would keep it. 
@alyblenkin If you think we should remove it please file a separate issue.

**Comment by dbemke** [comment]
> old mean?

Old-  2023.3.0  ; New- the PR

**Comment by grzesiek2010** [comment]
2023.3.0 does not include the new material design so as I said above that's the reason. Not directly related to this pr so we can ignore it. If @alyblenkin thinks this should be changed we can do that separately.

**Comment by alyblenkin** [comment]
> . If @alyblenkin thinks this should be changed we can do that separately.

Yup, we made this change as part of a different story! No new issue is needed.

**Comment by srujner** [comment]
@grzesiek2010 and the reason for the lack of borders around "No errors" text is similar? 
Screenshot_20231115-103808

**Comment by grzesiek2010** [comment]
> and the reason for the lack of borders around "No errors" text is similar?

I don't remember when it was changed but it's the same on master and that means it had to be removed earlier.

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on Androids: 8.1, 11, 13 (by Szymon)

**Verified cases:**
- #5750 app bar
- the bar in settings, forms, "Start new form”, "Drafts” etc.
- light and dark mode
- the bar when below there is a progress bar and a banner
- landscape, portrait view

**Pull request merged**
