### PR TITLE
Adds translations

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**

### CODE REVIEW

**Comment by lognaturel** [comment]
Translations are managed through [Transifex](transifex.com/opendatakit/odk-collect/dashboard/)! The files get overwritten each time we pull new translations before a release. I can merge this but please also make the changes there so they will persist. In fact, if you have non-technical friends who are interested in helping out, translations are a great way they can do that.

**Comment by lognaturel** [comment]
I don't think the change to the view sent form button is the right one. The default is to have just "View Sent Form" if there are no sent forms to display. The block starting at 597 sets the number of forms if it exists.

**Comment by shobhitagarwal1612** [comment]
Sure, will add them to Transifex as well :+1: 
I discussed about this project with my college friends and juniors, and some of them have already started contributing to this project

**Comment by shobhitagarwal1612** [comment]
So should I undo the changes made to the view sent button or just update the Transifex?

**Comment by lognaturel** [comment]
If you just do the changes in Transifex, we'll pull the files for the next release!

**Comment by lognaturel** [comment]
And thanks so much for getting your friends involved!!

**Pull request closed without merging**
