### PR TITLE
Fixed sending forms via SMS on Android >= 8

### LINKED ISSUE #2756: Sending forms via SMS doesn't work on Android >= 8
#### Software and hardware versions 
Collect v1.18.*

#### Problem description
Sending forms via SMS doesn't work on Android >= 8

#### Steps to reproduce the problem
Try to send forms via SMS on Android >= 8

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #2756 

#### What has been done to verify that this works as intended?
I've tested sending forms via SMS on Android  8

#### Why is this the best possible solution? Were any other approaches considered?
The first commit is just a thing we need to do. Since our targetSdkVersion is 26 we can't register brodcastRecivers in the Manifest file. More info: https://developer.android.com/guide/components/broadcasts

The second commit fixes the bug in Android 8 https://issuetracker.google.com/issues/66979952
which causes that we need the `READ_PHONE_STATE` permission granted.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This pr changes the way we register BrodcastRecivers used during sending forms via SMS so this functionality should be tested.
As I mentioned above there is a bug which affects Android 8 and we need to ask for the `READ_PHONE_STATE` permission as well (not only the `SEND_SMS` permission). It should take place only on Android 8 (API 26). So we ask for two permissions but if one of them is denied the additional dialog (with an explanation) which is displayed after denying contains an info only about `SEND_SMS` permission I'm not sure if we need a better explanation about the `READ_PHONE_STATE` since it's only Android 8 if we need I can create another pr.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by grzesiek2010** [comment]
@yanokwa 
If you think it's a high priority issue and we need a point release please let us know.

**Comment by yanokwa** [comment]
Do you know if any users are running into this problem? Also, is this bug also show up when you try to send an SMS inline?

**Comment by grzesiek2010** [comment]
> Do you know if any users are running into this problem?

I haven't' seen any reports but maybe it's because of the fact the app doesn't crash, no topics on the forum as well.

> Also, is this bug also show up when you try to send an SMS inline?

Do you ask about that bug with the `READ_PHONE_STATE` permission on Android 8 and sending messages using the default app? If so default apps for messages always need that permission an all android versions

**Comment by yanokwa** [comment]
We do want to fix this as soon as possible, but I'm not excited about doing a hot fix because: 
1. This affects a pretty small population (Android 8) in our user base (see Play Store analytics)
1. The use of SMS submissions is very tiny (see Google Analytics)
1. No one has complained
1. It's the holidays and if we break something, there aren't going to be people around to fix it

**Comment by kkrawczyk123** [comment]
**Tested with success!**
 I've tried with one message and multiple messages sent at the same time. All messages have been sent successfully, all statuses were updated correctly. 

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Review by dcbriccetti — APPROVED** [review]
Merging without review as requested by @grzesiek2010

**Pull request merged**
