### PR TITLE
Updated licenses and dependencies #786 Done

### PR DESCRIPTION
**Pull request by krishnarai30**
This PR has updated all the dependencies used in the application and new licenses have been added and previous ones have been deleted.
@lognaturel please review this.
**Issue #786 is solved herewithin.**

### CODE REVIEW

**Comment by lognaturel** [comment]
@krishnarai30 Thanks! The intent was just to update the licenses but updating the libraries is a good idea as well. Can you please describe what you did to be confident that the version changes don't affect behavior?

**Comment by krishnarai30** [comment]
@lognaturel  
As I mentioned this in issues #464 that ODK Collect is an application which is primarily dependent of libraries provided by Google.
Thus I took the liberty to update the version of only google libraries, as updating these would not result in an any negative behavior of the application.

Also checking which dependency is still useful or not, I referred to this question on StackOverflow 

http://stackoverflow.com/questions/19379517/how-to-find-remove-unused-dependencies-in-gradle

further, I removed each of dependency one by one and manually checked the behavior of the application in runtime on my phone one plus 3 with android 7.0, for producing some bugs it might produce.

Also, this will bring us closer to a step of introducing new User experince we all are excited to work upon.

**Comment by shobhitagarwal1612** [comment]
As discussed in #478, updating play services will require all the users to update the google play service in their devices to the latest version. This would require 70~80 MB upgrade which is not at all needed at the current moment.

**Comment by krishnarai30** [comment]
@shobhitagarwal1612
Google play services are at auto update in majority devices and user isn't even notified of its version change so updating Google play services is the minimal and most easiest of all.

Also the moment for UI upgrade is here thus no better time to upgrade the play services version.

Further 70-80 mb upgrade aren't any relevant data charges in any of the country in the world thus upgrading cost might also not affect the minimal user of the application.

**Comment by lognaturel** [comment]
@shobhitagarwal1612 Do you know how to tell definitively what Play Services version will be required? I was surprised to notice that this doesn't actually change the Google Play Services version in the `AndroidManifest`. It looks like it's now `10298000` but I'm not exactly sure what that means. Does that mean that there is a component that requires that version or that any component that uses Google Play Services must have that version?

@krishnarai30 Many users are actually in places with very slow connections and high data charges. 70mb-80mb can be very significant in those conditions.

**Comment by lognaturel** [comment]
Oh, I'm sorry, it looks like I hadn't refreshed properly! Yes, it does change it from `10084000`. So this is not a good change, thanks for noticing that @shobhitagarwal1612 and keeping us on the right track.

@krishnarai30 Please take out the updates that would force a Play Services upgrade.

**Comment by krishnarai30** [comment]
@lognaturel  
Yes that might be expensive and slow process but irrespective of any application installed in the device the Google play services are updated to he latest version in all devices automatically.

I would remove play services update as you say  but please reconsider once as it wont be forced by collect to update those services.

**Comment by shobhitagarwal1612** [comment]
> Does that mean that there is a component that requires that version or that any component that uses Google Play Services must have that version?

I guess it means that the version of the Google Play Services required to run the application should be atleast this much

**Comment by krishnarai30** [comment]
@shobhitagarwal1612 
Yes this means that features added between the new and old version of play services would show abnormal behaviour. 
But again play services are never out of date in any phone until and unless it is cutoff from data for long time.
Also device updates it to the latest version as soon as it is connected to the internet.
Please read the documentation about play services.

**Comment by lognaturel** [comment]
@krishnarai30 May I suggest that you read a bit about ODK and its target uses? Many users are almost entirely offline, in fact, many deployments are done through APKs that bypass the Play Store. Old devices that may not have the option of updating Play Services are common. Certainly we can make the update once we leverage features that require it but we should aim to delay it as much as possible.

**Comment by krishnarai30** [comment]
@lognaturel 
Thank you!
I realized the usage of Collect and an updated the licenses as required. 
Will surely keep these valuable inputs for future contributions. 
Please review the PR. 
@shobhitagarwal1612 Thanks for helping us out buddy!

**Comment by lognaturel** [comment]
Thank you, @krishnarai30, and welcome to the project! 🎉

**Pull request merged**
