### PR TITLE
More than one option is highlighted in soring menu

### LINKED ISSUE #1791: More than one option is highlighted in soring menu.
#### Software and hardware versions 
Collect v1.12.2 and older versions

#### Problem description
More than one option is highlighted in soring menu.

#### Steps to reproduce the problem
It's not possible to reproduce the problem using master branch because the problem is fixed by using different files for the same icons what is wrong.

If you want to reproduce the issue you need to use #1787 

Then:
1. Open the list of forms "Fill Blank Form"
2. Open the sorting menu
3. Change the selected option

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #1791 

#### What has been done to verify that this works as intended?
I tested this pr on a few different devices and everything looks well.

#### Why is this the best possible solution? Were any other approaches considered?
We need to mutate drawables to avoid sharing state.
More info here https://medium.com/@hanru.yeh/tips-for-drawablecompat-settint-under-api-21-1e62a32fc033
#### Are there any risks to merging this code? If so, what are they?
No.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

### CODE REVIEW

**Comment by grzesiek2010** [comment]
@opendatakit-bot label "needs testing"

**Comment by mmarciniak90** [comment]
**Tested with success!**

Verified on Android: 4.2, 4.4, 5.1, 6.0, 7.0, 8.0.
Verified case on all pages from main menu.

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Comment by grzesiek2010** [comment]
@lognaturel can we merge this pr for both #1791 and #1787 ?

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
👍 @shobhitagarwal1612 you'll probably find this interesting.

**Comment by shobhitagarwal1612** [comment]
:sparkles: I didn't knew about `mutate`. Very well!

**Pull request merged**
