### PR TITLE
Replaced == , != with equals()

### PR DESCRIPTION
**Pull request by siavash1986**
== tests for reference equality whereas .equals() tests for value equality. this code may lead to bugs, especially when "new String(" ")" used instead of String literals.
Also <exclude name="UseEqualsToCompareStrings" /> removed by the order of @shobhitagarwal1612 

#### What has been done to verify that this works as intended?
Debugged on the Android Emulator and ran Lint

#### Why is this the best possible solution? Were any other approaches considered?
using == and != for String comparison are discouraged since Java pooling mechanism cannot be predicted 

#### Are there any risks to merging this code? If so, what are they?
Absolutely not

### CODE REVIEW

**Comment by lognaturel** [comment]
Thanks, @siavash1986! It looks like you're committing some additional changes to this branch -- this branch should just be for the == to equals change. 

The check for == to equals is performed by `pmd` and it looks like there are a few more instances that need to be changed. If you run `./gradlew pmd`, it will show you where those are. That's why the build is currently failing. Once those are fixed, it should pass!

**Comment by siavash1986** [comment]
Thanks @lognaturel, I'm fixing this issue

**Comment by siavash1986** [comment]
@lognaturel  I found the glitch! please close this pull request and let me open a new one. sorry for the inconvenience.

**Comment by lognaturel** [comment]
You can close your own! There should be a button at the bottom. 

You can also make changes to this branch and force push them. You may want to read a little about git from https://git-scm.com, it takes some getting used to!

**Pull request closed without merging**
