### PR TITLE
Fixed Failed to find configured root that contains on huawei devices

### LINKED ISSUE #3887: Failed to find configured root that contains /storage/emulated/0/Android/data/org.odk.collect.android/files/settings/collect-settings.png
#### Software and hardware versions 
Collect v1.27.0

#### Problem description
https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/d9c8a9db66823efa64a701b76295e1e3?time=last-seven-days&sessionId=5ED1DA00035000013E521B1B631AD624_DNE_0_v2

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.odk.collect.android/org.odk.collect.android.preferences.qr.QRCodeTabsActivity}: java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/emulated/0/Android/data/org.odk.collect.android/files/settings/collect-settings.png
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2969)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3047)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1777)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:6861)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:450)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #3887 

#### What has been done to verify that this works as intended?
Not much because I 'm not able to reproduce the issue. I just confirmed there is no regression on devices I have.

#### Why is this the best possible solution? Were any other approaches considered?
It's a bug that occurs on huawei devices. I implemented a fix according to: https://stackoverflow.com/a/41309223/5479029

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
it might be difficult to test becuase we might reproduce the bug only on Huawei devices. If we are not able to reproduce we need just confirm that nothing wrong happens when we click `Configure via QE code` and we can scane/share codes.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by grzesiek2010** [comment]
For reviewers:
as I mentioned I used the fix provided in https://stackoverflow.com/a/41309223/5479029 but I adjusted it a bit using our cache directory instead of `context.getCacheDir()` like in the original solution.
So looks as if I can skip the second part of the solution (updating our provider_paths.xml file) am I right, or maybe I'm missing something about configuring file provider?

**Review by seadowg — APPROVED** [review]
Yuck. Huawei have really not made this pleasant. I'd really like to verify this on a Huawei device before we merge if possible. Do @getodk/testers have any?

**Comment by kkrawczyk123** [comment]
@seadowg jup, I will try it on Huawei Y560-L01.

**Comment by grzesiek2010** [comment]
> I will try it on Huawei Y560-L01.

If you had been able to report this issue https://github.com/getodk/collect/issues/3826 that means the crash doesn't occur because it would happen earlier when you click `Configure via QR code`. 

I'll ask on slack or maybe even on the forum. Maybe someone will help us.

**Comment by grzesiek2010** [comment]
@lognaturel @seadowg 
I'm back to this issue because there is one thing I'm thinking about...
the code that causes crashes on some Huawei devices (`FileProvider.getUriForFile()`) is used in a few different places in our codebase:
- taking photos
- playing videos
- opening files via the file widget

but I can't see reports about crashes in these functionalities. However I would go ahead and use this fix in all of the places just in case. What do you think?

**[Edit] ahh ok I can't see reports because we catch `IllegalArgumentException` in most of those places which extends `RuntimeException` thrown by Huawei devices. Ok so I think we should handle all the other places as well.**

**Comment by grzesiek2010** [comment]
Ok I added changes to handle all cases. If you are strongly against we can get rid of it but I'm pretty sure it's a good solution.

**Comment by seadowg** [comment]
@grzesiek2010 makes sense to me. I think keeping the error handling inside the abstraction is the right thing to do here. In #3886 I converted `FileProvider` to an interface (I can deal with the conflict there) so we could even call out in the implementing class that this deals with Huawei problems (`HuaweaiSafeContentURProvider` example).

**Comment by mmarciniak90** [comment]
**Tested with success**

Verified on devices:
* Sony Xperia Z3 D6603 - Android 6.0.1
* Samsung Galaxy S7 SM-G930F - Android 7.0.0
* LG Nexus 5X - Android 8.1
* Xiaomi Redmi 7 - Android 9.0

Verified cases:
* confirm that nothing wrong happens when I click `Configure via QR code` 
* scan code
* share code
* QR code with admin password
* QR code functionality from Admin Settings

**Comment by mmarciniak90** [comment]
@getodk-bot@getodk-bot

**Comment by mmarciniak90** [comment]
@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"

**Pull request merged**
