### PR TITLE
Changed Layout Bottom Padding to use the space on screen.

### LINKED ISSUE #1615: Unused space is visible under buttons in GeoPoint question
#### Software and hardware versions 
Collect v1.11.1

#### Steps to reproduce the problem
1. User uses device in horizontal position 
2. User opens GeoPoint question with maps appearance
3. User sees option buttons on the right side
4. Unused space is visible under buttons
screenshot_2017-11-08-15-30-58

#### Expected behavior
* Whole right area should be used to display buttons

#### Notes
Problem is visible only on GeoPoint question

### PR DESCRIPTION
**Pull request by akshay-ap**
Closes #1615 

#### What has been done to verify that this works as intended?
Tested on Moto M
#### Why is this the best possible solution? Were any other approaches considered?
The easiest way was to reduce the bottom Padding so that space can be used in horizontal orientation.

#### Are there any risks to merging this code? If so, what are they?
No.
#### Do we need any specific form for testing your changes? If so, please attach one.
No.

### CODE REVIEW

**Comment by grzesiek2010** [comment]
@opendatakit-bot label "needs testing"

**Comment by grzesiek2010** [comment]
@opendatakit-bot unlabel "needs review"

**Comment by mmarciniak90** [comment]
Tested with success.
I verified fix on Android 4.1, 4.2, 4.4, 5.1, 6.0, 7.0, 8.0
screenshot_2017-11-13-09-05-06

**Comment by mmarciniak90** [comment]
@opendatakit-bot unlabel "needs testing"

**Review by lognaturel — APPROVED** [review]

**Pull request merged**
