### PR TITLE
Import offline layers into projects and globally

### LINKED ISSUE #5845: Convert reference layer selection to bottom sheet in select one from map
## Acceptance

- [x] Given I'm filling out a form with a select one from map question
And I've copied reference layers to both the global and the current project's directory
And no layer has been selected before
When I open the select one from map view
And I press the layers button
Then I see a list of the available layers as bottom sheet
And "None" is selected

- [x] Given I'm filling out a form with a select one from map question
And I've copied reference layers to both the global and the current project's directory
And I've selected one of those layers in settings
When I open the select one from map view
And I press the layers button
Then I see a list of the available layers as bottom sheet
And the expected layer is selected

- [x] Given I'm filling out a form with a select one from map question
And I've copied reference layers to both the global and the current project's directory
When I open the select one from map view
And I press the layers button
And I swipe the bottom sheet up above the middle of the screen
Then the bottom sheet should fill the screen

- [x] Given I'm filling out a form with a select one from map question
And I've copied reference layers to both the global and the current project's directory
When I open the select one from map view
And I press the layers button
And I press back
Then I should return the map

- [x] Given I'm filling out a form with a select one from map question
And I've copied reference layers to both the global and the current project's directory
When I open the select one from map view
And I press the layers button
And I select a layer
And I click "Save"
Then I am returned to the map with that layer being used

- [x] Given I'm filling out a form with a select one from map question
And I've copied reference layers to both the global and the current project's directory
When I open the select one from map view
And I press the layers button
And I select a layer
And I click "Cancel"
Then I am returned to the map with whatever was being used before as the reference layer

## Notes

- Figma link: https://www.figma.com/file/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows.
- In the current/old UI, the list of layers are loaded on the UI thread (straight from `DirectoryReferenceLayerRepository`). Given this involves scanning the file system, this should definitely be happening in a background thread (probably using `Scheduler#immediate`) and the bottom sheet should display a centred (in the bottom sheet) [circular progress indicator](https://m3.material.io/components/progress-indicators/overview) while they're loading.
- The implementation of the bottom sheet itself will probably be similar to the summary sheet in `SelectionMapFragment` although it might need to be a `Fragment` itself so that it's more reusable (as it will eventually be used in other places).

### PR DESCRIPTION
**Pull request by konishon**
Draft PR that Closes #5845 

#### Why is this the best possible solution? Were any other approaches considered?
This issue has been primarily discussed on https://forum.getodk.org/t/provide-a-way-to-get-mbtiles-to-collect-without-having-to-connect-to-a-computer/42206 and

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Users 

#### Do we need any specific form for testing your changes? If so, please attach one.
Tested using "Select a point" question on  "Collect v2022.2 Select one from map" question 

#### Before submitting this PR, please make sure you have:
- [ ] added or modified tests for any new or changed behavior
- [ ] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [ ] added a comment above any new strings describing it for translators
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by konishon** [comment]
Here's a demo of 
1. MBtile import into the project
2. Mbtile delete from project
3. Mbtile added on the map

https://github.com/getodk/collect/assets/11831955/fc089a06-08cc-45b7-bfed-d005f77cc003

**Comment by seadowg** [comment]
Thanks @konishon! I'm still catching up on this after my Christmas break so might be a little more delayed than usual getting to this.

**Comment by seadowg** [comment]
@konishon it looks like the checks are failing. Are you able to fix those before we dive into a review?

**Review by seadowg — CHANGES_REQUESTED** [review]
https://github.com/getodk/collect/pull/5917#issuecomment-1895637334

**Comment by seadowg** [comment]
Looking at the failure logs, it looks like the PMD checks are failing. This can be run locally with `./gradlew pmd`. You can also run all style checks with `./gradlew checkCode`.

**Comment by seadowg** [comment]
Closing this as it's been inactive for a while. Someone else will likely take on #5845.

**Pull request closed without merging**
