### PR TITLE
Added support for RTL languages in Select One Widgets

### LINKED ISSUE #1849: Selection with autoadvance isn't displayed properly for right-to-left languages
As reported at https://forum.opendatakit.org/t/odk-collect-autoadvance-gui-fix/11745

> With right to left alphabets the autoadvance symbol covers the first three letters of each word.

### PR DESCRIPTION
**Pull request by vrjgamer**
Closes #1849 

+Updated All Select One Widgets for RTL languages.

#### What has been done to verify that this works as intended?
I checked it on a physical device Moto G4+ running Android 7.1, on Nexus emulator running 5.0 & 4.3.
The Widgets were perfectly adapting to the selected Language direction (RTL & LTR). 

**Output**
xcfhvbjh

#### Why is this the best possible solution? Were any other approaches considered?
This is the best solution because it supports all the targeted api levels (16 to 26). There other methods like using TextAlignment or LayoutDirection but they need min. api level of 17.

#### Are there any risks to merging this code? If so, what are they?
No there no risk in merging my code. 

#### Do we need any specific form for testing your changes? If so, please attach one.
Any form that contains Select one widget of any type, especially the one that this issue targets, Select one widget auto-advance. Then select any language either RTL or LTR, from `General Setting -> User Interface -> Language`. Test if the widgets adapt themselves to the language direction.

### CODE REVIEW

**Comment by vrjgamer** [comment]
@lognaturel @grzesiek2010 @shobhitagarwal1612 
CircleCI is giving me an error-> ` 'Do not use Windows line endings' ` for each and every line in all the files. 
How do i fix this issue 😅 ?

**Comment by lognaturel** [comment]
Run `./gradlew checkstyle` to see the checkstyle report and see that you need a newline before a method.

The `.gitattributes` file should be taking care of Windows line endings for you. If not, you can also try the [global setting](https://help.github.com/articles/dealing-with-line-endings/#global-settings-for-line-endings).

**Comment by vrjgamer** [comment]
@lognaturel 
I tried the global setting, but I am still getting the same error -> ` 'Do not use Windows line endings' `, I will try to find some solution.

**Comment by lakshyagupta21** [comment]
@vrjgamer I think you need to clone it again because while cloning it automatically adds `Window line endings`, I faced the same problem when I cloned the project on Windows.

Execute `git config --global core.autocrlf true` in Git bash before cloning the project.

If you find another solution let me know.

**Comment by vrjgamer** [comment]
@lakshyagupta21 Thank you :smile:  for the suggestion. I will test it out.

**Comment by vrjgamer** [comment]
@lakshyagupta21 I found this -> https://intellij-support.jetbrains.com/hc/en-us/community/posts/206360359-Convert-existing-file-line-endings-
In this you can directly convert all the line endings directly to LF for unix system.

@lognaturel  can you please retry the build. Its giving me this error
for Download dependencies
```
#!/bin/bash -eo pipefail
./gradlew androidDependencies
/bin/bash: ./gradlew: Permission denied
Exited with code 126
```
its working with local ./gradlew test for both lint and checkstyle

**Comment by vrjgamer** [comment]
@lognaturel Hi, sorry to disturb you so much. I just need help with this error ` /bin/bash: ./gradlew: Permission denied`. 
I found this https://discuss.circleci.com/t/gradlew-permission-denied/15346/2

**Comment by vrjgamer** [comment]
Yes!! finally everything got fixed. :tada:

**Comment by lognaturel** [comment]
Nice, @vrjgamer! The code for handling media is complex and it's looking like there are opportunities to simplify it. That should have been filed as a separate issue, apologies for not leading you down that path earlier.

Could you please issue a new pull request off of a separate branch that only adds `isLanguageRTL` with an attribution link to https://stackoverflow.com/a/23203698/137744 and the check in `SelectOneWidget`? That's what you described at https://github.com/opendatakit/collect/issues/1849#issuecomment-366351013

That would be a great fix to get merged for the upcoming release and then the additional changes can be iterated on for the following release. Please find me in #collect-code if you have any questions about how to achieve this.

**Comment by vrjgamer** [comment]
@lognaturel, can you please elaborate on how can i find you? (slack or odk forum)
A direct link would be very helpful.

**Comment by lognaturel** [comment]
Invite yourself to the Slack at http://slack.opendatakit.org/ and then go to the #collect-code channel.

**Comment by vrjgamer** [comment]
Its failing because this branch also contained the modifications to MediaLayout class, I think it would be better if I push the changes in pr #1895

**Comment by lognaturel** [comment]
This PR should include the modifications to the MediaLayout class so these can be reviewed and merged! You will need to look at the compilation errors and fix them.

**Comment by lognaturel** [comment]
Closing in favor of #1958

**Pull request closed without merging**
