### PR TITLE
Removed the regression test package

### PR DESCRIPTION
**Pull request by grzesiek2010**
#### Why is this the best possible solution? Were any other approaches considered?
The regression package was a set of tests written by the QA team. It's been a while since the QA team added something there and we have decided that it will no longer be their responsibility.
I have reviewed the tests:
- removing duplicated tests
- reworking/moving test that we (developers) might still need
- removing tests that didn't make much sense from my (dev) perspective or were difficult to understand.

The test cases that were covered by the tests I've removed are still performed manually by the QA team during regression testing I belive so it shouldn't be dangerous.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It doesn't require testing.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by seadowg** [comment]
@grzesiek2010 there's some conflicts here now (probably because of #6059 - sorry 😔).

**Review by seadowg — CHANGES_REQUESTED** [review]
https://github.com/getodk/collect/pull/5983#issuecomment-2057135670

**Comment by grzesiek2010** [comment]
> @grzesiek2010 there's some conflicts here now (probably because of https://github.com/getodk/collect/pull/6059 - sorry 😔).

Fixed.

**Comment by seadowg** [comment]
Github doesn't let me track where I am in a review by commit so I'll just track it in this comment. [Latest commit](https://github.com/getodk/collect/pull/5983/commits/74cbd26ed21b34cfd0fe8bfe1c2c2266c80981c7)

**Comment by seadowg** [comment]
I'm frankly finding it hard to find time to fit this in. @grzesiek2010 are you able just pull the commits after 74cbd26ed21b34cfd0fe8bfe1c2c2266c80981c7 onto another branch for the moment? I think this will be much easier to review and merge in chunks rather than all at once and there's no reason we need to make the change in one go.

**Comment by grzesiek2010** [comment]
> I'm frankly finding it hard to find time to fit this in. @grzesiek2010 are you able just pull the commits after https://github.com/getodk/collect/commit/74cbd26ed21b34cfd0fe8bfe1c2c2266c80981c7 onto another branch for the moment? I think this will be much easier to review and merge in chunks rather than all at once and there's no reason we need to make the change in one go.

Let's keep this pr. I will convert it to a draft. There is a new one that contains the commits you have reviewed https://github.com/getodk/collect/pull/6142

**Comment by grzesiek2010** [comment]
I'm closing in favor of https://github.com/getodk/collect/pull/6383

**Pull request closed without merging**
