### PR TITLE
Change "autosend" to "auto send".

### LINKED ISSUE #1132: Consistently use "autosend" or "auto send"
I don't think "autosend" is a word, so we should probably go for "auto send." When it's capitalized, it should be "Auto send."

### PR DESCRIPTION
**Pull request by VisheshVadhera**
Closes #1132 

Except for preferences, changed occurrences of "autosend" to "auto-send".

### CODE REVIEW

**Comment by lognaturel** [comment]
Thanks, @VisheshVadhera! Can you please make sure that only user-facing strings in English are changed? That means other languages should not be modified (see the readme for information on how translations are managed) and that names that are only seen by developers and the compiler should not be changed.

**Comment by VisheshVadhera** [comment]
Alright @lognaturel

**Comment by VisheshVadhera** [comment]
@lognaturel I have made the requested set of changes. Please let me know if they are correct.

**Comment by lognaturel** [comment]
Thank you so much @VisheshVadhera and welcome to the project! Make sure to join the developers at https://slack.opendatakit.org and to introduce yourself to the broader community at https://forum.opendatakit.org/t/introduce-yourself-here/6671

I realized it wasn't always super clear what our capitalization conventions are so I made a couple of quick changes to your branch so we can get the release out. Typically the PR creator would make changes but since this was so small I thought this would be a bit quicker!

**Comment by VisheshVadhera** [comment]
Hi @lognaturel 

Thanks for pushing the commit to my branch. I do agree with you that it was a very small fix and you did the right thing by pushing it directly to my branch. 

I have already joined the slack channel and I look forward to making more contributions to this project especially migrate this project to Butterknife which I feel can certainly make us all a lot more efficient and reduce a lot of boilerplate.

**Comment by lognaturel** [comment]
Looking forward to it! 

Let me respond to your comments on that issue.

**Pull request merged**
