### PR TITLE
Disable audio widget when form has background recording

### LINKED ISSUE #4386: Disable `AudioWidget` when form has background recording

### PR DESCRIPTION
**Pull request by seadowg**
Closes #4386

#### What has been done to verify that this works as intended?

New tests and verified manually

#### Why is this the best possible solution? Were any other approaches considered?

Not a lot here to comment on. Made sense just to tack this on to the existing disabling mechanism.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Should just add the feature.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by grzesiek2010 — APPROVED** [review]

**Comment by mmarciniak90** [comment]
@seadowg Is audio widget disabled permanently when background recording is in form? I cannot add audio to widget even if I disabled background recording.

Screenshot_20210211-100730

**Comment by seadowg** [comment]
@mmarciniak90 yeah that's the intention! We don't expect form designers to place audio widgets in forms with background recording.

**Comment by mmarciniak90** [comment]
**Tested with success**

Verified on Android versions: 7.0, 8.1, 10.0

**Verified cases:**
* audio widget on single view - disabled background recording
* audio widget on `field-list` - disabled background recording
* audio widget on form without background recording
* edit saved form
* minimization
* rotation
* don't keep activity

**Comment by kkrawczyk123** [comment]
Verified also on Androids 5.1, 7.1 and 9.0

@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"

**Pull request merged**
