### PR TITLE
Bump Dexter dependency to 5.0.0

### LINKED ISSUE #2715: Memory leak due to Dexter library
#### Software and hardware versions 
Collect v1.18.0

#### Problem description
The current version of [Dexter](https://github.com/Karumi/Dexter) causes memory leaks

#### Steps to reproduce the problem
1. Enable `leak canary` for debug build by using `Collect` application class instead of `TestCollect` in debug/AndroidManifest.xml
2. Run the app
3. Leak canary detects memory leak in `SplashScreenActivity` caused due to the usage of library `Dexter`

#### Expected behavior
No memory leak should happen

#### Other information 
https://github.com/Karumi/Dexter/releases suggests that version 5.0.0 resolves this problem. So, we should try updating the dependency and verify that it does solve this problem

### PR DESCRIPTION
**Pull request by ggalmazor**
Closes #2715 

#### What has been done to verify that this works as intended?

Here's a capture of LeakCanary before updating Dexter:

collect - dexter 4 x

Here's a capture after updating it:

collect - dexter 5 0

I've tried to do similar runs with the All Widgets form (fill the same fields, use the geo & photo widgets, etc.)

#### Why is this the best possible solution? Were any other approaches considered?
This is a straightforward change to update a dependency.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Users should not expect any visible change, other than stability improvements (I guess).

#### Do we need any specific form for testing your changes? If so, please attach one.
Nope.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by ggalmazor** [comment]
@shobhitagarwal1612, could you say if the procedure I've followed is correct?

**Comment by shobhitagarwal1612** [comment]
Yes, that's what I would also do. 

It appears from the second attached screenshot that leak canary was able to detect another leak. Can you please verify that detected leak isn't caused by the Dexter library? You can do that by clicking on that.

**Comment by ggalmazor** [comment]
@shobhitagarwal1612, maybe you can help me interpret what I see :)

screenshot_1541777111

**Comment by ggalmazor** [comment]
Could it be that there's a `TimerTask` keeping a reference to a `GeoPointActivity` reference?

There's one being created at `GeoPointActivity.onResume()` 

In any case, it doesn't look like Dexter is involved, right?

**Comment by shobhitagarwal1612** [comment]
Yes, you're right. Thanks for working on this

**Review by shobhitagarwal1612 — APPROVED** [review]

**Comment by yanokwa** [comment]
@shobhitagarwal1612 You added the needs testing label, but then merged the PR. Is this something that needs to go through QA?

**Comment by shobhitagarwal1612** [comment]
The change was small and even the release notes of Dexter library suggested that they haven't modified any other behaviour. I verified the PR myself but thought it would be even better if this is verified by the QAs as well. I've always been amazed by their results. The reason I merged this was because this change was necessary for the unit tests PR I submitted and it was also causing build failures for other's PRs

**Comment by yanokwa** [comment]
Can you help guide the testing? What exactly should QA verify hasn’t been broken?

**Comment by shobhitagarwal1612** [comment]
@yanokwa Sure

Things to verify:
 - Permission dialogs appear when the permission is not granted
 - No crash whenever trying to grant/deny permission in the permission dialog

**Comment by kkrawczyk123** [comment]
Verified those cases on Androids 6.0, 7.0 and 8.1.

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Pull request merged**
