### PR TITLE
Some devices show photos show up sideways

### LINKED ISSUE #36: Galaxy Tab photos show up sideways if not taken in a landscape orientation
<a href="https://github.com/mitchellsundt"></img></a> **Issue by [mitchellsundt](https://github.com/mitchellsundt)**
_Thursday Jul 09, 2015 at 17:37 GMT_
_Originally opened as https://github.com/opendatakit/opendatakit/issues/183 (2 comment(s))_

---

Originally reported on Google Code with ID 182

```
Photos can't be rotated, so when you take a picture it comes in as 
landscape regardless of the orientation you took the picture, so upon 
importing into fusion forms the default info windows sometimes show 
sideways photos. I've trained myself to not take portrait shots 
anymore. Even though portrait is much better for snapping shots of 
trees. 

Galaxy Tab OS 2.2
```

Reported by `parkstrial` on 2011-01-27 15:33:39

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #36 

#### What has been done to verify that this works as intended?
I've tested devices we have. 
Affected like Samsung galaxy s4 and not affected like Infinix Race Bolt.

#### Why is this the best possible solution? Were any other approaches considered?
Looks like it's the only solution.

#### Are there any risks to merging this code? If so, what are they?
I wasn't able to notice such cases but:
-it might work slowly if we rotate and scale down an image
-or maybe it might even throw some exception (OutOfMemoryException for example).

and I refactored the code so we need to confirm scaling down works as before too.

#### Do we need any specific form for testing your changes? If so, please attach one.
We can us AllWidgets form.

### CODE REVIEW

**Comment by grzesiek2010** [comment]
@lognaturel I've added an automated test to cover all cases I can imagine.

**Comment by mmarciniak90** [comment]
I noticed that horizontal selfie in selfie widget displays upside down on some devices.

**Comment by grzesiek2010** [comment]
> I noticed that horizontal selfie in selfie widget displays upside down on some devices.

Please test again.

**Comment by mmarciniak90** [comment]
Marked cases need to be fixed.

| case/device  | Samsung S7 | Huawei | Sony z3 | Samsung J1 | Infinix | 
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| image widget, front camera, vertical | vertical | vertical | vertical | vertical | vertical |
| image widget, front camera, horizontal | horizontal | horizontal | horizontal | horizontal | horizontal |
| selfie widget, front camera, vertical | vertical | vertical | vertical | **horizontal** | **horizontal** |
| selfie widget, front camera, horizontal | ~~crash~~ EDIT: after #1541 **upside down** | **upside down** | **upside down** | horizontal | horizontal |

**Comment by grzesiek2010** [comment]
It's related to the SelfieWidget. I'll take a look at it.

**Comment by lognaturel** [comment]
@grzesiek2010 Sounds like the selfie widget issues should be filed separately, right?

**Comment by grzesiek2010** [comment]
@lognaturel no it should be the same. It uses the same method to rotate image but looks like this case is a bit more tricky.

I'll debug it on Monday.

**Comment by grzesiek2010** [comment]
This is related to the SelfieWidget and the problem is there. I would merge this pr and then work on the SlefieWidget.

Issues reported:
https://github.com/opendatakit/collect/issues/1552
https://github.com/opendatakit/collect/issues/1551

**Comment by mmarciniak90** [comment]
Tested with success other cases, especially cases with use a back camera. 
Everything work as expected.
Verified on Android 4.1, 4.2, 4.4, 5.1, 6.0, 7.0.

@opendatakit-bot unlabel "needs testing"

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
Awesome! I had the rotation issue on my Galaxy Tab but it seemed there was always something more urgent. It's great to see it fixed!

**Pull request merged**
