### PR TITLE
Disable reset button if nothing selected

### LINKED ISSUE #1836: Reset button in admin settings is enabled even if nothing is selected
#### Software and hardware versions 
Collect v1.12.2

#### Problem description
Reset button in admin settings is enabled even if nothing is selected

#### Steps to reproduce the problem
1. Go to `Admin Settings` -> `Reset application...`
2. Reset button is always available

#### Expected behavior
Reset button should be enabled only if something is selected.

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #1836

#### What has been done to verify that this works as intended?
I tested the new behavior of the mentioned button.

#### Why is this the best possible solution? Were any other approaches considered?
it's just an improvement.

#### Are there any risks to merging this code? If so, what are they?
No.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

### CODE REVIEW

**Review by yanokwa — CHANGES_REQUESTED** [review]
I like the idea of preventing the user from hitting a button that doesn't do anything. And it reduces a string which is always nice.

The functionality works, but the reset button looks the same as it did (it looks like the cancel button). I think that's confusing because to the user, it's not obvious the button is disabled. Is that standard Android behavior these days?

**Comment by grzesiek2010** [comment]
On my device, it's disabled and greyed out so maybe it depend's on Android version. I'll check it on other devices.

**Comment by yanokwa** [comment]
Moto G5
device-2018-02-09-123814

Galaxy Tab
screen shot 2018-02-09 at 12 25 06

OneTouch
screen shot 2018-02-09 at 12 21 24

**Comment by yanokwa** [comment]
The behavior on the Moto is really strange. You hit the button and nothing happens and it looks like a bug. And the bad thing is that we can't know what other devices will have this problem. 

I think the options are:
1. If you happen to press Reset and the button is disabled, then we show the toast that you haven't selected anything.
2. Do some research to see where the bug is and try to fix it. Maybe add try to force a 50% lightening.
3. Reject this PR and then the behavior is consistent across devices.

What do you think @shobhitagarwal1612 @lognaturel

**Comment by grzesiek2010** [comment]
@yanokwa I agree my preferable order is 2,1,3 :) I'll check it.

**Comment by grzesiek2010** [comment]
@yanokwa I fixed the issue implementing that method: https://github.com/opendatakit/collect/pull/1837/files#diff-8be972fa817297fe2db3c718c69da61bR234 I think it's the best solution since the issue is related to Android versions.

**Review by yanokwa — APPROVED** [review]

**Comment by yanokwa** [comment]
This is looking good to me, @grzesiek2010. Nicely done! I think we now want to test on a few devices and see if it looks reasonable to @mmarciniak90.

**Comment by mmarciniak90** [comment]
**Tested with success!**
Verified on Android: 4.1, 4.2, 4.4, 5.1, 6.0, 7.0, 8.0
Reset button is disabled when nothing is selected.

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Review by lognaturel — APPROVED** [review]

**Pull request merged**
