### PR TITLE
Simplify MediaLoadingTask, possibly address null activity crash

### LINKED ISSUE #4458: Crash when using Timestamp Camera Free
#### Software and hardware versions 
Collect v1.30.1. User's workflow was working on v1.29.5.

#### Problem description
We have reports from a user that he and his team are experiencing crashes when trying to add pictures (see [review](https://play.google.com/console/u/0/developers/6923365842552008664/app/4974849288395221404/user-feedback/review-details?reviewId=gp%3AAOqpTOEjlIqlPApaecz4t-L5MYG_gI4Czadf2bLPZl6VD1ls3QmJvFvlkbIaZvA4OMWCv-t_Xz142zucaiPflnM&corpus=PUBLIC_REVIEWS)). He says they  use [Timestamp Camera Free](https://play.google.com/store/apps/details?id=com.jeyluta.timestampcamerafree&hl=en_US&gl=US). I've tried using it as my default app with Moto G5, Android 7.1 and that works. I've tried attaching pictures from it with Pixel 3A, Android 11 and that also works.

I've asked for more details on workflow. I think the crash is [this one on Crashlytics](https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/3ddd52fccd131dbe93e954f40687da19?time=last-seven-days&versions=v1.30.1%20(4094)&sessionEventKey=603E97C6006B0001177FA127E295BD67_1513593247377389545):

```
Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference
org.odk.collect.android.tasks.MediaLoadingTask.doInBackground (MediaLoadingTask.java:48)
org.odk.collect.android.tasks.MediaLoadingTask.doInBackground (MediaLoadingTask.java:21)
android.os.AsyncTask$3.call (AsyncTask.java:394)
java.lang.Thread.run (Thread.java:923)
```

It almost looks like Collect is going out of memory but that seems really strange to happen consistently and on multiple devices.

#### Steps to reproduce the problem
Unknown.

#### Expected behavior
No crash.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #4458

#### What has been done to verify that this works as intended?
I reviewed implemented changes and ran tests.

#### Why is this the best possible solution? Were any other approaches considered?
We can't reproduce the issue so this pr just contains some code improvements that maybe help.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It doesn't require testing.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by lognaturel — CHANGES_REQUESTED** [review]
Could you please remove the `FormEntryActivity` field in the `MediaLoadingFragment` and use `getActivity()` instead? This would be a cleaner approach to this change and should also address any possible problem related to the activity being recreated (even though we agree that doesn't seem to be the problem). I think it's a good opportunity to do a quick cleanup and remove `MediaLoadingTask.onDetach` and anything else that might seem unecessary.

**Comment by grzesiek2010** [comment]
@lognaturel 
Ok it should be done.

**Review by lognaturel — APPROVED** [review]
This looks good to me. I think we merge without QA and don't take any further action for now?

I've renamed the PR to reflect that we don't really expect this is a fix. Have you had a chance to run connected tests just in case?

**Comment by grzesiek2010** [comment]
> I think we merge without QA and don't take any further action for now?

Yeah, I think so.

> Have you had a chance to run connected tests just in case?

yes I did it.

**Pull request merged**
