### PR TITLE
RetrieveDriveFileContentsAsyncTask alert dialog no longer crashes

### LINKED ISSUE #2268: Google auth exception can attempt to show after GoogleDriveActivity is destroyed
#### Software and hardware versions 
Collect v1.13+, all Android versions

#### Problem description
Stack trace from Play Store ([link](https://play.google.com/apps/publish/?account=6923365842552008664#AndroidMetricsErrorsPlace:p=org.odk.collect.android&appVersion=2834&clusterName=apps/org.odk.collect.android/clusters/180a408f&detailsSpan=7) requires credentials):
```
android.view.WindowManager$BadTokenException: 
  at android.view.ViewRootImpl.setView (ViewRootImpl.java:796)
  at android.view.WindowManagerGlobal.addView (WindowManagerGlobal.java:351)
  at android.view.WindowManagerImpl.addView (WindowManagerImpl.java:93)
  at android.app.Dialog.show (Dialog.java:322)
  at org.odk.collect.android.activities.GoogleDriveActivity.createAlertDialog (GoogleDriveActivity.java:415)
  at org.odk.collect.android.activities.GoogleDriveActivity.access$600 (GoogleDriveActivity.java:71)
  at org.odk.collect.android.activities.GoogleDriveActivity$RetrieveDriveFileContentsAsyncTask$1.run (GoogleDriveActivity.java:660)
  at android.os.Handler.handleCallback (Handler.java:836)
  at android.os.Handler.dispatchMessage (Handler.java:103)
  at android.os.Looper.loop (Looper.java:203)
  at android.app.ActivityThread.main (ActivityThread.java:6251)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1075)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:936)
```
It looks like `RetrieveDriveFileContentsAsyncTask` can try to display an alert dialog even when `GoogleDriveActivity` has completed

#### Expected behavior
No crash.

#### Other information 
Verifying if the activity is finishing as described [here](https://stackoverflow.com/a/31986885/137744) should address the crash.

### PR DESCRIPTION
**Pull request by jd-alexander**
Closes #2268

#### What has been done to verify that this works as intended?
WIP

#### Why is this the best possible solution? Were any other approaches considered?
This is the best solution because the activity and dialog is checked before attempting to attach it to the window. 

#### Are there any risks to merging this code? If so, what are they?
No.

#### Do we need any specific form for testing your changes? If so, please attach one.
No. 
#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew pmd checkstyle lint findbugs` and confirmed all checks still pass.
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by grzesiek2010 — APPROVED** [review]

**Comment by jd-alexander** [comment]
@mmarciniak90 I think for this we are gonna have to just do regression testing because it's really hard to reproduce.
@opendatakit-bot label "needs testing"

**Comment by jd-alexander** [comment]
I hope this gets merged in soon. Just saw another [dialog related crash(firebase console)](https://console.firebase.google.com/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/5b32adad6007d59fcdeb58e9?time=last-seven-days&sessionId=5B32A9FA02AA00011000DCBAECE4D4D6_DNE_0_v2). The safe `show` and `dismiss` methods added in this PR can be used on all dialogs in the app to prevent these crashes.

**Comment by mmarciniak90** [comment]
@jd-alexander I noticed regression:
1. User uses Google Drive as a server
2. User goes to `Get Blank Form`
3. User selects form and downloads
4. User **does not see** dialog:


I will continue testing.

**Comment by jd-alexander** [comment]
@mmarciniak90 okay I am gonna have to give it a test. So on the branch without this change the dialog pops up?

**Comment by mmarciniak90** [comment]
@jd-alexander, yes, the dialog pops up. When the user clicks on `OK` button, he is moved to the main view.

**Comment by jd-alexander** [comment]
What is the expected behavior?

**Comment by mmarciniak90** [comment]
The expected behavior:
* the dialog pops up
* when the user clicks on OK button, he is moved to the main view.

@jd-alexander, you can always compare with the released version.

**Comment by jd-alexander** [comment]
Okay I haven’t tested as yet. Will do so in the morning.  It’s currently night time in Jamaica :)

**Comment by jd-alexander** [comment]
This is ready now! A simple condition check had thrown it off.

**Comment by kkrawczyk123** [comment]
The only regression that I have noticed is that when a user doesn't have API configuration and he tries to Get Blank Form from Google Drive there is no information displayed what he should do to use it, screenshot attached:
screenshot_2018-07-09-09-44-54
No information can be confusing for the user. 

The result from the master:
screenshot_2018-07-09-10-46-11

cc @jd-alexander @lognaturel 
@opendatakit-bot unlabel "needs testing"

**Comment by jd-alexander** [comment]
Okay, checking this out. Not sure why that would be happening because the changes made shouldn't have any impact on that dialog. Gonna take a look now.

**Comment by jd-alexander** [comment]
Just tried to reproduce and couldn't. Dialog is shown when Google Sheet returns an error.

**Comment by lognaturel** [comment]
To confirm, @jd-alexander, you tried with a Google account that does NOT have the gdrive API authorization and you saw the "Unable to make API call" dialog? All the gdrive accounts I have have the auth so I can't easily verify this!

**Comment by jd-alexander** [comment]
Yes, that's exactly what I tried. I displayed the apis in my Google console and this is the result that was shown. 

device-2018-07-09-185047

**Comment by lognaturel** [comment]
🤔 @kkrawczyk123 Could you please try again on another device with this PR first and then on master? I agree with @jd-alexander that the PR should not affect that particular error state unless a dialog were already showing or the activity was finishing or something like that.

**Comment by kkrawczyk123** [comment]
I removed API configuration and I checked again on 3 different devices and I can't reproduce it too, that's weird but everything seems to work just fine. 

@opendatakit-bot label "behavior verified"

**Review by lognaturel — APPROVED** [review]

**Pull request merged**
