### PR TITLE
Replaces HardCopying of arrays with System.arraycopy() 

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
`System.arraycopy()` uses JNI (Java Native Interface) to copy an array (or parts of it), so it is blazingly fast (for more info read [here](http://www.javaspecialists.co.za/archive/Issue124.html))

Also, the conversion of primitive array to object array and vice versa has been replaced with methods of `ArrayUtils` utility class from `commons-lang3` package

#### What has been done to verify that this works as intended?
This is just refactoring and does not modify the behavior in any possible way. 

#### Why is this the best possible solution? Were any other approaches considered?
Replaces the code with the standard library method calls

#### Are there any risks to merging this code? If so, what are they?
No

#### Do we need any specific form for testing your changes? If so, please attach one.
No

### CODE REVIEW

**Comment by lognaturel** [comment]
The kinds of risks here are bounds issues and adding a new dependency. I'm not familiar with `commons-lang3`, how much does it add to the binary size?

Since the arrays in question are quite small, it's not clear to me that it's worth sacrificing readability and simplicity! What do you think @shobhitagarwal1612? I imagine these changes were directly suggested by `pmd`, right?

**Comment by shobhitagarwal1612** [comment]
@lognaturel PMD suggests to use `System.arraycopy()` instead of manually copying one array to another. So, it got triggered where primitive type array is being converted to object type array. But `System.arraycopy()` 
 cannot be used in such cases as it does not handle incompatible types (eg. copying `long[]` to `Long[]`).  

> I imagine these changes were directly suggested by pmd, right?

PMD did not suggest to use `commons-lang3` package. `commons-lang3` has a lot more to offer. [official documentation](https://commons.apache.org/proper/commons-lang/) 
Read this article too, https://eclipsesource.com/blogs/2013/11/06/get-rid-of-your-stringutils/

Another reason why I considered using this library was to clean up the code.

> how much does it add to the binary size?

image

**Comment by lognaturel** [comment]
Using `System.arraycopy()` is great. If I'm understanding correctly, adding the dependency adds almost half a megabyte to the binary size. That would only be acceptable if it meant deep improvements to user experience which it doesn't sound like it will. 

Can some of the code leading to the copy be modified so values are boxed/unboxed earlier? In other words, if the ultimate goal is to have a `Long[]`, can values be turned into `Long`s before they are now? If that's not practical, I think ignoring the `pmd` warnings is appropriate for small arrays.

**Comment by shobhitagarwal1612** [comment]
@lognaturel Please review. I have removed the added dependency and created a utility class to handle the conversion between the `long[]` and `Long[]` types. In the same utility class, I have suppressed the warnings

**Review by lognaturel — APPROVED** [review]
Thank you! It's a lot to think about, right?

**Comment by shobhitagarwal1612** [comment]
I thought that the 500kb increase was showing as the APK analysed was of debug build. For release build, proguard removes all the unused classes from the library, hence the change would have been not much in that case. But you have a point too. Adding another dependency where it can be avoided is not the ideal approach
Thanks for your thoughts :)

**Pull request merged**
