### PR TITLE
Determine text direction based on used characters

### LINKED ISSUE #2330: When form language is RTL but Collect language is LTR, form text is not shown RTL
#### Software and hardware versions 
Collect v1.15.0+

#### Problem description
https://forum.opendatakit.org/t/odk-collect-1-15-1-right-align-issue/13754

#### Steps to reproduce the problem
1. Add a form that has label or hint in a RTL language like Arabic or Urdu (e.g. https://data2.unhcr.org/en/documents/details/52583 -> [arabic.xml.txt](https://github.com/opendatakit/collect/files/2142489/arabic.xml.txt))

1. Open the form

#### Expected behavior
Text should appear RTL. See v1.14.0 for desired behavior.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #2330 

#### What has been done to verify that this works as intended?
I tested changing languages using languages like: English, Polish, Arabic

#### Why is this the best possible solution? Were any other approaches considered?
A user reported it's a regression and It worked before v1.15.0. In fact, it worked just for TextViews not because we handled that case but because of the fact that Android recognizes chars and if is a text in RTL, it's displayed on the right side, if LTR on the left of course.
But then we added https://github.com/opendatakit/collect/commit/a5081c1c1821f3063e03e12e2c65f56a61384a57 and it stopped works.

My first idea was to handle everything programmatically but I realized it's a crazy idea and we wouldn't be able to move some code responsible for building layouts to xml https://github.com/opendatakit/collect/pull/2323

Then I realized that in the doc http://xlsform.org/en/ the format for languages is: langaugeName + locale eg. `English (en)`. So we can use that locale to update the entire layout after changing the language.
That what I did. So now if we have a language `Arabic (ar)` the layout is updated to RTL. if someone uses a bad format for example without locale code its treated as LTR by default.

Of course, those changes don't affect the entire app and once we leave form view it returns to an original language.

#### Are there any risks to merging this code? If so, what are they?
I can't see any risk here.

#### Do we need any specific form for testing your changes? If so, please attach one.
Any form with different languages.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew pmd checkstyle lintDebug spotbugsDebug` and confirmed all checks still pass.
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by lognaturel** [comment]
Thanks for this, @grzesiek2010, it's an interesting approach! Asking for feedback at https://forum.opendatakit.org/t/odk-collect-1-15-1-right-align-issue/13754/9. The language code requirement is a new one and not enforced (though pyxform does now issue a warning) so my guess is that it's not included in most forms.

As an alternative (or perhaps additionally?), how about overriding the theme direction for the `TextViews` used for label and hint? I think setting it to `firstStrong` (https://developer.android.com/reference/android/view/View.html#attr_android:textDirection) would have the desired effect.

**Comment by grzesiek2010** [comment]
@lognaturel 
I followed your advice and added it but as an additional option so now if you have a language called Arabic and use Arabic chars TextViews will be displayed on the right side (the second commit) but if you have also specified locale eg. Arabic (ar) then the entire view has RTL direction (the first commit).

I think it's good, what is your opinion?

**Comment by lognaturel** [comment]
Nice hybrid approach. I agree.

**Comment by kkrawczyk123** [comment]
I have noticed some issues for Arabic (ar) case and Polish (ar) case from which I expected the same behavior.

Firstly I would like to ask what should be considered by "default" language? I thought it would be the language chosen in Settings but it looks like it is not? @lognaturel @grzesiek2010 

**4.1:** Problem with text, number, range, select one and select multi-widgets with Arabic (ar) configuration.
Example screenshot:
screenshot_2018-07-24-15-28-22
screenshot_20180724-143724
And problem with most of widgets with Polish (ar) configuration. 
 
**4.2:** Problem with text question like attached above and select one and select multi.
Example screenshot:
screenshot_20180724-143849
screenshot_20180724-143830
And a problem with mostly question on Polish.

**4.4 and 5.0:** The same issue as above with text question and numeric questions. Arabic (ar) and  Polish (ar) behavior remain the same

**6.0:** The same issues with text question, select one and select multi and the problem with mostly question on Polish (ar)

**8.1:** Issue with text, numeric, range, select one and select multi when Arabic (ar) and a problem with mostly all question on Polish (ar)

@opendatakit-bot unlabel "needs testing"

**Comment by grzesiek2010** [comment]
> Firstly I would like to ask what should be considered by "default" language? I thought it would be the language chosen in Settings but it looks like it is not?

currently, the `default` language is treated like any other without an appropriate language code so for example:
default, Polish, Arabic, Arabic (x) it would be treated as LTR and a direction of TextViews would be determined based on chars.
Thinking about this approach I agree it might be a little bit tricky. let's assume we have a user who uses the Arabic language for the entire app but has forms without any languages (just the default one). Then it might be annoying that everything looks like in LTR. I think we should treat the default language as a global language. Do you agree @lognaturel?

When it comes to the rest of the mentioned bugs I didn't know it depends on Android version and the behavior is so different. I'll take a look at it.

**Comment by lognaturel** [comment]
@kkrawczyk123 To be completely clear, the issue you're seeing is that the `ar` suffix isn't always respected, is that correct? What language did you set Collect/your device to for the test?

When I say "default" language, I mean the default for a form when no language is set. That is, when a user writes an XLSForm with `label` and `hint` that have no `::` language suffix.

> let's assume we have a user who uses the Arabic language for the entire app but has forms without any languages (just the default one)

There are two subcases then, right? One where the labels, hints, etc use a LTR language and one where the labels, hints, etc use a RTL language. It seems good to me that Collect would respect that directionality: 
- I have the app set to Arabic. I have a form with just a default language specified. My labels and hints are in Urdu. Then I expect labels, hints, etc to be shown in RTL because Urdu is RTL. 
- I have the app set to Arabic. I have a form with just a default language specified. My labels and hints are in English. Then I expect labels, hints, etc to be shown in LTR because English is LTR.

I believe that's what happens with this PR.

> I think we should treat the default language as a global language.

I'm afraid I'm not sure what that means! Can you share some specific examples like I did above?

**Comment by grzesiek2010** [comment]
> To be completely clear, the issue you're seeing is that the ar suffix isn't always respected, is that correct? What language did you set Collect/your device to for the test?

The problem @kkrawczyk123 described is that on some device (to be honest on most of our devices) direction of `TextView` elements is determined based on used characters only (not based on form language). So for example, if you use a form with `Arabic (ar)` (RTL) language but with Polish (LTR) chars, a result is:

on most of tested devices:
screenshot_20180727-114239

on other devices:
screenshot_2018-07-27-11-40-26

Direction of `TextViews` is not always respected in the same way like direction of other elements.
Everything is ok if it's an arabic text.

there is no easy way to fix this issue and we would need to do everything programmatically. I'm not even sure if we should treat it as a bug. Since it's rather not a big problem and a rare case I would vote for leaving it as it is.

> There are two subcases then, right? One where the labels, hints, etc use a LTR language and one where the labels, hints, etc use a RTL language. It seems good to me that Collect would respect that directionality:

labels and hits are positioned based on characters and that's ok I'm talking about direction of rest elements, please take a look below:

> I'm afraid I'm not sure what that means! Can you share some specific examples like I did above?

Let's say you are from Saudi Arabia :smile:  your Collect (and probably device) language is Arabic but you didn't explore the doc carefully and languages you use in your forms are `label` or `label::Arabic` not `label::Arabic (ar)`.
So device/Collect language as I said is Arabic - RTL
Form language is default or Arabic - LTR

what is the expected result?

In my opinion it's:
screenshot_20180727-111454

not

screenshot_20180727-111653

That's why I said that if locale is not specyfied we should follow the global language (Collect language) to determine direction of elements.

**Comment by grzesiek2010** [comment]
I hope my explanations are clear and you agree we can add `needs testing` label back.

**Comment by grzesiek2010** [comment]
We used this form for testing: 
[all-widgets.xlsx](https://github.com/opendatakit/collect/files/2235335/all-widgets.xlsx)

**Comment by kkrawczyk123** [comment]
@grzesiek2010 I still can reproduce bugs that I described above. Additionally, I have noticed another problem visible on Androids 4.1, 4.2 and 4.4 when I fill the form in both Arabic (ar) and Polish (ar) and I set in Collect use device language - I can see a language changes in main menu even if Use device language is set, screenshot attached:
screenshot_2018-07-30-13-12-48

@opendatakit-bot unlabel "needs testing"

**Comment by grzesiek2010** [comment]
> @grzesiek2010 I still can reproduce bugs that I described above.

that's ok if you use LTR chars your text is on the left side even if the entire form lanuage is RTL.

but I agree that the solution is buggy or rather android is buggy different behavior on android 4, 5-7, 8

It was a nice hybrid solution but now noticing all those differences I think that maybe it's better just to fix text direction (based on chars - it's the second commit). It would work like before and like our user asked on the forum https://forum.opendatakit.org/t/odk-collect-1-15-1-right-align-issue/13754.

@lognaturel what do you think? Does that make sense to fight with all those bugs/differences between android versions?

**Comment by lognaturel** [comment]
😫 The joy of Android! I’m very happy with just using the direction characters for labels and hints. As you said, it’s the behavior we had before. It was good to try using the language code but not worth investing more in for now, I think.

**Comment by grzesiek2010** [comment]
Ok, so I've just updated the pull request. Now only TextViews:
- Group name
- Question label
- Hint

are supposed to change their direction based on used characters (whether they are LTR or RTL).

I prepared a form for testing with media files in order to confirm that everything works well:
[langs.zip](https://github.com/opendatakit/collect/files/2282502/langs.zip)

**Comment by kkrawczyk123** [comment]
@grzesiek2010, I have noticed one minor issue on Android 4.2. When I set Collect's language as arabic and polish as a language of the form, an audio button is overlapping polish text, screenshot attached:
screenshot_2018-08-13-11-03-21
In the opposite situation, when collect's language is polish and frm language is arabic, everything seems to look just fine:
screenshot_2018-08-13-11-02-36

**Comment by grzesiek2010** [comment]
@kkrawczyk123 
I fixed the issue moving those buttons below the question. I think it's a good solution and it looks nice. Please test and let me know what you think.

**Comment by grzesiek2010** [comment]
> I have noticed one minor issue on Android 4.2

I'm not going to fix this problem now because I'm pretty sure there is something wrong with that device not with all Android 4.2. 
Could you create a separate issue with all those strange things with all those strange things we noticed on that device (I mean layout bugs).

Please finish testing.

**Comment by kkrawczyk123** [comment]
**Finally tested with success!!!!!**
Verified on Androids: 4.1, 4.2, 4.4, 6.0, 7.0 and 8.1.
I reported new issues connected to RTL language as they are also visible on master:
https://github.com/opendatakit/collect/issues/2473
https://github.com/opendatakit/collect/issues/2475
https://github.com/opendatakit/collect/issues/2476

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Review by lognaturel — APPROVED** [review]

**Pull request merged**
