### PR TITLE
Refactored uploadInstancesResultDialog

### PR DESCRIPTION
**Pull request by grzesiek2010**

### CODE REVIEW

**Review by yurilaguta — APPROVED** [review]
Look clear. 
The only thing of a bit of concern is growing SimpleDialog constructor, which might be replaced with cleaner Builder pattern, but that is not part of this refactor.

**Comment by grzesiek2010** [comment]
@Yurii-Laguta haha you don't even know how long conversation we had with @lognaturel and @srsudar about it :) My first solution was based on builder pattern you can look here https://github.com/opendatakit/collect/pull/1259/files there is one of my previous versions of the general approach.

But after really long discussions and a few different prs we decided to keep the current approach. I was rather in favor of builder pattern too but they prefer this one.

**Comment by yurilaguta** [comment]
@grzesiek2010 that is a bit sad, your PR looks like clear and reusable solution. There is no conversation on that PR, was it in Slack? I'm just wondering what was opposing arguments to that.

Since builder pattern wasn't adopted maybe then we should have Factory methods override with default values? so you won't have to modify ResetDialogPreference.java

**Comment by grzesiek2010** [comment]
@Yurii-Laguta you should see that on slack I've just mentioned you in that thread

**Comment by grzesiek2010** [comment]
@Yurii-Laguta but as I remember it's not the only thread, we discussed here on github too.

**Comment by dr0pdb** [comment]
@grzesiek2010 @lognaturel @Yurii-Laguta While trying to review this PR on my local machine, i got the following stack trace 
```
08-23 01:07:49.625 31265-31265/org.odk.collect.android E/UncaughtException: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
                                                                                at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1842)
                                                                                at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1860)
                                                                                at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:650)
                                                                                at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:609)
                                                                                at android.support.v4.app.DialogFragment.show(DialogFragment.java:143)
                                                                                at org.odk.collect.android.activities.InstanceUploaderActivity.createUploadInstancesResultDialog(InstanceUploaderActivity.java:359)
                                                                                at org.odk.collect.android.activities.InstanceUploaderActivity.uploadingComplete(InstanceUploaderActivity.java:254)
                                                                                at org.odk.collect.android.tasks.InstanceUploader.onPostExecute(InstanceUploader.java:53)
                                                                                at org.odk.collect.android.tasks.InstanceUploader.onPostExecute(InstanceUploader.java:42)
                                                                                at android.os.AsyncTask.finish(AsyncTask.java:636)
                                                                                at android.os.AsyncTask.access$500(AsyncTask.java:177)
                                                                                at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:159)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5541)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
```
Steps to reproduce-
1. Finalize few forms.
2. Select multiple instances and click the send selected button
3. Minimize the app
4. Keep a track on debugger to know when all instances have been uploaded
5. After all of the instances have been uploaded, reopen the app

It's hard for me to recognize the actual cause of this error or if we should even be concerned by this or not ,but i think you guys can do some in-depth checking.

**Comment by lognaturel** [comment]
I can repro what @srv-twry describes. It's a hard crash so should be addressed. It doesn't happen in `master`.

**Comment by grzesiek2010** [comment]
@lognaturel @srv-twry I'll investigate it of course. Which android version? I'm sure I tested everything using my 5.0.1

**Comment by lognaturel** [comment]
Thanks, @grzesiek2010! Android 7.0 for me.

**Comment by dr0pdb** [comment]
@grzesiek2010 Android 5.1.1 for me.

**Comment by grzesiek2010** [comment]
@srv-twry good catch thanks. It's fixed.

**Comment by lognaturel** [comment]
Let me make sure I'm understanding correctly here. The fundamental problem is that when `uploadingComplete` is called by the `AsyncTask` and tries to show a dialog, the activity may be paused, right? I believe that was also exactly what caused #1361 that @srv-twry and @shobhitagarwal1612 were looking at, right?

In the latest commit, the `show` method is overridden to avoid and log any crash related to that state. Is this the best possible approach? Is it possible to avoid calling `show` in the first place? I'm really surprised this isn't better handled by Android!

**Comment by yurilaguta** [comment]
This looks like workaround for problem, rather then solution.
Activity lifecycle and asyncTask do not work very well out of the box in Android.
Few options to consider:
1. BaseActivity that keeps boolean of it's state (isResumed) set in onResume and onPause and then in AsyncTaskCallback check before doing anything.
2. nullify instanceServerUploader.setUploaderListener(null) in onPause and set back in onResume

Actually 2nd looks like the clearest approach because it's already set in onResume, maybe someone just forgot to nullify it in onPause?

**Comment by grzesiek2010** [comment]
Yes it's sort of workaround but I know it has been working for a long time in TaroWorks project :) Maybe we can wait for @mmarciniak90 and ask her if she knows any problems related to it.

@Yurii-Laguta if we use `setUploaderListener(null)` in `onPause()` method then https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/tasks/InstanceUploader.java#L47 won't be called at all. I don't think it's a good approach.

I think generally showing dialogs after long tasks is not a good approach maybe we should use notifications in such cases (I'm not sure it's just an idea, have to investigate it)

**[EDIT]** yes this case is described here for example http://www.androiddesignpatterns.com/2013/08/fragment-transaction-commit-state-loss.html
He also says we should avoid `"performing transactions inside asynchronous callback methods"`

**Comment by yurilaguta** [comment]
@grzesiek2010 I see your point, InstanceUploader will stop working if we nullify uploadListener in onPaused. But given that the dialog 'setCancelable(false);' do users expect that upload will continue if they leave application in the middle of it, by pressing the home button?

Feels like checking if activity is paused is the fastest solution here, the cleanest would require huge amount of refactoring, as an option moving InstanceUploader functionality into IntentService, and showing notification in status bar updating user on the progress similar to what Google Photos does when it's uploading pictures into cloud that was recently taken.

**Comment by grzesiek2010** [comment]
> do users expect that upload will continue if they leave application in the middle of it, by pressing the home button?

It's not easy to say what they expect... @lognaturel what is your opinion I think it's ok isn't it?

@Yurii-Laguta about your first idea with keeping a boolean value of an activity state. I'm afraid it might make the code complicated since we probably will need the same in some of other dialogs. What about just changing https://github.com/opendatakit/collect/pull/1275/files#diff-63a0b3e03ec031ef141db8e0d5bb78abR62 to a default `commit()` then we just catch the exception and the result is the same like in your idea - the dialog is not visible.

**Comment by yurilaguta** [comment]
@grzesiek2010 that boolean logic will might have to belong to BaseActivity class.
you can use try catch, but I won't be the one approving such code. Given that we target low end devices, creating fragment passing it to fragmentManager and catch exception because we do it in incorrect activity lifecycle state doesn't resonate with me at all.

**Comment by grzesiek2010** [comment]
@Yurii-Laguta I see your point of view and your concerns. I've implemented changes according to your suggestion and I've added the same check in `ResetDialogPreference` class since we try to show a dialog using the same `SimpleDialog` class there too. 
I'm just wondering about the fact I mentioned above. As you can see we need to add changes to control an activity state in each activity. What about adding one general activity and put those changes there and then each activity could extend that one? It would allow as to control the state only in that one general activity.

**Comment by yurilaguta** [comment]
@grzesiek2010 thanks. Regarding adding activity I believe we must have it, because there are a lot of code that can be shared between different activities through inheritance, and state awareness is one of them. Few other would be analytics (sending screen), toolbar setup etc.

**Comment by grzesiek2010** [comment]
@lognaturel what about this one? It's been a while since I created this pr and I thought everything is agreed. If there is something wrong please let me know or just close this pr.

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
Thank you for the great conversation both here and in #541 @grzesiek2010 and @Yurii-Laguta. 

@jknightco can we please get a last sanity check from you?

**Review by heyjamesknight — APPROVED** [review]
Everything looks great. I usually avoid putting implementation details in names like `Abstract`, `Impl`, `Interface`, etc. but that's my one nitpick 😛

**Pull request merged**
