### PR TITLE
Filtering

### PR DESCRIPTION
**Pull request by grzesiek2010**

### CODE REVIEW

**Comment by yanokwa** [comment]
This is really close, @grzesiek2010! Just one request. When I touch the search button, I should get focus on the text box, the keyboard should pop up, and I should get the blinking cursor.

**Comment by grzesiek2010** [comment]
@yanokwa done.

**Comment by yanokwa** [comment]
@grzesiek2010 If I have filtered view, and I rotate the screen, the view reverts to the non-filtered. Taping on the search box then shows me the text I've entered, but it's not filtered. 

Landscaped filtering also doesn't work. If I type text and hit Next or the blue arrow in the keyboard, it doesn't close and filter as I would expect.

**Comment by grzesiek2010** [comment]
@yanokwa I think it's not a big effort to fix that so I'll try to add a fix tomorrow morning.

**Comment by grzesiek2010** [comment]
@yanokwa I've fixed that bug.

**Comment by lognaturel** [comment]
Nicely done, @grzesiek2010! There were a lot of subtle cases to handle.

**Pull request merged**
