### PR TITLE
converted png to svg assets

### LINKED ISSUE #1549: Drawables can be converted to scalable assets (e.g., PNG to SVG)
#### Problem description
Collect is using .png drawables instead of scalable vector graphics (SVG). These PNG assets can be converted over to SVG to improve the app's UI / UX.

### PR DESCRIPTION
**Pull request by asclepiusgal**
Closes #1549 

#### What has been done to verify that this works as intended?
usages of the PNG assets were assessed to account for any issues with removing duplicate PNG icon types, and the SVG assets were updated to maintain the original color palette

#### Why is this the best possible solution? Were any other approaches considered?
scalable vectors replaced the static sized .png assets, so the UI/UX should be improved

#### Are there any risks to merging this code? If so, what are they?
No

#### Do we need any specific form for testing your changes? If so, please attach one.
No

### CODE REVIEW

**Comment by lognaturel** [comment]
Thank you for doing this, @asclepiusgal! It's a nice improvement.

I noticed that General Settings is now missing most of its icons. It also looks like the "my location" icon for geopoint/geotrace/geoshape is too small. 

The build is failing because of a lint check. You can see the lint results by running `./gradlew lint` locally. The explanation is the following:
> To use VectorDrawableCompat, you need to make two modifications to your project. First, set android.defaultConfig.vectorDrawables.useSupportLibrary = true in your build.gradle file, and second, use app:srcCompat instead of android:src to refer to vector drawables.
More info: http://chris.banes.me/2016/02/25/appcompat-vector/#enabling-the-flag

Please take a look at those and let me know if you have any questions.

**Comment by asclepiusgal** [comment]
Kk, I'll look more into it tomorrow. This was meant to be a straight forward update, but it seems as though some of the UI's may have been  hardcoded with dimensions and the manifest was missing the compatibility code. I guess first PRs with new projects are meant to be a learning curve, but sorry for the inconvenience!

**Comment by lognaturel** [comment]
No problem! It always takes a bit to get oriented within a new project, @asclepiusgal. Let us know if you have any questions.

**Comment by lognaturel** [comment]
Thanks again for looking into this, @asclepiusgal. I'll close the PR for now but please do reopen if you get a chance to resolve the issues above.

**Pull request closed without merging**
