### PR TITLE
Remove Activity Logger

### LINKED ISSUE #1395: Deprecate ActivityLogger
[ActivityLogger](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/database/ActivityLogger.java) was added for logging all user interface activity into a SQLite database. The main purpose of adding this feature was to prevent reduction in quality of data collection due to Interviewer fabrication (for more info, read [this](http://bbirnbaum.com/assets/publications/dissertation.pdf)). But this feature is **deactivated** by default.
Logging is enabled if the file `sdcard/odk/log/enabled` exists. Given the fact that this feature is neither well documented nor is being discussed despite the fact that the data that is being stored is not complete. So it's better we think about deprecating this feature in future releases.

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Closes #1395 

#### What has been done to verify that this works as intended?
Verified that app compiles and runs.

#### Why is this the best possible solution? Were any other approaches considered?
The methods were removed one at a time using search in path tool which helps make it safe.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Previous to this change, including `/sdcard/odk/log/enabled` should result in a database being created and events being logged. After the change, including the file should have no effect. It should be ok for the database to exist already. Regression risks are overall low because of the use of automated tools. All widgets have been modified and one possible area where mistakes could have been made are handling clicks for widgets that pop up dialogs because those handlers were removed (e.g. exit dialog from draw widget).

#### Do we need any specific form for testing your changes? If so, please attach one.
It would be a good idea to go through All Widgets entirely and send a form.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No because the feature was never documented.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by lognaturel** [comment]
Thanks, @shobhitagarwal1612! We will all breathe easier once it's gone.

Once it's ready for review, please provide a quick explanation of how you made the change and verified that it's safe.

**Comment by shobhitagarwal1612** [comment]
The PR is ready for the review.

To ensure that no regressions were introduced, the methods were removed one at a time using `search in path` tool

**Comment by lognaturel** [comment]
👍 I updated the PR description.

**Comment by grzesiek2010** [comment]
> It would be a good idea to go through All Widgets entirely and send a form.

I wonder how testing should look like and whether it's needed at all. If @shobhitagarwal1612 confirmed there is no crash maybe it's enough. We are just after a release so we would have a lot of time just testing it on a daily basis. Or maybe you @lognaturel have any special tips for our QAs?

**Comment by lognaturel** [comment]
I'm ok merging as-is if you're comfortable with that as well, @grzesiek2010 and @mmarciniak90.

My approach to verifying it would be to check the desired behavior and also go through the All Widgets form as described in the PR description:
> Previous to this change, including /sdcard/odk/log/enabled should result in a database being created and events being logged. After the change, including the file should have no effect. It should be ok for the database to exist already. Regression risks are overall low because of the use of automated tools. All widgets have been modified and one possible area where mistakes could have been made are handling clicks for widgets that pop up dialogs because those handlers were removed (e.g. exit dialog from draw widget).

**Review by grzesiek2010 — APPROVED** [review]

**Comment by grzesiek2010** [comment]
Those changes look fine so It's up to you @lognaturel I'm sure @mmarciniak90 will test AllWidgets form 500 times till next release anyway so it's not required to do that for this pr. I think she can just test mentioned dialogs.

> one possible area where mistakes could have been made are handling clicks for widgets that pop up dialogs

Dialogs @shobhitagarwal1612 mentioned:
-Exit dialog in DrawActivity with Save/Ignore changes options
-Change language dialog in FormEntryActivity

**Comment by lognaturel** [comment]
Sounds great to me!

**Comment by kkrawczyk123** [comment]
**Tested with success!**
Verified on Androids: 4.2, 4.4, 6.0, 7.0 and 8.1.

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Pull request merged**
