### PR TITLE
Send raw values to Google Sheets

### LINKED ISSUE #3124: Results from select multiple questions might be converted to dates in Google Sheet
#### Software and hardware versions 
Collect v1.22.0 and older versions

#### Problem description
Results from select multiple questions might be converted to dates in Google Sheet

#### Steps to reproduce the problem
Fill the form: [SampleQuestions.xml.txt](https://github.com/opendatakit/collect/files/3249008/SampleQuestions.xml.txt)
1. In the first question select options: 6, 2, 3
in the second question select options: 11, 7, 3

2. Finalize and send the form.

The result will be:
image

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #3124 

#### What has been done to verify that this works as intended?
I tested sending forms with select-multi questions to GS.

#### Why is this the best possible solution? Were any other approaches considered?
I mentioned other possible solutions in the issue. This is the only good one. It causes that values the user has entered are not parsed more info: https://developers.google.com/sheets/api/reference/rest/v4/ValueInputOption

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Sending forms to GS should be tested here and it would be enough. The change is not risky.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by lognaturel — APPROVED** [review]
I'm glad it's straightforward to get Google Sheets to skip the parsing -- that's definitely the ideal solution.

**Comment by mmarciniak90** [comment]
@grzesiek2010 @lognaturel 
This fix looks good at first glance. 
But I noticed one additional effect which should be known.
Extra sign `'` is added at the beginning of the value. 
It causes that value is not formatted to date format
Screenshot from 2019-06-04 11-12-27

This behavior is visible for a lot of widgets: numbers, strings with a number value, dates, range, accuracy and altitude from the geopoint widget.

I share a google sheet where you can look on it -  [pr/3128](https://docs.google.com/spreadsheets/d/1JBF1wI4MBu3HPIqrAOIksBHeGxy1AMvDkV3kzUIXB5E/edit#gid=1825158448)

I finished `All widgets` form on v1.21.2 and version with the fix

**Comment by grzesiek2010** [comment]
It's the way it works...
but it's visible only in edit mode. You can also perform calculations without any problems, right?

**Comment by mmarciniak90** [comment]
> You can also perform calculations without any problems, right?

That's right

**Comment by mmarciniak90** [comment]
@lognaturel, are we able to accept the mentioned additional effect visible in GS?

**Comment by lognaturel** [comment]
I exported to CSV and XLSX opened in Numbers and everything looks good. I don't have access to Excel and I think that would be a good additional check if someone can quickly verify it. As @grzesiek2010 mentions, it looks like the tick is some kind of Google Sheets convention.

It's a little unfortunate to lose the formatting when it was helpful. It also will be confusing for users who have ongoing data collection campaigns and will see data displayed differently all of a sudden. I verified that users can add formatting as appropriate after the fact so it should be a possible to get everything looking the same pretty easily.

If nothing strange shows up in the Excel export, I think this is ok.

**Comment by mmarciniak90** [comment]
I checked on MS Excel and it looks the same. Extra sign `'` is visible in edit mode. Excel informs that the number value is stored as a text and gives a quick option to convert. But this information does not cause any issue. I was able to perform calculations as well.

**Tested with success.**

Verified on Android: 4.2, 4.4, 5.1, 6.0, 7.0, 8.1

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Pull request merged**
