### PR TITLE
Invalidate Glide disk cache when new images are received

### LINKED ISSUE #6419: Images are cached incorrectly, probably by glide
#### ODK Collect version
https://github.com/getodk/collect/commit/66e9c1f10f707b803654bc57f7930b805edf2742 but I believe this affects all recent versions

#### Android version
5.1

#### Device used
Moto G5

#### Problem description
When media is updated for a Central draft, that update is not reflected on Collect.

#### Steps to reproduce the problem
1. Start a Central draft for a form with attached media such as All Widgets.
2. scan in the draft QR code to Collect
3. change one of the media files in Central
4. Refresh the form in Collect

#### Expected behavior
The new media file should show in Collect.

#### Other information 
Things I've verified:
* Central changes the md5 hash
* Central changes the etag
* Collect does download the new file and updates the "updated at" timestamp for the form
* The media file is correctly written to storage! I verified this through adb and the files app. Yes, this means that the file that is being used by Collect does not seem to exist in storage.
* The problem persists even after killing and reopening Collect 
* If I delete the image from storage, Collect shows a missing image error. Then if I download the form update, the expected (new) image is saved to disk but the unexpected (old) image is still shown when filling a form!
* If I delete the blank form from the UI and download it again, the unexpected (old) image is still shown
* If I delete the project and create a new one from the same QR code, I get the expected (new) image
* If I scan in the QR code again and create a duplicate project, the duplicate project shows the expected (new) image. The original project still shows the old image

https://forum.getodk.org/t/select-one-multiple-with-images-for-choices-big-image-choice-filtering-labels-images-not-shown-enketo-images-repeated-collect/40655/6?u=ln

I suspect this is related to glide disk caching: https://github.com/bumptech/glide/issues/624#issuecomment-140117332, https://github.com/bumptech/glide/wiki/Caching-and-Cache-Invalidation

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #6419 

#### Why is this the best possible solution? Were any other approaches considered?
According to [Glide's documentation](https://bumptech.github.io/glide/doc/caching.html), we need to assist Glide in determining when cached images should be invalidated. ~There are several options to achieve this, and I chose to base it on the last modification date of the image file which seems to be simple and reliable.~ Now uses MD5 hash because timestamp updates with each form update.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This pull request should just fix the problem with cached images described in the issue.
Please note that we also support SVG images, which are handled differently from other image types, so it’s important to test them as well. For example, I recently forgot to apply this fix to SVG images: [link to PR](https://github.com/getodk/collect/pull/6417), but I've now included it.

#### Do we need any specific form for testing your changes? If so, please attach one.
I used this one:
[imgCacheTest.zip](https://github.com/user-attachments/files/17148779/imgCacheTest.zip)

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by lognaturel — CHANGES_REQUESTED** [review]
Those images are pretty big and will forever increase the size of the repo. Could you please replace them with really small images? I don't think they need to be more than 1x1 squares of different colors. You'll need to rebase the commit introducing the images.

Are you sure that update time is stable across updates without changes to media files? While troubleshooting the original issue I noticed that I was always getting updated timestamps for all media files. I didn't investigate why but it seems to me like there might be an issue there.

**Comment by grzesiek2010** [comment]
> Are you sure that update time is stable across updates without changes to media files? While troubleshooting the original issue I noticed that I was always getting updated timestamps for all media files. I didn't investigate why but it seems to me like there might be an issue there.

I thought I was sure, but you're right. Each updated form creates a new directory, so even though we try to optimize the process by not downloading media attachments we already have, we still have to copy the existing ones from the old location to the new one, which changes the timestamp. This isn't a bug, but it forces Glide to load a new image (not ideal, but manageable). I've updated the fix to use an MD5 hash instead.

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
@getodk/testers I imagine you already have a good protocol for testing this area but just in case you don't have it captured formally anywhere, I think it's important to use as slow of a device as you can and as big of an image as you can. In addition to checking correctness, let's do a brief check of performance. I imagine this will be slightly slower but it shouldn't be very noticeable.

**Comment by lognaturel** [comment]
> Each updated form creates a new directory, so even though we try to optimize the process by not downloading media attachments we already have, we still have to copy the existing ones from the old location to the new one, which changes the timestamp. This isn't a bug

This feels surprising to me. I think it may also explain some unexpected behavior a user recently reported -- they were seeing multiple different form directories with full media even though the form version/definition had never changed. That suggests to me that there might be an issue with cleanup. Is there a reason we can't do the form attachment updating in place if the form definition hasn't changed?

**Comment by grzesiek2010** [comment]
> This feels surprising to me. I think it may also explain some unexpected behavior a user recently reported -- they were seeing multiple different form directories with full media even though the form version/definition had never changed.

That's not the scenario I have described I believe because:

> Is there a reason we can't do the form attachment updating in place if the form definition hasn't changed?

It's not possible to update attachments without bumping the form version right? At least it's not possible with Central.

**Comment by lognaturel** [comment]
> It's not possible to update attachments without bumping the form version right? At least it's not possible with Central.

There are two cases in which it's possible using Central: drafts (that's how this issue was discovered) and Entities. The user issue was reported for a form with Entities. They noticed a few unexpected directories with Entity Lists from different points in time. Given what we've described here, it seems possible that they weren't cleaned up correctly for some reason.

Other servers do more liberally allow updating form attachments without changing the form version.

**Comment by grzesiek2010** [comment]
I've tested drafts, and it's true that all files end up with updated timestamps. We have a mechanism in place to prevent downloading media files that are already available. This was originally implemented for form updates, as we would have encountered the issue with drafts otherwise. The mechanism searches for existing media files in other directories created for the same form (but older versions) before downloading a new one. If a matching file is found, it’s copied to the new location instead of being re-downloaded. Unfortunately, it's not optimized, so if a new directory isn't created (such as in the case of drafts or entities) the file is copied regardless.

**Comment by WKobus** [comment]
**Tested with Success!**

Verified on device with Android 10,14 

**Verified cases:**

- Issue #6419 does not occur
- Different image file types
- Big images
- Selects with SVG images

**Pull request merged**
