### PR TITLE
Tap quickly won't show two 'Pause' icon at the same time, fix #1999.

### LINKED ISSUE #1999: Two 'Pause' icons are visible when user tries to play few sounds quickly
#### Software and hardware versions 
Collect v1.13.2 and older versions

#### Problem description
Two 'Pause' icons are visible when user tries to play few sounds quickly

#### Steps to reproduce the problem
1. User opens `Birds` form from the demo server
2. User clicks on `Speaker` icon
3. `Speaker` icon is changed to `Pause` icon 
4. User immediately clicks on some other `Speaker` icon
5. User sees two `Pause` icons

| | |
| ---- | ---- |
| screenshot_20180312-132041 | screenshot_20180312-132110|

#### Expected behavior
* The `Pause` icon should be restored to `Speaker` icon if user starts to play other sound

#### Other information 
Noticed during testing #1987

### PR DESCRIPTION
**Pull request by huangyz0918**
Closes #1999 

#### What has been done to verify that this works as intended?
Behavior now:
- Tapping audio button, the audio would start playing, everything goes well if user just wait the audio until it completed.
- Tapping one audio button, and tap another one quickly, the previous one would stop and show a `horn` icon, everything will stop and wait for a further operation.
- User **tap the new item again** to start playing the new audio.

It looks like this:

#### Why is this the best possible solution? Were any other approaches considered?
Similar with the method `resetQuestionTextColor` in interface `AudioPlayListener`, The code can be easily to locate the changes can be easily to refactor, so I think this way is good.
Besides, I have refactored some details (e.g, Bitmap in AudioButton) so that I can address this issue in a more convenient way.

#### Are there any risks to merging this code? If so, what are they?
No.
#### Do we need any specific form for testing your changes? If so, please attach one.
No need.

### CODE REVIEW

**Comment by huangyz0918** [comment]
@opendatakit-bot label 'needs review'

**Comment by huangyz0918** [comment]
@opendatakit-bot label "needs review"

**Comment by grzesiek2010** [comment]
@opendatakit-bot label "needs testing"

**Review by grzesiek2010 — APPROVED** [review]

**Comment by mmarciniak90** [comment]
Tested with success!

Verified on Android: 4.1, 4.2, 4.4, 5.1 6.0, 7.0, 8.0

@huangyz0918 It is a good solution to pause currently playing a sound when some other speaker icon is clicked.

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
👍

**Pull request merged**
