### PR TITLE
Revert putting choices from a search() result into JavaRosa choices

### LINKED ISSUE #3132: Autocompletion issues in v1.22
Hi all, here is an issue i just notice today:

#### Software and hardware versions 
Collect v1.22  

#### Problem description
Autocompletion work the first time but then if you go back to change the text, the autocompletion will display the same answer as before you change the text. 

For example i want to select a species from a list, i write the first letters of Vipera aspsis : vip... then on the next screen i can choose between a list of species starting by 'vip' which contain vipera aspis; But instead of selecting vipera aspis and going to the next screen, i decide to go back to change the specie name im looking for. I write 'pod' for Podarcis muralis and proceed to the next sreen. But instead of displaying some species name starting by 'pod' it's displaying the previous list of species starting by 'vip'.
 
#### Steps to reproduce the problem
try with my files

[espece.zip](https://github.com/opendatakit/collect/files/3257634/espece.zip)
[formulaire_adherent.xlsx](https://github.com/opendatakit/collect/files/3257636/formulaire_adherent.xlsx)

#### Other information 
i try the same form with odkcollect 1.21 and it work just fine

thanks for the help !

### PR DESCRIPTION
**Pull request by lognaturel**
Closes #3132

#### What has been done to verify that this works as intended?
Added a test that fails on master, made the fix and then verified that the test passes.

#### Why is this the best possible solution? Were any other approaches considered?
We could fix #2845 by clearing the choices and re-populating them on every form re-evaluation but I don't think we should spend any more effort on this. `search()` fundamentally exists outside of the form spec so it's expected that typical tools wouldn't work with them. If we have additional cycles for external data, we should spend them on supporting external secondary XML and CSV instances.

I didn't revert the whole PR because I think the refactoring is still valuable.

I did a little cleanup when introducing the new test. I changed the name of the package for tests over specific forms to `formentry`. I also put this new form in a `forms` asset subdirectory.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
There are possible regression risks around how `search()` works but I think the two simple tests I've put in place are sufficient to guard against them.

#### Do we need any specific form for testing your changes? If so, please attach one.
https://github.com/opendatakit/collect/compare/master...lognaturel:issue-3132?expand=1#diff-02e431bd1590a9e1aa5d472d5e86ce43 

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by lognaturel** [comment]
I am kicking myself because I noticed this issue while working on updates in field lists in https://github.com/opendatakit/collect/pull/3023#issuecomment-490342792 and wrote 
> I've started looking into search() and am confused about current behavior. Even on master, search-appearance-function-filter.zip seems to only filter down the list based on the first value entered into the textbox. This behavior seems fundamentally incompatible with updates in field lists. I'm not sure we want to fix this now since it goes deeper.

It did not occur to me at the time that a previous change had actually broken it.

**Review by grzesiek2010 — APPROVED** [review]

**Comment by lognaturel** [comment]
@mmarciniak90 I merged this before QA because more and more users were running into it so it seemed like a good idea to get the point release out as soon as possible to minimize disruptions. It would still be good to get a check on this to make sure the tests provide enough coverage and that there aren't other problem cases we may have missed. Thanks!

**Comment by mmarciniak90** [comment]
**Tested with success**

Verified on Android; 4.2, 4.4, 5.1, 6.0, 7.0, 8.1

Verified cases:

- Use case with `formulaire_adherent` form :
    1. The user selects Plante/Aminal/Champignon
    2. The user adds 3 letters on the second question
    3. User sees option lists started on added letters
    4. User backs to the second question and changes letters
    5. New options are visible, options follow the new search

- changing screen orientation
- less/more than 3 letters
- jump via hierarchy view
- invalid search
- case from pr/2845

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Comment by lognaturel** [comment]
Thanks, @mmarciniak90.

**Pull request merged**
