### PR TITLE
Prevent filled form from being edited if sending is canceled or crashes

### LINKED ISSUE #5317: Prevent filled form from being edited if sending is canceled or crashes
Some users have been reporting that they are seeing failures to send submissions because the server has already received a different submission with the same instanceID. Error message from Central:

> A submission already exists with this ID, but with different XML. Resubmissions to attach additional multimedia must resubmit an identical xml_submission_file.

See [this report](https://forum.getodk.org/t/odk-central-upload-error-a-submission-already-exists-with-this-id-but-with-different-xml/33596/5?u=ln).

In https://github.com/getodk/collect/issues/4589, we greatly improved the situation by not allowing edits of failed submissions. I believe that users are now seeing this issue when they have long uploads that they manually cancel or experience crashes during sending.

We can probably do something like change the send status to failed as soon as the XML of the submission is sent. That way, if the user cancels or gets a crash then, they aren't in an inconsistent state.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5317 

#### What has been done to verify that this works as intended?
I've tested uploading forms, canceling the process of uploading.

#### Why is this the best possible solution? Were any other approaches considered?
We shooed mark submission as submission failed before trying to send it in order to make sure it's not possible to edit it when something goes wrong during uploading when it's xml file can be already sent.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Please test uploading finalized forms to make sure there is no regression.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by lognaturel — APPROVED** [review]
The always-blank `uriRemap` is weird to me. Not an issue related to this PR and it's much clearer with your change. But I'm surprised we didn't lose functionality when this change came in. I guess we let users complain if some network configuration is no longer supported.

**Comment by dbemke** [comment]
#### Android version
8.1, 10, 13
#### Device used
Nexus 5X,Redmi 9T, Pixel 3a
#### Problem description
Button "Send Selected" in "Send Finalized Form" is not disabled after cancelling sending forms. Forms are still selected after cancelling sending.
#### Steps to reproduce the problem
1. In Collect setting auto send is off.
2. Go to "Fill Blank Form".
3. Fill and finalize a few forms.
4. Go to "Send Finalized Form".
5. Select forms to send.
6. Tap "Send Selected".
7. Cancel sending the forms.
8. Tap "Send Selected".

The user sees a toast "Sorry, you have not selected any forms" while forms are still selected.
#### Expected behavior
After cancelling sending forms should be deselected, Send Selected button should be disabled.
#### Other information 
The issue doesn’t occur on master 948748b589ee16377da992aef8d4dbd8d4be76d9 and the store version (v2022.3.6)

**Comment by grzesiek2010** [comment]
> Button "Send Selected" in "Send Finalized Form" is not disabled after cancelling sending forms. Forms are still selected after cancelling sending.

That was a tricky one but it should be fixed.

**Comment by srujner** [comment]
**Tested with Success!**

Verified on Android 13 

Verified cases:

- Issue #5317 and one from comments are no longer reproducing;
- Sending finalized Forms, Editing saved Forms, Viewing sent Forms, Deleting saved Forms;
- Match exactly and Failed match exactly;
- Form version and media updates;
- Automatic download and Failed automatic download;
- Killing the app in the middle of sending finalized Forms;
- Cancel sending finalized Forms;
- Rotating the app in the middle of sending finalized Forms;
- Turning off internet connection during sending finalized Forms:
- Sending 1000 submissions to Central;
- Trying to send already sent Form;
- Auto send option off/on;
- Don't keep activities enabled/disabled

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on Android 10

**Pull request merged**
