### PR TITLE
load system locale or use selected language in collect

### PR DESCRIPTION
**Pull request by icemc**
This PR addresses issue #890

### CODE REVIEW

**Comment by icemc** [comment]
@yanokwa  @lognaturel  and @nribeka  added the functionalities as described [here](https://github.com/opendatakit/collect/pull/900). Could you please review the changes made. Tested all the functionalities and it works as required. Waiting to hear from you. Cheers

**Comment by lognaturel** [comment]
Very nice, it's getting quite close!

Here's what I tried:
1. Uninstall app, change phone language to French
1. Install app, it should be in French and settings should show "Use Phone Settings"
1. Change phone language to Spanish, app should be in Spanish and settings should show "Use Phone Settings" as the language
1. Change app language to French, app should be in French and settings should show French as the language
1. __Kill and relaunch app, app should be in French and settings should show French as the language. The app launches in Spanish but settings does show the language as French.__
1. Change app language back to French.
1. Change phone language to English, app should be in French and settings should show French as the language.
1. Change app language to "Use Phone Settings", app should be in English and settings should show "Use Phone Settings" as the language.

Are there any other cases that you thought of? For future pull requests, it's very helpful if you can write out the cases you've considered.

The broken case in bold above is pretty important -- right now language changes don't persist between app launches! That's what the call on `new LocaleHelper().updateLocale(this);` was for in `onCreate`. The good news is that I think you can address this without too much trouble by changing `isUsingSysLanguage` to a local variable in `updateLocale`. Then the value can be read from the settings rather than being in memory and cleared when the app terminates.

**Comment by lognaturel** [comment]
Oh, and also, we tend to squash and merge so don't worry too much about your commit history. For big pull requests where commit history is important, you can always rebase and then force push instead of creating a new pull request.

**Comment by icemc** [comment]
@lognaturel I confirm the problem you pointed out. Working on the fix.

**Comment by icemc** [comment]
@lognaturel  @yanokwa  corrected the changes requested. There is one subtle problem in this fix, I don't verify if the system language is supported by collect. I observed that collect supports so many languages(even those my android phone doesn't support like Afrikaans) and it will be very rare to find a system language not supported by Collect. But if the system language is not supported by Collect what should be done then(Remember language settings is set to "Use phone locale")?

**Comment by icemc** [comment]
Fixing my build was very difficult. I tried doing this the whole day. Don't know why my test keeps failing on cicleci. Learning how to use git ain't an easy task but what a learning experience.
Edit: The problem is from the master  build i forked yesterday it seems to have some issues. But i think the problem was solved. I'm closing this even though it solves the problem since it doesn't pass all the tests in circleci. @lognaturel  @yanokwa  thanks for your understanding.

**Pull request closed without merging**
