### PR TITLE
Avoid multiple empty lines

### PR DESCRIPTION
**Pull request by grzesiek2010**
#### Why is this the best possible solution? Were any other approaches considered?
When I saw another pr (#2257)  where we ask a user to remove multiple empty lines I felt like I can't go to sleep today until I fix the problem :smile: so here you go: new rules in checkstyle.
Nobody likes multiple empty lines as we agreed in one of the already closed prs and it's annoying to ask users to remove them and for users, it's also annoying to see such requests I guess.

so good night!

#### Are there any risks to merging this code? If so, what are they?
No.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew pmd checkstyle lintDebug spotbugsDebug` and confirmed all checks still pass.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by jd-alexander** [comment]
@grzesiek2010 Thank You! I am gonna review this soon. I was always wondering if there isn't a rule we could use to detect this but I just assumed someone had checked it out haha. Good going man!

**Review by shobhitagarwal1612 — APPROVED** [review]

**Comment by shobhitagarwal1612** [comment]
I am totally in favor of adding this check but I think we should consider others' opinion as well as this adds another restriction to writing code base which is related to styling

**Comment by grzesiek2010** [comment]
Yeah, we can wait some time to check if anyone is against.

**Review by jd-alexander — APPROVED** [review]
I think this change makes alot of sense due to the overall style guidelines of the repos maintained under the ODK. I think it's better to enforce this from a static analysis level than code reviews as well.

**Pull request merged**
