### PR TITLE
Fixes multidex issue in Android 4.4. Fixes #387 

### LINKED ISSUE #387: ClassNotFoundException on path DexPathList
Seen from builds 1061, 1063 and 1065 in the Google Play Developer console. It has happened three times each on Android 4.2, 4.4 and 5.1 (so not very frequently). There is a recent user message that says "legal help page" but I don't know what that means.

````
java.lang.RuntimeException: Unable to instantiate application org.odk.collect.android.application.Collect: java.lang.ClassNotFoundException: Didn't find class "org.odk.collect.android.application.Collect" on path: DexPathList[[zip file "/system/framework/com.google.android.maps.jar"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
	at android.app.LoadedApk.makeApplication(LoadedApk.java:628)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4964)
	at android.app.ActivityThread.access$1600(ActivityThread.java:177)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1491)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5910)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.odk.collect.android.application.Collect" on path: DexPathList[[zip file "/system/framework/com.google.android.maps.jar"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	at android.app.Instrumentation.newApplication(Instrumentation.java:987)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:623)
	... 10 more
	Suppressed: java.lang.ClassNotFoundException: org.odk.collect.android.application.Collect
		at java.lang.Class.classForName(Native Method)
		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
		... 13 more
Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
````

[This StackOverflow post](http://stackoverflow.com/questions/29816745/classnotfoundexception-didnt-find-class-on-path-dexpathlist) has some ideas to explore.

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Fixes issue #387

### CODE REVIEW

**Comment by lognaturel** [comment]
Can you please add a comment on that method to the effect of "Use the multidex support library as required for a minSDKVersion of 20 or lower. https://developer.android.com/studio/build/multidex.html" I want to make sure we keep track of the fact that we can eventually remove this code.

**Comment by shobhitagarwal1612** [comment]
@lognaturel Sure

**Comment by lognaturel** [comment]
And I should just add, if you commit it to the same branch (in this case your fork's master branch), the PR will be updated, no need to do anything else special. :)

**Comment by lognaturel** [comment]
As I understand it, that method doesn't actually have anything to do with Instant Run, it enables the multidex support library! The comment should reflect that. It's also helpful to add a link to the reference (https://developer.android.com/studio/build/multidex.html).

**Comment by grzesiek2010** [comment]
According to the doc https://developer.android.com/studio/build/multidex.html changing
`extends Application` to `extends MultiDexApplication` should be enough (in Collect class).

**Comment by lognaturel** [comment]
I did see that @grzesiek2010 but it is just a subclass of `Application` with that method. See code [here](https://android.googlesource.com/platform/frameworks/multidex/+/master/library/src/android/support/multidex/MultiDexApplication.java). I think it's clearer to have the method with a comment.

**Comment by shobhitagarwal1612** [comment]
@lognaturel Is the comment ok now?

**Comment by lognaturel** [comment]
Yes, thank you! And for what it's worth, this also fixes my `INSTALL_FAILED_DEXOPT` problem with the API 9 emulator. 👍

**Pull request merged**
