### PR TITLE
Fix tests that contain screen rotation

### LINKED ISSUE #3205: Espresso regression tests failing sporadically
The `DrawWidgetTest` and `SignatureWidgetTest` appear to be failing on most runs on Test Lab but not in a predictable manner. The actual failure appears to be:

```
androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with id: org.odk.collect.android:id/jumpEndButton 
```

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #3205 

#### What has been done to verify that this works as intended?
We can't reproduce the issue so nothing.

#### Why is this the best possible solution? Were any other approaches considered?
I just guess that it might fix failing tests as described in #3205 

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
No risk.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by seadowg** [comment]
@grzesiek2010 did this fix it on Test Lab?

**Comment by grzesiek2010** [comment]
Ok, I've just realized I can do that without merging let me play with it a bit :)

**Comment by grzesiek2010** [comment]
@seadowg I tested `waitForIdleSync()` but it doesn't fix the problem. The only way that seems pretty reliable is using `Thread.sleep()` what I did. I know we don't like it but 5 test passed in a row on Test Lab so looks as if it works.

**Comment by seadowg** [comment]
Ach that's annoying. One thing I've done when I've run into a scenario like this is use a "looping wait" rather than a solo `sleep`. In a test that's waiting for some text to appear that says "Hello" this would look like this:

```java
waitFor(() -> {
    onView(withText("Hello")).check(matches(isDisplayed()));
});
```

The actual implementation of the method could be:

```java
public static void waitFor(Runnable runnable) throws TimeoutException {
    long startTime = System.currentTimeMillis();

    do {
        try {
            runnable.run();
            return;
        catch (Exception e) {
            Thread.sleep(500);
        }
    } while ((System.currentTimeMillis() - startTime) < TIMEOUT);

    throw new TimeoutException();
}
```

This is a bit nicer than a solo `sleep` as we check several times and then get out as early as we can. This means on a fast device we probably don't wait as long as we would have set the sleep and a slow device will pass without needing to bump the sleep time up.

For these tests we could use a `waitFor` with an assertion on what we expect the screen to look like after the rotation.

What do you think?

**Review by seadowg — CHANGES_REQUESTED** [review]
As earlier comments - just making sure this is in the right state!

**Comment by grzesiek2010** [comment]
I tried improving the solution but to no avail: https://github.com/opendatakit/collect/commit/ca06a2ce2973806266957b90f292f3195dcc3331
looks as if ids are available before and the method returns too quickly.
I talked to @seadowg and we decided to leave it as-is for now and maybe in the future we will be able to do it better.

@seadowg I resolved conflict so you can merge.

**Comment by seadowg** [comment]
Looks good! Gave this a run on test lab as well.

**Review by seadowg — APPROVED** [review]

**Pull request merged**
