### PR TITLE
New buttons in DrawActivity

### LINKED ISSUE #914: Buttons in DrawWidget don't look good
#### Software and hardware versions 
Collect v1.5.1

#### Steps to reproduce the problem
Use this form: 
[draw.txt](https://github.com/opendatakit/collect/files/929900/draw.txt)

#### Other information 
screenshot_2017-04-18-15-17-10

### PR DESCRIPTION
**Pull request by grzesiek2010**
This PR is in reference to resolve #914

### CODE REVIEW

**Comment by grzesiek2010** [comment]
@lognaturel it's ready.

**Comment by lognaturel** [comment]
Nice! One thing that would be really useful to document as UI changes start happening is whether a check on API 16 has been done (lowest possible API level).

The floating action button looks very nice to me and definitely a big improvement! There are still a bunch of bugs with the widget and it's a bit hard to know what to look at and not but I'll try to focus on issues specific to these changes. One is that the screen clears when changing orientation (only for draw since the other two don't allow rotation). The color picked is also reset. I think that's a new thing, right?

The reset button only resets the drawings added in this session which is unexpected. For signature, it does reset the whole thing which is what I would expect.

I also do want to make sure that we coordinate a little bit when making UI changes to make sure there's a consistent look and feel across the app. I think floating action buttons are pretty common now and @shobhitagarwal1612 has proposed using the concept as well. But let's make sure this will harmonize with all the other planned changes.

A high-level thing about floating action buttons -- the secondary buttons are pretty small and close together. Will it work ok on devices with inaccurate touch screens? Small screens? Is the text big enough?

@yanokwa @nribeka @shobhitagarwal1612

**Comment by grzesiek2010** [comment]
@lognaturel 

> One thing that would be really useful to document as UI changes start happening is whether a check on API 16 has been done (lowest possible API level)

I've tested my changes using Samsung Galaxy Young Android 4.1.2 (API level 16) 

> One is that the screen clears when changing orientation (only for draw since the other two don't allow rotation). The color picked is also reset. I think that's a new thing, right?

> The reset button only resets the drawings added in this session which is unexpected. For signature, it does reset the whole thing which is what I would expect.

everything works as before I would like to fix some other problems but in a separate prs and I'll file new issues, this pr contains only layout changes.

> A high-level thing about floating action buttons -- the secondary buttons are pretty small and close together. Will it work ok on devices with inaccurate touch screens? Small screens? Is the text big enough?

It looks ok I think. Here you can see three various screen seizes:
1080 x 1920 pixels (~441 ppi pixel density)
screenshot_2017-06-07-09-06-13

480 x 800 pixels (~233 ppi pixel density)
screenshot_2017-06-07-12-53-38

320 x 480 pixels (~176 ppi pixel density)
screenshot_2017-06-07-09-33-26

**Comment by lognaturel** [comment]
Thanks! Makes sense to do the bug fixes separately. I'd like a verification and ok from @shobhitagarwal1612 and @yanokwa since they're the most involved with UI decisions.

**Comment by shobhitagarwal1612** [comment]
Looking great!!!
This can be used as a reference in future for adding floating buttons in other places as well.
:+1:

**Comment by lognaturel** [comment]
Well if it gets three !!! from @shobhitagarwal1612, that's fantastic!

Got a chance to quickly show it to @yanokwa. He's on board. His only question was whether it's possible to not have any animation when the buttons are disappearing. Now that I look more carefully at it, it does look a little bit glitchy.

Google Maps has a similar menu when in navigation mode. That one just disappears without animation which I like. It also makes the labels clickable which is another thing I think is nice. What do you think about adding that, @grzesiek2010?

**Comment by grzesiek2010** [comment]
@lognaturel I've added possibility to click on labels and removed out animation. I think it's ready.

**Pull request merged**
