### PR TITLE
Add checking update path to release checklist

### PR DESCRIPTION
**Pull request by seadowg**
We recently ended up with a production crash based on a bug in our update path. There's not currently a simple way to check this in our automated test suite (or certainly not in a way that would have caught the recent bug), and we don't want to check it on every PR, so I think we should make it a manual pre-release check for the moment to catch us missing any problems in a PR.

### CODE REVIEW

**Comment by lognaturel** [comment]
Possibly useful note: use `adb install -r`.

I think in this case what's described wouldn't have actually caught the issue and in fact I'm pretty sure I did do those steps. It would have had to be downloading a new form to an existing project. When creating a new project, a new forms db would have been created and that would have worked fine.

**Comment by seadowg** [comment]
Good point. I can have a think about a better set of steps.

**Comment by lognaturel** [comment]
I'm not convinced this is the right level to add a set of checks at. Review and QA feel more appropriate.

**Comment by seadowg** [comment]
I think #5429 is a better effort from protecting us from the specific problem we had than this PR. However, I still think having an explicit step to check upgrades is a good idea. I imagine this gets checked most times we do releases anyway, but a reminder won't hurt.

**Review by lognaturel — APPROVED** [review]

**Pull request merged**
