### PR TITLE
Fixed: User is able to open two different views from the main screen

### LINKED ISSUE #4213: User is able to open two different views from the main screen
#### Software and hardware versions 
Collect v1.28.4 (older versions were not verified)
Android: 7.1 (Motorola), 8.1 (LG), 9.0 (Xiaomi), 10.0 (Xiaomi)

#### Problem description
User is able to open two different views from the main screen

#### Steps to reproduce the problem
1. User clicks on two different buttons on the main screen
2. User sees that one view is opened -> user clicks on device back button to leave it
3. User sees that second view is opened

ezgif com-video-to-gif

#### Expected behavior
Opening multi-views is not possible

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #4213

#### What has been done to verify that this works as intended?
I tested the fix manually and added tests.

#### Why is this the best possible solution? Were any other approaches considered?
We have custom `MultiClickSafeButton` so using them in the main menu is better and also fixes the issue since using `MultiClickGuard.allowClick` in `OnClickListener` was faulty..

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It's a safe fix so we can just verify that the issue describe in #4213 is fixed.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
> using MultiClickGuard.allowClick in OnClickListener was faulty.

Is the implementation problematic or just the usage? Does this affect anything else?

**Comment by grzesiek2010** [comment]
> Is the implementation problematic or just the usage? Does this affect anything else?

`getClass().getName()` used in `if (MultiClickGuard.allowClick(getClass().getName()))` was returning numbers at the end of class names like 1,2,3 (because it's inside anonymous classes) for different buttons that's why it didn't work.

**Comment by kkrawczyk123** [comment]
**Tested with success!**
Verified on Androids: 5.1, 7.1, 9.0 and 10

Tested scenarios:
- clicking on two buttons in menu in the same time
- multiclick on all menu buttons
- portrait/landscape

**Comment by mmarciniak90** [comment]
Tested with success on Android versions: 7.0, 8.1, 10.0

@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"

**Pull request merged**
