### PR TITLE
fix: Rename 'Type' to 'Server' in Admin Settings > User Settings fix …

### LINKED ISSUE #1311: Rename 'Type' to 'Server' in Admin Settings > User Settings
The top-level item for defining a server used to be "type" (as in server type) but now it is "server". It looks like the admin settings were not updated to match.

### PR DESCRIPTION
**Pull request by dr0pdb**
Closes #1311
Translations of the word 'server' needs to be done in the future.

### CODE REVIEW

**Review by heyjamesknight — APPROVED** [review]
Straightforward change, looks good and follows `strings.xml` naming conventions.

**Comment by Yurii-Laguta** [comment]
At the moment string "type" has 11 translation, any chance you could add them, otherwise it will result in worse user experience. 
"server" is easily translatable by Google Translate. But I'm new here, so it's just an opinion

**Review by yurilaguta — COMMENTED** [review]
Clear change. Good to be merged any type.

**Review by yurilaguta — APPROVED** [review]
Look straight forward and simple.

**Review by lognaturel — APPROVED** [review]

**Pull request merged**
