### PR TITLE
WIP: Nepali (Bikram Sambat) Date Widget

### PR DESCRIPTION
**Pull request by konishon**
@lognaturel 
Please, look at it is more or less copy paste of @grzesiek2010  and @alxndrsn implementations.
What are your thoughts on it ?

[NepaliDateDemo.xml.txt](https://github.com/opendatakit/collect/files/1440121/NepaliDateDemo.xml.txt)

### CODE REVIEW

**Comment by grzesiek2010** [comment]
@nishontan Could you clean your code. It contains lots of not related changes.

Please use also commands like:
```
./gradlew lint
./gradlew checkstyle
./gradlew pmd
```

to be sure you follow all rules.

**Comment by lognaturel** [comment]
Before @nishontan does this, we should take a look at the approach and make sure it's looking good. What are your thoughts, @grzesiek2010?

**Comment by lognaturel** [comment]
This is a really good start, @nishontan! 

There are a few bugs like the date not updating as the spinners are changed and as @grzesiek2010 said there are some unrelated changes that need to be removed but before those are addressed, we need to decide whether we want to go with just using the methods @alxndrsn defined of whether we should build the joda chronology. I'm fine either way. If we choose to keep @alxndrsn's code it should go in its own file with a copyright notice matching that code's license.

**Comment by konishon** [comment]
@alxndrsn is going to work on nepali chronology on joda time. I am excited to see either that or however he implements the NepaliDateWidget

**Comment by lognaturel** [comment]
Thank you for looking into this @nishontan and @alxndrsn! I'll let @alxndrsn open a new pull request when he is ready.

**Pull request closed without merging**
