### PR TITLE
fixes #585 

### LINKED ISSUE #585: Sending complete form progress dialog showing sliced upload
#### Software and hardware versions 
Collect code latest from master

#### Problem description
With the current slicing, when you upload more than the slice size, the dialog will show the sliced counter instead of the overall upload counter.

#### Steps to reproduce the problem
* Change the slice size to lower number in `ApplicationConstants.SQLITE_MAXIMUM_QUERY_LIMIT` (I use 3).
* In the send finalized form section, select forms more than the slice size (7 forms in my case).
* Press "Send Selected" to upload the form
* The dialog will display "Sending 1 of 3 forms" twice and "Sending 1 of 1 forms" for the last slice.

#### Expected behavior
The dialog should display the progress of the upload as a whole instead. So it should show "Sending 1 of 7 forms" and then start counting to 7.

### PR DESCRIPTION
**Pull request by lokeshkvn**
Removed Hard Coded Integer from SQLITE_MAXIMUM_QUERY_LIMIT in progress dialog box of Send Finalized Form

### CODE REVIEW

**Comment by rijuldhir** [comment]
@lokeshkvn I was the one who asked to fix the issue and was waiting for response from core committer.
I even had the PR ready

**Comment by lakshyagupta21** [comment]
@lokeshkvn Have you read the contents on the link provided in the comments just above the declaration of SQLITE_MAXIMUM_QUERY_LIMIT. The reason for providing the comment is that contributors should be able to understand why it is initialized so i request you to please read the contents first. It needs to be hardcoded.

Have you tried uploading files after the changes you made ?

**Comment by lokeshkvn** [comment]
@lakshyagupta21 I have tested it with 7 forms in Android v7.1 and with 4 forms Android v5.1 and it worked fine. 
according to http://www.sqlite.org/limits.html, its given about Maximum limit of column in Sqlite tables.
I have searched in stackoverflow about upper limits when we have no clue about what will be the upper bound and I found Integer.MAX_VALUE . 

@rijuldhir Sorry for your inconvienience , I am closing this PR go ahead. Good Luck 👍

**Comment by lakshyagupta21** [comment]
@lokeshkvn Try uploading files > 999 then observe the logcat.

**Comment by rijuldhir** [comment]
Thanks @lokeshkvn Read http://www.sqlite.org/limits.html and found that Maximum rows can be 2^64. I think we can replace it with Integer.MaxValue.

**Pull request closed without merging**
