### PR TITLE
Allow disabling external recording feature

### LINKED ISSUE #4229: Admin can disable external recording setting
**Acceptance**

- [x] Given I have access to Admin Settings
When I navigate to "User settings"
And I uncheck "External app recording"
Then that setting is hidden in General Settings

- [x] Given I have access to admin settings
When I navigate to "User settings"
And I check "External app recording"
Then that setting is shown in General Settings

### PR DESCRIPTION
**Pull request by seadowg**
Closes #4229

#### What has been done to verify that this works as intended?

New tests and verified manually

#### Why is this the best possible solution? Were any other approaches considered?

Just using our standard pattern for tests and implementation here.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Just good to verify acceptance criteria here I think.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by lognaturel — APPROVED** [review]

**Comment by mmarciniak90** [comment]
@seadowg, this option is not visible at all in General Settings when you uncheck all options except the `Use external app for audio recording` in Admin Settings.

ezgif com-video-to-gif

I have also a suggestion to move `Use external app for audio recording` option under `Show guidance for questions` to follow the same order as in the Form Management list.

**Comment by mmarciniak90** [comment]
@getodk-bot unlabel "needs testing"

**Comment by seadowg** [comment]
@mmarciniak90 oh wow I didn't realize that we hide sections if all the keys were disabled. What do you think about just not doing that? It's pretty easy to not realize and create the problem (like I just did).  We could add tests but I think you'd still need to remember to add a new test every time we move settings around or add/remove one. To me, it feels like a pretty risky feature with not a lot of value -worst case scenario the enumerator is able to click into a blank screen. cc/ @lognaturel.

**Comment by mmarciniak90** [comment]
@seadowg, it's not new behavior. We checked a similar case to other options, eg. guidance. Displaying a blank screen in General Settings is possible.

**Comment by seadowg** [comment]
@mmarciniak90 right. My feeling is it'd be great if none of us had to keep track of it! For the moment I can fix and I'll add an issue about removing the feature.

**Comment by seadowg** [comment]
@mmarciniak90 fixed!

**Comment by mmarciniak90** [comment]
@seadowg thanks! 

**Tested with success** 

Verified on Android versions: 7.0, 8.1, 10.0, and emulator with v5.0

Verified cases:
- `Use external app for audio recording` checked in Admin Settings
   - option is visible in the user's General Settings
- `Use external app for audio recording` unchecked in Admin Settings
   - option is not visible in the user's General Settings
   - option is still visible in admin's General Settings
- only `Use external app for audio recording` checked in Admin Settings
   - Form management with option is visible
- scan QR code with option disabled/enabled
- light/dark mode
- RTL language

@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"

**Pull request merged**
