### PR TITLE
WIP : Settings redesign

### LINKED ISSUE #1048: Redesign settings
The following changes were proposed in the GSoC [proposal ](https://docs.google.com/document/d/1tAP5vRdwiF3KdqXnXGKJnjlh98SywbeoyQSZQWMRhSA/edit)for this: 

- Removing separate options for admin and general settings and merging them into one
- Regrouping the preferences in order to reduce the number of options on a single screen

This issue is created in order to discuss the re-work that should be done in the settings. 
Everyone, please share your views. @yanokwa @lognaturel @grzesiek2010 I would love to hear your thoughts.

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
In reference to resolve #1048

### CODE REVIEW

**Comment by lognaturel** [comment]
This is so nice! I'm going to need to take a closer look at the details but in general it is a huge improvement.

This is currently set up to go into the ui-refresh branch but perhaps we should do it in master and ship it next month? I don't think many enumerators are trained on using settings anyway and it will make things a lot easier. What do others think?

**Comment by shobhitagarwal1612** [comment]
@lognaturel I agree with you.

**Comment by yanokwa** [comment]
Great work, @shobhitagarwal1612! I went through these and put some of my thoughts below. This are just suggestions, so if any of these don't feel right, let's discuss them and try to reach a consensus. I expect that we'll go through a few iterations before it feels nice.

Paging @grzesiek2010 @rowo @hooverlunch for their feedback as well!

#### Icons
I like the icons, but they seem much bigger than other settings icons I've seen. Match the format of https://material.io/guidelines/patterns/settings.html with the app contrast color (use a variable for now).

#### Autosend
I think we should change this to a select one with the following options (Off, Wifi only, Cellular only, Wifi or cellular). We should be able to use the same preference variables for backward compatibility.

#### Platform
Can we change this so changing the platform shows the appropriate settings below? If you need an example, when you add a WiFi network and toggle the security, it does what I'm imagining. If this is going to be a lot of work, we should talk about it first!

#### Sentence case
It looks like the Android settings use Sentence case. Instead of `Server Settings` it should be `Server settings`. Text that are acronyms should be capitalized (e.g, `URL`).

#### Renaming
Rename `Platform` to `Type`
Rename `Show splash screen` to just `Splash screen`
Rename `Constraint processing behavior` to just `Constraint processing`
Rename `Use phone language` to `Use device language`
Rename `Enable hi-res video` to `High res video`
Rename `Select a basemap` to just `Basemap`

#### General Settings
Server
* Type
* Type settings (dynamic, no title)

User interface
* Language
* Text font size
* Navigation
* Splash screen
* Mapping (section header)
	* Mapping SDK
	* Basemap

Form management
* Form submission (section header)
	* Auto send
	* Delete after send
* Form filling (section header)
	* Default to finalized
	* Constraint processing
	* Hi-res video
* Form import (section header)
	* Import saved forms as finalized

User and device identity
* Form metadata
* Usage data

#### Admin Settings

I like the layout you have and I love the User Access Control title.

I would remove all the secondary under the individual items (e.g, `Unchecked to hide from Main Menu`) because it's redundant redundant. Would it be possible to instead have some note at the top?

Under Main Menu and User and Form Entry Settings, I would remove the secondary/summary/hint text. It doesn't add anything. https://material.io/guidelines/patterns/settings.html for more.

**Comment by lognaturel** [comment]
I love where this is going!

**Comment by lognaturel** [comment]
Just some ideas...
* Client: https://material.io/icons/#ic_phonelink_setup
* Form management: https://material.io/icons/#ic_assignment
* User and device identity: https://material.io/icons/#ic_face

**Pull request closed without merging**
