### PR TITLE
Improve naming of filtered form list including only newest

### LINKED ISSUE #2705: Improve naming of filtered form list including only newest
https://github.com/opendatakit/collect/pull/2691 introduces a new content URI for getting only the newest version of each form_id. I named it `uniqueFormsByFormId`. In a conversation with @zestyping, he suggested `newestFormsByFormId` but I completely forgot to make the change. 

Since this is user-facing but not documented yet, I propose we make the change now as part of a hotfix.

### PR DESCRIPTION
**Pull request by lognaturel**
Closes #2705 

#### What has been done to verify that this works as intended?
Tried Fill Blank Form with and without the hide older versions setting. This uses all three content URIs. Opened the form list from collectTester and downloaded a blank form.

#### Why is this the best possible solution? Were any other approaches considered?
I thought about just changing the URI name but then I realized this was a good opportunity to improve some more naming and comments for greater consistency. In particular, introducing a constant for the new content URI and using the content URI constants in the URI matcher reduces the risk of errors.

I took a look at https://android.googlesource.com/platform/frameworks/base/+/android-4.2.2_r1/core/java/android/provider/CalendarContract.java for naming and comment inspiration. I saw that the convention for content provider paths is to use `snake_case` rather than `camelCase` so I changed that too.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
If someone started immediately using the `uniqueFormsByFormId` content URI in their external app, this change would disrupt them. This is vanishingly unlikely since it's been released for a day and is undocumented.

Users not using external apps should see no change. There is some risk around listing and selecting forms but I think the manual verification I described above is sufficient to confirm the behavior is as-expected.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
Yes, we should document the content provider URI. I have added a note at https://github.com/opendatakit/docs/issues/876#issuecomment-434552013.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by lognaturel** [comment]
@zestyping, if you have a moment to make sure I executed what you had in mind, please take a look!

**Comment by zestyping** [comment]
This looks great to me!

**Review by shobhitagarwal1612 — APPROVED** [review]

**Review by grzesiek2010 — APPROVED** [review]

**Comment by kkrawczyk123** [comment]
I have checked fill blank form for all kinds of sorting, for filtering, display/hide only the newest version of the form, finalizing different version of the same form and sending them as well. It all looked good on Androids 4.4, 5.1, 6.0, 7.0 and 8.1. 

Unfortunately, I am not able to use Collect nearly at all on Androids 4.1 and 4.2 as it's crashing when open Fill Blank Form, View Sent Form, Get Blank form and Delete Saved Form. (confirmed that on master branch everything works just fine).

@opendatakit-bot unlabel "needs testing"

**Comment by lognaturel** [comment]
Thanks, @kkrawczyk123! Wow, sometimes I wonder how supporting low API levels hasn't made us all crazy by now.

From https://developer.android.com/reference/android/content/UriMatcher:
> Starting from API level Build.VERSION_CODES.JELLY_BEAN_MR2, paths can start with a leading slash.

I still think it's good to use the URI constants to ensure consistency of the paths. I considered introducing new constants for the paths without leading slashes but I think removing the leading slashes when initializing the `UriMatcher` is just as clear and gives me an opportunity to explain why the leading slash can't be there in that specific context.

**Comment by zestyping** [comment]
Yeah, I agree this is the best solution.

The same situation could potentially come up in InstanceProvider.java but constants aren't used there yet.

**Comment by kkrawczyk123** [comment]
Confirmed that issue has been fixed.
Verified on Androids: 4.1, 4.2, 4.4, 6.0, 7.0 and 8.1.

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Pull request merged**
