### PR TITLE
Removed the limitation of 256 columns in Google Sheets

### LINKED ISSUE #2888: Remove 255 sheet limit in Google Sheet support
#### Software and hardware versions 
Collect v1.9.x

#### Problem description
Google Sheets used to have a 255 column limit, but according to https://support.google.com/drive/answer/37603, that's been changed to a 5 million cell limit. We should confirm that the limit is actually gone (maybe the API still has the limit). 

If so, we should probably remove the 255 column limit in Collect and
1. warn users that if they have a campaign with more than 5 million cells, submissions will fail
2. or try to create a new sheet if we run into that limit

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #2888 

#### What has been done to verify that this works as intended?
I tested a form with one thousand questions:
[OneThousandQuestions.xml.txt](https://github.com/opendatakit/collect/files/2888845/OneThousandQuestions.xml.txt)

#### Why is this the best possible solution? Were any other approaches considered?
I just removed a limitation.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It just removes the limitation of 256 columns. Now we are able to send bigger forms to Google Sheets.
It's not risky, we just need to test forms with many questions like the one I attached.

#### Do we need any specific form for testing your changes? If so, please attach one.
The form attached above.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by yanokwa** [comment]
What happens if a sheet reaches the 5 million cell mark?

**Review by yanokwa — APPROVED** [review]

**Comment by grzesiek2010** [comment]
> What happens if a sheet reaches the 5 million cell mark?

I didn't try I think it's an unreal case.

**Comment by yanokwa** [comment]
Famous last words, @grzesiek2010. I've seen campaigns with more data than that so we should at least know what happens when you get past that. Maybe we add the limit to the docs, and add an issue for someone to test this as a `quick win`?

**Comment by grzesiek2010** [comment]
ahhh it's about cells, not columns... ok then yes it could be possible I'll try to do that

**Comment by grzesiek2010** [comment]
Ok, I prepared a sheet with almost 5 million cells, I should be able to send one last form but I can't I get this:
screenshot_2019-02-21-22-32-26

It works really slow. If I try to add a new row manually (using a browser) : 
screenshot from 2019-02-21 22-44-23

So probably it would be a similar message but can't confirm since it works too slowly.

**Comment by mmarciniak90** [comment]
**Tested with success**

Verified on Android: 4.2, 4.4, 6.0, 7.0, 8.1

Verified forms:
* [OneThousandQuestions.xml.txt](https://github.com/opendatakit/collect/files/2892857/OneThousandQuestions.xml.txt)
* [mr.xml.txt](https://github.com/opendatakit/collect/files/2892860/mr.xml.txt)

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Comment by yanokwa** [comment]
@grzesiek2010 Interesting that the failure mode is a timeout. Please file an issue on docs so we can document the 5 million cell limit. We'll just tell people if they expect to have that many cells, they should use something else.

**Comment by grzesiek2010** [comment]
ok, done.

**Pull request merged**
