### PR TITLE
Allow date, datetime and time widgets to show 'null' values

### LINKED ISSUE #81: Allow date, datetime and time widgets to show 'null' values
<a href="https://github.com/mitchellsundt"></img></a> **Issue by [mitchellsundt](https://github.com/mitchellsundt)**
_Thursday Jul 09, 2015 at 19:02 GMT_
_Originally opened as https://github.com/opendatakit/opendatakit/issues/685 (1 comment(s))_

---

Originally reported on Google Code with ID 684

```
What steps will reproduce the problem?
1. define one of these widgets
2. see that it displays the current date/time as the default value.

What is the expected output? What do you see instead?

Would like to be able to display 'null' or 'unselected' values in some way.

And allow null values to be swiped through without them being stored as today's date/time.


```

Reported by `mitchellsundt` on 2012-09-17 16:57:24

### PR DESCRIPTION
**Pull request by grzesiek2010**
This PR is in reference to resolve #81

I've tested my changes and I haven't noticed any crash. I've noticed that constraint doesn't work properly when the answer is null (it allows to go to next question).

@lognaturel I wasn't able to use relevant for dates (only simple relevant false) is it possible to use for example something like `relevant="/widgets/Date > date('2017-11-12')"` with date? there is no example for [dates](https://opendatakit.org/help/form-design/binding/)
 
Here is a form for testing: 
[dates.txt](https://github.com/opendatakit/collect/files/947023/dates.txt)

### CODE REVIEW

**Comment by lognaturel** [comment]
Is it possible that your relevant test didn't work out because you used the `widget` node name instead of `data`? I replaced your `false` by `/data/Date > today()` and `/data/Date > date('2017-11-12')`, both work great.

The fact that constraints don't work properly is problematic. We should try to identify the root cause, presumably on the JavaRosa side of things.

Otherwise, it's looking great!

**Comment by grzesiek2010** [comment]
@lognaturel 
hmmm strange I'm sure I've tried with `/data/something` anyway you are right it works and it works well with null as well so looks like we have only one problem -  constraints + null.

**Comment by grzesiek2010** [comment]
@lognaturel the problem is that `true` is returned if selected value is null look here:
https://github.com/opendatakit/javarosa/pull/38
That change works well with above attached form but I'm not sure what about other cases - I don't know why someone has added that null check.

**Comment by lognaturel** [comment]
@grzesiek2010 I think the choice was explicitly to allow blank values for non-required fields regardless of the constraint. In other words, if a form designer wants to guarantee that a value will be set, he or she must use the `required` keyword. The `constraint` only applies in the case that there is a value. 

For an example of that at work, see the decimal field in the Widgets test form on the default server. It requires numbers >10.51 and <18.39 but it does allow blank values. I believe that is by design.

@yanokwa does that sound right? If so, I think we can review and merge this pull request as it is.

**Comment by yanokwa** [comment]
This sounds correct.

**Comment by lognaturel** [comment]
The one thing I'm not totally sure about is what happens when one of date or time is null in a datetime widget. Right now it automatically fills in the current date/time. I think that could be confusing or wrong. I'll think about it some more and file a separate issue if I can think of a better behavior.

**Pull request merged**
