### PR TITLE
Add support to manually enter Bearing reading using EditText.

### LINKED ISSUE #1572: Graceful degradation of bearing widget
#### Software and hardware versions 
Collect v1.10.2, 1.11.0, 
Android v5 (Lenovo Tab3 7"), Android 6 (Moto G4+), Android 7 (Samsung S2 8")

#### Problem description
The [bearing widget](http://docs.opendatakit.org/form-widgets/#bearing-widget) works great in devices with compass hardware (S2), but does not work in devices without the required hardware to measure magnetic bearings (Tab3, G4+).

#### Steps to reproduce the problem
Fill in a form with the bearing widget on a compatible vs. an incompatible device.

#### Expected behaviour
Incompatible devices show the "capture bearing" button greyed out, so there is some form of communication between ODK Collect rendering the button as inactive and the underlying hardware.

It would be great if in this case, the form would simply and gracefully degrade the widget to a simple numeric input -- after all, the bearing widget is only a special case of a numeric input.

This would allow devices to capture bearing information from built-in hardware (ideally) or from external sources (e.g. a hand held compass, if available).

### PR DESCRIPTION
**Pull request by akshay-ap**
Closes #1572

#### What has been done to verify that this works as intended?
Tested on Motorola e2 (2nd generation) - (without sensor support)
Moto M - (with sensor support)
#### Why is this the best possible solution? Were any other approaches considered?
This method required minimum changes in current code. Changes are easy to understand.
#### Are there any risks to merging this code? If so, what are they?
`isValidInput()` method might need improvement.
Toast messages might need change.

#### Do we need any specific form for testing your changes? If so, please attach one.
Need to check if the changes affect form filling in any way.

### CODE REVIEW

**Comment by akshay-ap** [comment]
This is how the user will upload bearing reading manually (screenshots from Moto e2 2nd gen)
screenshot_2017-11-15-00-32-14
screenshot_2017-11-15-00-32-20
screenshot_2017-11-15-00-32-37

**Comment by akshay-ap** [comment]
Some improvements that might be needed :
1. Currently, if sensor is not available, `EditText` is shown but the keyboard is closed initially. User needs to click on `EditText` to open keyboard.
2. On invalid input keyboard is closed. User needs to open it again by clicking `EditText`
3. Input validation can be improved.

**Comment by grzesiek2010** [comment]
I think this approach is not consistent with ExStringWidget/ExIntegerWidget/ExDecimapWidget where we still keep the button but that button is disabled and then we can pass something manually using an EditText.
What do you think @lognaturel ?

**Comment by lognaturel** [comment]
I haven't looked at this in detail yet but I do agree that ideally it would be consistent with other question types that have a similar pattern.

**Comment by akshay-ap** [comment]
@grzesiek2010 So you mean `Take bearing` button should be seen but disabled in case sensor is not available? If yes, it can be done by making few changes in current PR. But I was not sure where to add `getEditText()` method. Should it be in `QuestionWidget` or `BearingWidget` ?

**Comment by grzesiek2010** [comment]
@akshay-ap just try eg. `Ex string widget` form `AllWIdgets form`. I think the behavior should be the same.

**Comment by akshay-ap** [comment]
@grzesiek2010 @lognaturel 
This is how it looks now : 
Screen shot

**Comment by lognaturel** [comment]
This is getting close, @akshay-ap! Thanks for taking it on. In terms of interface, it looks really close. The other external widgets don't have the keyboard pop up but they do show the cursor in the edittext. That makes it clearer that it is editable so I would recommend doing the same.

In terms of functionality, it looks like the value is not actually getting saved! That's an important one to fix.

Additionally, could you please rebase on master and force push? There are unrelated changes showing up in the diff right now.

**Comment by akshay-ap** [comment]
@lognaturel This branch seems to be pretty messed up. I tried rebase command but I am not able to remove unnecessary commits. Shall I file a new pull request?

**Comment by lognaturel** [comment]
It's up to you @akshay-ap! If that's easier for you it would be fine.

**Comment by akshay-ap** [comment]
I have added PR #1655 to solve #1572

**Pull request closed without merging**
