### PR TITLE
On form download, only set up the reference manager if the form has media

### LINKED ISSUE #3535: Unable to download forms without media attachments
#### Software and hardware versions 
Collect current master.x, Android v7, 9 probably all.x.x, device used...

#### Problem description
The error message is displayed when try to download form from Central:
Screenshot_20191213-161532

#### Steps to reproduce the problem
1. Import settings via QR code from Central to Collect.
2. Go to Get Blank Form
3. Select form from the displayed list
4. Click on Get Selected

#### Expected behavior
The form should be successfully downloaded.

#### Other information 
!! The issue does not occur on beta, only on current master

### PR DESCRIPTION
**Pull request by lognaturel**
Closes #3535

#### What has been done to verify that this works as intended?
Ran the automated tests. Downloaded forms with and without media from the default Aggregate server.

#### Why is this the best possible solution? Were any other approaches considered?
The fix itself is a null check and I think that's the only possible option.

The tests I don't love but I couldn't come up with any other option without risky refactoring. They use Robolectric because of `FormDownloader`'s reliance on the `Collect` singleton for dependency injection, for looking up strings and for database access (this class, like many in this code base, has all the concerns). I mocked the actual download of files and tried to make it really clear in the test comments what the tests target.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
I made the mistake of not thinking about this question carefully enough in #3523. This code is involved in the downloading of all forms from any server so that's where the risk is. There are different branches based on whether there is or isn't media attached and both should be verified.

#### Do we need any specific form for testing your changes? If so, please attach one.
Forms on https://opendatakit.appspot.com

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by lognaturel** [comment]
CC @OpenDataNerd, you may have some thoughts on the tests and whether there might be alternate ways to structure them.

**Review by seadowg — APPROVED** [review]
There are some things in the tests I'm not a fan of (that you've pointed out) - the spy usage and this having to use Robolectric. However, I think the test is at the right "level" here and that these nasty parts are just exposing the problems in the objects design. I think this is good to go and is a great candidate for a little clean up work. I'll add an issue!

**Comment by breakbusyloop** [comment]
> you may have some thoughts on the tests and whether there might be alternate ways to structure them.

I added my thoughts to #3538

**Review by grzesiek2010 — APPROVED** [review]

**Comment by mmarciniak90** [comment]
**Tested with success**

Verified on Android: 4.2, 4.4, 5.1, 6.0, 7.0, 8.1, 9.0, 10.0

Central:
- download form without media
- download form with media
- send submission with attachments
- send submission without attachments
- downloading a few forms during at once

Local Aggregate v2.0:
- download form without media
- download form with media
- verified Aggregate which accepts anonymous user and does not accept

Default Aggregate v1.7.4:
- download all available forms
- send submission with attachments
- send submission without attachments

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Pull request merged**
