### PR TITLE
Upgrade to the new Firebase Crashlytics

### LINKED ISSUE #3807: Upgrade to the new Firebase Crashlytics
#### Problem description
The topic from the forum https://forum.getodk.org/t/fixing-leaks-in-collect-app/26137/3 made me thinking what actually fabric is for. I took a look at the documentation and found out that it's needed fro crashlytics but now it's legacy and we can switch to the new [Firebase Crashlytics](https://firebase.google.com/docs/crashlytics/get-started-new-sdk?platform=android) and get rid of fabric.

@lognaturel @seadowg any thoughts pros/cons?

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #3807 

#### What has been done to verify that this works as intended?
Reviewed implemented changes according to the doc: https://firebase.google.com/docs/crashlytics/upgrade-sdk?platform=android

#### Why is this the best possible solution? Were any other approaches considered?
https://firebase.google.com/docs/crashlytics/upgrade-sdk?platform=android

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
it does't require testing.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by lognaturel — APPROVED** [review]
Whoops, good catch upgrading that. Could you please do a quick sanity check and make sure you actually see a crash in the Crashlytics log for debug builds before merging?

**Comment by lognaturel** [comment]
Also, I didn't realize that we track warnings. I think we should exclude them but we can do that for next release.

**Comment by grzesiek2010** [comment]
> Could you please do a quick sanity check and make sure you actually see a crash in the Crashlytics log for debug builds before merging?

I can see something in logs but unfortunately can't test it according to [Test your Firebase Crashlytics implementation](https://firebase.google.com/docs/crashlytics/force-a-crash?platform=android) because it seems outdated and uses old Fabric/Crashlytics.

> Also, I didn't realize that we track warnings. I think we should exclude them but we can do that for next release.

You mean logging only errors right? If so I did that https://github.com/getodk/collect/pull/3841/commits/fe2bbc47b34100529be1e645e02fd54a969fe992

**Comment by grzesiek2010** [comment]
> You mean logging only errors right? If so I did that fe2bbc4

wait wait wait... I agreed but those logs are then visible if we have a crash and might be helpful sometimes so why do you want to get rid of it?

**Comment by grzesiek2010** [comment]
> wait wait wait... I agreed but those logs are then visible if we have a crash and might be helpful sometimes so why do you want to get rid of it?

I removed the last commit to keep logging warning according to what I said. Do you think we should review warning and remove those we don't need in this pr or add as a separate one?

**Comment by lognaturel** [comment]
For context, @grzesiek2010 and I briefly talked about this in a call. I had never used the log view in Crashlytics so that's nice to know about. But there really is a lot of noise in warnings.

> Do you think we should review warning and remove those we don't need in this pr or add as a separate one?

I think it can go into a separate PR.

**Pull request merged**
