### PR TITLE
take out auto-send and auto-delete

### PR DESCRIPTION
**Pull request by grzesiek2010**

### CODE REVIEW

**Comment by lognaturel** [comment]
I would personally remove all of it (getting the values in the form, methods to check if they're turned on in the forms) since we're not sure when we'll be ready to bring the features in and we can always get the code back from history. But if you think this more minimal removal is better we can go that route. It would be good to understand why you prefer this. Thanks!

**Comment by grzesiek2010** [comment]
@lognaturel ok I agree we can remove everything. It's done,

**Comment by mmarciniak90** [comment]
Tested with success. I don't notice regression.
Verified that user is able to auto-send and auto-delete when user selects this option in settings.
Android v4.1, v4.2, v4.4, v5.1, v6.0

**Comment by mmarciniak90** [comment]
@opendatakit-bot unlabel "needs testing"

**Pull request merged**
