### PR TITLE
Resolve issue #511

### PR DESCRIPTION
**Pull request by Bastiantheone**
Replace deprecated methods with a better alternative. Note: This method doesn't include notification bar and window title in the display height.

### CODE REVIEW

**Comment by lognaturel** [comment]
Please give a short summary of the verifications you made to ensure that the UI was not affected.

**Comment by Bastiantheone** [comment]
collect_issue551_screenshot

I put a log.d statement after my change to see if it gives the correct display width and height.

**Comment by Bastiantheone** [comment]
@lognaturel I tested all forms in addition to the above-mentioned testing

**Comment by lognaturel** [comment]
Thank you, @Bastiantheone for doing this so thoroughly and describing how you verified it! Congrats on your first merged pull request and welcome to the project. 🎉👏👏🎉

**Pull request merged**
