### PR TITLE
Rework Osm Widget

### PR DESCRIPTION
**Pull request by SaumiaSinghal**
This PR includes reworking the OSM Widget class, and adding proper test coverage.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
I used `ActivityAvaibility` object in the widget to check for the case when the intent cannot be launched. I have missed the test coverage for some part of the code, like for the try-catch statement when launching an intent. Also, I feel it would be better to show the alert dialog in a fragment.

#### Do we need any specific form for testing your changes? If so, please attach one.
Any form having OSM integration widget, like AllWidgetsForm

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by seadowg** [comment]
@SaumiaSinghal this needs a rebase with master and then we're good to review!

**Review by seadowg — CHANGES_REQUESTED** [review]
As above

**Comment by SaumiaSinghal** [comment]
It is fixed @seadowg

**Comment by seadowg** [comment]
@lognaturel @grzesiek2010 I'm pretty out of the loop on the OSM integration so if either of you have experience there feel free to jump in and assign yourself as a reviewer. Otherwise, I can stick myself back on here.

**Comment by seadowg** [comment]
Coming back to this it looks like this definitely takes a step forward: it adds new tests and moves the widget view definition to XML. I'm going to approve this but happy for @lognaturel or @grzesiek2010 to interject if they notice something seems off. As I said before, this isn't a part of the code I'm very familiar with.

**Review by seadowg — APPROVED** [review]

**Comment by lognaturel** [comment]
Thank you for looking at this @seadowg and for doing it, @SaumiaSinghal. Agreed the high-level changes look good. I think @getodk/testers probably know the most about the OSM widget and how it's supposed to work so good to get it to them.

I'll also file an issue for getting analytics on this functionality.

**Comment by mmarciniak90** [comment]
This issue was quite difficult to test because we noticed crashes of the OpenMapKit app, especially in the `All widgets` form. The crash is also visible in released apps so it required a separate investigation.

When we used another form we were able to receive an answer in Collect -> [buildings_example.xml.txt](https://github.com/getodk/collect/files/6149358/buildings_example.xml.txt)

@SaumiaSinghal, it seems that the only issue is the missing margin for the button. 

|PR|released 1.30.1 | 
|---|---|
Screenshot_20210316-143612|Screenshot_20210316-143659|

@lognaturel should we fix it as a part of this issue or as a separate one? Is it important to merge it as soon as possible?

Tested on devices with Android versions: 7.0, 8.1, 10.0

**Verified cases:**
- added single tag
- added list of tags
- edited tags
- edited submission with tags
- removed response with tags
- sent submission with .osm file to Central
- run prepared automated test
- light and dark mode
- minimization
- rotation

**Comment by lognaturel** [comment]
There's no risk of conflict so addressing the margin in this PR seems like a good idea.

**Comment by kkrawczyk123** [comment]
@getodk-bot unlabel "needs testing"

**Comment by SaumiaSinghal** [comment]
Hi @mmarciniak90! Sorry for replying late. I don't notice the issue of missing margin. I checked on my emulator Android 8, 9. I check on real device with Android 10 as well.
WhatsApp Image 2021-03-29 at 04 53 54

**Comment by mmarciniak90** [comment]
@SaumiaSinghal here is what I found:
* problem is not visible on PR
* problem is not visible on the master branch
* problem **IS VISIBLE** when I rebased with master as suggested by Callum 

Could you try again?

**Comment by SaumiaSinghal** [comment]
@mmarciniak90 yes you are correct, I am able to reproduce the issue on rebasing with master

**Comment by SaumiaSinghal** [comment]
Hi @mmarciniak90! I fixed the issue and rebased the PR with master as well. I added the same padding for other widgets layout as well. I noticed that the margins of other widgets were not uniform. I have checked it for All Widgets form.

**Comment by mmarciniak90** [comment]
@getodk-bot label "needs testing"

**Comment by mmarciniak90** [comment]
**Tested with success**

Verified on Android 7.0, 8.1, 10.0

Verified cases:
- padding for the `Launch OpemMapKit` button
- padding for the `Redo OSM Tagging` button
- light and dark mode
- English and Spanish language
- RTL language
- cases mentioned previously

**Comment by kkrawczyk123** [comment]
Verified also on Androids: 5.1, 7.1 and 9.0.

@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"

**Pull request merged**
