### PR TITLE
#3189 changed the targetSDK version to API 28

### LINKED ISSUE #3189: App updates must target Android 9 (API 28) by November 2019
>Your app currently targets API level 26 and must target at least API level 28 to ensure it is built on the latest APIs optimized for security and performance.
>
>From August 2019, new apps must target at least Android 9.0 (API level 28).
> From November 2019, app updates must target Android 9.0 (API level 28).
> 
> https://developer.android.com/distribute/best-practices/develop/target-sdk.html

### PR DESCRIPTION
**Pull request by anilshatharashi**
Closes #3189

Updated the targetSdkVersion to API 28 in order to support the app updates.

#### What has been done to verify that this works as intended?
Ran the application with the latest targeted version and tested, didn't find any problems with that.

#### Why is this the best possible solution? Were any other approaches considered?
https://developer.android.com/distribute/best-practices/develop/target-sdk.html

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
App can be updated/published without any issues

#### Do we need any specific form for testing your changes? If so, please attach one.
Not really

#### Does this change require updates to documentation? If so, please file an issue here and include the link below.
No

#### Before submitting this PR, please make sure you have:
 run ./gradlew checkAll and confirmed all checks still pass OR confirm CircleCI build passes and run ./gradlew connectedDebugAndroidTest locally.
 
 verified that any code or assets from external sources are properly credited in comments and/or in the about file.
 
 verified that any new UI elements use theme colors. UI Components Style guidelines

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by lognaturel** [comment]
Thanks for taking this on, @anilshatharashi! In parallel, there was some discussion [in the developer Slack](https://slack.opendatakit.org/) about targeting API 29 directly (see [here](https://opendatakit.slack.com/archives/C35ENHA64/p1567462335007100)). Would you be willing to change this PR to do so? The ideal would be to [do an interactive rebase](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History) to change the first commit. It's also ok if you just add another commit that a reviewer can squash.

**Comment by lognaturel** [comment]
I also see that there are still some failing tests. Could you please look into those?

**Comment by seadowg** [comment]
@anilshatharashi it looks like the change to API 28 needs an update to Robolectric as well

**Comment by anilshatharashi** [comment]
Reopening the PR incase if it is agreed to be merged.

**Review by seadowg — CHANGES_REQUESTED** [review]
Hey @anilshatharashi! Would you be able to verify that you've run the exercises in the checkboxes (in the PR description) and then tick them off?

It looks like the recent updates have fixed the Robolectric problems (we've upgraded it). But need to make sure other tests are all passing.

**Comment by grzesiek2010** [comment]
@anilshatharashi 
Thanks for your effort but:
1. We decided to bump the version to 29 to avoid the same work (testing) two times.
2. I was able to find at least one problem so far caused by changing the version so it's not that easy. I'm in the middle of testing and reading the doc.

So thanks again but I'm closing the pr and will try to create a new one soon, your help with testing it will be welcome.

**Pull request closed without merging**
