### PR TITLE
Changed background of AudioButton

### PR DESCRIPTION
**Pull request by rijuldhir**
Solved Issue #577 

Added Background and Aligned AudioButton

### CODE REVIEW

**Comment by grzesiek2010** [comment]
@rijuldhir as you can see @pratikmjoshi was first and wanted to do that. Don't take tickets which aren't yours.

**Comment by rijuldhir** [comment]
@grzesiek2010 
He had not sent PR nor was in progress or Assigned Label on the Issue. So did not knew if he was active or not.
I can close PR if you want.

**Comment by grzesiek2010** [comment]
It's not "In progress" because @paraschadha2052 is waiting for @lognaturel's decision but he asked about it as the first. Yes you should close this pr but keep your changes locally just in case.

**Comment by rijuldhir** [comment]
@grzesiek2010  Closing the PR and keeping the Changes

**Pull request closed without merging**
