### PR TITLE
Islamic calendar

### PR DESCRIPTION
**Pull request by grzesiek2010**
#### What has been done to verify that this works as intended?
I've tested attached forms and forms from #1505 and #1576 

#### Why is this the best possible solution? Were any other approaches considered?
It's a continuation of #1505 and #1576 

#### Are there any risks to merging this code? If so, what are they?
I think it's safe but I've implemented some code refactoring too so it's should be tested by @mmarciniak90 or @kkrawczyk123 

#### Do we need any specific form for testing your changes? If so, please attach one.
[islamic.xml.txt](https://github.com/opendatakit/collect/files/1502035/islamic.xml.txt)

### CODE REVIEW

**Comment by grzesiek2010** [comment]
Other forms for testing to avoid regression:
[coptic.xml.txt](https://github.com/opendatakit/collect/files/1508890/coptic.xml.txt)
[ethiopian.xml.txt](https://github.com/opendatakit/collect/files/1508891/ethiopian.xml.txt)
[gregorian.xml.txt](https://github.com/opendatakit/collect/files/1508892/gregorian.xml.txt)
[islamic.xml.txt](https://github.com/opendatakit/collect/files/1508893/islamic.xml.txt)

**Comment by kkrawczyk123** [comment]
I checked all calendar forms on our devices. I found some issues:
- On Androids 4.2 and 4.1 and islamic calendar form I noticed some misspells in month names:
Muharram without “h”, Safar without “S”, Ramadan without “d”, Dhu al-Hijjah without “H”. One space is displayed in places of missing letters.
- On Androids 7.0, 4.1 and 5.1 and all calendar forms, When I fill form and suddenly minimize an app and then go back to application, I don’t see form which I was filling but main menu of collect, this issue occurs on all pages of all calendars. 
- On Androids 7.0, 6.0, 8.0, 4.4 and 5.1 in all types of calendars, for all pages of form when you choose date, english translations in brackets are not complete. On first page of all forms there is time missing, on MonthYear page there are time and day missing, on Year page there are day month and time missing and on DateTime there is time missing in bracket. 
- On Android 4.1 and gregorian calendar, default time in brackets on all form pages is 00:00:00 and it’s different than on other devices where you can find 12:00:00.

**Comment by kkrawczyk123** [comment]
@opendatakit-bot unlabel "needs testing"

**Comment by kkrawczyk123** [comment]
I'm attaching screenshots of issues described above.

**Comment by grzesiek2010** [comment]
Ok thanks I'm on it.

**Comment by grzesiek2010** [comment]
> On Androids 4.2 and 4.1 and islamic calendar form I noticed some misspells in month names:
> Muharram without “h”, Safar without “S”, Ramadan without “d”, Dhu al-Hijjah without “H”. One space is displayed in places of missing letters.

Fixed.

> On Androids 7.0, 4.1 and 5.1 and all calendar forms, When I fill form and suddenly minimize an app and then go back to application, I don’t see form which I was filling but main menu of collect, this issue occurs on all pages of all calendars.

It's normal Android behavior when you use a device with insufficient memory or you have checked "Don't keep activities option". You will be able to restore everything if you open your blank form again.

> On Androids 7.0, 6.0, 8.0, 4.4 and 5.1 in all types of calendars, for all pages of form when you choose date, english translations in brackets are not complete. On first page of all forms there is time missing, on MonthYear page there are time and day missing, on Year page there are day month and time missing and on DateTime there is time missing in bracket.

It's an expected behavior too. I think you thought it should be visible because it's visible on Android 4. But it shouldn't it's a bug https://github.com/opendatakit/collect/issues/1002

> On Android 4.1 and gregorian calendar, default time in brackets on all form pages is 00:00:00 and it’s different than on other devices where you can find 12:00:00.

I believe you forgot to add am and it was 12:00:00am in fact
00:00 is 12am so it's the same. Could you confirm @kkrawczyk123 ?

**Comment by grzesiek2010** [comment]
@opendatakit-bot unlabel "changes requested"

**Comment by grzesiek2010** [comment]
@opendatakit-bot unlabel "needs review"

**Comment by grzesiek2010** [comment]
@opendatakit-bot label "needs testing"

**Comment by kkrawczyk123** [comment]
All calendars look good now.

**Comment by kkrawczyk123** [comment]
@opendatakit-bot unlabel "needs testing"

**Review by lognaturel — APPROVED** [review]

**Pull request merged**
