### PR TITLE
Refactors FormHierarchyActivity

### LINKED ISSUE #740: Refactor FormHierarchyActivity so FORM_MODE extra isn't needed
`FormHierarchyActivity` was originally designed to display a form's hierarchy and enable form editing. With the introduction of the "View Sent Form" feature, there was a need for a read-only form hierarchy. This was implemented by adding a string extra with key `ApplicationConstants.BundleKeys.FORM_MODE` which can have values `ApplicationConstants.FormModes.VIEW_SENT` or `ApplicationConstants.FormModes.EDIT_SAVED`. 

This is not great class design and had unintended consequences (#535). This design should be rethought so that the constants can be removed. There should probably be separate activities for a form hierarchy that can be edited and a read-only form hierarchy.

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Fixes #740

### CODE REVIEW

**Comment by shobhitagarwal1612** [comment]
@lognaturel Please review

**Comment by lognaturel** [comment]
@shobhitagarwal1612 I must admit I'm not quite sure why this has been sitting for so long! I think between there being no description and the other form hierarchy pull request it got lost in the shuffle.

Please fix the small merge conflicts and we can get this through a round of testing.

**Comment by shobhitagarwal1612** [comment]
@lognaturel Done

**Comment by mmarciniak90** [comment]
@shobhitagarwal1612 Could you tell me what behaviors may have changed?
What should be tested more carefully?

**Comment by shobhitagarwal1612** [comment]
`Fill Blank Form`, `Edit Saved Form`, S̶e̶n̶d̶ ̶F̶i̶n̶a̶l̶i̶z̶e̶d̶ ̶F̶o̶r̶m̶ - Should allow editing the forms
`View Sent Form` - Should not allow editing the forms

**Comment by mmarciniak90** [comment]
`Send Finalized Form` does not give an opportunity to edit a form. 
@shobhitagarwal1612, I suppose it is mistake in you comment, please confirm that.

**Comment by shobhitagarwal1612** [comment]
@mmarciniak90 Yes, it was a mistake in my comment. Thank you for pointing it out :+1: 
I've edited the comment

**Comment by mmarciniak90** [comment]
**Tested with success!**
Verified on Android: 4.1, 4.2, 4.4, 5.1, 6.0, 7.0, 8.0
Regression was not noticed. 
Merging this issue allows us to test this changes also during testing other issues.

**Comment by mmarciniak90** [comment]
@opendatakit-bot unlabel "needs testing"

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
@shobhitagarwal1612 the best things are worth the wait, right? 🙃

**Comment by shobhitagarwal1612** [comment]
@lognaturel Well said :smile:

**Pull request merged**
