### PR TITLE
Performance improvements in SelectOneWidget

### LINKED ISSUE #2494: Long lists of choices take a long time to render
#### Problem description
If the list of choices in a select one or select multiple question is long, it takes a long time to display that question because all `TextView`s are computed and held in memory. 

#### Steps to reproduce the problem
Load a form with a select question that has a long list of choices. These can come from a static choice list, a dynamic choice list or an external DB (using "search/pulldata" or "external itemsets").

#### Expected behavior
Views are only built for the currently-displayed items and a few before and after.

#### Other information 
As @shobhitagarwal1612 described in https://github.com/opendatakit/collect/issues/1254, this is probably a compelling place to use a `RecyclerView`.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #2494 

#### What has been done to verify that this works as intended?
I tested ths solution with a big dataset @lognaturel shared with me and using a form with media files like:
https://ufile.io/1t8ki (too big to attach here directly)

#### Why is this the best possible solution? Were any other approaches considered?
My first idea was to create a list of choices using [RecyclerView](https://developer.android.com/reference/android/support/v7/widget/RecyclerView). I created a sample app to test more than 1k items and it was promising (everything worked well). When I implemented changes in Collect I noticed the `RecyclerView` works slowly not like in a sample app I created. After some investigation finally, I found out it's because of `ODKView` which extends `ScrollView`. That means we would add `RecyclerView` inside `ScrollView` what doesn't work well. I even created a sample app to compare displaying the same dataset in `RecyclerView` which is inside `FrameLayout` and `RecyclerView` which is inside `ScrollView`: https://github.com/grzesiek2010/RecyclerViewTest. We can't resign from our scrollable `ODKView` and even if there is any other solution it would require a big refactoring. That's why I decided to find another solution. I analyzed the code and found out that creating media layouts takes the most resources (time). We don't always need `MediaLayout` so if we have a simple selectOne question without any media we can use a simple (and faster) approach (simpler layout). I guess if someone uses such a big dataset (more than 1k items) it's rather without any media so my solution should be enough. it's not a super fast solution but I noticed a big improvement: 
```
Tested on Samsung Galaxy S4 Android 5
master branch: ~50s needed to load all items
this branch ~20s needed
```

#### Are there any risks to merging this code? If so, what are they?
Yes, SelectOne widgets should be tested to avoid any regression.

#### Do we need any specific form for testing your changes? If so, please attach one.
Forms attached above.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew pmd checkstyle lintDebug spotbugsDebug` and confirmed all checks still pass.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by lognaturel** [comment]
Nice! 

Our baseline should be before the change in f6087e3. The user form that @grzesiek2010 mentioned (can't be shared publicly unfortunately) takes about 11s before f6087e3 on my Galaxy Tab A. It takes about 22s with this change. That's better than `master` (about 35s for me) but still slower than baseline. Does that match your experience, @grzesiek2010?

The `ScrollView` can be directly swapped out for a `NestedScrollView`. Did you try that and if so, what might be some downsides of that approach? Which of the suggestions in posts like https://stackoverflow.com/questions/27083091/recyclerview-inside-scrollview-is-not-working did you try?

**Comment by grzesiek2010** [comment]
> It takes about 22s with this change. That's better than master (about 35s for me) but still slower than baseline. Does that match your experience, @grzesiek2010?

my experience is:
```
before f6087e3 15s
this branch 20s
master branch 50s
```

so yes it's not ideal and I would say that even 15s visible before f6087e3 is too much.

> The ScrollView can be directly swapped out for a NestedScrollView. Did you try that and if so, what might be some downsides of that approach?

All those topics on StackOverflow are about problems with scrolling (I didn't even tested scrolling and probably `NestedScrollView` would be a solution) the problem is it works really slow (I mean I have to wait a long time to load the layout). I tried `NestedScrollView` and it's the same slow performance.

The ideal solution would be to create a separate widget (which could be used only one per page - without any additional ScrollView). I mean a widget for many items like 500+ which should be simpler without any media elements (I don't think anyone would need to use media with such a long list).

**Comment by lognaturel** [comment]
The problem with the slowness is that the scroll views have infinite height and so when the recycleview matches that, it has to load the full list. I thought there were some ideas about addressing that in the thread I linked to but maybe I linked to the wrong one!

What I have in mind is to cap the height of the `RecyclerView` if the number of elements to render is high. See a quick and dirty example at https://github.com/grzesiek2010/RecyclerViewTest/compare/master...lognaturel:cap-long-list. 

I picked 80% of the screen height to leave space for other things that may be in the scroll view like a label and perhaps other elements in a field list but I'm not exactly sure how it would behave if there's a lot more content in the scrollview. That would be the next thing to check. I believe that when the user swipes in that 20% space at the bottom, the whole scrollview will scroll. Perhaps it would be good to do the same thing as with the image map widget where there's some space left on the right side for the user to scroll the scrollview.

This should load instantly with media and lists of crazy long lengths without needing to introduce yet another widget type. Hopefully this gives you some good ideas to try out!

**Comment by grzesiek2010** [comment]
Ok I'll try it.

**Comment by grzesiek2010** [comment]
Closed in favor of https://github.com/opendatakit/collect/pull/2513

**Pull request closed without merging**
