### PR TITLE
Use Android's SQLiteOpenHelper instead of custom ODKSQLiteOpenHelper

### LINKED ISSUE #1334: ODKSQLiteOpenHelper - why do we need this class?
#### Problem description
Currently we use custom [ODKSQLiteOpenHelper](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/database/ODKSQLiteOpenHelper.java) instead of Android's SQLiteOpenHelper. It would be good to know why as our class might be faulty (as we can see in this case https://github.com/opendatakit/collect/issues/1325)

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #1334 

#### What has been done to verify that this works as intended?
I can confirm that databases are created in the same locations. I've used simple forms, [external itemsets](https://opendatakit.org/help/form-design/external-itemsets/) and [pre-loading form](https://opendatakit.org/help/form-design/data-preloading/) to test it.

I've tested instances database upgrade installing my version on collect v1.4.14 

and I've investigate our old ODKSQLiteOpenHelper class - looks like there is nothing special we need. I think someone created this class to create database files in various locations now I can achieve it using [DatabaseContext class](https://github.com/opendatakit/collect/pull/1363/files#diff-6ad889557126ddaeea10e8427652dcd7)

#### Why is this the best possible solution? Were any other approaches considered?
Now we use Android's SQLiteOpenHelper class so it should be the safest way for us.

#### Are there any risks to merging this code? If so, what are they?
I can't see any possible problems. I've tested it pretty carefully I think but it would be good if someone else can do the same @mmarciniak90 ideally.

I would vote for merging it just after the upcoming release, then we have much time to catch any possible bugs and @mmarciniak90 should be able to test it after her vacation.

### CODE REVIEW

**Comment by lognaturel** [comment]
I think @mmarciniak90 is enjoying some time away from the computer right now. This is a somewhat significant change and there's no reason to rush it so let's wait to merge until she can come back to verify it or someone can do a very detailed check like she usually does.

**Comment by mmarciniak90** [comment]
Tested with success. I did not notice regression. 
I focused on databases:
* instance.db in /odk/metadata
* forms.db in /odk/metadata
* hhplotdetails.db in /forms/[FORM_NAME]-media (pre-loading form)
* itemset.db in /odk/metadata (external itemsets)

All databases were created in the correct directory.
I verified on Android 4.1, 4.4, 5.1, 6.0, 7.0.

**Comment by grzesiek2010** [comment]
Thanks @mmarciniak90 ! @lognaturel let's merge it. It's related to almost everything so it will allow us to test these changes on a daily basis.

**Comment by lognaturel** [comment]
Awesome, thanks both! Totally agreed about merging ASAP.

**Review by lognaturel — APPROVED** [review]

**Comment by mmarciniak90** [comment]
@opendatakit-bot unlabel "needs testing"

**Pull request merged**
