### PR TITLE
Check whether Google play services are installed or not

### LINKED ISSUE #490: Check whether Google play services are installed or not
#### Problem description
Currently the app doesn't check whether the play services of the required version are installed or not before trying to access any concerned google API like Google Maps, Google Sheets or Google Drive API. Right now the app doesn't give any hint to the user as to what is happening when services are not found

#### Expected behavior
To show a dialog box that the required services are not found and a option to update to the latest version

@lognaturel @yanokwa @Dvik Any thoughts?

### PR DESCRIPTION
**Pull request by grzesiek2010**
This PR is in reference to resolve #490 

Most of required changes were already implemented so I've added some and refactored the code. 
The code in PlayServicesUtil was duplicated so I've fixed that.
I've implemented changes to avoid starting activities and then checking play services (it didn't make sense). Now we check that before we start another activity.

### CODE REVIEW

**Comment by lognaturel** [comment]
One big question is whether the mapping widgets can still be useful without Play Services. We know getting location does require it but I think it should be possible to place a marker/shape on a map without location being known. Perhaps the check for Play Services should only be done when the user taps the button to go to the current location.

The thing to check is whether in previously-released versions of Collect it was possible to launch and use mapping activities without Play Services. Is it the case with Google Maps too or just OSM? Then it can be verified that it would crash when the "go to my location" button was tapped.

**Comment by shobhitagarwal1612** [comment]
Google maps cannot be used without the required google play services since the google maps are a part of it. But osm doesn't require google play services.

**Comment by grzesiek2010** [comment]
@shobhitagarwal1612 is right I can confirm. When I try to use mapping widgets I get:
screenshot_2017-03-21-17-38-33
screenshot_2017-03-21-17-38-46

but my current changes block osm as well so I have to fix that.

**Comment by grzesiek2010** [comment]
@lognaturel I refactored PlayServicesUtil class as you asked me and added required changes to block only google maps when there is something wrong with play services so now OSM works well.

I noticed one problem: "Update" option doesn't work on emulator. Maybe because I have not installed the "Play store" app on emulator... I think then web browser should be used in that case but it doesn't work.

**EDIT:**
Yes I can confirm I removed "Play store" app from my device and now that option doesn't work on this real device.

**Comment by lognaturel** [comment]
Great, @grzesiek2010! We can file a separate issue to make sure that every time Play Store is launched, there's a check to make sure the app is installed and if not, launches it from a browser. I think that was already done for one of the checks so the issue should have a reference to that.

If you have a moment to fix the merge conflicts, we'll be ready to merge!

**Comment by shobhitagarwal1612** [comment]
@grzesiek2010  `GoogleDriveActivity` also accesses google play services (introduced in #722)

**Comment by grzesiek2010** [comment]
@shobhitagarwal1612 yes it's checked here https://github.com/opendatakit/collect/pull/726/files#diff-4843e9d988e60283c4c8967d83b05c0bR257

**Comment by grzesiek2010** [comment]
@shobhitagarwal1612 ahh you've implemented changes and now we don't have to click on "My Drive" button I have to check it with your changes.

**Comment by grzesiek2010** [comment]
@lognaturel I think it's ready please review.

**Pull request merged**
