### PR TITLE
Removed unused ic_menu_forward.png icon

### PR DESCRIPTION
**Pull request by grzesiek2010**
#### Why is this the best possible solution? Were any other approaches considered?
I just removed completely unused icon.

#### Are there any risks to merging this code? If so, what are they?
No.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew pmd checkstyle lint findbugs` and confirmed all checks still pass.
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

Google Drive list just should be tested for regression.

### CODE REVIEW

**Review by huangyz0918 — APPROVED** [review]

**Comment by huangyz0918** [comment]
@opendatakit-bot label “needs testing”

**Comment by huangyz0918** [comment]
@opendatakit-bot label "needs testing"

**Comment by mmarciniak90** [comment]
**Tested with success!**

Verified on Android: 4.1, 4.2, 4.4, 5.1, 6.0, 7.0
`ic_menu_forward.png` files are not available in collect files.
I did not notice regression on `Draw widget`

@opendatakit-bot label "behavior verified"
@opendatakit-bot unlabel "needs testing"

**Comment by lognaturel** [comment]
For those who may be wondering where this was used and why removing it is safe, the layout is used in listing Google Drive contents. The arrow was used as a placeholder and was immediately replaced by either a download icon or a folder icon in `FileArrayAdapter`.

Thanks for noticing this, @grzesiek2010 and for the verification, @huangyz0918! 🎉

**Review by lognaturel — APPROVED** [review]

**Pull request merged**
