### PR TITLE
Make sure trunk version is blank rather than null when provided to forms

### LINKED ISSUE #6336: Crash on opening the map (to select an entity) after finalizing a registration form and going to follow-up form
#### ODK Collect version
the master version 3669ada1310c97d2f8112eb6439205ae2442c65e
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
If a registration form is finalized and after that in a follow-up form the map to select an entity is opened, there's a crash.
followUPRegCrash

#### Steps to reproduce the problem
1. Download a project with Trees registration form (containing entities) and Trees follow-up form.
2. Go to the Trees registration form and finalize/send a new entity.
3. Go to the Trees follow-up form and tap "Select place".

### PR DESCRIPTION
**Pull request by seadowg**
Closes #6336

#### Before submitting this PR, please make sure you have:
- [ ] added or modified tests for any new or changed behavior
- [ ] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [ ] added a comment above any new strings describing it for translators
- [ ] added any new strings with date formatting to `DateFormatsTest`
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by seadowg** [comment]
@lognaturel does this change make sense to you? I'm always very unclear on if a `TreeElement` can have a `null` value or not. For example, for `<blah></blah>` would the value be `StringData("")` or `null`?

**Comment by lognaturel** [comment]
A form definition with `<blah></blah>` will result in a `TreeElement` with a `null` value. See https://github.com/getodk/javarosa/blob/8a22ede18b1ee4284be9fd6c29a55bcbadc75a70/src/main/java/org/javarosa/core/model/data/StringData.java#L55

But this is an attribute value? Where's the `getDisplayText` call? Can it be fixed on that end instead?

**Comment by seadowg** [comment]
> But this is an attribute value?

Not in this situation. This is where we're creating the `__trunkVersion` child element for the entity's `item` in the secondary instance.

> Where's the getDisplayText call? Can it be fixed on that end instead?

It's in [`SelectChoice#getAddditionalChildren`](https://github.com/getodk/javarosa/blob/8a22ede18b1ee4284be9fd6c29a55bcbadc75a70/src/main/java/org/javarosa/core/model/SelectChoice.java#L137). Maybe that code needs fixed instead to allow for children with no value? I've actually just reproduced the crash by add `<blah></blah>` to a form with an internal instance which is a little easier to reason about. I'm guessing this hasn't come up as it looks like CSV and GeoJSON external instances never produce child elements with no value (they set ` UncastData("")` instead).

**Comment by lognaturel** [comment]
> This is where we're creating the __trunkVersion child element for the entity's item in the secondary instance.

Right, of course.

>  I've actually just reproduced the crash by add <blah></blah> to a form with an internal instance

Very interesting! I agree this makes it feel like https://github.com/getodk/javarosa/blob/8a22ede18b1ee4284be9fd6c29a55bcbadc75a70/src/main/java/org/javarosa/core/model/SelectChoice.java#L146 should be updated so that if `getValue` is null then "" is used as the value in the Pair.

**Pull request closed without merging**
