### PR TITLE
Remove .DS_Store files

### PR DESCRIPTION
**Pull request by adithya321**

### CODE REVIEW

**Comment by nribeka** [comment]
Can you also check if this file is in the git ignore list too or any pattern there that's excluding this file? If not, probably good idea to add it to the git ignore list.

**Comment by yanokwa** [comment]
@adithya321 I know this seems minor, but I'm really glad you sent this in!

I agree with @nribeka that we should have a better .gitgnore. I think https://github.com/github/gitignore/blob/master/Android.gitignore might be a good place to start.

**Comment by adithya321** [comment]
@nribeka @yanokwa 
.DS_Store is already in the gitignore list [https://github.com/opendatakit/collect/blob/master/.gitignore](https://github.com/opendatakit/collect/blob/master/.gitignore). 
The files must have been added before ignoring them.

**Comment by lognaturel** [comment]
@adithya321, @yanokwa is correct that there are some improvements to be made to the .gitignore. If you'd like to take that on, please file an issue and say you're working on it!

**Comment by adithya321** [comment]
@lognaturel @yanokwa @nribeka 
I have filed issue #567 [Improve .gitignore to share settings](https://github.com/opendatakit/collect/issues/567). I would like to hear your thoughts about it.

**Pull request merged**
