### PR TITLE
Added background for AudioButton

### LINKED ISSUE #577: Audio button has no background
#### Software and hardware versions 
Current master branch

#### Problem description
Audio button has no background.

#### Steps to reproduce the problem
1. Open "sample" form.
2. Go to the first question

#### Expected behavior
Audio button should look like before.

#### Other information 
It's coused by changes from #525:
[compileSdkVersion](https://github.com/opendatakit/collect/pull/525/files#diff-fa0f36229667501896e9f29c3a2a4b35R60)
[AudioButton](https://github.com/opendatakit/collect/pull/525/files#diff-ce9802d4c0f435bd3f26034d56b61e95R39)
**BEFORE:**
before
**NOW:**
now

@lognaturel you can mark this issue as "quick win".

### PR DESCRIPTION
**Pull request by pratikmjoshi**
Fixes #577 
screenshot_20170314-193046

### CODE REVIEW

**Comment by lokeshkvn** [comment]
@pratikmjoshi Can you add Screenshot for reference or apk file so that we can test and verify ☺️ .

**Comment by shobhitagarwal1612** [comment]
@lokeshkvn You can clone the branch `audiobutton` from @pratikmjoshi's repo  `https://github.com/pratikmjoshi/collect.git` locally and test it

**Comment by grzesiek2010** [comment]
@pratikmjoshi I think it's wrong that change was required and you just changed it back. Please try to build your project on CircleCI and let us now if everything is ok I guess it isn't.

**Comment by pratikmjoshi** [comment]
@lokeshkvn Yes, just updated.
@grzesiek2010 I'm sorry I didn't get you. The app is running fine on my phone with the change. Do you want me to keep it as an AppCompatImageButton, and create a background for it? If so, I can do so, but I'll have to do the same for the other button(play) as well.

**Comment by grzesiek2010** [comment]
@pratikmjoshi I know you can use this code (install on your device) but can't you se the message?:
> this custom view should extend android.support.v7.widget.AppCompatImageButton instead...

You can use: `./gradlew build` command to see that you can't build the code with this change.
As I said you should setup CircleCI also. Look at other prs eg: https://github.com/opendatakit/collect/pull/458 there you can see 

> This branch has no conflicts with the base branch 

and also:

> All checks have passed

**Comment by pratikmjoshi** [comment]
@grzesiek2010 Ahh yes, I noticed. Actually I had initially kept AudioButton as AppCompatImageButton and added a background, but it was looking different than the VideoButton. I think its because VideoButton was an ImageButton and not an AppCompatImageButton
Ive made some changes. I've kept AudioButton as AppCompatImageButton, and I've added a background. In addition to that, I've made VideoButton as AppCompatImageButton and added a background to that as well. The change is shown below:
screenshot_20170314-201636
If this is ok, then I'll send a PR right away.

**Pull request closed without merging**
