### PR TITLE
Fixed distorted buttons

### LINKED ISSUE #3472: RadioButtons/CheckBoxes are distorted
#### Software and hardware versions 
Current master branch

#### Problem description
This is what I see on Android 5.1 Samsung Galaxy S4:
Screenshot_2019-11-26-15-07-25
Screenshot_2019-11-26-15-07-38

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #3472 

#### What has been done to verify that this works as intended?
I tested the solution on the same device I noticed the problem. Also I used emulators to check it on different android versions.

#### Why is this the best possible solution? Were any other approaches considered?
It's a trick but it seems to fix the problem. I can't be sure if it's a perfect solution but the current one which turned out to be faulty is also a trick so we should test it on as many devices as possible and merge this one if it turns out to be better.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
We should just test questions like:
- select_one
- select_multiple
- trigger

nothing else should be affected.

#### Do we need any specific form for testing your changes? If so, please attach one.
Any form with select_one/select_multiple/trigger questions so All widgets form for example.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by grzesiek2010** [comment]
@seadowg what do you think?

**Review by seadowg — CHANGES_REQUESTED** [review]
I was initially so excited that this worked. I had tried drawable padding but I don't think I'd tried explicitly set the drawableLeft/Start. Annoyingly on API 19 and below I'm seeing this:

Screenshot_1574876255

I still like it more as a solution though (it doesn't cause the ripple effect to be off center) so I think it'd make sense to still use this instead but just only for API 21+. 

Of course if you can get rid of that double radio button that would be even better! I had a look at removing `drawableStart` and switching the button back to a `RadioButton` (rather than `AppCompatRadioButton`) but no joy. I don't understand why the `android:button="@null"` isn't working.

**Comment by grzesiek2010** [comment]
Ahh it is the same problem like #3150 I will try to fix it

**Comment by grzesiek2010** [comment]
@seadowg the problem with Android 4 is fixed.

**Comment by seadowg** [comment]
Urgh. Using `buttonCompat` seems so obvious with the benefit of hindsight. Amazing!

I think we should QA this on a few different Android versions just to check we've got this nailed down.

**Review by seadowg — APPROVED** [review]

**Comment by kkrawczyk123** [comment]
**Tested withs success**
Verified on Androids: 4.2, 4.4, 5.1, 6.0, 7.1, 8.1, 9..0 and 10.

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Pull request merged**
