### PR TITLE
Update app after resetting settings

### LINKED ISSUE #1067: Update app after resetting settings
#### Software and hardware versions 
Collect v1.7.0-beta-3

#### Problem description
The app isn't updated after settings are reset so it may not show the actual state of things.

#### Steps to reproduce the problem
1. Uncheck a couple of options in admin settings
1. Reset all settings from admin settings
1. Note that the options that were unchecked are still unchecked even though internally they are now set to true

===

1. Change the language in general settings
1. Reset all settings from admin settings
1. Note that the language doesn't change until the app is quit and restarted

#### Expected behavior
Admin settings and/or language should be updated.

#### Other information 
#1058 may be a nice example to look at. The challenge with this one is that I think we do want to show the result of the different reset components so going back to the landing screen may not be the best thing to do.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #1067

#### What has been done to verify that this works as intended?
I tested resetting settings and the behavior after reading a QR code since I touched that part of code too.

#### Why is this the best possible solution? Were any other approaches considered?
It uses the same approach like in #1058 

#### Are there any risks to merging this code? If so, what are they?
Potential regression in behavior after reading a QR code.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

### CODE REVIEW

**Comment by mmarciniak90** [comment]
@grzesiek2010 language is not updated after resetting settings on Android 8.0.

**Comment by grzesiek2010** [comment]
ok, I'm on it.

**Comment by grzesiek2010** [comment]
@mmarciniak90 
I've just fixed the issue you found.

**Comment by mmarciniak90** [comment]
**Tested with success!**
Verified on Android: 4.1, 4.2, 4.4, 5.1, 6.0, 8.0
Verified cases: 
* resetting settings changed in General Settings : language and other options
* resetting settings changed in Admin Settings
* resetting settings previously set by scanned QR code

@opendatakit-bot unlabel "needs testing"

**Review by lognaturel — APPROVED** [review]

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
👍

93b0a45 would have been nice for the commit message to describe the bug and the details to explain the fix.

**Pull request merged**
