### PR TITLE
Robolectric tests are added for the method downloadFormList in FormDo…

### PR DESCRIPTION
**Pull request by sanovikov71**
…wnloadList.

Change-Id: I4577550bded9e15f7ad37588632950f41dfb141c

### CODE REVIEW

**Comment by sanovikov71** [comment]
Hi, I have added several tests that check correct handling of AsyncTask in downloadFormListMethod.

**Comment by lognaturel** [comment]
These are some really good tests to add, @sanovikov71! I would be very interested in some feedback from @yadav-rahul @alxndrsn @grzesiek2010 if you have some time to provide it (and of course, anyone else interested in testing). In particular, the use of the dummy class seems good to me but I don't have much experience with that kind of approach.

**Comment by alxndrsn** [comment]
Hi @sanovikov71, a couple of suggestions for improving these tests:

* try not to modify the production code when writing the tests
* make the aim of each test method clear in its name

It may well be that `FormDownloadList` is not easily exercisable as a unit test.

**Comment by sanovikov71** [comment]
I believe that this PR can be postponed a bit, because it contains lots of changes in production code. It looks that there are other parts of code that can be unit tested easier without unnecessary code complication, for example, AsyncTasks.

**Comment by lognaturel** [comment]
Thanks @sanovikov71, I think that makes sense. If you don't mind, do keep the branch in your fork so that we may all refer to it as we get a chance to make further progress on adding tests. I'll close the pr for now.

**Pull request closed without merging**
