### PR TITLE
Refactored Geo widgets.

### PR DESCRIPTION
**Pull request by grzesiek2010**
#### What has been done to verify that this works as intended?
I added automated tests and also tested implemented changes manually.

#### Why is this the best possible solution? Were any other approaches considered?
I noticed that three geo widgets (GeoPoint, GeoTrace, and GeoShape) have a lot in common and their code is duplicated so I created one base class when I moved the duplicated code.
Then I created a utility class to move the code not related to UI from widgets and added automated tests for factored out methods.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Tested geo widgets from AllWIdgets form would be enough. We've just released v1.24 so we will have a lot of time to test it on a daily basis.

#### Do we need any specific form for testing your changes? If so, please attach one.
AllWidgets form is ok.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by lognaturel** [comment]
Would be great to have a quick talk through things like this that aren't prioritized for a release so we know how it fits in with other lines of work. In general, it's fantastic to reduce duplication and clean things up but we should just make sure someone isn't planning to do more in that code in the short to medium term. I've tagged @zestyping for review since he was most recently here and will likely be circling back to more related functionality soon.

**Comment by grzesiek2010** [comment]
Yes, I see your point of view and generally, agree that I should file an issue firs and discuss it. I'm trying to stick to priorities and do things like this as rarely as possible.

**Comment by zestyping** [comment]
Hi @grzesiek2010 ! I just saw this.  Thanks for tagging me in, @lognaturel !  I'll try to have a look at this after I've drafted the design doc we talked about.

**Review by zestyping — APPROVED** [review]
This all looks pretty reasonable to me!

**Comment by lognaturel** [comment]
I agree. But oh no, I got a little too excited to see @zestyping's approval. 🤦🏻‍♀️ @opendatakit/testers please take a look and file any issues you may find.

**Comment by mmarciniak90** [comment]
**Tested with success**

Verified cases from regression checklist for GeoPoint, Geotrace, and Geoshape
Verified on Android: 4.2, 4.4, 5.1, 6.0, 7.0, 8.1, 9.0, 10.0

Noticed only #3442 

@opendatakit-bot unlabel "needst testing"
@opendatakit-bot label "behavior verified"

**Comment by mmarciniak90** [comment]
@opendatakit-bot unlabel "needs testing"

**Pull request merged**
