### PR TITLE
Adds dimens.xml

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
This PR is in reference to add dimens.xml so that we can replace hardcoded values with these values.

### CODE REVIEW

**Comment by lognaturel** [comment]
light_blue -> tint_color is a fantastic change. In general, using names that describe the function of the thing it names is awesome! (black / white is probably fine unless we think they may be used in a way in which it would make sense to change all things black to another color, for example.)

As I understand it, some of the values in `dimens.xml` are used but most are not yet and will be in the future. Am I getting this right?

**Comment by shobhitagarwal1612** [comment]
> As I understand it, some of the values in dimens.xml are used but most are not yet and will be in the future. Am I getting this right?

@lognaturel Yes, you are right. These values aren't being used right now. I thought if we could have a common agreement over how the values would look like then we can merge this and then use these values in the whole app in many separate PRs just like we did for `checkstyle` and `lint`. How does this sound to you?

**Comment by lognaturel** [comment]
Sounds perfect, @shobhitagarwal1612!

@mmarciniak90 I guess the only thing to check then is the color name change.

**Comment by shobhitagarwal1612** [comment]
name of resource `black` can be changed to `primaryTextColor` as it is being used mostly as a text color. And for places using color black for other things like background can use the same color resource `black`.

**Comment by lognaturel** [comment]
YES! `primaryTextColor` is great.

**Comment by shobhitagarwal1612** [comment]
@lognaturel Done

**Comment by lognaturel** [comment]
@shobhitagarwal1612 I'm not quite clear on why this is failing. Can you please try running it again?

**Comment by shobhitagarwal1612** [comment]
@lognaturel It is passing now

**Pull request merged**
