### PR TITLE
Override intent theme to choose google account.

### LINKED ISSUE #1626: Change Google account selection dialog to match app theme
The account selection dialogs use the dark theme.

Screenshots from @mmarciniak90 [here](https://github.com/opendatakit/collect/pull/1612#issuecomment-343869649):

| Dialog before fix | Dialog on Get Blank Form view | Dialog after fix |
| ------------- | ------------- | ------------- |
| before |  getblankform | after |

The first answer from https://stackoverflow.com/a/32955986/137744 seems like the way to go.

### PR DESCRIPTION
**Pull request by akshay-ap**
Closes #1626

#### What has been done to verify that this works as intended?
Tested manually.
#### Are there any risks to merging this code? If so, what are they?
No.

### CODE REVIEW

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
Thanks, @akshay-ap! Works great on my Moto G4, API 24. I've added the "needs testing" label so we can get verification on lower API levels.

**Comment by mmarciniak90** [comment]
'Choose an account' dialog is still dark when user opens 'Get Blank Form' view.



@lognaturel Do you also agree that both dialogs should be consistent?

**Comment by mmarciniak90** [comment]
@opendatakit-bot unlabel "needs testing"

**Comment by akshay-ap** [comment]
I will add another commit for this too.

**Comment by akshay-ap** [comment]
added PR #1644 to make changes at other 2 uses of Google account selection dialog.

**Comment by mmarciniak90** [comment]
Tested as a part of #1644 
Tested on Android 4.1, 4.2, 4.4, 5.1, 6.0, 7.0

|Google Sheets Settings | Get Blank Form | Send Finalized Form|
| --- | --- | --- |
| screenshot_2017-11-17-09-25-15 | screenshot_2017-11-17-09-25-24 | screenshot_2017-11-17-09-25-41 |

@opendatakit-bot unlabel "needs testing"

**Comment by lognaturel** [comment]
Replaced by #1644.

**Pull request closed without merging**
