### PR TITLE
Fixed issue #538: If credentials are invalid tell the user

### PR DESCRIPTION
**Pull request by Midhun07**
Changed the Alert Dialog message, to indicate the proper problem.

### CODE REVIEW

**Comment by lognaturel** [comment]
Thank you, @Midhun07! 

I think the name of the server should be included in the message because users could have credentials for multiple servers and they shouldn't have to go back to settings to see what server they should be connecting to. @nribeka @yanokwa what do you think?

**Comment by Midhun07** [comment]
@lognaturel Thank you for pointing that out. I shall correct that and will resubmit the patch.

**Comment by Midhun07** [comment]
@lognaturel i have added the server name in the dialog message. Please check.

**Comment by lognaturel** [comment]
@wonderchook @Midhun07 One thing I hadn't considered is that there is no difference between the first time the user sees the auth dialog and subsequent times. I think that's why the message was so generic.

With this change, the message will always be "Invalid username or password for server: %s", even the first time the user sees the dialog. I think that makes sense and am happy with the change -- I think of it as values from the general settings being incorrect.

@wonderchook @yanokwa Do you think this is the right message?

**Comment by yanokwa** [comment]
It's a little confusing, but I think it works.

**Comment by Midhun07** [comment]
@lognaturel @yanokwa yes, since the app pops that dialog only when there is any mismatch in user's password or username, in both send form and get form. Hence it's just the message on the alert dialog that needed to be changed.

**Comment by Midhun07** [comment]
So, is this change ready to be merged?

**Comment by lognaturel** [comment]
@wonderchook let us know what you think when you get a chance. If you have alternate solutions, please either re-open the issue or file a new one!

**Pull request merged**
