### PR TITLE
Updated dependencies that do not need Play Services Update (Fixed #1990)

### LINKED ISSUE #1990: Update dependencies that don't need Play Services update
Several dependencies are now out of date. See `build.gradle` in AndroidStudio to see them highlighted. 

All dependencies that can be updated should be. Because Play Services is a big download, it should not be updated at this time. That means dependencies such as `firebase-core` can't be updated immediately.

Other dependency updates may have issues with them so it will be important to verify that the updates work.

### PR DESCRIPTION
**Pull request by arundhatigupta**
Updated several outdated dependencies, that do not require Play Services
update, in build.gradle. Dependencies requiring Play Services update have
not been updated in this commit as it is a big download and, as suggested,
it should not be updated at this time.

Closes #1990 

#### What has been done to verify that this works as intended?

Cleaned the project and tested it on a physical device. 
Device used [Xiaomi Redmi Note 4 ; Android 7.0 API24]

#### Why is this the best possible solution? Were any other approaches considered?

The simplest possible way was to update the outdated versions to new versions.

#### Are there any risks to merging this code? If so, what are they?

No, as per my understanding.

#### Do we need any specific form for testing your changes? If so, please attach one.

None, as per my understanding.

### CODE REVIEW

**Comment by lognaturel** [comment]
It looks like you upgraded some of the testing dependencies but didn't verify that the tests still pass. You can run unit tests with the `testDebugUnitTest` Gradle task (`./gradlew testDebugUnitTest` at the command line or from Android Studio) and integration tests with the `connectedDebugAndroidTest` task. Please take a look at those and either see if you can quickly fix the problems caused by the updates or if not, please don't upgrade those dependencies in this PR and file a separate issue to upgrade each one that will need to be handled separately.

**Comment by shobhitagarwal1612** [comment]
I think the culprit is `mockito-core`

**Comment by arundhatigupta** [comment]
@lognaturel  I will do the same as you suggested. :)
@shobhitagarwal1612 Yes, earlier there was an issue with the mockito-core when I had updated that dependency. WIll try to fix it soon.

**Comment by arundhatigupta** [comment]
@lognaturel  Please review this PR. :)
Updating test dependencies is leading to failed tests. Should I go ahead and open a separate issue for updating test dependencies?

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
>  Should I go ahead and open a separate issue for updating test dependencies?

Yes, please do!

**Pull request merged**
