### PR TITLE
issue#477

### PR DESCRIPTION
**Pull request by SIMRAN1**
changes made

### CODE REVIEW

**Comment by lognaturel** [comment]
Great! Now that you have abstractions around the regular expressions, you should be doing your tests through the abstractions. In other words, you want to test `isValidGoogleSheetsString`, not the regular expression that it uses. That means that if someone needs to change how the check on a Google Sheet string is done, your tests will still be useful.

**Comment by SIMRAN1** [comment]
@lognaturel  please elaborate the change specified I am not  getting clear idea about it..

**Comment by lognaturel** [comment]
You shouldn't need the `RegexTest` class. You just need to come up with different inputs to `isValidGoogleSheetsString`and `isValidLocation` and verify that those methods correctly return true or false.

**Comment by SIMRAN1** [comment]
Thanks @lognaturel I will do it

**Comment by SIMRAN1** [comment]
@lognaturel  I think we dont need GoogleAbstractUploaderTest  and in Regex Test I have modified testing of Regex by methods.Please Review and tell me the changes..

**Comment by lognaturel** [comment]
Thank you so much for your contribution, @SIMRAN1 and I apologize for the silence. There has been a lot going on in the ODK community and I encourage you to go check some of it out [here](https://forum.opendatakit.org/tags/convening-2017).

The `hamcrest` package should no longer be needed as an explicit dependency so please do remove it.

Upon seeing the code, I think it's actually more helpful to have the regular expression in the test methods rather than as class-level constants. That keeps all of the related functionality together. So perhaps they should be held in variables as the first thing in each method. In fact, maybe the original `isValidGoogleSheetsString` was the best pattern to follow. What do you think? This is definitely a matter of taste.

I think the test class should be named after the class it tests -- in this case, `GoogleSheetsAbstractUploader`. For the tests themselves, do make sure that they are organized in some way and show both valid and invalid example. You should aim to make the tests as exhaustive as you can. That is, they should show the full extent of what is and isn't allowed through systematically created examples.

**Comment by SIMRAN1** [comment]
THANKS @lognaturel I have done all mentioned changes..

**Comment by lognaturel** [comment]
Thank you so much for your patience in seeing this through, @SIMRAN1! 🎉 We appreciate you!

**Comment by SIMRAN1** [comment]
Thank you so much @lognaturel. ODK community is very supporting.I am very glad to contribute in it
!!

**Pull request merged**
