### PR TITLE
fixed inconsistency in SelectOneWidget

### LINKED ISSUE #1855: Inconsistency between SelectOne widgets.
#### Software and hardware versions 
Current master branch

#### Problem description
Last month we implemented `image-map` appearance for select questions. I noticed a small inconsistency between that new widget and ordinary `SelectOneWidget`. 
If we use the first one we can unselect our answer clicking on the same value what is not possible in `SelectOneWidget`. 

#### Expected behavior
I'm not sure which approach we should choose but it should work in the same way. @lognaturel what do you think?

#### Other information 
singleselect

Form for testing:
[canada.zip](https://github.com/opendatakit/collect/files/1719434/canada.zip)

@opendatakit-bot label "needs discussion"
@opendatakit-bot label "quick win"

### PR DESCRIPTION
**Pull request by SIMRAN1**
Fixes #1855  @grzesiek2010  please review the changes!!

### CODE REVIEW

**Comment by grzesiek2010** [comment]
@SIMRAN1 
You changed the behavior in radioButtons but as we decided https://github.com/opendatakit/collect/issues/1855#issuecomment-365488348: 

> Let's use radio button behavior. That means a second click on the image map should not unselect. Note that the unselect behavior should exist in the case of multiple selection.

we should fix image map.

**Comment by SIMRAN1** [comment]
@grzesiek2010 can you please tell me how to test canada.zip form?

**Comment by grzesiek2010** [comment]
@SIMRAN1 sorry for the delay but I was on medical leave. You need to extract that .zip file and copy all files to `odk/forms/` dir on your device. You can also just download the `AllWidgets` form from our demo server since that widget is available there and then you don't need this .zip.

**Comment by lognaturel** [comment]
@SIMRAN1 were you able to load the test form? Please let us know if you have any questions!

**Pull request closed without merging**
