### PR TITLE
Appearance of Forward/backward navigation buttons depends on Android version

### LINKED ISSUE #1498: Appearance of Forward/backward navigation buttons depends on Android version
#### Software and hardware versions 
Collect current master
Android 4.1, 4.2, 4.4, 5.1, 6.0, 7.0

#### Problem description
Appearance of Forward/backward navigation buttons depends on Android version

#### Steps to reproduce the problem

**1. Android 6.0, 7.0**
- arrows are brighter than buttons background 
- backward button on first question looks like active
screenshot_20170927-124456

**2. Android 5.1**
- arrows are darker than buttons background 
- backward button on first question looks like active
screenshot_2017-09-27-12-45-11

**3. Android 4.1, 4.2, 4.4**
- arrows are darker than buttons background 
- backward button on first question looks like inactive
screenshot_2017-09-27-12-45-24

#### Expected behavior
Buttons are consistent on all Android versions

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #1498 

It's my proposal - new images for buttons (all look the same) and grayed out versions of them.

#### What has been done to verify that this works as intended?
I've tested navigation in forms using this branch.

#### Why is this the best possible solution? Were any other approaches considered?
Now all buttons look the same. Additionally I've added grayed out images to highlight when button is enabled/disabled.

#### Are there any risks to merging this code? If so, what are they?
No, it's only a change in appearance.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

### CODE REVIEW

**Comment by mmarciniak90** [comment]
@opendatakit-bot unlabel "needs testing"

**Comment by mmarciniak90** [comment]
@opendatakit-bot label "needs testing"

**Comment by lognaturel** [comment]
I don't know how to evaluate this one! I think the proposed buttons are much better looking but I wonder whether they might be less clear? @yanokwa would be good to get your opinion on this one.

**Comment by grzesiek2010** [comment]
Why less clear :smile: ? only the arrow is a little different

**Comment by lognaturel** [comment]
I think it's plenty clear but maybe in some contexts they wouldn't be recognized as buttons or arrows?

**Comment by grzesiek2010** [comment]
For me it's obvious but if you can imagine better solution I'm ready to implement it (since I'm not a good designer :smile: ).

**Comment by grzesiek2010** [comment]
@lognaturel I've changed those icons and now they look more like before

screenshot_2017-10-25-12-40-27

Maybe it would be good to add it to the upcoming release?

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
Love it!

**Comment by mmarciniak90** [comment]
Tested with success.
Verified on Android 4.1, 4.2, 4.4, 5.1, 7.0
Forward/backward navigation buttons look the same on all versions.

@opendatakit-bot unlabel "needs testing"

**Pull request merged**
