### PR TITLE
Deleted OpenSourceLicensesActivity

### LINKED ISSUE #1926: Use `WebViewActivity` for showing Open Source Licenses
Remove the activity `OpenSourceLicensesActivity` and use `WebViewActivity` for showing the Open Source Licenses

### PR DESCRIPTION
**Pull request by ArmenApresyan8**
Closes #1926

What has been done to verify that this works as intended?
I have removed OpenSourceLicensesActivity and used WebViewActivity for displaying the open source licenses. I have passed the URL of html file with an intent.

Are there any risks to merging this code? If so, what are they?
No

Do we need any specific form for testing your changes? If so, please attach one.
No

### CODE REVIEW

**Comment by shobhitagarwal1612** [comment]
@ArmenApresyan8 The build is failing because there is an unused resource that needs to be deleted.
You can see the detailed report by going [here](https://circleci.com/gh/opendatakit/collect/1625#artifacts/containers/0). 

https://1625-40213809-gh.circle-artifacts.com/0/reports/lint/lint-result.html#UnusedResources

**Comment by ArmenApresyan8** [comment]
@shobhitagarwal1612 yeah I just realized it. Will fix it now. Thanks!

**Review by grzesiek2010 — APPROVED** [review]

**Comment by grzesiek2010** [comment]
@opendatakit-bot label "needs testing"

**Comment by mmarciniak90** [comment]
Verified on Android: 4.1, 4.2, 4.4, 5.1, 6.0, 7.0, 8.0

@lognaturel 
On device with Android 4.1 header with URL is not always visible:
screenshot_2018-02-28-12-07-34

Header appears when I change device orientation or scroll.
I did not notice problems on other Android versions.

**Comment by mmarciniak90** [comment]
@ArmenApresyan8 Could you look on this black header on Android 4.1? Are you able to fix it?

**Comment by ArmenApresyan8** [comment]
@mmarciniak90 Was this also happening before? Before this pull request.

**Comment by mmarciniak90** [comment]
@ArmenApresyan8 I checked on v1.13.1 and it happened but much less often, about 1 of 10 attempts.
Now it is visible on 1 of 3 attempts.

**Comment by mmarciniak90** [comment]
@ArmenApresyan8 I will create a separate issue for this problem cause it is not related with your fix.

**Comment by mmarciniak90** [comment]
**Tested with success!**

Verified on Android: 4.1, 4.2, 4.4, 5.1, 6.0, 7.0, 8.0.
New issue was created for problem noticed on Android 4.1 - #1959

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Review by lognaturel — APPROVED** [review]

**Pull request merged**
