### PR TITLE
WIP : Form hierarchy redesign

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
The intent is to implement the wireframes as described here:
https://app.moqups.com/linesarefuzzy/4WPu8QH3er/view/page/a420360b9

Form for testing : [Household.txt](https://github.com/opendatakit/collect/files/1113133/Household.txt)

This is the structure of the form:

```
| Intro screen (Question)
| Household members (Non-repeat Group)
| ---- How many people live in this house? (Question)
| ---- Head of household (Non-repeat group) 
| ------------ Name (Question)
| ------------ Age (Question)
| ---- Other people (Repeat Group)
| ------------ Name (Question)
| ------------ Age (Question)
| ------------ Sex (Question)
```

### CODE REVIEW

**Comment by lognaturel** [comment]
This is cool! It makes the All Widgets form so much easier to use. 

@hooverlunch I think you should take a look at this and see how it's feeling as a first pass. @shobhitagarwal1612 has taken a look at [the notes from our in-person brainstorming](https://docs.google.com/document/d/1mp7EbLR4rCXFMsO83VxMFEGpFpRLDSpBRgCWftlzruM/edit#). I will be very interested to hear what your users think.

I'm surprised to say that now that I see the question count in action, I do find it kind of compelling. @shobhitagarwal1612 does it take into account relevance calculations? Did you get a chance to start exploring how feasible it would be to show the validation status?

**Comment by shobhitagarwal1612** [comment]
@lognaturel I have calculated the Question/Group count [here](https://github.com/opendatakit/collect/pull/1222/files#diff-c4569759abab98c20df2aa91fe129bc8R356)
What it does is get the children of the form element using the form controller object at the current index

**Comment by lognaturel** [comment]
@shobhitagarwal1612 Does that count take into account relevance? Let's say I have a group that contains a text field followed by 10 fields that have a relevance expression that depends on the text field's value being "foo". If I type "bar" in the text field and then tap jump, does it show 1 question or 10? I think 1 would be the correct number in this case.

**Comment by shobhitagarwal1612** [comment]
I will have to create a new form to test that

**Comment by lognaturel** [comment]
@yanokwa, do you have some really big forms that can be shared publicly with complex logic? We need to be really cautious about performance when adding new information to the hierarchy view and I think it would be helpful to be able to try out some extreme forms. @shobhitagarwal1612, any ideas for programmatically assessing performance?

**Comment by shobhitagarwal1612** [comment]
@lognaturel I agree with you. This has some pretty big logical changes so it's better to test it with as many forms as we can. I have tried all of the forms available in the default aggregate server as well as tried creating few others. 

I am not sure how to access the performance programmatically. Do you have any ideas?

**Comment by lognaturel** [comment]
Good to know about the verification. How about writing up some of the important cases that need to be considered and verified? (e.g. nested repeat groups, non-repeat groups, relevance across different levels in the hierarchy, etc.)

A quick look at 60551e9 is a little scary! It would be helpful to have a narrative on some of the high-level changes you made, how you chose your approach and an estimated impact on performance.

**Comment by shobhitagarwal1612** [comment]
Till now the form hierarchy overview was generated by stepping into the group and then performing whatever that needed to be done.
But now that we have to keep a track of the child groups/questions so it was getting difficult for me to do that with the existing approach. So what I have done is whenever we encounter a group/repeat event for the first time, then I take the reference of that group and loop through its children to get the necessary info.

Since there can be groups/repeats within a repeat as well as groups/repeats within a group, so it seemed like a doable approach to me.

@lognaturel What do you think about this approach?

**Comment by lognaturel** [comment]
Questions completely outside a given group's hierarchy can affect the relevance of questions within groups. Is that accounted for? At a high-level, can you describe what you believe the impact on performance is?

**Comment by shobhitagarwal1612** [comment]
> Questions completely outside a given group's hierarchy can affect the relevance of questions within groups. Is that accounted for?

I am not sure about this but we can test it using a form.

> At a high-level, can you describe what you believe the impact on performance is?

Performance-wise, it should be almost similar to what we already had.

**Comment by smoyte** [comment]
Hi everyone, since I was on vacation, I haven't yet applied any of the changes that came out of our meeting to the mockups. I won't have time to do that for a few days yet, but I don't want unnecessary work to get done. So here are my notes for the meantime:

* Note that bold style for groups may get overridden by styled group names
* Add go to end button to the toolbar
* Breadcrumb doesn’t seem connected to current item title, re-style
* Forget about changes to the 'add group' popup, most people don't use it and the changes are non-trivial
* We don't want to always show non-repeat groups in the list, as sometimes they're just used for organization with no desire to split them out visually. We need a heuristic or property for this. Not sure how to handle. Will need discussion.
* Nix the "n questions" label for groups (although @lognaturel now maybe likes this?)
* Don't use first question response as an item's label in the list -- the form designer can set this explicitly using $ notation. Not sure what to use if they haven't done this though... Maybe just "Item N"?
* Be sure to include item/instance number somewhere in the item label as people rely on it

**Comment by lognaturel** [comment]
I hope you had a restful vacation, @hooverlunch! Welcome back!

In this branch, @shobhitagarwal1612 has been familiarizing himself with the code and doing a preliminary implementation of going to a new screen when entering a group. We talked through our in-person brainstorming together so don't worry, no unnecessary directions have been explored yet! Except maybe for the counts, we'll need to discuss that. I agree totally with your list of items that need discussion.

Some observations about how the current implementation works:
- The "Go Up" and back button don't work as I would expect. I would expect both to take me up exactly one level rather than all the way back.
- It looks like going up to the root level implies reloading the whole form. It's really noticeable when using a big form like [this one](https://forum.opendatakit.org/t/error-message-only-questions-are-allowed-in-field-list/6587)
- Going up to the root level scrolls to the very top of the hierarchy view. Like when the jump menu is first opened from the form, it should scroll down to the latest question that was accessed.

My sense is that these things will need to be addressed in any implementation so that it's worth looking at them even before @hooverlunch's mockups are revised. What do you both think?

**Comment by smoyte** [comment]
Sounds good to me.

**Comment by shobhitagarwal1612** [comment]
Yes. I will fix these bugs

**Comment by smoyte** [comment]
I made a few changes just now. I am super confused about how to name groups and items. @lognaturel can we set up a time to discuss this on a call? I feel like I'm missing some key knowledge here of current practices.

**Comment by lognaturel** [comment]
Just pinged you in #collect-code. Find me there and we can set up a time.

**Comment by lognaturel** [comment]
@hooverlunch @yanokwa and I had a voice chat. 

We discussed the question count and thought it might be best to remove as it is likely to be confusing in the same way that progress bars get confusing. @shobhitagarwal1612, let's discuss in #collect-code when we can. We agreed it would be worth exploring how the validation notifications (amber triangles in the mockups) could be shown.

The current maximized/minimized arrow icons don't make sense with stacking views and should be replaced. Tom will explore different options, one that seemed promising was a folder icon.

For when to show non-repeat groups in the jump screen, we are currently considering two options: always show them when the groups have labels or introduce a new appearance for when they should be shown.

The big thing we talked about was the different kinds of groups and repeats and how they should be displayed both in the form view and in the jump screen. We thought it would be helpful to create an XLSForm with the different kinds of groups and repeats and how we think they should be shown. This is something that we could also get broader feedback on. I have started this initiative [here](https://docs.google.com/spreadsheets/d/1QaCcjAawdlv_o28EQS8GDZnRq8nvYI8JM6FL6qd1WqU/edit#gid=0), please edit as you see fit.

The `students`/`student_grades` examples are where things get interesting. There we give dynamic names to an inner group in the case of `students` and to the repeat itself in the case of `student_grades`. These highlight that it would be interesting to be able to name the instances/items independently of the repeat they are contained in.

**Pull request closed without merging**
