### PR TITLE
Enable external CSV secondary instances (issue #3334)

### LINKED ISSUE #3334: CSV external secondary instances don't work because the jr://file-csv scheme is undefined
Add `file-csv` as a session root translator in `FormLoaderTask`. It needs to go before `file` because `file` is a substring.

https://github.com/opendatakit/javarosa/files/3095508/external_csv.zip is a form for testing. See https://docs.opendatakit.org/collect-forms#loading-form-media for loading form media. If pushing the form directly to a device, a folder with name `<form_id>-media` needs to be created and populated with the media.

### PR DESCRIPTION
**Pull request by breakbusyloop**
Closes #3334

#### What has been done to verify that this works as intended?
gradlew testDebug
gradlew connectedAndroidTest

#### Why is this the best possible solution? Were any other approaches considered?
The only solution to the issue was to add an extra host string to handle "file-csv". The tests seemed to require a fair bit of state (CopyFormRule, global singletons) so they are mostly integration tests. I'm open to discussing ways to make the tests more narrow, but the implementation itself is not and would require more refactoring to support true unit tests.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This enables users to work with secondary instances defined by CSV files. The regression risk is clear: it exposes issue #3335.

#### Do we need any specific form for testing your changes? If so, please attach one.
Same form as is listed in issue #3334: https://github.com/opendatakit/javarosa/files/3095508/external_csv.zip

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
.... maybe?

#### Before submitting this PR, please make sure you have:
- [ X ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ X ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ n/a ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by breakbusyloop** [comment]
This review actually starts with change 6c0a9f4.
Sorry about the errant commits from prior work... still getting the hang of GitHub and git. I'll start creating separate branches for each of my work so the commit histories are cleaner.

**Comment by seadowg** [comment]
Before reviewing I think it'd be good to have the history fixed so we're only seeing the commits relevant to this PR. It looks like you've created a previous PR with your master, merged `opendatakit`'s master back into yours and then added more work on top of that.

As you point out, it's generally easier (for a GIthub PR flow) to have work divided into feature branches coming off master. To get there from where you are right now will take a little "git foo". I think what we need to do is:

**Note**: I'm assuming you have `opendatakit` as a remote. If not do `git remote add opendatakit git@github.com:opendatakit/collect.git`. 

1. Create a feature branch from your current master:

```bash
git checkout -b external-csv
```

2. Force update your own master to be like your upstream:

```bash
git checkout master
git fetch opendatakit
git reset --hard opendatakit/master
```
3. Plonk the new commits from `external-csv` on top of your shiny new master. For this we do a rebase where we tell git what commit to start with. Confusingly (to me at least) we do this by giving it the commit SHA for the commit BEFORE the one we want to start with:

```bash
git checkout external-csv
git rebase --onto master 0140393
```

4. I think you'll need to close this and make a new PR (using `external-csv`) as I don't believe there is a way to edit the branch. When that's all reviewed and merged I find the easiest way of getting my own fork master up to date is:

```
git fetch opendatakit
git merge opendatakit/master --ff-only # ensures we're only adding commitds
git push
```

Maybe you can think of a better way than this - it's early here and I've only just made a cup of tea ☕️. I'm still annoyed that "take a bunch of commits and put them on top of a different branch" is so hard. Maybe I need to write my own git command for this (`git plonk`).

**Comment by breakbusyloop** [comment]
@seadowg thanks for the guidance. I had read that this was possible, and with your specific steps I think I can pull it off.

**Comment by breakbusyloop** [comment]
Closing and replacing with proper rebased branch:  https://github.com/opendatakit/collect/pull/3518

**Pull request closed without merging**
