### PR TITLE
Launch select from map with zoom on current location

### LINKED ISSUE #5093: Zoom to current location when launching select from map view
Currently we launch with a viewport that includes all of the available points. As briefly discussed in https://github.com/getodk/collect/issues/5087#issuecomment-1091928594, let's launch zoomed on the current location instead. It's likely users will want to toggle between the two views. In many use cases starting with current location is most helpful.

Note that this appears to be the current behavior with osmdroid.

### PR DESCRIPTION
**Pull request by lognaturel**
Closes #5093

#### What has been done to verify that this works as intended?
Ran with osmdroid, Google Maps, Mapbox. Added test.

#### Why is this the best possible solution? Were any other approaches considered?
We briefly considered changing the behavior for the form instance map as well. That map is intended to be a summary of work done, though, whereas the select from map is more likely to be used for tasking upcoming work. It makes sense that they would start with a different zoom.

I also considered doing some additional work on making the zoom deterministic here. I've decided to do it separately in case it's controversial https://github.com/getodk/collect/pull/5099.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
The intentional behavior change is that now all three mapping engines should start the select from map view zoomed in to the device location.

#### Do we need any specific form for testing your changes? If so, please attach one.
Any with select from map (https://forum.getodk.org/t/odk-collect-v2022-2-beta-select-from-map-geojson-datasets/36913/6)

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
Should be included in https://github.com/getodk/docs/issues/1458

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by lognaturel** [comment]
One thing to consider about this implementation is that if no location is available on load it might feel jerky. That is, the viewport will be initialized to whatever the default center is and then all of a sudden when a location is acquired it will change. That would particularly be problematic in rural settings where there's only GPS to rely on.

An alternative would be to forget about the location change listener and at time of viewport initialization, go to the current location if there is one and fall back to the feature bounding box.

**Comment by lognaturel** [comment]
This also possibly intersects with a conversation we've had on the forum about initial zoom levels: https://forum.getodk.org/t/geo-optimizing-zoom-levels-for-walking-surveyors/18941

I think we should start with this and explicitly ask field teams about how this default zoom level is working for them.

**Review by seadowg — APPROVED** [review]
I made one change to naming but looks good!

**Comment by kkrawczyk123** [comment]
I have noticed crash on all my devices when used form with 1000 points and OSM Maps, Collect crashes just after tapping on Select place button. 

Stacktrace:
`2022-04-13 13:20:28.768 19972-19972/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.odk.collect.android, PID: 19972
    java.lang.IllegalArgumentException: north must be in [-85.05112877980658,85.05112877980658]
        at org.osmdroid.util.BoundingBox.set(BoundingBox.java:74)
        at org.osmdroid.util.BoundingBox.<init>(BoundingBox.java:49)
        at org.osmdroid.views.overlay.Marker.setPosition(Marker.java:192)
        at org.odk.collect.android.geo.OsmDroidMapFragment.createMarker(OsmDroidMapFragment.java:611)
        at org.odk.collect.android.geo.OsmDroidMapFragment.access$400(OsmDroidMapFragment.java:84)
        at org.odk.collect.android.geo.OsmDroidMapFragment$MarkerFeature.<init>(OsmDroidMapFragment.java:742)
        at org.odk.collect.android.geo.OsmDroidMapFragment.addMarker(OsmDroidMapFragment.java:322)
        at org.odk.collect.geo.selection.SelectionMapFragment.updateFeatures(SelectionMapFragment.kt:354)
        at org.odk.collect.geo.selection.SelectionMapFragment.updateItems(SelectionMapFragment.kt:317)
        at org.odk.collect.geo.selection.SelectionMapFragment.initMap$lambda-14(SelectionMapFragment.kt:195)
        at org.odk.collect.geo.selection.SelectionMapFragment.$r8$lambda$SlaLN6kg4v5ozQIoXqTju2L70Dw(SelectionMapFragment.kt)
        at org.odk.collect.geo.selection.SelectionMapFragment$$ExternalSyntheticLambda6.onChanged(Unknown Source)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
        at org.odk.collect.androidshared.livedata.MutableNonNullLiveData.setValue(NonNullLiveData.kt:22)
        at org.odk.collect.android.widgets.items.SelectChoicesMapData._init_$lambda-1(SelectOneFromMapDialogFragment.kt:127)
        at org.odk.collect.android.widgets.items.SelectChoicesMapData.$r8$lambda$kznZHyHp7KqYIiw6zCS5HBSyEV8(SelectOneFromMapDialogFragment.kt)
        at org.odk.collect.android.widgets.items.SelectChoicesMapData$$ExternalSyntheticLambda0.accept(Unknown Source)
        at org.odk.collect.async.CoroutineScheduler$immediate$1.invokeSuspend(CoroutineScheduler.kt:17)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5298)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)`
        
It works well for forms with2 points. 
cc @seadowg @grzesiek2010

**Comment by srujner** [comment]
Reproduced also on Androids 10 and 11

**Comment by seadowg** [comment]
@srujner @kkrawczyk123  it looks like that crash is this issue: https://github.com/getodk/collect/issues/5075. I'm pretty sure @lognaturel's script/geojson file will always cause that - that form post should be updated to avoid people our beta testers running into it. I don't think we should be using it for QA either.

**Comment by lognaturel** [comment]
Not quite the same, the points are valid in this case. It’s https://github.com/getodk/collect/pull/5073#issuecomment-1080952039 explanation at https://github.com/osmdroid/osmdroid/issues/1339#issuecomment-491519929 but fine to just not use that form.

**Comment by kkrawczyk123** [comment]
**Tested with success!**
Verified on Androids: 5.1 and 8.1

Verified cases:
- Zoom to current location
- zoom to all points
- screen rotation
- display points on map
- regression check on display points on map 
- regression check on geowidgets
- Google, Mapbox, OSM (Crashes from #5084 still visible, and crash mentioned above)
- offline layers

**Comment by srujner** [comment]
**Tested with success!**

Verified also on Androids 10 and 11

**Pull request merged**
