### PR TITLE
Update the end screen warning text based on the available actions

### LINKED ISSUE #5584: Update the end screen warning text based on the available actions
Currently the warning text in the form entry end screen is the same no matter what actions are available. If only one of "finalize" or "save as draft" is available, it doesn't make sense:
Screenshot_20230512_144702

I'd mentioned possible alternatives at https://github.com/getodk/collect/issues/5570#issuecomment-1540372063. This included no notice for the cases where only one action is available. @alyblenkin is working on possible alternatives to consider.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5584 

#### What has been done to verify that this works as intended?
I've tested the fix manually and added automated tests.

#### Why is this the best possible solution? Were any other approaches considered?
This is what we discussed in the issue.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Please just verify the warning is displayed according to the available actions as described in the issue.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by seadowg — APPROVED** [review]

**Comment by seadowg** [comment]
@getodk/testers the different messages are all described [here](https://github.com/getodk/collect/issues/5584#issuecomment-1549905445) in the issue.

**Comment by dbemke** [comment]
The end page of a form is not shown correctly when Save as draft / Finalize is disabled and in auto-send settings there is wifi/wifi or cellular.
endpage


**Steps to reproduce:**
1. Go to Settings → Access control → Form Entry Settings
2. Disable Save as draft or Finalize.
3. Go to Settings →Form management → Auto send
4. Choose wifi only/ wifi or cellular
5. Open a form and go to the end page.

When Auto send is set to off or cellular only the issue doesn’t occur. The issue doesn’t occur on the master version.

**Comment by grzesiek2010** [comment]
@dbemke The problem should be fixed.

**Comment by srujner** [comment]
@dbemke already checked all items from the verified cases yesterday

**Tested with Success!**

Verified on device with Android: 10, 13

Verified cases:

- Acceptance Criteria from #5584 has been met;
- auto send: off, wifi only, cellular, wifi or cellular
- with/without SIM card
- wifi on/off
- switching between projects with different settings in auto send
- changing auto send settings in duplicate project
- auto sending submissions
- sending submissions manually
- finilizing an edited form
- form with auto send set to true/false and auto delete set to true/false

**Pull request merged**
