### PR TITLE
Fixed using settings in CollectSetGeopointAction

### LINKED ISSUE #4627: Filling forms with start-geopoint question is broken
#### Software and hardware versions 
Current master branch

#### Problem description
```
2021-06-20 21:43:05.146 17418-17479/org.odk.collect.android E/FormLoaderTask: java.lang.NullPointerException: Attempt to invoke interface method 'boolean org.odk.collect.shared.Settings.getBoolean(java.lang.String)' on a null object reference
        at org.odk.collect.android.logic.actions.setgeopoint.CollectSetGeopointAction.requestLocationUpdates(CollectSetGeopointAction.java:78)
        at org.javarosa.core.model.actions.setgeopoint.SetGeopointAction.processAction(SetGeopointAction.java:75)
        at org.javarosa.core.model.actions.ActionController.triggerActionsFromEvent(ActionController.java:100)
        at org.javarosa.core.model.actions.ActionController.triggerActionsFromEvent(ActionController.java:82)
        at org.javarosa.core.model.FormDef.initialize(FormDef.java:1170)
        at org.odk.collect.android.tasks.FormLoaderTask.initializeForm(FormLoaderTask.java:338)
        at org.odk.collect.android.tasks.FormLoaderTask.doInBackground(FormLoaderTask.java:183)
        at org.odk.collect.android.tasks.FormLoaderTask.doInBackground(FormLoaderTask.java:71)
```

#### Steps to reproduce the problem
1. Open the attached form and save it: 
[start-geopoint.xlsx](https://github.com/getodk/collect/files/6682985/start-geopoint.xlsx)
2. Try to fill another instance of this form.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #4627

#### What has been done to verify that this works as intended?
I was able to reproduce the issue and confirm that this fix works well.

#### Why is this the best possible solution? Were any other approaches considered?
We need to take the `SettingsProvider` using `DaggerUtils` every time we read from settings not only during creating `CollectSetGeopointAction` because then the provider might be null.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It doesn't require testing.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by seadowg — CHANGES_REQUESTED** [review]
Given this broke without us noticing, I think a test is needed to make sure the same thing doesn't happen again. It looks like everything gets hooked up in `ApplicationInitializer` but it also of course relies on the implementation of `CollectSetGeoPontAction` and on JavaRosa itself, so it feels like a UI test is best here. Ideally we'd have a test that opens a form with `start-geopoint`, finalizes it and then checks the audit log, but for the moment a test that simply launches a form with `set-geopoint` and checks we don't end up with an error would at least avoid this crash happening again.

I know @grzesiek2010 is out today, so I can add a basic test to this, so we're not holding up the fix from being released (given users found this).

**Comment by grzesiek2010** [comment]
> I know @grzesiek2010 is out today, so I can add a basic test to this, so we're not holding up the fix from being released (given users found this).

I'm not out, my dentist's appointment was in the morning and I feel good! But if you already started feel free to continue as I have other tasks too.

**Comment by seadowg** [comment]
@grzesiek2010 good to hear it! Yeah I can still look at this.

**Review by seadowg — APPROVED** [review]

**Comment by seadowg** [comment]
@grzesiek2010 I've added a test. Go ahead and merge if you're happy with it!

**Comment by lognaturel** [comment]
> so we're not holding up the fix from being released (given users found this)

Thanks! Unless it’s really terrible and affects everyone we don’t typically rush to get beta fixes out. I imagine we’ll do another near the end of the week when we have a few more things in.

**Pull request merged**
