### PR TITLE
Do not finalize forms with bad public keys

### PR DESCRIPTION
**Pull request by grzesiek2010**
This pr resolves both issues: #122 and #87

### CODE REVIEW

**Review by lognaturel — CHANGES_REQUESTED** [review]
This is very nicely done! There is just one case missing to close #87: more than one form with the same `jr_form_id`. You can search for the error text "Not exactly one blank form matches this jr_form_id"

**Comment by grzesiek2010** [comment]
Done.

**Comment by lognaturel** [comment]
I still see two cases in which a form that should be encrypted is saved unencrypted -- [here](https://github.com/grzesiek2010/collect/blob/0907ce9d1499437f9bff934cf40f679998f7cbe3/collect_app/src/main/java/org/odk/collect/android/utilities/EncryptionUtils.java#L320) and [here](https://github.com/grzesiek2010/collect/blob/0907ce9d1499437f9bff934cf40f679998f7cbe3/collect_app/src/main/java/org/odk/collect/android/utilities/EncryptionUtils.java#L355).

**Comment by grzesiek2010** [comment]
Updated.

**Comment by lognaturel** [comment]
I believe that [line 319](https://github.com/grzesiek2010/collect/blob/9dda53e472e78b363e1a39cb9552ef087f58c927/collect_app/src/main/java/org/odk/collect/android/utilities/EncryptionUtils.java#L319), [line 347](https://github.com/grzesiek2010/collect/blob/9dda53e472e78b363e1a39cb9552ef087f58c927/collect_app/src/main/java/org/odk/collect/android/utilities/EncryptionUtils.java#L347) and [line 355](https://github.com/grzesiek2010/collect/blob/9dda53e472e78b363e1a39cb9552ef087f58c927/collect_app/src/main/java/org/odk/collect/android/utilities/EncryptionUtils.java#L355) all identify the same issue -- that there's more than one blank form for the instance. Does that sound right? I don't know why the messages are different but it could simply be because they were added at different times. Could you please double check that and either tell me how they're different or use `not_exactly_one_blank_form_for_this_form_id` for all of them if that sounds right to you? Thanks!

**Comment by grzesiek2010** [comment]
[line 347](https://github.com/grzesiek2010/collect/blob/9dda53e472e78b363e1a39cb9552ef087f58c927/collect_app/src/main/java/org/odk/collect/android/utilities/EncryptionUtils.java#L347) and [line 355](https://github.com/grzesiek2010/collect/blob/9dda53e472e78b363e1a39cb9552ef087f58c927/collect_app/src/main/java/org/odk/collect/android/utilities/EncryptionUtils.java#L355) identify the same issue but not [line 319](https://github.com/grzesiek2010/collect/blob/9dda53e472e78b363e1a39cb9552ef087f58c927/collect_app/src/main/java/org/odk/collect/android/utilities/EncryptionUtils.java#L319) which refers to instance not form. I added changes for those two lines.

**Comment by lognaturel** [comment]
Great! For future changes like this, please add a new commit. In this case I would write something like "Use the same error text for the two cases of non-unique blank forms." That makes it much easier to review and refer back to in the future.

**Pull request merged**
