### PR TITLE
Implement a range control

### PR DESCRIPTION
**Pull request by dcbriccetti**
A work in progress. Goes along with https://github.com/opendatakit/javarosa/pull/44. Shows that the range element and its attributes can be parsed and provided to a widget.
To be determined: What sort of widget to use.

### CODE REVIEW

**Comment by dcbriccetti** [comment]
Hmm, sorry about all the ugly merge commits. Perhaps I can redo this.

**Comment by lognaturel** [comment]
Don't worry about it, this will almost certainly be squashed and merged!

The default appearance of the control should probably be a [SeekBar](https://developer.android.com/reference/android/widget/SeekBar.html):
seekbar-1
Questions we need to answer include whether to show a number as in the screenshot above, gridlines, etc.

I think you can keep this branch about doing some light refactoring as you've been doing and perhaps we can merge it as a skeletal widget and implement the UI separately.

**Comment by lognaturel** [comment]
@dcbriccetti @grzesiek2010 I believe @grzesiek2010 is now working off another branch and has taken what is needed from here. Are we ok to close?

**Comment by dcbriccetti** [comment]
>@dcbriccetti @grzesiek2010 I believe @grzesiek2010 is now working off another branch and has taken what is needed from here. Are we ok to close?
Fine with me.

**Pull request closed without merging**
