### PR TITLE
Fixed: Read-only binary questions have no spacing below the question text

### LINKED ISSUE #4209: Read-only binary questions have no spacing below the question text
#### Software and hardware versions 
Collect v1.28 and prior

#### Problem description
Binary widgets hide their buttons when they're read-only. Currently they leave no spacing below the question text which looks strange in field lists, especially when they're combined with text fields:
 

#### Steps to reproduce the problem
Load a form with a field list including one or more binary questions such as https://github.com/getodk/collect/pull/4188#event-3962296705.

#### Expected behavior
There should be spacing below question text for read only binary questions.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #4209

#### What has been done to verify that this works as intended?
I tested the fix manually and added some tests.

#### Why is this the best possible solution? Were any other approaches considered?
We just agreed that if a question is read-only and has no answer we need some space to separate such widgets especially in field-list groups.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Since now if a question is read-only and has no answer an empty container should be displayed instead of its question container. In order to test this fix it would be good to just go through a form with all widgets like the one I attached below.

#### Do we need any specific form for testing your changes? If so, please attach one.
I used:
[all-widgets-read-only-field-list.xlsx](https://github.com/getodk/collect/files/5603942/all-widgets-read-only-field-list.xlsx)
[all-widgets-read-only.xlsx](https://github.com/getodk/collect/files/5603943/all-widgets-read-only.xlsx)

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by grzesiek2010** [comment]
@lognaturel it turned out that we don't need all those checks if the answer container is gone or not. I don't know what I did wrong that I needed it in my first solutions and I don't want to waste time now to figure it out. It's even better, the solution is cleaner, sorry for the confusion.

**Review by lognaturel — APPROVED** [review]
I'd tend to put a comment next to where `space_box` is defined in the XML layouts but don't feel super strongly about it. Looks good!

**Comment by mmarciniak90** [comment]
**Tested with success**

Verified on Android versions: 7.0, 8.1, 10.0

Verified cases:
- read only widgets - the difference is visible especially in widgets:
   - Range
   - Video
   - Data/time
   - Select one/multi. _Keyboard on autocomplete appearance reported as a separate issue._
   - Trigger
- read only widgets on field-list - _Additional issue noticed also on master branch - no space below ex printer widget._
- read only widgets on field-list with answers
- light/dark mode
- RTL language
- go forward/backward
- different font size settings
- rotate screen
- jump from hierarchy
- minimize app

**Comment by kkrawczyk123** [comment]
Verified on Androids 5.1, 7.1 and 9.0.

@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"

**Pull request merged**
