### PR TITLE
closing drawer on pressing back button in FileManagerTabs activity ( …

### PR DESCRIPTION
**Pull request by pranavgupta1234**
…it contains fragments , related to issue #759) issue #765 fixed

### CODE REVIEW

**Comment by lognaturel** [comment]
Please make sure that you run code to verify its behavior before submitting a pull request! 

Make sure this compiles and please make the same style changes as for #759 -- conditionals should have the following spacing: 
```
if (condition) {
    ...
} else {
    ...
}
```

**Comment by lognaturel** [comment]
The style looks great but I still don't think that this compiles... have you tried it?

**Comment by pranavgupta1234** [comment]
The build failed and I am trying to troubleshoot the errors. I will try to fix it asap.

**Comment by lognaturel** [comment]
Oh, sorry, I think I commented right as you got your latest commit in.

**Pull request merged**
