### PR TITLE
Fix code duplication from JavaRosa for serializable classnames

### LINKED ISSUE #1466: Collect violates separation of concerns and complicates maintenance by copying class names from JavaRosa
Collect’s `FormController` copies class names from JavaRosa in order to register prototypes in the `PrototypeManager`. 

```
    private static final String[] SERIALIABLE_CLASSES = {
            "org.javarosa.core.services.locale.ResourceFileDataSource", // JavaRosaCoreModule
            "org.javarosa.core.services.locale.TableLocaleSource", // JavaRosaCoreModule
⋮
```

The comments indicate that this was done because calling the proper `registerModule` JavaRosa methods have unwanted side effects. I assume someone wanted to avoid making the changes in JavaRosa that would allow these concerns to stay separated. Instead they copied a large list of class names from JavaRosa into Collect. These details should not be exposed to Collect, and Collect should not have to be changed just to add a new serializable class (such as one for external secondary instances) to JavaRosa.

Let’s make this better by exposing these class names from JavaRosa at runtime, rather than copying them into the source code.

### PR DESCRIPTION
**Pull request by dcbriccetti**
Closes #1466

Will fail until https://github.com/opendatakit/javarosa/pull/187 is merged and a new JavaRosa version is created.

#### What has been done to verify that this works as intended?
Ran Collect with JavaRosa https://github.com/opendatakit/javarosa/pull/187. Saved and loaded several forms.

#### Why is this the best possible solution? Were any other approaches considered?
(From the corresponding JavaRosa PR:) It’s the best for now. Later we can learn about the side effects in the registration methods that a Collect developer wanted to avoid, years ago.

#### Are there any risks to merging this code? If so, what are they?
I wish I could automatically test with a form containing all types of serializable data. If I missed something, serialization could fail.

### CODE REVIEW

**Comment by dcbriccetti** [comment]
@mitchellsundt Your fingerprints are on this from when you moved some of this code around years ago. Does this seem like a reasonable intermediate step, to eliminate the code duplication?

**Comment by lognaturel** [comment]
@dcbriccetti Do you have any idea at all what the undesired side effects could have been?

**Comment by lognaturel** [comment]
The comment says `unfortunately, the JR registerModule() functions do more than this.` Since we're now controlling the ODK JavaRosa public interface, could we just introduce a new public method that `registerModule` calls and just does the stuff Collect needs?

**Comment by dcbriccetti** [comment]
I don’t know why Collect can’t just call registerModule on those three “modules”: JavaRosaCoreModule, CoreModelModule, and XFormsModule. My immediate goal was to remove the code duplication while doing exactly the same things. Perhaps we could package up what needs to be done in a single JavaRosa call, but what would we call it? Does it contain knowledge of Collect that it shouldn’t? Would other clients also use it?

**Comment by dcbriccetti** [comment]
Digging around in Aggregate, I see it also duplicates this code, in `BaseFormParserForJavaRosa`:
```
  /**
   * Classes needed to serialize objects. Need to put anything from JR in here.
   */
  public final static String[] SERIALIABLE_CLASSES = {
    "org.javarosa.core.services.locale.ResourceFileDataSource", // JavaRosaCoreModule
    "org.javarosa.core.services.locale.TableLocaleSource", // JavaRosaCoreModule
⋮
```

**Comment by lognaturel** [comment]
I continue to be very confused about the possible risks this presents. I originally thought that "unfortunately, the JR registerModule() functions do more than this" was an explanation for why the list of classes was needed. Upon more careful reading, it appears to explain why `registerPrototypes` is used instead of `registerModule`. Does that match your reading, @dcbriccetti?

Looking at it carefully again, is it possible that the original writer of the code just didn't know they could pass in `JavaRosaCoreModule.classNames` and `CoreModelModule.classNames` to `registerPrototypes`?

If that analysis seems right, then this is change is great and non-controversial. I would only request that the comment
```
            // need a list of classes that formdef uses
            // unfortunately, the JR registerModule() functions do more than this.
            // register just the classes that would have been registered by:
            // new JavaRosaCoreModule().registerModule();
            // new CoreModelModule().registerModule();
            // replace with direct call to PrototypeManager
``` 
be changed to something less cryptic.

There is a lot of duplicate code between the different tools and that's something that would also be good to address over time. The worst is between Aggregate and Briefcase.

**Comment by lognaturel** [comment]
Ok, I'm sorry, I was forgetting about opendatakit/javarosa#187.

The bit about side effects in the registration methods was throwing me off but now I don't think it's relevant to this PR, it's just something to potentially investigate in the future.

**Review by lognaturel — APPROVED** [review]

**Review by lognaturel — CHANGES_REQUESTED** [review]
Comment clean up or removal. Maybe something like "`registerPrototypes` is used instead of `registerModule` to avoid re-registering storage." I'm pretty sure that's the explanation.

**Comment by lognaturel** [comment]
Good news, this is finally making sense to me! We just have to update JR before merging so `classNames` is available. I think a comment cleanup would also help future archaeologists.

**Comment by dcbriccetti** [comment]
Why don’t I give this one more “think”, and also consider the new duplication case from Aggregate.

**Comment by lognaturel** [comment]
Perfect.

**Review by lognaturel — APPROVED** [review]
Have you completed your "think"? I'm feeling satisfied with this and now that JR has been updated I believe it's ready to merge.

**Comment by dcbriccetti** [comment]
Yes, I am done veeth my leetle theenk (get the Einstein reference?—not that I’m any Einstein)

**Pull request merged**
