### PR TITLE
Ignore case when sorting Blank Forms list

### LINKED ISSUE #1264: Sort on 'Fill Blank Form' view takes into account a case-sensitive
#### Software and hardware versions 
Collect v1.8.1
Noticed during testing [Sort menu redesign - Bottom Sheet Dialog](https://github.com/opendatakit/collect/pull/1242)
#### Problem description
Sort on 'Fill Blank Form' view takes into account a case-sensitive
screenshot_2017-07-20-12-43-45

#### Steps to reproduce the problem
User opens 'Fill Blank Form' view
User sees list of form
Part of forms starts with a upper case letter and part lower case letter
User sees that sorting by name is not correct

#### Expected behavior
Forms are sorted alphabetically even if form names starts from lower case and upper case

### PR DESCRIPTION
**Pull request by dsrees**
Closes #1264 

#### What has been done to verify that this works as intended?
I have verified the behavior by running on a device and adjusting the sorting to make sure that lowercase letters are sorted in alphabetical order with uppercase letters. I have also modified a test to use the `COLLATE NOCASE` SQL option to test this behavior as well

#### Why is this the best possible solution? Were any other approaches considered?

`COLLAGE NOCASE` is a built in SQL command which converts uppercase ASCII characters to lowercase prior to executing a compare. This is the least intrusive change to the codebase to achieve the desired result. More can be read about `COLLATE` in the [SQLite documentation](https://sqlite.org/datatype3.html#collating_sequences)

#### Are there any risks to merging this code? If so, what are they?

There are no risks.

I did a bit of refactoring as well by assigning the `sortingOrder` options to static variables which can be easily compared against in other places in the product, such as `FormDownloadList:467`.

### CODE REVIEW

**Comment by lognaturel** [comment]
Thank you, @danielrees18! 

We're just getting Codecov set up and it's the first time I see a report from the bot as above. I think the reason we're seeing a decrease in coverage is that `master` runs connected tests and branches don't. @shobhitagarwal1612 does that sound right to you? If so, perhaps the branch reports aren't so useful. Let's discuss in Slack!

**Comment by shobhitagarwal1612** [comment]
@ln Yes, you are absolutely correct

**Comment by mmarciniak90** [comment]
Tested with success.
Tested on Android 4.1, 4.2, 4.4, 5.1, 6.0, 7.0. 
screenshot_20170922-123543

Created a new issue to fix this behavior on all views #1489

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
Thank you, @mmarciniak90! I totally forgot that the other screens would need to be handled separately. 

@danielrees18 thanks very much for doing this and welcome to ODK! You've already found the Slack. Additionally, if you haven't already, you may want to also checkout [the forum](https://forum.opendatakit.org) to learn more about the user community. If you'd like to take #1489 on and do it as a single pull request, that'd be great!

**Comment by mmarciniak90** [comment]
@opendatakit-bot unlabel "needs testing"

**Pull request merged**
