### PR TITLE
Factored out MultiClickGuard class

### PR DESCRIPTION
**Pull request by grzesiek2010**
#### What has been done to verify that this works as intended?
Just reviewed implemented changes.

#### Why is this the best possible solution? Were any other approaches considered?
We keep to much in the application class. This is just a refactoring that factors out the code responsible for blocking multi-clicks which is not related to the application class so should exist somewhere else.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
I would say it doesn't require testing. Reviewing the code would be enough.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by seadowg — APPROVED** [review]
Nice! Definitely good to get stuff out of `Collect`. I'll mark this as needs testing but dont' think there is any need to get it into 1.26 so it's low priority.

**Comment by mmarciniak90** [comment]
@grzesiek2010 @seadowg 
For now, tested on Android: 6.0, 7.0, 8.1
If you think that testing on Android 5.1, 9.0, and 10.0 is necessary, let us know.

**Verified cases**
* Learn more and migrate
* More details in Storage migration page
* Migrate
* Dismiss migration dialog
* All subpages in About page
* All subpages in General Settings
* All buttons in the Main menu
* All widgets with button
* Permission dialogs
* Add group dialog
* Hierarchy icon

During testing, I noticed new issues: #3713 and #3714
Issue #3638 was noticeable

**Comment by grzesiek2010** [comment]
> If you think that testing on Android 5.1, 9.0, and 10.0 is necessary, let us know.

In this case three devices seems enough.

**Comment by mmarciniak90** [comment]
Thanks, @grzesiek2010 

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Pull request merged**
