### PR TITLE
line separator added. Fix #1976.

### LINKED ISSUE #1976: There are no separator lines in SelectOneSearchWidget
#### Software and hardware versions 
Collect v1.13.2 and older versions

#### Problem description
There are no separator lines in `SelectOneSearchWidget`

#### Steps to reproduce the problem
screenshot_2018-03-06-14-55-04
screenshot_2018-03-06-14-55-14

#### Expected behavior
I'm not sure whether we should add those lines in `SelectOneSearchWidget` or maybe remove them at all (from other widgets) but the layout in both cases should be consistent.

@lognaturel which approach do you prefer?

@opendatakit-bot label "quick win"
@opendatakit-bot label "needs discussion"

### PR DESCRIPTION
**Pull request by arihant-001**
Closes #1976 

#### What has been done to verify that this works as intended?
Tested on physical device(ASUS Zenfone) and other emulators.
#### Why is this the best possible solution? Were any other approaches considered?
Line separator was already present in the SelectOneWidget form and it was working fine, so using same method in the SelectOneSearchWidget won't create any problem and hence the best way.
#### Are there any risks to merging this code? If so, what are they?
No risks at all.
#### Do we need any specific form for testing your changes? If so, please attach one.
You will need SelectOneSearchWidget and SelectOneWidget form.

### CODE REVIEW

**Review by lognaturel — APPROVED** [review]

**Comment by arihant-001** [comment]
@lognaturel do I need to do anything?

**Comment by mmarciniak90** [comment]
**Regression has been found!**
@ArihantJain456 
Steps to reproduce:
1. User puts text to search field in Select one search widget
2. If the text is available, Collect crashes

@opendatakit-bot unlabel "needs testing"

**Review by lognaturel — CHANGES_REQUESTED** [review]
Thank you, @mmarciniak90! @ArihantJain456 please look at the reported crash.

**Comment by lognaturel** [comment]
Closing this for now so someone else can take it on if they would like.

**Pull request closed without merging**
