### PR TITLE
Added 3 test cases to `FillBlankFormTest` and small improvements

### PR DESCRIPTION
**Pull request by mmarciniak90**
### What has been done 

* Added 3 test cases to `FillBlankFormTest`
* Fixed typos
* Reordered test cases to match the issue
* Made tests more language-independent

### CODE REVIEW

**Comment by seadowg** [comment]
I ran this on test lab but hard to verify it's working as there are several broken tests in this file already. Hopefully we can get that fixed and then update this PR 😃

**Review by seadowg — CHANGES_REQUESTED** [review]
I ran this on test lab but hard to verify it's working as there are several broken tests in this file already. Hopefully we can get that fixed and then update this PR 😃

**Comment by mmarciniak90** [comment]
@seadowg Could you tell me what Android version you used?
I tried to find the reason for broken tests and I noticed interesting dependence.
I run tests on an emulator with Android 6 and all passed, then I run them on an emulator with Android 7 and most of them failed.

**Comment by seadowg** [comment]
@mmarciniak90 Interesting. Our CI is currently using API 27 so that's Android 8.1. The problems there were mainly related to Espresso not loading translated strings properly (as described in #3317)

**Review by seadowg — CHANGES_REQUESTED** [review]
Think this just needs updated against master now hopefully!

**Review by seadowg — DISMISSED** [review]
I'm seeing `questionValidation_ShouldShowToastOnlyWhenConditionsAreNotMet` failing on Test Lab and locally (using API 27 on both). Is that working for you?

**Comment by mmarciniak90** [comment]
@seadowg test was updated and now everything is ok. I checked on Android 8.1 (API 27)

**Comment by mmarciniak90** [comment]
@seadowg @grzesiek2010 
Do you know why tests failed on CircleCI? 
I'm not sure but it doesn't seem like a problem with my changes. 

`> Task :collect_app:testDebugUnitTest
Calling mockable JAR artifact transform to create file: /home/circleci/.gradle/caches/transforms-2/files-2.1/6d18b7bcebcaedf79078ab314d29f6c5/android.jar with input /opt/android/sdk/platforms/android-28/android.jar
Too long with no output (exceeded 10m0s)`

**Comment by seadowg** [comment]
@mmarciniak90 hmmm. I'm not sure. Rerunning for the moment.

**Comment by seadowg** [comment]
Seems happy now. Feels like we're running into time limit problems on Circle CI that we need to keep eye on.

**Comment by mmarciniak90** [comment]
@seadowg thanks for the help. I can't wait for the merge

**Review by seadowg — APPROVED** [review]
Looks good! Sorry for the delay in the review. I wanted to give this a run through on Test Lab.

**Pull request merged**
