### PR TITLE
Introduce helpers for theme colors and document how to support light and dark themes

### LINKED ISSUE #2165: Describe how best to support light and dark themes when adding UI components
#2061 adds support for a dark theme. 🎉 

As new UI components are added, they need to use `colorControlNormal`, `primaryTextColor`, etc to make sure the look changes based on the the theme. Advice on how best to do that should be added to https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md. This should also be linked to from [the pull request template](https://github.com/opendatakit/collect/blob/master/.github/PULL_REQUEST_TEMPLATE.md).

@shobhitagarwal1612, as the feature developer, I think you are best positioned to take a first pass when you get a chance! 😊

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Closes #2165 

#### What has been done to verify that this works as intended?
Verified manually on Moto G5 plus Android 7.0

#### Why is this the best possible solution? Were any other approaches considered?
This adds helper functions for getting theme colors instead of fetching using the attribute id and also create a new custom attribute `iconColor` to be used in place of `coloControlNormal` for better clarity

#### Are there any risks to merging this code? If so, what are they?
Yes, refactoring is always risky. The color of icons might behave differently if the new attribute is not applied to all places 

#### Do we need any specific form for testing your changes? If so, please attach one.
No

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew pmd checkstyle lint findbugs` and confirmed all checks still pass.
- [x] verified that any new UI elements use theme colors so that they work with both light and dark themes.

### CODE REVIEW

**Comment by lognaturel** [comment]
Looks good to me! Thanks, @shobhitagarwal1612.

**Comment by lognaturel** [comment]
@shobhitagarwal1612 something has happened to the history. It looks like you may have tried to rebase on master to fix conflicts but maybe ended up with an older version? Only the relevant commits should show up in the diff.

**Comment by shobhitagarwal1612** [comment]
I rebased onto my origin master branch instead of upstream master branch which wasn't updated in quite some time

**Comment by lognaturel** [comment]
Ahh, much better! Hope it wasn't too painful. Now we're back in business. 😊

**Comment by shobhitagarwal1612** [comment]
Just had to rebase and then drop some commits to fix it

**Comment by mmarciniak90** [comment]
**Tested with success**

I did not notice regression. 
I'm just not sure about `Save icon` in `Import/Export Settings` view. There is a crash (fixed in #2192).
I will be able to check that after the merge.
Verified on Android: 4.1, 4.2, 4.4, 5.1, 6.0, 8.1

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Comment by shobhitagarwal1612** [comment]
@mmarciniak90 I have updated the branch with the fix so the remaining task can be tested now

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
The buttons are looking good so I'll merge and there will be more verification with a second beta and pre-release testing. 👍

**Pull request merged**
