### PR TITLE
WIP: Database refactoring

### PR DESCRIPTION
**Pull request by grzesiek2010**
@lognaturel  it's related to https://github.com/opendatakit/collect/issues/1252
I have been thinking about refactoring for a long time. To solve [this issue](https://github.com/opendatakit/collect/issues/1252) we need downgrade functionality but we also need to refactor the code. Here is my proposal let me know if it's ok and if I should go ahead.

I haven't tested it yet it's only a proposal.

When it comes to downgrade I think [that](https://github.com/opendatakit/collect/pull/1253/files#diff-4d08a2751ff1701de2dc77d0c4a336c0R96) implementation should be enough (I mean case 3,2 and 1 might be empty) as version 4 was implemented in 2012 so I think there is no need to support downgrade to such an old version :).

### CODE REVIEW

**Comment by lognaturel** [comment]
I'm going to need to look at this in more detain but in principle it seems like there are good changes here.

I don't think it addresses #1252 at all, though, because the code in the old version won't change. The problem isn't with the code that runs in the current version, it's with the code that gets run when the old version is used, right?

**Comment by grzesiek2010** [comment]
> I don't think it addresses #1252

yes you are right I made a mistake. However we need this refactoring so let me improve it a bit and then you can decide if it's ok.

**Comment by grzesiek2010** [comment]
@lognaturel please look at it when you are free. I think it's important to fix our problems in next release.
I've written one test for instances.db. If you like this I'm going to test everything manually to be sure onUpgrade/onDowngrade work as expected.

**Comment by lognaturel** [comment]
I want to start by making sure we are in agreement on goals here. I think this has been a very useful prototype but to make sure we get to the best structure possible, we should separate out the different components of this changeset and consider them separately.

The current problem we are facing is that the forms database upgrade migration ends in a dangling `else`. I think addressing that is the most important first step and that it should be done in its own pull request. I have filed #1323 and we can include the change in 1.9.1 which should go out tomorrow. That change will mean that it will later be possible to downgrade to 1.9.1 even if there are additive database changes (it still won't work if columns are removed). We should make a note of that version limit in documentation somewhere for when we do decide to make a change to the forms database.

I think that in this pull request you have tried to address a number of other issues. The first one is that there is no testing of the database migrations. That might be a good pull request to introduce next to verify the existing migration behavior.

You also have identified that the class hierarchy and placement of classes for the database helper classes is not ideal. I agree and that might be a next good thing to address based on some of the work you have done here. I think it would good to file an issue and discuss the approach first. I have a number of questions:
- Why was `ODKSQLiteOpenHelper` introduced as a new class instead of subclassing [SQLiteOpenHelper](https://developer.android.com/reference/android/database/sqlite/SQLiteOpenHelper.html)? It seems that subclassing the Android class would provide many benefits such as including an `onDowngrade` method.
- If that can't happen for some reason, why not introduce `onDowngrade` in the parent class?

And finally, you have added `onDowngrade` functionality. That is definitely great but I don't think it is necessary to support downgrades below the current DB versions. It will be impossible to ever run that code since the version number will never be lower in an app you want to downgrade to. It's the same problem we were discussing in the early comments on this pull request -- we can't modify the code of apps that are already running on devices, only on apps that will be installed in the future.

**Comment by grzesiek2010** [comment]
@lognaturel 

> Why was ODKSQLiteOpenHelper introduced as a new class instead of subclassing SQLiteOpenHelper?

It's a good question. To be honest I don't know :) and it's a thing we have to investigate.

> The current problem we are facing is that the forms database upgrade migration ends in a dangling else. I think addressing that is the most important first step and that it should be done in its own pull request. I have filed #1323 and we can include the change in 1.9.1 which should go out tomorrow.

I agree the code there doesn't look well and I refactored it in a separate pr https://github.com/opendatakit/collect/pull/1324
but it's not the main problem. The problem is we call onUpgrade method even if we install an app with an older database look at my pr https://github.com/opendatakit/collect/pull/1326 so this method shouldn't be even called.

The original SQLiteOpenHeler class cares about it https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/core/java/android/database/sqlite/SQLiteOpenHelper.java#253

**Comment by lognaturel** [comment]
Awesome, breaking it down into smaller pieces looks great. You're totally right about #1326.

When you have a chance, please open up an issue so we can discuss the class hierarchy and whether we can use Android's `SQLiteOpenHelper` instead of this custom one. I did a quick diff with the latest `SQLiteOpenHelper` but naturally it has changed quite a bit. Doing a diff with the original class and seeing how ODK's was changed might be a good place to start.

I'll close this pull request but I'd recommend you keep the branch around to get ideas from as we approach this step by step.

**Pull request closed without merging**
