### PR TITLE
Use MaterialAlertDialogBuilder instead of AlertDialog.Builder across the app

### LINKED ISSUE #4915: Make dialogs across the app look the same
#### Software and hardware versions 
Collect v2021.3.2 and older versions

#### Problem description
Currently we use two dialog builders `AlertDialog.Builder` and `MaterialAlertDialogBuilder` in our app what cause differences in their style. We should use one builder - `MaterialAlertDialogBuilder`.

Unfortunately we can't change the way `PreferenceFragmentCompat` works under the hood (it uses `AlertDialog.Builder`) so we should improve its styling to make sure that dialogs displayed in preferences look the same like all the other dialogs (build using `MaterialAlertDialogBuilder`).

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #4915 

#### What has been done to verify that this works as intended?
I reviewed implemented changes and tested some dialogs used in our app.

#### Why is this the best possible solution? Were any other approaches considered?
The first thing I changed was using `MaterialAlertDialogBuilder` instead of `AlertDialog.Builder`. Unfortunately our settings which are based on `PreferenceFragmentCompat` use `AlertDialog.Builder` under the hood so I also had to improve styling of `AlertDialog.Builder` to make sure dialogs created using that builder look the same like those created using `MaterialAlertDialogBuilder`.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This change is related to the way our dialogs are styled so please review them to make sure they look the same.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Review dialogs used across the app and make sure 

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by seadowg — APPROVED** [review]
Definitely in support of this change!

**Comment by kkrawczyk123** [comment]
@grzesiek2010 When testing I have noticed that I can't open auto-send results and automatic form update dialogs - app is crashing instead. I have investigated and the issue is also visible on the master. Is there a chance that you could take a look at that in this pr or do you prefer opening a new issue?

**Comment by grzesiek2010** [comment]
I know about those crashes but those dialogs are removed in https://github.com/getodk/collect/pull/4929 so it doesn't make sense to fix them.

**Comment by kkrawczyk123** [comment]
**Tested with success!**
Verified on Androids 5.1, 8.1 and 10

Verified cases and dialogs:

- screen rotation
- minimize app
- light/ dark mode
- projects dialog 
- admin password
- enter admin password
- project name
- project icon
- project color
- reset application
- reset results
- delete project
- connecting to server dialog
- download results dialog
- form list download failed 
- sending form
- upload result dialog
- server require authentication dialog
- moving backward disabled/enabled
- server type
- Google account not set dialog
- Set Goggle account dialog
- fallback submission URL
- server url
- username
- password
- theme
- language
- test font size
- navigation
- Maps/source
- map style dialog
- offline layer dialog
- blank form update mode
- automatic update frequency dialog
- auto send dialog
- constraint processing behavior dialog
- image size dialog
- show guidance for questions
- form metadata/username
- form metadata/phone number
- form metadata/email address
- change view dialog
- delete selected dialog
- saving form dialog
- save and exit dialog
- save and exit dialog when moving backwards enabled
- change language in form dialog
- bearing widget
- Range widget with number picker
- exit sketch image widget
- set color
- exit gather signature
- audio recording in background
- delete recorded audio dialog 
- all date widgets
- location widgets
- input methods on Geotrace and Geoshape dialog
- offline layer on map view
- discard changes on Geotrace and Geoshape
- clear the feature on Geotrace and Geoshape
- rank widgets
- add group dialog
- remove group
- remove response dialog
- field-list not supported in repeats error
- edit encrypted form

**Comment by srujner** [comment]
**Tested with success!**
Verified also on Android 11

**Pull request merged**
