### PR TITLE
Get audio file from uri using ContentResolver

### LINKED ISSUE #2342: Recording and saving an audio file causes a crash
#### Software and hardware versions 
f0d5fa2 on sms_submission branch. Android 7.0 on Moto G5 Plus

#### Problem description
Recording and saving an audio file causes a crash

#### Steps to reproduce the problem
* Install the [Sony Audio Recorder](https://play.google.com/store/apps/details?id=com.sonymobile.androidapp.audiorecorder)
* Download the All Widgets form and navigate to the Audio widget
* Record sound (and grant any necessary permissions)
* Save sound and press Done.
* Collect crashes

#### Other information 
```
06-29 13:41:41.508 27437 27437 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=3, result=-1, data=Intent { dat=content://com.sonymobile.androidapp.audiorecorder.content/voice recordings/music recordings/Audio recording 2018-06-29 13-41-35.wav typ=audio/raw flg=0x1 }} to activity {org.odk.collect.android/org.odk.collect.android.activities.FormEntryActivity}: java.lang.IllegalArgumentException: column '_data' does not exist
06-29 13:41:41.508 27437 27437 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4094)
06-29 13:41:41.508 27437 27437 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4137)
06-29 13:41:41.508 27437 27437 E AndroidRuntime: 	at android.app.ActivityThread.-wrap20(ActivityThread.java)
06-29 13:41:41.508 27437 27437 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1529)
06-29 13:41:41.508 27437 27437 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-29 13:41:41.508 27437 27437 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
06-29 13:41:41.508 27437 27437 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6123)
06-29 13:41:41.508 27437 27437 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-29 13:41:41.508 27437 27437 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
06-29 13:41:41.508 27437 27437 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
06-29 13:41:41.508 27437 27437 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: column '_data' does not exist
06-29 13:41:41.508 27437 27437 E AndroidRuntime: 	at android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:333)
06-29 13:41:41.508 27437 27437 E AndroidRuntime: 	at android.database.CursorWrapper.getColumnIndexOrThrow(CursorWrapper.java:87)
06-29 13:41:41.508 27437 27437 E AndroidRuntime: 	at org.odk.collect.android.utilities.MediaUtils.getDataColumn(MediaUtils.java:648)
06-29 13:41:41.508 27437 27437 E AndroidRuntime: 	at org.odk.collect.android.activities.FormEntryActivity.onActivityResult(FormEntryActivity.java:765)
06-29 13:41:41.508 27437 27437 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:6931)
06-29 13:41:41.508 27437 27437 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4090)
06-29 13:41:41.508 27437 27437 E AndroidRuntime: 	... 9 more
06-29 13:41:41.512  2412  2448 W ActivityManager:   Force finishing activity org.odk.collect.android/.activities.FormEntryActivity
```

Perhaps related to #705, but the stack trace is different.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #2342 

#### What has been done to verify that this works as intended?
I tested a device with Sony Audio Recorder app.

#### Why is this the best possible solution? Were any other approaches considered?
This solution doesn't require `_data` column provided in uri.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This change should only fix the bug but the code used for capturing audio has been changed a lot so this part of our functionality should be tested carefully. Additionally, I edited a method used during capturing videos so it would be good to confirm there is no regression there as well.

#### Do we need any specific form for testing your changes? If so, please attach one.
Any form with `AudiWidget` for example `AllWidgets` form.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by lognaturel** [comment]
I initially wasn't sure this was going to work for all media sources but after some reading, I believe it will. I guess a good first QA pass would be to make sure audio can be added from all sources on different Android versions. I think verifying 4.1, 5.0 and 7.0 would be enough. We know it will fail when changing device orientation so that shouldn't be part of the verification. I don't think it's worth checking for video regressions yet because ideally the same solution can work for that as well. What do you think?

As far as device orientation changes, @shobhitagarwal1612's https://github.com/opendatakit/collect/pull/2569 addresses that though the PR doesn't mention it explicitly.

**Comment by grzesiek2010** [comment]
>  I don't think it's worth checking for video regressions yet because ideally the same solution can work for that as well. What do you think?

I agree. When it comes to video please answer my question https://github.com/opendatakit/collect/issues/660

**Comment by mmarciniak90** [comment]
**Tested on success**

Verified on Android: 5.1, 6.0, 7.0, 8.1
Crash does not occur on mentioned devices.

Audio recorded via Sony Audio Recorder app is not attached on Android 4.4, 4.2, 4.1. 
This behavior is not related to the fix. 
It is visible on ODK Collect v1.16.4 and 1.17.2 (I did not verify older versions)

@opendatakit-bot label "behavior verified"
@opendatakit-bot unlabel "needs testing"

**Comment by grzesiek2010** [comment]
Let me take a quick look and check what is going on with my favorite Android 4 :smile:

**Comment by grzesiek2010** [comment]
Ok that another bug is not on our side we can merge this pr.

**Comment by lognaturel** [comment]
@grzesiek2010 did you intend for the comment to be merged? Do you want this to go to production, check for crashes and then expand to the other media types?

**Comment by grzesiek2010** [comment]
Yes, I want this to be merged. I think it should be tested by our users and we can put on hold refactoring other media types since I've never seen any error report related to something else than audio.

**Review by lognaturel — APPROVED** [review]

**Pull request merged**
