### PR TITLE
Refactors AuthDialogUtility

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Closes #

#### What has been done to verify that this works as intended?
Needs testing. Since it required an authentication so I wasn't able to test it locally.

#### Why is this the best possible solution? Were any other approaches considered?
Since we are reusing the methods written in `GeneralSharedPreferences`, so it's the quickest and shortest solution.

#### Are there any risks to merging this code? If so, what are they?
I don't think there are any risks involved in merging this. But it would be even better if we could test it too.

### CODE REVIEW

**Comment by mmarciniak90** [comment]
@shobhitagarwal1612 Could you tell me what part of functionalities should be tested more carefully?
What behaviors may have changed?

**Comment by shobhitagarwal1612** [comment]
@mmarciniak90 This PR only deals with the part where credentials are set for an authenticated server using shared preferences when uploading instances

**Comment by mmarciniak90** [comment]
@shobhitagarwal1612 thanks for explanation.

Tested with success on Android 4.1, 4.4, 5.1, 6.0
I did not notice regression. I checked our ODK Aggregate test server. 
I was able to login. I verified login problem like incorrect URL/username/password.

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
Thanks @shobhitagarwal1612 and @mmarciniak90!

**Comment by mmarciniak90** [comment]
@opendatakit-bot unlabel "needs testing"

**Pull request merged**
