### PR TITLE
New goto_icon

### PR DESCRIPTION
**Pull request by grzesiek2010**

### CODE REVIEW

**Comment by lognaturel** [comment]
Thank you, @grzesiek2010! This now looks too big to me. :/ I think the scale of the original was good. This arrow looks fatter and shorter.

**Comment by grzesiek2010** [comment]
but not bigger than the save one you just mean that it's too fat itself?

**Comment by lognaturel** [comment]
Yes, that's right, I'm not talking about the overall size it takes up which is good now. I'm talking about the relative scale of the elements. The visual effect is that it looks more important than save when they should have the same visual impact.

**Review by yanokwa — APPROVED** [review]
Interestingly, this makes the ⋮ look smaller, but that's not what this PR is about.

**Comment by grzesiek2010** [comment]
> Interestingly, this makes the ⋮ look smaller, but that's not what this PR is about.

It's because we use different sizes in our app (I mentioned that yesterday during the meeting). I'll remember it so once we replace our pngs using vectors we can choose one size too and fix the issue.

**Pull request merged**
