### PR TITLE
Make offline basemaps available from general settings

### LINKED ISSUE #1610: Make offline basemaps available from general settings
When Google Maps SDK is selected as the Mapping SDK, if there are offline basemaps available, after the built in basemaps (Streets, Satellite, etc), display a "Offline Layers" heading and a list of offline layers. This will allow enumerators to set the offline layer once for use across multiple forms/instances. Offline map tiles are described in links from https://github.com/opendatakit/docs/issues/3

The dialog will need to scroll to fit all. This should be resilient to things like manual deletion of the selected offline base map. In that case, the selected basemap should default back to Streets.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #1610 

#### What has been done to verify that this works as intended?
I've tested new options.
I used a sample map from http://geoodk.com/mbtiles_howto.html
I used also not supported `PBF` format from https://www.mapbox.com/help/define-mbtiles/ to confirm this case is still handled properly.

#### Why is this the best possible solution? Were any other approaches considered?
It's the only solution I can see it's the easiest way.

#### Are there any risks to merging this code? If so, what are they?
It should be safe.

#### Do we need any specific form for testing your changes? If so, please attach one.
We can use AllWidgets form.

### CODE REVIEW

**Comment by lognaturel** [comment]
👍 This works really well when the Mapping SDK is set to OSM. The offline options are also available for Google Maps and that doesn't work. I think they should only be available for selection when the SDK is set to Google Maps.

**Comment by grzesiek2010** [comment]
@lognaturel 
yyy what do you mean by

> The offline options are also available for Google Maps and that doesn't work

it works for me and I can see an appropriate layer using both Google Maps and OSM.

**Comment by lognaturel** [comment]
Interesting. Then I suppose it doesn't work without the gmaps API key. It seems strange to have them in both places but I suppose that if it works it's ok.

And of course, this conflicts with the big refactor @jknightco is working on. As he announced in #collect-code, it makes sense not to accept any changes to the geo activities until that is complete. I think we should hold off on this.

**Comment by grzesiek2010** [comment]
> And of course, this conflicts with the big refactor @jknightco is working on.

yes, let's postpone it.

**Comment by shobhitagarwal1612** [comment]
Since the geo refactor PR has been on a hold for quite some time, so can this be merged?
@yanokwa @lognaturel

**Comment by lognaturel** [comment]
Thanks for bringing this back up, @shobhitagarwal1612. Yes, I think it would be fine.

I think sometimes users will only include features meant to overlay on a basemap in these custom layers. In that case they would want to be able to select both a basemap and layer. I think it's ok to leave this as-is and say that in that case they would need to use the old strategy -- select a basemap in settings and then choose the layer each time a geo widget is used. 

The alternative would be to provide two settings -- basemap and layer. I don't know how common that is, though, so perhaps we do that later if someone asks for it?

**Comment by shobhitagarwal1612** [comment]
:+1:

**Comment by mmarciniak90** [comment]
**Tested with success!**

Tested on Android: 4.1, 4.2, 4.4, 5.1, 6.0, 7.0, 8.1
Tested cases:
- supported and unsupported formats
- Google Maps SDK and OpenStreetMap SDK
- Geolocation widgets available in AllWidgets form
- light and dark theme

|screenshot_20180626-160749|screenshot_20180626-160736|screenshot_20180626-153138|screenshot_20180626-153132|
|---|----|----|---|

@opendatakit-bot label "behavior verified"
@opendatakit-bot unlabel "needs testing"

**Review by lognaturel — APPROVED** [review]

**Pull request merged**
