### PR TITLE
Improved styling the Form end screen

### LINKED ISSUE #5570: Styling the last screen before you finalize or send the form
As part of our work with https://github.com/getodk/collect/issues/5416, we want to style the last screen so it looks more aligned with where we are heading with the hierarchy view. 

### Proposed solution:

- Buttons aligned to the bottom for consistency  
- Text in the middle, as opposed to aligned to the top, because we don't want the page to look like something hasn't loaded in the centre.
- I think we will sort out the button styling in this issue https://github.com/getodk/collect/issues/5567

Screenshot 2023-05-04 at 10 57 31 AM

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5570 

#### What has been done to verify that this works as intended?
I've verified implemented changes manually:

Screenshot_1683536452

#### Why is this the best possible solution? Were any other approaches considered?
This is what we discussed during our Friday call.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
I think it doesn't require testing.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by seadowg — APPROVED** [review]

**Comment by seadowg** [comment]
@alyblenkin I'll send you a build on Slack

**Comment by alyblenkin** [comment]
Hey @grzesiek2010 @seadowg.  The last screen is looking good. The only thing is the background of the message is a bit dark. I was hoping we could do an opacity of the primary colour. I [mocked it up with 10% opacity](https://www.figma.com/file/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?type=design&node-id=1217%3A49540&t=wpDvV3KGmCimqhVM-1); however, that might be a little too light, so we should go with 15% opacity.

**Comment by seadowg** [comment]
@alyblenkin @grzesiek2010 maybe it makes sense for us to use a low emphasis version of our Primary color as the "Surface Container High" Material 3 color that ["Filled" Cards](https://m3.material.io/components/cards/specs#0f55bf62-edf2-4619-b00d-b9ed462f2c5a) (which this looks most like) use. That seems to fit with the default Material theme - Surface Container High looks like a faded version of their Primary. @grzesiek2010 it looks like that's another unreleased attribute, so we'd need to define it in `attrs.xml` until they release the new Material Components with the rest of the Material 3 colors.

**Comment by grzesiek2010** [comment]
@seadowg and then change `cardBackgroundColor` which defines what color is used as a background?

**Comment by seadowg** [comment]
@grzesiek2010 Yeah I think that's right

**Comment by grzesiek2010** [comment]
Ok It's ready. The new color compared to the old one:

| Now  | Before |
| ------------- | ------------- |
| Screenshot_1683703253 | Screenshot_1683667078 |

**Review by seadowg — APPROVED** [review]

**Review by alyblenkin — APPROVED** [review]

**Pull request merged**
