### PR TITLE
Rework Form List typography

### PR DESCRIPTION
**Pull request by seadowg**
Blocked by #3207.

This reworks typography for the form lists in the app ("Fill Blank Form", "Get Blank Form" etc).

The reasoning behind what we're doing is [here](https://forum.opendatakit.org/t/reworking-collects-typography/20634). I've also, while in the area, tried to clean up the layouts involved by reworking the structure, using standard values and extracting common styles.

There is also a small color change where the "This is an update..." on a form item now uses the theme's "secondary" (for our light theme that's the blue color used throughout the app) rather than a green color.

Here is before the changes:

Screenshot_1567001235

And after:

Screenshot_1567001057

#### What has been done to verify that this works as intended?

Ran tests, played around with effected screen.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by lognaturel — APPROVED** [review]
Works for me. @grzesiek2010 any reaction to using the secondary color rather than introducing a new one?

**Comment by grzesiek2010** [comment]
> any reaction to using the secondary color rather than introducing a new one?

LGTM.

**Review by grzesiek2010 — APPROVED** [review]

**Comment by bognasoldev89** [comment]
**Verified on Android:** 
4.2, 4.4, 5.1, 6.0, 7.0, 8.1, 9.0

**Verified cases:**
- Form Lists (Fill Blank Form, Edit Saved Form, Send Finalized Form, View Sent Form, Get Blank Form, Delete Saved Form)
- Light and Dark Theme
- LTR and RTL languages
- Rotating phone
- Minimizing phone
- Blocking phone

This rework looks and works great almost everywhere, app doesn't crash during going thorough form lists.
Here some examples of how good it looks (before and after):

| | |
| --- | --- |
| Screenshot_2019-09-12-11-19-02 | Screenshot_2019-09-12-11-54-22 |
| Screenshot_2019-09-12-11-27-56 | Screenshot_2019-09-12-11-57-22 |
| Screenshot_20190912-113607 | Screenshot_20190912-122951 |
| Screenshot_20190912-114414 | Screenshot_20190912-123127 |



Unfortunately on Android 4.2, on both Dark and Light Themes, with RTL languages, all lists look like that:

| | |
| --- | --- |
| Screenshot_2019-09-12-12-48-49 | Screenshot_2019-09-12-12-48-43 |

**Comment by bognasoldev89** [comment]
@seadowg is it OK for Android 4.2 to look like that (like in my comment)? Because you merged this pr and I'm a little confused.

**Comment by seadowg** [comment]
@bognasoldev89 sorry I jumped the gun on this after missing the part about Android 4.2. After chatting to @grzesiek2010 I think it makes sense to leave this merged unless there were any other problems blocking this from going through?

**Comment by bognasoldev89** [comment]
@seadowg I'm good with that, just was a little confused. I'm gonna comment my testing process better next time!

**Comment by seadowg** [comment]
@bognasoldev89 and I'll try and read the full report in future 😉

**Comment by bognasoldev89** [comment]
So if everything is clear I'll let opendatakit-bot do his work.

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Pull request merged**
