### PR TITLE
Formatted java code using official code style

### PR DESCRIPTION
**Pull request by max2me**
1. Formatted code.
2. Added additional step to Contributing.md about formatting code prior to committing it.

[Related issue 231](https://github.com/opendatakit/collect/issues/231)

### CODE REVIEW

**Comment by lognaturel** [comment]
#231 also includes configuring checkstyle and making sure it is invoked by CircleCI. I think it makes sense to do here and make sure the code and the file match. I'd probably start from [this file](https://github.com/noveogroup/android-check/blob/master/android-check-plugin/src/main/resources/checkstyle/checkstyle-easy.xml) and do things like remove the javadoc requirement. You can also take a look at the [hard file](https://github.com/noveogroup/android-check/blob/master/android-check-plugin/src/main/resources/checkstyle/checkstyle-hard.xml) to see if anything there should be included but basically I think it shouldn't be all that strict.

**Comment by max2me** [comment]
@lognaturel I've added easy checkstyle file and ran the check... so we are looking at a little over 500 errors across 100+ files.

Most common "offenders":
* Field names do not match appropriate pattern
* Trailing spaces
* Empty blocks
* Unnecessary nested blocks

Should I fix those issues up or add suppression instead?

**Comment by lognaturel** [comment]
Ooh, exciting. How about this, can you start by committing the checkstyle file so @yanokwa @batkinson and I and anyone else who wants to can confirm it works for the norms we want to establish?

Once we've agreed on that, @batkinson What do you think the best way to structure the commits for these fixes will be? I think some like spacing issues are trivial and can be committed all at once. But there is the possibility to introduce bugs with some of the other fixes.

**Comment by max2me** [comment]
Done :) After pulling simply run `gradlew checkstyle` and then look at the report at `collect_app/build/reports/checkstyle/checkstyle.html`

**Comment by lognaturel** [comment]
Now that I see how this is playing out, I think it would have been better to separate the space fixes and the style check automation. My mistake! Do go ahead and suppress checkstyle for now.

Can you please add credit for the checkstyle file in a comment along with a direct link to the original?

**Comment by max2me** [comment]
@lognaturel I believe this is ready to be merged.

**Pull request merged**
