### PR TITLE
Update FileManagerTabs to use viewpager2 and share the same material layout with QRCodeTabsActivity

### PR DESCRIPTION
**Pull request by grzesiek2010**
#### What has been done to verify that this works as intended?
I tested the new changes manually.

#### Why is this the best possible solution? Were any other approaches considered?
In the app we use tabs in two places. Both look different and use different viewpagers. I Updated the viewpager to viewpager2 in FileManagerTabs and refactored the code to use the same layout file in both tabs. SO now the UI is consistent and we have less duplicated code.

The table below show screenshots before and after:

| Light theme  | Dark theme | Magenta theme | Configure via QR code |
| ------------- | ------------- | ------------- | ------------- |
| Screenshot_1591911772  | Screenshot_1591911750  | Screenshot_1591911790  |  Screenshot_1591911565  |
| Screenshot_1591911582  | Screenshot_1591911608  | Screenshot_1591911552 | No changes |

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It would be good to test tabs we use in FileManagerTabs (Delete Saved Form from the main menu) and QRCodeTabsActivity (Configure via QR code from the main menu) but I would focus on the layouts, the functionality itself shouldn't be affected.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by seadowg — APPROVED** [review]
Wow that's much cleaner!

**Comment by mmarciniak90** [comment]
@grzesiek2010 I noticed that opening `Blank Forms` tab in`Delete Saved Form` view causes unexpected changes in the header with 'Delete Saved Form' text. The search icon is doubled for a second.

ezgif com-video-to-gif(1)

**Comment by mmarciniak90** [comment]
@getodk-bot unlabel "needs testing"

**Comment by grzesiek2010** [comment]
>  noticed that opening Blank Forms tab inDelete Saved Form view causes unexpected changes in the header with 'Delete Saved Form' text. The search icon is doubled for a second.

Fixed.

**Comment by mmarciniak90** [comment]
**Tested with success**

Verified on Android: 7.0, 8.1, 9.0

Verified cases:
- 3 themes
- vertical and horizontal orientation
- Delete Saved Form view
- Configure via QR code view 
- jumping between tabs

**Comment by kkrawczyk123** [comment]
Verified on Androids: 5.1, 7.1 and 10.

@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"

**Pull request merged**
