### PR TITLE
Rebasing ui-refresh branch onto master

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**

### CODE REVIEW

**Comment by lognaturel** [comment]
I think we need to be very careful with how these updates are done so that the diff between `master` and `ui-refresh` stays very clean. 

In this case, it's not clear to me that the merge commit is necessary. I think you could have done a `git rebase upstream/ui-refresh` into your local `ui-refresh` instead of a merge.

I'm also surprised when I look at [a diff against master](https://github.com/opendatakit/collect/compare/master...shobhitagarwal1612:ui-refresh) that there are two commits corresponding to the audio widget.

What if in your local `ui-refresh` you first do a `git rebase upstream/ui-refresh` followed by a `git rebase upstream/master`? Don't forget to `fetch upstream` first. I think you'll get some conflicts that you can then fix in one or more commits. I believe that if you submit that as a pull request, I should be able to rebase it into upstream/ui-refresh with no conflicts.

If anyone has done this kind of big feature development over a few months, it would get great to get some advice on the best approach to branches in that context.

**Comment by shobhitagarwal1612** [comment]
@lognaturel When I do `rebase upstream/master`, the recent changes done by @grzesiek2010 overwrites the files in `origin/ui-refresh` as we would guess. When a PR is submitted off `origin/ui-refresh` to `upstream/ui-refresh` then those changes of @grzesiek2010 that were merged during rebasing re-emerge as conflicts in this PR and thus those are resolved as you might have noticed in this [commit](https://github.com/opendatakit/collect/pull/1163/commits/8a242bd6276a344bc5b96669d376d227020bb97c) 

The extra commit which is for merging can be avoided if you directly force push the `upstream/ui-refresh` after rebasing onto `upstream/master`, without submitting a PR

**Comment by lognaturel** [comment]
I'm going to need to look at this again tomorrow! I'm sure your explanation is right. I'll wait to merge anything else until this is taken care of.

**Comment by shobhitagarwal1612** [comment]
Thank you

**Comment by lognaturel** [comment]
We've decided that @shobhitagarwal1612 will "own" keeping `ui-refresh` up to date and do it without pull requests so that he can make sure it never has too many conflicts with master.

**Pull request closed without merging**
