### PR TITLE
Issue #2264 None translatable string-array time_scale in GeoTrace

### LINKED ISSUE #2264: None translatable string-array time_scale in GeoTrace
#### Software and hardware versions 
Collect v1.15.0, Android v4.4.2

#### Problem description
In the widget GeoTrace the fixed strings "Seconds" and "Minutes" are used. They come from the String-Array time_scale which is marked as not translatable. 

#### Steps to reproduce the problem
Fill in an empty "all-widgets" form and swipe (~42 times) until you get to the geotrace widget.
Click on the add marker button (+) and select automatic mode in the dialog Select GeoTrace mode.
Then you should see the dropdown box with secons or minutes.

#### Expected behavior
The strings Seconds and Minutes should be displayed in the selected language of the user.

### PR DESCRIPTION
**Pull request by rk635636**
Closes #2264 

#### What has been done to verify that this works as intended?
I tested it.
Android v7.1.1
#### Why is this the best possible solution? Were any other approaches considered?
I added translations for `Minutes` and `Seconds` strings in almost all languages. We manually have to add translations because the `Minutes` and `Seconds` come from the String-Array time_scale which is marked as not translatable.
#### Are there any risks to merging this code? If so, what are they?
No
#### Do we need any specific form for testing your changes? If so, please attach one.
No
#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No
#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew pmd checkstyle lint findbugs` and confirmed all checks still pass.
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by lognaturel** [comment]
This is looking pretty good! No need to close it -- you should be able to make any changes necessary in this branch and the PR will update. If you have any questions, you can come find other devs on the [Slack](http://slack.opendatakit.org/) in the #collect-code channel.

Unfortunately, translations done inline are replaced so for this you should only change the base `strings.xml`. You can read more about translations at https://github.com/opendatakit/collect#contributing-translations and https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#strings.

The resources should be called `seconds` and `minutes` in case they can be used somewhere else in the future.

**Comment by rk635636** [comment]
Thank you very much for your response @lognaturel . I will reopen this request.

**Comment by rk635636** [comment]
I think there is some problem. I'm closing this pull request and will make a new pull request.

**Comment by rk635636** [comment]
Created a new PR #2273

**Pull request closed without merging**
