### PR TITLE
Fix for dynamic seeds when randomizing choices

### PR DESCRIPTION
**Pull request by yanokwa**
Addresses https://github.com/opendatakit/javarosa/issues/384

#### What has been done to verify that this works as intended?
I tried the 2.12.1-SNAPSHOT from JavaRosa at https://github.com/opendatakit/javarosa/pull/385 in a local build

#### Why is this the best possible solution? Were any other approaches considered?
This is a commit that will be used in an upcoming hot-fix.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Instead of failing on forms with dynamic seeds, this should use that seed.

#### Do we need any specific form for testing your changes? If so, please attach one.
I used this form [rand.xml.zip](https://github.com/opendatakit/collect/files/2623306/rand.xml.zip).

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [X] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [X] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [X] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by yanokwa** [comment]
Note that this PR uses the release version that isn't out yet and so the build will fail.

**Review by ggalmazor — APPROVED** [review]
I tried this yesterday too. This is looking good.

**Comment by ggalmazor** [comment]
The attached form doesn't quite capture all the different behavior of dynamic seeds in the `randomize()` function. Use this one instead: [rand.zip](https://github.com/opendatakit/collect/files/2624081/rand.zip)

- The choices list is bigger (100 elements)
- Seeds are correctly typed to `int`
- There are four selects using different seed combinations:

| # | Seed `calculate` expression | Example seed value | Behavior |
| --- | --- | --- | --- | 
| 1 | `once(decimal-date-time(now()))` | `17863` | The seed won't change until a day has passed. All devices will use the same seed in all instances of the form that are created the same day. Once the instance is generated, the seed won't ever change. |
| 2 | `once(substr(decimal-date-time(now()), 10))` | `01355324` | This expression will use the last 8 numbers of the decimal part of the `decimal-date-time()` function, which is less probable to repeat across devices and different days. Once generated won't ever change for an instance |
| 3 | (no `calculate`) | `42` | The value is fixed in the instance. All devices will have the same seed for all the generated instances |
| 4 | (no seed) | N/A | Every time the select widget appears, a new ordering is produced |

Insights:
- It looks like this is working
- We should document different ways to deal with seeds on the docs

**Comment by yanokwa** [comment]
The above is a great summary and mostly correct! 

The first gotcha is that [pyxform forces calculate to string](https://github.com/XLSForm/pyxform/issues/70), but I don't think it matters in this case. 
The second gotcha is that `once(decimal-date-time(now())` seems to generate a float (e.g., `17863.753929050927`) and that float, when evaluated seems to be cast to an int which then results in the same value. 

That seems like a bug and should probably block https://github.com/opendatakit/javarosa/pull/389

**Comment by ggalmazor** [comment]
> The first gotcha is that pyxform forces calculate to string, but I don't think it matters in this case.

Okey dokey

> The second gotcha is that once(decimal-date-time(now()) seems to generate a float (e.g., 17863.753929050927) and that float, when evaluated seems to be cast to an int which then results in the same value.

It turns out that `ParkMiller` - the cross-platform algorithm we're using - requires integer seeds. Therefore, JR will try to cast the seed to `Long`, which involves truncating decimals.

I don't know what are the consequences of using floating decimal point numbers as seeds with `ParkMiller`. We might need to sync this change with other clients that implement this, but it feels easier to use a different seed generator expression like the one I'm using in the form: `substr(decimal-date-time(now()), 10)`

**Review by shobhitagarwal1612 — APPROVED** [review]

**Comment by kkrawczyk123** [comment]
**Testes with success!**
Verified on Androids 4.1, 4.2, 4.4, 6.0 and 8.1.

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Pull request merged**
