### PR TITLE
Spaces in submission URLs crashes app when sending forms

### PR DESCRIPTION
**Pull request by batkinson**
Related to #175. This addresses the critical stability portion, but it _does not_ change the submission handling to catch runtime exceptions. That would have required more invasive changes and the recommendation would have introduced a bit of a code smell.

### CODE REVIEW

**Comment by yanokwa** [comment]
@batkinson Can you make sure url_error_whitespace, password_error_whitespace and username_error_whitespace in strings.xml are title case? I'd be happy to merge after that.

**Comment by batkinson** [comment]
> @batkinson Can you make sure url_error_whitespace, password_error_whitespace and username_error_whitespace in strings.xml are title case? I'd be happy to merge after that.

Hi @yanokwa, I am happy to make any adjustments you feel are appropriate/necessary. I pushed what I think you were suggesting, but I just want to double-check your intent. I am happy to update the PR as needed, so don't hesitate to correct mercilessly here.

I don't believe my changes actually touched the message content. I assumed you were asking that I make the content of those messages have initial capital letters to be consistent with other similar messages, or something else? I updated all the translations I could, but how would you like to handle others?

After revisiting this, I noticed that url_error_whitespace is no longer used and I pruned it.

**Comment by yanokwa** [comment]
Ugh, it looks like I was looking at the wrong rev. Regardless, your changes are the correct ones. And since you asked, let's do the same whitespace trimming on username and password and also throw away those translations.

**Comment by batkinson** [comment]
That makes perfect sense. Testing now, I was thinking that the user/pass messages were conspicuously inconsistent too. This will bring everything into alignment, even between platform variants. I will push those changes shortly as well. Thanks @yanokwa.

**Comment by batkinson** [comment]
After making the changes and testing locally, I am not sure treating user/pass the same way is a no-brainer. With URLs, filtering _internal spaces_ makes sense because using spaces aren't valid and should be URL-encoded anyway. This is consistent with RFC 2396 on page 33:

> For robustness, software that accepts user-typed URI should attempt to recognize and strip both delimiters and embedded whitespace.

However for username and password, there is no similar username/password encoding that can be used. Filtering embedded whitespace, and even trimming eliminates valid input that could prevent login from succeeding.

My inclination is to leave user/pass handling alone in case anyone has existing user/pass data that contains embedded spaces. I ran some quick tests locally, and with the latest version of Aggregate it appears that you can't use embedded whitespace for username, but you can use it for password.

Thoughts?

**Comment by yanokwa** [comment]
Agreed with your conclusion.

**Pull request merged**
