### PR TITLE
Attempt to prevent failing of builds on circle-ci

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Closes #

#### Do we need any specific form for testing your changes? If so, please attach one.

### CODE REVIEW

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
Ooh! Good idea. That has been very annoying...

**Comment by lognaturel** [comment]
So far so good but master always fails because of #2020, oops!

**Comment by shobhitagarwal1612** [comment]
I am not able to see the failing test within circle ci's artifacts. Looks like that is somehow broken too.

**Comment by lognaturel** [comment]
It’s a connected test so it runs on Firebase. I see the report fine but you may not have Firebase access. 

The test that fails is the last one of the group that does scale down. It does fail for me locally as well.

**Comment by shobhitagarwal1612** [comment]
Thanks for the info. I'll look into it

**Comment by lognaturel** [comment]
Thanks! If you don’t have time I can also quickly fix it.

**Comment by shobhitagarwal1612** [comment]
I am unable to run the test locally due to some bug in Android Studio 3.1. I can build the app and run it on my device but when I run the connected tests, it starts looking for the older version of the app and fails.

It would really appreciate if you could take this one.

**Pull request merged**
