### PR TITLE
WIP: Layers

### LINKED ISSUE #1042: Changing layers when the map view is open
Currently we allow selecting basemap in "General Settings" and we are not able to change selected layer during the work. We can only choose offline layers.

It should be possible to do that - be able to choose online layers as well.

### PR DESCRIPTION
**Pull request by grzesiek2010**
This PR is in reference to resolve #1042

### CODE REVIEW

**Comment by grzesiek2010** [comment]
Could someone explain me how offline layers should work? @lognaturel you said yesterday that files should be saved when we use OSM but I can't notice this behavior. I've tried to download example files eg from https://www.mapbox.com/help/define-mbtiles/ but then app crashes if I try to use them.

**Comment by lognaturel** [comment]
The only way I've used cached tiles is by navigating around a osmdroid map to load the tiles and then loading that same map offline. Last time I looked at this, it was creating a hierarchy of folders but it looks like now tiles are cached in an sqlite database by default (https://github.com/osmdroid/osmdroid/wiki/Tile-Caching). I've verified that this is working as expected.

The geo features were originally contributed from geodk and I followed [this tutorial](http://geoodk.com/mbtiles_howto.html) successfully with that sample MapBox mbtile file. The layers go in `/sdcard/odk/layers`. However, when I use the mbtiles file that you linked to, I get 
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getHeight()' on a null object reference
	at org.odk.collect.android.spatial.OsmMBTileSource.createFromFile(OsmMBTileSource.java:93)
	at org.odk.collect.android.spatial.OsmMBTileProvider.<init>(OsmMBTileProvider.java:0)
	at org.odk.collect.android.spatial.MapHelper$1.onClick(MapHelper.java:230)
	at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1119)
	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1155)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3152)
	at android.widget.AbsListView$3.run(AbsListView.java:4067)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```
Is that the same issue you have? That looks like it should be filed as a separate issue.

All this suggests that the layers button was designed just to show offline tiles rather than showing all available basemaps.

I think showing available basemaps is probably a useful thing but we should discuss the implications. I'll add some thoughts to the issue.

**Comment by grzesiek2010** [comment]
@lognaturel look at my comment here https://github.com/opendatakit/collect/pull/1087#issuecomment-305445087

i think there is just something wrong with that file because if I download a file using the link you attached everything is ok without any changes.

**Comment by lognaturel** [comment]
@grzesiek2010 I'm going to close this because it's not yet clear enough what exactly this should do. We should first aim to refine a spec at #1042 and then come back to it! Please keep the branch for now so that we can refer back to it once we know what the requirements are.

**Pull request closed without merging**
