### PR TITLE
Rtl problem with mobile language starts from right

### LINKED ISSUE #1981: RTL writing system is not visible on all views
#### Software and hardware versions 
Collect v1.13.2
Devices with Android: 4.1, 4.2, 4.4, 6.0, 7.0, 8.0.

#### Problem description
RTL writing system is not visible on all views 

#### Steps to reproduce the problem
1. User uses Collect on RTL language
2. User opens Fill Blank Form / Get Blank Form / Delete Saved Form or starts filling some form
3. User sees that text is not start from the right of the page and continues to the left.

#### Expected behavior
* User sees text which starts from the right of the page and continues to the left on all views
* On one of my devices to tests - Huawei Y5 with Android 5.1 - RTL languages works as expected on most of all views.

#### Examples

| View | Android 6.0 - Moto G4 | Android 5.1 - Huawei Y5 | 
| ---- | ---- | ---- |
| Get Blank Form | screenshot_20180307-164007 | screenshot_2018-03-07-14-40-09 | 
| Fill Blank Form | screenshot_20180307-163619 | screenshot_2018-03-07-14-37-37 | 
| Simple widget | screenshot_20180307-163716 | screenshot_2018-03-07-14-37-30 | 
| Select one quick appearance | screenshot_20180307-164733 | screenshot_2018-03-07-14-46-32|

### PR DESCRIPTION
**Pull request by kareemhamdy100**
make it start from left done

Closes #1981 

#### Are there any risks to merging this code? If so, what are they?
i think this will not have any risk  i try it in my application no thing change  when I use arabic language 
in my mobile 

#### Do we need any specific form for testing your changes? If so, please attach one.

### CODE REVIEW

**Comment by grzesiek2010** [comment]
@kareemhamdy100 why did you set `supportsRtl` to false? We want to support RTL languages.

**Comment by kareemhamdy100** [comment]
because the hole application will  be  change direction  when  the mother language of the mobile change to be (Arabic) for example  but you don't need english  things to change  so  
Arabic things will display in  the views  with the correct position and english to 
in all languages  the views  will in the same position ( textBox, checkBox,.....)

**Comment by kareemhamdy100** [comment]
when mother language change all views positions changes but this what we don't need 
we need all position of views  to be in same  only the language change  so I made this to prevent conflict happen
@grzesiek2010

**Comment by lognaturel** [comment]
@kareemhamdy100 When a language that is written from right to left is used, the layouts should change. That is what that attribute is for! Issue #1981 is to make sure all layouts are configured such that they adapt to the language direction.

**Pull request closed without merging**
