### PR TITLE
Replace Log with Timber Widget Folder

### PR DESCRIPTION
**Pull request by nmpatsal**
I had pushed code that was unrelevant to this issue so I committed a deletion of all unrellated changes.

### CODE REVIEW

**Comment by lognaturel** [comment]
You still have a number of changes unrelated to this pull request! Also, some of your changes are showing up as merge conflicts and I think that's because you branched off of an older version of master. Make sure to follow the instructions [here](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#submitting-a-pull-request), especially for syncing your fork. You can look right above this message to see merge conflicts and click on the "Files changed" tab to make sure that the ONLY changes for this PR are related to replacing Log with Timber.

You will also need to fix several lint and checkstyle failures that are causing the build to fail. You can run `./gradlew lint` and `./gradlew checkstyle` or see the results [here](https://circleci.com/gh/opendatakit/collect/389#artifacts/containers/0).

**Comment by lognaturel** [comment]
I just noticed that this pull request is off of your master branch. I'm going to close this pull request and I think it will be easier for you to update your local master following the fork syncing instructions and then create a new branch to have only the relevant changes.

**Comment by nmpatsal** [comment]
@lognaturel I created a new branch where I am going to continue but how can I get the changes from widgets because I made them in my master branch and now they are already there but I can not see it in diff .

**Comment by lognaturel** [comment]
@nmpatsal [This](http://stackoverflow.com/questions/1994463/how-to-cherry-pick-a-range-of-commits-and-merge-into-another-branch/1994491#1994491) should help. Or I recommend searching for what you are trying to accomplish and seeing what resources you find.

**Pull request closed without merging**
