### PR TITLE
 Update all_widgets.xml and AllWidgetsFormTest to match XLSForm

### LINKED ISSUE #2035: Update all_widgets.xml and AllWidgetsFormTest to match XLSForm in README
As @edyasikpo noticed [here](https://github.com/opendatakit/collect/issues/2002#issuecomment-373554661), the `all_widgets.xml` form used in `AllWidgetsFormTest` is out of date with the form linked to from the README.

To update the form and test:
- [ ] Download the form from the README to an Excel file and then [convert it to XML](http://docs.opendatakit.org/form-design-intro/#javarosa-compliant-build-tools)
- [ ] Replace the existing `all_widgets.xml` document
- [ ] Move, add and remove widget tests from `AllWidgetsFormTest` to match the new version. For the `image-map` one that will be added, a body with just the `screenshot` call is sufficient for now

### PR DESCRIPTION
**Pull request by vigneshtdev**
Closes #2035 

#### What has been done to verify that this works as intended?

- Was able to build the project with no errors.

- Ran ` ./gradlew lint` and `./gradlew checkstyle ` with zero error(s) being found.

### CODE REVIEW

**Comment by lognaturel** [comment]
Welcome, @vettyvignesh and thanks for taking this on! There's one more quality check that's important to run and that's `pmd`. There's one failure now that you can fix and commit to this branch to update the pull request.

**Comment by vigneshtdev** [comment]
@lognaturel  cirlceci: build_debug failed due to an error while downloading some dependency. I am not able to find a way to rectify it, so please help.

As for circleci: test_unit, where can I find a more detailed report?

**Comment by lognaturel** [comment]
You can see more details by clicking `Details` below next to the build name! For `test_unit`, the failure is due to a failed PMD check. And then `build_debug` can't run because it doesn't have the build it needs.

**Comment by vigneshtdev** [comment]
But I don't think  I added a dependency on my own! & as for the failed pmd check I would like to see the line number causing it to fail.

**Comment by lognaturel** [comment]
@vettyvignesh Did you run pmd locally with `./gradlew pmd`? Alternately you can click on "Details" next to `test_unit` and then on the Artifacts tab.

**Comment by vigneshtdev** [comment]
The problem was an unused method `onVisibleCheckBox`. Thanks for the help @lognaturel .

**Comment by lognaturel** [comment]
Thank you, @vettyvignesh, this is looking good. The Espresso tests are not run on CircleCI so you'll have to make sure you run them locally to verify they're working. You can do that with `./gradlew connectedDebugAndroidTest` or in Android Studio by clicking on the play arrow next to the class name in `AllWidgetsFormTest`. You'll see that some of the tests are failing.

**Comment by lognaturel** [comment]
I'm going to close this for now and if you'd like to pick it back up @vigneshtdev you can always re-open the PR!

**Pull request closed without merging**
