### PR TITLE
Allow to create lint-result.xml file

### LINKED ISSUE #1377: Can't see lint-result.xml file anymore
#### Software and hardware versions 
Current master branch

#### Problem description
Since we have merged https://github.com/opendatakit/collect/pull/1344 I can't see `lint-result.xml` file in `build -> reports -> lint` as it was before.

#### Steps to reproduce the problem
run `./gradlew lint` command and check mentioned location

#### Expected behavior
I find this file really helpful, so I would like to keep it.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #1377 

#### What has been done to verify that this works as intended?
I've ran `./gradlew lint` command to confirm that file is created

#### Are there any risks to merging this code? If so, what are they?
No, it's safe.

### CODE REVIEW

**Comment by grzesiek2010** [comment]
@shobhitagarwal1612 let me know if I missed anything but I think this file is really important it helps me for example to find problems in my code quickly. Did you decide to do that on purpose?

**Comment by shobhitagarwal1612** [comment]
Now an `html` report is being generated too. I find the html report more user friendly. So that's why I turned off the `xmlReport` option. 
You can find it where other reports are generated.

`\collect\collect_app\build\reports\lint\lint-debug.html`

**Comment by grzesiek2010** [comment]
Before we kept both... don't know what others prefer but I prefer xml file.

**Comment by shobhitagarwal1612** [comment]
In that case, we must keep both files 👍

**Review by shobhitagarwal1612 — APPROVED** [review]

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
For the hardcore like @grzesiek2010 who prefer to read XML!! 😊

**Pull request merged**
