### PR TITLE
Refactored the code in Collect class

### PR DESCRIPTION
**Pull request by grzesiek2010**
#### What has been done to verify that this works as intended?
I've tested updates with saved settings again.

#### Why is this the best possible solution? Were any other approaches considered?
@lognaturel sorry I haven't implemented this changes before (during #1660 for example) but only now I realized it might be tricky. I mean someone may save something in SharedPreferences before we call `loadDefaultValuesIfNeeded()` so I've moved it up and added a comment.

I've refactored some other things by the way.

#### Are there any risks to merging this code? If so, what are they?
No.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

### CODE REVIEW

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
@mmarciniak90 @kkrawczyk123 This touches the same code as #1662 and it would be great to verify them together. Basically we need to make sure settings are preserved on update and are properly set to defaults on a clean install. This code changes the implementation slightly for font size and language so it would be good to verify those especially.

**Comment by kkrawczyk123** [comment]
I checked that and it works as intended, saved settings do not reset after updating application.

**Comment by kkrawczyk123** [comment]
@opendatakit-bot unlabel "needs testing"

**Comment by kkrawczyk123** [comment]
Collect crashes when you try to rotate screen. Screen becomes dark and you can see a message "ODK Collect has stopped".

**Comment by lognaturel** [comment]
Thank you, @kkrawczyk123!

**Comment by kkrawczyk123** [comment]
Now, everything works fine.

**Pull request merged**
