### PR TITLE
 Handle select items with null values

### LINKED ISSUE #3142: NullPointerException in SelectOneListAdapter.java:105
#### Software and hardware versions 
Collect v1.22.1 and older versions

#### Problem description
`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
       at org.odk.collect.android.adapters.SelectOneListAdapter.setUpButton(SelectOneListAdapter.java:105)
       at org.odk.collect.android.adapters.SelectOneListAdapter.setUpButton(SelectOneListAdapter.java:38)
       at org.odk.collect.android.adapters.AbstractSelectListAdapter$ViewHolder.bind(AbstractSelectListAdapter.java:216)
       at org.odk.collect.android.adapters.SelectOneListAdapter$ViewHolder.bind(SelectOneListAdapter.java:90)
       at org.odk.collect.android.adapters.AbstractSelectListAdapter.onBindViewHolder(AbstractSelectListAdapter.java:82)
       at org.odk.collect.android.adapters.AbstractSelectListAdapter.onBindViewHolder(AbstractSelectListAdapter.java:60)`

#### Steps to reproduce the problem
Try to use this form: 
[selectOne.xml.txt](https://github.com/opendatakit/collect/files/3273143/selectOne.xml.txt)

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #3142 

#### What has been done to verify that this works as intended?
I tested the attached form.

#### Why is this the best possible solution? Were any other approaches considered?
Having items (in select one or multiple questions) that contain null values is a bug in a form. I decided to just filter all items and remove those with null values. It's much easier because we have one parent class where we can do that, but checking for nulls in all places we use items would be very difficult.

Additionally, if items with null values existed I added a toast which informs about that.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It's not a risky pr. Testing the form attached to the issue would be enough.

#### Do we need any specific form for testing your changes? If so, please attach one.
The form attached to the issue.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by lognaturel** [comment]
Thanks for your patience with this. This is a crash you saw in Firebase Crash, right? How frequent is it? I don't think `pyxform` makes this case possible so I imagine it's quite rare.

It feels like having a select option without a value should break the form. Even with a long toast, it seems quite likely that a form designer would miss it or that an enumerator wouldn't know what to do with the information. It's also one more translation for a case that is very rare (right?).

**Comment by grzesiek2010** [comment]
Yes it was rare I can't find it know to tell you exact numbers but rather rare (I don't know why I didn't attach a link to that reports).

So you would prefer to exit a form/skip such a question over handling it in the way I did? I think it would be fine too... the most important thing is to catch it and avoid crashing.

**Comment by lognaturel** [comment]
> Yes it was rare

👍 

The challenge is that this issue is only discovered when that specific choice is displayed and selected, right?

I was surprised that this wasn't caught at the JR level so I tried the form from your issue and I actually got a dialog that says "don't know xml value!..." which seems like the right thing. That message could certainly be made more useful but since the problem is rare, doing it at the JR level seems like the right thing. Were you actually able to reproduce the crash? Going through the stack trace, I'm not seeing exactly where it happens, can you point out what `equals` call causes it?

Even beyond all that, doing an iteration pass over the full set of choices could be time-consuming if the choice list is long, right? Doing that for every single select doesn't seem ideal.

**Comment by grzesiek2010** [comment]
>  Were you actually able to reproduce the crash?

It happens if you try to open such a saved forms.

**Comment by grzesiek2010** [comment]
The crash is still visible in v1.24 https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/c388f4d7c49c7c3cdefb2c5924ae1f17?time=last-seven-days&sessionId=5DAEE665000700016BB28EF7E7042DFD_DNE_0_v2

we should make a decision on how to handle it.

**Comment by lognaturel** [comment]
For now we'll make sure that there's no crash. We won't filter out items without values because it's potentially a slightly expensive operation for a long list and it could (?) be a deliberate choice.

**Pull request closed without merging**
