### PR TITLE
Localize response when default Aggregate response is given

### LINKED ISSUE #1010: When default Aggregate success message is sent, show in current language
#### Software and hardware versions 
Collect v1.6.1

#### Problem description
#336 enabled custom server responses. This is great when an organization configures custom messages but not so great for organizations who use standard Aggregate because they end up with the English message "full submission upload was successful!" no matter the language Collect is set to.
screen shot 2017-05-04 at 10 00 04 am

#### Steps to reproduce the problem
1. Change the phone language to anything but English
1. Successfully send a form

#### Expected behavior
The success message should match the Collect language when it is the standard Aggregate message.

#### Other information 
I propose adding a constant for the standard Aggregate text and adding something like
```
if (customResponse is STANDARD_AGGREGATE_SUCCESS_TEXT and language is not English)
    show localized success string (R.string.success)
else
   show customResponse
```
How does that sound?

### PR DESCRIPTION
**Pull request by grzesiek2010**
This PR is in reference to resolve #1010

### CODE REVIEW

**Comment by lognaturel** [comment]
I was imagining we'd just go with "Success" in whatever language -- the existing `success` string that's already localized. I don't think "full submission upload was successful!" is a particularly more helpful message. That would require either checking for languages other than English in `localizeDefaultAggregateSuccessfulText` or just using `success` for every language.

What do you think @grzesiek2010 @yanokwa?

**Comment by grzesiek2010** [comment]
@lognaturel Please confirm I understand well: so you just want to replace https://github.com/opendatakit/collect/pull/1095/files#diff-6b460960d294fb55ef800455a6dfa146R283 with https://github.com/opendatakit/collect/blob/master/collect_app/src/main/res/values/strings.xml#L178 ?

So if a message from the aggregate is "full submission upload was successful!" we just use "success" message and otherwise we use the original one. Am I right?

**Comment by lognaturel** [comment]
Yes, exactly! And I checked with @yanokwa, he agrees.

**Comment by lognaturel** [comment]
One more clarification. Let's just go ahead and use "Success" for English too so you don't even have to check for the current Collect language.

**Comment by grzesiek2010** [comment]
@lognaturel done

**Pull request merged**
