### PR TITLE
Add audit event for disabling/enabling background recording

### LINKED ISSUE #4380: Log audit events for background recording
Follow on to #4343 

- [x] Given I've enabled "Background audio" in Experimental settings
And I'm filling out a form
When I open the overflow menu
And I uncheck "Record audio"
Then a "background audio disabled" [event](https://docs.getodk.org/form-audit-log/#event-types) is added to the audit log

- [x] Given I've enabled "Background audio" in Experimental settings
And I'm filling out a form
And I've unchecked "Record audio"
When I open the overflow menu
And I check "Record audio"
Then a "background audio enabled" [event](https://docs.getodk.org/form-audit-log/#event-types) is added to the audit log

### PR DESCRIPTION
**Pull request by seadowg**
Closes #4380 

#### What has been done to verify that this works as intended?

Added tests.

#### Why is this the best possible solution? Were any other approaches considered?

Not a lot to comment on here.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Should just add the feature. Good to test that events appear in the audit log as expected.

#### Do we need any specific form for testing your changes? If so, please attach one.

Any form with background audio and auditing enabled.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by lognaturel — APPROVED** [review]

**Comment by mmarciniak90** [comment]
@seadowg I compared behavior for audio events with location events and I noticed that there is no event when you start a form (location event is visible). If you don't change the audio settings, there isn't any information about audio events in audit.

[audit-audio.csv.txt](https://github.com/getodk/collect/files/5965571/audit-audio.csv.txt)

Additionally, when permissions aren't granted, location events are visible but audio events are not.
[audit-permission.csv.txt](https://github.com/getodk/collect/files/5965574/audit-permission.csv.txt)

I used this form 
[AuditTestLocationBackgroundAudio.xml.txt](https://github.com/getodk/collect/files/5965603/AuditTestLocationBackgroundAudio.xml.txt)

**Comment by seadowg** [comment]
> I noticed that there is no event when you start a form (location event is visible)

We never planned to have an event for this, but it's a great point as we should make sure to point out in docs what event the start of the recording corresponds to (probably "form start" and "form resume" looking at https://docs.getodk.org/form-audit-log/).

> Additionally, when permissions aren't granted, location events are visible but audio events are not.

Ah that's an interesting point. @lognaturel do you think we should add an event for if the record permission is denied so it's clear if that happens why the recording is missing?

**Comment by lognaturel** [comment]
> point out in docs what event the start of the recording corresponds to

I've made a note of this.

Regarding permissions, this would be to handle the case where someone opens the form with granted audio permissions and then revokes the permission? When we had previously talked about this I didn't feel it was necessary given how unlikely that is but it's true that it gives a data collector an "out". @seadowg is it a big thing to add? Now I'm remembering there may be a relatively easy way to listen for those Android pref changes.

**Comment by seadowg** [comment]
@lognaturel I was more thinking about the case where they open the form without audio permissions and then deny them. I guess the absence of a recording flags that that enumerators aren't granting permissions it feels like it might be nice to have something explicit in the log so analysts know what's gone wrong.

**Comment by lognaturel** [comment]
> nice to have something explicit in the log so analysts know what's gone wrong.

I agree. If it's not a big lift, could you please see about adding for v1.30?

> open the form without audio permissions

I think you mean with and if so, that's what I was trying to express. It shouldn't currently be possible to open the form without audio permissions.

**Comment by mmarciniak90** [comment]
Final results for this PR:
* Event `background audio enabled` is visible in the audit file
* Event `background audio disabled` is visible in the audit file
* If user doesn't change the audio settings, there isn't any information about audio events in the audit.
* If microphone permission is not granted, there is no possibility to fill form so the "permission" events in the audit are not required.

Tested on Android versions: 7.0, 7.1, 8.1, 9.0, 10.0

@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"

**Pull request merged**
