### PR TITLE
Enabled UseShortArrayInitializer pmd rule

### PR DESCRIPTION
**Pull request by grzesiek2010**
#### What has been done to verify that this works as intended?
I just reviewed the implemented changes.

#### Why is this the best possible solution? Were any other approaches considered?
I enabled [UseShortArrayInitializer](https://pmd.github.io/latest/pmd_rules_java_codestyle.html#useshortarrayinitializer) pmd rule which became available after updating pmd in https://github.com/opendatakit/collect/pull/3329.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
it doesn't require testing.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by nribeka** [comment]
👍 @grzesiek2010 👯‍♂

**Review by lognaturel — APPROVED** [review]
Works for me. I'll let @seadowg make a final call and merge if ok with it.

**Review by seadowg — APPROVED** [review]
I'm into it. Do we feel like this can skip QA?

**Comment by grzesiek2010** [comment]
> Do we feel like this can skip QA

If you reviewed the changes. Usually, we don't test such prs. Moreover, we are before regression testing so a lot of functionalities will be tested this week, so it's a good time to merge it.

**Pull request merged**
