### PR TITLE
Support styling for group names and list-nolabel

### LINKED ISSUE #3433: Can't style group names
#### Software and hardware versions 
Collect v1.x

#### Problem description
[Form styling](https://docs.opendatakit.org/form-styling/) doesn't work for group names

The problem has been originally reported on the forum: https://forum.opendatakit.org/t/odk-form-change-font-and-size-of-group-label/15535/3?u=grzesiek2010

#### Steps to reproduce the problem
Open this form:
[style-example.xlsx](https://github.com/opendatakit/collect/files/3803175/style-example.xlsx)

#### Other information 
It would be good to review all places where we use styling and standardize it somehow because it's not the first case when we forgot about styling something.

Other users that complained about the issue:
https://forum.getodk.org/t/estilo-de-color-en-el-formulario/31656
https://forum.getodk.org/t/customize-your-odk-forms-with-fonts-colors-etc/5504/5?u=grzesiek2010
https://forum.getodk.org/t/xlsform-add-html-styling-to-group-label/35164/3?u=grzesiek2010

### LINKED ISSUE #4822: Font styling does not work in list-nolabel
#### Software and hardware versions 
Collect v2021.2.3

#### Problem description
Font styling does not work in list-nolabel

#### Steps to reproduce the problem

[color-test.xlsx](https://github.com/getodk/collect/files/7107337/color-test.xlsx)

**survey sheet**
Screen Shot 2021-09-03 at 09 33 32

**choices sheet**
Screen Shot 2021-09-03 at 09 33 51

**collect UI**
Screen Shot 2021-09-03 at 09 29 19

#### Expected behavior
Labels should show font styling

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #4822
Closes #3433 

#### What has been done to verify that this works as intended?
I tested the fixes manually and also added automated tesst.

#### Why is this the best possible solution? Were any other approaches considered?
When it comes to the fix there is not much to discuss. Regarding tests I had to use android tests because testing styling with our widgets tests separately wouldn't be easy.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It should be a safe change that only fixes bugs so please focus on testing styling forms.

#### Do we need any specific form for testing your changes? If so, please attach one.
The one I used for testing: https://github.com/getodk/collect/compare/master...grzesiek2010:COLLECT-4822?expand=1#diff-c1c4c9e35503625e4b93bd9a3e2cfd6fff57e3f8fa22a36df2ad591968ddfdeb
and also the one attached in the documentation: https://docs.getodk.org/form-styling/

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by lognaturel** [comment]
I've always felt uncomfortable with this mix of data and styling. But it's lightweight and can be quite powerful so I guess I have to let it go! It's also too bad that this deviates from Enketo but that's an issue for another day.

What are the performance implications for the minimal selects? Those can be used to serve very long lists, especially combined with the `search`/`autocomplete` appearance so if it significantly slows down the unstyled case I'd be against changing those. They're the only ones I see a possible issue with.

**Comment by grzesiek2010** [comment]
> What are the performance implications for the minimal selects?

I haven't tested performance. I can do that or we can ask the QA team too. Generally widgets I've fixed are:
- SelectImageMapWidget (only displayed answer will be styled)
- RankingWidget
- ListWidget
- ListMultiWidget
- LabelWidget

I don't think those widgets are used to display like 1k items or more. Widgets people might use to do that are other select widgets and those widgets already support styling. I remember styling had a bad impact on performance when we had that for select_one minimal when a spinner was used for that. Now as we reimplemented it and use `recycler_view` it shouldn't be a problem.

**Comment by lognaturel** [comment]
> Generally widgets I've fixed are

Sorry about that, I'm not sure why I got the idea this made a change to minimal selects. I agree with you that the changes you've made are unlikely to hit performance issues.

Please fix the merge conflict and mark as `Needs Testing`.

**Review by lognaturel — APPROVED** [review]

**Comment by srujner** [comment]
**Tested with Success!**
Verified on Androids: 10 and 11

Verified cases:

- Attached forms
- Linked Issues are no longer reproducing
- SelectImageMap, Ranking, List, ListMulti and Label widgets
- Light and dark mode
- Screen rotation, minimize the app, using backward button

**Comment by kkrawczyk123** [comment]
Verified also on Androids 5.1 and 8.1

**Pull request merged**
