### PR TITLE
In GeoTrace, do not add an extra point to close the polygon if it is already closed.

### LINKED ISSUE #2868: GeoTrace saved as Polygon few times generates unexpected coordinates
#### Software and hardware versions 
Collect v1.19, older versions were not verified

#### Problem description
GeoTrace saved as Polygon few times generates unexpected coordinates

#### Steps to reproduce the problem
1. User saved Geotrace as Polygon
2. User opens widget again and user DOES NOT change the answer
3. User saved Geotrace as Polygon
4. User repeats these steps a few times
5. User sees more coordinates than expected

geotrace

#### Expected behavior
Additional coordinates are not generated

#### Other information 
Discovered during testing #2865

### PR DESCRIPTION
**Pull request by zestyping**
Closes #2868.

### Note to reviewers

The choice to "Save as Polyline" or "Save as Polygon" is about to be removed soon (see Phase 3 of the [Geo improvement roadmap](https://docs.google.com/document/d/1r3wJrOVDeFQkk4kWMoW29LtLI1vbBChqJ65w1Jyg4YU/edit)), which will make #2868 obsolete and this change unnecessary.  Feel free to reject and close this PR if desired.

#### What has been done to verify that this works as intended?
I started the GeoTrace activity, added three points to make a triangle, tapped the Save button, and selected "Polygon".  The result had 4 points (the first point was repeated as the last point), which is correct.  I then started the activity again and saved as a polygon again, and the 4 points remained unchanged.  Repeatedly opening and saving as a polygon did not add any more points.

#### Why is this the best possible solution? Were any other approaches considered?
This approach is simple and addresses the problem.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
The only visible change in behaviour is that #2868 does not occur anymore.

#### Do we need any specific form for testing your changes? If so, please attach one.
The GeoTrace widget in the "All Widgets" form will do.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by cooperka — APPROVED** [review]

**Comment by cooperka** [comment]
Change is straightforward and LGTM; I'm avoiding the "needs testing" label because it sounds like this might not be a priority for the release. Feel free to tag however you like.

**Review by grzesiek2010 — APPROVED** [review]

**Comment by grzesiek2010** [comment]
@zestyping please fix conflicts

**Comment by mmarciniak90** [comment]
@zestyping I confirm that additional point is not added when user saves multi times the same Polygon.

But I noticed a case:
1. User adds 3 points and saves it as a Polygon

Actual Result:
* Answer with 3 points is visible

Expected Result:
* Answer with 4 points is visible because Polygon is closed area and the closing point need to be added

I see that this PR does not contain the newest changes with GeoTrace so I cannot tell what causes this problem. Could you update this PR?
Additionally, I see that saving only 3 points on Android 5.1 and 4.4 is not permanent behavior, sometimes 4 points are saved. I cannot find a condition of this behavior. I hope that an update of this PR will help.

**Comment by zestyping** [comment]
Thanks for catching this, @mmarciniak90 !  Based on the roadmap ahead, I'm about to propose a plan to bring GeoTrace and GeoShape together, and I believe it will resolve many inconsistencies including this one.  The general idea is that we don't want to GeoTrace to be limited to only walking (with GPS) and GeoShape to be limited to only drawing (with long-press).  Users should be free to walk or draw, in both cases (a trace or a shape).  So instead of having two different activities, we will have one, and the only difference between GeoTrace and GeoShape will be whether it closes the last point or not.

Related:
- #507 Refactoring Geo-based activities
- #1028 Geotrace widget should only capture lines, not polygons
- #1084 Allow manual entry of points for geo widgets

Stay tuned, a plan is on the way!

**Comment by lognaturel** [comment]
Am I understanding correctly that the fix here is in #2933 so this can be closed?

**Comment by zestyping** [comment]
@lognaturel Yes! Sorry I forgot to tag this issue in that PR.

**Pull request closed without merging**
