### PR TITLE
1265 Update quit dialog for DrawWidget

### LINKED ISSUE #1265: Dialogs with multiple possible actions look bad
It's no longer very clear that save or ignore changes are clickable:
 

I looked through the [material design guidelines](https://material.io/guidelines/components/dialogs.html#dialogs-simple-dialogs) and would like to propose something like the following:
screen shot 2017-07-19 at 5 32 59 pm
Disclaimer, I am not a designer and certainly open to other ideas! The icons should probably be tinted with the accent color. @shobhitagarwal1612 it would be good to get your feedback.

From what I understand, material design would suggest automatically saving and not presenting this kind of dialog at all. This can certainly be reviewed at some point, but for now I think it would be best to make the dialog more usable and fit in with other dialogs that now roughly follow material design guidelines.

Note that the guidelines explicitly state that this kind of dialog should have no cancel button and that the user should just use the back button or tapping outside the dialog to dismiss it. The cancel button has been on that dialog for a long time, though, and I think it's better not to assume that users know those other ways of dismissing dialogs.

### PR DESCRIPTION
**Pull request by yurilaguta**
Closes #1265 

#### What has been done to verify that this works as intended?
Launch on emulator and tested all the possible outcome.
#### Why is this the best possible solution? Were any other approaches considered?
Same approach as the FormEntryActivity
#### Are there any risks to merging this code? If so, what are they?
No.

### CODE REVIEW

**Comment by yurilaguta** [comment]
screenshot 2017-09-24 21 11 57
Design same as in FormEntryActivity

**Comment by mmarciniak90** [comment]
Tested with success.
Expected dialog is visible on questions: 
- Draw widget
- Annotate widget
- Signature widget

Tested on Android 4.1, 4.2, 4.4, 5.1, 6.0, 7.0.
On Android 4.1 is visible problem #1493 but when both issues will be merged to master branch everything should be OK.

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
🎉🎉🎉

**Comment by mmarciniak90** [comment]
@opendatakit-bot unlabel "needs testing"

**Pull request merged**
