### PR TITLE
Clear cached forms on app upgrade

### LINKED ISSUE #6301: The app crashes on form finalization
#### ODK Collect version
v2024.3.0-beta.0, current master branch

#### Problem description
https://console.firebase.google.com/u/1/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/7ddd17ca0a93e82d425a5a441cf649de?time=last-seven-days&types=crash&versions=v2024.3.0-beta.0%20(4913)&sessionEventKey=66A3A763019F000148A7574DA36DB8A9_1974385087817821121

```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List org.odk.collect.entities.javarosa.parse.EntityFormExtra.getSaveTos()' on a null object reference
	at org.odk.collect.entities.javarosa.finalization.EntityFormFinalizationProcessor.processForm(EntityFormFinalizationProcessor.java:31)
	at org.javarosa.form.api.FormEntryController.lambda$finalizeFormEntry$0$org-javarosa-form-api-FormEntryController(FormEntryController.java:210)
	at org.javarosa.form.api.FormEntryController$$ExternalSyntheticLambda0.accept(Unknown Source:4)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1642)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:606)
	at org.javarosa.form.api.FormEntryController.finalizeFormEntry(FormEntryController.java:209)
	at org.odk.collect.android.javarosawrapper.JavaRosaFormController.finalizeForm(JavaRosaFormController.java:285)
```

#### Steps to reproduce the problem
1. Install Collect v2024.2.1.
2. Download the `All question types` form from the demo server.
3. Open the form and close it.
4. Install v2024.3.0-beta.0 or the current master branch.
5. Open the `All question types` form and finalize it.

#### Expected behavior
There should be no crash.

#### What's going on? 
The problem is that `entityFormExtra` is null after trying to read it from `formDef`
https://github.com/getodk/collect/blob/4741fecf37d167cd97490940a5bd8824546308c6/entities/src/main/java/org/odk/collect/entities/javarosa/finalization/EntityFormFinalizationProcessor.java#L31
Then in the line below we try to use that object and get NPE.

**But how null is returned instead of the expected `entityFormExtra`?**

First of all, we need to keep in mind that we cache `FormDef` after opening a form for the first time. That''s what happened in the third step (see above). The cached `FormDef` contains extras as well.

Ok so now let's understand how we save/read extras. We do that using HashMap where the key is the class name (the fully qualified name of the class):
 
```java
    public void put(T extra) {
        map.put(extra.getClass().getName(), extra);
    }

    public <U extends T> U get(Class<U> key) {
        return (U) map.get(key.getName());
    }
```

So in the third step using v2024.2.1 we save `entityFormExtra` with the key: `org.javarosa.entities.internal.EntityFormExtra`.
However, then we decided that `EntityFormExtra` class along with its whole package should be moved from Javarosa to Collect what was implemented in https://github.com/getodk/collect/pull/6236 and became a part of v2024.3.0-beta.0.

As a result, if we now try to load such extras from cache we try to read them using `org.odk.collect.entities.javarosa.parse.EntityFormExtra` and get null because they exist but are stored with the old class name as a key `org.javarosa.entities.internal.EntityFormExtra`.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #6301

#### Why is this the best possible solution? Were any other approaches considered?
On slack we have discussed with @seadowg two options and we decided that this one is what we like more.
The second option was switching to using const instead of class names as keys to store data in `HashMap`. However, this would require adding backward compatibility and the code would be convoluted.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
I think it would be good to test two things:
1. The issue itself to make sure it does not exist anymore.
2. Testing how clearing the cache works on app upgrade. We store cached forms along with savepoints in the cache but only cached forms should be deleted (we of course need to keep savepoints).

I can't think of anything else that should be tested more carefully.

Here I'm attaching APKs for testing the upgrade:
https://drive.google.com/file/d/1YUZDF1QLzbmZCrKqeCiIDHZTLAn1zsZk/view?usp=sharing

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by lognaturel** [comment]
Apologies for jumping in without much context! Quick question -- did you consider catching any errors loading from cache file and reloading directly from the form definition in that case? I could have sworn that was already happening but maybe not completely? Clearing the cache on app update feels like a nuclear option and could add significant time to form load for forms with complex logic for every release including small point releases and many that have no impact on the cache files.

I probably won't have a chance to engage in a full discussion on this now so feel free to proceed for now if the approach still feels right and we can come back to some of my questions.

**Comment by seadowg** [comment]
> Apologies for jumping in without much context! Quick question -- did you consider catching any errors loading from cache file and reloading directly from the form definition in that case? I could have sworn that was already happening but maybe not completely?

You're correct that already happens, but it can't account for errors that happen later due to mismatches in the "serialized" code. The linked issue is about a crash that happens during finalization.

> Clearing the cache on app update feels like a nuclear option and could add significant time to form load for forms with complex logic for every release including small point releases and many that have no impact on the cache files.

Do we have forms that demonstrate this? @getodk/testers maybe has a set of them? I think it's worth investigating that and if caching is giving us noticeable loading time improvements, we should make that part of at least regression testing. Right now I don't think there's any check that would prevent it from being completely removed (or not work some large percentage of the time). I'm going to add "needs testing" before review here for that.

**Comment by grzesiek2010** [comment]
If caching is still needed we can consider a hybrid solution. That would mean clearing cache but only once for the next release and switching to using const instead of class names as keys to store extras. If we clear cache once then we can rework how extras are stored without backward compatibility and the code should still be clean.

**Comment by seadowg** [comment]
Some more thoughts on this I've had on this:

- I'm thinking there was probably a similar problem with forms that had been parsed by Collect before we wrote any entity code as those cached `FormDef` objects wouldn't include the extras needed to deal `saveto` etc. This was probably rare though.
- Although it does seem harder due to the sensitivity of `Externalizable`'s implementation, I'm not confident that we are entirely protected against similar "silent" or "crashes later" problems when making changes to JavaRosa crashes.
- I've noticed that it's very common for OOM crashes to be preceded by a failed read from the cache (logs [here](https://console.firebase.google.com/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/5b48ab2aa7ee6f9f311b9146ca58a40f?time=last-seven-days&types=crash&sessionEventKey=66B1DB39017600014792768CEE10C457_1978395157350177892)). This makes me wonder if our fallback mechanism is actually causing larger memory overheads due to the `readExternal` work followed by a full parse.

It's starting to look to me like our "extras" concept for `FormDef` might be incompatible with the way we've been doing form caching (keeping the cache until reading it fails). 

I'm also thinking that the only benefit we have from the fallback approach as opposed to clearing on upgrade is that **some** upgrades won't end up clearing the cache (due to JavaRosa's rate of change being lower than Collect's). However, when there is a change that breaks the cache, the fallback mechanism is inherently worse as it requires form loads to do more work (and that extra work will happen for every form). 

Given all that, I still think it's important for us to get a sense of the gains we're getting from caching currently, but I'm also now feeling like clearing the cache on upgrade is potentially a better overall solution - we're trading **sometimes** not needing to do full loads after upgrade for faster load times on upgrades that do break the cache, a ton of simplicity and much stronger protection from problems. If we really want to win back the cached load times on upgrades that don't break anything, we could introduce a versioning mechanic (like with Java `Serializable`). These are very hard to manage in practice though. 

Thoughts?

**Comment by srujner** [comment]
Hey, we have checked the loading times of the forms after the "upgrade" with the version from "PR" (clearing cache) and the version from "Master" (not clearing cache) and there is no noticeable loading time improvements. 

But we really only have 2-3 larger forms on which to check this and, to be 100% honest, we are not sure if any problems will arise in the future from clearing the cache after the upgrade. 

From our perspective, it is difficult to make a single decision here whether we should cleared cache after upgrade or not.

**Comment by seadowg** [comment]
> From our perspective, it is difficult to make a single decision here whether we should cleared cache after upgrade or not.

Thanks for digging in! That's helpful.

**Review by seadowg — APPROVED** [review]

**Comment by seadowg** [comment]
@grzesiek2010 I'm thinking we go ahead with this for the moment. We can always replace it with a more targeted fix later if we feel the performance hit is too great.

**Comment by srujner** [comment]
**Tested with Success!**

Verified on device with Android 10, 13

Verified cases:
- Issue #6301 is no longer reproducing;
- General regression check on savepoints;
- Upgrading the app from older version; 
- Checking how cache behaves before and after app upgrade;
- Don't keep activities enabled/disabled;
- Minimize the app, rotate the screen;
- Upgrade the app during sending big forms;

**Comment by WKobus** [comment]
**Tested with Success!**

Verified on device with Android 14

**Pull request merged**
