### PR TITLE
Only add analytics credentials to release builds

### LINKED ISSUE #655: Only add analytics credentials to release builds
Currently, we track analytics from every fork of Collect. This is not a great idea because we don't need to see activity from random forks of Collect. We should only include analytics credentials on release builds.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #655 

#### Why is this the best possible solution? Were any other approaches considered?
I use the same approach like in #1554  

#### Are there any risks to merging this code? If so, what are they?
No.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

### CODE REVIEW

**Comment by lognaturel** [comment]
This doesn't seem quite right. I believe this disables the analytics setting and hides it for all builds that are not the release build. That's going to be pretty confusing because the UI will look different for a debug build. Also, we don't want to completely hide analytics options for forks, just encourage them to use their own analytics credentials.

**Comment by grzesiek2010** [comment]
@lognaturel so what do we need just make the checkbox unchecked by default for other builds and checked like know for odkCollectRelease build?

> That's going to be pretty confusing because the UI will look different for a debug build.

I don't find it confusing. The checkbox is just not enabled but still visible.

**Comment by lognaturel** [comment]
Sorry to let this sit, @grzesiek2010! I've had trouble coming up with the right way forward.

Now I see that what this does is only pay attention to the analytics setting if the variant is the odk release build and to uncheck and disable the analytics setting otherwise (don't know why I thought hide).

It's a little unfriendly to forks because it means they need to hunt this down to enable analytics for themselves. That's probably not a huge concern. 

@grzesiek2010 did you investigate strategies that would involve not setting the tracking ID on non-release builds? That's what I had in mind. I see that the tracking ID is set in `google-services.json` and searching the project for `trackingId` shows me that it ends up in generated files for all the build variants. Ideally we could use three tracking IDs -- one for the collect release, one for debug builds and one for non-Collect release builds (hey, might as well if forks don't change it). I think that's possible by having multiple `google-services.json` files.

**Comment by grzesiek2010** [comment]
@lognaturel yes it should be possible to have different `google-services.json` files for different builds but I don't understand what you mean by:

> Ideally we could use three tracking IDs -- one for the collect release, one for debug builds and one for non-Collect release builds (hey, might as well if forks don't change it).

Do you want to register three different projects to have three different ids and track them separately?

**Comment by lognaturel** [comment]
Yes, exactly. You can set it all up with fake IDs to make sure the build files are properly set up and then I can give you two more real IDs for debug builds and non-Collect release builds. How does that sound?

**Comment by grzesiek2010** [comment]
@lognaturel I think this is what you wanted now you can try to create three different ids.

I also removed analytics_tracker.xml file since it was unused. According to the doc:
https://developers.google.com/analytics/devguides/collection/android/v4/

that file should be used [here](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/application/Collect.java#L304). But we use `global_tracker` which is auto-generated as I understand using google-services.json (it's in `collect_app/build/generated/res/google-services/`)

**Comment by lognaturel** [comment]
Awesome! I've confirmed that the different IDs go to the expected places by setting dummy ones.

@yanokwa does this approach seem good to you? I think you'll need to create the two new IDs -- one for debug and one for non-ODK release builds.

@grzesiek2010 any idea whether this kind of thing is possible for Firebase Crash as well?

**Comment by yanokwa** [comment]
It seems reasonable to me. I've added @lognaturel and @grzesiek2010 as admins on two new projects: `opendatakit-collect-debug` and `opendatakit-collect-forks`. @grzesiek2010 you two take it from here? If there are any private keys/secrets that need to go back to ODK leadership, let me know and we find a way to transfer that. Once it's done, let me know and I'll reduce your permissions from admins to something more appropriate.

**Comment by lognaturel** [comment]
@grzesiek2010 I think all is needed here is to put the two new tracking IDs in, right? Let's try to get this in before code freeze!

**Comment by grzesiek2010** [comment]
@lognaturel Yes, of course, I was on it. I created two new projects according to this tutorial https://www.numetriclabz.com/integrate-google-analytics-in-android-application-tutorial/ (as I remember we used it before too) and downloaded two new json files.

So that should be all we need I think...

**Comment by lognaturel** [comment]
Great! You mean you're using the projects `opendatakit-collect-debug` and `opendatakit-collect-forks` that @yanokwa created and added you to, right?

**Comment by grzesiek2010** [comment]
> You mean you're using the projects opendatakit-collect-debug and opendatakit-collect-forks that @yanokwa created and added you to, right?

yes projects with the same names were visible on my list so I just selected them (one by one) and created new GA projects for both.

**Comment by grzesiek2010** [comment]
@lognaturel 
You also should be able to see them https://analytics.google.com/analytics/web/ could you confirm?

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
Great! I don't see them but the projects may not have been shared with me.

**Pull request merged**
