### PR TITLE
Set default OSM Basemap

### LINKED ISSUE #1856: Default OSM basemap is not set
#### Software and hardware versions 
Collect v1.12.2 and older version

#### Steps to reproduce the problem
1. Go to `General Settings` -> `User Interface`
2. Change `Mapping SDK` for `OpenStreetMap SDK`

#### Expected behavior
Default basemap should be set.

#### Other information 
defaultosmbasemap

@opendatakit-bot label "quick win"

### PR DESCRIPTION
**Pull request by abdulwd**
Closes #1856 

#### What has been done to verify that this works as intended?
I have tested it on a device.

#### Why is this the best possible solution? Were any other approaches considered?
This was the simplest approach.

#### Are there any risks to merging this code? If so, what are they?
No. There is no risk

#### Do we need any specific form for testing your changes? If so, please attach one.
No form is needed for testing.

### CODE REVIEW

**Comment by grzesiek2010** [comment]
@opendatakit-bot unlabel "needs review"
@opendatakit-bot label "needs testing"

**Comment by grzesiek2010** [comment]
@opendatakit-bot label "needs testing"

**Comment by abdulwd** [comment]
@grzesiek2010 Do I need to write tests for getting the pull request merged?

**Comment by grzesiek2010** [comment]
@abdulwd tests are always welcome but it's not required and that label `needs testing` I added is for our QAs to let them know it's ready for manual verification.

Here you can find more info https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#the-review-process

**Review by lognaturel — APPROVED** [review]

**Comment by mmarciniak90** [comment]
**Tested with success!**
Verified on Android: 4.1, 4.2, 4.4, 5.1, 6.0, 7.0, 8.0
`OSM Streets` is selected as the default Basemap for `OpenStreetMap SDK`

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Review by lognaturel — APPROVED** [review]

**Pull request merged**
