### PR TITLE
Fixed error prone registerToClearAnswerOnLongPress() method for string widget

### LINKED ISSUE #4834: Integer questions do not play video
#### Software and hardware versions 
Collect 2012.2.4

#### Problem description
Reported at https://forum.getodk.org/t/integer-questions-do-not-play-videos/35175. On integer question types, the video do not play. The video button is displayed but the video is not opened

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...
[Example Problem.zip](https://github.com/getodk/collect/files/7232052/Example.Problem.zip)

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #4834 

#### What has been done to verify that this works as intended?
I tested the fix manually and ran automated tests.

#### Why is this the best possible solution? Were any other approaches considered?
The issue affects all string widgets (text, integer, decimal). It is because in `StringWidget#registerToClearAnswerOnLongPress()` we override ids and then we can't react to click events in [AudioVideoImageTextLabel](https://github.com/getodk/collect/pull/4860/files#diff-22969420ab3442906012d0bb852a6b38a6ed9987ce6ebefa324a852265cfa1b0L219) by using those static ids.

The previous solution (draining all sub views and setting their ids) was error prone. We can just navigate through the first level of sub vies (only containers) and register those whole views except `answer_container` which contains the EditText to support the clipboard menu.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It should just fix the issue but please test removing answers (especially in field-list groups) to make sure nothing is spoiled there.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by seadowg** [comment]
> Another solution would be to avoid draining audio_video_image_text_label layout (and overriding ids) in StringWidget#registerToClearAnswerOnLongPress() but then long press wouldn't be supported.

It does feel to me like it would be best to try and clean up what's happening in `StringWidget#registerToClearAnswerOnLongPress()` as it seems like it could definitely cause other bugs in the future. This issue has existed for a while, so I think we're ok to take a little longer on it. 

I don't understand why we have to mess with view IDs in `registerToClearAnswerOnLongPress()`. Could we not explicitly register the answer view and question label separately (instead of just registering the whole view) to avoid this kind of problem? Then we could just not register the answer view in our string widgets that use an `EditText`. Maybe I'm missing some complexities here though!

**Review by seadowg — CHANGES_REQUESTED** [review]
> Another solution would be to avoid draining audio_video_image_text_label layout (and overriding ids) in StringWidget#registerToClearAnswerOnLongPress() but then long press wouldn't be supported.

It does feel to me like it would be best to try and clean up what's happening in `StringWidget#registerToClearAnswerOnLongPress()` as it seems like it could definitely cause other bugs in the future. This issue has existed for a while, so I think we're ok to take a little longer on it. 

I don't understand why we have to mess with view IDs in `registerToClearAnswerOnLongPress()`. Could we not explicitly register the answer view and question label separately (instead of just registering the whole view) to avoid this kind of problem? Then we could just not register the answer view in our string widgets that use an `EditText`. Maybe I'm missing some complexities here though!

**Comment by grzesiek2010** [comment]
> Could we not explicitly register the answer view and question label separately (instead of just registering the whole view) to avoid this kind of problem?

clipboard menu won't work in that case (in EditText). **EDIT: I think your idea was close to mine that I described below (I misunderstood something)**

> I don't understand why we have to mess with view IDs in registerToClearAnswerOnLongPress()

It's because we need to have different ids otherwise if we have field-list group removing answers might not work properly.

You know what... a simpler and less error prone solution would be to `registerForContextMenu` only the `AudioVideoImageTextLabel` so that we support both: our contextual menu and clipboard menu and avoid draining the whole layout.
It would look like this: https://github.com/getodk/collect/commit/cb4ea6cae8742aefad2a02fbc021cec32db241f1
 
So in case of String widgets we would register just the `AudioVideoImageTextLabel` an not answer view to support clipboard menu bot for all the other widgets everything will work in the same way as before.

what do you think?

**Comment by seadowg** [comment]
>  EDIT: I think your idea was close to mine that I described below (I misunderstood something)

Yeah it looks like we're on the same page - register the views explicitly and just don't do it for the answer view. I was thinking that we probably also need to register the `help_text` part of the `question_widget` layout as well right? Also, I think we want to just register the whole widget for the `Ex...` widgets right? In that case there isn't an edit text to avoid.

**Comment by grzesiek2010** [comment]
> Yeah it looks like we're on the same page - register the views explicitly and just don't do it for the answer view. I was thinking that we probably also need to register the help_text part of the question_widget layout as well right?

Right, my current implementation handles it. I navigate through the first level of sub vies and register them (except for the `answer_container`) and I don't drain that sub views like before what was error prone.

> Also, I think we want to just register the whole widget for the Ex... widgets right? In that case there isn't an edit text to avoid.

There is an edit text which is displayed if there is no activity to handle such an external widget.

**Review by seadowg — CHANGES_REQUESTED** [review]
This is looking so much better/simpler than the existing implementation! 

I think we should cement this in with a test that checks that all the subviews (other than the answer container) have had their ID changed to the widget ID and have been registered with the Activity - I'm guessing this could be done by overriding `registerForContextMenu` on the test Activity and then recording the views it's passed.

I'll make this ready for QA as I don't think the test will disrupt them.

**Comment by mmarciniak90** [comment]
**Tested with success**

Verified on Android versions: 8.1, 9.0, 10.0

Verified cases:
- play video in form from issue
- text, integer, decimal
- field-list groups
- removing answers in simple view
- removing answers in field-list groups
- read-only widgets, with and without answers 
- rotation, minimization 
- light/dark mode

**Comment by kkrawczyk123** [comment]
Tested on Androids 5.1, 7.1 and 11.
When testing on Android 11 I have noticed an issue with playing video attachments in other forms as well - reported in #4876

**Comment by seadowg** [comment]
I'm going to merge this now so it can be in for regression testing. Are you able to follow up with a testing I mentioned @grzesiek2010?

**Review by seadowg — APPROVED** [review]

**Comment by grzesiek2010** [comment]
> Are you able to follow up with a testing I mentioned

yeah I'll try to write some valuable tests for this.

**Pull request merged**
