### PR TITLE
WIP: Add image crop view

### LINKED ISSUE #2104: Add image crop view in ImageWidget
#### Problem description
When I am using the ImageWidget, I feel uncomfortable because the image cannot be resized by myself (although I can click this image to launch my system gallery, my gallery has **no crop** feature). ODK Collect just simply put the whole image into the form and has no options for me to crop that. I have to take a lot of pics until I get a satisfied one. 
#### Expected behavior
I think we should add a build-in `image-crop` view when user has finished their photo shooting.
#### Other information 
I'd like to improve this.

### PR DESCRIPTION
**Pull request by huangyz0918**
Closes #2104 

#### What has been done to verify that this works as intended?
- Added a custom view which allows **image cropping**.
- Added them to all operations related to image picking (image shooting and selfie).

Screen records:
68747470733a2f2f692e6c6f6c692e6e65742f323031382f30342f31302f356163633561613838393465652e676966

#### Why is this the best possible solution? Were any other approaches considered?
Maybe we can use third-party libraries that support image cropping.
But DIY is a good choice.
#### Are there any risks to merging this code? If so, what are they?
No.
#### Do we need any specific form for testing your changes? If so, please attach one.
No need.
#### Does this change require updates to documentation? If so, please file an issue at https://github.com/opendatakit/docs/issues/new and include the link below.
If needed, will do.

### CODE REVIEW

**Comment by lognaturel** [comment]
Thanks for exploring this, @huangyz0918 and apologies for taking so long to take a look -- there's a lot going on! 

In general, we try to be really careful about making sure there's a lot of demand before a feature is added, especially when it changes the existing flow through a form. Because Collect is mostly used by people without a lot of experience with smart phones or a lot of survey training, changes to functionality and interface need to be slow and deliberate. It's not sexy but it's one of the reasons ODK is so widely adopted!

My sense is that this feature certainly could be helpful for some users but that it might not be right as the default behavior. I believe a lot of form developers who want a picture want something raw from the camera. I also think this could confuse enumerators and require re-training. But I could also be wrong! It would be good to describe the feature at https://forum.opendatakit.org/c/features and get user feedback. In particular, I would want to know whether people who want this would like it as the default behavior or perhaps an appearance that a form developer can specify.

**Comment by huangyz0918** [comment]
@lognaturel Sorry for my hurry about this new feature. I'd like to see how our users thoughts in ODK forum too, so I'll open a thread and ask for their opinions 😄 . At the mean time I think I can keep this PR and add some modifications & tests if needed. If we don't need this feature for now, I don't mind closing it immediately, it decided by maintainers and users. 🔨

**Comment by lognaturel** [comment]
I'm going to close this PR for now but let's keep an eye on https://forum.opendatakit.org/t/allow-cropping-image-from-camera-or-gallery/12778 and see if someone has a need for it! Thanks for starting the conversation, @huangyz0918.

**Comment by huangyz0918** [comment]
@lognaturel Thanks ! It's ok to me :)
And I'm looking forward to come back here and do more contribution in next month! @yanokwa suggested that I can try something elses except Collect, what's your suggestion? I will be glad to have a try!

**Pull request closed without merging**
