### PR TITLE
Fixed IllegalArgumentException in AnalyticsUtils.java line 116

### LINKED ISSUE #5111: IllegalArgumentException in AnalyticsUtils.java line 116
#### Software and hardware versions 
Collect v2022.2

#### Problem description
https://console.firebase.google.com/u/1/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/b4bf1e7c527dc4de6ca9905f04ee7a0c?time=last-ninety-days&versions=v2022.2.0%20(4418)&types=crash&sessionEventKey=625D574F0169000164954961284FF97E_1666363054017438386

```
Fatal Exception: java.lang.IllegalArgumentException
       at org.odk.collect.android.analytics.AnalyticsUtils.getFormSourceExceptionAction(AnalyticsUtils.java:116)
       at org.odk.collect.android.analytics.AnalyticsUtils.logMatchExactlyCompleted(AnalyticsUtils.java:46)
       at org.odk.collect.android.formmanagement.FormsUpdater.matchFormsWithServer$lambda-1(FormsUpdater.kt:98)
       at org.odk.collect.android.formmanagement.FormsUpdater.$r8$lambda$_5u1JWTN1jJtGa3FQvdqO4vyOtU(FormsUpdater.kt)
       at org.odk.collect.android.formmanagement.FormsUpdater$$InternalSyntheticLambda$1$bd7588e51343d3eb3b2716d803239190a936968875952368c45f3e582fbf4768$0.apply(FormsUpdater.java:10)
       at org.odk.collect.shared.locks.ReentrantLockChangeLock.withLock(ReentrantLockChangeLock.java:13)
       at org.odk.collect.android.formmanagement.FormsUpdater.matchFormsWithServer(FormsUpdater.kt:82)
       at org.odk.collect.android.formmanagement.FormsUpdater.matchFormsWithServer$default(FormsUpdater.kt:68)
       at org.odk.collect.android.formmanagement.FormsUpdater.matchFormsWithServer(FormsUpdater.kt:8)
       at org.odk.collect.android.formmanagement.BlankFormsListViewModel.lambda$syncWithServer$2(BlankFormsListViewModel.java:94)
       at org.odk.collect.android.formmanagement.BlankFormsListViewModel.$r8$lambda$N7AqnlNFBo19_u8_SgYGeg3OeUU(BlankFormsListViewModel.java)
```

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5111

#### What has been done to verify that this works as intended?
I've reviewed implemented changes.

#### Why is this the best possible solution? Were any other approaches considered?
There was one unchanged exception in `getFormSourceExceptionAction()` which I added. Additionally I got rid of throwing exceptions in that method since I think class responsible just for logging analytics should not do things like that (that can crash the app).

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It doesn't require testing.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by seadowg** [comment]
I'm wondering if, as an alternative, we can just get rid of the `MatchExactlySyncCompleted` (and other match exactly) events as we already reacted to the data from them. Also, we know it's hard to read the data from the category/action events with the current state of Firebase (which is why that version of `logEvent` is deprecated). cc/ @lognaturel.

**Review by seadowg — COMMENTED** [review]
I'm wondering if, as an alternative, we can just get rid of the `MatchExactlySyncCompleted` (and other match exactly) events as we already reacted to the data from them. Also, we know it's hard to read the data from the category/action events with the current state of Firebase (which is why that version of `logEvent` is deprecated). cc/ @lognaturel.

**Comment by lognaturel** [comment]
> get rid of the MatchExactlySyncCompleted (and other match exactly) events

That would be fine by me.

**Comment by grzesiek2010** [comment]
> That would be fine by me.

Ok, done.

**Review by lognaturel — APPROVED** [review]

**Pull request merged**
