### PR TITLE
Fixes code coverage report generation on CircleCI

### LINKED ISSUE #1881: Fix the code coverage report generation on CircleCI
A merged code coverage report should be uploaded to the codecov after the build finishes on Circle CI. 
Currently, the unit tests are running on Circle CI and the integration tests are running on firebase(only for master branch).

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Closes #1881 

#### What has been done to verify that this works as intended?
- Verified that all code quality checks, unit tests and instrumentation tests are running properly.
- Artifacts are getting generated properly
- Code coverage report is uploading to codecov.io (tested using my [repo]( https://codecov.io/gh/shobhitagarwal1612/collect/))

#### Why is this the best possible solution? Were any other approaches considered?
 - Moved the unitTests out of the build task and into a separate task to run both the jobs simultaneouly for faster builds. 
- Refactored the script by using `references` to reuse the script commands.
- Adds one more job to create code coverage report and then upload to codecov.io 

#### Are there any risks to merging this code? If so, what are they?
I have verified everything manually but someone who has much better experience in this should double check to ensure that it won't have side-effects.

#### Do we need any specific form for testing your changes? If so, please attach one.
None required

### CODE REVIEW

**Review by yanokwa — COMMENTED** [review]
This is an extraordinary amount of work, @shobhitagarwal1612. THANK YOU!

I have some minor complaints, but I'll file those separately.

**Review by yanokwa — APPROVED** [review]

**Comment by shobhitagarwal1612** [comment]
I am glad it worked. Also, very happy to see codecov back :smile: 

I do think there is a scope of reducing the build timings (like removing the dependency from the jacocoTestReport) and removing some redundant commands from the circle ci config yaml.

**Comment by yanokwa** [comment]
@shobhitagarwal1612 It might be good to file issues for those things so we don't forget!

**Comment by shobhitagarwal1612** [comment]
Sure.

**Pull request merged**
