### PR TITLE
Default accent color

### LINKED ISSUE #2399: Tint color in dark theme should be higher contrast
See https://forum.opendatakit.org/t/dark-theme-radio-buttons-hard-to-see/13499

Android does seem to have a standard for some if its own screens that we should use: https://phandroid.com/2015/05/28/android-marshmallow-has-a-dark-theme-hidden-in-the-developer-options/ I'm not sure why this is not what the app compat dark theme uses (https://developer.android.com/guide/topics/ui/look-and-feel/themes). Ideally we can find that color defined somewhere in Android instead of having to use a color picker to define it.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #2399 

#### What has been done to verify that this works as intended?
I tested how it looks with Dark and Light modes.

| Light theme  | Dark theme |
| ------------- | ------------- |
| screenshot_2018-07-23-16-06-51 | screenshot_2018-07-23-16-07-28 |
| screenshot_2018-07-23-16-06-58 | screenshot_2018-07-23-16-07-35  |
| screenshot_2018-07-23-16-07-15 | screenshot_2018-07-23-16-07-51 |

#### Why is this the best possible solution? Were any other approaches considered?
We should use default colors if it's possible.

#### Are there any risks to merging this code? If so, what are they?
No.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew pmd checkstyle lintDebug spotbugsDebug` and confirmed all checks still pass.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by lognaturel** [comment]
This looks perfect for the dark theme. I hope the users will agree.

I wonder whether we should change it for the light theme. It's the kind of thing that doesn't really make a difference but can be confusing and surprising for users and make them concerned that other big changes have happened. That blue is common across a lot of Android apps (maybe it was the default on older Android versions?) and has been the ODK standard for a long time. I would tend to keep the blue. @yanokwa, @shobhitagarwal1612, @jd-alexander -- any one else have an opinion on that?

**Comment by jd-alexander** [comment]
Yes, it looks good indeed but I think @yanokwa made a comment at one point about keeping minimal colors for accessibility reasons such as color blindness and that the Android blue works better as the default.

**Comment by shobhitagarwal1612** [comment]
I like this change. Keeping it same for both themes might make it easier for people to adapt while changing the theme frequently

**Comment by yanokwa** [comment]
To my eye, the teal doesn't make a meaningful difference, but it seems the consensus is for teal on the dark theme, so I'm glad to proceed there.

As for changing the color on the light theme, I like consistency, but 1) no one has complained and 2) @lognaturel feels strongly about it, so let's keep it blue.

**Comment by jd-alexander** [comment]
@grzesiek2010 since everything is utilizing the `accentColor`, we can always implement a feature where users can choose from a set of colour themes such as teal and everything that uses the `accentColor` will get overriden with that change at runtime.

**Comment by grzesiek2010** [comment]
Ok everyone, I added the original blue color back.

**Comment by kkrawczyk123** [comment]
**Tested with success!**
Verified on Androids 4.1, 4.2, 4.4, 6.0 and 8.1 

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Review by lognaturel — APPROVED** [review]

**Pull request merged**
