### PR TITLE
Group the external API definition together

### LINKED ISSUE #3040: Long-term fix for breaking change when openning instance upload list activity from external app
#### Software and hardware versions 
Collect v1.21.0, Android v7.0.0, Samsung SM T713

#### Problem description
Previously the form instance upload list page, called **Send Finalized Form** and displays a list of finalized forms for upload, could be openned using the following code:

```
 Intent surveyIntent = new Intent();
 surveyIntent.setComponent(new ComponentName("org.odk.collect.android", "org.odk.collect.android.activities.InstanceUploaderList"));
 surveyIntent.setAction(Intent.ACTION_EDIT);
 activity.startActivity(surveyIntent);
```
The new name for the activity is `org.odk.collect.android.activities.InstanceUploaderListActivity` thus external applications relying on this cannot open the page with version **v1.21.0** of ODK Collect 

#### Other information 

Suggestions on how to fix it:

1. Rename the integration in external applications
2. Rename the activity in ODK Collect
3. Add an action with a data type for openning the same activity

Each of the following suggestions has it's own 
- **amount of effort**
- **consequence to current users due to mismatching versions**
- **Sufficiency for providing a long-term fix**

Any other suggestion is welcome 😄 !!!

A long-term fix for the breaking change is required. The change made is in this PR https://github.com/opendatakit/collect/pull/2769/files#diff-2f6e2181f5fe37baca5afc44b6824d87R87

### PR DESCRIPTION
**Pull request by lognaturel**
Closes #3040

While #3044 narrowly fixes the issue that @ekigamba has run into, this attempts to make accidental changes to the public API less likely in the future by giving developers and reviewers some context. Once #3044 is merged and released, this can be rebased on top of master and merged for future release. I did them separately because this is too risky to go in a point release.

@seadowg and @shobhitagarwal1612, please see if you think this will be helpful. This has come up again because d8031b9 included a rename of an activity that was publicly accessible and that broke one of @onaio's integrations. This is not the first time Collect's public API has been accidentally changed so I want to make sure all reviewers are aware that it's a concern.

#### What has been done to verify that this works as intended?
Visually verified that all expected blocks remain in the new config.

#### Why is this the best possible solution? Were any other approaches considered?
This helps communicate what the Collect public API is and reminds devs to think about it when proposing or reviewing changes. I also considered adding something to the readme but it doesn't seem most people read it carefully. This puts the information right where developers need it.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
There should be no user-visible changes. If I made a mistake, the risks are that a certain activity would not be available at all anymore.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by seadowg — APPROVED** [review]
The `activity-alias` seems like the right thing to do™️. Conceptually it makes sense that the name of your Activity should be able to be different from its public facing integration. It also seems like this new grouping for the manifest makes sense. I'm not sure the comment gives us that much protection as I'd be worried any changes would be made within the class itself (with a `shift + F6` for example) and the developer would never have to read the manifest. That said I guess every little helps with something like this!

As an aside: I was trying to think of a good way of building in a test to catch this but it seems like anything you might do would be far to prone to IntelliJ/Android Studios renaming (as it changes String literal references as well). Do we have test cases for QA that we could add this too? If there is a well known integration that could be used as a check.

**Comment by lognaturel** [comment]
@seadowg Agreed it's not very strong protection but hopefully it's just one more thing someone is likely to run into and consider.

QA does verify external integrations but in this case they were verifying launching with an action rather than an explicit activity name. We should do both.

For future planning, is it possible to only export an action without exporting the activity name? I can't find a way to do it but that would be really nice.

**Comment by seadowg** [comment]
@lognaturel  I've only dealt with exposing actions really but I think, like you say, that that always exports the Activity as well as setting intent filters will always set `exported` to `true`. That's what I got from [here](https://developer.android.com/guide/topics/manifest/activity-element#exported) anyway.

In my head it would make sense that the action is the thing you've (intentionally) exposed and not the Activity name so people probably shouldn't be using the Activity name directly. 

I'm not that familiar with what integrations are possible for Collect - are there docs around this? Maybe an idea for the future would be to push people towards the actions with docs and "deprecate" using the Activity name.

**Comment by lognaturel** [comment]
The docs are at https://docs.opendatakit.org/launch-collect-from-app/ and it does document actions. But I'm guessing developers are more likely to look at the source than the docs so I do still think the activity names should be stable. That's easy enough to achieve with aliases.

In the case of `InstanceUploaderList`, the actions exported are just `VIEW` and `EDIT` with no qualifications which is really bizarre and an accident of history, especially since the two do the same thing. I think that may have further nudged developers to use the activity name rather than the action name. Let's also add a custom action name as described at https://github.com/opendatakit/collect/issues/3050.

**Comment by grzesiek2010** [comment]
It looks fine but it's rather something that could help only reviewers. A contributor might rename such activity using Android Studio and not even look at the manifest file.
What about adding aliases for all those activities just in case? Those aliases should be safe when it comes to renaming files using Android Studio.

**Comment by lognaturel** [comment]
Good idea, @grzesiek2010. Will do that soon.

**Comment by lognaturel** [comment]
Ready for your review, @grzesiek2010. I did a quick verification that all the activities launch as expected. I also verified that when renaming an exported activity in Android Studio, the alias updates as expected. 👍 

I suggest you do a visual inspection and merge if happy since any issues will be really obvious in regression testing. It's also fine if you'd rather do a QA pass now. 😊

**Review by grzesiek2010 — APPROVED** [review]

**Pull request merged**
