### PR TITLE
Timber Instead of Log in views, utilities and widgets

### PR DESCRIPTION
**Pull request by nmpatsal**
I completely synced my fork and now only relevant changes are shown.
Replaced Log with Timber in views, utilities and widgets.

### CODE REVIEW

**Comment by shobhitagarwal1612** [comment]
I noticed that your PR has some very old commits. Also, I think you have not checked out your new branch `TimberIt` from the latest upstream `master` branch. That is the reason you are having those unrelated changes.
To avoid this in future you should do the following:
Checkout your master branch : `git checkout master`
Update the master branch       : `git pull upstream master`
Then checkout new branch     : `git checkout -b new-branch-name`

**Comment by nmpatsal** [comment]
@shobhitagarwal1612  If I will try it now, will I lose the changes that I made?

**Comment by nribeka** [comment]
Yep, sync up your fork with upstream. That will not remove any of your changes.

And there's duplicate import too in the code. Check the GridMultiWidget.java file.
You can run the checkstyle task from gradle or run `gradle checkstyle`

**Comment by lognaturel** [comment]
One more thing! Please make sure that when you remove a line of code, you also remove the newline. There should be no blank lines added when looking at the diff.

**Comment by nmpatsal** [comment]
Ok I think that I had to apply this commands after my old pull request was accepted, I found it on the internet:
git remote add upstream (url-for-upstream-repository)
git fetch upstream
git rebase upstream/master
git push -f origin

Now I created a new branch and followed the instructions of "sync your fork" and @shobhitagarwal1612 but when I try to make a pull request it still shows the old commits. :(

**Pull request closed without merging**
