### PR TITLE
Closes#2195: Replaced the icons in DrawView with Vectors.

### LINKED ISSUE #2195: Replace icons we use in DrawView with vectors
#### Problem description
Replace icons we use in DarwView with vectors

Icons we should replace:
ic_clear_white
ic_save_white
ic_color_lens_white
ic_add_white

#### Steps to reproduce the problem
1. Open `All Widgets` form
2. Navigate to `Draw widget`

#### Expected behavior
All mentioned icons should be replaced with vectors. 

#### Other information 
screenshot_2018-05-14-10-14-48

### PR DESCRIPTION
**Pull request by SaumiaSinghal**
Closes #2195 

#### What has been done to verify that this works as intended?
I tested it.

#### Why is this the best possible solution? Were any other approaches considered?
I simply converted the png to svg file first and then, used it to generate a vector .xml file.

#### Are there any risks to merging this code? If so, what are they?
No

#### Do we need any specific form for testing your changes? If so, please attach one.
Draw widget in AllWidgetForm

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew pmd checkstyle lint findbugs` and confirmed all checks still pass.
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by grzesiek2010** [comment]
@SaumiaSinghal looks good. Just don't like the `word` vector in new files I think it's not needed. I bet it works on Android 4 but I'm asking to be sure: did you test it on Android 4?

**Comment by SaumiaSinghal** [comment]
Okay @grzesiek2010, I'll remove that. No, Not on Android 4.0, i tested it on Android 5.1 and 8.0.

**Comment by SaumiaSinghal** [comment]
Done @grzesiek2010.

**Comment by grzesiek2010** [comment]
Ok, thanks, I took a quick look using Android 4 and seems fine so it's ready for testing.
@opendatakit-bot label "needs testing"

**Comment by mmarciniak90** [comment]
**Tested with success!**

Verified on Android 4.1, 4.2, 4.4, 5.1, 6.0, 7.0, 8.1
Verified light and dark theme. 
Icons look and work as previously.

@opendatakit-bot label "behavior verified"
@opendatakit-bot unlabel "needs testing"

**Review by lognaturel — APPROVED** [review]

**Pull request merged**
