### PR TITLE
Auto-increment build number and move to Settings

### LINKED ISSUE #238: Automate versionCode increments and remove it from the interface
It's not clear to me why build number needs to be front and center. It should auto-increment and probably be moved to settings or made smaller.

### PR DESCRIPTION
**Pull request by grzesiek2010**
This PR is in reference to resolve #238

### CODE REVIEW

**Comment by lognaturel** [comment]
This looks great, thanks @grzesiek2010! One small thing - I notice that some of the Gradle code comes from [here](http://stackoverflow.com/questions/21405457/autoincrement-versioncode-with-gradle-extra-properties). That's great and very much encouraged instead of reinventing the wheel but we do want to credit it. I'll add this to the contribution guide in a bit.

This does a great job of automating the existing process which is to increase the build number every time a release build is generated. Seeing it like this got me thinking about what the meaning of a build number is and whether we could make it even more useful by perhaps having it dynamically generated based on something like git history. Let's have some community discussion around that.

**Comment by grzesiek2010** [comment]
Actually it's from http://devdeeds.com/auto-increment-build-number-using-gradle-in-android/

**Comment by lognaturel** [comment]
Ahh, ok. @jayakrishnan-pm doesn't have an explicit open source, Apache-2.0 compatible license on his blog so we can't use that as the source (@jayakrishnan-pm something to consider adding!). In this case, we're lucky he also posted it on StackOverflow and can credit him from there. [Here](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#code-from-external-sources) is the new section on including code from external sources. Let me know if you have any suggestions.

Let's leave this one aside as we think about whether it's the most helpful behavior.

**Comment by jayakrishnan-pm** [comment]
Hello Hélène Martin,

Just saw your mail and conversation in this morning and i am writing this
mail to tell you that you can use the code (
http://devdeeds.com/auto-increment-build-number-using-gradle-in-android/) in
your project. Actually this groovy code is based on a stackoverflow answer
what i did is just modified the script so that it can be reused in projects
and created a tutorial on it.

Ofcourse am thinking about adding free open source licence to my blog
posts. Thank you for pointing this out.

Best regards!

Jayakrishnan P.M
Android Application Developer

**Comment by lognaturel** [comment]
@grzesiek2010 I'm going to close this PR now that we have further discussed what the build number should be. Please see the comment at the bottom of #238. Thanks! 😊

**Pull request closed without merging**
