### PR TITLE
Fixed the problem with finding an instance file during sending a form to GoogleSheets

### LINKED ISSUE #2847: Document has no root element!
#### Software and hardware versions 
Collect v1.19.0 an older versions

#### Problem description
https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/5b1e1bde6007d59fcd7ce3ad?time=last-seven-days&sessionId=5C57E18402C600013D8BDB7A89A42D26_DNE_0_v2

https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/5b84087f6007d59fcdf61bfc?time=last-seven-days
```
org.kxml2.kdom.Document.getRootElement (Unknown Source)
org.javarosa.xform.parse.XFormParser.getXMLDocument (XFormParser.java:435)
org.javarosa.xform.parse.XFormParser.getXMLDocument (XFormParser.java:384)
org.javarosa.xform.parse.XFormParser.restoreDataModel (XFormParser.java:2157)
org.javarosa.xform.parse.XFormParser.restoreDataModel (XFormParser.java:2182)
org.odk.collect.android.tasks.FormLoaderTask.importData (FormLoaderTask.java:412)
org.odk.collect.android.upload.InstanceGoogleSheetsUploader.getInstanceElement (InstanceGoogleSheetsUploader.java:302)
org.odk.collect.android.upload.InstanceGoogleSheetsUploader.uploadOneSubmission (InstanceGoogleSheetsUploader.java:135)
org.odk.collect.android.upload.AutoSendWorker.doWork (AutoSendWorker.java:148)
```

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #2847 

#### What has been done to verify that this works as intended?
I tested sending forms to Google Sheets (encrypted forms too).

#### Why is this the best possible solution? Were any other approaches considered?
The issue takes place when an instance file does not exist. I can imagine two cases:
1. A case with deleting instances
- save a form
- open the `Send Finalized Forms` list
- delete the instance file from the storage
- try to send a form

This case is solved in the second commit. I think it's rather a rare case in most reports we have are caused by the second case.

2. A case with encrypted forms
Sending encrypted forms to Google Sheets doesn't make sense of course. Currently, we try to do that what ends up with empty values. In the first commit, I added a check to avoid such a case. Sending empty values is not a big problem but encrypted forms might cause the crashes we can see in reports, why?
As described here: https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/upload/InstanceServerUploader.java#L165

an encrypted instance might be named just `submission.xml` that's why we can't find it.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This pr is not risky. I think that we just need to test sending forms to Google Sheets (encrypted forms as well).

#### Do we need any specific form for testing your changes? If so, please attach one.
Any form, any encrypted form.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by cooperka — APPROVED** [review]
Is it true that there are no use-cases for sending encrypted forms to Google Sheets? If so, LGTM.

**Comment by grzesiek2010** [comment]
> Is it true that there are no use-cases for sending encrypted forms to Google Sheets? If so, LGTM.

That's true.

**Comment by grzesiek2010** [comment]
@shobhitagarwal1612 if it looks fine to you too please add `needs testing` label

**Review by shobhitagarwal1612 — APPROVED** [review]

**Comment by mmarciniak90** [comment]
**Tested with success.**

Dialogs are visible:

|screenshot_2019-02-19-10-58-53|screenshot_2019-02-19-11-24-35|
|---|---|

Verified on Android: 4.1, 4.2, 4.4, 5.1, 6.0, 7.0, 8.1

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Pull request merged**
