### PR TITLE
Updating the sqlite constant name to match sqlite documentation.

### PR DESCRIPTION
**Pull request by nribeka**

### CODE REVIEW

**Comment by lognaturel** [comment]
Ah, I'm sorry, I think I misunderstood its meaning when @lakshyagupta21 and I were reviewing the last PR. It refers to the number of variables which can be included in a query, is that right?

**Comment by nribeka** [comment]
Yeah, I think we should match the name with the one mentioned in the sqlite documentation.

Search SQLITE_MAX_VARIABLE_NUMBER in [SQLite Documentation](https://www.sqlite.org/limits.html).

**Comment by lakshyagupta21** [comment]
@nribeka I agree with you its better to change variable name to  SQLITE_MAX_VARIABLE_NUMBER according to the Documentation.

**Comment by lognaturel** [comment]
My apologies, I just got confused and was wondering what in the world a constant variable number was. 😆

**Pull request merged**
