### PR TITLE
Report crashes only for the collect release

### LINKED ISSUE #1472: Forks shouldn't report to Firebase Crash
Currently, we get crash reports from forks and from developer debug builds. Why is this happening and how can we prevent it? The intent is to only get crashes from release builds of the core.

This is problematic because a lot of forks have really buggy extensions that overwhelm the crash list, making it hard to see true Collect crashes.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #1472 

**What has been done to verify that this works as intended?**
It's a fix for #1554 that solution was wrong since all crashes have been reported automatically anyway.

**Why is this the best possible solution? Were any other approaches considered?**
Now I use new method `setCrashCollectionEnabled` which is available in v11

**Are there any risks to merging this code? If so, what are they?**
No.

**Do we need any specific form for testing your changes? If so, please attach one.**
No

### CODE REVIEW

**Comment by lognaturel** [comment]
This would require uses to update Play Services, right? See the discussion about that at https://github.com/opendatakit/collect/issues/478

Basically, Play Services is a really big download for many connections around the world so it's going to be a burden for users. We should try to delay this as much as possible.

This is a nice fix but I'm wondering whether it's compelling enough to force the update. Any opinions? @yanokwa @shobhitagarwal1612?

**Comment by grzesiek2010** [comment]
@lognaturel most likely there is another option that doesn't require this update. If you want I can implement it in a different way. Just let me know what your decision is.

**Comment by lognaturel** [comment]
I do think it's worth looking into other options, please!

**Comment by grzesiek2010** [comment]
@lognaturel according to https://firebase.google.com/docs/crash/disable-sdk looks like it should be a proper solution that doesn't need updating dependancies.

**Review by lognaturel — APPROVED** [review]

**Pull request merged**
