### PR TITLE
change png icons to vector (#1858)

### LINKED ISSUE #1858: Replace png icons from FormEntryActivity with vectors
#### Software and hardware versions 
Collect v1.12.2 and older versions

#### Problem description
Replace png icons from FormEntryActivity with vectors

#### Steps to reproduce the problem
Just open any form.

screenshot_2018-02-13-13-38-05

#### Expected behavior
We should use vectors instead of pngs, and both icons should be black like here for example: 
screenshot_2018-02-13-13-38-01

it looks better.

@opendatakit-bot label "quick win"

### PR DESCRIPTION
**Pull request by lumarega**
Closes #1858 

#### What has been done to verify that this works as intended?
tested locally to verify that the images were changed

#### Why is this the best possible solution? Were any other approaches considered?
yes
#### Are there any risks to merging this code? If so, what are they?
no
#### Do we need any specific form for testing your changes? If so, please attach one.
no

### CODE REVIEW

**Comment by grzesiek2010** [comment]
@lumarega 
answering your [question](https://github.com/opendatakit/collect/issues/1858#issuecomment-372060114) it's ok to use another icon I think since I also wasn't able to find identical one but not that one you used because it looks like an icon for sorting. Could you try to find something more similar?

**Comment by grzesiek2010** [comment]
This one is completely different but more appropriate I think https://material.io/icons/#ic_explore
or maybe https://material.io/icons/#ic_details (but I prefer the first option)

@lognaturel what do you think?

**Comment by shobhitagarwal1612** [comment]
How about this? https://material.io/icons/#ic_low_priority

**Comment by lognaturel** [comment]
While I do like the low priority icon @shobhitagarwal1612 is suggesting, I think this is the kind of change that should get community feedback. It will also require changing a lot of screenshots in documentation so we should not take it lightly.

@lumarega you can either make this change just for the save icon or if you are feeling a bit adventurous, you can convert the goto icon to a vector using Inkscape or a combination of an online converter and Inkscape to clean up.

Either way, you will also need to delete the corresponding png(s) so that the lint checks pass.

**Comment by grzesiek2010** [comment]
> @lumarega you can either make this change just for the save icon or if you are feeling a bit adventurous, you can convert the goto icon to a vector using Inkscape or a combination of an online converter and Inkscape to clean up.

I can prepare an identical icon in SVG if you can't so please add a pull request just for the save icon.

**Comment by lumarega** [comment]
Thanks @lognaturel for pointing that out. So first I´m going to change only the save button and send a PR for it. And then I will try to draw it using inkscape since the SVG output icon of the online converter tools I tried were not very good.

@grzesiek2010 thanks! I never used inkscape but I´m going to try it out. If I can´t do it I let you know. 

Thanks for your suggestion @shobhitagarwal1612 .

**Comment by lognaturel** [comment]
@lumarega You can leave this PR open since we have a good plan to get both icons changed! Let us know your experience with Inkscape in about a day and @grzesiek2010 should be able to do it quickly if needed. Thanks everyone!

**Pull request closed without merging**
