### PR TITLE
Add icons to buttons

### LINKED ISSUE #6016: Add icons to buttons
**Context**
As part of our work improving the [Geo buttons](https://github.com/orgs/getodk/projects/9/views/8?pane=issue&itemId=50778689), we want to add icons to other buttons to make them more intuitive. 

We will not be changing the language as part of this story.

**Icons**
Please see [Google sheet](https://docs.google.com/spreadsheets/d/1wxC5Uz5WaMsGI6pMMpDuhXQPWBJyjqlVtsnyNGgSjHw/edit#gid=0)

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #6016

#### Why is this the best possible solution? Were any other approaches considered?
As described in the issue we want to make the buttons more intuitive by adding icons.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It doesn't require testing if question types work well. We can focus on the icons to make sure they are displayed properly and there are no places (questions) we have missed.
I've realized that there is one extra case where we display a button in the form view [External apps to populate multiple fields](https://docs.getodk.org/collect-external-apps/#external-apps-to-populate-multiple-fields). That button used to populate multiple fields should also have an icon and look like the buttons used in normal questions so I've added some visual tweaks there.

#### Do we need any specific form for testing your changes? If so, please attach one.
The `All question types` form would be good for testing all types of questions. In order to test populating multiple fields you can use my app: https://github.com/grzesiek2010/CollectAnswersProvider/tree/master

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by alyblenkin** [comment]
@grzesiek2010 - the filled icons work really well! This will make a massive improvement for end users. They might still be too small, but we can come back to that. 

Before increasing the button icons, we should make them all filled icons. I specifically selected outlines for a few of them (e.g. clock, choose file, compass) because they are typically more recognizable than when they are filled. But they are too squished and hard to read here, likely because they are more detailed than the icons. I have updated the [Google sheet ](https://docs.google.com/spreadsheets/d/1wxC5Uz5WaMsGI6pMMpDuhXQPWBJyjqlVtsnyNGgSjHw/edit#gid=0)and highlighted the ones that need to change. We should see if that helps before we change the size.

Screenshot 2024-03-18 at 1 05 18 PM


If they are still too small after we change the outlined icons, we should consider making all of the button icons slightly larger. The current size works well with smaller buttons, as seen below, but the icons get lost when we have full-width buttons. 
 
Screenshot 2024-03-18 at 1 05 38 PM


Side note: @seadowg the dialog seems to have shifted to purple...Maybe we can chat about this later this week!

**Comment by grzesiek2010** [comment]
> I have updated the [Google sheet ](https://docs.google.com/spreadsheets/d/1wxC5Uz5WaMsGI6pMMpDuhXQPWBJyjqlVtsnyNGgSjHw/edit#gid=0)and highlighted the ones that need to change.

Done.

What about the geo icons? I saw you have highlighted them as well. Should we maybe edit them/create our own if there are no filled versions of them?

**Comment by grzesiek2010** [comment]
> Side note: @seadowg the dialog seems to have shifted to purple...Maybe we can chat about this later this week!

I'm not sure but I guess this might be caused by https://github.com/getodk/collect/pull/5974

**Comment by seadowg** [comment]
> I'm not sure but I guess this might be caused by https://github.com/getodk/collect/pull/5974

Yup looks like it! @alyblenkin they've updated the Material Components implementation so it uses the proper surface container color system (https://material.io/blog/tone-based-surface-color-m3) as opposed to the weird "elevation overlay color" we were playing around with before. We should do another pairing session to flesh out those colors.

**Comment by alyblenkin** [comment]
> Done.

Amazing! Thank you. The annotate, choose file, calendar, time, bearing, icons are a lot more recognizable filled 🎉

To discuss on our call shortly: 
- I'm still unsure about the add audio icon (the music note might be too small)
- For the external audio, file, and video widget, do you think that we should use the same open new icon instead?

Screenshot 2024-03-19 at 7 47 17 AM

> What about the geo icons? I saw you have highlighted them as well. Should we edit them/create our own if there are no filled versions of them?

Yes, I was hoping we could quickly chat about this on the call!

**Comment by alyblenkin** [comment]
@grzesiek2010 We discussed earlier about experimenting with increasing the icons to 22 or 24dp (without changing button size) to see if that helps with legibility. 

> What about the geo icons? I saw you have highlighted them as well. Should we edit them/create our own if there are no filled versions of them?

I don't think we should create our own version. I think we should increase the size to see if that helps.

**Comment by grzesiek2010** [comment]
@alyblenkin I've increased the icon size from default 18dp to 20dp. Let me know if it's not too much maybe 19dp would be better.
The only icon that still does not look well is https://fonts.google.com/icons?selected=Material+Symbols+Outlined:playlist_add_check:FILL@0;wght@400;GRAD@0;opsz@24 used in the range picker widget. Can we maybe use a different one that doe not have that much vertical padding?

**Comment by alyblenkin** [comment]
> @alyblenkin I've increased the icon size from default 18dp to 20dp. Let me know if it's not too much maybe 19dp would be better. 

Ah I thought you said they were already 20dp. 20dp looks a lot better!! It's noticeably better with the line-based icons.

> The only icon that still does not look well is https://fonts.google.com/icons?selected=Material+Symbols+Outlined:playlist_add_check:FILL@0;wght@400;GRAD@0;opsz@24 used in the range picker widget. Can we maybe use a different one that doe not have that much vertical padding?

Agreed. I've updated the [sheet](https://docs.google.com/spreadsheets/d/1wxC5Uz5WaMsGI6pMMpDuhXQPWBJyjqlVtsnyNGgSjHw/edit#gid=0) with the ones that still look too small.

**Comment by alyblenkin** [comment]
I think this is nearly done! Select one from map and the choose audio icons look great. The ranking icon hasn't changed though. 

Edit: Just saw the notes you added to the google sheet.

**Review by alyblenkin — APPROVED** [review]

**Review by seadowg — APPROVED** [review]

**Comment by srujner** [comment]
One thing to discuss:
Should the icon size be scaled with the text size?
Screenshot_20240326-105610

**Comment by alyblenkin** [comment]
I'm not sure if this is going to be added as a separate issue, but we also discussed changing all the [launch icons](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Aopen_in_new%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024) for external questions, so they are consistent. 

We discussed how the mic icon might be a bit misleading for the external audio question, as it seems like it will start recording straight away, which might not always be the case for all audio widgets.

Screenshot 2024-03-26 at 1 22 46 PM

**Comment by srujner** [comment]
**Tested with Success!**

Verified on device with Android 12, 13, 14 

Verified cases:
- Work towards #6016;
- Checked icons in the All Question types form; 
- Light and Dark mode;
- Used Collect Intents tester to test populating multiple fields;
- Different Languages, RTL; 
- Different font size in device settings and in the app settings

**Comment by WKobus** [comment]
**Tested with Success!**

Verified on device with Android 11

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on device with Android 10, 14

**Pull request merged**
