### PR TITLE
Persian calendar

### LINKED ISSUE #3084: Support persian calendar
Some time ago one of our users asked  about supporting persian calendar:
https://forum.opendatakit.org/t/persian-calendar-available-for-odk/19256

There are some java libs we could to do that.

@lognaturel please consider it, maybe it could be added to v1.23

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #3084 

#### What has been done to verify that this works as intended?
I tested the form attached to the issue and added automated tests.
Results were confirmed using two online converters:
http://www.iranchamber.com/calendar/converter/iranian_calendar_converter.php
https://calcuworld.com/calendar-calculators/persian-calendar-converter/

#### Why is this the best possible solution? Were any other approaches considered?
I analyzed other libs we could and shared my thoughts in the issue. Initially, I didn't want to use a lib created by one person by all the others were too big so I decided to try this one despite the fact it's not something actively maintained.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Changes implemented here are not risky or related to other functionalities so testing the new calendar would be enough.

#### Do we need any specific form for testing your changes? If so, please attach one.
[PersianForm.xml.txt](https://github.com/opendatakit/collect/files/3256953/PersianForm.xml.txt)

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
Yes, I'll create an issue.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by grzesiek2010** [comment]
@lognaturel 
the implementation is based on https://github.com/mohamadian/PersianJodaTime but I forgot about licenses. There is no info there. Should we ask the owner?

**Comment by lognaturel** [comment]
I think this has the huge advantage of fitting right in with the other calendar implementations. 👍

Good call on the license. Yes, please! Since basically all the code came from https://github.com/zubinkavarana/joda-time which is Apache 2.0 I /think/ we're ok but it would be best if the repackaged library had an explicit license.

**Comment by grzesiek2010** [comment]
A license file has been added https://github.com/mohamadian/PersianJodaTime/blob/master/LICENSE

**Comment by lognaturel** [comment]
Looks like the license has been changed to Apache v2 which is great. Once you change that in the licenses, I approve and it's ready for QA. 👍

**Comment by grzesiek2010** [comment]
> Once you change that in the licenses, I approve and it's ready for QA.

Ready.

**Review by lognaturel — APPROVED** [review]
Well that sure was a more relaxing experience than the Myanmar calendar...

**Comment by mmarciniak90** [comment]
**Tested with success**

Verified on Android: 4.2, 4.4, 5.1, 6.0, 7.0, 8.1

Verified cases
- proper naming
- removing response
- hierarchy view
- edit saved form
- read-only

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Pull request merged**
