### PR TITLE
#794 fixed signature widget

### LINKED ISSUE #794: Signature widget in portrait mode
#### Software and hardware versions 
Collect v1.4.16

#### Problem description
The current signature widget seems to have gone backwards from its previous capabilities. The phone switches into landscape mode for signature but then only shows a small portrait style window within that to take the signature. End results is that captured signature images are a lot smaller than the used to be and in portrait.

#### Steps to reproduce the problem
Create a form with an image with appearance signature

#### Expected behavior
The screen switches to landscape, the user has nearly the whole length of the phone to do their signature, the captured image is in landscape.

#### Other information 
device-2017-03-30-105506

@max2me,  Maxim may have a view on this issue.

### PR DESCRIPTION
**Pull request by rijuldhir**
Fixes #794

### CODE REVIEW

**Comment by lognaturel** [comment]
Can you please say more about how you verified this change? It doesn't change anything for me!

**Comment by lognaturel** [comment]
This doesn't work on my Nexus 5 running Android 6.0.1. Did you take a look at @max2me's comment about timing and go back to see if you can identify the commit that introduced the problem? It should be in release 1.4.11 I believe.

This change also seems to make the button for gathering signatures and the signature preview disappear when returning to the form from the widget screen.

**Comment by rijuldhir** [comment]
Yes I guess will need to look more as increasing the size is not helping

**Comment by lognaturel** [comment]
@rijuldhir This one is important to get in before Wednesday's code freeze. Do you think you'll have time to complete it Tuesday? If not, it's ok, someone else can take it on.

**Comment by rijuldhir** [comment]
@lognaturel My final exams are on. I will try it but someone can work on it to be on a safer side.

**Comment by lognaturel** [comment]
@rijuldhir Don't worry about it, exams are important! Best of luck with those and there will be plenty of other issues to look at when they are over. 😊

**Comment by lognaturel** [comment]
@grzesiek2010 Will be looking at this one.

**Pull request closed without merging**
