### PR TITLE
Highlight question that has caused validation error in field list

### LINKED ISSUE #2118: When there's a validation error caused by a question in a field list, it's not clear which question has caused it
#### Software and hardware versions 
Collect v1.14.0

#### Problem description
When there's a validation error caused by a question in a field list, it's not clear which question has caused it

#### Steps to reproduce the problem
1. Open a form with multiple questions in a field list, at least one of which has a constraint or required condition (e.g. [field-list-constraint.xml.txt](https://github.com/opendatakit/collect/files/1900134/field-list-constraint.xml.txt))
1. Put in an answer that fails the constraint or omit a required question
1. Swipe forward, see a toast
1. Note that it's not clear which question has resulted in the toast

#### Expected behavior
It should be clear which question caused the problem. The screen should be scrolled to the problematic question and the question should be highlighted in some way (e.g. changing the background color). Ideally the question gets focus where appropriate (i.e. a question with edittext).

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #2118  

#### What has been done to verify that this works as intended?
I tested the attached form.

#### Why is this the best possible solution? Were any other approaches considered?
As we agreed fading out with red color is the best solution.

#### Are there any risks to merging this code? If so, what are they?
It shouldn't be risky.

#### Do we need any specific form for testing your changes? If so, please attach one.
[AOOP.xml.txt](https://github.com/opendatakit/collect/files/2006675/AOOP.xml.txt)

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew pmd checkstyle lint findbugs` and confirmed all checks still pass.
- [x] verified that any new UI elements use theme colors so that they work with both light and dark themes.

### CODE REVIEW

**Comment by lognaturel** [comment]
Nice! 

I don't love the flashing. I'm guessing you were looking for a way to make sure to catch the user's attention? I understand not wanting to keep the border until swipe since it's confusing once it has been fixed. What about fading it out? Red would be a more common color for these kinds of things, was there a reason you picked blue? 

Does anyone else have thoughts here? @yanokwa?

**Comment by grzesiek2010** [comment]
> I'm guessing you were looking for a way to make sure to catch the user's attention? 

yes.

> was there a reason you picked blue?

no, I just used our tint color to show my proposal.

What do you think about this effect?
ezgif com-video-to-gif 3

**Comment by yanokwa** [comment]
I really like the red and the filling of the entire question!

**Comment by lognaturel** [comment]
Sounds great to me. Let's do it, @grzesiek2010.

**Comment by grzesiek2010** [comment]
It's ready!
Only one concern: currently I highlight a question only if it's on one page with other questions. Is it ok or should we do that in all cases?

**Comment by lognaturel** [comment]
> currently I highlight a question only if it's on one page with other questions. Is it ok or should we do that in all cases?

I like the way you've done it now and would keep it that way. If there's only one question on the page, there's no ambiguity about which one caused the problem.

**Review by lognaturel — APPROVED** [review]

**Comment by mmarciniak90** [comment]
@grzesiek2010 there is one problem in the case where text or number question is first on the list.
Use case:
1. The user starts a form with text or number as the first question on field-list
2. The user adds an invalid answer
3. The user jumps to end and clicks on `Save Form and Exit`
4. The user is moved back to correct field-list but the highlighted question is not at the beginning. Input focus is set on first question and keyboard is visible.

[All_widgets_one_page.xml.txt](https://github.com/opendatakit/collect/files/2012503/All_widgets_one_page.xml.txt)

screenshot_20180517-112354

**Comment by mmarciniak90** [comment]
@opendatakit-bot unlabel "needs testing"

**Comment by grzesiek2010** [comment]
@lognaturel I've never liked this feature. Is it really important or maybe we can get rid of that automatic focus (and opening the keyboard)?
I think I'm not alone, for example, in TaroWorks the mentioned feature is removed and users have to click on EditText. It doesn't look good to me especially when we have a few questions on one page.

What do you think? If you don't agree I'll try to find a solution.

**Comment by lognaturel** [comment]
@grzesiek2010 Do you suggest removing the autofocus for all fields or just for fields in field lists? I think it's useful when questions are on single screens, especially on large devices.

It's true that it can be problematic in field lists and is not as useful as it could be because, as #2215 points out, there is no consistent way to navigate between fields.

How about only doing the autofocus and keyboard show if the first question in the field list contains an `EditText`? I think you can check on whether the widget is a descendent of stringwidget? I haven't carefully looked at this so I may be totally wrong. If that's too hard, my next preference would be to never show the keyboard if the screen contains a field list. If that's still complicated, we should have a broader discussion about removing autofocus across the board.

**Comment by grzesiek2010** [comment]
> How about only doing the autofocus and keyboard show if the first question in the field list contains an edit test?

sorry but I completely don't understand. What do you mean by `edit test`?

**Comment by lognaturel** [comment]
😭 Sorry, I meant `EditText`. 🧠The issue comes up when the first question to have an `EditText` is not the first question overall. For example, if the first question is a select and the second is a string question, the second question gets focus. We could possibly avoid it by only giving a question focus if the first question is a string/integer/decimal/etc question which includes an `EditText`.

**Comment by grzesiek2010** [comment]
Ok, now I see but

> The issue comes up when the first question to have an EditText is not the first question overall. For example, if the first question is a select and the second is a string question, the second question gets focus. 

That's not true the keyboard is shown (and this issue takes place) only if the first question contains an EditText.

I like the idea of showing the keyboard only if it's a single question.

**Comment by lognaturel** [comment]
> That's not true the keyboard is shown (and this issue takes place) only if the first question contains an `EditText`.

Oh, of course, that makes sense.

> I like the idea of showing the keyboard only if it's a single question.

Let'd do that. 👍

**Comment by grzesiek2010** [comment]
@lognaturel it's ready and here is another form for testing which shows some different cases:
[Collect-2118.xml.txt](https://github.com/opendatakit/collect/files/2025462/Collect-2118.xml.txt)
please take a look.

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
Nice to see a bunch of duplicated code go away!

**Comment by mmarciniak90** [comment]
@lognaturel @grzesiek2010 everything is great on Androids newer than 4.1. 
Problem is on Android 4.1, where a question is not highlighted. 
The user is moved to correct question, toast is visible - the problem is only with a highlight in red. 
I will create a separate issue for a fix on Android 4.1 to not blocks the merge of this great feature.

**Tested with success**

Verified on Android: 4.2, 4.4, 5.1,6.0, 7.0, 8.1

* question is highlighted in red only in the field list
* there is no focus > keyboard is not visible in the field list

@opendatakit-bot label "behavior verified"
@opendatakit-bot unlabel "needs testing"

**Pull request merged**
