### PR TITLE
Fixes #2364: Unable to play video recorded by selfie-video widget on Android 4.2

### LINKED ISSUE #2364: Unable to play video recorded by selfie-video widget on Android 4.2
#### Software and hardware versions 
Collect v1.15.x, Android v4.2.x,

#### Problem description
Unable to play video recorded by selfie-video widget on Android 4.2  

#### Steps to reproduce the problem
1. Open selfie video widget on Android 4.2
2. Record a video
3. Click on Play Video button

#### Expected behavior
Video should be played using a default video player app or some other installed app - I tried VLC media player - which worked on other Androids.
I am able to play video recorded by regular video widget with using both app.

I used All widgets form.

### PR DESCRIPTION
**Pull request by SaumiaSinghal**
Closes #2364 

#### What has been done to verify that this works as intended?
I tested it on Nexus 4, API 16 and on Android 5.1.

#### Why is this the best possible solution? Were any other approaches considered?
I found that for lower API, selfie video widget was saving the file in Pictures/ directory while it was still retrieving the same from odk/Instances folder.  

#### Are there any risks to merging this code? If so, what are they?
No

#### Do we need any specific form for testing your changes? If so, please attach one.
Any form having Selfie Video widget like AllWidgets form.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew pmd checkstyle lintDebug spotbugsDebug` and confirmed all checks still pass.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by yanokwa** [comment]
@SaumiaSinghal Were you able to try this on a higher API device to see if the behavior is as expected?

**Comment by SaumiaSinghal** [comment]
Yes @yanokwa, I checked on a higher API device too.

**Comment by yanokwa** [comment]
Can you please specify the version? The more details you can provide then easier it is for maintainers and testers to know where we need to focus our efforts.

**Comment by SaumiaSinghal** [comment]
Yes @yanokwa, I tested it on my emulator running Nexus 4 API 16 and on my phone too, on Android 5.1. I'll include that in the description of my PR too.

**Comment by grzesiek2010** [comment]
@SaumiaSinghal 
Nice! Only one thing: I noticed you copied the code from `Camera2VideoFragment#getVideoFilePath()` I think it would be better to have that code in one place not duplicated. I was thinking about moving that method `Camera2VideoFragment#getVideoFilePath()` from` Camera2VideoFragment` to a util class and use in both places. Maybe `CameraUtill` class is a good place? What do you think? Could you implement that small code improvement?

**Comment by SaumiaSinghal** [comment]
Yes @grzesiek2010, This seems nice. I will do that.

**Comment by grzesiek2010** [comment]
@SaumiaSinghal you need to fix your branch. You have some unrelated changes perhaps from other commits.

**Comment by SaumiaSinghal** [comment]
Yes i know @grzesiek2010, but whenever i tried to squash my commits, the same thing happens. and one more thing, ./gradlew pmd is not working on my machine, can u suggest something?

**Comment by SaumiaSinghal** [comment]
But wait I'll fix this.

**Comment by shobhitagarwal1612** [comment]
Try rebasing onto master branch

**Review by grzesiek2010 — APPROVED** [review]

**Comment by grzesiek2010** [comment]
Ok looks good, so it's ready for testing, thanks!

**Comment by mmarciniak90** [comment]
**Tested with success!**

Verified on Android 4.2
I did not notice regression on Android: 4.4, 5.1, 6.0, 7.0, 8.1

@opendatakit-bot label "behavior verified"
@opendatakit-bot unlabel "needs testing"

**Pull request merged**
