### PR TITLE
Move entities package from JavaRosa

### PR DESCRIPTION
**Pull request by seadowg**
~~Blocked by https://github.com/getodk/javarosa/pull/772~~

This allows us to iterate on entities without as much back and forth between Collect and JavaRosa changes.

#### Why is this the best possible solution? Were any other approaches considered?

I could have converted more classes to Kotlin, but there's a lot of code here and I felt like that would easier to review on a case by case basis as we touch those classes.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

A lot of code has been moved, and a few things have been converted to Kotlin, so there's definitely a risk of type conversion problems. The most important things to look at will be form loading and finalization, especially for forms with entities.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by lognaturel** [comment]
Am I understanding correctly that the next steps are to put in a JR PR to remove these same files, merge to master, do some quick QA?

Is the `entities.javarosa` subpackage named that way because it interacts closely with the JR API? I think I'd mostly expect that functionality to be directly in `entities` but maybe there's a benefit to the subpackage that I'm not seeing.

**Review by lognaturel — APPROVED** [review]

**Review by grzesiek2010 — APPROVED** [review]

**Comment by seadowg** [comment]
> Am I understanding correctly that the next steps are to put in a JR PR to remove these same files, merge to master, do some quick QA?

Yup! There was a bit of "chicken n' egg"-ing going on here where I needed to expose scenario, move everything over and then finally delete so as not to break anything (due to auto snapshot releases).

> Is the entities.javarosa subpackage named that way because it interacts closely with the JR API?

Spot on. Basically Collect now has some code that's for its own entities implementation and then some that's its JavaRosa "plugin".

**Comment by grzesiek2010** [comment]
@seadowg don't you think this pr needs testing? You didn't add the label.

**Comment by seadowg** [comment]
Whoops! Adding now. I usually only add it after reviewing so generally don't do it for my own PRs. Are you thinking of it the other way around?

**Comment by grzesiek2010** [comment]
> I usually only add it after reviewing so generally don't do it for my own PRs. Are you thinking of it the other way around?

I don't have any strong preferences. Usually, I review and manage immediately. In such cases, I add the label. The person who merges should at least double-check tha the label is there.

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on a device with Android 10

**Verified Cases:**
- registration and update forms
- saving, sending, finalizing forms

**Comment by WKobus** [comment]
**Tested with Success!**

Verified on a device with Android 14

**Pull request merged**
