### PR TITLE
Fixed the title of the Open source licenses page under About section.

### LINKED ISSUE #2397: Title of open source licenses screen is not human-friendly
#### Software and hardware versions 
Since the open source licenses screen was introduced

#### Problem description
Title of open source licenses screen is not human-friendly.

#### Steps to reproduce the problem
1. In the overflow menu from the main screen, tap 'about'
1. Tap 'open source libraries / licenses'

See that the menu shows the file URI.

#### Expected behavior
Something friendly like "Open source licenses"

#### Other information 
I think this is likely as simple as setting the `title` tag.

### PR DESCRIPTION
**Pull request by DreamyPhobic**
Closes #2397

#### What has been done to verify that this works as intended?

I tested it by opening the Open Source Licenses page under the About section. It is showing the title as intended.

 #### Why is this the best possible solution? Were any other approaches considered?

It's a one-line and only solution for this issue.   

#### Are there any risks to merging this code? If so, what are they?

No.

#### Do we need any specific form for testing your changes? If so, please attach one.

No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew pmd checkstyle lintDebug spotbugsDebug` and confirmed all checks still pass.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by DreamyPhobic** [comment]
Please, Can anybody help me with this..?

**Comment by SaumiaSinghal** [comment]
Hey, I had the same problem once, try disabling Configuration on demand and then run `./gradlew pmd` locally on your machine. Hope this helps.

**Comment by jd-alexander** [comment]
The build is failing due to an issue with bintray. I think I have seen some chatter about them having timeout issues sometimes so a rebuild should be able to get this up and running.

**Comment by lognaturel** [comment]
Thank you for this, @DreamyPhobic! Great that you identified the problem when exploring Collect and then found the issue for it. 😊

And thanks @SaumiaSinghal and @jd-alexander for jumping in to help with the build failure! Now that the problem has been fixed by #2497 (thanks, @jd-alexander!), we can merge this and the build will pass.

**Review by lognaturel — APPROVED** [review]

**Comment by grzesiek2010** [comment]
It's not a good solution since WebViewActivity may be used in many different cases not only to display that page (open source licenses). It may be used to display ODK website/ODK forum/UrlWidget under some circumstances. I thought we agreed that each pr should be tested before merging.

**Pull request merged**
