### PR TITLE
Remove "Choose" from image, audio, video prompts #108

### LINKED ISSUE #108: Remove "Choose" from image, audio, video prompts
<a href="https://github.com/mitchellsundt"></img></a> **Issue by [mitchellsundt](https://github.com/mitchellsundt)**
_Thursday Jul 09, 2015 at 19:31 GMT_
_Originally opened as https://github.com/opendatakit/opendatakit/issues/893 (1 comment(s))_

---

Originally reported on Google Code with ID 892

```
This is not really an issue but it would be great if we could remove the "Choose Image"
button from the picture screen.

I am using ODK to control field workers and I want them to send me a picture at the
end of their workday showing me that their stand is still up and running right before
closing time.

Would that be possible?

Thanks!
```

Reported by `yael@soyhormiga.com` on 2013-08-16 19:29:31

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #108 

#### What has been done to verify that this works as intended?
I tested the attached form.

#### Are there any risks to merging this code? If so, what are they?
I would say it's not really risky but we need to test the attached form and other media widgets.

#### Do we need any specific form for testing your changes? If so, please attach one.
[NewAppearance.xml.txt](https://github.com/opendatakit/collect/files/1730983/NewAppearance.xml.txt)

### CODE REVIEW

**Comment by grzesiek2010** [comment]
@lognaturel I didn't implement that `new` appearance for `web` since you didn't mention it https://github.com/opendatakit/collect/issues/108#issuecomment-364589023 and as I understand we are going to deprecate that widget, am I right?

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
That sounds right to me, @grzesiek2010!

**Comment by mmarciniak90** [comment]
**Tested with success!**

Verified on Android: 4.1, 4.2, 4.4, 5.1, 6.0, 7.0, 8.0
Verified cases:
- new form NewAppearance
- saved form NewAppearance
- new form All widgets
- 'Do not keep activities' option

**Comment by mmarciniak90** [comment]
@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
Great to get this in, finally! Thanks @grzesiek2010, @mmarciniak90. 😊

**Pull request merged**
