### PR TITLE
User can reset a project

### LINKED ISSUE #4425: User can reset a project
~~Blocked by #4417~~

**Acceptance**

- [ ] Given I'm on the Projects dialog
When I click "Admin settings"
And I click "Project"
And I click "Reset project"
And I confirm
Then the project settings return to the Collect defaults

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #4425

#### What has been done to verify that this works as intended?
I tested resetting projects manually and improved automated tests.

#### Why is this the best possible solution? Were any other approaches considered?
This is the only solution.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This will be tested later as a whole feature.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by grzesiek2010** [comment]
I came across two problems related to resetting projects:
**The first one (more serious):** we keep credentials in one static hashmap:
```
private static final Map<String, HttpCredentialsInterface> HOST_CREDENTIALS = new HashMap<>();
```

that means if we clear them in preferences we do that for all projects.
What should we do? Keep them separately for every projects and then clear only those that were added for the current project?

**The second issue (less important):** The last option is clearing OSM tile cache. The problem is that it's not our folder and we are not responsible for it. That means it's a shared folder for all projects and if we clear it in one projects everything is removed.
I wonder if we need to that step at all... maybe we could just remove it?

@lognaturel what do you think?

**Comment by lognaturel** [comment]
> that means if we clear them in preferences we do that for all projects.

What are the actual implications of this? e.g. does it affect background jobs? I would expect the map to be cleared when switching projects.

If it does make sense to keep those credentials in memory for some reason, perhaps `webCredentialsUtils.clearCredentials(url)` could be used to only clear the current project's?

> it's not our folder

I don't really remember how this works. Do we specify a root that the cache folder gets put in? Or does the library just pick the folder for us? It looks like this behavior is already broken, probably since using scoped storage -- https://github.com/getodk/collect/issues/4464. It would be good to explore whether we have options like having each project set its own cache folder but if not, I think removing the option is ok.

**Comment by grzesiek2010** [comment]
> What are the actual implications of this? e.g. does it affect background jobs? I would expect the map to be cleared when switching projects.

Oh I think I misunderstood how we use that static hashmap it's rather for temporary credentials and even if we clear it we should be able to take username/password from settings:

```
    public @Nullable HttpCredentialsInterface getCredentials(@NonNull URI url) {
        String host = url.getHost();
        String serverPrefsUrl = getServerUrlFromPreferences();
        String prefsServerHost = (serverPrefsUrl == null) ? null : Uri.parse(serverPrefsUrl).getHost();

        // URL host is the same as the host in preferences
        if (prefsServerHost != null && prefsServerHost.equalsIgnoreCase(host)) {
            // Use the temporary credentials if they exist, otherwise use the credentials saved to preferences
            if (HOST_CREDENTIALS.containsKey(host)) {
                return HOST_CREDENTIALS.get(host);
            } else {
                return new HttpCredentials(getUserNameFromPreferences(), getPasswordFromPreferences());
            }
        } else {
            return HOST_CREDENTIALS.get(host);
        }
    }
```

but here we have another issue. We read `getUserNameFromPreferences()` and `getPasswordFromPreferences()` from the current project but if it's a background job that was created by an inactive project then it won't work.
It's not a problem when it comes to Central because there we don't use username/password but it might be a problem for aggregate or other servers like that.

@seadowg did you test background jobs with credentials or just with ODK Central?

**Comment by grzesiek2010** [comment]
> What are the actual implications of this? e.g. does it affect background jobs? I would expect the map to be cleared when switching projects.

Oh I think I misunderstood how we use that static hashmap it's rather for temporary credentials and even if we clear it we should be able to take username/password from settings. I tested it and it works well.

> I don't really remember how this works. Do we specify a root that the cache folder gets put in? Or does the library just pick the folder for us? It looks like this behavior is already broken, probably since using scoped storage -- #4464. It would be good to explore whether we have options like having each project set its own cache folder but if not, I think removing the option is ok.

when I debug it shows that the path is:
`/data/user/0/org.odk.collect.android/files/osmdroid/tiles`

We don't create that folder and the only thing we can do is setting a different location:
`DefaultConfigurationProvider.setOsmdroidTileCache(File osmdroidTileCache)`
but we would need to do that for every project, I mean after switching projects we would need to set that default osmdroid tile cache dir path.

I can create a separate issue for investigating this but for now I would just remove that option from resetting because I don't think it's important.

Do you agree?

**Comment by lognaturel** [comment]
>  I tested it and it works well.

🎉

> for now I would just remove that option from resetting

That sounds good to me. There was some reason why we added clearing that cache but @yanokwa would have to remind us. Maybe it had to do with space concerns and those are now less significant with modern devices.

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
I meant to review this yesterday and apparently got confused. Sorry about that! 😭

**Pull request merged**
