### PR TITLE
Prevent recording service from being recreated

### PR DESCRIPTION
**Pull request by seadowg**
Well this is a weird one. While investigating #4433 I found that if the app is restarted by Android the "Recording..." notification pops up. This is because we were returning `START_STICKY` from `onStartCommand` in `AudioRecorderService` when we really needed to be returning `START_NOT_STICKY`. Docs on these flags are [here](https://developer.android.com/reference/android/app/Service#START_NOT_STICKY) and it would be good for another developer to sanity check that the flag I've chosen seems to make sense.

Just to be clear, to reproduce the problem I found (and that this PR fixes) you can do:

1. Start a form with background recording
2. Find "Collect" in system settings
3. Revoke the microphone permission

#### What has been done to verify that this works as intended?

Verified manually. We could test that the service is sticky/not stick from the return of `onStartCommand` but it wouldn't verify any actual behaviour.

#### Why is this the best possible solution? Were any other approaches considered?

I'd initially thought that this service should be sticky because of the examples given in the docs. However, it doesn't seem like we'd ever want the service to be restarted by Android as we'll restart it if we need it for either internal or background recording.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

I think it'd be good to check internal recording and background before merging this if we've already covered it in the regression pass. If we haven't, I think just running through those features as part of the regression pass is good so we can just go ahead and merge this.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by grzesiek2010 — APPROVED** [review]

**Comment by kkrawczyk123** [comment]
@seadowg I am not exactly sure what the expected behavior of this PR is. I have noticed crash when following scenario:
1. Open form with a background recording
2. Revoke microphone permission
3. Go back to form 
4. Agree for microphone permission in form
5. Try to finalize form

I was able to reproduce it only on Android 7.1 device and @mmarciniak90 also experienced that on Android 7.0 device. 

see gif:
ezgif com-video-to-gif (53)

stacktrace:
`2021-02-18 16:22:17.812 22910-22910/org.odk.collect.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.odk.collect.android, PID: 22910
    java.util.NoSuchElementException
        at java.util.HashMap$HashIterator.nextEntry(HashMap.java:854)
        at java.util.HashMap$KeyIterator.next(HashMap.java:885)
        at org.odk.collect.android.formentry.RecordingHandler.handleBackgroundRecording(RecordingHandler.java:70)
        at org.odk.collect.android.formentry.RecordingHandler.lambda$handle$0$RecordingHandler(RecordingHandler.java:48)
        at org.odk.collect.android.formentry.-$$Lambda$RecordingHandler$V-ws2wEX8QL3nQl0XXD8NB2yn5M.onChanged(lambda)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
        at org.odk.collect.android.formentry.saving.FormSaveViewModel.lambda$createAnswerFile$1$FormSaveViewModel(FormSaveViewModel.java:378)
        at org.odk.collect.android.formentry.saving.-$$Lambda$FormSaveViewModel$2uu05vBIQlrmlmrKOPHT6fFCUdQ.accept(lambda)
        at org.odk.collect.async.CoroutineScheduler$immediate$1.invokeSuspend(CoroutineScheduler.kt:17)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6165)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)`

**Comment by seadowg** [comment]
@kkrawczyk123 sorry I should have said that I'd ~~expect~~ hope that nothing changes. 

Is that crash just in the PR and not reproducible on master?

**Comment by mmarciniak90** [comment]
> Is that crash just in the PR and not reproducible on master?

@seadowg It is reproducible on Beta 1 from Play Store.
I created a separate issue for mentioned crash.

**Comment by mmarciniak90** [comment]
**Tested with success**

Verified on Android 7.0, 8.1, 10.0

* revoke microphone permission during background recording
* revoke microphone permission during internal recording
* audio widget on field-list where other widgets are filled
* quick regression chceck on background recording

**Comment by kkrawczyk123** [comment]
Verified also on Androids 5.1, 7.1 and 9.0.

@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"

**Pull request merged**
