### PR TITLE
Inflate MediaLayout using xml 

### LINKED ISSUE #2127: Refactor list views using Adapter Pattern
#### Problem description
As @grzesiek2010 said in #2099 , It's better to refactor lists using **Adapter Pattern**. So thanks : )
> Xml Files ---> Adapter ---> Java Class

**It can:**
- Simplify our code and make it easier to read.
- Help us manage our list items.
- Remove the unnecessary `if-else` statements.
- Make code easier to patch fixes and changes.

**Which list may need this refactor?**
- [ ] Media Layout items: see `MediaLayout.java` --> `setAVT` method or others.
- [x] Jump/Hierarchy view items: see `HierarchyElementView.java` or others. (need discussion whether it needs a refactor or not)

#### Expected behavior
Code can be easier to read and modify with **Adapter Pattern**.

@opendatakit-bot label "refactor"
@grzesiek2010 I think PR #2123 and PR #2099 are **hot fix** pull requests focus on specific issues, if we need to refactor related lists, we can work on this issue after hot fixes were merged.

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Closes #2127 

#### What has been done to verify that this works as intended?
Verified on Redmi Note 4 (Android 7)

#### Why is this the best possible solution? Were any other approaches considered?
Simplifies a lot of logic that had to be added manually for RTL compatibility

#### Are there any risks to merging this code? If so, what are they?
Yes, this changes the way the media layout is inflated in the widgets. So, should be properly verified for normal locales as well as RTL locales

#### Do we need any specific form for testing your changes? If so, please attach one.
I used the `Birds` form available from default aggregate server for testing

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew pmd checkstyle lint findbugs` and confirmed all checks still pass.
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by shobhitagarwal1612** [comment]
@grzesiek2010 In this PR I have completely inflated the Media Layout using an xml as suggested by you in a comment in #2127 
Should I modify this further to incorporate the adapter pattern for the select one & select multi widgets?

**Comment by grzesiek2010** [comment]
> Should I modify this further to incorporate the adapter pattern for the select one & select multi widgets?

I don't know if it's needed you can investigate if we can benefit from such refactoring. I just wanted to create MediaLayout using xml to handle LTR and RTL easily without tons of if/else statements.

**Comment by shobhitagarwal1612** [comment]
> I just wanted to create MediaLayout using xml to handle LTR and RTL easily without tons of if/else statements.

This pull request already does fix that. Once this is fully tested and merged, then I will open another PR to try to refactor the code in the adapter pattern. What do you think? @grzesiek2010

**Comment by grzesiek2010** [comment]
> This pull request already does fix that.

Yes I know that's good.

> Once this is fully tested and merged, then I will open another PR to try to refactor the code in the adapter pattern. What do you think?

as I said if it brings any benefits then sure.

**Comment by mmarciniak90** [comment]
@shobhitagarwal1612, I compared your fix with v1.16.0 beta 2.
I noticed that text stays highlighted in blue when I played and paused the sound.

**Comment by mmarciniak90** [comment]
@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "regression"

**Comment by shobhitagarwal1612** [comment]
> I noticed that text stays highlighted in blue when I played and paused the sound.


@mmarciniak90 Fixed the issue

**Comment by grzesiek2010** [comment]
@opendatakit-bot label "needs testing"
@opendatakit-bot unlabel "regression"

**Comment by mmarciniak90** [comment]
Thanks, @shobhitagarwal1612, for fixing this small, appearance issue.

**Tested with success**
Verified on Android: 7.0, 6.0, 5.1, 4.4, 4.2

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Review by lognaturel — APPROVED** [review]

**Pull request merged**
