### PR TITLE
Ensure icon sizes are consistent

### LINKED ISSUE #438: Ensure icon sizes are consistent
Make sure the icons that are used in Google Drive downloads and in View Sent Form's encrypted forms are consistently sized.

### PR DESCRIPTION
**Pull request by grzesiek2010**
This PR is in reference to resolve #438 

The icons that are used in View Sent Form are ok but I noticed some missed icons and wrong sizes of icons from Google Drive downloads. 
I fixed this but using a little different icons because there aren't identicall here https://material.io/icons/.

### CODE REVIEW

**Comment by lognaturel** [comment]
The new icons look good. They're not centered vertically in each row, though, and I think they should be.

I think the reason that @yanokwa filed this is that the visibility off icon on "View Sent Form" looks pretty big proportionately. I did a quick measure on the emulator and while the folder in "Get Blank Form" is 40px wide, the eye from edge to edge is 46px. Even if this is the "natural size" of the visibility off icon, can you add a little padding so it scales down just a little?

**Comment by grzesiek2010** [comment]
Now it's a a little smaller. I think it's ok. Is that enough? I can change it to 0.8 if you want.

**Comment by lognaturel** [comment]
That looks good to me. What about the vertical centering of the GDrive icons?

**Comment by grzesiek2010** [comment]
I fixed the vertical centering as well.

**Comment by lognaturel** [comment]
I didn't even have time to attach a screenshot 😄

**Pull request merged**
