### PR TITLE
Adds material cards to widgets

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Pulls out layout elements from ODKView into XML
Adds cardview to question widget
~~Adds dimens.xml~~

### CODE REVIEW

**Comment by lognaturel** [comment]
I think the card change is a pretty big one so I'd tend to say it should be going to `ui-refresh`, what do you think?

**Comment by shobhitagarwal1612** [comment]
Yes, you are right. That should be done.
Also, I have sent a separate PR for adding dimensions.xml so that can be removed from this PR.

**Comment by shobhitagarwal1612** [comment]
@lognaturel I have removed all other changes except the material cards from this PR

**Comment by lognaturel** [comment]
Looks great. As you continue refining the look and feel, I think you'll want to make sure the padding is consistent, especially at the bottom of widgets, but that can come later.

**Pull request merged**
