### PR TITLE
Use start button to start ranking instead of double tap AND add numbers on the left

### PR DESCRIPTION
**Pull request by grzesiek2010**
#### What has been done to verify that this works as intended?
I just tested RankingWidget using a new button instead of double tap and numbers.

#### Why is this the best possible solution? Were any other approaches considered?
Changes requested after testing the beta version.

#### Are there any risks to merging this code? If so, what are they?
No.

#### Do we need any specific form for testing your changes? If so, please attach one.
Forms are attached to #2180 

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew pmd checkstyle lint findbugs` and confirmed all checks still pass.
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by lognaturel** [comment]
Thanks, this is looking really great to me. There have been a lot of requests for leading numbers so let's bring those back here and then we can build a new beta.

**Comment by grzesiek2010** [comment]
@lognaturel it's ready.

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
Beta release blocking on @yanokwa who said he wanted to think about the UI some more.

**Comment by yanokwa** [comment]
I've put my UI concerns at https://forum.opendatakit.org/t/odk-collect-v1-16-beta/13690/15

**Comment by kkrawczyk123** [comment]
What a great feature @grzesiek2010 !

**Tested with success!**
Verified on Androids: 4.1, 4.2, 4.4, 5.1, 6.0, 7.0 and 8.1.

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Comment by kkrawczyk123** [comment]
@opendatakit-bot label "behavior verified"

**Pull request merged**
