### PR TITLE
Add vertical appearance to range widget

### LINKED ISSUE #1136: Add vertical appearance to range widget
As describe at opendatakit/xforms-spec#111

### PR DESCRIPTION
**Pull request by grzesiek2010**
This PR is in reference to resolve #1136 

Forms for testing:
[range_decimal_vertical.txt](https://github.com/opendatakit/collect/files/1090720/range_decimal_vertical.txt)
[range_integer_vertical.txt](https://github.com/opendatakit/collect/files/1090721/range_integer_vertical.txt)

### CODE REVIEW

**Review by lognaturel — APPROVED** [review]
Looking good!

**Comment by mmarciniak90** [comment]
Tested with success.
Tested on Android: v4.1, v4.2, v4.4, v5.1, v6.0
- Verified new and saved job.
- Verifies vertical and horizontal device orientation, scroll is visible.
- Tested also with turned on 'Don't keep activities' option. 
screenshot_20170623-124222

**Comment by lognaturel** [comment]
Thank you @grzesiek2010 and @mmarciniak90!

**Comment by mmarciniak90** [comment]
@opendatakit-bot unlabel "needs testing"

**Pull request merged**
