### PR TITLE
Clean up temp files and DB before starting InstanceUploaderTaskTest

### PR DESCRIPTION
**Pull request by alxndrsn**
@lognaturel this may sort out your issue when re-running tests on a long-lasting emulator instance

### CODE REVIEW

**Comment by lognaturel** [comment]
👍 While you're in here, could you also please unsuppress the test? I forgot we were supposed to do that as part of #930 so it's not running on CI.

**Comment by alxndrsn** [comment]
De-suppression at https://github.com/opendatakit/collect/pull/965

**Comment by lognaturel** [comment]
This will fail if the temp directory doesn't exist before `setUp` is run, right? How about reseting the content provider on both `setUp` and `tearDown` and only cleaning up the temp file in `tearDown`? Or I suppose you could also check to see whether there are any files before attempting to delete them. I do think it's important to clean things up at the end.

Another thing that would be good to clean up is the Aggregate server URL.

**Comment by alxndrsn** [comment]
> Another thing that would be good to clean up is the Aggregate server URL.

Can't find this; where is it?

**Comment by alxndrsn** [comment]
> This will fail if the temp directory doesn't exist before `setUp` is run, right?

Yes, good spot!

> How about reseting the content provider on both `setUp` and `tearDown` and only cleaning up the temp file in `tearDown`?

The temp files are _likely_ to be deleted anyway, and their existence shouldn't affect the working of the test, so I guess doing it in the `tearDown` is ok.

> Or I suppose you could also check to see whether there are any files before attempting to delete them. I do think it's important to clean things up at the end.

Yeah, and possibly not required at the beginning, although that leaves the possibility of pollution from other tests.  I'll add the `ContentProvider` clean-up to `tearDown` as well, and move the temp file cleanup there.

**Pull request merged**
