### PR TITLE
Run tests in parallel on 50 separate devices

### LINKED ISSUE #3578: Look at parallelizing instrumentation tests
Right now our tests take 20m+ to run. This is causing timeout issues with CI and I don't think we want to have to keep bumping our timeout values every time the test suite grows. We do also need an audit of test coverage we can move from Espresso to Robolectric/JUnit but I think we expect this suite to stay at least this big in the long term. 

It'd be good to look into parallelizing our tests. I think the focus for this should be for CI (with Firebase Test Lab). Parallelizing locally is potentially a bad idea due to the hit on people's dev environments. Locally I think continuing to break tests into concentrated domain areas will help devs have smaller sets of tests to run while working on features/refactors.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #3578 

We decided to revert #3672 because it turned out that that `--num-uniform-shards` requires `gcloud alpha firebase test android run` so since we are just about to release a new version of the app it's important to have the build green and we can play with this improvement later.

#### What has been done to verify that this works as intended?
Nothing.

#### Why is this the best possible solution? Were any other approaches considered?
I use this option manually running test on Firebase Test Lab and it works much faster.
https://cloud.google.com/sdk/gcloud/reference/beta/firebase/test/android/run#--num-uniform-shards

> Specifies the number of shards into which you want to evenly distribute test cases. The shards are run in parallel on separate devices. For example, if your test execution contains 20 test cases and you specify four shards, each shard executes five test cases.
> The number of shards should be less than the total number of test cases. The number of shards specified must be >= 1 and <= 50.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It doesn't require testing.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by seadowg** [comment]
I gave this a go and found we're getting 3 failures: https://console.firebase.google.com/u/0/project/api-project-322300403941/testlab/histories/bh.f6f8331e5ae6e371/matrices/8628208877531572155.

I was initially only getting one failure in `FormDatabaseHelperTest`. It looked like it didn't have permissions or our reset rule so I added those to `SqliteHelperTest`. This annoyingly caused `InstancesDatabaseHelperTest` to fail. I think we should seperately added fixes for dodgy tests (as other PRs) until we can get this green. Hopefully only a couple of tweaks required!

**Comment by seadowg** [comment]
I keep getting this failure: https://console.firebase.google.com/u/0/project/api-project-322300403941/testlab/histories/bh.f6f8331e5ae6e371/matrices/4733938542694164299/executions/bs.1827bf05fa566136/testcases/2/test-cases. Can't work out a way to reproduce locally. @lognaturel / @grzesiek2010 any ideas around what could be happening?

**Review by seadowg — DISMISSED** [review]
Sticking this into "Request changes" until it's working

**Comment by grzesiek2010** [comment]
I tried today but have no idea why that one test is failing and how multiple shards might impact it... maybe we could comment it out temporarily and merge this pr to check how costs are going to change because if it's to expensive for us it also doesn't make sense to spend time on failing test?

**Comment by lognaturel** [comment]
That sounds reasonable to me. We can add an issue to bring back that coverage in some way if deemed necessary so we don't forget. @seadowg? And I think we could merge this one before the repeat add PR.

**Comment by shobhitagarwal1612** [comment]
I was wondering if it's possible to run tests incrementally. What if gradle only ran tests for the classes that were compiled? I'm certain gradle build is incremental but not the test task. Maybe we can create one? Has anyone seen that before?

**Comment by seadowg** [comment]
@grzesiek2010 good idea. That's probably a test we can move to Robolectric anyway. I'll try ignoring it and running a few times.

@shobhitagarwal1612 we're more focused on our full suite run here but being able to run subsets of tests locally is pretty amazing. Reorganizing tests into domain slices so it's clearer what to run and also breaking the code up into modules so the build time is faster for individual modules are things we're looking at.

**Comment by seadowg** [comment]
@grzesiek2010 I'm still seeing the occasional test flake but I think it'll be easier to fix those as we see them come up as part of our actual workflow. If we are really stumped it's an easy revert. Merging this feels like a good step forward so happy for you to go ahead when you the checks pass!

**Comment by grzesiek2010** [comment]
Ok so let's merge. I can't do that since it's my pr.

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
I knew there was a risk this would break the build but it did so in a very unexpected way: “ (gcloud.alpha.firebase.test.android.run) unrecognized arguments: --num-uniform-shards=50”

**Comment by seadowg** [comment]
I'm guessing from the error we probably need to update the GCloud tools we use in Circle CI. It looks like we use the `cloud-sdk` Docker image. I'll make a quick PR that updates that to the latest.

**Pull request merged**
