### PR TITLE
Fix TextView and EditText in RTL languages (higher than API 16), fix #1981

### LINKED ISSUE #1981: RTL writing system is not visible on all views
#### Software and hardware versions 
Collect v1.13.2
Devices with Android: 4.1, 4.2, 4.4, 6.0, 7.0, 8.0.

#### Problem description
RTL writing system is not visible on all views 

#### Steps to reproduce the problem
1. User uses Collect on RTL language
2. User opens Fill Blank Form / Get Blank Form / Delete Saved Form or starts filling some form
3. User sees that text is not start from the right of the page and continues to the left.

#### Expected behavior
* User sees text which starts from the right of the page and continues to the left on all views
* On one of my devices to tests - Huawei Y5 with Android 5.1 - RTL languages works as expected on most of all views.

#### Examples

| View | Android 6.0 - Moto G4 | Android 5.1 - Huawei Y5 | 
| ---- | ---- | ---- |
| Get Blank Form | screenshot_20180307-164007 | screenshot_2018-03-07-14-40-09 | 
| Fill Blank Form | screenshot_20180307-163619 | screenshot_2018-03-07-14-37-37 | 
| Simple widget | screenshot_20180307-163716 | screenshot_2018-03-07-14-37-30 | 
| Select one quick appearance | screenshot_20180307-164733 | screenshot_2018-03-07-14-46-32|

### PR DESCRIPTION
**Pull request by huangyz0918**
Closes #1981
links to PR #2048

### CODE REVIEW

**Comment by lognaturel** [comment]
Ahh, yes, I see the problem with including the fix in the base theme file, now, thank you. So you were right the first time, you do need a version-specific one. You should be able to only add the changes you need for that version and inherit the rest (I can't remember whether that's what you had done).

**Comment by huangyz0918** [comment]
I think we have to wait #2061 , to prevent a merge conflict.

**Comment by grzesiek2010** [comment]
@huangyz0918 
as you know I worked on #2128 I added only this one line in our theme file https://github.com/opendatakit/collect/pull/2128/files#diff-ae3e0475e2ce5e0ee992f82c7a81207dR7
and I noticed it fixes this issue too.

I didn't investigate it much but looking at the description and attached screenshots:

- Get Blank Form :heavy_check_mark: 
- Fill Blank Form :heavy_check_mark: 
- Simple widget :heavy_check_mark: 
- Select one quick appearance - here is a problem but it's because the layout for radio buttons is broken

so could you tell me why we need all those changes you implemented (two new files) why not just that one line? what am I missing?

**Comment by grzesiek2010** [comment]
@opendatakit-bot unlabel "needs testing"

**Comment by huangyz0918** [comment]
@grzesiek2010 It seems you got a better solution. I cannot reach my computer at this moment so can you take a look at `about page` ? If it looks the same with my screenshots I will close this PR or I will remove the modification in `theme.xml` and only left the modification in about items.

Thanks for all your efforts and suggestions! I’m so happy to see so many issues were addressed by our work. 🔥

**Comment by grzesiek2010** [comment]
you are right about the `about page` my changes from #2128 don't solve this view but you know why?
because I added the mentioned line https://github.com/opendatakit/collect/pull/2128/files#diff-ae3e0475e2ce5e0ee992f82c7a81207dR7 to `AppThemeBase` but for settings activities, we use `AppTheme.SettingsTheme` if we add the same line there it works well :smile: 

so looks like we need only those two lines here. If you want please update this pull request according to our insights. Thanks.

**Comment by huangyz0918** [comment]
@grzesiek2010 Thank you !
 I will update this PR along with #2094  according to your suggestions soon.
 It’s awesome to corporate with you !

**Comment by huangyz0918** [comment]
Please review @grzesiek2010 @lognaturel 
A new issue is that I have tested devices in API 17 but failed when the `targetApi` is `jelly_bean_mr1`, I changed the parameter to `tools:targetApi="17"` and it worked.
I think it’s ready for a test now.

**Review by grzesiek2010 — APPROVED** [review]

**Comment by grzesiek2010** [comment]
@opendatakit-bot label "needs testing"

**Comment by kkrawczyk123** [comment]
All views: Fill Blank Form, Edit Saved Form, Send Finalized Form, View Sent Form, Get Blank Form and Delete Saved Form are aligned to the right side when RTL language is chosen on Androids 4.4, 5.1, 6.0, 7.0 and 8.1 - so I think it's a success!

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Review by lognaturel — APPROVED** [review]

**Pull request merged**
