### PR TITLE
Remove theme setting

### PR DESCRIPTION
**Pull request by seadowg**
This removes the theme setting so that Collect will always use the system theme.

#### Why is this the best possible solution? Were any other approaches considered?

I've made this a pretty "soft" removal: all the code that deals with the setting is still present but disabled behind a feature flag, and I've not removed the `appTheme` key from preferences schema. This will mean that we can easily add the setting back in if we get given a good reason to.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Nothing other than the theme setting should be affected here! The app should now always use the system theme.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by seadowg** [comment]
@lognaturel I'm thinking we should put this out in the next major release (with a forum post soon) to test the waters. Interested to hear your thoughts though!

**Comment by lognaturel** [comment]
Yep, that works! Do you want to write a quick post in the Ideas category? I think it just needs to say
* We want to remove this because it causes weird crashes and bad state
* When we introduced it, it wasn't possible to change the theme at the device level
* Now 90% of users have the same theme as their device
* If you have a use case for changing the theme just for Collect, let us know

**Comment by seadowg** [comment]
> Do you want to write a quick post in the Ideas category?

Will do!

**Review by grzesiek2010 — APPROVED** [review]

**Comment by dbemke** [comment]
Should in Settings in description what's in the User interface be the theme? 
themeUserint

**Comment by seadowg** [comment]
> Should in Settings in description what's in the User interface be the theme?

Nope! Could you file an issue please?

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on Androids: 10,14

**Verified cases:**
- theme in settings
- changing theme in the device

**Comment by WKobus** [comment]
**Tested with Success!**

Verified on device with Android 15

**Pull request merged**
