### PR TITLE
Change in the way ranges look

### LINKED ISSUE #6288: Change in the way ranges look
#### ODK Collect version
the master version a9c57b94bd7d935e4a62cfd9052066eb15ec7328
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
The progress in geopoint widget and range widget changes (a dot at the end and the space at the end of filled part). 
range
lodation

#### Steps to reproduce the problem
1. Go to All question types form.
2. Check geopoint widget.
3. Check range widget

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #6288

#### Why is this the best possible solution? Were any other approaches considered?
Setting attributes on a theme level is better than doing the same in every place where sliders/progress indicators are used so that's what I did here.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It requires testing sliders and progress indicators across the app to make sure they look good. I don't think we need to test anything else.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by seadowg — APPROVED** [review]

**Comment by seadowg** [comment]
@grzesiek2010 leaving this unmerged so that @alyblenkin can have a look and so that we don't need to open any issues if there's a regression somewhere else due to the style changes.

**Comment by alyblenkin** [comment]
@grzesiek2010 - when I try to test the build it says "package appears to be invalid"

**Comment by grzesiek2010** [comment]
@alyblenkin I've rerun the build, please try now.

**Review by alyblenkin — APPROVED** [review]

**Comment by dbemke** [comment]
We finished testing. There's one difference comparing to the previous design. The dot is smaller than it used to be. To me it feels ok when a value is in the middle of the axis but less visible when it's the beginning or end. @alyblenkin Should I file an issue or it's ok?
selectsPoint

**Comment by alyblenkin** [comment]
> We finished testing. There's one difference comparing to the previous design. The dot is smaller than it used to be. To me it feels ok when a value is in the middle of the axis but less visible when it's the beginning or end. @alyblenkin Should I file an issue or it's ok? 

Good spot! I agree, the larger dot makes it much more visible and easier to use. We should file an issue. I think it would be great to bring it back if it isn't too much effort.

**Comment by dbemke** [comment]
@grzesiek2010 As this PR isn't merge should I label it "behaviour verified" and file the issue after merging or you'll fix it in the PR?

**Comment by grzesiek2010** [comment]
> Good spot! I agree, the larger dot makes it much more visible and easier to use. We should file an issue. I think it would be great to bring it back if it isn't too much effort.

@alyblenkin  we can do that but it's still the old look. What do you think about using the new material 3 one? It would be like:
Screenshot_1723113108

I think I like it. The old one was very thin barely visible probably in daylight on some devices.

**Comment by alyblenkin** [comment]
@grzesiek2010 yes, I think the M3 slider is more visible too. I [suggested it](https://github.com/getodk/collect/issues/6288#issuecomment-2256293942) when we were first looking at this issue but I think it might of got missed. Let's go forward with the new slider.

**Comment by grzesiek2010** [comment]
> Let's go forward with the new slider.

Cool. @dbemke please continue testing.

**Comment by dbemke** [comment]
@alyblenkin @grzesiek2010 Everything seems to work well. There's one case in which the new design adds a dot when there aren't any ticks on the axis. Is it ok?
rangeNoTicks

**Comment by grzesiek2010** [comment]
> There's one case in which the new design adds a dot when there aren't any ticks on the axis. Is it ok?

Ahh no let me try to fix this.

**Comment by grzesiek2010** [comment]
@dbemke the bug should be fixed, however, I had to add some more changes so please test the range with ticks again too,

**Comment by grzesiek2010** [comment]
BTW I completely forgot that the `no-ticks` appearance exists. It turns out this appearance is not documented so I filed an issue in https://github.com/getodk/docs/issues/1844 and also updated the demo `All question types` form. Good catch @dbemke

**Comment by dbemke** [comment]
Tested with success!

Verified on devices with Android 10, 14

Verified cases:
- issue #6288 doesn't occur
- range widgets with and without ticks
- geopoint widgets
- light and dark mode
- RTL

**Pull request merged**
