### PR TITLE
Uninstall and reinstall bypasses admin password

### LINKED ISSUE #556: Uninstall and reinstall bypasses admin password
If you set an admin password, and uninstall/reininstall the application, you get access to all the functions and that were previously disabled. We should explore either ..

1. Adding documentation to make this behavior clear. Admin password was never meant to be robust. It's more of a convenience feature.
2. Adding functionality to reset all data when you uninstall the application.
3. Adding functionality to persist the admin password on reset.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #556 

#### What has been done to verify that this works as intended?
I've tested:
Setting admin password
Disabling admin password
Saving/reading using QR code and settings file
Reinstalling the app

#### Why is this the best possible solution? Were any other approaches considered?
I can't see anything better. We can't use Device Administration API.
Everything we store on internal storage is removed automatically. Creating a file in odk folder isn't a good idea too as someone might remove that folder.

#### Are there any risks to merging this code? If so, what are they?
The file with password is hidden but still on external storage so if someone is really sneaky it might be possible to remove or edit this file.

### CODE REVIEW

**Comment by grzesiek2010** [comment]
I just wanted to add that saving/reading settings might be tricky here. 
So two scenarios:
1. Add the admin pass and generate QR code and settings file 
2. Read QR code/settings file on device without specified pass
3. The pass should be added

.

1. Remove the admin pass and generate QR code and settings file 
2. Read QR code/settings file on device with specified pass
3. The pass should be removed

I've tested both and it's ok I believe but it's the most tricky scenario I can imagine here.

**Comment by grzesiek2010** [comment]
and..... we can specify in QR settings whether we want to include the pass :)

**Comment by lognaturel** [comment]
Next step is for @yanokwa to verify this behavior since he's the one who is most familiar with what users need here.

**Comment by grzesiek2010** [comment]
@yanokwa I investigated [Android Keystore System](https://developer.android.com/training/articles/keystore.html) as you asked me. Unfortunately it looks useless for us. The first thing is it requires API 18 and we support 16 and 17 too. The second thing is I tested this sample app: https://github.com/obaro/SimpleKeystoreApp and keys are removed when you uninstall the app.

**Comment by yanokwa** [comment]
The hidden file option won't stay hidden for very long because someone will ask about it on the support forum and it'll eventually be known to the community at large. So while this is an OK solution, it feels like a half-measure and when it comes to security we go for half measures. 

I think we should close this PR. @lognaturel, if you agree, please close. If not, let's discuss.

**Comment by heyjamesknight** [comment]
@grzesiek2010 could this be something we could use? https://developer.android.com/reference/android/app/backup/BackupAgentHelper.html

**Comment by lognaturel** [comment]
Unfortunately I agree that this only provides a little more security through obscurity. It was a good idea to try, though!

@jknightco does that API make it possible to force reapplication of settings on reinstall? If so, that might indeed help. Let's close this and continue the discussion in #556.

**Pull request closed without merging**
