### PR TITLE
Track form edits

### LINKED ISSUE #5200: Capture analytics for form instance edits
Currently, form instances can always be edited whether they are finalized or not. This makes the meaning of finalization unclear and confusing. We are considering moving towards a model where finalized forms are immutable. It would be helpful to have a sense of how common edits are and what fraction of those edits happen on finalized forms.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5200 

#### What has been done to verify that this works as intended?
I've reviewed implemented changes and debugged the project.

#### Why is this the best possible solution? Were any other approaches considered?
Nothing to discuss here.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It doesn't require testing.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by seadowg — CHANGES_REQUESTED** [review]
If we fire these events after `FormEntryActivity#formControllerAvailable` (i.e. once the form has loaded), we could just call `logFormEvent` without needing to do any additional DB work as we'll have set the default param for `"form"`.

**Comment by grzesiek2010** [comment]
> If we fire these events after FormEntryActivity#formControllerAvailable (i.e. once the form has loaded), we could just call logFormEvent without needing to do any additional DB work as we'll have set the default param for "form".

If I did that in `FormEntryActivity` then yeah I could use form controller to get form id and title instead of reading it from DB but then I would need to read status of a form from database. So it won't help my to avoid using DB + I wanted to avoid adding that code to already big enough `FormEntryActivity`.

**Review by seadowg — APPROVED** [review]
>  I wanted to avoid adding that code to already big enough FormEntryActivity.

Yeah fair enough. Don't feel strongly enough about that to block this. @lognaturel good to get your approval on this as well.

**Review by lognaturel — APPROVED** [review]
Works for me. I'm hopeful we won't keep this in for long. Thanks!

**Pull request merged**
