### PR TITLE
Mark required questions using an asterisk

### LINKED ISSUE #1827: Mark required questions using asterisks
Currently, required questions are not highlighted. Users only see a toast when they try to swipe without answering. I think it would be good to mark such questions, for example, using asterisks. It would look like here:
screenshot_2018-02-02-16-00-42

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #1827 

#### What has been done to verify that this works as intended?
I tested All Widgets form where the last question is required.

#### Are there any risks to merging this code? If so, what are they?
No.

#### Do we need any specific form for testing your changes? If so, please attach one.
I used All widgets form.

### CODE REVIEW

**Comment by mdmahendri** [comment]
why not use different color for asterisk to get more attention from user

**Review by akshay-ap — COMMENTED** [review]
Seems fine to me.

**Comment by grzesiek2010** [comment]
> why not use different color for asterisk to get more attention from user

It could be red but I'm not sure what's better...Who thinks it should be red?

**Review by yanokwa — CHANGES_REQUESTED** [review]
This is a pretty cool feature! 

I think we should put the * at the beginning. Putting it at the end of long questions or small screens means it's hidden, which defeats the purpose of letting the user know before a swipe.

I think an Android red (probably the same as when you reset the app) would work better because it catches the user's attention.

I think questions that have no label text (e.g., media only questions) and are required should also have the *. Currently, they don't.

**Comment by grzesiek2010** [comment]
I implemented required changes. Here is a form fo testing:
[asterisk.xml.txt](https://github.com/opendatakit/collect/files/1698618/asterisk.xml.txt)

**Comment by grzesiek2010** [comment]
I implemented required changes. Here is a form for testing: 
[asterisk.xml.txt](https://github.com/opendatakit/collect/files/1698933/asterisk.xml.txt)

**Comment by yanokwa** [comment]
I like what you've done with the red! 

I think questions that have no label text (e.g., media only questions) and are required should also have the *. Currently, they don't and it'd be good to include that in your test file. Also good to include is a form with multiple questions so we can verify how that looks.

If I try to swipe to the `/asterisk/empty2`, I get an error.
```
FormEntryActivity: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
FormEntryActivity: 	at org.odk.collect.android.widgets.QuestionWidget.createQuestionMediaLayout(QuestionWidget.java:153)
FormEntryActivity: 	at org.odk.collect.android.widgets.QuestionWidget.<init>(QuestionWidget.java:121)
FormEntryActivity: 	at org.odk.collect.android.widgets.StringWidget.<init>(StringWidget.java:62)
FormEntryActivity: 	at org.odk.collect.android.widgets.StringWidget.<init>(StringWidget.java:56)
FormEntryActivity: 	at org.odk.collect.android.widgets.WidgetFactory.createWidgetFromPrompt(WidgetFactory.java:134)
FormEntryActivity: 	at org.odk.collect.android.views.ODKView.<init>(ODKView.java:197)
FormEntryActivity: 	at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1314)
FormEntryActivity: 	at org.odk.collect.android.activities.FormEntryActivity.showPreviousView(FormEntryActivity.java:1536)
FormEntryActivity: 	at org.odk.collect.android.activities.FormEntryActivity.onFling(FormEntryActivity.java:2882)
FormEntryActivity: 	at android.view.GestureDetector.onTouchEvent(GestureDetector.java:650)
FormEntryActivity: 	at org.odk.collect.android.activities.FormEntryActivity.dispatchTouchEvent(FormEntryActivity.java:1413)
FormEntryActivity: 	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
FormEntryActivity: 	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
FormEntryActivity: 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:373)
FormEntryActivity: 	at android.view.View.dispatchPointerEvent(View.java:10165)
FormEntryActivity: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4446)
FormEntryActivity: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4314)
FormEntryActivity: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3861)
FormEntryActivity: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3914)
FormEntryActivity: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3880)
FormEntryActivity: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4007)
FormEntryActivity: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3888)
FormEntryActivity: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4064)
FormEntryActivity: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3861)
FormEntryActivity: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3914)
FormEntryActivity: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3880)
FormEntryActivity: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3888)
FormEntryActivity: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3861)
FormEntryActivity: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6257)
FormEntryActivity: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6196)
FormEntryActivity: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6157)
FormEntryActivity: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6360)
FormEntryActivity: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
FormEntryActivity: 	at android.os.MessageQueue.nativePollOnce(Native Method)
FormEntryActivity: 	at android.os.MessageQueue.next(MessageQueue.java:323)
FormEntryActivity: 	at android.os.Looper.loop(Looper.java:136)
FormEntryActivity: 	at android.app.ActivityThread.main(ActivityThread.java:6123)
FormEntryActivity: 	at java.lang.reflect.Method.invoke(Native Method)
FormEntryActivity: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
FormEntryActivity: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
FormEntryActivity: Created view for group [top] null
```

**Comment by grzesiek2010** [comment]
> If I try to swipe to the /asterisk/empty2, I get an error.

silly bug, it's fixed. Sorry.

> I think questions that have no label text (e.g., media only questions) and are required should also have the *. Currently, they don't and it'd be good to include that in your test file.

It works in that way. If you have required question without a label you can see an asterisk before hint but if both are not specified (label + hint) there is only an asterisk. Please check those questions after that NPE.

**Review by yanokwa — APPROVED** [review]

**Comment by mmarciniak90** [comment]
**Tested with success!**

Verified on Android: 4.1, 4.2, 4.4, 5.1, 6.0, 7.0, 8.0
Verified cases:
* [All widgets required.xml.txt](https://github.com/opendatakit/collect/files/1720046/All.widgets.required.xml.txt)
* [requiredOnePage.xml.txt](https://github.com/opendatakit/collect/files/1720047/requiredOnePage.xml.txt)

|  | |

**Comment by mmarciniak90** [comment]
@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Review by lognaturel — APPROVED** [review]

**Pull request merged**
