### PR TITLE
Fixed 'Shared with Me/My Drive' button when user navigates to deeper directories in Get Blank form activity

### LINKED ISSUE #3071: Inappropriate 'Shared with Me/My Drive' button is visible if the user navigates to deeper directories
#### Software and hardware versions 
Collect v1.21.0

#### Problem description
Inappropriate 'Shared with Me/My Drive' button is visible if the user navigates to deeper directories

##### Case1:
1. GoogleDrive is set in server settings
2. User goes to `Get Blank Form`
3. User clicks on `Shared with Me` button
4. User goes to some folder
5. **User sees `Shared with Me` button instead of `My Drive` button**
6. User goes to some folder
7. **User sees `My Drive` button**

##### Case2:
1. GoogleDrive is set in server settings
2. User goes to `Get Blank Form`
3. User goes to some folder
4. **User sees `My Drive` button**
5. User goes to some folder
6. **User sees `Shared with Me`**

videogif

#### Expected behavior
If the user is somewhere in `Shared with Me` directory, the user should always have an option to move directly to `My Drive` directory

### PR DESCRIPTION
**Pull request by SaumiaSinghal**
Closes #3071

#### What has been done to verify that this works as intended?
I tested it on Android P.

Issue#3071

#### Why is this the best possible solution? Were any other approaches considered?
I used `currentPath` variable to check whether we are currently in Shared with me or in MyDrive.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
No

#### Do we need any specific form for testing your changes? If so, please attach one.
No specific form required

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by grzesiek2010 — CHANGES_REQUESTED** [review]
Seems as if you fixed the first described case but the second one still works like before.

**Comment by SaumiaSinghal** [comment]
Hie @grzesiek2010, I was a little confused. That means when the user is inside one of the deeper directories in 'My Drive', then he should always see 'Shared with Me' button?

**Comment by SaumiaSinghal** [comment]
Hie @grzesiek2010! I fixed the code for both cases. Can you please, review it again?

**Review by grzesiek2010 — APPROVED** [review]

**Comment by mmarciniak90** [comment]
**Tested with success**

Verified on Android: 4.4, 5.1, 6.0, 7.0, 8.1, 9.0, 10.0
I was not able to verify this PR on Android 4.2 because of a crash that is not related to this problem.

Verified cases:
- two cases from issue
- light/dark mode
- English/Spanish language
- changing device orientation

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Comment by grzesiek2010** [comment]
Thanks @SaumiaSinghal!

**Pull request merged**
