### PR TITLE
Added circle.yml and configured it to spit out apk into artifacts

### PR DESCRIPTION
**Pull request by max2me**

### CODE REVIEW

**Comment by lindsay-stevens** [comment]
Cheers! Hope to see it merged :+1:

**Review by lognaturel — COMMENTED** [review]
Looks great. Only question is whether lint needs to be stopped from aborting on error across the board? What required that?

**Comment by max2me** [comment]
@lognaturel Hélène, that's a good question. I did not remember rationale behind that choice so I removed that piece to test and builds are passing fine on CircleCI now. In the hindsight it does look a bit sketchy disabling it and next time I'll be adding comments explaining changes like that.

**Comment by lognaturel** [comment]
I think this is ready for merging. More can always be added later but this should make it so anyone can grab APKs for any build easily from https://circleci.com/gh/opendatakit/collect @lindsay-stevens or @yanokwa anything else you'd like to see added at this time?

**Comment by lognaturel** [comment]
This fails saying tasks `assembleMasterRelease`, `assembleMasterReleaseUnitTest` and `testMasterReleaseUnitTest` are not found. It did work when I tried the branch myself (https://circleci.com/gh/lognaturel/collect/2) so I suspect @max2me and I were using an updated version of Gradle for some reason.

When I tried using the corresponding older `gradlew` tasks, `assembleRelease` failed on linting. There was a duplicate admin menu item that was causing the failure so I went ahead and fixed that. I'll try to submit a PR soon.

**Pull request merged**
