### PR TITLE
Adds lint check for unused ids

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Removes unused ids

### CODE REVIEW

**Comment by shobhitagarwal1612** [comment]
@yanokwa @lognaturel Circle CI is not including the test files in the lint check. That's why the lint check is failing. 
https://369-80862566-gh.circle-artifacts.com/0/tmp/circle-junit.ml5fsjZ/lint/lint-results-debug.html#UnusedIds

This `id` is being used in one of the test classes

**Comment by lognaturel** [comment]
When I run `./gradlew lint` locally I see those errors as well so it's not related to CircleCI. `MainActivityTest` has a `layoutTest` method which verifies that the `RelativeLayout` is there. I don't really think that is a useful test so I'd be in favor of removing it and the identifiers in the 3 layout files.

**Comment by shobhitagarwal1612** [comment]
@lognaturel You have to explicitly include test files within the scope of the lint check

**Comment by lognaturel** [comment]
Ah, ok. But in this specific case, does the test really give us any info? It seems like verifying the toolbar title, menu item titles and buttons is plenty good enough. I don't think it's very good practice to ID things that are only used for tests, hence why they're not included in the lint check by default.

**Comment by shobhitagarwal1612** [comment]
> I don't really think that is a useful test so I'd be in favour of removing it and the identifiers in the 3 layout files.

@lognaturel I am in favour of this.

**Comment by lognaturel** [comment]
Awesome. I think you can just do it in this PR and then it will be ready to merge.

**Comment by shobhitagarwal1612** [comment]
@lognaturel Done

**Review by lognaturel — APPROVED** [review]

**Pull request merged**
