### PR TITLE
Connectivity check & toast only occurs with internet submissions.

### LINKED ISSUE #2478: Status of failed submission does not have information about Airplane mode on
#### Software and hardware versions 
Collect current master
Collect 1.16.2 works correct

#### Problem description
Status of failed submission does not have information about Airplane mode on

#### Steps to reproduce the problem
1. User sets `Send submission via SMS`
2. Airplane mode is turned on on device
3. User goes to `Send Finalized Form
4. User tries to send forms
5. The user sees toast with error

#### Expected behavior
Submission should have information `Airplane Mode being on`

### PR DESCRIPTION
**Pull request by jd-alexander**
Closes #2478
screencast-genymotion-2018-08-14_17 09 48 875

#### What has been done to verify that this works as intended?

- The transport was set to `SMS Submission` and when an instance was submitted while on airplane mode the network connectivity toast did not show. The list item updated with the `Failed due to airplane mode` message. 

- The transport mode was set to `Select on send`. When the `Send (Internet)` button was pressed the toast `no network available` toast was shown. When the `Send (SMS)` button was pressed the list item was updated with the failed messaging. 

- The transport mode was set to the default `Wifi/Cellular` and that gave the network connectivity toast when a submission was attempted.

- Once the airplane mode was disabled both transport types performed submissions normally.

#### Why is this the best possible solution? Were any other approaches considered?
Because the code changes basically optimized the conditions used to enable the network check. Once that's done the functionality is the same as before.

#### Are there any risks to merging this code? If so, what are they?
No. 

#### Do we need any specific form for testing your changes? If so, please attach one.
No. 

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew pmd checkstyle lintDebug spotbugsDebug` and confirmed all checks still pass.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by kkrawczyk123** [comment]
It is weird but Android 7 has a problem with the message that Airplane mode is being on but also there is no message "failed due to no reception" when it should appear. gif attached: 
samsungs7

The problem doesn't occur on Androids: 4.2, 4.4, 5.1, 6.0 and 8.1 
@opendatakit-bot unlabel "needs testing"

**Comment by lognaturel** [comment]
It seems Android 7 may have had some odd behavior related to permissions (in this case, reading if airplane mode is on). It reminds me of what @lakshyagupta21 discovered when working on Share -- he had to prompt the user to enable hotspot settings but didn't need to do that on any other Android version.

@jd-alexander maybe look into it just a bit but if you're not seeing any obvious way to get that info, we can go with this as-is.

**Comment by jd-alexander** [comment]
> @jd-alexander maybe look into it just a bit but if you're not seeing any obvious way to get that info, we can go with this as-is

okay! Will do!

**Comment by jd-alexander** [comment]
Just tested this behavior on a Huawei Nexus 6P running Android 7.0 and it displayed the airplane mode failure error. So it seems Android 7.0 is working well and there might be some inconsistencies with some Android forks or something.

**Comment by lognaturel** [comment]
On Android 7.0, I am also unable to get a message about airplane mode. Moto G4.

But I don't think this inconsistency is all that big of a deal. It's nice extra information to have but I think the user can figure it out. I'm going to merge this and if it really bothers someone, a new issue can be filed.

**Review by lognaturel — APPROVED** [review]

**Pull request merged**
