### PR TITLE
d != java.lang.String error when adding manual value to external integer widget

### LINKED ISSUE #1281: d != java.lang.String error when adding manual value to external integer widget
#### Software and hardware versions 
Collect v1.9.0 beta.0, Android v7.0, Motorola G4

#### Problem description
After manually inserting a value in the external integer widget, returning to it causes an error.

#### Steps to reproduce the problem
1. Open a form with an external integer widget such as the All Widgets form from the default server
1. Manually enter a value
1. Swipe to the next question
1. Swipe back to the external integer widget or jump to it
1. See "Error Occurred" dialog with "d != java.lang.String"

#### Expected behavior
No error.

#### Other information 
```
java.util.IllegalFormatConversionException: d != java.lang.String
	at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4135)
	at java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:2832)
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2786)
	at java.util.Formatter.format(Formatter.java:2491)
	at java.util.Formatter.format(Formatter.java:2426)
	at java.lang.String.format(String.java:2670)
	at org.odk.collect.android.widgets.ExIntegerWidget.<init>(
	at org.odk.collect.android.widgets.WidgetFactory.createWidgetFromPrompt(
	at org.odk.collect.android.views.ODKView.<init>(ODKView.java:199)
	at org.odk.collect.android.activities.FormEntryActivity.createView(
	at org.odk.collect.android.activities.FormEntryActivity.showPreviousView(
	at org.odk.collect.android.activities.FormEntryActivity.onFling(
	at android.view.GestureDetector.onTouchEvent(GestureDetector.java:650)
```

### PR DESCRIPTION
**Pull request by grzesiek2010**
This PR is in reference to resolve #1281

### CODE REVIEW

**Comment by lognaturel** [comment]
Even with really simple situations like this, I think it's really helpful to provide a narrative on what you considered and how you decided on the change you made!

Here's what I did to understand what is going on and how it should be fixed: I used `blame` to see the history of this particular number output to get some insights into how the bug was introduced. I saw that the original conversion from integer to string was done with `i.toString()`. This had to be changed when we introduced lint checks to verify that values were following the current locale. The version causing the problem was `String.format(Locale.getDefault(), "%d", i.toString())` which is almost right but was failing because the result of `i.toString()` is a string and can't be formatted as an integer. I think the way to resolve this is to use `String.format(Locale.getDefault(), "%d", i)` so that the value formatted is truly an integer.

This pull request changes the call to `String.valueOf(i.intValue())`. I believe that is essentially tricking the linter into accepting `i.toString()` (for now).

**Comment by lognaturel** [comment]
To be more explicit, @grzesiek2010, I think the way to go is `String.format(Locale.getDefault(), "%d", i)`. If you agree, make it so and if not, please explain why!

**Comment by grzesiek2010** [comment]
@lognaturel It was my first idea so I can agree with you, there is only one thing: in you example you use `Locale.getDefault()` in IntegerWidget we use `Locale.ENGLISH` and I decided to use `Locale.US` in both cases - you use `Loacale.US` in decimal widget as well. Is there and reason to use` Locale.getDefault() `or `Locale.ENGLISH` ? I just think about ` Locale.getDefault() `... 
if we use something else than ` Locale.getDefault() ` we should always use one (`Locale.US`) not sometimes English sometimes US I think.

**Comment by lognaturel** [comment]
In the case of integers, I don't believe it matters since grouping is off by default. I'm happy with using `Locale.US` explicitly for now in a consistent way and then reviewing with our translation partners whether localization should be used.

**Comment by smoyte** [comment]
I had a look through the code and this all looks good to me! If I'm not mistaken, @grzesiek2010 has made the changes requested by @lognaturel?

**Review by lognaturel — APPROVED** [review]

**Pull request merged**
