### PR TITLE
Remove form processing logic from settings

### LINKED ISSUE #434: Remove form processing logic option from settings
I'd like to move `Reset application` and `Form processing logic` to General Settings. I'd like to do this move because then the distinction between the two become very clear. General Settings are where all the settings are. Admin Settings are for when you want to show/hide things.

### PR DESCRIPTION
**Pull request by nmpatsal**
Hello ODK team!
I deleted everything that had to do with form processing logic so that we do not have dead code.Although, as I understand I have a merge problem but I do not understand it, could you please provide some tips?

### CODE REVIEW

**Comment by yanokwa** [comment]
Hi @nmpatsal! Can you please fix the merge conflicts?

**Comment by nmpatsal** [comment]
@yanokwa Yes I did it! Thank you a lot for your help! Are there any further issues to fix that you need? I am going to work on this project at least for 2 more months!

**Comment by lognaturel** [comment]
@nmpatsal Welcome to the project! Make sure to also join us on [Slack](http://slack.opendatakit.org) in #collect-code, that will be a good place to discuss issues you could work on.

Your merge wasn't quite right because it left behind some things like `+>>>>>>> d118f43170d3d8fa17e074727a20898b2444fc25`. That's just meant to indicate where the conflicting changes come from and must be removed.

But regardless, you'll see in the diff for the changes that there are some unrelated things in there. I think it's because you initially were working off an old version of master. In this case, it may be easier for you to start this change again by making sure you have a [remote set up for this repo](https://help.github.com/articles/configuring-a-remote-for-a-fork/), [syncing your master branch](https://help.github.com/articles/syncing-a-fork/) and then creating a fresh branch from there.

**Comment by nmpatsal** [comment]
I followed both links and synced my branch. In my last commit I think everything is fixed without merge conflicts, am I wrong?

**Comment by lognaturel** [comment]
There are some unrelated changes in here that I think are old versions of the code. Take a look at `AdminPreferencesActivity` for example. There should only be the changes that you made for this issue in the diff!

**Comment by nribeka** [comment]
If you want to resolve conflicts on your branch, the three way merge view in Android Studio is great.

This is how I usually resolve conflicts on my branch:
* Get the changes from upstream to your fork: [Updating Fork](https://help.github.com/articles/syncing-a-fork/).
* Get changes from master to my branch with conflicts.
* Use the three way to resolve conflicts: [Resolving Conflicts](https://www.jetbrains.com/help/idea/2016.3/resolving-conflicts.html).
* Commit and push your branch to update your pull request.

**Comment by nmpatsal** [comment]
Thank you!! 
I synced my fork and made the changes that you can see in Files changed section. Should I create a new pull request with only those commits?

**Comment by shobhitagarwal1612** [comment]
There is no need to create a new pull request. You can push the new commits to this branch since the merge conflicts are resolved now. 
Also, I noticed that the `AdminPreferenceActivity` class is reverted back to its older version. Please make sure that you merge it with the latest master branch from upstream.

**Comment by nmpatsal** [comment]
updatestatus

I am trying everything to update my version although, after all, I still have the old version of AdminPreferenceActivity.

**Comment by lognaturel** [comment]
@nmpatsal I think that somehow that code became a part of a changeset on your branch. One simple thing you could do is look at the diff here, take out extra code not related to the changes you wanted to make and commit that removal to your branch.

**Comment by shobhitagarwal1612** [comment]
Try this:
1. Checkout your master branch: `git checkout master`
2. Pull latest code of upstream branch: `git pull upstream master`
3. Since the changes are in your local/master branch, it should merge the branches and show any possible merge conflicts.
4. If any merge conflicts are found, then resolve them.
5. Push the changes to your remote branch: `git push origin master`

**Comment by nmpatsal** [comment]
Is it ok or it still has a problem?

**Comment by lognaturel** [comment]
Thank you, @nmpatsal for taking this on and @shobhitagarwal1612 @nribeka for helping him out with the merge! There are no more conflicts and this looks almost ready to go but it doesn't currently compile. I think you'll be able to quickly find and fix the problem.

**Comment by nmpatsal** [comment]
I created a new fork and solved this problem. Can someone close this pull request please?

**Comment by shobhitagarwal1612** [comment]
https://help.github.com/articles/closing-a-pull-request/

**Pull request closed without merging**
