### PR TITLE
Adds options menu in AdminPreferences for devices not having hardware menu button

### LINKED ISSUE #1138: Add "export settings" functionality back
In the recent changes to preferences, "Save Settings to Disk" was removed from the Admin Settings. That feature allowed users to export a serialized `collect.settings` file that could be pushed to multiple devices. 

For most people, QR code configuration will now be more convenient but some people may still prefer to use configuration files. In addition #1099 is adding the ability to load json preference files which will be easier to generate and verify than the serialized files.

Since we haven't discussed removing the serialized file creation with the broader community, I think we should bring that back. In addition, we could also add the ability to generate a json file.

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Fixes #1138

### CODE REVIEW

**Comment by lognaturel** [comment]
This addition makes a CircleCI test fail with 
```
java.lang.ClassCastException: org.robolectric.util.FragmentTestUtil$FragmentUtilActivity cannot be cast to android.support.v7.app.AppCompatActivity
	at org.odk.collect.android.preferences.AdminPreferencesFragment.onResume(AdminPreferencesFragment.java:57)
	at android.app.Fragment.performResume(Fragment.java:2096)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:928)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
	at android.app.BackStackRecord.run(BackStackRecord.java:834)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:447)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at org.robolectric.shadows.ShadowMessageQueue.dispatchMessage(ShadowMessageQueue.java:144)
	at org.robolectric.shadows.ShadowMessageQueue.access$100(ShadowMessageQueue.java:30)
	at org.robolectric.shadows.ShadowMessageQueue$1.run(ShadowMessageQueue.java:105)
	at org.robolectric.util.Scheduler.runOrQueueRunnable(Scheduler.java:293)
	at org.robolectric.util.Scheduler.postDelayed(Scheduler.java:143)
	at org.robolectric.shadows.ShadowMessageQueue.enqueueMessage(ShadowMessageQueue.java:126)
	at android.os.MessageQueue.enqueueMessage(MessageQueue.java)
	at android.os.Handler.enqueueMessage(Handler.java:631)
	at android.os.Handler.sendMessageAtTime(Handler.java:600)
	at android.os.Handler.sendMessageDelayed(Handler.java:570)
	at android.os.Handler.post(Handler.java:326)
	at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1358)
	at android.app.BackStackRecord.commitInternal(BackStackRecord.java:729)
	at android.app.BackStackRecord.commit(BackStackRecord.java:705)
	at org.robolectric.util.FragmentTestUtil.startFragment(FragmentTestUtil.java:15)
	at org.odk.collect.android.preferences.AdminPreferencesActivityTest.setUp(AdminPreferencesActivityTest.java:30)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:250)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:176)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:49)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:142)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy3.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:377)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I can't reproduce it locally.

**Comment by lognaturel** [comment]
I read through robolectric/robolectric#1859 and thought perhaps using `startVisibleFragment` would help but then that results in a `NullPointerException`.

**Comment by shobhitagarwal1612** [comment]
@lognaturel Did you use `containerViewId` as 1 too?

**Comment by lognaturel** [comment]
@shobhitagarwal1612 No, I hadn't. 

Are you able to reproduce this locally or do the tests work for you?

**Comment by shobhitagarwal1612** [comment]
I tried running the tests on CircleCI but with no success

**Comment by lognaturel** [comment]
And what about when you run `./gradlew connectedCheck` locally? As I think you looked into as well, seems like versions on CircleCI might not be right.

**Comment by shobhitagarwal1612** [comment]
> And what about when you run ./gradlew connectedCheck locally

@lognaturel : All tests passed

**Comment by lognaturel** [comment]
Hmmmmmmmmm. 🤔🤔 Something is fishy here. 🐟

Makes me think there's an incorrect version being used on CircleCI. I'd say don't spend much time on it, this could easily become a huge time sink! I'll see if I have any fresh ideas my tomorrow.

**Comment by lognaturel** [comment]
Nice fresh ideas!

**Comment by shobhitagarwal1612** [comment]
We can even post this answer to that thread to help others out

**Comment by lognaturel** [comment]
Yes, please do!

**Comment by shobhitagarwal1612** [comment]
This thread was already referenced to that post by you :+1:

**Pull request merged**
