### PR TITLE
New color picker

### LINKED ISSUE #1907: Small color picker
#### Software and hardware versions 
Collect v 1.12.2
Android 7.0
Samsung Galaxy S6 edge

#### Problem description

The color picker is very small on the screen and almost impossible to choose the color you want

#### Steps to reproduce the problem

1) Open an image type with draw appearance 
2) Click on plus FAB
3) Click on "Set color"
#### Expected behavior

The color picker should be bigger

#### Screenshots 
28460360_1548389028608050_1981746943_o
28343307_1548387458608207_659312532_o

#### Other information 

I would like to work on it. Also can you provide the right size for it?

### PR DESCRIPTION
**Pull request by ArmenApresyan8**
Closes #1907

#### What has been done to verify that this works as intended?

Tested on a physical device

#### Why is this the best possible solution? Were any other approaches considered?

There was a discussion and using this library was confirmed

#### Are there any risks to merging this code? If so, what are they?

No

#### Do we need any specific form for testing your changes? If so, please attach one.

[All widgets.xml.txt](https://github.com/opendatakit/collect/files/1815094/All.widgets.xml.txt)

### CODE REVIEW

**Comment by lognaturel** [comment]
On a small device the hue slider is truncated. Can you say a little bit about how you picked this specific library? It looks like there may be some out there that support landscape explicitly (e.g. https://github.com/martin-stone/hsv-alpha-color-picker-android).

**Comment by dcbriccetti** [comment]
OK, bot, you win.

**Comment by ArmenApresyan8** [comment]
OK I'll implement it.

**Comment by lognaturel** [comment]
I don't know if that's the best one, @ArmenApresyan8, I just did a really quick search! Did you look around a bit? I just want to make sure that there's a good reason to pick the one we end up going with. Thanks!

**Comment by ArmenApresyan8** [comment]
Actually, I think I didn't search enough. I'll look for good options and pick the best!

**Comment by lognaturel** [comment]
✨

**Comment by lognaturel** [comment]
I'm going to close this for now @ArmenApresyan8 but please comment on the issue if you find another lib you like!

**Comment by ArmenApresyan8** [comment]
@lognaturel so sorry for a late reply. I was busy with my exams. I'll look for it when I'm free.

**Pull request closed without merging**
