### PR TITLE
All files in Google Drive now showing when user clears search text. F…

### LINKED ISSUE #1909: All blank forms to download are not visible when user adds and then removes text in search bar for Google Drive
#### Software and hardware versions 
Collect v1.12.2

#### Problem description
All blank forms to download are not visible when user adds and then removes text in search bar for Google Drive

#### Steps to reproduce the problem
1. User uses Google Drive as a server
2. User goes to `Get Blank Form`
3. User adds text to search bar
4. User sees forms 
5. User removes text added to search bar
6. All available forms are not visible
searchbargoogle
#### Expected behavior
* All forms should be visible when user removes text in search bar

### PR DESCRIPTION
**Pull request by Diefenbaker**
…ix #1909

Closes #1909 

#### What has been done to verify that this works as intended?
Tested on emulator and physical device.

#### Why is this the best possible solution? Were any other approaches considered?
Uses existing listFiles() method. No other approach considered.

#### Are there any risks to merging this code? If so, what are they?
No.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

### CODE REVIEW

**Comment by grzesiek2010** [comment]
@opendatakit-bot label "needs testing"

**Comment by grzesiek2010** [comment]
@opendatakit-bot unlabel "needs review"

**Comment by mmarciniak90** [comment]
@opendatakit-bot label "needs discussion"

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
Thanks, @Diefenbaker! 

@mmarciniak90, I agree with you that using the same search for Google Drive as for other servers would be better. Can you please file that as a separate issue? This at least fixes the immediate problem.

**Comment by Diefenbaker** [comment]
My pleasure @lognaturel, thanks for allowing me to contribute! I think I must now hold the record for the easiest ever first contribution to an open source project on GitHub :)

**Comment by mmarciniak90** [comment]
**Tested with success!**

Verified on Android: 4.1, 4.2, 4.4, 5.1, 6.0, 7.0, 8.0
New issue created : #1944 

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Comment by mmarciniak90** [comment]
@opendatakit-bot unlabel "needs discussion"

**Pull request merged**
