### PR TITLE
RangeDecimalWidget

### LINKED ISSUE #1135: Add decimal support to range widget
#1108 added a range widget that supports integers. When the bind specifies a type of `xs:decimal`, a range should use decimal values for start, end and step and return a decimal.

### PR DESCRIPTION
**Pull request by grzesiek2010**
This PR is in reference to resolve #1135 
Forms:
[range_decimal.txt](https://github.com/opendatakit/collect/files/1072274/range_decimal.txt)
[range_integer.txt](https://github.com/opendatakit/collect/files/1072275/range_integer.txt)

### CODE REVIEW

**Comment by lognaturel** [comment]
Looks great to me! I believe that in `WidgetFactory` you don't need to add a default case because if it's not integer or decimal it will just fall through to the default case for the outer switch statement.

I'll let @mmarciniak90 do some extra testing before merging.

**Comment by grzesiek2010** [comment]
@lognaturel 

> I believe that in WidgetFactory you don't need to add a default case

I need as it's an inner switch statement. the similar situation is here:
https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java#L117

It doesn't look good so maybe we should initialize [questionWidget](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java#L51) by default as simple String widget and get rid of all defaults.

**Comment by mmarciniak90** [comment]
Tested with success.
I don't notice any problem.
Tested on Android 4.1, 4.2, 4.4, 5.1, 6.0
* Tested on new and saved form
* Tested with turned on and off option 'Do not keep activities'

**Comment by lognaturel** [comment]
Thank you @mmarciniak90!

@grzesiek2010 Ah, I forgot inner switches didn't fall through.

I think your refactor suggestion sounds really good for when you have a moment!

**Comment by grzesiek2010** [comment]
@lognaturel 

> I think your refactor suggestion sounds really good for when you have a moment!

done:
https://github.com/opendatakit/collect/pull/1187

**Comment by mmarciniak90** [comment]
Tested with success on Android 4.1, 4.2, 6.0
I did not notice regression.
Tested on new and saved form
Tested with turned on and off option 'Do not keep activities'

**Pull request merged**
