### PR TITLE
Escape html characters from markdown before conversion

### PR DESCRIPTION
**Pull request by thedavidmccann**
Proposed fix for https://github.com/opendatakit/collect/issues/1043

If we like this fix, I'll add some unit test coverage to this PR as well.

### CODE REVIEW

**Comment by lognaturel** [comment]
This unfortunately breaks HTML support and markdown [includes HTML support](https://daringfireball.net/projects/markdown/syntax#html). There really needs to be a special case for **unmatched** `<`.

For example, a form such as the one attached [here](https://groups.google.com/d/msg/opendatakit/W13PNfZhLDE/SdQBDuqbAgAJ) should work.

**Comment by thedavidmccann** [comment]
html wrapped in markdown converted to html o_O

Playing around with the sandbox here https://daringfireball.net/projects/markdown/dingus, it looks like a literal less than symbol, followed by any alphabetic character, will always be unescaped (regardless of whether it's unmatched or matched, regardless of whether it's a valid html tag keyword or not).  When followed by any other non-alpha character the less than is always escaped, again regardless of matched/unmatched.

So I think there are two options, one is to just do a regex search for the above simpler case (< followed by [^a-zA-z] gets replaced with &lt;), or haul in a dependency that implements a particular markdown standard: https://github.com/atlassian/commonmark-java.  Going with the easier one for now to see if we like how that looks and works.

**Comment by lognaturel** [comment]
Can you please make sure to verify that the form I linked to above works as intended? Thanks!

**Comment by thedavidmccann** [comment]
Good point, thank you @lognaturel!  I've added one more commit to not escape closing tags in text and updated the test case to cover this as well.  Also verified the attached form looks good now.

**Comment by lognaturel** [comment]
Special thanks for including tests! 🎉

**Pull request merged**
