### PR TITLE
Fixed RadioButtons and CheckBoxes in Dark Theme.

### LINKED ISSUE #1844: Thre is a space between the status bar and the toolbar in `General Settings`
#### Software and hardware versions 
Collect v1.12.2 an older versions
Samsung Galaxy S4, Android 5.0.1

#### Problem description
Thre is a space between the status bar and the toolbar in `General Settings`.

#### Steps to reproduce the problem
screenshot_2018-02-08-12-22-36

### LINKED ISSUE #2230: Radio buttons aren't visible in dark mode with Android 4.4.2
#### Software and hardware versions 
Collect v1.15.beta.0 Huawei Y336 with Android version 4.4.2.

#### Problem description
Radio buttons are black on a dark gray background.

#### Steps to reproduce the problem
Go to a question with radio buttons.

#### Expected behavior
Radio buttons are white.

#### Other information 
Reported at https://forum.opendatakit.org/t/odk-collect-v1-15-beta/13086/27

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #2230 

The problem was not only with RadioButtons in forms as described in the issue. The problem was also with checkBoxes used in widgets and radioButtons/checkboxes used in `General Settings`. I fixed all cases.

Thanks to the refactoring this pr also closes #1844 

#### What has been done to verify that this works as intended?
I've tested widgets that use radioButtons or checkboxes and `General Settings`

#### Why is this the best possible solution? Were any other approaches considered?
When it comes to General Settings I refactored them and now we use the same approach in both Admin and General Settings. After my refactoring the color of checkBoxes is appropriate.

#### Are there any risks to merging this code? If so, what are they?
Yes, I refactored `General Settings` so we should carefully confirm that everything works like before.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew pmd checkstyle lint findbugs` and confirmed all checks still pass.
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by xsteelej** [comment]
Code looks good to me @grzesiek2010

**Comment by grzesiek2010** [comment]
@xsteelej thanks for reviewing. BTW I noticed it's not the first pull request you have reviewed what is really cool and we appreciate so I have a small tip for you: there is a better way to say that you accept changes it's:
`Files changes` tab -> `Review changes` -> `Approve` -> `Submit review`

**Review by xsteelej — APPROVED** [review]
Approved!

**Review by lognaturel — APPROVED** [review]

**Comment by mmarciniak90** [comment]
@grzesiek2010 I was able to reproduce the problem on Android 4.4, 4.2, 4.2. 
This fix causes that RadioButtons and CheckBoxes are blue.

* I see big spaces between options on `General Settings` view
* Server option is located lower on light theme than in dark theme on Android 4.1, 4.2, 4.4.
* Blue icons are moved to left on Android 6.0
* App crashes when I try to open 'General Settings` on Android 7.0, 8.1

|Android 4.1 without fix|screenshot_2018-05-28-10-26-07|screenshot_2018-05-28-10-26-34|screenshot_2018-05-28-10-26-47 |
|---|---|---|---|
|**Android 4.1 with fix**|screenshot_2018-05-28-10-34-25|screenshot_2018-05-28-10-36-47|screenshot_2018-05-28-10-31-51|
|**Android 4.4 without fix**|screenshot_2018-05-28-11-37-43|screenshot_2018-05-28-11-37-47|screenshot_2018-05-28-11-37-55|
|**Android 4.4 with fix**|screenshot_2018-05-28-11-40-34|screenshot_2018-05-28-11-40-18|screenshot_2018-05-28-11-39-54|
|**Android 6.0 without fix**|screenshot_20180528-120340| screenshot_20180528-114400|screenshot_20180528-114352|
|**Android 6.0 with fix**|screenshot_20180528-120249|screenshot_20180528-114500|screenshot_20180528-114521|

**Comment by grzesiek2010** [comment]
> Server option is located lower on light theme than in dark theme on Android 4.1, 4.2, 4.4.

the same problem is visible on master branch and it's an Android bug between dark/light themes

> I see big spaces between options on General Settings view

It's just a default behavior.

> Blue icons are moved to left on Android 6.0

It's also a default behaviour I think they decided to move icons more to left and it looks the same on Android 6, 7.

> App crashes when I try to open 'General Settings` on Android 7.0, 8.1

Fixed.

**Comment by mmarciniak90** [comment]
**Tested with success!**

Verified on Android 4.1, 4.2, 4.4, 5.1, 6.0, 7.0, 8.1

@opendatakit-bot label "behavior verified"
@opendatakit-bot unlabel "needs testing"

**Pull request merged**
