### PR TITLE
Fixed: Caused by java.lang.IllegalArgumentException: Host name may not be null

### PR DESCRIPTION
**Pull request by grzesiek2010**

### CODE REVIEW

**Comment by lognaturel** [comment]
It would be really helpful to get an issue for this one with a link to the crash if you saw it in logs. Were you able to actually reproduce it? I thought all of the submission URLs were validated so I'm surprised that this issue can happen. I'm also particularly wondering how it's possible to get a null host in the first case where the uri was previously kept in the `uriRemap`.

**Comment by grzesiek2010** [comment]
Here is more info https://console.firebase.google.com/project/api-project-322300403941/monitoring/app/android:org.odk.collect.android/cluster/bc6b899b?reportTypes=FATAL_JAVA&duration=2592000000&appVersions=2356

I wasn't able to reproduce this issue but similar null check exists here: https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/utilities/WebUtils.java#L324

so I decided to add it. 

> I thought all of the submission URLs were validated so I'm surprised that this issue can happen

I don't know what may be wrong but I'm sure url is not null because then it would be crash here https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/tasks/InstanceServerUploader.java#L132 so urlString is not null but u.getHosts() may be null https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/tasks/InstanceServerUploader.java#L155

> I'm also particularly wondering how it's possible to get a null host in the first case where the uri was previously kept in the uriRemap.

the problem takes place [here](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/tasks/InstanceServerUploader.java#L155)  not [here](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/tasks/InstanceServerUploader.java#L147)

**Comment by lognaturel** [comment]
Thanks for that extra context! I'm convinced it's needed in that `else` branch ([here](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/tasks/InstanceServerUploader.java#L155)) but pretty sure it's not in the `if` because by the time things get there, the host has already been validated. How about taking it out in the `if` and continuing to monitor for crashes?

**Comment by grzesiek2010** [comment]
> How about taking it out in the if and continuing to monitor for crashes?

Yes I think you are right it should be needed only in `else` branch. Fixed.

**Pull request merged**
