### PR TITLE
Add an option to set an image size in settings

### LINKED ISSUE #1217: Add an option to set an image size in settings
Here https://github.com/opendatakit/collect/pull/1210 we have started a discussion about adding an option to settings in order to setting image size for all widgets. 

My proposal is to add a dialog with three options:
* Normal - by default
* Small - for example if I use my camera I get 1920x1080 pictures originally it's 2073600 pixels so I think small might be normal/2 - 2073600 / 2  = 1036800 it's 1357x764
* Extra small - small / 2

@lognaturel @yanokwa what do you think?

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #1217 

#### What has been done to verify that this works as intended?
1. I've tested the attached form (all possible options).
2. I've tested saving/reading settings using QR code and settings file.
3. I've tested hiding this option in admin settings.

#### Why is this the best possible solution? Were any other approaches considered?
This approach seems to be the only one right. It's clear and uses the code added before for #1210 

#### Are there any risks to merging this code? If so, what are they?
I can't imagine any other scenario apart from those I mentioned above. If @mmarciniak90 tests the same too and confirm it works as expected it should be safe.

#### Do we need any specific form for testing your changes? If so, please attach one.
Yes. We can use this form:
[AllWidgets.txt](https://github.com/opendatakit/collect/files/1362416/AllWidgets.txt)

where `orx:max-pixels` is specified only for one question with image widget.

### CODE REVIEW

**Comment by mmarciniak90** [comment]
Tested with success.
I verified this issue on Android 4.1, 4.2, 4.4, 5.1, 6.0, 7.0

screenshot_20171011-151517

I prepared the table displaying results on few devices.

Device | Camera | Original size from camera | Very small (640px) | Small (1024px) | Medium (2048px) | Large (4096px)  
:----- | :-----: | :-----: | :-----: | :-----: | :-----: | :-----: 
**Samsung Galaxy S7** | 12 MP | 4032x3024 4.49MB | 640x480 229.42KB | 1024x768 552.17KB | 2048x1536 1.87MB | 4032x3024 4.62MB
**Sony Z3** | 20.7 MP | 3264x2448 2.40MB | 640x480 244KB | 1024x768 554KB | 2048x1536 1.9MB | 3264x2448 2.36MB
**Samsung J1** | 5 MP | 2592x1944 1.5MB | 640x480 217KB | 1024x768 550KB | 2048x1536 1.9MB | 2592x1944 1.6MB
**Samsung Young** | 3.15 MP | 2048x1536 782KB | 640x480 219KB | 1024x768 497KB | 2048x1536 792KB | 2048x1536 776KB

**Comment by mmarciniak90** [comment]
@opendatakit-bot unlabel "needs testing"

**Comment by lognaturel** [comment]
Thanks, @mmarciniak90! Seeing the table makes me wonder whether 4096px for "large" is actually useful. Maybe we should make it 3072? @grzesiek2010 @kusaasira @acawood777 any thoughts on that?

**Comment by grzesiek2010** [comment]
@lognaturel yes I agree. Looking at the table it doesn't make sense to keep 4096px for "large". I'll change it.

**Comment by grzesiek2010** [comment]
@lognaturel it's fixed.

**Comment by grzesiek2010** [comment]
@lognaturel I've just fixed conflict it's ready to merge I think.

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
🎉🎉🎉

I made a tiny change to help translators out. Figured it wasn't worth doing one more round of edits so I pushed it directly.

**Pull request merged**
