### PR TITLE
Fixed memory leaks in settings

### LINKED ISSUE #3417: Memory leak : LinearLayout when user opens some page under 'User Access Control' on Android >8.0
#### Software and hardware versions 
Collect master
Android 8.1, 9.0

#### Steps to reproduce the problem
1. User opens Admin settings
2. User goes to `Main Menu Settings` or 'User Settings' or `Form Entry Settings`
3. `LinearLayout` leaked

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #3417 

#### What has been done to verify that this works as intended?
I was able to reproduce the leaks and confirmed they are no more visible after implementing my changes.

#### Why is this the best possible solution? Were any other approaches considered?
The way we created and managed the toolbar in settings was wrong and I refactored the code:
- moving setting the title to resources instead of doing it in fragments
- removing redundant code
- covering `toolbar` and `root` to [local variables](https://github.com/opendatakit/collect/commit/a2a92d3050dd91202ea1ebc9cb513e587dbb3ddf) what eventually fixed the issue.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It should be confirmed that there are no more leaks like those mentioned in the issue, additionally I refactored the way the toolbar (in settings) is created (especially its title) so please confirm there is no regression.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by lognaturel** [comment]
Looks right to me but @seadowg is more likely to know if there's anything else that should be considered.

**Comment by seadowg** [comment]
I can't see any problems with the changes. 

One thing that stood out to me is the code that sets the toolbar seems overly complicated. Are we not able to simply do `((AppCompatActivity) getActivity()).setSupportActionBar(toolbar)` from the `Fragment`? Maybe that's something we can mark as a problem.

Also, just out of interest, did you work out what the cause of the memory leak was? I couldn't see where `toolbar`/`root` were being leaked.

**Review by seadowg — APPROVED** [review]

**Comment by grzesiek2010** [comment]
> One thing that stood out to me is the code that sets the toolbar seems overly complicated

I simplified it.

> Also, just out of interest, did you work out what the cause of the memory leak was?

I'm not 100% sure so I'm not going to explain it but it was related to [root](https://github.com/opendatakit/collect/pull/3434/files#diff-37ab08a05a62c126f15766bfb4e750efL21) field. Probably it was caused by the fact that we were adding views multiple times not removing them https://github.com/opendatakit/collect/pull/3434/files#diff-37ab08a05a62c126f15766bfb4e750efL61

**Comment by grzesiek2010** [comment]
Please add needs testing label if everything is fine.

**Comment by mmarciniak90** [comment]
**Tested with success**

Tested on Androids: 8.1, 9.0
Verified also on Androids: 7.0, 6.0, 5.1, 4.4, 4.2

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Pull request merged**
