### PR TITLE
User is able to change validation option although Admin blocks all options of moving backwards

### LINKED ISSUE #1704: User is able to change validation option although Admin blocks all options of moving backwards
#### Software and hardware versions 
Collect master

#### Problem description
User is able to change validation option although Admin blocks all options of moving backwards

#### Steps to reproduce the problem
1. Admin blocks moving backwards
2. Admin select 'Yes' on dialog
3. User goes to `General Settings` -> `Form management `-> `Constraint processing`
4. User is able to change validation option to 'Defer validation until finalized'

#### Expected behavior
`Constraint processing` should not be editable for user if Admin selects Yes to prevent bypassing

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #1704 

#### What has been done to verify that this works as intended?
I tested this scenario:
1. Admin blocks moving backwards
2. Admin select 'Yes' on dialog
3. User goes to General Settings -> Form management-> Constraint processing
4. User is able to change validation option to 'Defer validation until finalized'

#### Why is this the best possible solution? Were any other approaches considered?
It's just a fix.

#### Are there any risks to merging this code? If so, what are they?
No, I just block an appropriate option thanks to this fix.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

### CODE REVIEW

**Comment by grzesiek2010** [comment]
@opendatakit-bot label "needs testing"

**Comment by mmarciniak90** [comment]
**Bug has been found!**

**Steps to reproduce:**
1. User goes to Settings -> Form management-> Constraint processing and changed this option to 'Defer validation until finalized'
2. Admin blocks moving backwards
3. Admin select 'Yes' on dialog

**Current behavior:**
Constraint processing option is not editable but 'Defer validation until finalized' is still selected

**Expected behavior:**
* Constraint processing option is set as 'Validate upon forward swipe'
* Constraint processing option is not editable

**Comment by mmarciniak90** [comment]
@opendatakit-bot unlabel "needs testing"

**Comment by grzesiek2010** [comment]
@mmarciniak90 It's fixed.

It was a stupid bug... I used  `KEY_CONSTRAINT_BEHAVIOR` here https://github.com/opendatakit/collect/pull/1705/files#diff-eb1ef5b405a42b83c0cf8b2abe0cf4d6R272 instead of `PreferenceKeys.KEY_CONSTRAINT_BEHAVIOR` in a result it was a key from admin keys not general.

**Comment by lognaturel** [comment]
Verified that the issue @mmarciniak90 identified is fixed.

**Review by lognaturel — APPROVED** [review]

**Pull request merged**
