### PR TITLE
Show form version and form id when deleting blank forms #2173

### LINKED ISSUE #2173: Show form version and form id when deleting blank forms
#### Software and hardware versions 
Collect v1.x.x, Android vx.x.x, device used...

#### Problem description
Under Delete Saved Form > Blank Forms, the form list should also show the form version and form ID, similar to what Fill Blank Form and Get Blank Form does. To be precise, I expect the UI to look like...

>**Form title**
Version: 123456 ID: form-title

#### Steps to reproduce the problem
Download a form with a version (e.g., All Widgets from opendatakit.appspot.com)

#### Other information 

**delete blank forms**
screen shot 2018-05-07 at 14 14 04

**fill blank form**
screen shot 2018-05-07 at 14 15 29

**get blank form**
screen shot 2018-05-07 at 14 17 19

### PR DESCRIPTION
**Pull request by SaumiaSinghal**
Closes #2173 

#### What has been done to verify that this works as intended?
I tested it.

#### Why is this the best possible solution? Were any other approaches considered?
I used VersionHidingCursorAdapter instead of using SimpleCursorAdapter and incorporated a small piece of code for showing ID number of forms. As VersionHidinCursorAdapter is working fine for Fill Blank Form page, it must work out fine here too.

#### Are there any risks to merging this code? If so, what are they?
No

#### Do we need any specific form for testing your changes? If so, please attach one.
The forms which have both version and id like the All Widgets form, CascadingSelect Form, Cascading Triple Select Form

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew pmd checkstyle lint findbugs` and confirmed all checks still pass.
- [x] verified that any new UI elements use theme colors. [UI Components Style **guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)******

### CODE REVIEW

**Comment by lognaturel** [comment]
Whoops, sorry about those conflicts, @SaumiaSinghal! Hopefully they're not too bad to fix but do join [the Slack](http://slack.opendatakit.org/) and ask in the #collect-code channel if you're getting stuck on any of it (or just want to chat!). Thanks for taking this issue on! 😊

**Comment by SaumiaSinghal** [comment]
No problem @lognaturel, I'll just rebase my branch against the master branch and come to this issue again..:)

**Comment by lognaturel** [comment]
Hmm, it looks like a bunch of recent changes are showing in the diff. 🤔 @SaumiaSinghal can you please try doing a rebase on master once again and let us know what happens in the Slack #collect-code channel?

**Comment by lognaturel** [comment]
Replaced by #2248.

**Pull request closed without merging**
