### PR TITLE
Improved Map Performance for OSM basemaps

### PR DESCRIPTION
**Pull request by Archaejohn**
This increases the displayed size of the tiles on the screen and therefore reduces the numbers of tiles being requested at any given time to speed up the entire map display as well as increase the size of objects on the screen while maintaining the appropriate zoom level for the tile provider.

#### What has been done to verify that this works as intended?
Tested in Android Emulator with all available OSM basemaps.

#### Why is this the best possible solution? Were any other approaches considered?
This is a built in approach from the MapView for OSMDroid

#### Are there any risks to merging this code? If so, what are they?
Doubtful

#### Do we need any specific form for testing your changes? If so, please attach one.

### CODE REVIEW

**Comment by lognaturel** [comment]
👍 This is in code that @jknightco is reworking as part of https://forum.opendatakit.org/t/collect-geotrace-and-geoshape-improvements/10160 and https://github.com/opendatakit/collect/issues/507 My guess is that it's small enough it's ok to merge now but I'll wait to get his feedback.

**Comment by Archaejohn** [comment]
Great!  I was trying to figure out why the tiles looked so small, sorry I didn't look at the open issues before I submitted the pull request.

**Review by heyjamesknight — APPROVED** [review]
Looks good to me. Will make sure this makes it into the refactor as well.

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
Thank you @Archaejohn, @jknightco!

**Pull request merged**
