### PR TITLE
Renamed the 'Save Form' setting

### LINKED ISSUE #5580: Rename Access control > Form Entry Settings > Save Form
The existing "Save Form" setting is in a section called "Uncheck to hide from Form Entry". Unchecking it hides the save button from the top bar and the "Save as draft" button from the form exit modal.

It's really not clear what to expect this setting to do, especially now that the setting after it is called "Save as draft".

I propose the following changes:

1) Rename "Save Form" to "Save as draft" and add subtext "Save icon in top bar and "Save as draft" button when exiting form"
2) Add a section header below it called "Uncheck to hide from Form End". That will contain "Save as draft" and "Finalize"

This reinforces the new language and matches the new code structure where form end and form entry are more separate.

~~A further change we could consider is separating the two concepts that are currently linked: we could have "Save icon" and "Save as draft" with subtext "In dialog when exiting form". We could migrate the existing "Save Form" setting to uncheck both settings if it's unchecked.~~

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5580

#### What has been done to verify that this works as intended?
I've tested the changes manually and updated automated tests.

#### Why is this the best possible solution? Were any other approaches considered?
There is nothing to discuss here.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Please verify that strings are updated according to what is described in the issue. It's rather a safe change and I don't see any area of risk to explore more carefully.
Please keep in mind that I've implemented:
> 1) Rename "Save Form" to "Save as draft" and add subtext "Save icon in top bar and "Save as draft" button when exiting form"
> 2) Add a section header below it called "Uncheck to hide from Form End". That will contain "Save as draft" and "Finalize"

but not:

> A further change we could consider is separating the two concepts that are currently linked: we could have "Save icon" and "Save as draft" with subtext "In dialog when exiting form". We could migrate the existing "Save Form" setting to uncheck both settings if it's unchecked.

The second part is something we are not sure about yet and will consider in the future. 
#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by seadowg — APPROVED** [review]

**Comment by dbemke** [comment]
Dialogs after enabling and disabling moving backwards in Form Entry Settings contain names of settings from the previous version (Save Form).
movback

**Comment by grzesiek2010** [comment]
@dbemke the language should be updated now.

**Comment by srujner** [comment]
**Tested with Success!**

Verified on device with Android 13

**Verified cases:**

- Works toward changes in issue #5580;
- Regression check on Saving forms;
- Form Entry Setting; 
- Moving backwards;
- Text has been changed in all areas; 
- Rotate the screen, minimize the app;

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on device with Android 10

**Pull request merged**
