### PR TITLE
Checks on types of settings

### LINKED ISSUE #2086: Import/Export settings can crash app with certain invalid QR codes
#### Software and hardware versions 
[Collect v1.14.0-beta.1](https://github.com/opendatakit/collect/releases/tag/v1.14.0-beta.1), Android v6.0.1, [Samsung A5](http://www.samsung.com/ph/smartphones/galaxy-a5-2016-a510/SM-A510YZKDXTC/)

#### Import/Export settings is broken
First thing I noticed is that the QR code wasn't previewed.
screenshot_20180331-031538

Then for few minutes it then shows a popup message saying "**ODK Collect has stopped.**"

#### Steps to reproduce the problem

1. Fresh install [**Collect v1.14.0-beta.1**](https://github.com/opendatakit/collect/releases/tag/v1.14.0-beta.1)
2. Go to **Admin settings** › **Import/Export settings**
3. Wait for it... (later, ODK Collect will break itself)

### PR DESCRIPTION
**Pull request by brunoguic**
Closes #2086 

_The problem:_ Trying to import settings with an incorrect expected value type. On the follow example, the expected type of field password in SharedPreference is **String**, and not **Boolean**. 
{
  "general": {
    **"password": false,**
    "username": "ra.callejo"
  },
  "admin": {
      ....
  }
}

_The solution:_  create a dictionary with general-settings and their expected type. Before saving the settings in the SharedPreference its checks if the properties are in that dictionary and if it is in expected format.

#### What has been done to verify that this works as intended?

- Exploratory tests with others settings configurations;
- Developed two unit test to validade the checker method;
 
#### Why is this the best possible solution? Were any other approaches considered?
Ensures that values inserted are respecting their defaults types values.

#### Are there any risks to merging this code? If so, what are they?
No.

#### Do we need any specific form for testing your changes? If so, please attach one.
As shown on the issue, that is the malformat QRCode:
image

### CODE REVIEW

**Comment by lognaturel** [comment]
Thanks for doing this @brunoguic and so good to see some tests! I'm a little concerned about having to keep another hash map in sync. How about using `.getClass` on the default from `GENERAL_KEYS`?

**Comment by brunoguic** [comment]
Hi @lognaturel , your suggestion made me reflect more about the problem..

The big picture here is that SharedPreferences, as it is a XML, it's not typed by default. So when it **saves** the properties it's not check the expected typed used in the app, check it out the code `preferences.GeneralSharedPrefences.java`, it uses the type of the desire inserted `value`

``` java
public GeneralSharedPreferences save(String key, Object value) {
        editor = sharedPreferences.edit();
        if (value == null || value instanceof String) {
            editor.putString(key, (String) value);
        } else if (value instanceof Boolean) {
            editor.putBoolean(key, (Boolean) value);
        } else if (value instanceof Long) {
            editor.putLong(key, (Long) value);
        } else if (value instanceof Integer) {
            editor.putInt(key, (Integer) value);
        } else if (value instanceof Float) {
            editor.putFloat(key, (Float) value);
        } else if (value instanceof Set) {
            editor.putStringSet(key, (Set<String>) value);
        } else {
            throw new RuntimeException("Unhandled preference value type: " + value);
        }
        editor.apply();
        return this;
    }
```

When we want to **restore** data from SharedPreference, we use the type of the default data used in `GENERAL_KEYS` . If its does not exists, uses by default as String. 
``` java
public Object get(String key) {
        Object defaultValue = null;
        Object value = null;

        try {
            defaultValue = GENERAL_KEYS.get(key);
        } catch (Exception e) {
            Timber.e("Default for %s not found", key);
        }

        if (defaultValue == null || defaultValue instanceof String) {
            value = sharedPreferences.getString(key, (String) defaultValue);
        } else if (defaultValue instanceof Boolean) {
            value = sharedPreferences.getBoolean(key, (Boolean) defaultValue);
        } else if (defaultValue instanceof Long) {
            value = sharedPreferences.getLong(key, (Long) defaultValue);
        } else if (defaultValue instanceof Integer) {
            value = sharedPreferences.getInt(key, (Integer) defaultValue);
        } else if (defaultValue instanceof Float) {
            value = sharedPreferences.getFloat(key, (Float) defaultValue);
        }
        return value;
    }
```

In the QRCode's exemple, the password field is a Boolean, and doesn't has a default value defined in `GENERAL_KEYS` so after saves as Boolean , it tries to cast back to String.

So I think the way is put a default value in `GENERAL_KEYS` for password, and uses the `.getClass()` approach. Have to check all places that uses password, but it will works.

Do you think is there another more appropriate way?

**Comment by lognaturel** [comment]
What about making `save` based on the type of the defaults (defaulting to String when there's no default) rather than on the types of the values? I believe that saving a value of the wrong type will always be bad news so this seems like it would be good to do in all places where we're saving preferences, not just for json (though that's where it's most likely to be corrupt).

**Comment by grzesiek2010** [comment]
> What about making save based on the type of the defaults (defaulting to String when there's no default) rather than on the types of the values?

I think we should check both and when both are equal we should allow saving. It should take place in save methods in both General and Admin preferences.

@brunoguic what do you think?

**Comment by lognaturel** [comment]
I'm going to close for now since we haven't heard from @brunoguic in a long while. If he or someone else would like to pick back up, that'd be great!

**Pull request closed without merging**
