### PR TITLE
Updated gradle for Studio 3.0

### LINKED ISSUE #1651: Error in build of project in android studio 3.0
#### Problem description
Build gives error when imported the project in android studio.

#### Steps to reproduce the problem
Just build the project in Android Studio 3.0

#### Expected behavior
Successful build with no errors and warnings

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

### PR DESCRIPTION
**Pull request by yashLadha**
Signed-off-by: yashLadha <201551061@iiitvadodara.ac.in>

Closes #1651

#### What has been done to verify that this works as intended?

Updated gradle file for removing the build error referenced in this [link](https://github.com/gradle/gradle/issues/2340) for the updated gradle version.

#### Why is this the best possible solution? Were any other approaches considered?

Updated the variable. There is no alternate approach as per my research.

#### Are there any risks to merging this code? If so, what are they?

No. It gives a successful build

#### Do we need any specific form for testing your changes? If so, please attach one.

No. Just build the code by importing the code in android studio from VCS.

### CODE REVIEW

**Comment by lognaturel** [comment]
Thank you, @yashLadha and welcome to ODK! If you haven't already, please join us in the #collect-code channel of the [developer Slack](slack.opendatakit.org).

This results in some build failures which you can see by clicking on Details above. I believe that if you revert the change to `outputFileName` it will work.

This is part of #1645 but let's get it in once the problem above is resolved to make the upgrade smoother in the short term. 

@jknightco is addressing some build warnings in #1645 and we have announced that the upgrade will happen next week to give everyone the opportunity to download and upgrade Android Studio as convenient (we have developers in areas with limited bandwidth). Once #1645 is merged everyone will need to use AS 3.0.

**Comment by yashLadha** [comment]
@lognaturel I haven't got invite for the slack team. Can you check?

**Comment by lognaturel** [comment]
Oops, the URL was broken because I left off the protocol. http://slack.opendatakit.org/ should let you self-register.

**Comment by yashLadha** [comment]
It also says i had requested for an invite. But till now i haven't received invite for slack channel. @lognaturel

**Comment by lognaturel** [comment]
Do make sure to check your spam folder. You may also want to try again and make sure you enter in your email address exactly right.

**Comment by lognaturel** [comment]
Closing since this doesn't work. Will focus on #1645.

**Pull request closed without merging**
