### PR TITLE
Add support for SVG image assets

### LINKED ISSUE #1763: Add support for SVG image assets
If an SVG image is used, it is currently reported as invalid. Try form https://docs.google.com/spreadsheets/d/17eDX7wYPsZnvk6nHzx3WkwHADXqj1IJezK6zE5SiSu4/edit#gid=0 with media [svg-images-media.zip](https://github.com/opendatakit/collect/files/1613463/svg-images-media.zip) to reproduce.

Allow SVG images. I think they should always scale to fit the device width but if you have other ideas, please share in comments.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #1763 

#### What has been done to verify that this works as intended?
I've tested two devices:
Samsung Duos Android 4.2.2
Samsung Galaxy S4 Android 5.0.1

and this form:
[form.zip](https://github.com/opendatakit/collect/files/1635323/form.zip)

#### Why is this the best possible solution? Were any other approaches considered?
I thought it's easy and @lognaturel  as I remember you said the same but unfortunately we were wrong and it's not as trivial as we thought.
I have tested multiple possible solutions and only one works well to me, it's https://scand.com/products/svgkit-android/

I've also tested these solutions:

https://github.com/japgolly/svg-android
http://bigbadaboom.github.io/androidsvg/
https://github.com/Pixplicity/sharp
and probably something else I can't recall now.

In all mentioned above cases I was able to find bugs so they are faulty.

#### Are there any risks to merging this code? If so, what are they?
We need to test image formats we had supported before like `png` etc. That's the possible regression.

#### Do we need any specific form for testing your changes? If so, please attach one.
The form is above.

### CODE REVIEW

**Comment by lognaturel** [comment]
Unfortunately svgkit-android is GPLv3 which is a viral license and not compatible with Apache 2.0. It looks like they may be open to relicensing but before we ask I'd like to understand the issues with the other libs. In particular, androidsvg seems to be the most popular one in resources I'm seeing. It also seems like svgkit-android may not help with #1764 which is the ultimate goal for this.

**Comment by lognaturel** [comment]
Some other ideas that may be worth looking into are whether simple SVGs could be programmatically converted to VectorDrawables or using a WebView.

**Comment by grzesiek2010** [comment]
@lognaturel do you mean the androidsvg I mentioned?

**Comment by lognaturel** [comment]
Yes @grzesiek2010 that is the one that virtually all writings on SVG in Android that I can find recommend.

**Comment by lognaturel** [comment]
Closed in favor of #1807.

**Pull request closed without merging**
