### PR TITLE
Fixed changing languages

### LINKED ISSUE #4077: Change language issue
#### Software and hardware versions 
Collect v1.28.x, Android v7, 9, 10 probably all device used...

#### Problem description
I have noticed that changing the language does not work in all tried. On Android 7 it doesn't work at all. On other ones it works sometimes - not sure exactly why. In all tries after closing the app after opening it again default language is restored. 

ezgif com-video-to-gif (22)

#### Steps to reproduce the problem
1. Change language to Spanish
2. Change language to RTL
3. Close an app 
4. Go back to Collect

#### Expected behavior
- the language should be updated immediately 
- default language should not be restored after closing app and going back

#### Other information 
- compared with 1.27: the issue is not visible

@getodk-bot label "regression"

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #4077

#### What has been done to verify that this works as intended?
I tested the fix on various different APIs 21...29

#### Why is this the best possible solution? Were any other approaches considered?
The issue was caused by changes in androidx.appcompat. I implemented my fix according to what they said in release notes:
https://developer.android.com/jetpack/androidx/releases/appcompat#1.2.0
https://cs.android.com/androidx/platform/frameworks/support/+/androidx-master-dev:appcompat/appcompat/src/androidTest/java/androidx/appcompat/app/NightModeCustomApplyOverrideConfigurationActivity.java

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
We should test changing language on as many different android versions as possible. Would be also good to verify if everything is fine after reseting settings.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by lognaturel — APPROVED** [review]
Great to get off a release candidate and even better that there's now an explicitly documented way to do all this.

**Comment by kkrawczyk123** [comment]
@grzesiek2010 I have noticed a small issue with the text cursor in RTL. It is also visible on 1.27.3 so it was not introduced in that PR. I was wondering if you could take a look if it's quick to fix. If it's not, don't bother and we will report it separately as it's just not aesthetic: 
Screenshot_2020-09-15-12-31-13

I have verified cases:
- jumping between different languages
- RTL
- filling form
- reset settings
- use different devices language 
on Androids: 5.1, 7.1, 8.1, 9.0 and 10.

**Comment by grzesiek2010** [comment]
Since the issue with doubled cursor is not visible on the newest versions 9+ and I can't see any easy fix let's merge without it. To be honest I'm not sure if I would even report it in a separate issue since it's not a big problem. I would rather wait once we refactor those widgets and move the code responsible for creating those text boxes to layout files. Maybe this will fix the issue.

**Comment by kkrawczyk123** [comment]
Sure I agree.

@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"

**Pull request merged**
