### PR TITLE
CODE_REFACTORING: Added a general method to create TextViews for answers

### PR DESCRIPTION
**Pull request by grzesiek2010**
It's a continuation of https://github.com/opendatakit/collect/pull/1374

#### What has been done to verify that this works as intended?
I've used AllWidgets form to review all widgets and confirm it looks like before. I've used also forms from #1274 to test range widgets.

#### Why is this the best possible solution? Were any other approaches considered?
Now we have two general methods to build TextViews for answers, so we can be sure everything is consistent and looks the same.

#### Are there any risks to merging this code? If so, what are they?
I can't see any risk.

### CODE REVIEW

**Comment by mmarciniak90** [comment]
Tested on Android 4.2, 4.4, 5.1, 6.0, 7.0
I did not noticed regression.

**Comment by lognaturel** [comment]
@jknightco This one also touches code you're looking at right now. What do you think?

**Comment by lognaturel** [comment]
@jknightco Just want to draw your attention to this one since I think you thought there was only one PR I was asking about! At first glance it looks like there are no conflicts with what you've done so far but I want to get your ok before merging.

**Comment by heyjamesknight** [comment]
@lognaturel nope looks good!

**Review by lognaturel — APPROVED** [review]

**Pull request merged**
