### PR TITLE
Make sure redownloading the same form doesn't break anything [master]

### LINKED ISSUE #4355: Downloading a form with the same hash fails every other time
#### Software and hardware versions 
Collect v1.29.3, works in v1.29.2

#### Problem description
Downloading a form with the same formid and version fails every other time. The user reporting this uses match exactly which is particularly annoying because the forms will disappear and re-appear periodically. https://forum.getodk.org/t/document-has-no-root-element-error-message/32121

#### Steps to reproduce the problem
1. Download a form such as All Widgets from the default server, verify it opens
2. Go back to Get Blank Form, select the same form, download it
3. Go to Fill Blank Form, see that the form is no longer there
4. On the device in `/sdcard/Android/data/org.odk.collect.android/files/forms`, verify that the form was added a `.bad` extension and is an empty file

#### Expected behavior
It should be possible to request downloading a form with the same formid and version over and over again. Files (form or media) with the same hash should be skipped.

#### Other information 
I think the problem was introduced in #4333 and is that `ServerFormDownloader.downloadXform`'s result will have a file that is the destination form XML file if the form was already on the device. Then `installEverything` will try to copy the file onto itself and apparently the result is to empty the file.

@seadowg This is freshest for you! An easy solution would be to wrap the form def copy in `if (!formFile.getAbsolutePath().equals(fileResult.file.getAbsolutePath()))` in `installEverything`. Would be great to have a test and maybe you can think of a better approach. Perhaps `file` should be `null` in this case.

### PR DESCRIPTION
**Pull request by seadowg**
Closes #4355

#### What has been done to verify that this works as intended?
@lognaturel fixed merged conflicts after #4356 was merged, ran the build and ran the tests.

#### Why is this the best possible solution? Were any other approaches considered?
#4357 was a simple fix for a point release. This is a more permanent one.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This makes changes to how forms are downloaded and moved so it's relatively risky. The test coverage is good which de-risks it but all of the same cases as https://github.com/getodk/collect/pull/4357#issuecomment-766981446 should be verified.

#### Do we need any specific form for testing your changes? If so, please attach one.
Any.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by lognaturel — APPROVED** [review]

**Comment by mmarciniak90** [comment]
@seadowg something is wrong :cry: I can't download all forms from default server - I tried fresh instalation and reset settings.
When I try connect with Central, all forms are not downloaded (compared with master where all forms are visible)

You can try this user. 5 forms should be downloaded but I see only 2 forms. 
image

You can also try this Aggregate server. 8 forms should be downloaded.
collect-settings

**Comment by mmarciniak90** [comment]
@getodk-bot unlabel "needs testing"

**Comment by lognaturel** [comment]
Thank you, @mmarciniak90. This is a case of over-reliance on tests that use faulty doubles. The `InMemFormsRepository` always uses absolute paths for everything so we didn't see that this failed with scoped storage and relative paths in the db. I think we should run all tests with the equivalent of scoped storage now. I'm still working out the best way to do this and don't think it should block QA.

**Comment by mmarciniak90** [comment]
**Tested with success**

Verified on Android versions: 7.0, 8.1, 10.0

Verified cases (followed list from  #4357):
- download using match exactly and then manually (Central, Aggregate, Kobo, ONA)
- download twice manually from the same server (Central, Aggregate, GD, Kobo, ONA)
- download twice manually from different servers (Central and then Aggregate)
- download the same and another version (Central)
- download when submission has been filled
- download twice Central draft
- same formId/version, different contents- Central draft -> error during finalizing when 2 forms with different content are available
- same formId/version, different media - Central draft -> only new media are downloaded
- download form with media
- download forms without media
- match exactly - refresh button
- auto-update to the latest form version (match exactly; only previous forms; Central)
- cases from my previous comment

**Comment by kkrawczyk123** [comment]
Verified also on Androids 5.1, 7.1 and 9.0.

@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"

**Pull request merged**
