### PR TITLE
Audio widget

### LINKED ISSUE #1120: Improving the audio widget
This is the proposed wireframe for the new UI
audio widget

When no audio file is selected, then the bottom layout with play buttons and seekbar will remain hidden

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Resolves #1120 

In continuation of #1127

### CODE REVIEW

**Comment by lognaturel** [comment]
Looks fantastic! You convinced me on the 5sec fast forward/rewind interval; let's keep it.

The play and forward/back icons look a little bit fuzzy on the Samsung Tab 4 like maybe they're not quite the right resolution.

When audio is paused and I scrub, the audio starts playing right when I drop the scrubber which I find surprising. I'd expect it to match the current state -- keep playing if it's already playing or don't play if it was paused when I started scrubbing.

If I have some audio loaded, swipe forward or back to another question and then return to the audio question, there's some strange behavior. Play works but the scrubber doesn't. If I try to scrub, the end time goes to 0. I haven't looked at the code but I suspect the audio isn't loaded in that case.

**Comment by shobhitagarwal1612** [comment]
@lognaturel Done. Please review

**Comment by lognaturel** [comment]
As you reminded me, I'm looking at this again, @shobhitagarwal1612 and I agree we should get it into master! How about using vectors now?

I also suggest leaving off the button icons. I like them a lot but I think they could be confusing for people who don't recognize what they are. Not everyone has seen a paperclip or a microphone before.

**Comment by shobhitagarwal1612** [comment]
@lognaturel Will submit a PR with the changes soon

**Pull request merged**
