### PR TITLE
Always fall back to the "Demo Project" name when the domain is demo.getodk.org and no project name is set

### LINKED ISSUE #4626: Always fall back to the "Demo Project" name when the domain is demo.getodk.org and no project name is set
Tapping on "Try a demo" provisions a project with name "Demo project" and corresponding icon and color. There should be the same behavior in the following cases:
- [x] manually configuring "https://demo.getodk.org" as the URL
- [x] upgrading from a prior version with the server configured as "https://demo.getodk.org"
- [x] scanning a QR code with "https://demo.getodk.org" as the URL and without a project name
- [x] scanning a QR code no (or empty) URL and without a project name

I'm hoping there's a single place where the fallback project name is defined that this special case can be added to.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #4626

#### What has been done to verify that this works as intended?
I tested this change manually and improved automated tests.

#### Why is this the best possible solution? Were any other approaches considered?
It has been implemented according to what we agreed in the issue.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
This will be tested later as a whole feature.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by seadowg — COMMENTED** [review]
This looks good, but one of the cases in the issue isn't quite solved. Will discuss there.

**Review by seadowg — CHANGES_REQUESTED** [review]
Ok so as per the discussion in #4626 we also need to handle empty URL cases for QR codes as that's what we'll get when scanning demo QRs from older versions.

**Comment by grzesiek2010** [comment]
> Ok so as per the discussion in #4626 we also need to handle empty URL cases for QR codes as that's what we'll get when scanning demo QRs from older versions.

Done.

**Review by seadowg — APPROVED** [review]
Done!

**Pull request merged**
