### PR TITLE
Measure how often manually specified instance names are used

### LINKED ISSUE #5350: Add analytics for manually-specified instance name
Instance name is editable when it is not specified by an expression in the form definition. Any name specified that way is local to Collect only.

Our hypothesis is that this gets used very rarely. We'd like to verify that.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5350 

#### What has been done to verify that this works as intended?
I've reviewed implemented changes.

#### Why is this the best possible solution? Were any other approaches considered?
I've just added new logs so not much to discuss here.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It doesn't require testing.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by seadowg — COMMENTED** [review]
Not sure if this is what we're after. I've started a discussion at https://github.com/getodk/collect/issues/5350.

**Review by seadowg — CHANGES_REQUESTED** [review]
Based on discussion in issue.

**Review by seadowg — APPROVED** [review]
Looks good to me! @lognaturel would appreciate a double check here in case I'm missing a case/scenario. If you're happy, you should just be able to go ahead and merge this.

**Review by lognaturel — APPROVED** [review]
I would only have tracked the edited names assuming that there will be very, very few but this seems good too! If we get the info we need quickly, we can remove the events.

**Pull request merged**
