### PR TITLE
Combine background audio for each form fill session

### LINKED ISSUE #4346: Background recording is resumed whenever form is opened
~~Blocked by #4344~~

**Acceptance**

- [x] Given I've filled and closed a form with background recording
When I open the form to edit
And close the form again
Then the recording has audio from the first and the second time I was filling in the form

~~- [ ] Given I'm filling a form with background recording
When the app crashes
And resume form entry
And exit the form
Then the recording has audio from the first and the second time I was filling in the form~~

**Combining files**

For MP4/AAC we can use `org.mp4parser:muxer:1.9.41`:

```kotlin
val runningTrack = MovieCreator.build(runningFile.absolutePath).tracks[0]
val newTrack = MovieCreator.build(newFile.absolutePath).tracks[0]

val movie = Movie().also { it.addTrack(AppendTrack(runningTrack, newTrack)) }
val out = DefaultMp4Builder().build(movie)
val fc = RandomAccessFile(runningFile, "rw").channel

out.writeContainer(fc)
fc.close()
```

For AMR we can skip the headers of the second file to combine: https://stackoverflow.com/questions/9901786/android-mediarecorder-class-does-the-setoutputfile-method-append-data-to-the/9924630#9924630

EDIT: We can't detect crashes (the app just closes and the process is killed) so can't deal with that scenario.

### PR DESCRIPTION
**Pull request by seadowg**
Closes #4346

#### What has been done to verify that this works as intended?

New tests and verified manually.

#### Why is this the best possible solution? Were any other approaches considered?

Comments inline.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

I think it'd be good for another dev to check this manually to see if I've missed anything.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
I like how the `AudioFileAppender` implementations have ended up looking. I did some trying of things and it seems to work really well! I find it surprisingly cool to listen to the stitched together audio. I do think it'd be helpful to separate the sessions with a tone or something but definitely something we can come back to after user feedback. I can't think of anything else missed and look forward to seeing what @getodk/testers find!

I initially thought it'd be nice to merge open background audio PRs to `master` so everything is together. I don't see an advantage at this moment so I'll let you all coordinate at the start of your day.

**Comment by kkrawczyk123** [comment]
@seadowg I have to admit that I am impressed! I have identified one scenario when the recording is broken and unusable. 
Steps to reproduce:
1. Fill submission with background recording
2. Go to instance folder and delete the recording
3. Open edit Saved Form and edit submission
4. Open instance folder - see that new recording has been created
5. Try to play the audio file - it doesn't work 
New audio file should be independent of the deleted one. What do you think about that? Should I open new issue for that case?
ezgif com-video-to-gif (52)

**Comment by seadowg** [comment]
@kkrawczyk123 haha yeah I think we can categorize that under the "please don't do that". I agree the behaviour should just be to handle this gracefully, so the user ends up with the recording from the second session. Let's file an issue for that and not block this as you suggest.

**Comment by kkrawczyk123** [comment]
**Tested with success!**
Verified on Androids: 5.1, 7.1 and 9.0

Tested scenarios:
- finalize submission and edit
- save submission and edit 
- edit submissions for multiple times
- fake, low and normal quality questions
- send submission to Central, and open the record
- edit submission when previous audio deleted - issue reported in #4398
- fill submission, disable recording in another submission and continue recording after enable recording
- minimize app when filling and editing form

**Comment by mmarciniak90** [comment]
Tested also with success on Android 7.0, 8.1, 10.0

@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"

**Pull request merged**
