### PR TITLE
Fixed the IconDuplicates lint

### PR DESCRIPTION
**Pull request by grzesiek2010**
#### What has been done to verify that this works as intended?
I tested sorting and confirmed everything looks like before.

#### Why is this the best possible solution? Were any other approaches considered?
I just removed duplicated icons, they were identical so I don't know why we added two different files with the same image.

#### Are there any risks to merging this code? If so, what are they?
No.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

### CODE REVIEW

**Comment by shobhitagarwal1612** [comment]
Regression noticed: The tint color of the previously selected item is not removed in some cases

Steps to reproduce:
1. Click on `Fill Blank Form`
2. Click on `sort` icon located in the toolbar
3. The first item `Name A-Z` is selected (both the icon and text are blue) by default
4. Click on the second item `Name Z-A`
5. Reopen the sort menu by clicking on the `sort` icon again
6. User notices that the first icon is still blue in color

**Comment by grzesiek2010** [comment]
@shobhitagarwal1612 
Thanks but I can't reproduce the issue. Could you provide more info about your device? Are you sure it's regression?

**Comment by shobhitagarwal1612** [comment]
I tested it on Redmi Note 4 - Android 7.0

**Comment by lognaturel** [comment]
@shobhitagarwal1612 Thanks for noticing this! Do you also see the problem on master? If so it might be best to file as a separate issue.

**Comment by kkrawczyk123** [comment]
I reproduced issue mentioned by @shobhitagarwal1612  on Androids: 4.1, 4.2, 4.4, 7.0 and 8.0 (Screenshot 1) I couldn’t obtain it on master, only on branch so I guess this is regression. On Android 7 I also was able to select two sorting option simultaneously (Screenshot 2) and after choosing it “Sort by” module did not minimize but it wasn’t 100% reproducible. Additionally, I wasn’t able to reproduce that issue on androids 5.1 and 6.0. 
screenshot1
screenshot2

**Comment by kkrawczyk123** [comment]
@opendatakit-bot unlabel "needs testing"

**Comment by grzesiek2010** [comment]
Ok, thanks for the confirmation. I'll try to figure out why it works in this way when I'm free.

I'm pretty sure it's a bug that was bypassed using different files.

**Comment by grzesiek2010** [comment]
I created a separate issue https://github.com/opendatakit/collect/issues/1791 since I'm almost sure it's a different bug.

**Comment by lognaturel** [comment]
Let's fix #1791 first and make sure this works before merging.

**Pull request merged**
