### PR TITLE
Fixed Attempt to invoke virtual method 'java.lang.String java.io.FilegetParent()' on a null object reference

### LINKED ISSUE #2324: Attempt to invoke virtual method 'java.lang.String java.io.File.getParent()' on a null object reference
> org.odk.collect.android.activities.FormEntryActivity.saveChosenImage (FormEntryActivity.java:878)
org.odk.collect.android.activities.FormEntryActivity.lambda$onActivityResult$3$FormEntryActivity (FormEntryActivity.java:748)
org.odk.collect.android.activities.FormEntryActivity$$Lambda$3.run (Unknown Source)

https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/5b2a19556007d59fcd52cba4?time=last-seven-days&sessionId=5B30BAC6017D0001282975BD14D7D5AD_DNE_1_v2

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #2324 

#### Why is this the best possible solution? Were any other approaches considered?
I wasn't able to reproduce the issue it's just a null check to avoid crashes.

#### Are there any risks to merging this code? If so, what are they?
No.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew pmd checkstyle lint findbugs` and confirmed all checks still pass.
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by lognaturel** [comment]
How about adding a toast and perhaps logging something? I also don't know how this can happen but it doesn't seem right to just silently let the image not be saved.

**Comment by grzesiek2010** [comment]
Yes, you are right. I added a toast and logging.

**Review by dcbriccetti — APPROVED** [review]

**Comment by dcbriccetti** [comment]
Since we aren’t able to reproduce, I see no reason to send to QA. Shall we merge?

**Comment by lognaturel** [comment]
Yes! 🙏

**Pull request merged**
