### PR TITLE
Automated tests and fixes for existing ones

### PR DESCRIPTION
**Pull request by kkrawczyk123**
Adding new regression automated tests and fixing existing ones.

### CODE REVIEW

**Comment by seadowg** [comment]
@kkrawczyk123 Oh wow this is an interesting one. I pulled this down and saw that the PMD error is `Avoid calling finalize() explicitly`. It looks like line 47 in `FormManagementTest` is incorrectly triggering this check as the string resource used is `R.string.constraint_behavior_on_finalize`. 

I'm guessing the simplest thing to do is change the string name but I'm surprised this broke!

**Comment by grzesiek2010** [comment]
Yes, it's a pmd bug I even tried to update pmd but the problem is not solved so renaming if you can come up with a good name is fine or suppressing otherwise.

**Review by mmarciniak90 — APPROVED** [review]

**Review by grzesiek2010 — APPROVED** [review]

**Comment by seadowg** [comment]
@grzesiek2010 sorry I'd talked to @kkrawczyk123  but not posted here about it looking like we had Test Lab failures with these changes. Should we revert this until we know the suite is green? It looks like the fix we needed for `spinnerList_ShouldDisplay` is something we could bring in seperately.

**Comment by grzesiek2010** [comment]
Let's keep it, for now, I'll look into it.

**Pull request merged**
