### PR TITLE
Set OSM map allowable min zoom to 2, max zoom to 22.

### PR DESCRIPTION
**Pull request by zestyping**
#### What has been done to verify that this works as intended?
I manually tested the zoom controls in the GeoTrace activity in OSM map mode.

#### Why is this the best possible solution? Were any other approaches considered?
This adjustment addresses two small problems:
  - The minimum zoom level used to be 1, which zooms out far enough that you can see two vertically repeated copies of the map on most phones.  Setting the minimum to 2 means that when you are zoomed out as far as possible, you mostly don't see this repetition.
  - The maximum zoom level used to depend on the resolution of the map tiles, which usually would come out to level 19.  Increasing this to allow zooming in to level 22 is one of the things we wanted to do in Phase 2 of our geo roadmap (https://docs.google.com/document/d/1r3wJrOVDeFQkk4kWMoW29LtLI1vbBChqJ65w1Jyg4YU/edit).

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
The only visible change should be the operation of the zoom buttons.

#### Do we need any specific form for testing your changes? If so, please attach one.
Any form that has geo widgets with maps can be used to test this change.  Here's one:
[geo-widgets.zip](https://github.com/opendatakit/collect/files/2497688/geo-widgets.zip)

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by lognaturel — APPROVED** [review]

**Comment by kkrawczyk123** [comment]
**Tested with success!!**
Verified on Androids 4.1, 4.2, 4.4, 6.0, 7.0 and 8.1.
I feel much more the lower boundary as finally when I open OSM map I don't see few maps!!! good job @zestyping!!

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Comment by ivangayton** [comment]
Some testing with OSM basemap:
- Zoom works to 19, and you can pan anywhere you like.
- When you zoom up to 20 and 21, it scales the tiles up (you can see that the labels pixillate, so it's obviously scaled). However, if you pan sideways, you go off the edge of the scaled tiles and find the graph-paper-grid empty area beneath. When moving laterally it seems it doesn't fetch new level-19 tiles to scale.
- At zoom 22, the OSM tiles disappear altogether, leaving only the graph-paper-grid emptiness.

So zooming to level 20 or higher seems only to work by scaling level-19 tiles _that have already been downloaded_. And then only to level 21—at level 22 it's blank. 

Immediately afterward on the same phone, I tried an MBTiles raster with tiles from level 16 to 20. That displayed perfectly until level 20, then disappeared—so at level 21 the scaled OSM tile popped up from behind the MBTiles. As far as I can see, the MBTiles never scale at all, while the OSM tiles seem to scale from 19 to 21 (but only in the region already covered by a downloaded level-19 tile).

**Comment by zestyping** [comment]
@ivangayton Thanks, Ivan!

On my two phones (Sony Xperia Z3 compact, Huawei LYO-L21), I observed exactly the same behaviour you described.

When @lognaturel tried it on her phone, though, she was able to zoom all the way to 22 and the tiles did not disappear.  Just as you experienced, only the tiles that had been previously loaded at level 19 stayed present; new tiles did not load at zoom level 22.

We're going to leave it this way for the current release, because it seems harmless.  It is inconvenient that zoom level 22 seems to work (well, semi-work) on some phones and not on others, but I don't think it's too terrible for users to learn or discover that if level 22 doesn't work they can zoom back out to 21.

Clearly, even if tiles are visible at level 21 or 22, the tile loading logic isn't ideal.  It looks like some issues related to this were addressed in the osmdroid library within the last two years, so I think we should upgrade osmdroid (see #2695) and see if that fixes all these issues.  (See especially https://github.com/osmdroid/osmdroid/wiki/FAQ.)

**Comment by zestyping** [comment]
Added #2696 to capture this as an issue.

**Pull request merged**
