### PR TITLE
New media icons

### PR DESCRIPTION
**Pull request by grzesiek2010**
#### What has been done to verify that this works as intended?
I tested a form with media files like:
https://drive.google.com/open?id=1SRtrp3TobXyc49EzSDZLPdtBOPWEG6pL

#### Why is this the best possible solution? Were any other approaches considered?
Current media buttons are really awful:
screenshot_2018-09-07-00-40-18

I added new buttons so now it may look like below:
screenshot_2018-09-12-18-03-51
screenshot_2018-09-12-18-04-16

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
It's only a visual change. I can't see any potential risk here.

#### Do we need any specific form for testing your changes? If so, please attach one.
The form attached above.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew pmd checkstyle lintDebug spotbugsDebug testDebugUnitTest connectedDebugAndroidTest` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by grzesiek2010** [comment]
@lognaturel do you like it?

**Comment by lognaturel** [comment]
I think it's a really good idea to think about updating these. Like all changes, it should be approached with careful reasoning and consideration of tradeoffs. Whatever icons are picked should be picked for principled reasons and hopefully fit into a broader visual design strategy.

What was your reasoning for those specific icons? What other applications did you look at for inspiration? How does this change fit in with [material design iconography guidelines](https://material.io/design/iconography/system-icons.html#)? What other changes to the layout did you consider to make media more intuitive and attractive?

**Comment by jd-alexander** [comment]
At a glance, the icons look really close to each other like someone could mistakenly attempt to press one and invoke the other. We need to revisit the way how we handle padding around icons.

**Comment by grzesiek2010** [comment]
>What was your reasoning for those specific icons? What other applications did you look at for inspiration? 

I used two icons from https://material.io/tools/icons/?style=baseline so I think it's a good option.
I think they look well and are similar to old ones what is important (we should implement big changes because it may be confusing for our users).

> How does this change fit in with material design iconography guidelines?

Two of the used icons come from https://material.io/tools/icons/?style=baseline
I mean:
https://material.io/tools/icons/?search=pla&icon=play_circle_filled&style=baseline
and
https://material.io/tools/icons/?search=paus&icon=pause_circle_filled&style=baseline

I just needed to prepare the one for audio files and I did it based on those two I mentioned above so I think it matches rules pretty well.

> What other changes to the layout did you consider to make media more intuitive and attractive?

I don't have any idea. I think it's a good first step and as I said maybe we shouldn't change the layout too much since it may be confusing for our users.

> At a glance, the icons look really close to each other like someone could mistakenly attempt to press one and invoke the other.

They were even closer before. In fact, I think people rather use one of media types I mean it's audio or video and the problem doesn't exist.

**Comment by lognaturel** [comment]
I'm going to close for now pending an issue with some description of alternatives and an overall vision for where the changes would go. I agree that the current icons are quite bad and that this would be good to address but at the very least, there should be a description of various icons considered and why one is better than others. 

For example, wouldn't using a [video icon](https://material.io/tools/icons/?search=video&style=baseline) be more helpful for showing videos? Which of the Material Design [play icons](https://material.io/tools/icons/?search=play&style=baseline) might be more visually appealing? Should the icons have a background or not?

**Pull request closed without merging**
