### PR TITLE
Bityarn branch

### PR DESCRIPTION
**Pull request by gmimano**
This is output from work done during the ODK hackathon in Nairobi 21st Novemeber 2016
**Issues Fixed:**

1. Toggle All in Get Blank Form first selects all even if they already are selected #248.
2. ODK Aggregate URL History #255

### CODE REVIEW

**Comment by lognaturel** [comment]
Yay @gmimano! Couple of quick procedural things. First, I think it's worth making separate PRs for separate features even if some seem trivial. In this case, the fix to #248 would be ready to merge but the one for #255 needs some changes. Second, to close issues automatically on merge, the keyword to close ("Fixed", etc) needs to be right before the issue number 😏. You can read more [here](https://help.github.com/articles/closing-issues-via-commit-messages/).

When I try to use the autocomplete, it's only suggesting the last value URL even if I've changed servers a few times. It also seems like it only starts making suggestions after two characters are typed in. I think it makes sense to show the list as soon as the field gets focus.

I notice that your constructor call on super is only available in API-21+. Currently the min API level is 9. There probably needs to be a broader conversation on whether it still needs to be that low but in the mean time, is it possible for you to make the code API-9 compatible?

**Comment by lognaturel** [comment]
One more thing! Like we discussed yesterday, there aren't any commenting guidelines yet. I think it's ok not to comment on very simple methods but please remove the Javadoc template if you don't think a comment is needed. 👍

**Comment by gmimano** [comment]
Noted. Will make the necessary changes.

**Comment by gmimano** [comment]
All the server history now shows when widget is focused, I have also cleaned up the code documentation (perhaps we can make it better. Let me know) . 

For this issue:
**I notice that your constructor call on super is only available in API-21+. Currently the min API level is 9. There probably needs to be a broader conversation on whether it still needs to be that low but in the mean time, is it possible for you to make the code API-9 compatible?**

I will have to check my IDE settings and make proper changes. I guess I need the app to check the API levels programmatically like so _int currentapiVersion = android.os.Build.VERSION.SDK_INT;_ and call the appropriate constructor. I may have changed my IDE settings at some point. Will let you know once I have figured it out.

**Comment by lognaturel** [comment]
Looks like the list is correctly populated as long as I stay on the Aggregate settings screen but if I navigate away from it and come back, then only the last URL is shown. When multiple URLs are shown, there seems to be a second 'ghost' URL list in the upper left that doesn't go away when I tap out of the input field. Sometimes the 'drop down' is shown above the input field and some of the options are off the screen. I think it should always be below and scrollable. Thanks!

**Comment by lognaturel** [comment]
I'm going to close this PR because #248 was closed by #300. It would be fantastic to get a new PR for #255 so we can get that nice feature in!

**Pull request closed without merging**
