### PR TITLE
Replace pngs in General settings with vectors

### LINKED ISSUE #2196: Replace pngs we use in General Settings with vectors
#### Software and hardware versions 
Collect v1.14.2

#### Problem description
Replace pngs we use in `General Settings` with vectors

#### Other information 
**It should be done once we stop supporting android 4 since there is no easy way to replace these icons with vectors (android 4 would require doing that programmatically).**

Icons we should replace:

ic_cloud
ic_phonelink_setup
ic_assignment
ic_face

screenshot_2018-05-14-10-26-04

### PR DESCRIPTION
**Pull request by CRMinges**
Closes #2196 

#### What has been done to verify that this works as intended?
The General Settings activity has proper icons that are vectors. This is according to 
both Android Studio preview and testing application on Google Pixel.
#### Why is this the best possible solution? Were any other approaches considered?
Simple fix, just create new vector files, and use them to replace PNG's
#### Are there any risks to merging this code? If so, what are they?
No
#### Do we need any specific form for testing your changes? If so, please attach one.
No
#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No
#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew pmd checkstyle lint findbugs` and confirmed all checks still pass.
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by jd-alexander** [comment]
Hey @CRMinges thanks alot for your contribution! Although this solution works well on newer versions of Android some won't support it so it's not an optimal solution at the moment. Check out this other PR that's similar that was trying to accomplish the same for more details! #2204

**Comment by grzesiek2010** [comment]
Yeah, I think it doesn't make sense to do that programmatically maybe we can wait till we stop supporting Android 4. Do you agree? @lognaturel @jd-alexander if so I'll add to the description in #2196

**Comment by CRMinges** [comment]
@jd-alexander alright, no worries. Thanks for the feedback.

**Comment by jd-alexander** [comment]
Yeah I agree @grzesiek2010 having these icons in xml looks way cleaner in IMO and it's not that much of them anyway.

**Comment by CRMinges** [comment]
Should I close this pull request then? @grzesiek2010  @jd-alexander

**Comment by lognaturel** [comment]
Thank you so much for looking into this, @CRMinges! I agree with you all -- we should close this and come back to it after we stop supporting Android 4.

**Pull request closed without merging**
