### PR TITLE
Copied test results into artifacts

### LINKED ISSUE #1585: Lint and test output files are not copied to artifacts in CircleCI
`checkstyle`, `pmd` and `findbugs` reports are correctly copied over and visible from the artifacts tab in CircleCI. However, `lint` reports are not. No test reports are available.

### PR DESCRIPTION
**Pull request by Divya063**
Closes #1585

### CODE REVIEW

**Comment by lognaturel** [comment]
Thanks for this, @Divya063! In the mean time, there has been some conversation in Slack about moving integration tests to another platform and upgrading to CircleCI 2.0. If we are moving to 2.0, #1628 may end up replacing this so I'll wait a bit on it.

**Comment by Divya063** [comment]
@lognaturel Upgrading to CircleCI 2.0 would be great as build performance would improve significantly and local build feature would reduce the time it takes to debug the build. I guess I should close this one.

**Comment by lognaturel** [comment]
Let's see if we can resolve the issues in #1628 and then we can close! If you have any ideas there, please share.

**Comment by Divya063** [comment]
@lognaturel I'm not sure about this but I guess XML report files are not being generated.

**Comment by lognaturel** [comment]
#1628 was completed and merged so we're now on CircleCI 2.0!

Was your comment about xml about this config or the 2.0 one? In the other one, copying over of artifacts is much simplified so XML doesn't have to be handled directly. I have verified that it shows up in the artifacts.

**Pull request closed without merging**
