### PR TITLE
Make select preloading disableable

### PR DESCRIPTION
**Pull request by seadowg**
This adds a "Select choice preloading" experimental setting that allows the new select choice loading behaviour to be disabled.

@dbemke could you try your performance test with and see if you get different times running with the setting enabled and disabled?

### CODE REVIEW

**Comment by dbemke** [comment]
Does this experimental setting change only the loading of a form (from clicking the form to open till the first question is displayed)or it also influences going to the next question? In the previous test I set time tracking so that it measured both cases together. I can change that time tracking - measuring which part would be better?
Should I compare 2023.3.1 vs the PR? or also the master vs the PR?

**Comment by dbemke** [comment]
I started testing the PR apk with (Kobo Test) the same settings like in the previous tests (form opening the form till getting to the second question. The results I got : 7370ms, 7547ms, 7630ms, 7718ms, 7303ms.
On the master version (064f9269ecc62a3ae68362884d7dcc1b7ec9ef4e) : 7081ms, 7611ms, 7346ms.

**Comment by seadowg** [comment]
It looks like the problem is more likely to be the recent changes to select choice caching than this, but could you do timings for the full test run like you did before @dbemke? Instead of testing against master it'd be good to compare the test with "Select choice preloading" on and "Select choice preloading" off. We want to know if disabling it increases performance.

**Comment by dbemke** [comment]
I changed the test - it measures time form opening the form till saving as draft (on Android 10, Kobo Test, the PR apk).
With the setting "Select choice preloading" on: 20579ms, 21026ms, 20691ms
With the setting "Select choice preloading" off: 21157ms, 21234ms, 20978ms

**Comment by seadowg** [comment]
Looks like preloading is slightly slower, but no where near the ~2s extra time you were seeing which is just further evidence it's because we're now caching less select expressions. I'll close this PR for the moment.

**Pull request closed without merging**
