### PR TITLE
Picker appearance

### PR DESCRIPTION
**Pull request by grzesiek2010**
Forms for testing:
[picker_decimal.txt](https://github.com/opendatakit/collect/files/1176723/picker_decimal.txt)
[picker_integer.txt](https://github.com/opendatakit/collect/files/1176722/picker_integer.txt)
[seekbar_decimal.txt](https://github.com/opendatakit/collect/files/1176724/seekbar_decimal.txt)
[seekbar_decimal_vertical.txt](https://github.com/opendatakit/collect/files/1176726/seekbar_decimal_vertical.txt)
[seekbar_integer.txt](https://github.com/opendatakit/collect/files/1176725/seekbar_integer.txt)
[seekbar_integer_vertical.txt](https://github.com/opendatakit/collect/files/1176727/seekbar_integer_vertical.txt)

### CODE REVIEW

**Comment by lognaturel** [comment]
Thank you, @grzesiek2010! Now that I see this in action, I'm not finding it as usable as I would have hoped. We know that users can find the date pickers confusing and use the wrong line as the selected value. I know this is the standard Android picker widget but I'm thinking we shouldn't rush this and should instead spend a little more time thinking through potential alternate interfaces. @yanokwa what do you think?

**Comment by lognaturel** [comment]
Would still like to get @yanokwa's opinion but upon further consideration, I think using the standard Android spinner is probably the best thing to do.

`null` as a null value seems like it might be a problem. I'm not sure that English speakers would understand it and I'm sure speakers of other languages won't. I thought I might be able to set a different value like "scroll to choose" or "empty" but it looks like that's not possible with the current code setup. That's the kind of thing that would be great to mention in the PR description! How did you figure out `null` worked? Do you have any ideas for using other default text?

**Comment by yanokwa** [comment]
When I tried this interface, my immediate thought was that putting the picker in a dialog (kinda like the new time widgets) would solve both the problem of enumerators using the wrong line AND the problem of null (it'd just be empty text below the button).

**Comment by lognaturel** [comment]
Very true. But it then feels much heavier. I wonder if people would use it at all.

Or we leave it and make it really clear in the docs that form developers should set a default?

**Comment by yanokwa** [comment]
Defaults help with null, but it doesn't help with people thinking the top level element is being selected. Yes, it's heavier, but I vote for more accurate data until we can find a better widget.

**Comment by lognaturel** [comment]
Let's go with an interface similar to the date/time widgets for now and get user feedback.

**Comment by grzesiek2010** [comment]
@lognaturel please take a look at it.

**Comment by lognaturel** [comment]
Thanks! It's better than I thought. The only thing I don't love is that it may not be super clear when a value is selected. What about changing the button from "Select value" to "Edit value" when a value has been selected? This would be similar to what the buttons for geowidgets do.

**Comment by lognaturel** [comment]
One other thing - when I'm on a tablet (Galaxy Tab 4), the buttons for other widgets like the geo widgets or camera widgets get a little taller. This button doesn't do that and I think they should match.

**Comment by grzesiek2010** [comment]
@lognaturel it should work as you expect.

**Review by lognaturel — APPROVED** [review]

**Pull request merged**
