### PR TITLE
Allow to use a front camera in BarcodeWidget

### LINKED ISSUE #2452: Allow to use a front camera in BarcodeWidget
#### Problem description
One of our users claims that his front camera works better and would like to use it in `BarcodeWidget`:
https://forum.opendatakit.org/t/using-zxing-barcode-scanner-plus-instead-of-barcode-scanner-or-odk-collect-integrated-scanner-for-decoding-barcodes/14358?u=grzesiek2010

We need to check if it's possible to do that.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #2452 

#### What has been done to verify that this works as intended?
I tested the attached form.

#### Why is this the best possible solution? Were any other approaches considered?
I used front appearance because it's similar to the appearances we use for selfie widgets.
#### Are there any risks to merging this code? If so, what are they?
We use the existed methods to check if a front camera is available and to determine a front cameraId so it's tested and I would say it's safe.

#### Do we need any specific form for testing your changes? If so, please attach one.
[barcodes.xml.txt](https://github.com/opendatakit/collect/files/2255314/barcodes.xml.txt)

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
Yes, we should add information about a new appearance if the solution is accepted.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew pmd checkstyle lintDebug spotbugsDebug` and confirmed all checks still pass.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by yanokwa** [comment]
@grzesiek2010 Will this also need changes in the form spec, pyxform, or JavaRosa?

**Comment by grzesiek2010** [comment]
> Will this also need changes in the form spec, pyxform, or JavaRosa?

No, Everything works out of the box. Here is an original xlsx file 
[barcodes.xlsx](https://github.com/opendatakit/collect/files/2265512/barcodes.xlsx) 

I just added the mentioned appearance.

We only need to add changes in https://github.com/opendatakit/docs

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
Works for me! Hard to believe the front camera works better on some devices -- mine won't even focus on a barcode -- but this is non-invasive so if it helps someone it's worth doing.

**Comment by kkrawczyk123** [comment]
@lognaturel, I have a question about the result when a device doesn't have a front camera - there is a toast "front camera not available on this device" which is very good but except that I am able to use a normal barcode scanner - is it the result that we want or it should be disabled after toast shows up as there is no front camera?

**Comment by lognaturel** [comment]
@kkrawczyk123 Good catch. In this case, I think it's falling back to the rear camera is more useful than disabling so this behavior seems fine to me.

I also now see that this removes the flashlight button when the front camera is used and that seems like the right way to go. 👍

**Comment by kkrawczyk123** [comment]
Ok, so there are no more questions.
**Tested with success!**
Verified on Androids: 4.1, 4.2, 4.4, 6.0, 7.0 and 8.1 

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Review by lognaturel — APPROVED** [review]

**Pull request merged**
