### PR TITLE
Migrated to AndroidX

### LINKED ISSUE #3013: Migration to AndroidX
#### Problem description
As described [here](https://developer.android.com/topic/libraries/support-library/revisions) Support Library 28.0.0 is the last released version so migrating to AndroidX is recommended.
More info about AndroidX: https://developer.android.com/jetpack/androidx

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #3013 

Changes in the first commit have been generated using Android Studio: **Refactor > Migrate to AndroidX** from the menu bar.

Rest of changes (commits: https://github.com/opendatakit/collect/commit/19705d8a43c52bb24fbbfee05fcacd83e8ed0f59 https://github.com/opendatakit/collect/commit/44b71024bf24c5e3a82116b7cfa305ed13bc5de8 https://github.com/opendatakit/collect/commit/87b562c316437ca81e3934346dbefbd1ade87c11 https://github.com/opendatakit/collect/pull/3014/commits/687af78958c46a25061258a17255896a2f51c2f6)
I added manually.

#### What has been done to verify that this works as intended?
I just installed the app and started some activities to check if it works well without any obvious crashes.

#### Why is this the best possible solution? Were any other approaches considered?
Migrating to AndroidX is recommended as described in the issue.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
There is no one thing/activity or something we could test here because changes are in 239 files.
I think it's a good time to merge those changes because we are after release so we have much time to test everything on a daily basis, without spending much time testing each functionality.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by grzesiek2010** [comment]
Three errors `incompatible types` are throwing. Everything works fine locally so probably it's just a problem wit CIrcleCi. I'll try to figure out what's going on.

**Comment by grzesiek2010** [comment]
Ok, finally I figured out what's wrong and fixed the problem in the last commit.
I had to add `gradle.properties` file, this file with appropriate values is being created for me by Android Studio but looks as if CircleCi can't do that and we need to add that file.

**Review by shobhitagarwal1612 — APPROVED** [review]

**Comment by shobhitagarwal1612** [comment]
I also performed a basic sanity test by checking the core functionalities. But would be even better if QAs can also verify this across different android versions

**Comment by lognaturel** [comment]
I propose this just get merged as soon as @grzesiek2010 fixes the merge conflicts without a QA pass. As @grzesiek2010, I think ongoing usage and eventual regression testing will be enough to catch any issues. Good thing the refactor tool was effective!

**Review by lognaturel — APPROVED** [review]

**Pull request merged**
