### PR TITLE
Stop using WeakReference in BaseLocationClient

### LINKED ISSUE #5208: Stop using `WeakReference` in `BaseLocationClient`
When using the [Observer pattern](https://en.wikipedia.org/wiki/Observer_pattern), storing observers (or listeners) using Java's `WeakReference` removes any guarantees that the observer is notified (a listener is called) but does introduce the advantage of not having to explicitly unregister an observation. In a lot of cases, the hidden detail of the former is actually completely undesired, even if the latter is useful. This is certainly the case for `BaseLocationClient` - storing the `LocationClientListener` as a `WeakReference` can result in cases where it is never called (if it is an anonymous object for instance). 

We should switch to using a direct reference for the `LocationClientListener` and manually unregister it in calling classes instead of relying on `WeakReference`.

As a side note, we should probably avoid `WeakReference` as much as possible. It always seems like such a good idea, but anonymous objects and lambdas mess up the expected memory behaviour very subtely. I have been fooled by this more times than I'm comfortable with.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5208 

#### What has been done to verify that this works as intended?
I've tested the changes manually.

#### Why is this the best possible solution? Were any other approaches considered?
The only interesting thing here is that after getting rid of using WeakReference I decided to combine setting listeners with start/stop methods see: https://github.com/getodk/collect/pull/5624/commits/d888d58547587a728317374d364f35737b47e4ed and https://github.com/getodk/collect/pull/5624/commits/22460462d94115d7c325b79256b1940dcdaa3ad6 Those two were always called together so I thought that it made sense to combine them.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Please test everything related to using GPS which means geo widgets and background location tracking. Please also test carefully if after recreating the activity/getting back to the app tracking location works correctly since this is the biggest area of risk I guess.

#### Do we need any specific form for testing your changes? If so, please attach one.
Any form with geo widgets and background location tracking like the `All widgets` form and [AuditTest.xml.txt](https://github.com/getodk/collect/files/11637168/AuditTest.xml.txt)

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by seadowg — APPROVED** [review]

**Comment by dbemke** [comment]
Something strange happened with maps. Mapbox is not available as a source of maps in settings and Google maps don't show the map (blank background, unable to zoom in/out)
maps

**Comment by seadowg** [comment]
@dbemke are you using the build created by CI? I'm realising you'll need to manually build to test maps (other than OSM), as we don't include our Google Maps or Mapbox keys in the CI build (so neither will work).

**Comment by dbemke** [comment]
Yes, the CI build

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on device with Android 10

**Verified cases:**
- regression tests with Geo widgets and background location recording (audit logs)
- Google Maps, OSM, Mapbox
- don’t keep activities enabled and disabled
- no background processes
- minimizing the app, rotating the screen
- location permissions enabled, disabled
- quick checks on Android 8.1

**Comment by srujner** [comment]
**Tested with Success!**

Verified on device with Android 13

**Pull request merged**
