### PR TITLE
Fix crash if storage permission is modified and display a screen to request for the permission

### LINKED ISSUE #2694: App crashes if the user returns to Get Blank Form view when Storage permission is unselected
#### Software and hardware versions 
Collect v1.18
Collect v1.17.**2**

Collect v1.17.1 works correct

#### Problem description
App crashes if the user returns to Get Blank Form view when Storage permission is unselected

#### Steps to reproduce the problem
1. The user opens the app as the first time and allows Storage permission
2. The user opens Get Blank Form / Delete Saved Form
3. Permission is unselected and the user returns to Collect
4. App crashes

#### Expected behavior
The user sees the dialog and is able to allow storage permission

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Closes #2694 

#### What has been done to verify that this works as intended?
1. Open app for the first time, the user sees the screen(attached below) which asks for storage permission. Then allow the storage permission
2. Open any activity and minimize the app
3. Unselect storage permission from system settings
4. Reopen the app 
5. The user sees the same screen asked on the first app launch which asks for the permission.
6. Granting the permission reopens the last opened activity, denying closes the app. 

#### Why is this the best possible solution? Were any other approaches considered?
1. Provides some context to the user before asking access to storage permission.
2. Since this check is implemented in the base activity, so the behavior remains constant across all activities
 3. I have also checked that only the code which relies on storage permissions is in `init()`

I only considered this approach.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Users will now see an extra screen instead of getting directly prompted with the permission access dialog when the app launches for the first time or whenever the storage permission is revoked from system settings. 
Until now, only entry point activities were able to request for permissions, but now all activities can since the base activity has the implementation to request for permission

Possible risks include crashes due to mishandled storage permission, incorrect loading of data in all of the screens (since this change affects all screens)

#### Do we need any specific form for testing your changes? If so, please attach one.
No, any form can be used to verify the behavior of FormEntryActivity

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
Not required
https://docs.opendatakit.org/collect-install/?highlight=permission

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

Light theme

Dark theme

### CODE REVIEW

**Comment by lognaturel** [comment]
Thanks for looking into this, @shobhitagarwal1612! It would be helpful for the PR to state right away that this is not a targeted fix for #2694 which was a regression from 1.17.1 to 1.18 but rather a rethinking of how the user is prompted for the storage permission. It incidentally does fix #2694 but the changes presented here are not required for the fix.

Luckily, #2694 is pretty unlikely to happen because it will be rare for users to manually revoke permissions so it is ok to leave it unfixed for a bit. If it were a common issue, we should first fix it and then reconsider the structure.

In general, larger changes should be accompanied by some kind of rationale and study. Ideally this happens before a PR is created. I know sometimes it's helpful to try things out in code so in a PR description can possibly be ok too. Questions addressed should be things like 
- what is the overall goal of moving away from the standard dialog approach and how can that best be achieved?
- what do we lose by moving away from the standard dialog approach?
- do any other apps do something like what is suggested here?

I'm going to be out shortly and I think @smoyth and @adamvert would be best positioned to provide process ideas for suggesting such UI changes. @zestyping has also been involved in more review lately and has broad experience with leading software engineering teams to make the best decisions possible. I bet he'd have some good process ideas to help make sure these kinds of changes are made thoughtfully, possibly related to [some suggestions he made on the forum](https://forum.opendatakit.org/t/odk-1-developer-call-2018-10-03/15428/3).

**Comment by shobhitagarwal1612** [comment]
@lognaturel I haven't removed the standard permission dialog. Now it appears when we click on the grant permission button instead of popping up directly. This is the standard approach many applications follow, eg Facebook. I'll attach a gif too to make it more clear

**Comment by lognaturel** [comment]
The behavior of this PR is clear.

The questions are about the motivation behind it and how carefully you considered it. Did you read through https://material.io/design/platform-guidance/android-permissions.html#? Did you consider which recommendation made the most sense? Did you carefully consider what the text of the new activity should include? Did you design the interaction in the case where the dialog is asked not to be shown again?

**EDIT**: to be clear, I think designing a first load experience for Android 6+ that is more carefully considered than immediately seeing the permissions dialog is a good idea. What I am trying to express is that I think it needs to be considered as its own initiative with a clear game plan with reasons to back it up, just like any new feature or UI.

**Comment by zestyping** [comment]
Hi @shobhitagarwal1612, @lognaturel is on leave now and I'm just catching up here—thanks in advance for getting me up to speed.  Can you help me understand what you want to achieve with this change?  You mentioned adding a gif, if that illustrates what you have in mind, that might help.

**Comment by shobhitagarwal1612** [comment]
ezgif com-video-to-gif

**Comment by zestyping** [comment]
I see what you are going for here.  The motivation seems reasonable, i.e. you want to give the user some explanation as to why they are about to get a permission dialog.  I just don't know whether this is the look / experience we want users to get on the first launch of the app.  @yanokwa, would you like to weigh in?

**Comment by smoyte** [comment]
I wonder if we could show this when the user first does something that would obviously require file access, like download forms? Seems that would make the big screen unnecessary since it would make sense to the user given they have just clicked a button relating to "files".

**Comment by admbtlr** [comment]
Looking at the Material Design Platform Guidance docs on permissions as linked by @lognaturel , there is a diagram and this quote:

> Critical permissions should be requested up-front.
>
> Secondary permissions may be requested in-context.

I would argue that access to the filesystem is critical; you just plain can't use ODK Collect unless you grant this permission.

BUT... you have to grant this permission in order to install ODK Collect in the first place, don't you? (Not sure whether this is the case with all Android versions, but it is on my device) So the only way that this situation would arise is if you have - whether accidentally or intentionally - retracted that permission.

Further on in the linked document is a [section on denied/retracted critical permissions](https://material.io/design/platform-guidance/android-permissions.html#denied-permissions), where it states:

> If the app can no longer run because a critical permission has been denied, explain why that permission must be allowed and offer a button to open Settings so the user can allow it.

The illustrative screenshot looks a lot like the screen that @shobhitagarwal1612 has included here, with the one difference that their screenshot links to settings, rather than directly granting the permission: 

image

This seems preferable since, AFAIK, if the user has at some point selected _Don't show this again_, then nothing will happen when they click on the _Grant Permission_ button.

I also think the copy could be a little more direct; maybe switch the phrasing around to match the example:

> In order to download forms and collect data, ODK Collect needs access to photos, media and files on your device. Go to settings to enable these permissions.

**Comment by shobhitagarwal1612** [comment]
> you have to grant this permission in order to install ODK Collect in the first place, don't you? 

From Android 6 onwards, we have to manually provide the permission after the app is installed as well

**Pull request closed without merging**
