### PR TITLE
The user sees success information in notification even if an error occurs

### LINKED ISSUE #2200: The user sees success information in notification even if an error occurs
#### Software and hardware versions 
Collect with #2095

#### Problem description
The user sees success information in notification although error occurred
#### Steps to reproduce the problem
1. The user has selected `Automatic download` in Form Update settings
2. The new version of the form is available but internet connection error occurred during downloading
3. The user sees success information in the notification 
3. The user clicks on notification and sees view with header `Forms downloaded`

| Notification| Error | Error |
|---|---|---|
|screenshot_20180514-124315|screenshot_20180514-123721|screenshot_20180514-124320|

#### Expected behavior
* User sees different text in notification if an error occurs
* User sees different text in the header if an error occurs

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #2200 

#### What has been done to verify that this works as intended?
I've tested the dialog displayed after sending/downloading forms automatically.

#### Why is this the best possible solution? Were any other approaches considered?
I changed dialog titles using the same we use for normal downloading and sending results. Now it's consistent.

#### Are there any risks to merging this code? If so, what are they?
No.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew pmd checkstyle lint findbugs` and confirmed all checks still pass.
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by jd-alexander — COMMENTED** [review]
Looks at the attached issue and the changes you made and this looks good to me!

**Review by lognaturel — DISMISSED** [review]

**Comment by mmarciniak90** [comment]
@grzesiek2010 I like that headers were unified

|screenshot_20180613-141721|screenshot_20180613-142704|screenshot_20180613-143422|screenshot_20180613-141504|
|---|---|---|---|

As I noted in #2200, the user should see information in the notification that error occurred. 
Now, the user always sees `New form versions downloaded`
Also `Auto Send` notification should be unified. The text in the bottom should not be visible.
The header message may be more accurate.

|screenshot_20180613-142658|screenshot_20180613-141908|screenshot_20180613-141455|
|---|---|---|

@opendatakit-bot unlabel "needs testing"

**Review by mmarciniak90 — CHANGES_REQUESTED** [review]
* add a different header for notification if an error occurred during downloading a new form
* remove text in the bottom in `Auto Send` notification

**Comment by grzesiek2010** [comment]
I agree we should remove the text from `Send Notification` and keep only the title. That text is not readable and not needed.

When it comes to the title of `Download Notification` hmmmm....
`ODK Auto Download Notification`? to be consistent.

**Comment by mmarciniak90** [comment]
Using `ODK Auto Download Notification` is a good idea for me. It fits to `ODK Auto Send Notification`.

**Comment by grzesiek2010** [comment]
@lognaturel what do you think?

**Comment by lognaturel** [comment]
Good points, @mmarciniak90. I hadn't thought about the changes to the notification messages themselves.

One other change I'd like to ask for is for the "Download Result" string to become "Download Results" to match "Upload Results".

I think "Notification" is redundant for the title of a notification. How about "ODK auto-send results" and "ODK auto-submission results". I agree with @mmarciniak90 that it would be ideal for the subtext to say something simple like "Success" or "Failure(s)".

**Comment by grzesiek2010** [comment]
> I agree with @mmarciniak90 that it would be ideal for the subtext to say something simple like "Success" or "Failure(s)".

but it might be a mix of `Successes` and `Failures` that's why I would like to remove the subtext at all.

**Comment by lognaturel** [comment]
> but it might be a mix of Successes and Failures

I think what a user generally cares about is whether there was any failure. If all succeeded, I don't really need to see the details. But if there was one or more failures then it's important I go see what's going on.

**Comment by grzesiek2010** [comment]
Ok, I think it's ready for testing.
Notification titles I use:
`ODK auto-send results`
`ODK auto-download results`

Notification messages:
`Success` - if everything is ok
`Failures` - if there is any problem with at least one form.submission

Also, I unified dialogs with `Send results` so @mmarciniak90 please test them all I mean we have three:
*Uploading to GD
*Uploading to aggregate
*Uploading using auto-send

**Comment by grzesiek2010** [comment]
@oendatakit-boot label "needs testing"

**Comment by grzesiek2010** [comment]
@opendatakit-bot label "needs testing"

**Comment by mmarciniak90** [comment]
@grzesiek2010 I see `Failures` message when I send the form with success to Google Sheets
[OnePageFormSubmission.xml.txt](https://github.com/opendatakit/collect/files/2145150/OnePageFormSubmission.xml.txt)

**Comment by grzesiek2010** [comment]
@mmarciniak90 fixed.

**Comment by mmarciniak90** [comment]
Thanks @grzesiek2010 for so quick fix! 

**Tested with success!**

Verified on Android: 4.1, 4.2, 4.4, 5.1, 6.0, 7.0, 8.1
Verified cases:
- download the new version with success and failed
- sent the form with success and failed
- sent to Aggregate
- sent to Google Drive
- sent to Aggregate defined in the form, different than is set in settings
- light / dark theme

|screenshot_20180628-125033|screenshot_20180628-122449|screenshot_20180628-124819|
|---|---|---|

|screenshot_20180628-125039|screenshot_20180628-122509|screenshot_20180628-124831|
|---|---|----|

@opendatakit-bot label "behavior verified"
@opendatakit-bot unlabel "needs testing"

**Review by lognaturel — APPROVED** [review]

**Pull request merged**
