### PR TITLE
Improve view sent form blank text

### LINKED ISSUE #437: Improve View Sent Form blank text
When you tap View Sent Form, it should say something like "Nothing available to display. Try sending finalized forms before viewing."

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Fixes #437

### CODE REVIEW

**Comment by grzesiek2010** [comment]
This is wrong. The string you edited is used in other activities so you can't edit it. You have to add new string and display that string when we are in "View Sent Form" view.

**Comment by shobhitagarwal1612** [comment]
@grzesiek2010 Is it ok now?

**Comment by grzesiek2010** [comment]
No it isn't. You can test this easy: String you added should be visible in View sent form but https://github.com/opendatakit/collect/blob/master/collect_app/src/main/res/values/strings.xml#L108 should be displayed in Edit Saved Form (both activities use InstanceChooserList).

**Comment by lognaturel** [comment]
@shobhitagarwal1612 Let us know if you need some ideas to figure this one out. You might start by taking a look at how the `FORM_MODE` constant is used.

**Comment by shobhitagarwal1612** [comment]
@lognaturel @grzesiek2010 Thanks

**Pull request merged**
