### PR TITLE
Filtering of filled up forms for editing and submission

### PR DESCRIPTION
**Pull request by grzesiek2010**
It's a part of #258

### CODE REVIEW

**Comment by yanokwa** [comment]
@grzesiek2010 I'm pretty sure I've pulled the code, but I can't the filtering UI in Edit Saved Form. Am I missing something?

**Comment by grzesiek2010** [comment]
@yanokwa it should be visible only if you have many items in your list I mean if you can see the scrollbar then you can see an edit text for filtering too https://github.com/opendatakit/collect/pull/362/files#diff-1677ad9b3727e99fd068a02e664eb0c4R175

**Comment by yanokwa** [comment]
@grzesiek2010 I think it'd be more intuitive if there was a search icon on the app bar. Then on pressing it, a search box would appear below to allow live filtering. Tapping the search icon would hide the box.

**Comment by grzesiek2010** [comment]
@yanokwa what do you mean by "search box would appear below"? directly below the search icon? Is the current place wrong?

**Comment by yanokwa** [comment]
The current place below the app bar and taking up the whole width is great. I'd just like to see it appear and disappear when a user taps on a search icon in the app bar.

**Comment by grzesiek2010** [comment]
Ok I see my mistake. I fixed this and sorting too once we merge #444

**Comment by lognaturel** [comment]
Strangely it doesn't show up at all on my Nexus 5 emulator running either API 16 or API 22! It works great on a moto g4 running 6.0.1. That needs to be figured out.

I think that what @yanokwa was suggesting is putting [a search icon](https://material.io/icons/#ic_search) in the app bar next to where the sort icon will be soon. When that is tapped, the text field for search would scroll down into position or perhaps the whole app bar would become a search field. Does that make sense?

Then I think that just like with search, it should be a decorator that can be applied to all views with lists! The only one that might be problematic is the delete one that has the tabs. If you can make the text box for the search be on the app bar then it should work well.

**Comment by grzesiek2010** [comment]
Replaced by #672

**Pull request closed without merging**
