### PR TITLE
Zero-byte stubs for unsupported architectures

### LINKED ISSUE #3097: Reduce size of APK
Historically, the Collect apk has been small (~4MB). Version v1.22.0-beta.1 has grown to 12.3MB. This is likely due to the addition of the Mapbox SDK.  12MB isn't terrible, but for large scale projects it will add up to a lot of time and money.

I'm using `./gradlew clean assembleOdkCollectRelease` to build the APK. The attached screenshot is what the Play Store sees as a difference between v1.22.0-beta.0 and v1.22.0-beta.1.

Screen Shot 2019-05-23 at 4 06 57 PM

Some next steps:

- [X] Size increase is indeed because of Mapbox.
- [X] OSM SDK will reduce size further, but only 1.1%
- [x] Follow the steps at https://docs.mapbox.com/help/troubleshooting/android-apk-size to reduce size

### PR DESCRIPTION
**Pull request by yanokwa**
Closes #3097

#### What has been done to verify that this works as intended?
* File size is 8.3 MB on Mac. It's smaller in the Play Store.
* On armeabi-v7a with no libmapbox-gl.so binaries, there is a crash when I try to load the map. 
* On armeabi-v7a with just the armeabi-v7a libmapbox-gl binary (this PR), it works just fine.
* Play Store shows that this binary works on 5 native platforms (see screenshot below)

#### Why is this the best possible solution? Were any other approaches considered?
This approach is different from Ping's suggestions in #3097 in that I create my own aar with zero byte native binaries, rather than try to remove native binaries while packaging.

This allows us to ship this update to all architectures through the Play Store, but we only really include support for armeabi-v7a (by excluding everything else). The file size increase is minimal because we use zero-byte .so files.

If we could disable the Mapbox option on non-armeabi-v7 instead of crashing, that'd be better.
```
public static boolean isSupportedAbi(String Abi) {
        if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.LOLLIPOP) {
            return Arrays.asList(Build.SUPPORTED_ABIS).contains(Abi.toLowerCase());
        } else {
            return Build.CPU_ABI.equalsIgnoreCase(Abi);
        }
    }
```

#### Other
How I made nbi-stubs.
```
rm -rf nbi-stubs*
mkdir -p nbi-stubs/jni/arm64-v8a/;
mkdir -p nbi-stubs/jni/armeabi-v7a/;
mkdir -p nbi-stubs/jni/armeabi/;
mkdir -p nbi-stubs/jni/x86/;
mkdir -p nbi-stubs/jni/x86_64/;
touch nbi-stubs/jni/arm64-v8a/stub.so;
touch nbi-stubs/jni/armeabi-v7a/stub.so;
touch nbi-stubs/jni/armeabi/stub.so;
touch nbi-stubs/jni/x86/stub.so;
touch nbi-stubs/jni/x86_64/stub.so;
cd nbi-stubs;
zip -r ../nbi-stubs-1.0.0.aar *
cd .. 
rm -rf nbi-stubs/;
```

Play Store screenshots

**v1.22.0-beta.1**
Screen Shot 2019-05-28 at 2 23 44 PM

**this PR**
Screen Shot 2019-05-28 at 2 23 38 PM

### CODE REVIEW

**Comment by zestyping** [comment]
Nicely done!

**Comment by lognaturel** [comment]
@yanokwa This looks good to me. How do you want this to proceed? There's no real QA to do I don't think.

> If we could disable the Mapbox option on non-armeabi-v7 instead of crashing, that'd be better.

Do you want someone to do this for this release? Next release?

**Comment by zestyping** [comment]
A note on how to do this—

Instead of examining various system parameters (CPU_ABI, CPU_ABI2, SUPPORTED_ABIS, SUPPORTED_32_BIT_ABIS, SUPPORTED_64_BIT_ABIS) to guess whether the device supports any of the included binaries, I recommend wrapping the `Mapbox.getInstance()` call in a `try` block and catching `ExceptionInInitializerError`.  This approach is simpler, more bulletproof (the code doesn't have to change depending on which binaries are included in the APK), and truer to reality (it just works if it works).

**Comment by yanokwa** [comment]
@zestyping If you think https://github.com/opendatakit/collect/issues/3115 (gracefully failing) is fast to do and you have the cycles, please take a crack at it. We have some PRs that are still undergoing testing for this release so we probably have 24ish hours.

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
So to confirm -- we merge this now and then if one of us can get #3115 in by the end of the day, great, but it's not a big deal if not?

**Comment by yanokwa** [comment]
Confirmed.

**Pull request merged**
