### PR TITLE
Sorting of filled up forms for editing and submission

### PR DESCRIPTION
**Pull request by grzesiek2010**
It's a part of #258

### CODE REVIEW

**Comment by lognaturel** [comment]
Sorry if I wasn't clear, can you please make the search part a separate branch/PR? That will keep the master branch history cleaner and make reviewing easier. 😊 

I'm going to leave the sort part aside for now. The interface looks great. That said, I'd like to get clarity on #293 before we do anything with it since it currently crashes for <API 11.

**Comment by grzesiek2010** [comment]
Ohh yes you were clear. Don't know why that commit is here (probably I added that yesterday evening and I was tired). I'll fix this. My bad.

**Comment by yanokwa** [comment]
I love how this turned out! I'd like to see a couple of changes...
* The icon before ODK Collect looks like it's been indented. 
* I think the sort icon should aways be there. UI elements that come and go are a confusing.
* In the filter view, there should be a little bit more padding on the left. Let's match the space on the top and bottom. 

How does this look on a small screen device? Can you scroll through the list of sort options?

**Comment by grzesiek2010** [comment]
I added some changes and now the sort icon is always visible as you required. I added padding on the left as well and I can confirm that this list is scrolable.

I'm not sure what you mean by "The icon before ODK Collect looks like it's been indented" because I didn't notice any strange behaviour.

Generally I think it's ok and ready to merge but then we have to make a decision: now this feature is available only in "Edit Saved Form" as described in the issue but "View Sent Form" uses the same class (InstanceChooserList) that makes this class big and messy so I think we have two options. We can separate these two views (create spearate class for "View Sent Form") or we can add the same feature to "View Sent Form" as well because now there are lots of lines that "View Sent Form" doesn't use and it isn't ok to me.

What do you think @yanokwa @lognaturel ?

**Comment by lognaturel** [comment]
Wow, no merge conflicts! This is looking great. I think it should actually go everywhere that there is a list of forms. Some of the activities like Send Finalized Form have a three dots menu to get to settings but that's not really needed so you can remove it. I think a good structure would be something like introducing a new decorator classes which is applied to @dcbriccetti's new `AppListActivity` class. That will keep all the related behavior grouped together and give you a way to apply it to all lists. Let us know if you want to talk more about structure.

**Comment by lognaturel** [comment]
Replaced by #525

**Pull request closed without merging**
