### PR TITLE
Improvements to web auth

### PR DESCRIPTION
**Pull request by max2me**
**Changes from master (re: #48):**
* Automatically use stored credentials
* If stored credentials are invalid and "Enter new credentials" dialog is shown, update stored credentials with those values
* Some refactoring
* Credentials dialog no longer shows URL that we are connecting to (not sure if this is a big deal or not, removing it in the code made things a little easier and dialog from UX perspective cleaner -- lmk if I should bring it back, it's rather trivial).

**Testing environment**
https://opendatakittrial.appspot.com / admin / aggregate

**Tested scenarios**
* Connecting to env that requires credentials when none are set.  
Result: dialog is shown
* Connecting to env that requires credentials when none or invalid credentials are set and entering new ones.  
Result: Entered credentials are updated in preferences (regardless whether they are valid or not).
* Updating username/password by going to General Settings &rarr; Configure platform settings.
Result: new username/password are applied to all requests right away.
* [BUG] Updating username/password by going to General Settings and changing username/password there.  
Result: Requires app restart for those changes to take effect on web requests.

### CODE REVIEW

**Comment by lognaturel** [comment]
The refactoring and actually updating saved credentials look great. I do think it's important to have the server in the auth dialog because a single user could have several servers she routinely connects to and not knowing which one is currently configured would be confusing.

It looks like this doesn't address an important improvement from #48:
- Enter https://opendatakittrial.appspot.com / admin / aggregate in the `Configure platform settings menu`
- Go to `Get Blank Form`
- The credentials should automatically be sent without showing the `Server Requires Authentication` dialog

**Comment by max2me** [comment]
@lognaturel I can confirm that this issue is happening. 

Interestingly enough even though same code is used for adding credentials to credentials provider, it works right after app restarts but not if you change credentials and then attempt to retrieve something without restarting the app. I spent some time digging into it today but didnt find a smoking gun. I'll continue investigation tomorrow.

**Comment by max2me** [comment]
ZOMG. The depths I went in fixing this while all I had to do was to apply new credentials upon leaving activity instead of doing it right away. It was starring at me the whole time >.<

@lognaturel Please take a look.

**Comment by lognaturel** [comment]
So annoying, sorry!! But thanks so much for hunting down the issue. 🎉

**Pull request merged**
