### PR TITLE
Use darker colors for dark theme

### PR DESCRIPTION
**Pull request by seadowg**
This makes the dark theme colors darker. @alyblenkin and I paired on these changes after I decided I didn't like the new (Material 3) dark theme once I'd seen it on an actual device.

### CODE REVIEW

**Comment by alyblenkin** [comment]
Hey @seadowg the colours that we picked yesterday are looking a lot better. I think the dialog still feels off, but it might be because the main menu buttons are too grey. We can always come back to this and try a different button colour, like using this colour [#374955](https://www.figma.com/file/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?type=design&node-id=3905%3A13700&mode=design&t=DRIKMdbFNrGuQ440-1) instead.

**Comment by seadowg** [comment]
> I think the dialog still feels off, but it might be because the main menu buttons are too grey. We can always come back to this and try a different button colour, like using this colour [#374955](https://www.figma.com/file/KFi9hIQdrRgo0rLqIC7Sg8/ODK-user-flows?type=design&node-id=3905%3A13700&mode=design&t=DRIKMdbFNrGuQ440-1) instead.

Let's come back to this. The color we actual set isn't the one we end up with due to it being placed transparently on top of our surface color, so we'll have to play around with it to get it just right.

If you approve, I can go ahead and merge!

**Comment by alyblenkin** [comment]
@seadowg sounds good! The build isn't showing up - could you run it again?

**Comment by seadowg** [comment]
@alyblenkin done!

**Review by alyblenkin — APPROVED** [review]

**Pull request merged**
