### PR TITLE
Update copy on end screen

### LINKED ISSUE #5948: Update copy on end screen
We are updating the end screen message to make it more scanable and adding the link to the forum so users can learn more.

### Updated copy

**Finalized forms are not editable.**

If you need to make edits to your form, “Save as draft” until you’re ready to send. [Learn more](https://forum.getodk.org/t/finalized-forms-will-not-be-editable-starting-in-collect-v2024-1/42007)

Image

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5948

#### Why is this the best possible solution? Were any other approaches considered?
As in the issue:
> We are updating the end screen message to make it more scanable and adding the link to the forum so users can learn more.

| Auto send disabled | Auto send enabled | Saving as draft disabled |
| ------------- | ------------- | ------------- |
| Screenshot_1707487269 | Screenshot_1707487286 | !Screenshot_1707487356 |

When it comes to the implementation there is nothing to discuss.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
The only think we need to test is the end screen in a form to make sure the new warning contains correct title and message depending on the state. Please also test the link that should open the forum thread.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by alyblenkin** [comment]
Woo, that looks good! Could we make the "Learn more" section the same font-weight as the first line, "Sent forms are not editable? " In the screengrabs above, they look the same weight, but on the device it seems bolder. I could be wrong. 

An optional minor tweak would be to increase the padding around the message. I don't know if people would notice, but if they click the forum link, the mockup looks slightly different. This isn't a deal breaker- we can return to it later.

image

**Comment by grzesiek2010** [comment]
> Could we make the "Learn more" section the same font-weight as the first line, "Sent forms are not editable? " In the screengrabs above, they look the same weight, but on the device it seems bolder. I could be wrong.

Done.

> An optional minor tweak would be to increase the padding around the message. I don't know if people would notice, but if they click the forum link, the mockup looks slightly different. This isn't a deal breaker- we can return to it later.

I've increased the vertical padding. I think now it looks closer to the mockup.

**Review by alyblenkin — APPROVED** [review]

**Review by seadowg — APPROVED** [review]

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on device with Android 10

**Verified cases:**
- end screen changes according to #5948
- end screen in Start new form and Drafts
- all auto send options
- Form entry settings with save as draft and finalize
- form with auto send set to true or false
- light and dark mode
- landscape and portrait view

**Comment by srujner** [comment]
Tested with Success!

Verified on device with Android 13

**Pull request merged**
