### PR TITLE
Fixes bug : 'Go Up' option looks like an active button

### LINKED ISSUE #1156: 'Go Up' option looks like an active button
#### Software and hardware versions 
Collect - current master
Android 5.0
Android 6.0

#### Problem description
'Go Up' option looks like an active button. The same background colour is visible. Buttons differ only by frame.

#### Steps to reproduce the problem
1. User starts form
2. User clicks on 'Go To Prompt' icon
3. 'Go Up' button looks like an active
master

#### Expected behavior
Button is grey which shows that is inactive

#### Other information 
Regression. Button looks like expected on v1.7.1

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
In reference to resolve #1156

### CODE REVIEW

**Comment by lognaturel** [comment]
Unfortunately, it's a bit more complicated than that! By changing the theme color, all question titles and hints are now gray. 

I think you had to make this kind of change for some widget buttons, too. Play audio and video if I remember correctly. Might be good to use a similar solution for this.

**Comment by shobhitagarwal1612** [comment]
@lognaturel Done

**Comment by lognaturel** [comment]
Let's keep the hint text black (below the question name). Other than that, looks good. 

It will be interesting to merge these changes into `ui-refresh`.

**Comment by shobhitagarwal1612** [comment]
Currently, it's headed to be merged into `master`. Should I change it to `ui-refresh`?

**Pull request merged**
