### PR TITLE
Add test runs and regression risks to PR template

### PR DESCRIPTION
**Pull request by lognaturel**
Related to #2295 

#### What has been done to verify that this works as intended?
It's a text-only change so I manually looked at the diff.

#### Why is this the best possible solution? Were any other approaches considered?
The first commit adds instructions for running tests. Running all the checks and tests locally can take a long time so I also added the option to wait for CI to finish and only run the connected tests locally since those will NOT be run on CI for a PR.

The second commit tries to synthesize the discussion at #2295 and pull everyone's ideas in. 

@grzesiek2010 rightfully suggests that PR descriptions contain more information about what specific behavior should be verified.

@ggalmazor makes the point that what makes manual QA so powerful is that the person doing it is not the same person who wrote the code and they come up with test cases through exploration. The important thing is for the QA to know what areas of behavior are affected and **which are intentional**. 

Where we've had problems in the past was with larger PRs that resulted in many different changes, some carefully considered and others that turned out to be unintentional side effects. If folks doing verification at least know what code has changed, they are more likely to identify unintended changes.

I've personally been filling this kind of information out in the risks section but that has not been common practice. I hope the new wording addresses all of our concerns.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
In this case, the users of the template are developers who submit pull requests. This change intends to guide those developers to provide more information on intended results of their code change and possible unexpected side effects. It also intends to help make sure we don't merge changes that break the connected tests.

This does add some complexity to the template so a risk is that developers stop filling it out with care.

#### Do we need any specific form for testing your changes? If so, please attach one.
No

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew pmd checkstyle lintDebug spotbugsDebug` and confirmed all checks still pass.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by jd-alexander** [comment]
I really like this @lognaturel Question, what do you think about having a sample of a really good PR description especially for the regression area. I think that would help new contributors who are probably new to have an actuall example. Well, some PRs are going to be sent in soon when this template is added so probably one could be quoted. Just a thought.

**Comment by lognaturel** [comment]
Good idea, @jd-alexander. We can add it to the contributor guide once we have some good examples.

**Comment by grzesiek2010** [comment]
Generally, I like this change. Could you explain to me why we don't run android tests on CircleCi. is it because of the time that would need?

**Comment by lognaturel** [comment]
> Could you explain to me why we don't run android tests on CircleCi. is it because of the time that would need?

It's actually because we run them on Firebase Test Lab and [each run costs](https://firebase.google.com/pricing/). Limiting runs to master keeps that under control. If someone has a contact in the Firebase team at Google, we could likely get an in-kind donation of test time that would allow for running them on every commit.

**Review by grzesiek2010 — APPROVED** [review]

**Comment by lognaturel** [comment]
Thanks for the good question, @grzesiek2010. I've made a note to add that explanation somewhere (maybe a comment in the Circle CI config?) because it's the kind of thing we're going to forget.

@ggalmazor, does this capture what you're after?

**Comment by ggalmazor** [comment]
Yeah, I think this would help me remember that I need to write that information on each PR :)

**Pull request merged**
