### PR TITLE
Dark theme is not applied to the main menu when user load settings from collect.settings file

### LINKED ISSUE #2244: Dark theme is not applied to the main menu when user load settings from collect.settings file
#### Software and hardware versions 
Collect master

#### Problem description
Dark theme is not applied to the main menu when user load settings from collect.settings file

#### Steps to reproduce the problem
1. The user puts [collect.settings.txt](https://github.com/opendatakit/collect/files/2038789/collect.settings.txt) file to odk directory
2. The user opens Collect app
3. The user sees the main menu in light mode but other views in dark mode
4. Dark mode is applied to the main menu after reopening the app

#### Expected behavior
Dark mode to the main menu is applied immediately after loading a collect.settings file

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #2244 

#### What has been done to verify that this works as intended?
I've tested the attached settings file.

#### Why is this the best possible solution? Were any other approaches considered?
The activity should be recreated after loading new settings.

#### Are there any risks to merging this code? If so, what are they?
No.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew pmd checkstyle lint findbugs` and confirmed all checks still pass.
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by andreimarcut — COMMENTED** [review]
Looks like a full forced activity refresh, which would indeed resolve the issue. But could there be a better way?
Also, although unrelated to the code changes, I think taking the opportunity to rename the "j" and "f" arguments into something more meaningful would also improve the code quality.

**Review by andreimarcut — APPROVED** [review]

**Comment by grzesiek2010** [comment]
> Looks like a full forced activity refresh, which would indeed resolve the issue. But could there be a better way?

I doubt it's a better solution here we just need to do that.

> Also, although unrelated to the code changes, I think taking the opportunity to rename the "j" and "f" arguments into something more meaningful would also improve the code quality.

you can do that in a separate pr if you want.

**Comment by lognaturel** [comment]
Thanks for the review, @andreimarcut! I'm not really coming up with great alternatives to reloading the activity. Did you have any to suggest?

**Comment by mmarciniak90** [comment]
**Tested with success!**

Verified on Android: 4.1, 4.2, 4.4, 5.1, 6.0, 7.0
Verified cases:
* adding collect.settings file
* scaning QR code

@opendatakit-bot label "behavior verified"
@opendatakit-bot unlabel "needs testing"

**Review by lognaturel — APPROVED** [review]

**Pull request merged**
