### PR TITLE
Fixed reading files from Downloads dir.

### LINKED ISSUE #2921: NumberFormatException For input string: "raw:/storage/emulated/0/Download/2019-2-25_93844.pdf"
#### Software and hardware versions 
Collect v1.19.0 and older versions, Android v8

#### Problem description
https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/5c5c0cc4f8b88c2963f9e201?time=last-seven-days&sessionId=5C71587F0161000173CC218A39811ED4_DNE_1_v2

`Caused by java.lang.NumberFormatException
For input string: "raw:/storage/emulated/0/Download/carl.jpg"
keyboard_arrow_up
java.lang.Long.parseLong (Long.java:590)
arrow_drop_down
java.lang.Long.parseLong (Long.java:632)
arrow_right
org.odk.collect.android.utilities.MediaUtils.getPath (MediaUtils.java:484)
org.odk.collect.android.utilities.MediaUtils.getPathFromUri (MediaUtils.java:419)
org.odk.collect.android.utilities.MediaUtils.getFileFromUri (MediaUtils.java:527)
org.odk.collect.android.tasks.MediaLoadingTask.doInBackground (MediaLoadingTask.java:60)
org.odk.collect.android.tasks.MediaLoadingTask.doInBackground (MediaLoadingTask.java:30)`

### LINKED ISSUE #2923: Caused by java.lang.IllegalArgumentException Unknown URI: content://downloads/public_downloads/4893
#### Software and hardware versions 
Collect v1.19.0 and older versions Android v7 and v8

#### Problem description
https://console.firebase.google.com/u/0/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/5c62ffc1f8b88c296394b606?time=last-seven-days&sessionId=5C74A35F02AF00014F92DC6C2D5DF87C_DNE_0_v2

Caused by java.lang.IllegalArgumentException
Unknown URI: content://downloads/public_downloads/4893
keyboard_arrow_up
android.database.DatabaseUtils.readExceptionFromParcel (DatabaseUtils.java:165)
arrow_drop_down
android.content.ContentResolver.query (ContentResolver.java:476)
arrow_right
org.odk.collect.android.utilities.MediaUtils.getDataColumn (MediaUtils.java:637)
org.odk.collect.android.utilities.MediaUtils.getPath (MediaUtils.java:486)
org.odk.collect.android.utilities.MediaUtils.getPathFromUri (MediaUtils.java:419)
org.odk.collect.android.utilities.MediaUtils.getFileFromUri (MediaUtils.java:527)
org.odk.collect.android.tasks.MediaLoadingTask.doInBackground (MediaLoadingTask.java:60)
org.odk.collect.android.tasks.MediaLoadingTask.doInBackground (MediaLoadingTask.java:30)

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #2921, Closes #2923 

The pr contains fixes for two bugs. They are interrelated so I decided to create just one pr in order to facilitate testing. 

#2921 fixed in the first commit
#2923 fixed in the second commit

#### What has been done to verify that this works as intended?
#2921 I was able to reproduce the issue so I just confirmed that the fix works.
#2923 I wasn't able to reproduce the issue so I asked the user who reported it to help, he confirmed it works: https://forum.opendatakit.org/t/file-question-failure/18100

#### Why is this the best possible solution? Were any other approaches considered?
Both fixes are based on what I found on StackOverflow:
https://stackoverflow.com/questions/46442064/java-io-filenotfoundexception-caught-when-processing-request-document-raw-sto
https://stackoverflow.com/questions/52591936/i-am-getting-illegalargumentexception-during-picking-a-document-file-from-downlo

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
The change is just related to reading/attaching files from `Downloads` dir, so we can test just that functionality.
As I said we are able to reproduce the first issue #2921 and it's not a risky change.
The second commit implements changes that are used only when the original approach fails so despite the fact we are not able to reproduce it I think it's pretty safe.

#### Do we need any specific form for testing your changes? If so, please attach one.
Any form with the `FIleWIdget`.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/opendatakit/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [ ] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [ ] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [ ] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by shobhitagarwal1612** [comment]
I noticed this warning in my logcat.

```
org.odk.collect.android W/MediaUtils: java.lang.IllegalArgumentException: Unknown URI: content://downloads/public_downloads/8433
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:165)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
        at android.content.ContentResolver.query(ContentResolver.java:532)
        at android.content.ContentResolver.query(ContentResolver.java:473)
        at org.odk.collect.android.utilities.MediaUtils.getDataColumn(MediaUtils.java:671)
        at org.odk.collect.android.utilities.MediaUtils.getPath(MediaUtils.java:500)
        at org.odk.collect.android.utilities.MediaUtils.getPathFromUri(MediaUtils.java:424)
        at org.odk.collect.android.utilities.MediaUtils.getFileFromUri(MediaUtils.java:561)
        at org.odk.collect.android.tasks.MediaLoadingTask.doInBackground(MediaLoadingTask.java:59)
        at org.odk.collect.android.tasks.MediaLoadingTask.doInBackground(MediaLoadingTask.java:29)
        at android.os.AsyncTask$2.call(AsyncTask.java:304)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:760)
org.odk.collect.android I/FormEntryActivity: Created view for group Media widgets File widget
org.odk.collect.android W/MediaUtils: java.lang.SecurityException: Permission Denial: reading com.android.providers.downloads.DownloadProvider uri content://downloads/all_downloads/8433 from pid=25704, uid=11023 requires android.permission.ACCESS_ALL_DOWNLOADS, or grantUriPermission()
        at android.os.Parcel.readException(Parcel.java:1715)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
        at android.content.ContentResolver.query(ContentResolver.java:532)
        at android.content.ContentResolver.query(ContentResolver.java:473)
        at org.odk.collect.android.utilities.MediaUtils.getDataColumn(MediaUtils.java:671)
        at org.odk.collect.android.utilities.MediaUtils.getPath(MediaUtils.java:500)
        at org.odk.collect.android.utilities.MediaUtils.getPathFromUri(MediaUtils.java:424)
        at org.odk.collect.android.utilities.MediaUtils.getFileFromUri(MediaUtils.java:561)
        at org.odk.collect.android.tasks.MediaLoadingTask.doInBackground(MediaLoadingTask.java:59)
        at org.odk.collect.android.tasks.MediaLoadingTask.doInBackground(MediaLoadingTask.java:29)
        at android.os.AsyncTask$2.call(AsyncTask.java:304)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:760)

```

**Comment by grzesiek2010** [comment]
@shobhitagarwal1612 
you mean you get that crash on this branch but on master it works well?

**Comment by shobhitagarwal1612** [comment]
I haven't compared with master branch. Will check again

**Comment by grzesiek2010** [comment]
Ohh you said "a warning" does that mean it works but you can see a warning? If so it's ok because that means you should be able to reproduce the bug using master branch on your device and this pr fixes the issue.
I wasn't able to reproduce the issue so I asked a user to check the solution but if you are able it's great because you can confirm.

**Comment by shobhitagarwal1612** [comment]
But ideally seeing such a warning means something isn't right, correct?

**Comment by grzesiek2010** [comment]
Ok, I changed Timber.w -> Timber.i so it won't be a warning anymore. Please test the behavior comparing to master.

**Review by shobhitagarwal1612 — APPROVED** [review]

**Comment by mmarciniak90** [comment]
**Tested with success**

I was able to reproduce the crash on Android 8.1.
I checked the same files on apk with fix and crash did not occur.
I checked also other file types to check possible regression on Android 8.1, 7.0, 6.0, 4.4.

Attached file types from Downloads dir:
* docs: rtf, txt, xlsx, xml, csv, xls, docx
* videos: 3gp, mp4
* audios: amr, ogg, mp3
* images: png, gif, jpg, jpeg
* others: rar, zip

@opendatakit-bot unlabel "needs testing"
@opendatakit-bot label "behavior verified"

**Pull request merged**
