### PR TITLE
Add AMR recordings

### LINKED ISSUE #4217: Can make voice only recordings
Based on spec: https://forum.getodk.org/t/form-spec-proposal-configure-audio-quality-for-internal-recording/31094

**Acceptance**

- [x] Given I'm using a form with an audio question with `audio-quality` as `voice-only`
When I make a recording with that question
And I submit the form somewhere
Then the audio file for the recording is a `.amr`

- [x] Given I'm using a form with an audio question with `audio-quality` as `normal` (or `foo`)
When I make a recording with that question
And I submit the form somewhere
Then the audio file for the recording is a `.m4a`

### PR DESCRIPTION
**Pull request by seadowg**
Closes #4217 
~~Blocked by #4220~~

#### What has been done to verify that this works as intended?

New tests and verified manually.

#### Why is this the best possible solution? Were any other approaches considered?

Didn't need to add much here. I'm not 100% confident we're leaving the door open for someone to add a codec not supported by `MediaRecorder` but my theory is that this could be done with an alternative implementation of `MediaRecorderWrapper`. I think what we have is good for now.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Good just to check we get the right files out based on the right forms.

#### Before submitting this PR, please make sure you have:
- [x] run `./gradlew checkAll` and confirmed all checks still pass OR confirm CircleCI build passes and run `./gradlew connectedDebugAndroidTest` locally.
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/CONTRIBUTING.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by lognaturel — APPROVED** [review]

**Comment by mmarciniak90** [comment]
@seadowg I've noticed one interesting case, please confirm if it's correct and planned

1. `Use external app for audio recording` is SELECTED
2. User starts a form with audio widget **with quality defined** [AllQ4222AudioQuality.xml.txt](https://github.com/getodk/collect/files/5598556/AllQ4222AudioQuality.xml.txt)
3. User tries to record sound -> **internal recorder is opened** (audio 1 and audio2 in the attached form)
4. User tries to record sound for widget where **quality is not defined** -> **external recorder is opened**

In conclusion, if the quality is defined in form, the internal recorder is used even if using an external app is set. Is it correct?

---

Verified on Android versions: 7.0, 8.1, 10.0

Verified cases:
- quality="voice-only" defined -> amr file is visible 
- quality="normal" defined -> m4a file is visible 
- quality="foo" defined -> m4a file is visible 
- no quality definition -> m4a file is visible
- five-minute sounds have been recorded for each setting -> 
Screenshot_20201125-181152
- a few audio widgets with a different quality set on field-list
- removed response
- hierarchy view with correct audio types
- send a submission to Central
- attached mp3 file

**Comment by kkrawczyk123** [comment]
@seadowg I have also verified on Android 5.1, 7.1 and 9.0 and I do not have any other concerns than @mmarciniak90 has already mentioned above. Could you please respond? I am not sure if it's ready for the label.

**Comment by lognaturel** [comment]
Your cases and experiences look good to me! In general, settings in forms should always override Collect settings.

**Comment by mmarciniak90** [comment]
> settings in forms should always override Collect settings

@lognaturel, thanks for the clarification

@getodk-bot unlabel "needs testing"
@getodk-bot label "behavior verified"

**Pull request merged**
