### PR TITLE
Add account in settings, not just at form upload

### LINKED ISSUE #1386: Add account in settings, not just at form upload
#### Software version
Collect v1.91

#### Problem description

In **General Settings -> Server -> Google Sheets settings**, you can select an existing Google account, or *no account*.

In **Get Blank Forms** you can select an existing Google account, or *Add Account*.

I imagine it would make more sense to be able to add an account in the Server settings screen.

### PR DESCRIPTION
**Pull request by akshay-ap**
Closes #1386 

#### What has been done to verify that this works as intended?
Tested on "Moto m" (android 7.0).
#### Are there any risks to merging this code? If so, what are they?
Changes in Google Account selection might affect the account selection procedure here.
#### Do we need any specific form for testing your changes? If so, please attach one.
No.

### CODE REVIEW

**Comment by lognaturel** [comment]
Thank you, @akshay-ap!

For something like this I would say the risk is disabling the feature that's being modified or in this case, Google Account selection.

**Comment by akshay-ap** [comment]
@lognaturel Are there any tests to be written for this? Or just manual testing is sufficient? If yes, I can try some expresso/roboelectric tests.

**Comment by mmarciniak90** [comment]
Tested with success.
I verified fix on Android 4.1, 4.2, 4.4, 5.1, 6.0, 7.0, 8.0

| Dialog before fix | Dialog on Get Blank Form view | Dialog after fix |
| ------------- | ------------- | ------------- |
| before |  getblankform | after |

@opendatakit-bot unlabel "needs testing"

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
Thanks, @akshay-ap. 

It's always best to have automated tests where we can. In this case, verifying that when the account preference is tapped the dialog shows up and has the "Add Account" option would be great. Since @mmarciniak90 has already done a thorough manual check I've merged this but another PR with the test would be much appreciated! 

I've also filed #1626 for changing the dialog theme.

**Pull request merged**
