### PR TITLE
Fixed memory leaks in form-filling 

### LINKED ISSUE #5976: Leaks In the ODK after the screen rotation
#### ODK Collect version
master: f20b15e8337a7e8440ae7600da3b803a5dbad8dc
#### Android version
10,13,14
#### Device used
Xiaomi Redmi 9T, Google Pixel 6a,7a
#### Problem description
Leak was found after the screen rotation

**Steps to reproduce:**

1. Open All widgets form to the first question.
2. Rotate the device.

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5976 

#### Why is this the best possible solution? Were any other approaches considered?
The first problem I was able to reproduce was building `SavepointsRepositoryProvider` and passing activity as a context. `SavepointsRepositoryProvider` similar to other database repository providers needs a context but it should be the application one instead.

Another problem was passing data to `BackgroundLocationHelper`. Here instead of using lambda functions to pass the form controller we should pass `formSessionRepository` and `sessionId` to let `BackgroundLocationHelper` get the form controller when it needs it similar to what other objects constructed in `FormEntryViewModelFactory` do.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Please make sure the leaks do not occur anymore. Additionally, it would be good to test background audio recordings briefly (just to check if it works with no crashes) as the code related to this functionality has been updated. 
There might be other leaks caused by device rotation but I was able to reproduce only the two described above. If there is something more you can still see please let me know.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] added any new strings with date formatting to `DateFormatsTest`
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by seadowg — APPROVED** [review]

**Comment by WKobus** [comment]
There is leak in select one and multi questions with minimal appearance when rotating device

1. Open all question types form
2. Go to select one minimal question
3. Tap on select answer
4. Rotate device few times until leak occurs

**Comment by grzesiek2010** [comment]
> There is leak in select one and multi questions with minimal appearance when rotating device

Please file a separate issue for that if it's a leak caused by a particular question type.

**Comment by WKobus** [comment]
**Tested with Success**

Verified on device with Android 14

**Verified Cases:**
- Issue #5976 does not occur
- Forms with background audio
- Check for leaks in all question type form
- Big forms
- Rotating device

**Comment by dbemke** [comment]
**Tested with Success**

Verified on device with Android 10

**Pull request merged**
