### PR TITLE
Update geo button language so the defaults are user-friendly

### LINKED ISSUE #5930: Update geo button language so the defaults are user-friendly
### **Problem**

We want to make geo language/ functionality easier to understand for new users while not confusing existing users. 

### **Solution**

**Language update** 

States | Start Geopoint | Start Geopoint with map | Start Geotrace | Start Geoshape
-- | -- | -- | -- | --
If there is no answer | Get point | Get point | Get line | Get polygon
If there are answers added | Change point | View or change point | View or change line | View or change polygon
Read only | | View point | View line | View polygon

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5930 

#### Why is this the best possible solution? Were any other approaches considered?
There is nothing important to discuss when it comes to the implementation. 

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
As described in the issue, this pr updates the buttons used by geo questions by updating the language. Please keep in mind that the buttons can have different titles depending on the state of a question (no answer vs answer, read-only).

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Comment by grzesiek2010** [comment]
@alyblenkin should the icons be bigger maybe? What do you think?
Screenshot_1710374213
Screenshot_1710374214
Screenshot_1710374216

**Comment by alyblenkin** [comment]
@grzesiek2010 - They do look a little small compared to the other icons. Are they the same size as the icons in the Save form dialog? It might be the filled button making them look smaller. 

The location icon is okay because it has a filled component, but the other ones are purely outlines, which makes them appear smaller on a device.

**Comment by grzesiek2010** [comment]
> They do look a little small compared to the other icons. Are they the same size as the icons in the Save form dialog? It might be the filled button making them look smaller.

yes, the size is the same because material buttons limit the size of icons to 20dp.

> The location icon is okay because it has a filled component, but the other ones are purely outlines, which makes them appear smaller on a device.

There are no filled versions of those icons available in https://www.svgrepo.com/vectors/

**Comment by alyblenkin** [comment]
> yes, the size is the same because material buttons limit the size of icons to 20dp.

I figured so! Would you prefer to keep all icons the same size so they're easier to update? I think increasing them would make them easier to see on a device, like increasing the polyline and polygon icon to 24dp.

> There are no filled versions of those icons available in https://www.svgrepo.com/vectors/

Yes, that's correct! It's one of those icons that will appear smaller because of the shape.

**Comment by grzesiek2010** [comment]
> Would you prefer to keep all icons the same size so they're easier to update? I think increasing them would make them easier to see on a device, like increasing the polyline and polygon icon to 24dp.

Let's maybe wait for adding icons to other buttons as well and then decide. We could update the style used by those buttons and increase the size but this would make all the icons bigger not only those outlined. I'm not sure if it's ok. On the other hand, using different icon sizes in different question types does not sound good either.

**Comment by alyblenkin** [comment]
> Let's maybe wait for adding icons to other buttons as well and then decide. We could update the style used by those buttons and increase the size but this would make all the icons bigger not only those outlined. I'm not sure if it's ok. On the other hand, using different icon sizes in different question types does not sound good either.

We certainly don't want to make all the icons bigger, and I can see how using different icon sizes for different question types would make things more complicated. So let's keep them at 20dp because the current size works well across the app.

**Comment by grzesiek2010** [comment]
I've converted this pr into a draft since there is a discussion on the forum about the language see: https://forum.getodk.org/t/making-collect-s-geo-buttons-more-user-friendly/45780.
I've added icons to the geo questions along with icons for all the other types of questions in https://github.com/getodk/collect/pull/6018 so this pr will be only about language.

**Comment by alyblenkin** [comment]
I've updated the [google sheet ](https://docs.google.com/spreadsheets/d/1wxC5Uz5WaMsGI6pMMpDuhXQPWBJyjqlVtsnyNGgSjHw/edit#gid=618642060)with the new geo button language for the different states based on the forum feedback. 

I think we could use either "Add" or "Get" when there isn't an answer. I prefer "add" because the actions are very clear (add, view, or change). Let me know if you disagree, @lognaturel. 


States | "Start Geopoint" button language | "Start Geotrace" button language | "Start Geoshape" button language
-- | -- | -- | --
If no answer | Add point | Add line | Add polygon
If there are answers added | Change point | View or change line | View or change polygon
Read only | View point | View line | View polygon

**Comment by lognaturel** [comment]
🤷🏻‍♀️ "Get" feels easier to use consistently across other media types but I don't feel strongly. "Add" makes me wonder "add to what?" The form, I guess?

Regardless, we need to be very explicit in the translator notes that translators should think about what makes sense for their language. Something like:

> Button text when a question that gets the current device location is blank. Use the most common word for a geographic point in your language, considering options like "location." The verb should be short and action-oriented. Consider "get",  "add" or "capture".

I doubt that a literal translation will work in many languages.

**Comment by alyblenkin** [comment]
> 🤷🏻‍♀️ "Get" feels easier to use consistently across other media types but I don't feel strongly. "Add" makes me wonder "add to what?" The form, I guess?

"Get" is more consistent with the other media types, but I've often thought that "Add barcode" or "Add fingerprint" to the form also works. 

I thought about it this weekend, and considering the other geo language changes, maybe the safest bet right now is to stick with "Get." It might also be easier for translations, seeing we are using it elsewhere. We can come back and revise later. I'll update the Google sheet. 

Update: if you have geopoint question (without a map) and there is an answer you can not view that answer after clicking on the button. The button will start new location searching. If it has a map you can "view or change" point.

**Review by alyblenkin — APPROVED** [review]
Everything aligns with the new language 
Screenshot 2024-04-09 at 9 13 51 AM

**Review by seadowg — APPROVED** [review]

**Comment by WKobus** [comment]
**Tested with Success!**

Verified on device with Android: 11

**Verified cases:**

- Check on Geo questions with different states
- RTL language
- Light and dark mode
- Different fonts size
- Rotating device

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on devices with Android: 10,14

**Pull request merged**
