### PR TITLE
Fixed minimizing and reopening the app while on enter name dialog

### LINKED ISSUE #5549: Form closes and two instances of Identify User form created after minimizng the app while on enter name dialog
#### ODK Collect version
2023.1.2, the master version 1f9155c7f1f6c1d91532993fd45cc9b68270124a
#### Android version
10, 13
#### Device used
Redmi 9T, Pixel 6A
#### Problem description
When a user minimizes the app while on enter identity dialog in the Identify User form, the form closes. After reopening and filling the form there are 2 instances created of the form (one is without xml and csv files in it).
If don’t keep activities is on, after minimizing the app the form doesn’t close (the user goes back to the enter name dialog – no need to reopen the form to fill it in) there are sill 2 instances created.
#### Steps to reproduce the problem
1. Go to Identify User form.
[identify-user-audit.xml.txt](https://github.com/getodk/collect/files/11222028/identify-user-audit.xml.txt)
2. When you see "Enter identity” dialog minimize the app.
3. Go back to the app.
4. Go to Fill Blank Form and reopen the form.
5. Fill and save the form.
6. Go to Form Management and the project files and check the created instances of the form.
#### Expected behavior
The form shouldn’t close after minimizing the app and I don’t know why there are 2 instances of the form when the form was/wasn’t reopened (without/with don’t keep activities on).

### PR DESCRIPTION
**Pull request by grzesiek2010**
Closes #5549

#### Why is this the best possible solution? Were any other approaches considered?
When we reopen the app (with a started form) the `onResume` , method from `FormFillingActivity` is called and it checks if `formController` object s null:
```java
if (formController == null) {
    // there is no formController -- fire MainMenu activity?
    Timber.w("Starting MainMenuActivity because formController is null/formLoaderTask is null");
    startActivity(new Intent(this, MainMenuActivity.class));
    exit();
    return;
}
```
if so it closes the form assuming something went wrong.
The thing is that if [Enumerator identification](https://docs.getodk.org/form-audit-log/#enumerator-identification) is enabled we set `formController`  only after passing username and navigating to the form. That's why such forms used to be closed after reopening the app and performing `onResume`.

I can't see any reason why we shouldn't set `formController` earlier to fix this bug. That's what I did!
Another solution would be to keep it as it is and add another check in `onResume` to prevent closing the form if `formController` is null when we are waiting for username. It should work as well but one another check is what I like less.

**[EDIT] The first solution turned out to be buggy see: https://github.com/getodk/collect/pull/5888#issuecomment-1895320643 so I had to use the second one.**

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
Forms that use [Enumerator identification](https://docs.getodk.org/form-audit-log/#enumerator-identification) should be tested because they are at risk. There should be no difference in the behavior of other forms (without that option enabled) so I believe they are safe. It's difficult to tell what might be broken (if anything) in the forms with Enumerator identification](https://docs.getodk.org/form-audit-log/#enumerator-identification) so please be creative.

#### Do we need any specific form for testing your changes? If so, please attach one.
No.

#### Does this change require updates to documentation? If so, please file an issue [here]( https://github.com/getodk/docs/issues/new) and include the link below.
No.

#### Before submitting this PR, please make sure you have:
- [x] added or modified tests for any new or changed behavior
- [x] run `./gradlew connectedAndroidTest` (or `./gradlew testLab`) and confirmed all checks still pass
- [x] added a comment above any new strings describing it for translators
- [x] verified that any code or assets from external sources are properly credited in comments and/or in the [about file](https://github.com/getodk/collect/blob/master/collect_app/src/main/assets/open_source_licenses.html).
- [x] verified that any new UI elements use theme colors. [UI Components Style guidelines](https://github.com/getodk/collect/blob/master/docs/CODE-GUIDELINES.md#ui-components-style-guidelines)

### CODE REVIEW

**Review by seadowg — APPROVED** [review]
I'm pretty worried moving `formLoaded` will cause logs to be different (we might end up with a `form resume` we don't want for instance) but I've not found a case as of yet. I do definitely prefer the new code though!

For the moment, I'm happy to accept, but let's not merge until we've got to "behaviour verified" for this one.

**Comment by dbemke** [comment]
I'm not sure what is the expected behavior - if I open the Identify User form and while on the dialog "Enter identity" I press the back button (there isn't a dialog in which I can discard changes) and the form is closed, in the file directory a file for this opened form is created (the file is empty). Is it expected that this type of form creates a file in the directory each time the form is opened?  OR maybe the dialog to save or discard changes is missing?

**Comment by dbemke** [comment]
Another case if I minimize the app while on the "Enter identity" and go back to the app, the form is closed and the file in the directory is also created. What is the expected result after changes in the PR after minimizing the app - should the form close?

**Comment by grzesiek2010** [comment]
> I'm not sure what is the expected behavior - if I open the Identify User form and while on the dialog "Enter identity" I press the back button (there isn't a dialog in which I can discard changes) and the form is closed, in the file directory a file for this opened form is created (the file is empty). Is it expected that this type of form creates a file in the directory each time the form is opened? OR maybe the dialog to save or discard changes is missing?

We don't need to add any dialog. The empty directory is of course not needed but it doesn't cause any problems plus it's not even visible to a user. I think you can file a separate issue for removing it (or maybe rather creating later after passing the identity.

> Another case if I minimize the app while on the "Enter identity" and go back to the app, the form is closed and the file in the directory is also created. What is the expected result after changes in the PR after minimizing the app - should the form close?

It should be restored. I've tested the fix again now and it looks like it works like that. Please double check maybe you were on master branch?

**Comment by dbemke** [comment]
> Please double check maybe you were on master branch?

Yes, I used the master branch as now after the changes by default when there's label needs testing we test on the master branch. If for some reason you would like us to test a PR before merging please be specific which version you would like us to test and add this info in the risk section.

**Comment by grzesiek2010** [comment]
> Yes, I used the master branch as now after the changes by default when there's label needs testing we test on the master branch. If for some reason you would like us to test a PR before merging please be specific which version you would like us to test and add this info in the risk section.

This pr is not merged as you can see. @seadowg wanted to test it first:
>  but let's not merge until we've got to "behaviour verified" for this one.

so you have to test the pr using its branch.

**Comment by dbemke** [comment]
In the apk in this PR when don't keep activities setting is enabled minimizing the app when on "Enter identity" dialog and going back to the app results in being moved to the first question so the "Enter identity" isn't shown and possible to fill in. The issue doesn't occur on the store version.
**Steps to reproduce the problem**
1. In the device settings don't keep activities is enabled.
2. Go to Identify User form.
3. When you see "Enter identity” dialog minimize the app.
4. Go back to the app.
  
 After going back to the app the user sees the first question

**Expected result**
After minimizing the app on "Enter identity" dialog and going back to it, the user should still be on the same dialog (not the first question)

**Comment by grzesiek2010** [comment]
@dbemke please try now, I hope it should be fixed.

**Comment by dbemke** [comment]
After the change the dialog doesn't disappear. There's only one thing which I'm not sure if it can be prevented. When don't keep activities setting is enabled. When in the Identify user form while on the "Enter identity" dialog I enter something in the field, minimize the app and go back, the filled identity disappears (need to enter it again). It works the same on the store version so it's not the PR but I'm not sure if should file an issue for that or the way it works is fine?

**Comment by grzesiek2010** [comment]
Yeah, I think a separate issue would be ok in this case.

**Comment by dbemke** [comment]
**Tested with Success!**

Verified on Androids: 10

**Verified cases:**
- issue #5549 doesn't occur
- Identify User form and track changes form
- regression checks in audit logs
- don't keep activities enabled and disabled
- other issues found while testing will be files separately

**Comment by srujner** [comment]
**Tested with Success!**

Verified on Androids: 13

**Pull request merged**
