### PR TITLE
'Get Selected' button is disabled although there is selected form after canceling downloading process

### LINKED ISSUE #330: "Get Selected" button is disabled although there is selected form after canceling downloading process.
#### Software and hardware versions 
Discovered on Collect v1.4.12, Android v5.0.1, Samsung Galaxy S4

#### Problem description
"Get Selected" button is disabled although there is selected form after canceling downloading process.

#### Steps to reproduce the problem
1. Click on "Get Blank Form" button from main menu.
2. Select one form eg. "Birds".
3. Click on "Get Selected" button.
4. Cancel downloading process.

#### Actual behavior
The form is still selected but "Get Selected" button is disabled.

#### Expected behavior
There are two options:
1. The form is still selected (as now) and "Get Selected" button is enabled.
2. The form is not selected and and "Get Selected" button is disabled (as now)

### PR DESCRIPTION
**Pull request by grzesiek2010**
This PR is in reference to resolve #330

### CODE REVIEW

**Review by lognaturel — CHANGES_REQUESTED** [review]
I don't think that this is the behavior that a user would expect. I think the form should remain checked and the 'Get Selected' button should be enabled. Did you see a reason not to do that?

**Comment by grzesiek2010** [comment]
No but I added two options in https://github.com/opendatakit/collect/issues/330 and no one said that one of those is better. Ok I'll change this.

**Comment by lognaturel** [comment]
Ah, yes, I missed that. :/

**Comment by grzesiek2010** [comment]
Done.

**Review by lognaturel — APPROVED** [review]

**Pull request merged**
