### PR TITLE
Replced the ic_save_black_36dp png with vector graphic

### LINKED ISSUE #2046: Replace the ic_save_black_36dp (png) with scalable vector
#### Software and hardware versions 
Collect v1.14.0

#### Problem description
Replace the ic_save_black_36dp (png) with scalable vector

We already have such a vector icon and we sue it in FormEntryActivity so there is no need to add a new one.

@opendatakit-bot label "quick win"

### PR DESCRIPTION
**Pull request by CRMinges**
Closes #2046 

#### What has been done to verify that this works as intended?
- Checked the icons that the vector graphic replaces to ensure they
  were black save icons.
#### Why is this the best possible solution? Were any other approaches considered?
- Relied upon the grey save vector graphics that already were being 
  utilized in the code, and switched the color.
#### Are there any risks to merging this code? If so, what are they?
- No, there should not be any risks. Changing are predominantly 
  aesthetic.
#### Do we need any specific form for testing your changes? If so, please attach one.
- No.

### CODE REVIEW

**Comment by grzesiek2010** [comment]
@CRMinges your build failed but it looks like a random fail. COuld you click on `Rerun job` button to try again?

**Comment by CRMinges** [comment]
@grzesiek2010 Is that the `Rerun job with SSH` button on the circleci page for build_debug? If so, it is grayed out and says I need write permissions to trigger builds.

**Comment by grzesiek2010** [comment]
> @grzesiek2010 Is that the Rerun job with SSH button on the circleci page for build_debug? If so, it is grayed out and says I need write permissions to trigger builds.

Yes, are you logged in using your GitHub account?

**Review by lognaturel — APPROVED** [review]

**Comment by CRMinges** [comment]
@lognaturel @grzesiek2010 I want to thank you for helping me make my first PR for an open-source project. I apologize for any inconvenience due to the build issues, and was hoping to get some clarification on the topic. Prior to opening the pull request, I followed the contributing guidelines and ran `./gradlew lint` and `./gradlew checkstyle`. Both of these builds were successful in Android Studio, and I am curious why my build failed after opening the PR? Is there anything else I should keep in my for my next PR?

**Comment by grzesiek2010** [comment]
You should run:
`./gradlew lint checkstyle pmd findbugs`
if everything is ok you can open your pr. Sometimes builds fail randomly and running the build again usually helps. For example today I saw there was a problem with builds but not on our side.

**Comment by lognaturel** [comment]
@grzesiek2010 is absolutely right, there was nothing wrong with your build, the continuous integration server just ran out of memory.

🤔 I notice that the contribution guide is out of date and only mentions `lint` and `checkstyle`. @CRMinges  would you like to issue a pull request to update that to suggest running `./gradlew lint checkstyle pmd findbugs` as @grzesiek2010 said?

**Comment by CRMinges** [comment]
@lognaturel I would be happy to. It should be a very quick fix, would you still like me to create an issue for it?

**Comment by lognaturel** [comment]
Awesome! I think that for README changes it's ok to put in a PR without an issue.

**Comment by CRMinges** [comment]
@lognaturel do the save icons still need to be converted to vectors for 36dp? I have seen a few recent PR's for changing icons to vectors for given activities, such as #2079 . If there is still a desire to switch from png to vector, I now have time again to work on it.

**Comment by grzesiek2010** [comment]
Theoretically, that icon should be fixed in https://github.com/opendatakit/collect/pull/2079 as you noticed but it isn't like some other icons as well. That pull request is not good and it's been six days without any answer, but let's wait...

**Comment by CRMinges** [comment]
@grzesiek2010 alright, sounds good, thanks for the response.

**Pull request merged**
